"""Life, keeping, real casket state and native Curios dependency contracts."""
from catalog_common import *
from collect_twilight_charms import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed TF4.8.3345, raw MC1.21.1, exact NeoForge21.1.244 and selected installed Curios9.5.1 dependency bytes. Static research only; no runtime boss/L2, fixes, Stage/production or Phase6/7. Existing Phantom armor stats are protected; this section closes its real retention producer. Native HP writes are described as installed TF behavior, never added or simulated.',
      'death_order':'CharmEvents.setup registers applyCharmOfLife at HIGHEST LivingDeathEvent, applyKeepingAndCasket at HIGH, returnItemsOnRespawn at ordinary priority. Each death handler explicitly requires !event.canceled, server, Player, !FakePlayer, !isCreative and !isSpectator. Life can cancel event before Keeping; same-priority/other-mod ordering is not invented. Native Living.hurt ordinarily checks Totem before die; successful native Totem prevents death event and charm consumption. Totem rejects BYPASSES_INVULNERABILITY, searches hands and has distinct effects/cures; TF Life handler has no DamageSource/tag check, so that tag alone does not veto Life once death event is reached. Exact244 ServerPlayer.die emits ENTITY_DIE game event then onLivingDeath; cancellation skips subsequent ordinary death/drops. No universal protection from removal/discard or pathways that never post eligible event.',
      'life':'handleCharmOfLife tries LifeII inventory, then equipped Curio II; only if neither succeeds tries LifeI inventory then Curio I. Consumes one. LifeI setHealth8 (native clamp to max), then Regeneration100 ticks amplifier0. LifeII setHealth(getMaxHealth), then Regeneration600 amplifier3, Resistance600 amplifier0, FireResistance600 amplifier0. Direct native setHealth, not heal and not damage cancellation before HP; no DamageSource for restoration. Does not explicitly clear existing effects/fire, grant absorption, modify invulnerableTime or restore hunger/SHP. addEffect native eligibility/merging/events/return behavior remains; returns true/cancels death even if an effect is rejected. Native Regeneration periodically heals1 with 50>>amplifier cadence (50/6 ticks here), subject to max/current health and native healing hooks, not guaranteed total HP. Higher LifeII priority can prefer Curio II over inventory I. Native packet/stat after activation, no extra item cooldown or charge field.',
      'consume':'TFItemStackUtils.consumeInventoryItem scans armor list first, then all36 main inventory slots, then offhand, stopping on first exact item match, shrink1. No held/hotbar-only condition for consuming charm/casket, no ender chest, bags or nested-container search. saveItemToTag true writes full pre-shrink stack to PlayerPersisted.CharmStack for later animation, not item reimbursement; Life inventory uses false, Keeping true. It also reads minecraft:block_state property damage if present, numeric parse else0, otherwise TF CASKET_DAMAGE component, into CasketDamage; normal casket has0. It does not clear old CasketDamage when neither property/component exists. Creative/spectator gate is in death handler, no permission/HP/source predicate in helper.',
      'keeping':'Only eligible uncanceled death with keepInventory=false runs handleCharmOfKeeping followed by stockKeepsakeCasket. Tries KeepingIII against all36 items, then II against real subList0..9 hotbar. Each candidate eligibility copies selected list plus armor/offhand, ignores stacks matching that SAME charm, and returns false if all remaining entries empty; otherwise tries inventory consumption then Curio. Other items including another tier count. Successful III transfers all36 plus armor/offhand; II transfers hotbar into same0..8 and armor/offhand. Item copies moved into temporary Inventory, original slots emptied. No XP/food/health/SHP preservation here. Curios-only contents do not satisfy base-list eligibility. Native later drop/vanishing logic sees the remaining inventory, not moved stacks.',
      'keeping_one':'If III/II did not succeed and selected index is valid hotbar, installed bytecode calls NonNullList.of(selectedStack,new ItemStack[0]) for KeepingI. Native of uses Arrays.asList(varargs) with first argument only as default value; the passed list therefore has SIZE ZERO. This does not contain or alias the selected inventory slot. Candidate eligibility sees only armor/offhand; a selected item alone cannot trigger KeepingI. If other eligible armor/offhand exists and charm is available, I consumes one and transfers armor/offhand but NO selected/main slot. This is proven by caller and raw native implementation, not assumed intended behavior or a runtime test; no fix made.',
      'reserve_casket':'keepWholeListAndCheckCasket copies each transferred stack. III starts skipCasketCheck=true so retains all selected caskets. Lower tiers reserve the first casket encountered across chosen items then armor then offhand for later death placement: if count>1 retain all but1 and leave original copy count1; if count1 leave original untouched, no retained copy. Further caskets transfer normally. Boolean result threads reservation across lists. Remaining unselected inventory may contain caskets too; actual consumption later scans normal armor/items/offhand order. No global guarantee that reserved casket is the exact consumed object.',
      'tag_retention':'After charm attempts, independently scans all36 items, armor and offhand for twilightforest:kept_on_death, copying to same temporary Inventory slots and clearing originals. Installed tag exactly TowerKey, PhantomHelmet, PhantomChestplate. No charm required, no worn-only restriction and no enchantment/curse gate; still subject to eligible death and keepInventory=false outer condition. Armor stats stay protected prior package. If resulting temporary Inventory nonempty, native Inventory.save writes TFCharmInventory in PlayerPersisted. Full main/armor/offhand structure retains slot numbers; no accessory/backpack search. No explicit keep-existing TFCharmInventory merge here, so a newly saved nonempty result replaces that key.',
      'persistence_return':'getPlayerData creates PlayerPersisted CompoundTag inside native persistent entity data. Exact244 ServerPlayer.restoreFrom copies old PlayerPersisted before PlayerClone; subsequent ordinary non-End-conquered ServerPlayer PlayerRespawnEvent runs returnStoredItems. TFInventory loadNoClear parses Slot byte&255: main0..35, armor100..103, offhand150. Empty valid destination gets saved stack; occupied destination queues saved stack for Inventory.add. Native add may merge/partially insert or fail when full; TF ignores return and neither drops nor retains leftovers, then clears/removes TFCharmInventory. Thus collision preserves existing slot but does not guarantee all saved items survive full inventory. Invalid-slot/empty parsed stacks skipped. No blind inventory clear. If CharmStack key exists, parsed stack sent in Keep animation packet/stat then key removed; this is independent of saved inventory presence and does not reimburse consumed charm. End-return respawn skips this restoration.',
      'casket_gate':'After Keeping/tag moves, stockKeepsakeCasket checks current player Inventory.hasAnyMatching(nonempty item not KeepsakeCasket). If true, consumes one genuine casket through normal inventory helper; no casket means returns. Consumption happens BEFORE placement/validation, with no refund on later failure. If false (only caskets/empty left), loops normal Inventory slots, loads any TFCharmInventory into temp Inventory, attempts add(copy of each casket), ignores add return, empties original slot and re-saves key. This preserves casket-only remainder when space allows without placing a block; full storage can lose uninserted remainder. No Curios/bag items qualify gate or enter casket.',
      'casket_place':'Uses player block position. Y<dimension.minY+2 ->minY+2; else Y>dimension.logicalHeight ->logicalHeight-1 (absolute comparison, not minY+logicalHeight). Starts one below then increments until canBeReplaced; no explicit upper-bound/search-length/LOS/permission/BreakEvent guard or collision safety check in TF loop. Reads fluid at destination via BlockLoggingEnum.getFromFluid and uses its native enum state. Casket damage from persisted CasketDamage else0; state BREAKAGE0..2. Facing from Direction.from2DDataValue(random.nextInt3). Random float<=.15: damage>=2 replaces with SkullChest using shared state, else increments casket damage. Native BlockState rejects out-of-range component value; no clamp in this path. setBlockAndUpdate false or unexpected missing/wrong BE logs and returns with casket already consumed, no inventory movement/refund at those failures. No fabricated placement/guaranteed success.',
      'casket_storage':'On successful SkullChestBlockEntity destination (including Keepsake subclass), owner=Player ResolvableProfile iff config casketUUIDLocking, else null; pinned installed common config false. Stores custom name then45-slot inventory: reversed live armor4, four empty placeholders, offhand1, main inventory9..35 then hotbar0..8. Copies list references into NonNullList.of(EMPTY,45-array), clearing actual armor/offhand/items only after adding those references; resulting contents survive clear. Native fixed-size list clear fills EMPTY. Removes CasketDamage after successful transfer. Casket is world storage; no HP/SHP/DamageSource or health rescue, no XP capture. Native block entity saves contents/optional owner via codecs and native loot-table handling. No respawn auto-return of casket contents.',
      'casket_access':'SkullChestBlockEntity45-slot GENERIC_9x5 menu. owner null uses ordinary container checks; owner nonnull allows owner OR permission>=3 to canOpen/stillValid, then native lock/distance checks. Source-proven different BreakEvent predicate: nonempty owned SkullChest cancels when (!permission3 OR !sameOwner), so only a permission3 owner passes that specific protection; ordinary owner and nonowner operator each fail. Empty/unowned chests bypass that TF cancel predicate. Native BreakEvent/protection rules remain. Both block types return explosion resistance Float.MAX_VALUE and canEntityDestroy=false, not absolute immunity to arbitrary world removal. On block replacement, native drops contents; ordinary server noncreative playerWillDestroy with doBlockDrops spawns separate block item modified by damage, while contents drop separately, not inside carried block item. Owner locking is not an HP defense.',
      'casket_repair':'Keepsake BREAKAGE integer0..2. useItemOn only if multi-logged block AIR or fluid nonEMPTY; holding KeepingIII and damage>0 ->stack.consume1 native creative rules, setBlockAndUpdate damage-1 (return ignored), repair sound/sided result. No owner authorization or explicit server-only guard inside this repair branch; menu opening has separate native owner checks. Other admitted uses open menu on server; solid logged stone/obsidian/basalt returns default interaction. Drop/clone item carries CASKET_DAMAGE if>0; setPlacedBy directly sets component value default0, no extra clamp. No repair via Life/I/II, no HP healing. Multi-logging/native fluid behavior and ordinary container operations remain, not new custom damage.',
      'curios_native':'Twilight common setup checks ModList curios then registers keepCurios listener and real item capability for five charms; installed data/curios/tags/item/charm.json lists all five. Actual native equipped-slot availability/eligibility remains. findAndConsumeCurio uses CuriosApi.getCuriosInventory->installed mixin capability lookup->handler.findFirstCurio(item), then if Optional present saves full pre-shrink stack into CharmStack and shrink1. Current installed Curios9.5.1 search uses real equipped stacks, not cosmetic, includes only active slots unless active-state list lacks entry, in handler slot order. It uses per-item same-gameTime cached SlotResult; TF does not re-test empty/count/item after Optional. Thus a same-tick cached emptied reference reaching save can throw native Cannot encode empty ItemStack; no runtime reproduction/fix or guaranteed repeated rescue claimed. Actual valid nonempty first-match consumption is legitimate positive path. Handler visibility is not an activation prerequisite.',
      'curios_keep':'TF keepCurios on real DropRulesEvent: server Player plus contains CharmStack AND contains TFCharmInventory AND list nonempty. No charm-tier/type/just-consumed validation. Iterates handler.getSlots and adds identity predicates stack==handler.getEquippedCurios().getStackInSlot(i) ->ALWAYS_KEEP. Native getEquippedCurios combines ordinary stacks only; cosmetics are not the matched equipped objects. Actual Curios playerDrops HIGHEST LivingDropsEvent posts DropRules, scans ordinary and cosmetic slots, last matching override wins, ALWAYS_KEEP leaves stack instead of remove/drop/vanishing processing; default/other rule and server keepCurios config remain. Other listeners may add later overrides, no total modpack order claim. Native PlayerClone copies old retained Curios tag into new handler. Twilight does not copy Curios items into its own TFCharmInventory or casket.',
      'curios_tokens':'Inventory Life uses saveItemToTag=false, while Curio Life unconditionally saves CharmStack through shared findAndConsumeCurio. Life cancellation does not clear that token or create TFCharmInventory. It can remain until later respawn; later nonempty tagged-gear/keeping storage can satisfy TF keepCurios even if token came from Life, because no type/freshness check. Conversely Keeping consumed but empty TFCharmInventory does not trigger accessory keep. Death/respawn packets/stat follow actual persisted keys, so Keep animation/stat may use saved Life stack. These are exact shared-state predicates, not assumed intended consumption semantics.',
      'visual_exclusion':'SpawnCharmPacket is registered clientbound; packet/anonymous handler only item activation or client CharmEffect plus particles/sound. CharmEffect follows owner eye/orbit, expires tickCount>200 or owner dead/invisible, has empty save/sync bodies and no HP/hurt/source/retention call. It is visual, not a summon, shield, resurrection source or extra gameplay mechanic. Rendering config does not change resource/HP behavior.'
    }
    E='events/CharmEvents';U='util/TFItemStackUtils';K='block/KeepsakeCasketBlock';S='block/SkullChestBlock';B='block/entity/SkullChestBlockEntity';C='compat/curios/CuriosCompat';I='init/TFItems'
    nxt='Continue Task C with Travellers gear/components/modifiers and their installed ASM/event control paths; then remaining utility/food, passive entities, environmental hazards and10 unfinished custom DamageTypes, complete nested ASM/compatibility/source exclusions before R2f8 and final Twilight promotion. IceAndFire only after COMPLETE Twilight pushed/live verified. No runtime boss/L2/Stage/production/fixes/Phase6/7.'
    data=dict(slug='charms',checkpoint_short='r2f8n',checkpoint='R2f8n-charms-complete',decision='TWILIGHT_CHARMS_CASKETS_SEMANTIC_REVIEW_COMPLETE',starting_sha='7449fff57d659e0bfd004e6fd5c9f4b1c78a5eaf',previous_checkpoint='R2f8m-equipment-complete',previous_draft='partial-drafts/twilightforest-r2f8m-partial.json',facts=facts,packages=[],paths=[],new_damage_types=0,full_classes=FULL,limited_classes={U:['consumeInventoryItem','sortArmorForCasket','sortInvForCasket','loadNoClear'],C:['registration/consumption/keepCurios and lambdas'],'events/EntityEvents':['setup','onCasketBreak'],'TwilightForestMod':['Curios setup/register'],'config/TFConfig':['common casket setting'],'enums/BlockLoggingEnum':['casket fluid conversion']},registration_classes=[I,'init/TFBlocks','init/TFBlockEntities','init/TFDataComponents','events/RegistrationEvents','TwilightForestMod'],closure_checklist=['death_priority_and_native_totem','eligible_Player_only','Life_actual_HP_effects','inventory_search_order','Keeping_III_II_I','empty_varargs_proof','casket_reservation','tagged_Phanthom_TowerKey','persist_clone_respawn','full_inventory_failure','casket_before_placement_cost','dimension_search_and_damage','45_slot_storage','owner_open_vs_break_predicate','repair_component_lifecycle','installed_Curios_consumption','Curios_drop_clone_identity','shared_CharmStack_token','visual_exclusion'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus Charms of Life/Keeping, Phantom/TowerKey retention, real Keepsake Casket storage/access/repair and selected installed Curios delivery/drop/clone dependency. Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=30,new_used_profiles=0,reviewed_profiles_after=30,remaining_profiles=10,remaining_disposition='Other actual custom caller profiles unfinished, not unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    life=pkg('charms_life','Charms of Life native death veto and restoration','BINARY_MECHANIC',['death_order','life','consume','curios_native','visual_exclusion'],[E,U,C],{'I_hp':8,'I_regeneration':[100,0],'II_hp':'max','II_regeneration':[600,3],'II_resistance':[600,0],'II_fire_resistance':[600,0],'consumed':1},['eligible uncanceled server Player death','II before I','inventory then Curio per tier','native effect eligibility'],'Totem-like death veto with inventory/resource/native HP and effect differences.','Native lethal hit with genuine Life charm',['Totem-first, bypass tag, empty inventory, Curio active/cache and no effect-clear controls'])
    keeping=pkg('charms_keeping','Keeping tiers native inventory transfer','CUSTOM_RESOURCE',['death_order','consume','keeping','keeping_one','reserve_casket'],[E,U],{'III_main_slots':36,'II_main_slots':9,'I_actual_main_slots':0,'consumed':1},['keepInventory false','eligible contents','III before II before I','actual empty varargs','casket reservation'],'Custom death inventory storage; exact TierI list differs from intended selected-slot reading.','Native death with KeepingIII/II/I',['Armor/offhand, only charms, selected-only TierI, casket reservation and Curio source'])
    tagged=pkg('tagged_death_retention','Phantom armor and Tower Key native retention','CUSTOM_RESOURCE',['death_order','tag_retention'],[E],{'native_tag_items':['tower_key','phantom_helmet','phantom_chestplate']},['eligible death','keepInventory false','actual item tag','normal main/armor/offhand'],'Tag-driven native retention without consuming charm.','Native death carrying Phantom armor/Tower Key',['Worn versus carried/offhand, curse/empty/tag controls'])
    restore=pkg('charms_persisted_return','Charm inventory persistence and respawn restoration','CUSTOM_RESOURCE',['persistence_return','tag_retention','curios_tokens'],[E,U],{'armor_slot_base':100,'offhand_slot_base':150},['PlayerPersisted copy','non-End ServerPlayer respawn','slot validity','occupied-slot native add'],'Persistent keyed resource replay with explicit full-inventory failure behavior.','Native death then actual respawn',['Save/load, occupied/full inventory, End-return, CharmStack-only token'])
    casket=pkg('casket_death_storage','Keepsake Casket native death placement and storage','CUSTOM_RESOURCE',['death_order','consume','reserve_casket','casket_gate','casket_place','casket_storage'],[E,U,S,K,B],{'size':45,'wear_chance_inclusive':.15,'max_breakage':2,'consumed_before_placement':1},['noncasket remainder','genuine casket','replaceable search','real setBlock/BE success'],'World inventory storage following death, not HP resurrection.','Native eligible death with genuine casket and inventory',['Keeping interactions, only-caskets, placement failure, Y bounds, damage states and persisted contents'])
    access=pkg('casket_native_protection','Casket access, break and native world protection','BINARY_MECHANIC',['casket_access','casket_storage'],[S,B,'events/EntityEvents'],{'operator_level':3,'explosion_resistance':'Float.MAX_VALUE','installed_owner_locking':False},['optional owner','GUI owner OR operator','nonempty break owner AND operator','native container rules'],'Separate native ownership and environmental predicates.','Native placed death casket interaction',['Owner/operator/nonowner, empty/nonempty, config, break/drop and explosion controls'])
    repair=pkg('casket_repair_state','Casket damage component and KeepingIII repair','CUSTOM_RESOURCE',['casket_repair'],[K,'item/KeepsakeCasketItem'],{'breakage_range':[0,2],'repair_consumption':1,'repair_delta':-1},['III exact item','damage>0','non-solid logging','native consume/placement state'],'Native block/item state resource transition.','Native KeepingIII use on damaged casket',['Creative, locked owner, logging, clone/drop/place and invalid component boundary'])
    curio=pkg('charms_curios_retention','Twilight Charms native Curios consumption and retention bridge','CUSTOM_RESOURCE',['curios_native','curios_keep','curios_tokens'],[C,E,'TwilightForestMod'],{'native_dependency':'Curios9.5.1','override':'ALWAYS_KEEP'},['installed bridge','real active equipped search','CharmStack plus nonempty storage','identity predicate','native drop/clone'],'Twilight-owned bridge through actual accessory API, not blanket inventory capture.','Native equipped charm and genuine death/drop/respawn',['Cosmetic/inactive, same-tick cache, token freshness, empty storage and later overrides'])
    data['damage_profiles']=[]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:charms_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' using genuine native inventory/accessory/death/block callbacks; future fixture only, no runtime test or synthetic damage.',future_controls=controls))
    rows=[
      ('life_i','Native LifeI inventory lethal hit',['death_order','life','consume'],[life],[E,U],['PASSIVE_ITEM'],['HP8 clamp','Regen100/0','consume1','no negative-effect cure']),
      ('life_ii','Native LifeII and mixed-tier inventory',['life','consume'],[life],[E,U],['PASSIVE_ITEM'],['max HP','three600-tick effects','II priority']),
      ('life_source','Native Life source and eligibility controls',['death_order'],[life],[E],['PASSIVE_ITEM','OTHER'],['Totem first','bypasses_invulnerability not TF veto','Fake/creative/spectator/cancel']),
      ('life_curio','Native equipped active Life charm',['life','curios_native'],[life,curio],[E,C],['ACCESSORY_PROC'],['real slot','II Curio before inventory I','noncosmetic/active','same-tick cache']),
      ('keep_iii','Native KeepingIII all inventory',['keeping','consume','reserve_casket'],[keeping],[E,U],['PASSIVE_ITEM'],['36+armor+offhand','only-current-charm eligibility','all caskets retained']),
      ('keep_ii','Native KeepingII hotbar',['keeping','reserve_casket'],[keeping],[E],['PASSIVE_ITEM'],['real0..8 sublist','armor/offhand','one casket reserve']),
      ('keep_i','Native KeepingI selected-slot control',['keeping_one','keeping'],[keeping],[E],['PASSIVE_ITEM'],['empty varargs size0','selected-only no consume','armor/offhand only when eligible']),
      ('keep_curio','Native equipped Keeping charm',['keeping','curios_native','curios_keep'],[keeping,curio],[E,C],['ACCESSORY_PROC'],['base contents required','inventory charm first','active equipped match']),
      ('keep_negative','Native Keeping priority and negative death cases',['death_order','keeping'],[keeping],[E],['PASSIVE_ITEM'],['Life cancellation','keepInventory true','only charms/no eligible items','tier ordering']),
      ('reserve','Native lower-tier casket reservation',['reserve_casket'],[keeping,casket],[E],['PASSIVE_ITEM'],['one across lists','multi-count split','actual consume order']),
      ('phantom_worn','Native Phantom worn retention',['tag_retention'],[tagged],[E],['ARMOR_PROC'],['no charm','same armor slots','death eligibility']),
      ('tag_carried','Native TowerKey/Phantom carried and offhand retention',['tag_retention'],[tagged],[E],['PASSIVE_ITEM'],['actual tag','no worn-only gate','no curse filter']),
      ('respawn','Native stored inventory respawn',['persistence_return'],[restore],[E,U],['OTHER'],['PlayerPersisted copy','slot bytes','not End return']),
      ('respawn_collision','Native occupied/full respawn inventory',['persistence_return'],[restore],[U,E],['OTHER'],['preserve existing slots','native add return ignored','no overflow drop/retry']),
      ('respawn_save','Native death-storage save/load and token-only replay',['persistence_return','curios_tokens'],[restore,curio],[E,C],['OTHER'],['persistent keys','Keep packet/stat','no charm reimbursement']),
      ('casket_death','Native death casket with inventory',['casket_gate','casket_place','casket_storage'],[casket],[E,U,K,B],['PASSIVE_ITEM','ENVIRONMENT'],['consume before placement','45-slot layout','actual BE success']),
      ('casket_only','Native only-caskets remainder',['casket_gate'],[casket],[E],['PASSIVE_ITEM'],['no world placement','merge saved inventory','ignored full add']),
      ('casket_failure','Native casket placement boundary/failure',['casket_place'],[casket],[E],['ENVIRONMENT'],['dimension min/logical Y','replaceable loop','cost no refund','setBlock/BE failure']),
      ('casket_damage','Native worn casket death state',['casket_place','casket_storage'],[casket],[E,K],['PASSIVE_ITEM','ENVIRONMENT'],['<=.15 random','0..2','final SkullChest transition']),
      ('casket_save','Native casket world persistence',['casket_storage'],[casket],[B],['ENVIRONMENT','OTHER'],['contents/owner codec','no auto-respawn return','no XP']),
      ('casket_gui','Native owner/operator casket access',['casket_access'],[access],[B],['OTHER'],['owner OR operator','native lock/distance','unowned current config']),
      ('casket_break','Native nonempty owned casket break',['casket_access'],[access],[S,'events/EntityEvents'],['OTHER','ENVIRONMENT'],['owner AND operator','empty/unowned controls','separate block/content drops']),
      ('casket_environment','Native casket explosion/entity removal defenses',['casket_access'],[access],[S],['ENVIRONMENT'],['FloatMAX resistance','canEntityDestroy false','no universal removal immunity']),
      ('casket_repair','Native KeepingIII casket repair',['casket_repair'],[repair],[K],['ACTIVE_ITEM'],['damaged only','consume1 creative rules','ignored set return','no owner gate in repair']),
      ('casket_component','Native casket block/item component cycle',['casket_repair'],[repair],[K,'item/KeepsakeCasketItem'],['OTHER'],['clone/drop/place damage','solid logging negative','invalid state range']),
      ('curios_drop','Native Twilight Curios DropRules bridge',['curios_keep'],[curio],[C],['ACCESSORY_PROC'],['two persisted keys/nonempty list','equipped identity','ordinary vs cosmetic']),
      ('curios_clone','Native kept Curios clone and override controls',['curios_keep'],[curio],[C],['ACCESSORY_PROC','OTHER'],['native drop and clone','last matching override','not casket contents']),
      ('curios_token','Native Life Curio token followed by later retention',['curios_tokens','curios_keep'],[curio,restore],[C,E],['ACCESSORY_PROC','OTHER'],['no freshness/type gate','tag-only saved gear can qualify','empty list negative']),
      ('curios_cache','Native repeated same-tick Curio lookup boundary',['curios_native'],[curio,life],[C,E],['ACCESSORY_PROC'],['cached SlotResult','no TF empty recheck','native save exception boundary','no runtime crash test']),
      ('visual','Native charm animation negative gameplay control',['visual_exclusion'],[life],[E,'network/SpawnCharmPacket','network/SpawnCharmPacket$1','entity/CharmEffect'],['OTHER'],['clientbound only','no HP/source','visual not summon'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-evidence/'+BATCH+'-curios.json','reference-routing/'+BATCH+'.json','twilightforest-charms-caller-scan.json','config-evidence/twilightforest-common.json','reference-evidence/vv-loader-244.json','reference-evidence/twilight-scepter-payloads-244.json','reference-evidence/twilight-equipment-244.json']
    data['exclusions']=['Nine listed complete native bodies plus actual helper/bridge/registration methods are covered; no custom DamageType added.','Selected Curios code proves Twilight dependency contract only; this does not start another catalog family or a runtime compatibility matrix.','TierI empty varargs, full-inventory return loss, pre-placement casket consumption, mismatched break/open predicates and persistent Curio token/cache boundaries remain source-proven behavior without fixes.','CharmEffect/packet visuals excluded as combat payloads; caskets preserve inventory, not HP/SHP/XP.','Travellers, remaining utilities/food/passive entities/hazards10 custom types and complete ASM/compatibility/source closure remain pending; Twilight PARTIAL, zero promoted, REVIEW_REQUIRED0.']
    data['fixture_groups']=['Genuine LifeI/II inventory and active Curio lethal hits with native Totem/event/tag eligibility controls.','Actual Keeping tier slot matrix including empty-list I, charm-only contents, casket reserve and unconditional tagged gear.','Real respawn/persistence with occupied/full slots and independent token/End-return controls.','Native death casket placement/failure/layout/damage/ownership/repair and item/block lifecycle.','Actual Curios consumption, drop override, clone, cosmetics/inactive/cache and shared-token boundaries.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-charms.json',data);assemble('twilightforest-charms.json')

if __name__=='__main__':build()
