"""Reviewed tactical mob AI, native TNT, and Troll rock source contracts."""
from catalog_common import *
from collect_twilight_tactical_mobs import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed TF4.8.3345, raw Minecraft1.21.1 and exact NeoForge21.1.244 are the authority. Static research only. Ordinary mob melee retains native mob_attack (direct=causing mob), effective attributes/enchantments, armor/shield/Resistance/protection/absorption/cooldown/events and native Player difficulty scaling. No runtime HP/SHP/L2/Stage claim. Native hurt true need not mean measurable HP loss. Native control/resource/terrain callbacks are not fabricated damage events.',
      'redcap_body':'Redcap HP20, speed.28, base attack2; Sapper HP30 and base armor2, same speed/base attack. Native finalize populates mainhand iron pick and iron boots; Sapper replaces pick with Ironwood pick and boots with Ironwood boots. Both pickaxes add3 mainhand damage (Iron tier2 or Ironwood tier2 plus pick argument1), so unenchanted equipped mob attack5, not Player tool attack4. Boots supply2 armor/toughness0, yielding Redcap2/Sapper4 total armor. Ordinary spawn equipment enchantments can alter results. Native equipment updates apply attributes; displaying held Flint/TNT temporarily removes the pick modifier. Melee goal priority5 uses speed1 and normal cooldown, not item attack-speed cadence. Default visible Player targeting and retaliation remain. No extra hurt/death/HP phase, fire/TNT immunity, summon or status payload in either body. Saved native equipment persists separately from heldPick helper stack; loaded custom gear can later be replaced by goal stop restoring heldPick.',
      'redcap_shy':'Priority2 RedcapShyGoal has MOVE/LOOK and speed1. isShy is lastHurtByPlayerTime<=0 (native recent-Player-hurt counter); not a permanent pacification flag. Entry requires target, shy, distance3..6 inclusive, target-looking predicate abs((targetYaw-(atan2(dz,dx)*180/pi-90))%360)<60 OR >300. No pitch or new ray trace in this helper. Per-goal lefty=Math.random()<.5 chooses rotation+1 or-1 radian. Destination is a snapshot radius5 around the target at Redcap minY. Continuation needs current target, captured target alive, navigation unfinished, shy, strict3<distance<6 and looking predicate. Tick looks at captured entity30/30; stop clears reference and stops navigation. This higher-priority control can preempt TNT lighting/melee; it does not modify incoming damage or grant immunity.',
      'redcap_avoid':'Priority1 AvoidAnyEntityGoal targets PrimedTnt within own AABB inflated2 XZ/3 Y, alive, sensed LOS, nonallied and native no-creative/spectator filter; selects first candidate, not nearest. MOVE flag. Native DefaultRandomPos.getPosAway is unusually passed the Redcap own position, then candidate must be at least as far from TNT as current Redcap and produce a path. Start speed1; tick speed2 within squared distance49 else1. Continues only while navigation unfinished, not a refreshed fuse/LOS/radius predicate. No disarm, damage or immunity. Primed TNT from any legitimate source can trigger this avoidance.',
      'redcap_light':'Priority3 RedcapLightTNTGoal MOVE/LOOK. canUse first requires canEntityGrief; if delay>0 decrement and reject, else lexicographically scan x/y/z=-8..8 around blockPosition and choose first exact TNT, not nearest/path-reachable check. No target, owner, heldTNT stock, LOS, lit-TNT exclusion or Flint durability predicate. Start equips heldFlint; continue only while stored block remains exact TNT, without rechecking grief permission. Tick looks at integer block coords; distanceSquared to lower corner<5.76 primes via Blocks.TNT.onCaughtFire(defaultState,level,pos,UP,Redcap), swings, replaces block with Air flags2, emits PRIME_FUSE and stops navigation. Otherwise navigates speed1. Stop restores heldPick and sets delay20 canUse evaluations (paused when grief gate fails). No native item use/hurtAndBreak call; Flint is not consumed. Any nearby native TNT block can be ignited, regardless planter, and Redcap/Sapper becomes the TNT owner when this priming route runs.',
      'sapper_plant':'Only Sapper registers priority4 RedcapPlantTNTGoal. Redcap heldTNT starts1 but has no planting goal; Sapper constructor sets3. Goal has no MOVE/LOOK flags and inherits canContinueToUse=canUse; therefore it can coexist with other nonconflicting goals rather than guaranteeing exclusive combat. Entry requires target, nonempty heldTNT, distanceSquared<25, target NOT looking by the shared yaw predicate, canEntityGrief, no PrimedTnt in BBinflate8, and no exact TNT in a +/-5 cube. Start equips the same heldTNT stack; only if current blockPosition is empty, shrink1 BEFORE setBlockAndUpdate(default TNT), sound and BLOCK_PLACE. Placement return ignored; no refund if it fails. Stop restores pick. TNTLeft saves/restores stack count; no native replenishment path. Placing alone is not an explosion or hurt call; higher-priority lighting can subsequently prime it, or ordinary Player/redstone/fire/projectile/explosion mechanics can determine a different owner.',
      'tnt_blast':'Exact244 TntBlock.onCaughtFire delegates server-only native PrimedTnt construction with supplied Living igniter. Redcap route starts fuse80 and owner Redcap/Sapper. Native fuse ticks to0, discards TNT then explodes strength4, fire=false, ExplosionInteraction.TNT. Direct entity=PrimedTnt, causing entity=its Living owner; native DamageSources selects minecraft:player_explosion whenever BOTH are nonnull, even when owner is a mob. With absent owner it selects minecraft:explosion. Both use native explosion pipeline and ALWAYS difficulty scaling on Player victims; no custom TF damage declaration. For native radius4, distance d<=8 and exposure e, request float(((q*q+q)/2)*56+1), q=(1-d/8)*e; normal shouldDamageEntity/ignoreExplosion/nonzero direction and event filters remain. No integer flooring of this1.21 formula. Native explosion armor/shield/Resistance/blast/general protection/absorption apply. Knockback follows independently of hurt return with native exposure, explosion knockback resistance and244 hook; terrain/explosion callbacks are separate. TNT interaction uses native TNT drop-decay rule, not a new canEntityGrief check at detonation, though priming/planting goal entry was grief gated. ExplosionStart/Detonate and block resistance/selection remain. Redcap owner is not excluded from its own blast.',
      'tnt_alternates':'Sapper places ordinary default-state TNT: native Player Flint/fire-charge or a burning eligible projectile supplies that igniter/owner; redstone can prime immediately during placement with null owner. Native wasExploded creates chain TNT with previous explosion indirect Living owner and fuse randomInt(80/4)+80/8=10..29; not another Sapper charge decrement. PrimedTnt saves fuse and block state but not owner, so ordinary unload/save/load can retain fuse yet lose owner and change native source from player_explosion to explosion. restoreFrom during dimension transfer explicitly copies owner; usedPortal substitutes native portal-protecting damage calculator, no custom TF adjustment. These alternate native routes are distinguished from Redcap-owned lighting and preserve source identity rather than assigning planter credit.',
      'kobold_body':'Kobold HP13/speed.28/attack4, registered.8x1.1, ordinary mob melee4 and leap.3. setCanPickUpLoot(true), native powder-snow-walkable tag; no custom armor/shield or damage source. Goals: Float0, panic1, seek bread2 and run-away-with-bread2, leap3, melee4, flock5, stroll6/look7; retaliation1 and custom Player target2. Native TF kobold_pacification_breads contains minecraft:bread directly, not the broader c:foods/bread tag. Standard bread has FOOD nutrition5/saturationModifier.6 and no effect; Kobold is not a Player and gets no native food bar or automatic HP heal from bread.',
      'kobold_pickup':'SeekBreadGoal MOVE: reject while getUseItem nonempty or panicked; nextInt(10)==0 then any tagged ItemEntity in own BBinflate8 and mainhand empty. It navigates to first result at1.2 (not nearest), start and tick; no direct pickup in this goal. Ordinary server Mob.aiStep performs actual pickup only canPickUpLoot/alive/!dead/canEntityGrief, native pickup-reach box, item not removed/nonempty/no pickup delay, wantsToPickUp -> overridden canHoldItem (mainhand empty, tagged bread, !panicked). Kobold.pickUpItem splits excess count into a new dropped ItemEntity, equips exactly1 bread, sets mainhand dropChance2, discards original item, initializes lastEatenBreadTicks1/eatingTime and clears target. It does not call native equipItemIfPossible or setPersistenceRequired here. canTakeItem only permits empty destination MAINHAND plus parent admission. No special interact/feed/tame hook, owner or allegiance change. Native dropped bread, rather than a fabricated held item, is the legitimate pacification control.',
      'kobold_pacification':'Holding a tagged mainhand stack blocks KoboldAttackPlayerTarget.canUse only; inherited continuation and HurtByTargetGoal retaliation are not overridden. Pickup explicitly clears current target once, not a universal permanent inability to attack. RunAwayWhileHoldingBreadGoal extends native AvoidEntityGoal<Player>(radius8,speed1.5/1.5), with canUse gated by held bread; inherited continuation does not repeat that held-item gate. Flock entry is also blocked by bread. On server alive+heldbread, lastEaten counter increments and positive eatingTime decrements, even while panicked; actual canEat requires FOOD component and !panicked. Initial eatingTime Easy400..999, Normal/default200..799, Hard100..699 (base+nextInt600), with decrement possible in the same aiStep as pickup. At<=0, directly calls stack.finishUsingItem; nonempty result replaces mainhand, ordinary bread mutates held stack to empty. It does not use the LivingEntity completeUsingItem/start/finish-event sequence. Native Item->Living.eat applies any actual food effects and consumes1, without Player food resources or guaranteed HP heal. lastEaten>60 plus10% roll resets only munch sound/gameevent/particles; it is not the consumption timer. Both counters save under EatingTimeLeft/TimeSinceBreadLastEaten; PANICKED is synced but not saved. Ordinary native held-item save/load retains bread; counter expiration during panic waits to consume until not panicked.',
      'kobold_panic':'PanicOnFlockDeathGoal MOVE, speed2 for Kobold. Entry if fleeTimer>0 OR any same-runtime-class entity within BBinflate(4,2,4) has deathTime>0, then requires DefaultRandomPos.getPos(5,4) nonnull. It does not require seeing the death, attacker identity or a successful new hit. Start sets fleeTimer40, navigates, sets Kobold PANICKED true. Continue timer>0 && navigation unfinished; tick--, stop subtracts20 and clears PANICKED. Positive residual timer can trigger another start/reset40; not a guaranteed single40 world-tick duration. Default goal cadence, not requiresUpdateEveryTick. Panic suppresses canHoldItem/canEat and higher-priority MOVE can preempt lower movement goals, but does not itself clear target, grant invulnerability, change ownership, or directly subtract HP. Timer and panic resource are not saved; particles are cosmetic.',
      'kobold_flock':'FlockToSameKindGoal has no flags. Bread-holding Kobold fails entry; else nextInt40==0 scans same runtime class in BBinflate(16,4,16), rejects list size>5. Computes average X/Y/Z over returned entities (no special alive/owner/LOS filter here); requires center distanceSquared>=25. Captures center, continuation needs25<=distanceSquared<=256; it does not refresh center or recheck bread, target, panic or count. Start moveTimer0; every10 goal tick callbacks navigation.moveTo(center,speed1). Stop clears center only. No MOVE flag means it may coexist with and issue navigation during other goals; priority alone is not a blanket suppression proof. No summons, shared HP or attack buff. Caller census confines these panic/flock constructors to Kobold in installed TF.',
      'boggard':'Boggard is an unregistered native class, not an established installed delivery source: full TFEntities registration surface and all-TF-class internal/dotted class-reference census find only its own class and no native producer. Its following declared behavior is assessed solely for exclusion, not promoted or exposed as a future native fixture. Boggard body: HP14/speed.28/attack3 and normal mob_attack; Float0, ChargeAttackGoal2(speed1.5,canBreak=false), normal melee3, stroll/look, retaliation and Player target with mustSee=false. Shared ChargeAttackGoal is reused from R2f5: requires captured target distanceSquared16..64, onGround, sensing LOS and nextInt10==0; snapshots targetY and overshoots horizontal position2.1. Start windup15..44 goal callbacks, sets sprinting; movement sprint multiplier1.3 and navigation1.5 are distinct. Boggard does not implement ITFCharger or use MinotaurAxe, so no synced charging flag or axe+7 payload. Even during windup, first squared-distance check <=4*attackerWidth^2+targetWidth sets hasAttacked before ordinary doHurtTarget; false hurt still spends the one attempt. Continuation windup>0 OR unfinished navigation does not refresh target/LOS/range; stop resets target/windup/attempt/sprint. No terrain break because canBreak=false, extra charge DamageType, launch, boss geometry or unique death behavior. The shared charge primitive is already reachable through protected Minoshroom/Minotaur paths; this unused class does not add a legitimate source.',
      'troll_body':'Troll HP30/speed.25/attack7, registered1.4x2.4, ordinary mob_attack7 when melee goal active. Float1, RestrictSun2/FleeSun3, combat4, stroll/look; retaliation ignores Troll class for that goal, visible Player acquisition. Sun avoidance is native navigation behavior, not petrification, forced burning or a custom daylight defense. ROCK_FLAG syncs false initially; rockCooldown starts300..399 and block state initially null. setHasRock server adds/removes transient follow-range+8 by fixed ID (default16->24), then swaps goal: rock=true RangedAttackGoal(speed1,min20,max60,range15), false MeleeAttackGoal(speed1.2,longMemoryfalse). Does not add armor, HP, attack damage or knockback immunity. Ordinary ranged goal distance/LOS/timer controls remain, callbacks not fixed60 ticks regardless distance.',
      'troll_pickup':'Server Troll.tick after super: only !hasRock && target!=null; positive cooldown decrements, else makes one random sample floor(x-2+rand*4),floor(y+rand*3),floor(z-2+rand*4). Outline/no-fluid ray from (blockX+.5,sampledY+.5,blockZ+.5) to sampled center must report the sampled blockPos, and sampled state must be BASE_STONE_OVERWORLD. Native raw tag: stone/granite/diorite/andesite/deepslate/tuff. If accepted, stores state then level.removeBlock(pos,false), ignores result, emits BLOCK_DESTROY. There is no canEntityGrief, EntityUtil.canDestroyBlock, hardness, inventory or drop-return gate in this TF method; ordinary world set/remove behavior still applies. If field rock!=null, setHasRock(true), create owned ThrownBlock with that state, startRiding Troll and addFreshEntity. Failed initial sample retries while cooldown0; cooldown only counts down while target present and no held rock. Rock carrying creates a real projectile entity, not just a render flag.',
      'troll_throw':'performRangedAttack requires hasRock, creates a NEW ThrownBlock(level,Troll,rock), aims target X/Z and minY+height/3 with+.2*horizontalDistance elevation, speed1.6/inaccuracy4-difficultyId. Native constructor spawns at owner eyeY-.1 and sets projectile owner Troll. Adds it, setHasRock(false), discards FIRST passenger only if its type is TF THROWN_BLOCK, resets cooldown300..399, clears rock=null. Throw does not directly hurt and does not release/reuse the carried entity. Passenger attachment height1.25*Troll height and rotation tracking are cosmetic geometry, but carried projectile is ticked by native Entity.rideTick (zero velocity then projectile tick, unless244 pre-tick event cancels), and has no isPassenger guard in impact callback. Thus native carried contact is a separate eligible delivery if the ordinary collision engine actually admits contact; no guaranteed hit count or fabricated launch. Missing/discarded passenger does not itself clear Troll ROCK_FLAG; flags/state drive the later throw.',
      'thrown_hit':'ThrownBlock extends TFThrowable/ITFProjectile, registered1x1 and fireproof, state defaults Stone unless constructor receives nonnull state. Ordinary ThrowableProjectile physics/gravity.03 and impact hook/deflection/collision eligibility apply. onHitEntity calls super; only server Living victim that is NOT any Troll requests twilightforest:thrown_block6. Source factory overload has NO entity or position: direct=null, causing=null, sourcePosition=null, despite projectile.owner=Troll or reflected blocker. Hurt result is discarded; broadcast3 and projectile discard happen after request even when false. Troll/nonLiving contacts do not enter this branch or discard there. No block-state-specific damage, enchantment/postattack callback, fire, status or area payload. Tags are exactly minecraft:damages_helmet, minecraft:is_projectile, neoforge:is_physical in scoped native merge. Helmet-equipped target receives native helmet durability processing and .75 damage factor (6->4.5 at that stage), then native cooldown/armor/etc; no armor/protection/Resistance bypass. It has no bypasses_shield tag, but ordinary directional shield check cannot block a null sourcePosition;244 shield event may still override. when_caused_by_living_non_player scaling is inactive because causing entity is null, so no automatic Troll difficulty multiplier or ownership/kill-credit substitution. Static attribution quirk is preserved, not repaired.',
      'thrown_block_reflection':'onHitBlock calls superclass native block projectile callback first, then server broadcast3, gameEvent BLOCK_DESTROY with projectile owner, discard; no placing/mining/dropping the carried state or hurt-success dependency. Native TF timed shield-parry path applies via ITFProjectile under pinned config (external parry mod absent, blocker within40ticks; parryNonTwilightAttacks=false still permits TF marker). AIM_DEFLECT changes projectile owner and cancels that impact; subsequent ThrownBlock entity hit STILL uses the ownerless source overload and Troll recipient veto. Reflection is not an exception that grants owner credit or makes Troll vulnerable. Ordinary native projectile owner/leftOwner collision mechanics and possible future block interactions use the new owner. ThrownBlock NBT stores BlockState and calls super to preserve native projectile owner; no custom lifetime timer. Aether/other data tags alone are not asserted as active consumers.',
      'troll_persistence_death':'Troll saves HasRock, RockCooldown and RockState only if nonnull; read always invokes NbtUtils.readBlockState on getCompound(RockState). Native missing Name produces AIR.defaultBlockState, which is nonnull. Therefore ordinary save/load of no-rock Troll can leave rock=Air with hasRock=false; at cooldown0 and target present, a failed stone sample still reaches rock!=null and creates a carried Air-state projectile. Valid later sample can overwrite it; ThrownBlock damage6 does not depend on state. Read restores follow-range/task from HasRock; native passenger save/load is separate, not reconstructed by this method. Death calls super.tickDeath then every deathTime%5==0 scans inclusive+/-12 cube (15625 positions), replaces exact UNRIPE_TROLLBER with ripe on independent nextBoolean and abs(x+y+z)%5==deathTime/5. Ordinary20-tick death visits offsets1..4; residue0 is not visited, no single guaranteed full ripening. No own server/grief/hurt-success gate, HP heal, explosion or summoned attack in these helpers; terrain/food availability is documented as an exclusion from unique combat packages. WorldUtil range proof reused. No extra Troll death boss phase.'
    }
    M='entity/monster/';G='entity/ai/goal/';P='entity/projectile/ThrownBlock'
    data=dict(slug='tactical-mobs',checkpoint_short='r2f8f',checkpoint='R2f8f-tactical-mobs-complete',decision='TWILIGHT_TACTICAL_MOBS_SEMANTIC_REVIEW_COMPLETE',starting_sha='ce8cafbf6c2fb8108f8db7cba46eb4a3cc9a12ff',previous_checkpoint='R2f8e-arthropods-complete',previous_draft='partial-drafts/twilightforest-r2f8e-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=1,full_classes=FULL,limited_classes={'init/TFItems':['Ironwood pick/boots registration and attribute lambdas'],'init/TFArmorMaterials':['Ironwood material only; other material bytes pinned for later review'],'util/WorldUtil':['getAllAround']},registration_classes=['init/TFEntities','events/RegistrationEvents','init/TFItems','init/TFArmorMaterials'],closure_checklist=['native_equipment_vs_base_attack','redcap_shy_and_avoid','tnt_goal_order_and_flags','sapper_resource_save','native_tnt_source_formula','tnt_chain_and_owner_reload','kobold_real_pickup_gates','pacification_vs_retaliation','bread_resource_and_consumption','panic_and_flock_cadence','unregistered_boggard_exclusion','troll_rock_control_and_terrain','carried_and_thrown_projectiles','ownerless_source_and_helmet_shield','native_parry_identity','reload_air_state','death_ripening_exclusion','actual_damage_callers'],compatibility_scope=facts['authority'],current_scope='Protected prior Twilight subsections plus Redcap/Sapper, Kobold and Troll/ThrownBlock are reviewed; unregistered Boggard is an assessed exclusion; whole Twilight PARTIAL/zero promoted.',exact_next_task='Continue Task C with CarminiteGolem, Adherent/HarbingerCube, MazeSlime, SnowGuardian, RisingZombie/LoyalZombie and remaining Wraith/Minotaur body coverage; then remaining items/scepters/armor/charms/projectiles/hazards/resources and14 custom caller profiles. Reuse all protected tactical/arthropod/earlier work. Protect each subsection toward R2f8 and whole-Twilight promotion; IceAndFire only after Twilight COMPLETE is pushed. No runtime boss/L2/Stage/production/fixes/Phase6/7.',damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=25,new_used_profiles=1,reviewed_profiles_after=26,remaining_profiles=14,remaining_disposition='Other native caller profiles unfinished, not unused.'))
    def pkg(key,title,classification,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=classification,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    shy=pkg('redcap_tactical_avoidance','Redcap shyness and TNT avoidance','CUSTOM_CONTROL',['redcap_body','redcap_shy','redcap_avoid','authority'],[M+'Redcap',M+'RedcapSapper',G+'RedcapBaseGoal',G+'RedcapShyGoal',G+'AvoidAnyEntityGoal',G+'AvoidAnyEntityGoal$1'],{'shy_min_distance':3,'shy_max_distance':6,'circle_radius':5,'circle_rotation_radians':1,'equipped_attack':5,'redcap_armor':2,'sapper_armor':4},['native shy counter','yaw predicate','MOVE/LOOK priority','native path admission'],'Custom goal composition and circle/avoid destinations using native navigation.','Native Redcap/Sapper engaging Player with nearby primed TNT',['Looking-away/range/recent-hurt controls; TNT from other native producers'])
    plant=pkg('redcap_tnt_control','Redcap TNT ignition and Sapper finite planting','CUSTOM_CONTROL',['redcap_light','sapper_plant','redcap_body'],[M+'Redcap',M+'RedcapSapper',G+'RedcapLightTNTGoal',G+'RedcapPlantTNTGoal',G+'RedcapBaseGoal'],{'sapper_initial_tnt':3,'scan_light_half_extent':8,'scan_plant_half_extent':5,'ignite_distance_squared':5.76,'plant_distance_squared':25,'light_delay_evaluations':20},['grief gate at entry','native TNT state','Sapper stock','target yaw','native block mutation'],'Custom stock and AI delivery of ordinary native TNT; placement and ignition are distinct.','Native Sapper plant followed by native Redcap/Sapper ignition',['Existing TNT with no target/stock; placement failure; reload stock; redstone/Player/chain priming'])
    blast=pkg('redcap_native_tnt_blast','Redcap and Sapper native TNT blast delivery','VANILLA_COMPOSITE',['tnt_blast','tnt_alternates','authority'],[G+'RedcapLightTNTGoal',G+'RedcapPlantTNTGoal',M+'Redcap',M+'RedcapSapper'],{'strength':4,'entity_radius':8,'fuse':80,'chain_fuse_min':10,'chain_fuse_max':29},['native fuse','native explosion events/exposure','actual owner','separate HP/control/terrain'],'Native TNT explosion primitive with TF AI producer; no custom explosion damage type.','Native Redcap-primed TNT with Living owner',['Sapper-planted TNT primed by Player/redstone/projectile/chain; owner lost on ordinary reload'])
    bread=pkg('kobold_bread_control','Kobold dropped-bread pickup and temporary pacification','CUSTOM_CONTROL',['kobold_body','kobold_pickup','kobold_pacification'],[M+'Kobold',M+'Kobold$1',M+'Kobold$SeekBreadGoal',M+'Kobold$KoboldAttackPlayerTarget',M+'Kobold$RunAwayWhileHoldingBreadGoal'],{'hp':13,'attack':4,'seek_range':8,'seek_chance_denominator':10,'easy_base':400,'normal_base':200,'hard_base':100,'random_timer_exclusive_max':600,'held_bread_count':1},['native server loot admission','actual bread tag','empty mainhand','not panicked','separate target/retaliation rules'],'Custom AI response and timed native item consumption; no taming or direct heal.','Native Kobold picks up legitimately dropped bread',['Grief/pickup-delay/panic failures; retaliation while bread held; timed consumption and save/load'])
    panic=pkg('kobold_flock_panic','Kobold local death-triggered panic','CUSTOM_CONTROL',['kobold_panic','kobold_pacification'],[M+'Kobold',G+'PanicOnFlockDeathGoal'],{'range_xz':4,'range_y':2,'start_goal_ticks':40,'stop_decrement':20,'navigation_speed':2},['same runtime class deathTime','native random destination','navigation/timer continuation'],'Custom death-sensitive navigation and synced panic flag, not a status damage event.','Native nearby Kobold death while another Kobold is alive',['Failed path; residual-timer restart; bread consumption delay; unsaved panic'])
    flock=pkg('kobold_flock_navigation','Kobold small-flock center navigation','CUSTOM_CONTROL',['kobold_flock'],[M+'Kobold',G+'FlockToSameKindGoal'],{'search_xz':16,'search_y':4,'max_group':5,'chance_denominator':40,'min_distance_squared':25,'max_distance_squared':256,'move_goal_ticks':10},['native class query','not bread at entry','snapshot center','no conflict flags'],'Custom local grouping navigation; no spawn, shared health or combat stat buff.','Native separated group of at most five Kobolds',['More-than-five/near-center/bread entry failures; concurrent goals and captured center'])
    rock=pkg('troll_rock_state','Troll rock acquisition, combat task and saved state','CUSTOM_RESOURCE',['troll_body','troll_pickup','troll_throw','troll_persistence_death'],[M+'Troll',P,'util/WorldUtil'],{'hp':30,'melee_attack':7,'follow_range_bonus':8,'cooldown_min':300,'cooldown_max':399,'ranged_speed':1.6,'ranged_interval_min':20,'ranged_interval_max':60,'ranged_range':15},['target and no rock','cooldown','sampled stone/ray','nonnull saved state','native task switch'],'Custom held-block state and AI/terrain resource with native projectiles; reload Air-state quirk retained.','Native Troll acquiring stone and throwing it',['Failed sample/no target; carried projectile loss; ordinary reload without RockState; death ripening exclusion'])
    thrown=pkg('troll_thrown_block_damage','Troll block projectile ownerless damage','CUSTOM_DAMAGE',['thrown_hit','thrown_block_reflection','troll_throw','authority'],[P,M+'Troll','entity/projectile/TFThrowable'],{'damage_request':6,'helmet_factor':.75,'gravity':.03,'projectile_size':1},['native impact admission','server Living not Troll','ownerless source factory','discard independent of hurt'],'Custom projectile-tagged physical source with missing source position/ownership; native helmet and other mitigation preserved.','Native Troll thrown-block collision with eligible Living target',['Carried contact only if native collision admits; timed shield parry then later hit; Troll/nonLiving/false-hurt/block controls'])
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:tactical_mobs_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' via genuine native entities, goals and callbacks; static future fixture, no fabricated damage source.',future_controls=controls))
    rows=[
      ('redcap_equipped','Native finalized Redcap/Sapper melee and equipment',['redcap_body','authority'],[shy],[M+'Redcap',M+'RedcapSapper'],['MOB_ATTACK','MELEE'],['attack5 vs base2','armor2/4','native enchantments','temporary held tools']),
      ('redcap_shy','Native target-looking shyness circle',['redcap_shy'],[shy],[G+'RedcapShyGoal',G+'RedcapBaseGoal'],['MOB_ATTACK','OTHER'],['3..6 entry vs strict continuation','yaw not pitch','native Player-hurt counter']),
      ('redcap_avoid','Native primed-TNT avoidance',['redcap_avoid'],[shy],[G+'AvoidAnyEntityGoal',G+'AvoidAnyEntityGoal$1'],['MOB_ATTACK','ENVIRONMENT'],['LOS/first candidate/path','own-position random helper quirk','speed1/2']),
      ('sapper_plant','Native Sapper finite TNT placement',['sapper_plant'],[plant],[M+'RedcapSapper',G+'RedcapPlantTNTGoal'],['MOB_ATTACK','ENVIRONMENT'],['three charges','looking-away','empty block','no flags/no refund']),
      ('sapper_state','Native Sapper stock/equipment save and failure',['sapper_plant','redcap_body'],[plant],[M+'Redcap',M+'RedcapSapper'],['MOB_ATTACK','OTHER'],['TNTLeft','no replenishment','goal restores helper pick']),
      ('redcap_light','Native Redcap or Sapper existing TNT ignition',['redcap_light'],[plant,blast],[G+'RedcapLightTNTGoal'],['MOB_ATTACK','ENVIRONMENT'],['no target/stock requirement','grief at entry','distance<5.76','no Flint wear']),
      ('redcap_blast','Native Redcap-owned TNT fuse and explosion',['tnt_blast'],[blast],[G+'RedcapLightTNTGoal'],['EXPLOSION','AOE'],['player_explosion despite mob owner','strength4 formula','separate knockback/terrain','owner can be hit']),
      ('sapper_redstone','Native redstone immediately primes placed TNT',['sapper_plant','tnt_alternates'],[plant,blast],[G+'RedcapPlantTNTGoal'],['EXPLOSION','ENVIRONMENT'],['owner null','minecraft:explosion','placement callback']),
      ('sapper_player','Native Player/fire/projectile ignition of Sapper TNT',['tnt_alternates'],[blast],[G+'RedcapPlantTNTGoal'],['EXPLOSION','ENVIRONMENT'],['actual igniter owner','not planter attribution','ordinary native mayInteract']),
      ('tnt_chain','Native TNT explosion chain',['tnt_alternates','tnt_blast'],[blast],[G+'RedcapPlantTNTGoal',G+'RedcapLightTNTGoal'],['EXPLOSION','AOE'],['fuse10..29','indirect owner inheritance','no extra stock decrement']),
      ('tnt_reload','Native primed TNT save/load or dimension transfer',['tnt_alternates'],[blast],[G+'RedcapLightTNTGoal'],['EXPLOSION','OTHER'],['owner unsaved vs restoreFrom copied','native source changes','fuse retained']),
      ('kobold_pickup','Native dropped bread search and pickup',['kobold_body','kobold_pickup'],[bread],[M+'Kobold',M+'Kobold$SeekBreadGoal'],['MOB_ATTACK','OTHER'],['tagged vanilla bread','native grief/delay/reach','split excess','clear target']),
      ('kobold_hold','Native held-bread targeting and avoidance',['kobold_pacification'],[bread],[M+'Kobold$KoboldAttackPlayerTarget',M+'Kobold$RunAwayWhileHoldingBreadGoal'],['MOB_ATTACK','OTHER'],['canUse only','retaliation remains','avoidance8/speed1.5']),
      ('kobold_eat','Native timed bread consumption',['kobold_pacification','kobold_body'],[bread],[M+'Kobold'],['ACTIVE_ITEM','OTHER'],['difficulty timer','panic postpones consumption','no Player food/heal','cosmetic munch timer separate']),
      ('kobold_reload','Native Kobold bread/counter save/load',['kobold_pacification'],[bread],[M+'Kobold'],['MOB_ATTACK','OTHER'],['both counters saved','held item native save','panic not saved']),
      ('kobold_panic','Native same-class nearby death panic',['kobold_panic'],[panic],[G+'PanicOnFlockDeathGoal',M+'Kobold'],['MOB_ATTACK','OTHER'],['deathTime box','no LOS','40 callbacks and stop-20','residual restart']),
      ('kobold_panic_bread','Native panic during bread holding',['kobold_panic','kobold_pacification'],[panic,bread],[M+'Kobold',G+'PanicOnFlockDeathGoal'],['MOB_ATTACK','OTHER'],['timer keeps decreasing','canEat false','target not universally cleared']),
      ('kobold_flock','Native small-group center navigation',['kobold_flock'],[flock],[G+'FlockToSameKindGoal'],['MOB_ATTACK','OTHER'],['at most5','center snapshot','no flags','10 goal callbacks']),
      ('troll_melee','Native Troll no-rock melee and sun avoidance',['troll_body','authority'],[rock],[M+'Troll'],['MOB_ATTACK','MELEE'],['attack7','no petrification','ordinary defenses']),
      ('troll_acquire','Native Troll stone sampling and carry state',['troll_pickup','troll_body'],[rock],[M+'Troll',P],['MOB_ATTACK','ENVIRONMENT'],['cooldown conditional','base stone/ray','no grief hook','remove return ignored']),
      ('troll_throw','Native Troll ranged-goal new projectile',['troll_throw','troll_body'],[rock,thrown],[M+'Troll',P],['MOB_ATTACK','PROJECTILE'],['new entity vs carried one','speed1.6','inaccuracy4-id','follow24']),
      ('troll_hit','Native thrown block eligible Living impact',['thrown_hit'],[thrown],[P],['PROJECTILE','MOB_ATTACK'],['request6','null source identity/position','helmet.75','false hurt still discard']),
      ('troll_carried','Native carried rock projectile contact admission',['troll_throw','thrown_hit'],[rock,thrown],[M+'Troll',P],['PROJECTILE','OTHER'],['native rideTick/collision only','not a guaranteed contact','same ownerless payload']),
      ('troll_parry','Native timed shield parry of Troll block',['thrown_block_reflection','thrown_hit'],[thrown],[P,'entity/projectile/TFThrowable'],['PROJECTILE','OTHER'],['marker eligible','owner changes but source null','Troll veto still applies']),
      ('troll_negative','Native Troll/nonLiving/block impact controls',['thrown_hit','thrown_block_reflection'],[thrown],[P],['PROJECTILE','ENVIRONMENT'],['no entity callback discard for Troll/nonLiving','block callback then discard','no terrain placement']),
      ('troll_reload','Native Troll and projectile save/load',['troll_persistence_death','thrown_block_reflection'],[rock,thrown],[M+'Troll',P],['MOB_ATTACK','PROJECTILE'],['missing RockState becomes Air','future carry possible without valid sample','state does not change damage','owner saved on projectile']),
      ('troll_state_loss','Native missing carried projectile and task state',['troll_throw','troll_persistence_death'],[rock],[M+'Troll'],['MOB_ATTACK','OTHER'],['flag independent of passenger','first-passenger discard only','cooldown resets on throw']),
      ('troll_death','Native Troll death ripening exclusion',['troll_persistence_death'],[rock],[M+'Troll','util/WorldUtil'],['ENVIRONMENT','OTHER'],['25-cube','offsets1..4','no HP/attack/summon','no grief/server gate in helper'])]
    for row in rows:path(*row)
    data['damage_profiles']=[dict(type='twilightforest:thrown_block',status='USED',callers=[dict(entry='twilightforest/entity/projectile/ThrownBlock.class',method='onHitEntity')],amount='6 request; native damages_helmet factor.75 at helmet stage, ordinary mitigation/events/cooldown afterward.',direct_and_causing_entities='direct=null, causing=null, position=null; projectile owner is not passed to the source factory, including reflected path.',mitigation=facts['thrown_hit'],difficulty='when_caused_by_living_non_player declaration does not scale this ownerless source.')]
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','vanilla-evidence/twilight-tactical-tags.json','reference-evidence/twilight-tactical-tags-244.json','twilightforest-tactical-mobs-caller-scan.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','vanilla-evidence/twilight-hydra-urghast.json','reference-evidence/twilight-hydra-urghast-244.json','vanilla-evidence/twilight-minoshroom-knight.json','reference-evidence/twilight-minoshroom-knight-244.json','vanilla-evidence/twilight-ranged-mobs.json','reference-evidence/twilight-ranged-mobs-244.json','vanilla-evidence/twilight-giants-tools.json','reference-evidence/twilight-giants-tools-244.json']
    data['exclusions']=['Full19 native class surfaces, including shared ChargeAttackGoal reused unchanged. TFArmorMaterials bytes captured for dependency proof; only Ironwood material is newly interpreted here, remaining armor review stays pending.','Ordinary equipped melee/armor and vanilla TNT are native primitives; TF control and materially distinct source paths are explicit. No fabricated planter/reflector ownership for damage.','Troll death ripening and Kobold munch particles are reviewed non-damage behavior, not independent combat packages. No phantom Troll petrification or Kobold healing.','Boggard is unregistered with no external installed class reference or native producer; its declared charge behavior is excluded, not counted as a legitimate path.','THROWN_BLOCK is USED through its actual ownerless caller;26/40 custom profiles reviewed,14 still unfinished.','Whole Twilight still PARTIAL/zero promoted; no runtime, L2, Stage, production, balancing or Phase6/7 changes.']
    data['fixture_groups']=['Redcap/Sapper native equipment, shyness/yaw/path and nearby TNT avoidance; held-tool state and late goal interruptions.','Sapper finite placement vs ordinary Redcap ignition; grief entry/continuation, failed placement, actual igniter and source owner, native TNT chain/save/dimension paths.','Native dropped bread and Mob pickup gates; Kobold target acquisition versus retaliation, difficulty timers/consumption, panic/residual timer and concurrent flock navigation.','Boggard exclusion: do not instantiate an unregistered class as a native positive control; protected registered Minoshroom/Minotaur charge paths remain valid.','Troll sampled stone/removal/cooldown/follow-range/task state, carried versus newly thrown projectile, state reload and Air-state fallback consequence.','ThrownBlock exact6 ownerless source, helmet effect, native shield-position failure versus separate timed parry, Troll/nonLiving/block/false-hurt outcomes.']
    data['expected_counts']=dict(mechanic_packages=8,delivery_cases=28,classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=1)
    write_json(OUT/'review-inputs/twilightforest-tactical-mobs.json',data);assemble('twilightforest-tactical-mobs.json')

if __name__=='__main__':build()
