"""R2g3a Siren song control and independent status marker."""
from catalog_common import *
from assemble_batch import refresh
START='fb6a249c3b77b051d3a0ce2b42343b05e4a016ee'
CP='R2g3a-siren-song-complete'
NEXT='R2g3b: finish distinct Siren Flute loveTicks control (SirenFluteItem.use -> MiscData.setLoveTicks/tick -> ComponentManager/native attachment and tick registration; actual consumers/removal/persistence) and Siren bite/pull attack admission/amount/hurt-return dependency. Do not conflate either with song/SIREN_CHARM. Reuse completed R2g3a song and R2g2 Frozen. Then Gorgon and remaining Ice & Fire combat families; no runtime/L2/Stage/production work.'
FACTS={
'authority':'Installed Iaf beta15 SirenEntity complete class bytes plus SirenCharmStatusEffect, native prey tag, config and cosmetic shader consumer; exact protected loader effect lifecycle and tensura_iaf bridge are reused. Actual callback is SirenEntity.aiStep; lambda$tickMovement$8 is only the compiler helper name, not an absent or separate tickMovement override. All726 native classes contain no SirenData class. The actual state is SirenEntity.charmingEntities.',
'mechanic':'The constructor allocates a private final Object2IntOpenHashMap<LivingEntity> charmingEntities. Song control is that map and tickCharm, while iceandfire:siren_charm is a HARMFUL heart-particle MobEffect with only a constructor, no movement/damage/removal override. The status is an independent marker and shader input; its native lifecycle/Resistance admission does not own the map. Whole package classification is CUSTOM_CONTROL with a custom status marker component. No new DamageType, hurt, HP subtraction or SHP call is used by tickCharm.',
'singing':'aiStep first calls superclass. Positive singCooldown decrements and calls setSinging(false). Server no-target/not-aggressive state requests setSinging(true), but setter clamps false while cooldown>0. wantsToSing=isSinging&&inWater&&!aggressive; isActuallySinging=isSinging&&!wantsToSing. The animation-pose local additionally requires !aggressive,!inWater,onGround, but those pose guards are NOT all acquisition guards. Server acquisition/tickCharm checks !GorgonEntity.isStoneMob(this) and isActuallySinging; isStoneMob is instanceof StoneStatueEntity, not a generalized petrification flag. Normally Siren and StoneStatue are different entity classes.',
'acquisition':'Every tickCount%20==0 during that server singing block: get LivingEntity in own box inflated(50,12,50), using explicit SIREN_PREY predicate; filter !isWearingEarplugs and distance>=5. SIREN_PREY is (Player&&!creative&&!spectator) OR entityType tag SIREN_CHARMABLE; native tag has villager and wandering_trader only. The OR allows tagged entities independently of the Player clause; do not invent an unconditional creative/spectator exclusion for arbitrary future tag additions. No LOS/wall check, damage result, holder application, or owner/team check gates this query.',
'map_before_effect':'Refresh removes map keys absent from current target list directly (no stopCharm/cooldown), adds missing keys with time0, then attempts addEffect(SIREN_CHARM,30ticks,amp0,source=this Siren) for every retained key; returned boolean discarded. Existing time counters are preserved by computeIfAbsent. Then setSinging(true) and tickCharm run even if effect addition was vetoed. Native finite duration/merge/cures remain, but clearing/rejecting this marker cannot remove map entries through this class. Shader enabled by marker is cosmetic and not proof of control admission.',
'timer_and_distance':'tickCharm iterates current map. First time>maxSingTime (default/snapshot12000) calls stopCharm; equality still permits a control tick. Next checks Siren isAlive and target distance<=64; failure stops that target and sets Siren aggressive=false. There is no corresponding target alive check in this method. The box query can include diagonals beyond64, so acquisition/marker attempt can be followed by immediate stop and global cooldown. Outside the server singing block the map/timers are not ticked or cleared by this class; they can remain dormant.',
'map_player_bug':'Exact bytecode tickCharm loads charmingEntities atoffset93 into a local before instanceof Player at100; another field load353 precedes instanceof Player356. Both test the MAP, not charmingEntity. The actual constructor allocates Object2IntOpenHashMap, so the intended creative/spectator escape in this tick body never applies and the rotation body also runs for Players. Ordinary initial Player eligibility still comes from SIREN_PREY; a mid-charm creative/spectator change is only removed by the next target refresh (unless tagged), not this mistaken tick guard. Preserve the native bug; no repair is authorized.',
'approach':'Distance<5 on a tickCharm iteration sets cooldown=timeBetweenSongs (default/snapshot2000), requests singing=false, sets target to that victim, sets aggressive=true, triggers nearby Sirens, then stopCharm. Refresh excludes <5 targets before tickCharm, so a target already inside5 on a refresh tick can be removed without this aggression handoff. At distance>=5: counter increments, horizontalCollision sets jumping=true; each velocity component moves10% toward +/-0.5 based on sign of Siren-target delta (Y sign uses SirenY-targetY+1). Writes delta, sets hurtMarked=true, stops riding if passenger, rotates pitch/yaw toward Siren-minus-target-minus(0,1,0) with each wrapped change clamped+-30 degrees. No damage result is tested.',
'removal_shared_state':'stopCharm only removes map entry and sets global Siren singCooldown; it does not remove the MobEffect, setSinging, clear motion, stop jumping, or clear target. Next aiStep consumes cooldown and clamps singing. Direct refresh removals do not call it. Losing singing suspends map processing; last marker can expire independently. Multiple Sirens own separate maps and can write one recipient velocity; multiple victims share a Siren cooldown/target/aggression state. No stable cross-map/target priority or single-controller arbitration is implemented here.',
'aggro_boundary':'triggerOtherSirens scans own AABB inflated12 and for other Siren entities sets target/aggressive and singing=false. Siren.hurt calls it when source.getEntity is living BEFORE super.hurt, so propagation is not gated by accepted damage. Arrival handoff itself does no HP damage. Bite/pull animation damage in the earlier aiStep body remains a separate next subsection; ordinary later aggression is not damage caused by the SIREN_CHARM MobEffect.',
'persistence':'Siren save writes each map target UUID and CharmTime under CharmingEntities. Read clears the map and restores only UUIDs resolving to a currently loaded LivingEntity in the ServerLevel; it does not store unresolved UUIDs for later. Singing/aggression and other entity fields restore separately. singCooldown is not saved in these methods. CHARMED/Passive is a distinct saved synced boolean and is not the target map or SIREN_CHARM membership.',
'native_immunity':'Native isWearingEarplugs checks nonempty HEAD stack exactly IafItems.EARPLUGS. tensura_iaf RETURN injection preserves an already true result; otherwise makes it true for SkillUtils.isSkillToggled(entity,SPIRITUAL_ATTACK_NULLIFICATION). Protected exact SkillUtils resolves an instance and requires isToggled&&mastery>=0. This bridge uses neither ResistSkill.canInteractSkill nor the ColdNullification holder-list dispatcher: it has no nullification-gamerule/sleep/Rest/area predicate of its own. Other native systems can change toggle state, but do not silently import those predicates into this helper. Earplug/toggle changes affect next20tick acquisition refresh; tickCharm has no per-tick earplug recheck.',
'status_independence':'Because marker addEffect result is ignored, generic effect immunity/cure alone need not prevent song movement. Conversely earplugs can prevent map acquisition even if a previously applied marker remains for its native duration. Existing native status admission, source=this, expiration/removal events and external hooks remain untouched. No status fallback, synthetic source, direct HP/SHP change, runtime L2 result or production fix is proposed.',
'exclusions_and_next':'SirenShaderRenderHelper is cosmetic and excluded as a separate mechanic. Hair/pose/sounds/rendering/spawn appearance are short exclusions. Source read-ahead shows SirenFlute writes MiscData.loveTicks200 rather than SIREN_CHARM; it requires its own component dispatch/persistence review next. Siren bite/pull likewise remain separate. Ice & Fire remains PARTIAL, no promoted records; Frozen complete checkpoints preserved.'
}

def save():
    files=['native-evidence/iceandfire-siren.json','iceandfire-siren-callers.json','native-evidence/iceandfire-foundation.json','reference-evidence/iceandfire-frozen-tensura.json','reference-evidence/vv-loader-244.json','reference-evidence/twilight-frosted-244.json','iceandfire-frozen-config-snapshot.json','annotation-evidence/iceandfire-compat-javap.json']
    fixtures=[('ordinary_player','native singing server query, no earplugs,5..64 distance, actual map and marker observed'),('native_tagged_villager','villager/wandering_trader target predicate, no Player-only assumption'),('status_rejection','map control independent of addEffect=false'),('marker_cure','cure does not mutate map'),('earplug_toggle','next refresh removes/prevents key; marker may remain'),('spiritual_nullification','native exact helper bool/mastery admission, not ColdNullification pipeline'),('mid_charm_creative','wrong map instanceof guard, next refresh behavior'),('distance_under5','non-refresh approach handoff vs refresh removal'),('distance_over64','query diagonal can add then stop/global cooldown'),('timer_boundary','time==max still controls; >max stops'),('reload','loaded UUID restore, unresolved UUID skipped, cooldown unsaved'),('multiple_sirens','independent maps; native update-order interactions'),('player_rotation','map instanceof bug permits pitch/yaw writes to Player')]
    d=dict(schema='tno.external_effects.iaf_siren_song.v1',baseline=BASELINE,checkpoint=CP,starting_sha=START,status='SIREN_SONG_SEMANTIC_REVIEW_COMPLETE',facts=FACTS,mechanic_draft=dict(id='iaf:siren_song',classification='CUSTOM_CONTROL',components=['native_target_map','velocity_attraction','dismount','rotation','independent_harmful_status_marker','aggression_handoff']),delivery_paths=[dict(id='iaf:siren_song:player',labels=['PASSIVE_AURA','MOB_ATTACK'],source='native singing Siren',eligibility='noncreative/nonspectator Player OR native tag; earplug/distance/query/state predicates',effect_source='Siren entity',status_success_required=False),dict(id='iaf:siren_song:tagged',labels=['PASSIVE_AURA','MOB_ATTACK'],source='native singing Siren',eligibility='SIREN_CHARMABLE native villagers/traders plus unchanged generic song guards',effect_source='Siren entity',status_success_required=False)],future_fixtures=[dict(id=k,expected_native_contract=v,executed=False) for k,v in fixtures],reference_files=[dict(file=f,sha256=sha256(OUT/f)) for f in files],song_native_ambiguities=[],review_required=[],whole_siren_family_complete=False,whole_iceandfire_complete=False,promoted_mechanics=0,promoted_paths=0,exact_next_task=NEXT,runtime_tests=0,**boundary_flags())
    write_json(OUT/'iceandfire-r2g3a-siren-song.json',d)
    r=read_json(OUT/'mod-reviews/iceandfire.json');r.update(checkpoint=CP,scope='Frozen family and Siren song/map-versus-status semantics complete. Flute love control, Siren attacks and other combat families pending.',notes_file='iceandfire-r2g3a-siren-song.json',exact_next_task=NEXT);write_json(OUT/'mod-reviews/iceandfire.json',r);refresh(CP)
    for f in ['effect-catalog.json','effect-sources.json','delivery-path-matrix.json','vanilla-comparison.json','behavior-primitives.json']:
        o=read_json(OUT/f);o.update(checkpoint=CP,unfinished_review=dict(mod_key='iceandfire',status='PARTIAL',promoted_records=0,notes_file='iceandfire-r2g3a-siren-song.json'));write_json(OUT/f,o)
    o=read_json(OUT/'research-decision.json');o.update(checkpoint=CP,next_task=NEXT,latest_iceandfire_subsection_decision='SIREN_SONG_SEMANTIC_REVIEW_COMPLETE');o['checkpoints']['R2g2b-frozen-native-delivery-complete']=START;o['checkpoints'][CP]='Self: exact SHA from commit/live verification.';write_json(OUT/'research-decision.json',o)
    lines=['# R2g3a — Siren song control and status marker','','**Song subsection complete; Ice & Fire remains PARTIAL.** Flute loveTicks and bite/pull combat are separate pending mechanics.','']
    for k,v in FACTS.items():lines+=['## '+k.replace('_',' ').capitalize(),'',v,'']
    lines+=['## Evidence and validation','','[Findings, paths and future fixtures](iceandfire-r2g3a-siren-song.json), [native witnesses](native-evidence/iceandfire-siren.json), [whole-JAR caller census](iceandfire-siren-callers.json). Scoped validation reproduces witnesses/census, proves map-versus-Player bytecode and ignored effect return, preserves accepted records/prior evidence, and runs five tooling tests plus diff checks. No runtime tests or new whole-catalog full-validation claim.','','Exact next task: '+NEXT,'']
    (OUT/'iceandfire-r2g3a-review.md').write_text('\n'.join(lines),encoding='utf-8')
    main=ROOT/'docs/external-effects-catalog-research.md';s=main.read_text(encoding='utf-8')
    if '## R2g3a — Siren song' not in s:s+='\n## R2g3a — Siren song\n\nNative song control is a Siren-owned target map, independent of its30tick HARMFUL status marker. Effect rejection/cure need not stop control. Two purported Player guards actually inspect the map; native rotation therefore also applies to Player victims. Existing SpiritualAttackNullification compatibility acts as earplugs at periodic target acquisition. [Evidence and exact resume](benchmarks/external-effects-catalog/iceandfire-r2g3a-review.md). No fixes or runtime tests; Flute and bite/pull are next.\n'
    main.write_text(s,encoding='utf-8')

if __name__=='__main__':save()
