"""R2f3 Lich subsection. Keep Frosted and accepted global rows immutable."""
from copy import deepcopy
from twilight_evidence import *
from assemble_batch import refresh

START='007aa5fd7610ba656bbd3b5f887a6bf1ac713b5a'
CP='R2f3-lich-complete'
NEXT='Naga semantic review from existing installed Twilight source aids; then Minoshroom / Knight Phantom, Hydra / Ur-Ghast, Alpha Yeti / Snow Queen. Lich and Frosted are reviewed: do not restart them. No Ice and Fire, runtime boss/L2 tests, Stage/production or Phase6 work.'

def build():
    refs=native_refs('entity/boss/Lich','entity/boss/BaseTFBoss','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal','entity/ai/goal/LichPopMobsGoal','entity/ai/goal/LichAbsorbMinionsGoal','entity/monster/LichMinion','entity/projectile/LichBolt','entity/projectile/LichBomb','entity/projectile/TwilightWandBolt','item/TwilightWandItem','init/TFAttributes','events/EntityEvents','init/TFDamageTypes','util/entities/EntityExcludedDamageSource')
    facts=[
      ('Shield resource/count', 'Integer SHIELD_STRENGTH, default6, separate from MAX_HEALTH100. Each accepted break subtracts exactly1, independent of excess amount. Clone getter returns0. Boss bar in phase1 displays shield/current max_shield_strength, not HP.'),
      ('Shield initialization', 'Synched default6; constructor then stores int(attribute twilightforest:max_shield_strength), default6/range0..1024. clone_count defaults2 and minion_count9 (same attribute range). Constructor copies int(minion_count) to reserve. finalizeSpawn equips Fortification Scepter; it does not grant additional shields. NBT explicitly saves/restores shield/reserve/clone UUIDs/master/baby count/hit counter; missing integer keys read0. Setter has no clamp or native refill.'),
      ('Shield decrement', 'Only the non-bypassing shield branch with tagged source and raw incoming float amount>2 decrements1. All shield-branch exits return false. A failed tag/amount check may set lastHurtByMob from a Living causing entity; successful break branch does not do that. die can clear shield to0 but is not shield break.'),
      ('Hurt ordering', 'Order: (1) teleport invisibility>0 rejects unless BYPASSES_INVULNERABILITY; (2) exact IN_WALL with target attempts teleport; (3) clone rejects unless bypass; (4) causing entity instanceof Lich rejects unconditionally; (5) non-bypass and shield>0 performs tag/strict>2 counter logic and returns false; (6) otherwise BaseTFBoss/super.hurt; (7) only true super return can trigger randomized survival teleport, then true. BaseTFBoss has no hurt override. IN_WALL teleport can set invisibility during this call without rechecking the first gate.'),
      ('Exact phases', 'getPhase: clone OR shield>0 =>1; else reserve<=0 AND countMyMinions()<=0 =>3; otherwise2. No HP threshold defines the three phases. countMyMinions scans AABB(x,y,z,x+1,y+1,z+1).inflate(32,16,32), master identity==this; no explicit alive filter. Nearby owned minions outside that box do not keep phase2 active.'),
      ('Shield versus normal HP', 'Shielded non-bypass hits never enter LivingEntity.hurt. Armor, Resistance, protection, absorption, ordinary hurt cooldown, incoming/pre/post damage hooks and HP subtraction are not reached for this branch. A normal untagged sword/arrow/explosion fails; amount<=2 fails even if tagged. Lich.hurt itself does not first repeat vanilla dead/client/invulnerable checks before counter processing. Delivery APIs can have their own earlier gates.'),
      ('Tag sufficiency', 'breaks_lich_shields is necessary inside the ordinary shield branch but is NOT sufficient. Exactly five native values: twilightforest:lich_bolt, twilightforest:twilight_scepter, minecraft:magic, minecraft:indirect_magic, minecraft:sonic_boom. Bomb and neoforge:is_magic membership alone do not qualify. BYPASSES_INVULNERABILITY skips the shield mechanism and attempts HP damage instead of decrementing.'),
      ('Additional predicates', 'To break normally: reach Lich.hurt through a legitimate delivery; teleport counter<=0; not a clone; causing entity not any Lich; shield>0; not bypassing invulnerability; tag match; argument strictly>2. No universal Player/direct-projectile/owner/nonally test is present in Lich.hurt. Projectile, potion, fang, Conduit and Warden predicates are separately retained in source_paths. Cloaked Bolt collision is rejected even before hurt.'),
      ('Legitimate sources', 'All five tag identities and their native producers are resolved in source_paths. The raw Minecraft factory census has10 callers; LootCommand is a loot-context source only, Guardian default targeting excludes Lich, Poison and water requests fail, and the other producer families have explicit eligible paths. Reuse accepted Friends ice chunk, Cult fangs and Royal anvil/pearl/enderman paths conditionally. This closes Lich semantics against native Twilight/Minecraft and accepted prior sources, not arbitrary unreviewed mods or datapack additions.'),
      ('Reflected projectile behavior', 'LichBolt is in minecraft:redirectable_projectile. Native Player.attack deflects AIM and returns before calling Bolt.hurt, provided attack hook/attackable/skipInteraction gates pass. AIM gives normalized look velocity (speed1), owner=Player. An admitted projectile hit on a redirectable bolt calls generic Projectile.onHit deflection with that projectile owner before its own onHitEntity. TF shield parry also calls AIM with blocking Living entity as owner and cancels impact. These are genuine transfer paths, distinct from Bolt.hurt fallback shoot(speed1.5,inaccuracy0.1).'),
      ('Direct/causing/owner', 'Lich Bolt damage direct=this bolt, causing=current owner; optional excluded Lich EntityType affects death message only. Phase1 Bolt collision additionally requires owner instanceof Player; native Lich/clone-owned, ownerless and other-mob-owned bolts cannot collide with phase1 Lich. Local Bolt.canHitEntity does not call super: it excludes Bolt/Bomb/Wand targets and cloaked Lich, then allows other candidates; do not invent inherited owner-vehicle/pickability predicates. Wand does call super.canHitEntity, then excludes Bolt/Bomb. Lich.hurt rejects ANY causing Lich, including another boss or clone.'),
      ('Ownership changes', 'Generic deflect executes callback, then setOwner(argument), then onDeflection. setOwner(null) is a no-op. Player/AIM/TF parry with nonnull owner transfer ownership. Bolt.hurt redirects using causing entity look, but only transfers if DIRECT entity is Living; indirect arrow damage alone does not transfer (the earlier generic onHit may already have done so). Later-phase Lich callback sets owner=Lich temporarily: a prior nonnull Player/Lich owner is restored by outer deflect; an initially ownerless projectile keeps the new Lich owner. Native projectile owner UUID serialization is inherited by Bolt/Bomb/Wand.'),
      ('Breaking shield and HP', 'A shield decrement, including6->5 and1->0, returns false without super.hurt: same request causes no HP loss, no hurt cooldown and no standard successful-hit callback. Separate later requests from one compound delivery can damage HP after1->0: ownerless Wither Skull magic5 can break, then its distinct native explosion request can hit exposed Lich. Multiple fangs/Anvil sweep+AoE similarly remain distinct requests. Damage requests are not measured HP loss.'),
      ('Final shield transition', 'At1->0 getPhase immediately becomes2 if reserve>0 or owned minion count>0; otherwise3. Default fresh Lich has reserve9, so phase2. No immediate HP damage, forced HP write or forced teleport is performed by shield break. Phase1 goal stops and despawns clones when goal scheduling observes loss of phase1; phase2 equips Zombie Scepter. Bossbar switches to HP on its next update.'),
      ('Later damage admission', 'Phase2 and3 with zero shields both admit ordinary source identities into super.hurt; killing all minions is NOT a prerequisite for HP damage. Teleport gate and causing-Lich rejection still apply. BYPASSES_INVULNERABILITY can skip shield/clone/teleport gates but still cannot skip causing-Lich rejection; native subsequent gates remain. Native exact244 LivingEntity checks invulnerable/client/dead/fire-resistance, incoming event, shield, freezing/helmet changes, cooldown, armor/magic/absorption, pre/post hooks and death handling. True hurt need not mean positive HP loss.'),
      ('Lich Bolt', 'Native main/clone phase1 and main phase2 attacks launch owner-bound Bolt from body offset at speed0.5/inaccuracy1; gravity0.001. Server admitted Living impact requests custom lich_bolt6, ignores return and broadcasts/discards. Block collision discards. Pickable radius1; ignoreExplosion=true. Later phases return deflection before onHit for tagged projectile with owner Player/Lich/null; another Living owner is not in that deflection predicate. The projectile remains alive after deflection; lastDeflectedBy suppresses repeated callback on the same entity but still suppresses onHit.'),
      ('Lich Bomb', 'Native AI launch shares speed0.5/inaccuracy1, gravity0.001. CanHitEntity unconditionally excludes every Lich plus Bolt/Bomb/Wand, despite an earlier conditional Lich check. Admitted hit calls super.onHit then explode. hurt ignores super result; direct entity required; non-IS_EXPLOSION request explodes, IS_EXPLOSION returns true without detonation. Not a native melee-reflect path, and not redirectable_projectile; TF shield parry can still deflect because ITFProjectile. Explosion server radius2, fire=false, Interaction.NONE, explicit lich_bomb direct=bomb/causing=current owner; then discard. isOnFire=true is not a target ignition callback. Parent block onProjectileHit can still trigger native block reactions (e.g. lighting candles).'),
      ('Clones', 'MASTER_LICH UUID presence defines clone even if master unresolved; getter shield0 but phase1 and normal hurt immunity. Default cap2 from attribute; tracked UUIDs resolved to Lich with getMaster()==this. Phase1 canUse phase1/tickCount>20/target!=null. Main synchronizes cooldown/cloak to clones, fires itself and all resolved clones at cooldown0/range<30; type choice nextInt(3)>0 gives next Bolt2/3 else Bomb1/3, cooldown100. At60 it teleports and on success requests at most one clone. Clone spawn uses LOS candidate, copies target/home/cloak, initial cooldown60+rand(3)-rand(3). During its active uncloaked goal an orphan seeks nonclone master with capacity nearby; absent/dead/non-phase1 master discards clone. Main goal stop/death despawns clones. Clones have real projectiles but no independent normal main firing branch.'),
      ('Minions/summons/healing', 'Phase2 goal only nonclone, acts while uncloaked with target. At attackCooldown%15==0 and server reserve>0/count<3, attempts spawn then decrements reserve even if LOS position/addFreshEntity fails. Native finalized MOB_SUMMONED LichMinion is Zombie subclass with master reference, no default equipment/loot pickup. Hard baby chance nextInt(100)<=20 while babyCount<minion_count/4 (default permits up to3 successful babies), otherwise adult. Missing/dead master seeks nearby nonclone count<3 then native kill if unresolved; master field is not custom-saved. Super-hurt success from ANY causing Lich grants Speed200/amp2 and Strength200/amp1, restores prior target via lastHurtByMob; false gives no buff. Ordinary Zombie melee uses effective ATTACK_DAMAGE, source mob_attack, inherited burning barehand successful-hit ignition; buffs are native effects. Pop goal: nonclone damaged, popCooldown0 and visible tagged Mob nearby; after20..39 held-scepter countdown and uncloaked/server, discard first visible poppable then heal2, cooldown40. Absorb goal: HP<max/2 and own nearby minions>0; after countdown/uncloaked, discard first owned minion then heal its current HP, no LOS test or hurt-success requirement. These discard/heal operations create NO DamageSource and are not player Lifedrain Scepter damage. Normal heal hook/clamp remains. Pop tag includes skeletons,zombie,enderman,spider,creeper,swarm_spider and removes #c:bosses.'),
      ('Combat teleport', 'teleportToNoChecks changes position, sets cloak20, clears fire/jumping. aiStep decrements cloak; isInvisible and canBeSeenAsEnemy reflect it (clone also invisible first10ticks). Combat goals pause actions while cloak>0, but global cooldown decrements follow their own conditions. findVecInLOSOf tries100 candidates target+Gaussian16XZ/Y+2; native randomTeleport requires loaded chunk, ground, no collision/liquid and stops navigation on success; restores original position after probe. Candidate must see target, remain in home range and be >=5 away; first85 attempts also require candidateY>=targetY. Home checks use current Lich Y for low-floor tests, candidate position for radius30. Target teleport helper randomly chooses an alive Player in range without its own creative/spectator filter, else uses passed target; successful move relocates clones. Triggers: phase1 cooldown60, later successful hurt (randomInt(3 or6)<=old hit counter, then increment; survival check; reset0 before attempted teleport), phase2 unable-to-shoot, phase3 failed navigation, IN_WALL with target, home escape. Home fallback can place stone support. No teleport damage callback. No EnderEntity event is explicitly posted by these Lich methods; native randomTeleport/teleportTo witnesses retained.'),
      ('Types/tags/amounts/returns', 'Custom lich_bolt6 and lich_bomb radius2 use armor/Wolf-armor bypass, projectile, witch-resistant and NeoForge magic tags; Bomb additionally explosion, Bolt additionally shield-break. twilight_scepter6 uses projectile/magic/shield-break but NOT normal armor bypass. None of these three has shield/Resistance/enchantment/invulnerability/cooldown bypass or no_knockback in scoped tags. Damage scaling WHEN_CAUSED_BY_LIVING_NON_PLAYER affects Player recipients (Peaceful0, Easy min(x/2+1,x), Normal x, Hard1.5x); it does not rescale a Lich target before shield threshold. Explosion damage = float((q*q+q)/2*7*4+1), q=(1-distance/4)*exposure, NO integer floor; outer radius and nonzero direction gates remain. Knockback is separate from hurt return and uses exposure and native explosion resistance/event adjustment. TF Detonate removes ItemEntity and LichBomb from affected entities; Bolt ignores explosions. Lich-owned explosion cannot damage any Lich, but displacement can still occur. See source_paths for native magic/sonic thresholds and secondary callback gates.')
    ]
    title,body=facts[18]
    facts[18]=(title,body+' Inherited Zombie behavior remains: registered Zombie attributes (base HP20, attack3, armor2, speed0.23), baby speed modifier+0.5 total; native finalization randomizes reinforcement chance, knockback/follow range and possible leader HP/door modifiers, so20 is not a universal finalized minion HP. Sun exposure ignites8s unless headwear protects. Barehand burning successful melee can ignite for2*int(effectiveDifficulty) seconds at chance0.3*effectiveDifficulty. Hard, mob-spawning-enabled successful hurt can spawn ordinary Zombie reinforcements after native chance/space/player-distance checks; these are not LichMinion and do not consume/count the Lich reserve. Underwater600ticks then conversion300 (native predecrement completion) can convert to ordinary Drowned through loader conversion hooks, losing LichMinion type/count. Native ZombieGroupData allows baby jockey handling; minion spawn calls addFreshEntity, not an independent guaranteed passenger-add path. No default equipment population does not suppress the separate native calendar/headwear and attribute-finalization branches. These inherited behaviors are pinned to exact244, not treated as new Twilight status types.')
    effects=[];paths=[]
    def effect(key,title,classification,indices,classes,components,source):
        eid='twilightforest:'+key
        e=dict(id=eid,mod_key='twilightforest',display_name=title,inspection_status='DRAFT',subsection_status='REVIEWED',primary_classification=classification,classification_provisional=False,
            actual_behavior=[facts[i-1][1] for i in indices],components=[dict(primitive=p,formula=f,vanilla_relation=v) for p,f,v in components],
            implementation=native_refs(*classes),primary_test_source=source,delivery_paths=[],registry_ids=[],
            pending=['Twilight whole-mod closure and final catalog promotion; this Lich subsection is reviewed.'],unresolved_ambiguities=None)
        effects.append(e);return eid
    shield=effect('lich_shield_resource','Lich shield resource','CUSTOM_RESOURCE',[1,2,3,7,8,13,14],['entity/boss/Lich','init/TFAttributes'],[('SHIELD_COUNTER','default6; qualified request>2 decrements1 and returns false','No vanilla HP/absorption equivalent')],'Player-reflected native Lich Bolt versus unreflected control')
    defense=effect('lich_damage_admission','Lich HP admission and projectile defense','BINARY_MECHANIC',[4,5,6,11,12,15],['entity/boss/Lich','entity/boss/BaseTFBoss'],[('HURT_ADMISSION','cloak -> in-wall side effect -> clone -> causing-Lich -> shield -> super','Custom gates before native hurt'),('PROJECTILE_DEFLECTION','phase>1 AND tagged type AND owner Player/Lich/null','Native deflect dispatch with custom callback')],'Native shield transitions and later-phase ordinary melee/projectile controls')
    bolt=effect('lich_bolt_package','Lich Bolt and reflection','CUSTOM_DAMAGE',[10,11,12,16,21],['entity/projectile/LichBolt','entity/boss/Lich','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal','events/EntityEvents','init/TFDamageTypes','util/entities/EntityExcludedDamageSource'],[('CUSTOM_PROJECTILE_DAMAGE','lich_bolt6; impact disposal independent of hurt','Native hurt, custom identity'),('OWNER_TRANSFER','AIM1 versus hurt fallback1.5; direct-Living predicate','Native redirect and custom fallback')],'Lich/clone-produced Bolt and Player melee/projectile/parry reflection')
    bomb=effect('lich_bomb_package','Lich Bomb explosion','CUSTOM_DAMAGE',[17,21],['entity/projectile/LichBomb','entity/boss/Lich','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal','events/EntityEvents','init/TFDamageTypes'],[('CUSTOM_EXPLOSION','radius2; firefalse; Interaction.NONE; native float exposure formula','Entity damage/knockback retained, block destruction disabled'),('DETONATION','impact or direct nonexplosion damage; discard regardless hurt result','No bomb melee reflection or shield-break tag')],'Native Lich Bomb block/entity impact and melee detonation')
    summon=effect('lich_phase_summons','Lich phase resources and summons','CUSTOM_RESOURCE',[5,14,18,19],['entity/boss/Lich','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal','entity/monster/LichMinion'],[('CLONE_CAP','default2 tracked UUID clones','Real entities with special immunity'),('MINION_RESERVE','default9; active cap3; failed attempt still spends1','Custom reserve, not HP gate'),('PHASE_STATE','clone/shield ->1; depleted reserve AND local minions0 ->3; else2','Custom state machine')],'Phase1 clone goal and phase2 native minion summon goal')
    heal=effect('lich_absorption','Lich mob consumption and healing','CUSTOM_RESOURCE',[19],['entity/ai/goal/LichPopMobsGoal','entity/ai/goal/LichAbsorbMinionsGoal','entity/boss/Lich'],[('DISCARD_AND_HEAL','visible poppable ->discard/heal2; own minion belowhalf ->discard/heal(minionHP)','Native heal, custom discard eligibility; no damage event')],'Injured Lich with eligible poppable or owned minion')
    teleport=effect('lich_teleport','Lich combat teleport','CUSTOM_CONTROL',[20],['entity/boss/Lich','entity/boss/Lich$1','entity/boss/Lich$2','entity/EnforcedHomePoint','entity/ai/goal/AttemptToGoHomeGoal','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal'],[('TELEPORT_AND_CLOAK','LOS/home candidate search, cloak20, clear fire','Uses native teleport, adds custom combat gates')],'Native phase1 cooldown, hurt-success and home/navigation teleport triggers')
    enrage=effect('lich_minion_enrage','Lich Minion retaliation buffs','VANILLA_LIKE_EXTENDED',[19],['entity/monster/LichMinion','entity/monster/LichMinion$1'],[('SPEED','200ticks amplifier2 (+60% native speed multiplier contribution)','VANILLA_DIRECT'),('STRENGTH','200ticks amplifier1 (+6 native attack damage)','VANILLA_DIRECT'),('TRIGGER','super.hurt true AND causing Lich (any instance)','Custom trigger and prior-target restoration')],'Native Lich Bolt/Bomb hitting its minion successfully')
    wand=effect('twilight_scepter_bolt','Twilight Scepter bolt','CUSTOM_DAMAGE',[11,12,21],['item/TwilightWandItem','entity/projectile/TwilightWandBolt','init/TFDamageTypes'],[('CUSTOM_PROJECTILE_DAMAGE','twilight_scepter6; server Living impact; dispose regardless return','Normal armor unlike Lich Bolt'),('ITEM_ADMISSION','used-up noncreative rejects; ownerPlayer; launch1.5/inaccuracy1; durability1 except creative or5% Mystic Crown reprieve','Native item/projectile path')],'Player uses Twilight Scepter against shielded Lich')
    def path(key,labels,source,behavior,eids,classes=('entity/boss/Lich',)):
        p=dict(id='twilightforest:lich_path:'+key,mod_key='twilightforest',status='DRAFT',subsection_status='REVIEWED',labels=labels,source=source,setup=behavior,native_delivery=behavior,effect_ids=eids,implementation=native_refs(*classes),future_controls=['Cloak/clone/causing-Lich admission','Shield count1 versus0; HP and return separately','Native eligibility and source identity retained'])
        paths.append(p)
        for e in effects:
            if e['id'] in eids:e['delivery_paths'].append(p['id'])
        return p['id']
    source_paths=[]
    def source(key,label,typ,amount,entities,predicates,outcome='SHIELD_BREAK_ELIGIBLE',eids=None,labels=None):
        pid=path(key,labels or ['OTHER'],label,predicates,eids or [shield,defense])
        source_paths.append(dict(path_id=pid,source=label,damage_type=typ,amount=amount,direct_and_causing_entities=entities,native_prerequisites=predicates,disposition=outcome))
    source('player_reflect','Player.attack native Bolt redirect','twilightforest:lich_bolt',6,'direct Bolt / ownerPlayer','Attack hook accepts; target attackable/interaction accepted; redirectable tag; native AIM transfer; Bolt then collides with uncloaked real phase1 Lich. No minimum player melee damage needed before redirect.',eids=[shield,defense,bolt],labels=['MELEE','PROJECTILE'])
    source('projectile_reflect','Player-owned projectile hits native Bolt','twilightforest:lich_bolt',6,'direct reflected Bolt / owner of impacting projectile','Admitted collision and generic Projectile.onHit before its subclass hit callback transfer nonnull owner. Bolt needs Player owner for phase1 Lich. Example ordinary player arrow; original projectile eligibility/impact cancellation applies.',eids=[shield,defense,bolt],labels=['PROJECTILE'])
    source('parry_reflect','Twilight native timed shield parry','twilightforest:lich_bolt',6,'direct Bolt / blocking Player','Server; external parry mod absent; ITFProjectile or configured non-Twilight; entity hit Living; isBlocking and use elapsed<=shieldParryTicks (installed40). AIM transfers owner and impact canceled. Living nonPlayer blocker can parry but reflected Bolt still cannot collide with phase1 Lich.',eids=[shield,defense,bolt],labels=['PROJECTILE','ACTIVE_ITEM'])
    source('scepter','Player Twilight Scepter','twilightforest:twilight_scepter',6,'direct WandBolt / player owner','Native use accepts not fully-used-up item or creative; server launches. Wand inherited canHitEntity and onHit/deflection gates; uncloaked real shielded Lich admits6. No mandatory reflection.',eids=[shield,defense,wand],labels=['ACTIVE_ITEM','PROJECTILE'])
    source('healing_splash','Native splash Healing I/II','minecraft:indirect_magic','int(intensity*(6<<amp)+0.5)>2','direct potion / thrower (null for native dispenser)','Lich is skeletons -> undead -> inverted_healing_and_harm, so HEALING damages and HARMING heals. Potion server splash AABB4/2/4, squared distance<16, isAffectedByPotions; direct target intensity1 else1-distance/4. Native amp0/1 full-hit amounts6/12; distant rounded<=2 fails. No arrow hurt prerequisite.',labels=['THROWN_PROJECTILE','AOE'])
    source('healing_cloud','Native lingering Healing I/II cloud','minecraft:indirect_magic','int(0.5*(6<<amp)+0.5) =3/6','direct cloud / potion Living owner or null','Potion spawns radius3, wait10, radiusOnUse-.5 cloud; native cloud duration/reapplication/radius and potion-affectability gates, every5ticks, in horizontal radius. Half-intensity Healing still strictly>2. No HP success needed for cloud victim cooldown/radius update.',labels=['THROWN_PROJECTILE','AOE'])
    source('fangs','Native Evoker Fangs; accepted Cult Azazel fangs','minecraft:indirect_magic; owner absent minecraft:magic',6,'direct fangs / owner; ownerless magic has neither','Native warmup=-8 and inflated(.2,0,.2) hitbox; alive/noninvulnerable recipient, not owner, nonallied when owner present. Lich can be an incidental eligible recipient of naturally summoned fangs. Shield false prevents owned-fang enchantment post-attack callback.',labels=['SUMMONED_ATTACK','AOE'])
    source('conduit','Fully framed native Conduit','minecraft:magic',4,'no direct or causing entity','Native active water/frame checks;42 effect blocks for attack;40tick server update. Acquire Enemy in water/rain in AABB8; retained target must alive/within8. Lich qualifies as Enemy, but geometry/wet eligibility must genuinely hold. No artificial owner or target assignment.',labels=['ENVIRONMENT'])
    source('sonic','Native Warden sonic boom','minecraft:sonic_boom',10,'direct/causing Warden','Native angry ATTACK_TARGET, cooldown absent, horizontal15/vertical20 range, sound delay34/duration60; Warden canTargetEntity requires same world, Living/noncreative/nonspectator, nonallied, not armorstand/Warden, noninvulnerable/alive/in border. Lich qualifies; cloak still rejects at hurt. Shield false prevents sonic success-dependent additional push.',labels=['MOB_ATTACK','AOE'])
    source('wither_ownerless','Native Wither Skull with unresolved/non-Living owner','minecraft:magic',5,'magic has no direct or causing entity','Server impact and owner not Living. Native persisted/unresolved owner branch is real, but ordinary Living Wither owner uses wither_skull8 and is NOT shield-breaking. Magic shield hit false suppresses Wither status; separate radius1 explosion still follows and can attempt HP after last shield.',labels=['PROJECTILE','EXPLOSION'])
    source('accepted_ice_chunk','Accepted Friends & Foes Iceologer Ice Chunk','minecraft:indirect_magic; owner absent minecraft:magic',12,'chunk / owner; null-owner magic has neither','Reuse accepted package and collision eligibility: alive/noninvulnerable, not owner or owner ally. Eligible incidental Lich collision breaks1; canFreeze gauge400 is independent of false shield hurt. No Friends research repeated.',labels=['SUMMONED_ATTACK','AOE'])
    source('accepted_anvil','Accepted Royal spectral anvil','minecraft:indirect_magic',8,'anvil / owner','Reuse accepted native creation/hover/fall/sweep+AoE. Player owner non-own-pet branch admits nonallied Lich; nonPlayer branch needs Player target or Gaze. Shield false suppresses Heaviness; a later separate sweep/AoE request after final shield may hit HP.',labels=['SUMMONED_ATTACK','AOE'])
    source('accepted_pearl','Accepted player Royal Pearl arrival','minecraft:indirect_magic',7,'pearl / player','Reuse accepted successful permitted native teleport, Enemy nonally in projectile AABB4. Lich Enemy eligible; shield false suppresses Heaviness. Native pearl thrown0 contact neither breaks shield nor gates burst.',labels=['ACTIVE_ITEM','THROWN_PROJECTILE','AOE'])
    source('accepted_enderman','Accepted Royal Enderman teleport splash','minecraft:indirect_magic',4,'RoyalEnderman direct/causing','Reuse accepted successful teleport and AABB4 nonallied Player OR Gaze recipient. A Lich must genuinely have Gaze; without it this path excludes Lich. Shield false suppresses Heaviness.',labels=['MOB_ATTACK','AOE'])
    path('ai_bolts',['BOSS_ATTACK','PROJECTILE','SUMMONED_ATTACK'],'Main Lich and clone Bolt goals',facts[17][1]+' Phase2: if distance<2 performs native melee/cooldown20; else distance<20+LOS launches type(next boolean)/cooldown60; else target teleport/cooldown20. Phase3 melee goal speed.75, golden sword; effective ATTACK_DAMAGE with base3 and held-item modifiers; no custom flat direct HP write.',[bolt,summon,defense],('entity/boss/Lich','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal','entity/projectile/LichBolt'))
    path('ai_bombs',['BOSS_ATTACK','PROJECTILE','EXPLOSION','SUMMONED_ATTACK'],'Main Lich and clone Bomb goals',facts[16][1]+' Native Lich owner means Lich.hurt rejects damage from this explosion in any phase; knockback remains independent.',[bomb,summon],('entity/projectile/LichBomb','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal'))
    path('bomb_parry',['ACTIVE_ITEM','PROJECTILE','EXPLOSION'],'Native TF shield-parried Lich Bomb','Same timed native parry gates; changes bomb owner to blocker and cancels contact. Bomb still never directly collides with Lich. Explosion source lacks shield-break tag, so positive shields reject; exposed Lich can receive non-Lich-owned blast through normal admission.',[bomb,defense],('entity/projectile/LichBomb','events/EntityEvents','entity/boss/Lich'))
    path('bomb_struck',['MELEE','PROJECTILE','EXPLOSION'],'Native directly struck Lich Bomb','Direct source entity required, nonexplosion tag detonates. This does not transfer owner; blast keeps prior owner. IS_EXPLOSION direct source merely returns true; ignoreExplosion and affected-list exclusion normally prevent blast chaining.',[bomb],('entity/projectile/LichBomb','events/EntityEvents'))
    path('phase_minions',['BOSS_ATTACK','SUMMONED_ATTACK','MELEE'],'Phase2 native minion summon and Zombie melee',facts[18][1],[summon,enrage],('entity/ai/goal/LichMinionsGoal','entity/monster/LichMinion'))
    path('minion_enrage',['PROJECTILE','EXPLOSION','SUMMONED_ATTACK'],'Native Lich-owned hit on minion','Any causing Lich (not just master) and inherited hurt true -> Speed200/2+Strength200/1; no HP-loss measurement requirement. Native effect eligibility/merge/expiry/cures and modifier calculations stay intact. Master reference is not damage-source owner: minion melee is caused by minion.',[enrage],('entity/monster/LichMinion',))
    path('pop',['BOSS_ATTACK','AOE'],'Damaged Lich and visible poppable Mob','Custom goal discards first visible eligible mob and heals2 after held-scepter countdown; no DamageSource/hurt/death requirement. #c:bosses removed from poppable tag.',[heal],('entity/ai/goal/LichPopMobsGoal','entity/boss/Lich'))
    path('absorb',['BOSS_ATTACK','SUMMONED_ATTACK'],'Below-half-health Lich and owned minion','Custom goal discards first local owned minion and native heals(minion current HP) after countdown; no LOS or hurt gate.',[heal,summon],('entity/ai/goal/LichAbsorbMinionsGoal','entity/boss/Lich'))
    path('teleport',['BOSS_ATTACK','OTHER'],'Native Lich combat/home teleport triggers',facts[19][1],[teleport,defense],('entity/boss/Lich','entity/boss/Lich$1','entity/boss/Lich$2','entity/ai/goal/LichShadowsGoal','entity/ai/goal/LichMinionsGoal'))
    path('exposed',['MELEE','PROJECTILE','OTHER'],'Native ordinary damage to exposed Lich','Zero shields permits normal HP pipeline during phase2 or3; cloak/clone/Lich-owner guards remain. Tagged phase>1 projectile deflection applies before collision callback with Player/Lich/null owner; other ordinary arrows/melee are not in that deflect tag.',[defense],('entity/boss/Lich',))
    blocked=[
      dict(source='Unreflected main/clone Lich Bolt',reason='Phase1 collision requires Player owner; any causing Lich rejected by hurt in all phases.'),
      dict(source='NonPlayer-reflected/ownerless Bolt',reason='Direction change alone fails Player-owner phase1 collision gate.'),
      dict(source='Lich Bomb / generic magic-tagged custom damage',reason='Not in breaks_lich_shields; blanket NeoForge magic tag is insufficient.'),
      dict(source='Ordinary Healing-tipped arrow into shield',reason='Arrow source untagged; hurt false prevents Arrow.doPostHurtEffects, so instant Healing callback cannot break the shield. Later-phase admitted arrow is different.'),
      dict(source='Harming potion on Lich',reason='Lich skeletons/undead inversion makes Harming heal; healing bypasses the shield damage branch. No shield decrement.'),
      dict(source='Guardian/Elder Guardian beam',reason='Damage1+2Hard+2Elder could exceed2, but native target selector is Player/Squid/Axolotl only, no Lich target. No fabricated setTarget positive control.'),
      dict(source='Poison',reason='Raw magic1 too small; installed NeoForge21.1.244 uses neoforge:poison (not shield tag). Lich ignores Poison via undead tags under ordinary addEffect.'),
      dict(source='Splash water',reason='Only water-sensitive entities receive indirect_magic1; Lich not water-sensitive and1<=2 regardless.'),
      dict(source='Ordinary Living-owner Wither Skull',reason='wither_skull8 source untagged; only the actual non-Living/unresolved-owner magic5 branch qualifies.'),
      dict(source='LootCommand.dropKillLoot',reason='Factory call builds a loot context, never calls hurt; not combat delivery.'),
      dict(source='amount exactly2 / cloak / clone / causing Lich',reason='Explicit counterexamples to tag-only admission.'),
      dict(source='TwilightWandBolt.hurt fallback',reason='Method can redirect/transfer with direct Living source, but Wand is not redirectable/pickable in native tags, so do not claim ordinary Player crosshair melee producer. Native item use is the proven positive path.')]
    resource_data=read_json(WORK/'twilightforest/resources.json')
    raw_resources=read_json(OUT/'vanilla-evidence/royalvariations.json')['resources']
    vanilla_tags={r['entry'].split('/tags/damage_type/')[1][:-5]:r['data']['values'] for r in raw_resources if '/tags/damage_type/' in r['entry']}
    def tag_values(tag,seen=()):
        values=set()
        for v in vanilla_tags[tag]:
            v=v['id'] if isinstance(v,dict) else v
            if v.startswith('#minecraft:'):
                sub=v.split(':',1)[1]
                if sub not in seen:values.update(tag_values(sub,seen+(tag,)))
            else:values.add(v)
        return values
    vanilla_profiles=[]
    for name in ['magic','indirect_magic','sonic_boom','mob_attack','arrow','wither_skull','explosion','player_explosion','in_wall','generic_kill','out_of_world']:
        rid='minecraft:'+name;tags=sorted('minecraft:'+k for k in vanilla_tags if rid in tag_values(k))
        vanilla_profiles.append(dict(type=rid,raw_minecraft_tags=tags,twilight_shield_break_member=name in ['magic','indirect_magic','sonic_boom'],declaration=next((r for r in raw_resources if r['entry']=='data/minecraft/damage_type/'+name+'.json'),None),note='Raw tag closure, reused pinned resources. Twilight custom additions are separate; no raw-profile prose from other reviews is copied. Native mitigation follows each flag; shield counter precedes ordinary mitigation.'))
    profiles=[]
    for typ,cls,method,amount in [('lich_bolt','LichBolt','onHitEntity',6),('lich_bomb','LichBomb','explode','native radius2 float explosion formula'),('twilight_scepter','TwilightWandBolt','onHitEntity',6)]:
        rid='twilightforest:'+typ
        tags=[k.split('/tags/damage_type/')[0].split('/')[-1]+':'+k.split('/tags/damage_type/')[1][:-5] for k,v in resource_data.items() if '/tags/damage_type/' in k and rid in v['data'].get('values',[])]
        profiles.append(dict(type=rid,status='USED',callers=[dict(entry='twilightforest/entity/projectile/'+cls+'.class',method=method)],amount=amount,direct_entity=cls,causing_entity='current owner',native_declaration=resource_data['data/twilightforest/damage_type/'+typ+'.json'],relevant_tags=tags,hurt_return='ignored by producer; separate shield branch returns false',not_tagged=['minecraft:bypasses_shield','minecraft:bypasses_resistance','minecraft:bypasses_enchantments','minecraft:bypasses_invulnerability','minecraft:bypasses_cooldown','minecraft:no_knockback'],tag_scope='Twilight contributions plus previously pinned Minecraft/NeoForge tag closure; no arbitrary datapack assertion'))
    comparison_files=['vanilla-evidence/twilight-lich.json','vanilla-evidence/twilight-lich-tags.json','reference-evidence/twilight-lich-244.json','reference-evidence/vv-loader-244.json','reference-evidence/twilight-frosted-244.json','reference-evidence/royal-loader-244.json','vanilla-evidence/royalvariations.json','vanilla-evidence/royal-final.json','vanilla-evidence/cult-completion.json','reference-evidence/cult-loader-244.json','lich-vanilla-source-audit.json']
    # Accepted producers are reused by exact hash/IDs, not copied or reclassified.
    reuse=[]
    for name,ids in [('friendsandfoes',['friendsandfoes:ice_chunk']),('cultofazazel',['cultofazazel:native_fangs']),('royalvariations',['royalvariations:spectral_anvil','royalvariations:royal_pearl','royalvariations:enderman_splash'])]:
        f='mod-reviews/'+name+'.json';d=read_json(OUT/f);assert set(ids)<={e['id'] for e in d['effects']};reuse.append(dict(evidence_file=f,sha256=sha256(OUT/f),effect_ids=ids))
    section=dict(schema='tno.external_effects.semantic_section.v1',baseline=BASELINE,mod_key='twilightforest',checkpoint=CP,starting_sha=START,status='REVIEWED_SUBSET_NOT_MOD_COMPLETE',subsection_decision='LICH_SEMANTIC_REVIEW_COMPLETE',semantic_coverage_complete=False,promoted_to_catalog=False,
      effects=effects,paths=paths,source_paths=source_paths,blocked_or_conditional_controls=blocked,damage_profiles=profiles,vanilla_damage_profiles=vanilla_profiles,
      requested_semantic_closure=[dict(requirement=i,title=t,conclusion=v,implementation=refs) for i,(t,v) in enumerate(facts,1)],
      comparison_evidence=[dict(evidence_file=f,sha256=sha256(OUT/f)) for f in comparison_files],reused_accepted_producers=reuse,
      source_registration_evidence=native_refs('init/TFEntities','init/TFItems','events/RegistrationEvents','events/EntityEvents','TwilightForestMod'),
      compatibility='Reuse four pinned candidate scans: no direct Twilight-specific name hits. Generic owner/recipient hooks only apply where their native dispatcher is reached. Lich shield early false never enters Living incoming/pre/post damage pipeline, so no power/umbrella/vampiric/etc rewrite is assumed for that counter. Exposed HP processing, Player victims of bolts/bombs, and minion effect application keep native generic hooks. No pack-wide guarantee.',
      exclusions=['295tick death animation is client presentation; BaseTFBoss performs server removal later, not another damage aura.','Nearby candle/Lightable lighting conversion has no damage callback in inspected implementations; omitted as separate combat effect. Home support-block placement and clear-fire teleport are retained.','Scepters visibly equipped by AI are not calls to Player item.use: AI has explicit goal/projectile/discard-heal implementations.','No runtime positive controls executed; all source cases are native static delivery proofs/future fixtures.'],
      counts=dict(reviewed_packages=len(effects),delivery_cases=len(paths),shield_source_cases=len(source_paths),review_required=0,promoted=0),exact_next_task=NEXT,**boundary_flags())
    write_json(OUT/'semantic-sections/twilightforest-lich.json',section)
    prior=read_json(OUT/'partial-drafts/twilightforest-r2f2-partial.json')
    combined=deepcopy(prior);combined.update(checkpoint=CP,starting_sha=START,effects=prior['effects']+effects,paths=prior['paths']+paths)
    write_json(OUT/'partial-drafts/twilightforest-r2f3-partial.json',combined)
    review=read_json(OUT/'mod-reviews/twilightforest.json');review.update(checkpoint=CP,scope='Frosted and complete Lich subsections reviewed; whole Twilight mod remains PARTIAL with zero final records promoted.',draft_file='partial-drafts/twilightforest-r2f3-partial.json',notes_file='semantic-sections/twilightforest-lich.json',draft_mechanic_count=len(combined['effects']),draft_path_count=len(combined['paths']),exact_next_task=NEXT)
    write_json(OUT/'mod-reviews/twilightforest.json',review);refresh(CP)
    for name in ['effect-catalog.json','effect-sources.json','delivery-path-matrix.json','vanilla-comparison.json','behavior-primitives.json']:
        d=read_json(OUT/name);d.update(checkpoint=CP,unfinished_review=dict(mod_key='twilightforest',status='PARTIAL',draft_file=review['draft_file'],promoted_records=0));write_json(OUT/name,d)
    decision=read_json(OUT/'research-decision.json');decision.update(checkpoint=CP,save_mode=False,save_reason=None,next_task=NEXT,lich_decision='LICH_SEMANTIC_REVIEW_COMPLETE',recovery_lich=dict(local_start=START,live_remote_start=START,working_tree_start='CLEAN',divergence='0/0',newer_work=False,restarted_research=False));decision['checkpoints'][CP]='Self: exact SHA reported after push/live verification.';write_json(OUT/'research-decision.json',decision)
    lines=['# R2f3 — LICH_SEMANTIC_REVIEW_COMPLETE','','Installed Twilight Forest4.8.3345, Minecraft1.21.1, NeoForge21.1.244. Static native review only; no boss/runtime/L2 testing. Frosted is unchanged. Twilight remains PARTIAL.','',f'{len(effects)} reviewed package drafts / {len(paths)} delivery cases / {len(source_paths)} shield-source cases. Zero final Twilight promotions.','', '## Requested semantic closure','']
    for i,(title,value) in enumerate(facts,1):lines.extend([f'### {i}. {title}','',value,''])
    lines.extend(['## Source admission table','','All eligible rows also require the Lich gates above. Requests are not measured HP loss. This table covers native Twilight/Minecraft plus accepted earlier mod producers; future unreviewed mods and dynamic datapacks can add producers.','', '| Source | Native type / amount | Exact prerequisites |','|---|---|---|'])
    for row in source_paths:lines.append('| '+row['source']+' | '+row['damage_type']+' / '+str(row['amount'])+' | '+row['native_prerequisites']+' |')
    lines.extend(['','## Rejected or conditional controls',''])
    for row in blocked:lines.append('- **'+row['source']+':** '+row['reason'])
    lines.extend(['','## Package review','', '| Package | Classification |','|---|---|'])
    for e in effects:lines.append('| '+e['display_name']+' | '+e['primary_classification']+' |')
    lines.extend(['','## Evidence and boundary','','[Machine-readable section](semantic-sections/twilightforest-lich.json), [native witnesses](native-evidence/twilight-lich.json), [exact loader references](reference-evidence/twilight-lich-244.json), [raw references](vanilla-evidence/twilight-lich.json), [source census](lich-vanilla-source-audit.json), [integrity validation](twilightforest-lich-integrity.json), [full validation](r2f3-lich-validation.json).','',section['compatibility'],'','Exact next task: '+NEXT,''])
    (OUT/'twilightforest-lich-review.md').write_text('\n'.join(lines),encoding='utf-8')
    print(json.dumps(section['counts']))

if __name__=='__main__':build()
