from catalog_common import *
from cataclysm_combat_common import save_section

START='2c104d7322a08307d05e013382b9ed038227a0e6'
CP='R2k2c-cataclysm-ghost-fear-complete'
STEM='cataclysm-r2k2c-ghost-fear'
NEXT='R2k2d: Cataclysm remaining seven statuses: Monstrous, Blazing Brand, Abyssal Burn, Bone Fracture, Abyssal Curse, Curse of Desert and Wetness. Trace numeric/DOT/source and event modifiers plus real application sites. Reuse shared boss, STUN and Ghost/Fear contracts; full bosses/projectiles/equipment remain pending. Continue automatically while quota healthy; static only.'
FACTS={
 'scope':'Four effects (Ghost Form, Ghost Sickness, Abyssal Fear, Blessing of Amethyst), native Cursium chestplate rebirth and associated food healing are reviewed. Nine installed class witnesses, three selected loader classes and the accepted native food/Regeneration dependency pin the contracts. All12 field-reference methods have a disposition. Full Abyss Mine/Orb launch and Leviathan attack schedules remain family work; their effect-side delivery is distinguished here. Together withR2k2b, five of twelve Cataclysm effect cores are reviewed.',
 'rebirth':'LivingDeathEvent handler first requires source NOT BYPASSES_INVULNERABILITY, then tryCursiumPlateRebirth. Recipient must be in ServerLevel, wear exact CURSIUM_CHESTPLATE in CHEST, and have neither Ghost Sickness nor Ghost Form. It setsHealth(5), requests Fire Resistance200amp0, requests Ghost Form100amp0 (ambient=false,particles=true,icon=true), then returns true so death is canceled. The native setHealth clamps to[0,maxHP]; it is a fixed revival state, not heal(5) and not a LivingHealEvent. Abyssal Fear therefore does not veto this assignment through BlockHeal. Preserve fixed5 and binary death admission, no Stage multiplier on this state reset. No item consumption/durability or separate timer is used by this helper.',
 'rebirth_effect_failures':'Neither addEffect return controls revival success. If Ghost Form admission fails, health reset and death cancellation still happen; no guaranteed protection or future Sickness follows. Its only repeat-prevention checks here are current Form/Sickness presence. Early removal of Form or failed Form/Sickness admission can therefore permit another native chestplate revival once neither is present. Do not fabricate a cooldown/resource or repair this path. Preserve death-event composition with other mods and maxHP clamp; event priority/other listeners can affect runtime.',
 'ghost_form':'Beneficial Ghost Form adds MOVEMENT_SPEED +0.4*(amplifier+1) ADD_MULTIPLIED_TOTAL under cataclysm:ghost_speed. ServerEventHandler cancels LivingIncomingDamageEvent while recipient has Form unless source BYPASSES_INVULNERABILITY. It also cancels the Player attack event and use-item Start, and sets base use-item event duration0. No Form canAttack mixin, no direct entity NoAI/noPhysics, and no universal prohibition of already-scheduled/direct hurt producers are present in this slice. Rendering transparency is cosmetic. Binary immunity/actions and speed/duration stay native; no extra Stage.',
 'ghost_expiry':'EffectGhostForm.shouldApply stores its argument in the registered effect object lastDuration and returns argument>0. applyEffectTick requests Ghost Sickness7200amp0 with particles=false/icon=true only when stored argument==1. Native finite MobEffectInstance.tick calls shouldApply with remaining duration, immediately calls apply, then decrements, so ordinary100tick Form attempts Sickness on its last tick before expiry. It is not an on-remove callback: early cure/explicit removal does not itself schedule Sickness. For native infinite instances the argument is recipient.tickCount, not remaining duration, so do not generalize to a universal expiry trigger. Normal native tick ordering is pinned; no concurrency effect inferred.',
 'sickness':'Harmful Ghost Sickness has no damage, movement modifier or resource drain in applyEffectTick (returns true); its combat role is the rebirth presence gate. The50>>amplifier callback cadence does not imply periodic damage. fillEffectCures is empty rather than calling the default extension, so native instances start with no ordinary cure entries. removeEffectsCuredBy requires the cure to exist in that set before the removal event. Thus ordinary cure-based removal is excluded by that mechanism; it is distinct from explicit removeEffect/removeAllEffects.',
 'removal_mismatch':'ServerEventHandler.preventEffectRemoval compares effectInstance.getEffect() == ModEffect.EFFECTGHOST_SICKNESS.get(). The first is a Holder; the second is the registered EffectGhost_Sickness MobEffect value, which is not that Holder. Its identity test is false for the native effect instances, so this listener does NOT prevent explicit removal. Patched removeEffect/removeAllEffects still post normal removal events and other listeners can veto. Natural expiry is not prevented by this code. Keep empty cure-set admission and ineffective explicit-removal listener separate; no immunity repair is authorized.',
 'fear':'Abyssal Fear is harmful and its own tick does no damage. BlockHeal cancels LivingHealEvent whenever recipient has Fear, irrespective of heal amount/amplifier/source and without a new duration/amplifier scaling rule. Native LivingEntity.heal passes through EventHooks.onLivingHeal before adding HP, so normal healing, Regeneration and boss heal calls are subject to this veto. Direct native setHealth state changes such as Cursium rebirth do not route through heal. Do not describe Fear as blocking every possible HP increase or bypass its veto with a fallback.',
 'mine_delivery':'After server warmup decrements below-20, Abyss Mine enumerates LivingEntities intersecting its box inflated(.2,0,.2). explode(candidate) requires candidate alive. With resolved Living caster, it excludes caster/allies, calls native Level.explode(caster,...,radius1,NONE), then applies Fear200amp0 with null effect-source and discards. Without caster it explodes using mine entity and still applies Fear200amp0. The Fear request is NOT gated by explosion damage success and occurs after blast; there is no second alive check. The enclosing candidate loop has no break/removal guard, so multiple captured candidates can still call this method; retain a future multi-target fixture rather than assuming one blast. Caster UUID and warmup persist, caster resolves server-side; unresolved owner follows the actual caster-null branch. Full damage/source closure and originating summons stay in Leviathan review.',
 'orb_delivery':'Abyss Orb entity impact invokes super then, server-side, rejects Leviathan/LeviathanPart hits only when current owner is Leviathan. With Living owner it requests native mobProjectile(orb,owner), amount getDamage(); otherwise anonymous native magic with getDamage(). Only hurttrue plus Living victim applies Fear100amp0 with native getEffectSource (owner or orb). Afterward native radius1 explosion using owner and discard occur regardless of hurt result in this admitted impact branch. Thus contact Fear, contact HP and explosion HP are independent observations; block impacts have no Fear call. Owner/alliance/launch/secondary blast source details remain projectile family review; no fabricated source.',
 'blessing':'Blessing of Amethyst is beneficial; every positive-duration tick independently checks and attempts native removal of Abyssal Burn, Abyssal Fear and vanilla Darkness in that order. Removal return is ignored, so vetoed effects can be retried on subsequent ticks; other statuses are untouched. It neither prevents initial application nor grants blanket immunity. Same-tick effect iteration order can determine whether a healing/DOT tick happens before cleanse; runtime must observe rather than assume priority. Shared boss whitelist omits Blessing and Fear/Form while including Sickness, subject to actual concrete/native/external admission.',
 'food':'Exact blessed_amethyst_crab_meat ModItems supplier lambda$static$226 installs native food effects Regeneration100amp0 and Blessing1800amp0, each chance1, and alwaysEdible. Its subclass adds only foil/tooltip; native food addEffect admission remains. Regeneration is a separate native heal1 callback at50tick cadence for amp0 when HP<max, subject to heal veto/max/alive processing; reuse the accepted vanilla Regeneration contract. Future Stage belongs once on that positive native heal amount, not food effect duration, application chance, modifier or cleanse. Blessing may remove Fear before later regeneration, but same-tick heal success is not promised.',
 'compatibility':'No new DamageType belongs to these four effects themselves. Parent mine/orb HP stays at each original native producer and is deferred rather than multiplied at Fear application. Keep event cancellation, cure-set eligibility, native holder/value mismatch, death cancellation, source identity, fixed revival HP and effect add/remove returns intact. Future fixtures remain NOT_RUN; no runtime, L2, Stage, production, Phase6 or Phase7 change.'
}

def save():
    defs=[('rebirth','ARMOR','Native death -> Cursium chestplate -> HP state5 and effects -> canceled death',['server and chest exact item','bypass-invulnerability exclusion','Form/Sickness presence','maxHP<5','effects rejected still revival']),('ghost_incoming','OTHER','Native incoming-damage event with Ghost Form -> cancel',['ordinary vs bypass tag','incoming amount/HP separate','source unchanged']),('ghost_actions','OTHER','Form player attack/use Start/base events',['already scheduled attacks','Start vs Tick/Stop/Finish','speed modifier cleanup']),('ghost_expiry','OTHER','Native finite Form tick duration1 -> Sickness7200 request',['normal100tick expiry','early remove/cure does not trigger','Sickness admission rejected']),('sickness_cure','OTHER','Native cure-set removal -> empty Sickness cures',['cure absent vs explicitly modified cure set','natural expiry','rebirth presence gate']),('sickness_explicit_remove','OTHER','Explicit native removeEffect/removeAllEffects -> Remove listener',['Holder/value test false','other listener veto','repeat revival after removal']),('fear_heal','OTHER','Native heal/Regeneration with Fear -> LivingHealEvent veto',['normal/boss/food healing','direct native revival assignment differs','amplifier does not scale veto']),('fear_mine_owned','ENVIRONMENT','Living-caster native mine contact -> explosion then Fear200',['alive/nonallied/noncaster','hurt result independent','multiple candidates after discard']),('fear_mine_unresolved','ENVIRONMENT','Caster-null native mine contact -> explosion then Fear200',['persisted UUID unresolved','null effect-source','no postblast alive gate']),('fear_orb_owned','PROJECTILE','Living-owned orb contact native mobProjectile hurttrue -> Fear100',['Leviathan owner/part exclusion','effect source owner','secondary blast even on hurtfalse']),('fear_orb_unowned','PROJECTILE','Non-Living/null owner orb native magic hurttrue -> Fear100',['anonymous damage vs owner-or-orb effect-source','block-hit no Fear','secondary blast independent']),('blessing_food','ACTIVE_ITEM','Blessed Amethyst Crab Meat food -> Blessing1800 and native tick cleanse',['admission and removal veto','Burn/Fear/Darkness only','same-tick effect order']),('crab_regeneration','ACTIVE_ITEM','Same blessed food -> Regeneration100amp0 -> native heal1',['Fear veto vs later cleanse','native50tick cadence/maxHP','one Stage heal boundary later'])]
    paths=[dict(id='cataclysm:ghost_fear:'+n,labels=[l],native_path=p,runtime_status='NOT_RUN',runtime_variants=v) for n,l,p,v in defs];ids={n:p['id'] for (n,*_),p in zip(defs,paths)}
    def m(id,name,cl,keys,point=None):return dict(id='cataclysm:'+id,name=name,primary_classification=cl,tno_categories=['COMPOSITE','ADMISSION_GATED']+(['NUMERIC_SCALABLE','VANILLA_ROUTED'] if point else ['NO_STAGE_VALUE','CUSTOM_ROUTED']),stage_scaling_needed=point is not None,single_scaling_point=point,stage_reason='Native binary control/admission, fixed revival state, effect duration/modifier or presence resource.',delivery_paths=[ids[k] for k in keys])
    pk=[m('cursium_rebirth','Native Cursium chestplate revival state','BINARY_MECHANIC',['rebirth']),m('ghost_form','Ghost Form native immunity/actions and expiry delivery','CUSTOM_STATUS',['ghost_incoming','ghost_actions','ghost_expiry']),m('ghost_sickness','Ghost Sickness cure set and revival exclusion','CUSTOM_STATUS',['sickness_cure','sickness_explicit_remove']),m('abyssal_fear','Abyssal Fear heal-event veto and delivery','CUSTOM_STATUS',['fear_heal','fear_mine_owned','fear_mine_unresolved','fear_orb_owned','fear_orb_unowned']),m('amethyst_blessing','Blessing of Amethyst selective native cleanse','CUSTOM_STATUS',['blessing_food']),m('blessed_crab_regen','Blessed food native Regeneration healing','VANILLA_LIKE_EXTENDED',['crab_regeneration'],'Once on positive native RegenerationMobEffect.applyEffectTick heal(1) amount, preserving HP/cadence/effect and heal-event admission; no additional food/status scale.')]
    dispositions=[dict(entry=r['entry'],method=r['method'],descriptor=r['descriptor'],disposition='REVIEWED_GHOST_FEAR_BLESSING_SLICE_OTHER_MECHANICS_REMAIN_FAMILY_WORK') for r in read_json(OUT/'cataclysm-ghost-fear-usages.json')['rows']]
    d=dict(schema='tno.external_effects.cataclysm_ghost_fear.v1',checkpoint=CP,previous_checkpoint='R2k2b-cataclysm-stun-contract-complete',starting_sha=START,status='GHOST_FEAR_BLESSING_CONTRACTS_COMPLETE',scope='Four status cores plus Cursium revival and Blessed Crab food paths; full Leviathan damage/launch families remain pending.',summary='Separated fixed HP revival, Ghost immunity/expiry, empty Sickness cure set versus ineffective removal listener, Fear healing veto, and native Blessing cleanse. Six packages/thirteen future paths; no repair.',facts=FACTS,mechanic_packages=pk,delivery_paths=paths,reference_dispositions=dispositions,review_required=[dict(id='cataclysm-ghost-fear-runtime',reason='Observe effect rejection/early removal and repeated native revival, death-event composition, native cures vs explicit removal, and same-tick cleanse/heal/DOT ordering. No runtime certification or repair.')],remaining_subsection_native_ambiguities=[],exact_next_task=NEXT,references=['native-evidence/cataclysm-ghost-fear.json','reference-evidence/cataclysm-ghost-fear-244.json','cataclysm-ghost-fear-usages.json','reference-evidence/cataclysm-stun-244.json','vanilla-evidence/bomd-equipment.json','reference-evidence/bomd-equipment-244.json','cataclysm-r2k2a-shared-admission.json','annotation-evidence/cataclysm-foundation-javap.json'])
    save_section(d,STEM,'R2k2c — Cataclysm Ghost, Fear and Blessing')

if __name__=='__main__':save()
