from copy import deepcopy
from catalog_common import *
from bossesrise_combat_common import save_section
CP='R2i8c-bossesrise-equipment-complete'
STEM='bossesrise-r2i8c-equipment'
START='c3d8a805a66baf3333e94fa92090524acb290301'
NEXT='R2i9: reconcile whole-JAR watched methods and source/entity closure, including anonymous melee-goal admission for Knight arena mobs and Dragon guardians. Apply evidence-backed additive corrections, deduplicate/promote Bosses Rise, resolve both custom DamageTypes, run full catalog validation and protect completion. No runtime work.'
FACTS={
'armor_buffs':'DragonArmorEvents.onPlayerTick is PlayerTick.Post, ServerPlayer only, gameTime%20==0. Exact equipped Dragon leggings while crouching request native Speed40 amp2 and FireResistance40 amp0. Exact full skull/chest/legs/boots requests Strength40 amp0 and Resistance40 amp0. Real addEffect/Applicable admission and Roll veto remain, including beneficial effects; native attributes and Resistance influence ordinary combat downstream. No outgoing HP request here, and no extra Stage factor on amplifier/duration/attributes. Skull NightVision60amp0/flashing helper is utility/cosmetic, excluded briefly.',
'post_admission':'onPlayerHurt is LivingDamageEvent.Post for ServerPlayer. Checks exact equipped boots first then chest. No event amount>0, source-is-fall, cooldown or recursive guard in handler. Patched Player.actuallyHurt invokes Post after the f1!=0 HP-change block, so reaching this native event does not require positive HP loss (e.g. full absorption); incoming cancellation/invulnerability can prevent reaching it. Do not turn a synthetic event into a delivered path. Native runtime fixtures must use genuine admitted incoming hits and record actual Post/result ordering.',
'boots_explosion':'Boots require fallDistance>=3 and max(knownMovement dot down, deltaMovement dot down)>=.5. Radius clamps that downward speed to[0,4.5]. Calls level.explode(player,playerPosition,radius,NONE), then immediately Explosion.explode() on the returned SAME object. Pinned Level final overload constructs explosion, checks Neo onExplosionStart, normally invokes explode then finalizeExplosion; ServerLevel returns it after packet handling. Thus normally two damage/detonate/control passes, one finalization. If Neo start cancels the first pass, Level returns the same object and mod still invokes explode explicitly once; no second start check. Every actual Explosion.explode still calls native detonate, calculator/exposure, hurt and impulse logic. This is an existing native cancellation inconsistency, not a proposed bypass. Source is player_explosion with direct/causing wearer; NONE keeps blocks and fire flag isfalse. Native hurt cooldowns/geometry may suppress repeat HP: do not assert doubled HP. Future Stage belongs once at each actual explosion per-victim hurt request, never radius or two hook layers. Existing native control impulse remains independent from hurt success. Multiple equipped victims can enter their own native Post handlers; preserve this test case without adding recursion or runtime tests now.',
'boots_ignition':'After explosion call(s), getNearbyPlayers(DEFAULT,wearer,full-side4 box at wearerPosition). Native EntityGetter tests player position in box; DEFAULT forCombat excludes self, unseen/dead/spectator, cannotAttack/cannotAttackType and allies. Its LOS check applies only when attacker is Mob; wearer is Player, so no block LOS test here. Each selected other player setRemainingFireTicks250 directly; not a MobEffect, not conditional on explosion hurttrue, and no FireResistance/fireImmune check at write. Direct counter writes bypass the duration helper/attribute, but later native on_fire HP still respects native admission. Reuse proven-origin native burning Stage point, never fire duration. No boss/mob ignition from this particular player-only loop.',
'chest_retaliation':'Chest Post branch independently passes Math.random<=.1, requires direct DamageSource entity instanceof Projectile, uses projectile.owner when nonnull else source.causing entity, requires nonnull cause and cause.distanceTo(wearer)>=3. No source-tag projectile inference, amount threshold or hurt-return test. Creates real BlazingFireBallEntity owner wearerPlayer, baseDamage1, silent, eyesY-.1, aimed at cause.position plus independent[-.5,.5) jitter, speed1.5/inaccuracy3; insertion result ignored. Reviewed native arrow direct HP, independent hit FireArea, block radius2 NONE explosion, proximity ignition and later burning are reused unchanged. The retaliating owner is defender, not original shooter. Multiple native projectile hits require independent random trials; no fabricated positive control.',
'knight_sword':'Native use requires item off cooldown then starts use(duration1200). Server Player release charge<5 makes0 waves; otherwise min(((charge-5)/20)*2+1,7), thresholds5/25/45/65 for1/3/5/7. Native cooldown80 only when waves>0. Each real SwordWave ownerPlayer/base5/KB0/silent/eyesY-.1/speed2/inaccuracy0; no release durability cost. No spread or deferred schedule in this item loop. Reuses exact SwordWave indirect_magic ceil(speed*base) hit and hurttrue status logic; do not multiply item attack13 into projectile or scale wave count. Native projectile overlap/iframes determine total HP. Ordinary melee attributes remain native.',
'pirate_saber':'Native ItemUtils.startUsingInstantly/BOW, duration14 -> finishUsingItem. Server creates one CrossbowPirate with native crossbow and one Rook with PirateSaber, positions one block at horizontal +/-90deg view, ownerUUIDPlayer, skipXP; direct construction/addFreshEntity, no finalizeMobSpawn and no explicit collision/LOS/cap/expiry check. Add results ignored. Player item-used stat and cooldown80; costs10 durability unless infinite materials. Standard use dispatch cooldown is preserved; do not manually call finish to bypass it. Summons retain own attributes/gear, own timed mob_attack or native crossbow arrow causes, not the player as source; no owner-to-projectile source rewriting. Owner UUID persists; shouldDropLoot false when owned; these two classes have no Ghost age200 expiry. Protected ownership target helpers exclude owner/shared resolved owner independently from damage immunity. Existing AI/timed/crossbow/control paths reused; no new Stage at summon.',
'ordinary_equipment':'Knight armor builds native default armor modifiers plus slot-specific rollCount+1. Dragon chest/legs/boots similarly add rollCount+1 and BURNING_TIME-2 ADD_VALUE; Dragon skull BlockItem explicitly installs head roll+1/BURNING_TIME-2/armor+3/toughness+2. Native IItemStackExtension uses explicit ATTRIBUTE_MODIFIERS when nonempty else item default modifiers, then Neo computeModifiedAttributes; no unconditional stacking with replacement components. DragonGuardShield is actual ShieldItem with offhand movementSpeed-.01/armor+1/toughness+2. EnhancedShield extends ShieldItem but constructor has onlydurability450; its static roll+1 createAttributes has no installed caller and is not installed in properties/override, so do NOT promote a roll bonus. All shield blocking/bypass sources remain native. Warrior/Large/Dagger ordinary damage/speed/reach modifiers and animation only; Dagger dual-hand animation is not a second damage callback. AnimatedSword swing hook empty unless override; Knight override empty. No mod-specific extra Stage for ordinary melee/equipment attributes. DragonShank native food and bone remainder, materials/repair/render/mining animations are short exclusions, not new combat mechanics.',
'compatibility_scope':'Only native damage requests are future numeric Stage candidates. Do not scale buffs, random chance, summon count, armor, Roll charges, ignition time, exposure or explosion radius. Native physical/magic/projectile/fire/explosion source tags and their admission are unchanged. Armor retaliation extends existing hazard identities and runtime paths. No Stage/production/runtime changes; whole-mod closure still required.'
}

def save():
    defs=[('armor_buffs','ARMOR_PROC','Equipped crouch/fullset native addEffect at20tick cadence'),('post_zero','ARMOR_PROC','Real native Post including zero net HP after absorption'),('boots_normal','ARMOR_PROC','Fall-distance/momentum Post -> normally two native explosion passes'),('boots_start_cancel','ARMOR_PROC','Native start cancellation -> explicit returned-object explosion pass still occurs'),('boots_ignite','ARMOR_PROC','After explosion -> DEFAULT nearby other players direct fire250'),('boots_burn','OTHER','Native on_fire from genuine boots ignition'),('chest_launch','ARMOR_PROC','Native direct-projectile Post random<=.1 -> defender-owned fireball'),('chest_arrow','PROJECTILE','Retaliatory Blazing native inherited arrow'),('chest_area','AOE','Independent native Blazing impact FireArea'),('chest_explosion','AOE','Retaliatory block hit native radius2 NONE explosion'),('chest_pool','AOE','Spawned FireArea native in_fire1.5'),('chest_burn','OTHER','Retaliatory proximity/area native ignition -> on_fire'),('sword_wave','ACTIVE_ITEM','Charged real Knight Sword release ->1/3/5/7 ownerPlayer waves'),('sword_status','PROJECTILE','Successful native wave non-Enderman Slowness'),('saber_summon','SUMMONED_ATTACK','Native14tick PirateSaber use -> Player-owned Rook/CrossbowPirate'),('saber_rook','SUMMONED_ATTACK','Rook own-source timed attribute mob_attack'),('saber_crossbow','SUMMONED_ATTACK','CrossbowPirate real crossbow arrow, own shooter'),('saber_control','SUMMONED_ATTACK','Rook blocking cooldown and independent raw push'),('equipment_attrs','OTHER','Actual native equipped/default component modifiers and rollCount'),('shield_use','ACTIVE_ITEM','DragonGuard/Enhanced ordinary native ShieldItem blocking'),('ordinary_melee','MELEE','Warrior/Large/Dagger native melee, no extra animated hit')]
    paths=[dict(id='br:equipment:'+n,labels=[label],native_path=desc,runtime_status='NOT_RUN',runtime_variants=['Native input/event/source and admission','Distinct callback result, owner and equipment component state']) for n,label,desc in defs];ids={n:p['id'] for (n,*_),p in zip(defs,paths)}
    prior={m['id']:m for f in ['bossesrise-r2i3b-knight-offense.json','bossesrise-r2i4-infernal-dragon.json','bossesrise-r2i7b-kraken-offense.json'] for m in read_json(OUT/f)['mechanic_packages']};pk=[]
    reuse=[('dragon_burning',['boots_burn','chest_burn']),('blazing_arrow',['chest_arrow']),('blazing_area_delivery',['chest_area']),('blazing_explosion',['chest_explosion']),('fire_area',['chest_pool']),('sword_wave',['sword_wave']),('knight_slow',['sword_status']),('pirate_melee',['saber_rook']),('pirate_crossbow',['saber_crossbow']),('pirate_control',['saber_control'])]
    for i,keys in reuse:
        m=deepcopy(prior['br:'+i]);m.update(delivery_paths=[ids[k] for k in keys],extends_existing_package=True);pk.append(m)
    groups=[('dragon_armor_buffs','Dragon armor native buffs and equipment modifiers','VANILLA_LIKE_EXTENDED',['armor_buffs','equipment_attrs','shield_use','ordinary_melee'],None),('dragon_armor_trigger','Dragon armor native Post retaliation/ignition admission','CUSTOM_RESOURCE',['post_zero','boots_ignite','chest_launch'],None),('dragon_boots_explosion','Dragon boots native repeated explosion request','VANILLA_LIKE_EXTENDED',['boots_normal','boots_start_cancel'],'Native Explosion.explode final per-victim hurt for the actual boots explosion origin, once per request; preserve native two-pass behavior and do not scale radius.'),('pirate_saber_summon','Pirate Saber native owned summon delivery','CUSTOM_RESOURCE',['saber_summon'],None)]
    for i,name,cl,keys,point in groups:pk.append(dict(id='br:'+i,name=name,primary_classification=cl,tno_categories=['COMPOSITE','ADMISSION_GATED','NUMERIC_SCALABLE' if point else 'NO_STAGE_VALUE'],stage_scaling_needed=bool(point),single_scaling_point=point,stage_reason='Native explosion HP request once.' if point else 'Native admission/control/resources/ordinary attributes, no additional HP scaling here.',delivery_paths=[ids[k] for k in keys]))
    d=dict(schema='tno.external_effects.bossesrise_equipment.v1',checkpoint=CP,previous_checkpoint='R2i8b-bossesrise-tentacle-trident-complete',starting_sha=START,status='DRAGON_ARMOR_REMAINING_COMBAT_EQUIPMENT_COMPLETE',scope='Dragon armor actual native Post/buff callbacks; Knight Sword/Pirate Saber delivery; native shield/ordinary equipment exclusions.',summary='Dragon boots normally run the same explosion twice and still invoke the explicit pass after start cancellation. Retaliatory fireballs, player SwordWaves and saber-owned pirates reuse reviewed native payloads.',facts=FACTS,mechanic_packages=pk,delivery_paths=paths,unexecuted_future_fixtures=['native_Post_zero_after_absorption_vs_incoming_veto','boots_fallDistance3_downmomentum_half_nonfall_source','boots_native_two_detonate_passes_hurtcooldown_separatecontrol','boots_start_cancel_still_explicit_nativepass_no_synthetic_event','boots_nearbyplayer_targeting_noPlayerLOS_firewrite_vsnativeonfire','multiple_boots_wearers_native_Post_interaction','chest_random_projectiledirect_ownerfallback_range3','defender_owned_Blazing_base1_native_hitfalse_hazard_blockexplosion','armor20tick_crouch_fullset_native_Applicable_Roll_veto','replacement_ATTRIBUTE_MODIFIERS_vs_default_and_rollCount','EnhancedShield_absent_rollhelper_vs_DragonGuard_nativeblocking','KnightSword_charge5_25_45_65_nativeWave_iframes_owner','PirateSaber14tick_cooldown80_dur10_infinite_materials','owned_Rook_Crossbow_no_Ghost_expiry_source_targeting_savedowner'],review_required=['Future origin attribution for native fire ticks and shared explosion callbacks remains an integration decision; native source/admission must be preserved.','Native boots bypass of ExplosionEvent.Start for explicit pass is documented only; no compatibility correction authorized.'],remaining_subsection_native_ambiguities=[],exact_next_task=NEXT,references=['native-evidence/bossesrise-equipment.json','bossesrise-equipment-helper-census.json','reference-evidence/bossesrise-equipment-244.json','vanilla-evidence/bossesrise-equipment.json','reference-routing/bossesrise-equipment.json','bossesrise-r2i3b-knight-offense.json','bossesrise-r2i4-infernal-dragon.json','bossesrise-r2i7b-kraken-offense.json','native-evidence/bossesrise-shared.json','bossesrise-kraken-source-profiles.json'])
    save_section(d,STEM,'R2i8c — Bosses Rise Dragon armor and remaining combat equipment')
if __name__=='__main__':save()
