"""Loyal Zombie and real scepter resources; separate native repair routes."""
from catalog_common import *
from collect_twilight_summon_resources import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed TF4.8.3345, raw Minecraft1.21.1 and exact NeoForge21.1.244. Real owned-mob use/AI, native EXPIRED self-hurt and native crafting/enchantment callbacks only. Request, final HP, motion, effect lifetime and item charges are separate. No runtime/L2/Stage/production change. Other scepter unique payloads remain protected or explicitly pending.',
      'summon':'ZombieWand is the actual survival producer of registered LoyalZombie; no egg/world producer in all-TF field-caller census. Capacity9. Use fails damage==max && !instabuild; exact244 default damage getters/setters clamp0..max, so no ordinary overshoot exploit inferred. Server native POV ray uses Player eye/look, current blockInteractionRange, OUTLINE/Fluid.NONE. Non-MISS creates LoyalZombie at exact hit location, requires noCollision(entity,itsBB), else PASS without cost. spawnAnim, setTame(true,false), Player ownerUUID, Strength1200/amp1, optional baby, addFreshEntity, ENTITY_PLACE and noncreative durability request1. Add return ignored: later denied add does not gate cost. No finalizeSpawn, injected gear/target, bespoke cap or cooldown. Client/MISS sided success without server summon/cost.',
      'loyal_body':'TamableAnimal, registered category MONSTER, HP40/speed.3/armor3, dimensions.6x1.95, not fireproof. Actual supplier LoyalZombie.registerAttributes starts Mob base, NOT Zombie, adds no ATTACK_DAMAGE. TF zombies tag/native undead nesting does not import Zombie sun burning, reinforcement or conversion. No phase/regen. dropExperience empty, native loot table empty; isFood=false, offspring null. removeWhenFarAway=!isTame, so genuine scepter tame avoids normal far-away despawn. No Lich master/shared HP.',
      'loyal_hit':'doHurtTarget requests fixed7 minecraft:mob_attack, direct=causing=LoyalZombie, NOT summoner. Only true then raw push(0,.2,0), not scaled by knockback resistance. False no push. No ATTACK_DAMAGE/Strength/Weakness read, super Mob melee, enchantment modify/post-attack helper or weapon callback. Native recipient events/admission remain; tame-owner kill credit is separate from source identity. Strength1200/1 is a lifetime marker, not +6 here. Native melee goal20 cadence, eligibility, armor/shield/Resistance/protection/cooldown/absorption and Player difficulty remain. Extra motion uses ordinary later fall, no TF throw marker.',
      'loyal_expiry':'Before super.aiStep: server && Strength absent && tickCount%20==0 -> self.hurt(ownerless twilightforest:expired,2), return ignored. No separate lifetime counter/owner-distance gate or explicit alive check; native hurt still rejects dead/invalid state. ANY present Strength amplifier/duration suppresses branch, including genuine admitted splash/lingering potion or AreaEffectCloud. Removal/expiry enables next modulo20 request. Standard spawn/feed1200ticks/amp1 uses native loaded effect ticking, not wall-clock countdown. Effects/health/owner persist, tickCount phase separate. No HP subtraction or guaranteed death time; exactly one actual EXPIRED combat caller.',
      'expired_source':'EXPIRED exhaustion0/default when-caused-by-living-non-player scaling; direct/causing/position null, no owner difficulty scaling. Transitive tags: bypasses_armor, bypasses_shield, bypasses_wolf_armor, bypasses_invulnerability, bypasses_resistance, always_most_significant_fall, neoforge:is_technical. Not is_fall, no_knockback, bypasses_cooldown/effects/enchantments. Native armor/shield/Resistance/invulnerable-flag bypasses apply; absorption, cooldown, events and custom enchantment logic remain native. Standard Protection requires NOT bypasses_invulnerability, so contributes0 despite no global bypasses_enchantments; Feather Falling also fails native fall/predicate. Native totem check rejects bypasses_invulnerability before consumption. ALWAYS_MOST_SIGNIFICANT_FALL is attribution, not fall HP damage. No source position/Living attacker for normal directed knockback. Default40HP/2 would need20 admitted unmitigated requests, not a measured lifetime.',
      'loyal_feed':'interactAt requires resolved getOwner()!=null && owner.is(player), held rotten_flesh. remove Strength, add Strength1200/1, heal(1), sound, consume1 with Player creative handling, sidedSuccess. No explicit server/fullHP/renewal-needed gate and no cross-call success dependency; native remove/add/heal hooks may reject individual operations without stopping others. Stronger/longer Strength removed first if removal succeeds. Ordinary heal(), not HP write or undead instant-health potion damage. Other item/player falls through inherited interaction. No breed/tame behavior inferred.',
      'loyal_targets':'Goals Float1, Melee4(speed1,longMemory), FollowOwner5(speed1,start10,stop2), stroll7/look9. Targets OwnerHurtBy1, OwnerHurtTarget2, HurtBy3, nearest Monster4(mustSee=true). Owner-response requires tame/notOrderedSit/resolved owner, new hurt timestamp, native TargetGoal.canAttack and wantsToAttack. Custom veto: Creeper/Ghast, same-owner tame LoyalZombie, PvP-protected Player, tame horse/other tame animal. NOT global canAttack: HurtBy and nearest Monster do not invoke wantsToAttack. Eligible Creeper can be selected by nearest Monster despite owner-response veto. Ghast is FlyingMob, not Monster, so it fails that class search; native HurtBy retaliation can still target an otherwise eligible Ghast. The registry MONSTER category is not the Java Monster class (Wraith likewise is FlyingMob). Native owner/team/combat/range/LOS/restriction gates remain; TamableAnimal.canAttack rejects owner and alliance follows resolved owner. No universal friendly-fire immunity/source rewrite.',
      'loyal_follow':'Native follow starts squared distance>=100; continues navigation unfinished, distance>2 and !unableToMoveToOwner. Vetoes orderedSit/passenger/any leash data (mayBeLeashed, even unresolved holder)/spectator owner. Higher-priority melee may preempt. Recalc adjustedTickDelay10 (default reduced5 goal callbacks) selects navigation1 or teleport when owner distanceSquared>=144. Up to10 integer offsets X/Z-3..3, at least one abs>=2, Y-1..1; WALKABLE, no leaves below (canFlyToOwnerfalse), translatedBB noCollision, then centered X/Z+.5 moveTo and nav stop. Native relocation, no HP/owner change or arbitrary compat teleport.',
      'loyal_baby':'ZombieWand HEAD MysticCrown && randomFloat<=.1 -> setBaby(true), AFTER collision check using adult dimensions. Custom flag half dimensions .3x.975/eye.93, transient minecraft:baby +.5 ADD_MULTIPLIED_BASE speed ->.45. setBaby first removes same modifier, adds server-only; does not set AgeableMob.age. Native age tick updates its own age/flag, not Loyal custom flag: this baby does not grow via ordinary24000tick aging. Save IsBaby restored after parent read reinstates speed without stacking. HP40/armor3/fixed7/lifetime unchanged; no Crown wear or charge discount in this item.',
      'charges':'hurtButDontBreak: if damageable, item.damageItem(amount,entity,empty callback) first; entity null or !hasInfiniteMaterials then positive amount passes native durability-enchantment processing (nonpositive result returns). Nonzero ServerPlayer amount triggers durability criterion; setDamageValue(current+amount), exact244 clamp0..max. Never shrinks/breaks item at max. Unbreakable/item hooks/Unbreaking/creative remain native. Zombie/Fortification9, Twilight/Lifedrain99. Actual helper callers also MoonwormQueen and DamageableStackDispenseBehavior; payloads there remain pending. Charges are durability, not HP.',
      'renewal_routes':'Renewal data: four #twilightforest:scepters, maxLevel1, HAND, native tick RechargeScepterEffect, no random requirement. Server Living.baseTick -> EnchantmentHelper.tickEffects -> equipment/item matchingSlot -> Enchantment.tick -> effect.apply -> applyRecharge. Main/offhand run each native tick, including selected mainhand; exact244 uses getAllEnchantments. Separately all four item.inventoryTick require tickCount%20==0, ServerLevel, literal ENCHANTMENTS component Renewal>0, !isSelected. Exact244 Inventory.tick uses global slot, selected==slot: offhand/unselected inventory eligible; offhand has both routes. Helper requires Player AND damage==max; partial use/mob holder no recharge. No level scaling/XP/HP operation. Shared inventory consumption order may matter; no simultaneous-refill guarantee.',
      'renewal_algorithm':'Queries current CRAFTING recipes filtered ScepterRepairRecipe. For each same-scepter recipe copies ingredients, scans ONLY Player.inventory.items in index order. Nonempty EXANIMATE_ESSENCE -> shrink1,setDamage0,return (no creative exemption). Otherwise each still-needed Ingredient.test match removes it and records slot; complete ingredient list ends inventory scan. If recorded slot count equals ingredient count, each stack shrinks1 THEN remainder is queried/added/dropped; subtract recipe repair amount. Slots list lives outside recipe loop, not reset; no return/exhausted recheck after normal repair. Installed data has one matching recipe each, so no invented multiple-recipe producer. Essence not globally prioritized: earlier complete ingredients stop scan; essence after partial match consumes itself without recorded ingredients. Native clamp retained.',
      'repair_data':'Installed repair amount9: Twilight #c:ender_pearls, Lifedrain fermented_spider_eye, Fortification golden_apple, Zombie potion plus rotten_flesh. Zombie potion ingredient ORs normal/long/strong Strength potion_contents for minecraft:potion. Renewal fully restores9-capacity, only9 of99 for others; essence restoresall. Compound/DataComponentIngredient strict defaultsfalse: actual item plus WHOLE potion_contents equality, unrelated stack components allowed, changed custom effects/color inside contents rejected; splash/lingering wrong item. Native Potion has no ordinary crafting remainder declaration; no promised glass bottle. Generic after-shrink remainder lookup can lose remainder on emptied stack, preserved without fix.',
      'crafting':'ScepterRepairRecipe extends CustomRecipe (special/empty display result). Single-ingredient match: exactly one damaged same scepter; every other occupied slot actual Ingredient.test, n>0 and damage+9-9*n>0 -> n<=ceil(damage/9), per occupied slot not stack count. Zombie multi-ingredient branch finds one damaged scepter, repairItems.size==ingredientCount-1, then input.stackedContents.canCraft(this,null). CraftingInput accounts each nonempty slot once; StackedContents indexes registry ITEM ID; RecipePicker uses Ingredient.getStackingIds. Exact244 Ingredient samples custom ingredient items but reduces them to ITEM IDs, without Ingredient.test/component checks. Thus manual Zombie repair statically accepts any minecraft:potion contents +rotten_flesh+damaged scepter, unlike Renewal Strength requirement. Water/other potion is real manual native path; splash/lingering still wrong IDs. No repair patch or runtime result claimed.',
      'crafting_output':'assemble creates target scepter, copies original components, subtracts9*n single or9 multi, native clamp. Enchants/name preserved. Native crafting consumes one per used slot and uses normal recipe remainder callback; inventory recharge separate. Literal canCraftInDimensions is repairItems.size+1 > width*height, inverted-looking but preserved. RecipeManager.getRecipeFor uses matches, not that dimension method, so it does not veto ordinary manual matching; no recipe-book UI outcome claimed. Full serializer pins item/ingredient/int amount; external recipe/data-pack changes outside fixed native defaults.',
      'persistence_scope':'Native Health/effects/owner UUID/Sitting persist; IsBaby custom and native Age separate. No bespoke saved Strength countdown/attack resource. Unresolved owner prevents owner feed/follow, not loaded expiry. Empty loot/XP, visuals and acquisition excluded. Other scepter payloads, Crown material/other bonuses, Essence fire/candle and Moonworm/dispenser payloads remain unfinished separately. No runtime or production claims.'
    }
    M='entity/monster/LoyalZombie';W='item/ZombieWandItem';R='enchantment/RechargeScepterEffect';C='item/recipe/ScepterRepairRecipe';U='util/TFItemStackUtils';I='init/TFItems'
    data=dict(slug='summon-resources',checkpoint_short='r2f8i',checkpoint='R2f8i-summon-resources-complete',decision='TWILIGHT_SUMMON_RESOURCES_SEMANTIC_REVIEW_COMPLETE',starting_sha='696eb25903f23324bbedb90116fd7a41a395dd20',previous_checkpoint='R2f8h-restless-mobs-complete',previous_draft='partial-drafts/twilightforest-r2f8h-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=1,full_classes=FULL,limited_classes={U:['hurtButDontBreak'],'init/TFEnchantments':['Renewal registration'],I:['four scepter constructors'],'item/TwilightWandItem':['inventoryTick; projectile protected'],'item/FortificationWandItem':['inventoryTick; shield pending'],'item/LifedrainScepterItem':['inventoryTick; drain pending']},registration_classes=['init/TFEntities','events/RegistrationEvents',I,'init/TFEnchantments','init/TFDamageTypes'],closure_checklist=['native_summon_collision_owner','fixed_attack_true_push','Strength_lifetime_not_attack','feed_independent_returns','owner_goals_vs_nearest_retaliation','native_follow_teleport','custom_persistent_baby','expired_caller_tags','protection_totem_predicates','nonbreaking_resource_hooks','hand_inventory_recharge_routes','installed_recipe_inputs','essence_inventory_order','manual_item_ID_vs_components','craft_output_remainders','persistence_scope'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus full LoyalZombie/ZombieWand and shared scepter durability/Renewal/manual repair. Other item payloads scoped separately; Twilight PARTIAL/zero promoted.',exact_next_task='Continue Task C with Fortification Scepter shield attachment/event admission/timer/producers and Lifedrain target/damage/control/execute/heal/food, reusing protected recharge. Then remaining utility/passive entities, weapons/armor/charms/projectiles/hazards/resources and13 unfinished custom DamageTypes. Protect each subsection toward R2f8 and final Twilight dedup/promotion. IceAndFire only after Twilight COMPLETE is protected; no runtime boss/L2/Stage/production/fixes/Phase6/7.',damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=26,new_used_profiles=1,reviewed_profiles_after=27,remaining_profiles=13,remaining_disposition='Other actual caller profiles unfinished, not unused.'))
    def pkg(key,title,classification,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=classification,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    summon=pkg('zombie_scepter_summon','Zombie Scepter native owned summon','CUSTOM_CONTROL',['summon','loyal_body','authority'],[W,M,I],{'capacity':9,'strength_ticks':1200,'strength_amplifier':1,'hp':40},['native ray/collision','owner/tame','no finalize','add return ignored'],'Custom real entity producer with native ownership/effect prerequisites.','Native Player Zombie Scepter use',['MISS/collision/creative/exhaustion, denied native add and saved owner'])
    hit=pkg('loyal_zombie_melee','Loyal Zombie fixed attack and successful push','VANILLA_COMPOSITE',['loyal_hit','loyal_body'],[M],{'request':7,'push_y':.2,'armor':3},['native melee goal','fixed7','true hurt for push','no attribute/enchantment helper'],'Native mob_attack and raw motion composition.','Native scepter LoyalZombie melee',['Strength/Weakness/equipment, failed hurt, recipient defense and source identity'])
    expiry=pkg('loyal_zombie_expiry','Loyal Zombie absent-Strength expiration','CUSTOM_DAMAGE',['loyal_expiry','expired_source','persistence_scope'],[M,'init/TFDamageTypes'],{'request':2,'tick_modulus':20},['server','Strength absent','native self hurt','actual source tags'],'Technical custom source through native hurt, no HP subtraction.','Native LoyalZombie Strength expiry',['Native feed/splash/lingering, removal, absorption/cooldown/events/totem'])
    feed=pkg('loyal_zombie_feed','Owner flesh feed and effect/heal refresh','VANILLA_COMPOSITE',['loyal_feed','loyal_expiry'],[M],{'heal':1,'strength_ticks':1200,'amplifier':1,'flesh':1},['resolved owner','rotten flesh','independent native calls'],'Native effect/heal/consume composition with owner prerequisite.','Native owner rotten-flesh interactAt',['Full HP, stronger effect, hook rejection, nonowner and creative'])
    owner=pkg('loyal_zombie_owner_ai','Loyal Zombie owner response and follow','VANILLA_COMPOSITE',['loyal_targets','loyal_follow','persistence_scope'],[M],{'follow_start':10,'follow_stop':2,'teleport_distance':12,'attempts':10},['native priorities','scoped wantsToAttack','separate nearest/retaliation','team/leash/sit'],'Native tame goals/teleport with scoped target predicate.','Native owner combat and follow',['Nearest Creeper versus owner veto, Ghast retaliation/class exclusion, leash/collision/leaves'])
    baby=pkg('loyal_zombie_permanent_baby','Crown-produced persistent Loyal baby','VANILLA_LIKE_EXTENDED',['loyal_baby','summon'],[M,W],{'chance_inclusive':.1,'speed_multiplier':1.5,'speed':.45,'scale':.5,'eye_height':.93},['HEAD Crown','roll<=.1','adult collision first','custom flag independent of age'],'Native size/attribute primitives with persistent custom age flag.','Native Crown Player Zombie Scepter use',['Adult/random controls, native age progression and save/load'])
    charges=pkg('scepter_charge_resource','Persistent scepter durability charges','CUSTOM_RESOURCE',['charges','summon'],[U,W,I],{'small_capacity':9,'large_capacity':99,'ordinary_cost':1},['damageable','native item/enchantment hooks','creative','clamp','never break'],'Native durability repurposed by nonbreaking consumption helper.','Native current scepter use caller',['Exhaustion, Unbreaking/Unbreakable, creative and repair'])
    renewal=pkg('scepter_renewal','Renewal hand/inventory reagent recharge','CUSTOM_RESOURCE',['renewal_routes','renewal_algorithm','repair_data','charges'],[R,W,'item/TwilightWandItem','item/FortificationWandItem','item/LifedrainScepterItem',C,'init/TFEnchantments'],{'repair':9,'unselected_modulus':20,'max_level':1},['Player','exhausted','native equipped or inventory callback','actual ingredient tests','ordered inventory'],'Native enchantment/inventory callbacks restore custom charge resource.','Native exhausted Renewal scepter with reagents',['Hand/offhand/inventory, partial/mob negatives, ingredient/essence order'])
    crafting=pkg('scepter_crafting_repair','Special native manual repair matching','CUSTOM_RESOURCE',['crafting','crafting_output','repair_data'],[C,C+'$Serializer'],{'repair':9},['damaged scepter','occupied slots','single ingredient test','multi ingredient ITEM ID','components copied'],'Special crafting resource recipe distinct from Renewal component tests.','Native manual damaged-scepter repair',['Zombie Water/Strength/splash, partial damage/count and enchant/name preservation'])
    data['damage_profiles']=[dict(type='twilightforest:expired',status='USED',callers=[dict(entry='twilightforest/entity/monster/LoyalZombie.class',method='aiStep')],amount='2 per server tickCount%20==0 while Strength absent; hurt return ignored.',direct_and_causing_entities='Both null; no source position or summoner attribution.',mitigation=facts['expired_source'],success_gates='Periodic scheduling independent of hurt return; native self-hurt admission remains.',secondary_payload='No HP write/forced discard; native death processing.')]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:summon_resources_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=list(dict.fromkeys(labels)),setup=title+' using real native mechanics; future fixture only, no runtime or fabricated source.',future_controls=controls))
    rows=[
      ('summon','Native Zombie Scepter owned summon',['summon','loyal_body'],[summon,charges],[W,M],['ACTIVE_ITEM','SUMMONED_ATTACK'],['native ray/reach/collision','owner/Strength','9 charges']),
      ('summon_negative','Native summon miss/collision/exhaustion',['summon','charges'],[summon,charges],[W,U],['ACTIVE_ITEM','OTHER'],['MISS success no cost','collision PASS','exhausted FAIL','creative']),
      ('summon_add','Native summon add and save controls',['summon','persistence_scope'],[summon],[W,M],['ACTIVE_ITEM','SUMMONED_ATTACK'],['no finalize','add return ignored','native owner/effect save']),
      ('melee','Native LoyalZombie melee',['loyal_hit'],[hit],[M],['SUMMONED_ATTACK','MOB_ATTACK','MELEE'],['fixed7','source mob not Player','true push.2']),
      ('melee_strength','Native effect/equipment and defense controls',['loyal_hit','loyal_body'],[hit],[M],['MOB_ATTACK','MELEE'],['no attack attr/helper','recipient pipeline','false no push']),
      ('expiry','Native missing-Strength expiration',['loyal_expiry','expired_source'],[expiry],[M,'init/TFDamageTypes'],['ENVIRONMENT','OTHER'],['ownerless2/mod20','native HP pipeline','mitigation/totem tags']),
      ('expiry_strength','Native genuine Strength prevents expiry',['loyal_expiry'],[expiry],[M],['THROWN_PROJECTILE','PASSIVE_AURA','OTHER'],['admitted splash/lingering potion or AreaEffectCloud','any amplifier','removal/expiry']),
      ('expiry_save','Native loaded lifetime and reload',['loyal_expiry','persistence_scope'],[expiry],[M],['OTHER'],['saved effect/HP','new tickCount phase','unresolved owner']),
      ('feed','Native owner flesh interaction',['loyal_feed'],[feed,expiry],[M],['ACTIVE_ITEM','OTHER'],['owner','remove/add/heal/consume','full HP allowed']),
      ('feed_controls','Native feeding/effect/heal negatives',['loyal_feed'],[feed],[M],['ACTIVE_ITEM','OTHER'],['nonowner/item','stronger effect','independent returns','creative']),
      ('owner_defense','Native owner hurt/attack responses',['loyal_targets'],[owner],[M],['SUMMONED_ATTACK','MOB_ATTACK'],['tame/resolved/nonsitting','new timestamp','wantsToAttack']),
      ('owner_nearest','Native nearest Monster and retaliation',['loyal_targets'],[owner],[M],['MOB_ATTACK','MELEE'],['no wantsToAttack','Creeper nearest / Ghast retaliation distinction','owner/team gates']),
      ('owner_follow','Native owner navigation and teleport',['loyal_follow'],[owner],[M],['SUMMONED_ATTACK','OTHER'],['start10/stop2','teleport12','10 collision/walkable attempts']),
      ('owner_follow_negative','Native follow vetoes',['loyal_follow'],[owner],[M],['OTHER'],['sit/passenger/leash data/spectator','melee priority','leaves/collision']),
      ('baby','Native Crown baby summon',['loyal_baby','summon'],[baby,summon],[W,M],['ACTIVE_ITEM','SUMMONED_ATTACK'],['HEAD/<=.1','adult collision','same HP/damage/lifetime']),
      ('baby_save','Native custom baby save/age',['loyal_baby'],[baby],[M],['SUMMONED_ATTACK','OTHER'],['custom flag not native age','speed.45/half dimensions','no load stacking']),
      ('charge','Native nonbreaking charge consumption',['charges'],[charges],[U,W],['ACTIVE_ITEM','OTHER'],['max retained item','durability hooks','creative/Unbreakable']),
      ('renewal_hand','Native Renewal hand ticks',['renewal_routes','renewal_algorithm'],[renewal,charges],[R,'init/TFEnchantments'],['PASSIVE_ITEM','ACTIVE_ITEM'],['HAND','each server tick','Player/exhausted']),
      ('renewal_inventory','Native unselected scepter inventory tick',['renewal_routes'],[renewal],[W,'item/TwilightWandItem','item/FortificationWandItem','item/LifedrainScepterItem'],['PASSIVE_ITEM','OTHER'],['global slot','20 modulus','literal component','offhand overlap']),
      ('renewal_zombie','Native Zombie Renewal ingredients',['repair_data','renewal_algorithm'],[renewal],[R,C],['PASSIVE_ITEM','OTHER'],['Strength potion variants','flesh','9 refill','Water/splash negative']),
      ('renewal_other','Native other scepter Renewal ingredients',['repair_data','renewal_algorithm'],[renewal],[R,C],['PASSIVE_ITEM','OTHER'],['pearl tag/fermented eye/golden apple','9 of99 or9']),
      ('renewal_essence','Native ordered Essence full refill',['renewal_algorithm'],[renewal],[R],['PASSIVE_ITEM','OTHER'],['essence1/full reset','earlier complete ingredients win','partial match then essence']),
      ('renewal_negative','Native recharge eligibility boundaries',['renewal_routes','renewal_algorithm'],[renewal],[R],['PASSIVE_ITEM','OTHER'],['partial/mob negative','main inventory only','creative consumes','no level scaling']),
      ('renewal_order','Native shared inventory and recipe state',['renewal_algorithm'],[renewal],[R],['PASSIVE_ITEM','OTHER'],['one installed recipe each','no invented extra recipe','slots list outside loop']),
      ('craft_single','Native manual single-ingredient repair',['crafting','crafting_output'],[crafting],[C],['OTHER','OTHER'],['Ingredient.test','damaged scepter','ceil(damage/9)','occupied slots']),
      ('craft_zombie','Native manual Zombie Scepter repair',['crafting','crafting_output','repair_data'],[crafting],[C,C+'$Serializer'],['OTHER','OTHER'],['potion ITEM ID','flesh','3 occupied slots','Renewal distinction']),
      ('craft_controls','Native repair output/negative controls',['crafting','crafting_output'],[crafting,charges],[C],['OTHER','OTHER'],['full/extra/splash negative','components preserved','dimension method separate']),
      ('repair_remainders','Native crafting versus recharge remainders',['crafting_output','renewal_algorithm','repair_data'],[crafting,renewal],[C,R],['OTHER','PASSIVE_ITEM','OTHER'],['native recipe remainder','recharge after shrink','no Potion bottle promise'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','vanilla-evidence/twilight-summon-protection.json','twilightforest-summon-resources-caller-scan.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','reference-evidence/cult-loader-244.json','vanilla-evidence/twilight-restless-mobs.json','reference-evidence/twilight-restless-mobs-244.json']
    data['exclusions']=['Five full native classes plus actual tag/data/registration and raw/exact244 caller chains.','Other scepters only shared resource callbacks here; Fortification/Lifedrain payloads next. Protected Twilight bolt unchanged.','Crown armor/other bonuses, Essence fire/candle and Moonworm/dispenser payloads remain separate.','Recipe quirks and source predicates preserved, no runtime/Stage/L2/production/fixes.','EXPIRED USED:27/40 reviewed,13 unfinished. Twilight PARTIAL, zero promotion; IceAndFire unstarted.']
    data['fixture_groups']=['Real Zombie Scepter ray/collision/owner/Strength/resource and creative/add-return controls.','Fixed7 melee/true push with effect/equipment/recipient controls.','Natural Strength expiry versus native refresh; EXPIRED tags, Protection/totem/absorption/events and persistence.','Owner feed independent returns, different target routes and native follow/teleport.','Crown baby/adult collision/independent age flag/save without damage or HP change.','Native charge consumption and main/offhand/inventory Renewal, ingredient/essence ordering, partial/mob negatives.','Manual ITEM-ID repair versus Renewal potion component tests, copied components and native remainders.']
    data['expected_counts']=dict(mechanic_packages=9,delivery_cases=28,classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=1)
    write_json(OUT/'review-inputs/twilightforest-summon-resources.json',data);assemble('twilightforest-summon-resources.json')

if __name__=='__main__':build()
