"""Reviewed Travellers movement admission, native physics and state boundaries."""
from catalog_common import *
from collect_twilight_travellers_movement import FULL,BATCH,T
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed Twilight4.8.3345 with exact installed nested ASM, raw Minecraft1.21.1 and installed NeoForge21.1.244. Static research, runtime0; no production/Stage/Phase6/7/L2/boss tests or changes. Eleven movement packages close the remaining TravellersGearLogic methods and eight registered movement transformers. Protected R2f8o modifier activation, recipes, broken state, attributes and Efficient Eater remain authoritative. Belt/display/zoom, Emperor cloth and unrelated ASM remain unfinished. No new DamageType, direct HP/SHP payload, synthetic event or compatibility fix.',
      'activation':'Reuse R2f8o: actual component/marker presence, registered modifier group and current equipped stack; !spectator and not broken Travellers armor, except Auto-Repair. Movement modifiers are not ALWAYS_ACTIVE. Real slots are FEET for boots, LEGS for wings, CHEST for Swift Swim. No reviewed movement callback queries Curios. Some later stored-state consumers explicitly do not repeat current activation checks; those differences are recorded below. Item attributes have their native equipment lifecycle independently from component activation. Native external listeners/clamps remain, no pack-wide compatibility certification.',
      'water':'WaterWalkTransformer inserts EntityHooks.processWaterWalking before every IRETURN of LivingEntity.canStandOnFluid(FluidState). Non-WATER fluid tag or inactive WATER_WALK preserves prior result. Eligible WATER overrides prior result with WATER_TYPE fluid height<.4 strict AND !shift. If height>0, eligible and gameTime%3==1, splash helper runs; it also requires horizontal known-motion length>=.01 and last-water-walk tick+1!=current tick before visuals/timestamp. No damage/effect/resource cost. Native LiquidBlock.getCollisionShape additionally requires context.isAbove(STABLE_SHAPE,pos,true), LEVEL==0, and context.canStandOnFluid(aboveFluid,currentFluid). STABLE_SHAPE height8/16; EntityCollisionContext requires entity bottom>posY+.5-1e-5, captured living canStandOnFluid(current), and above fluid type not same as current. Thus exposed source-fluid surface/position admission remains; this is not collision on every flowing water block or a deep-water/lava immunity. Living.travel liquid branch separately requires !canStandOnFluid. Other native collision/fluid eligibility remains.',
      'unrestrained':'Installed UnrestrainedBlockSpeedAndJumpFactorTransformer changes Entity.getBlockSpeedFactor/getBlockJumpFactor FRETURN to1 only with active UNRESTRAINED. ResetStuckUnrestrainedTransformer inserts helper before Entity.move reads stuckSpeedMultiplier; Living entity with lengthSqr>1e-7 and active modifier gets ZERO. EntityTick.Post also sets ZERO whenever active. UnrestrainedFrictionTransformer changes default IBlockExtension.getFriction FRETURN to.6 when active; cannot assert custom overrides necessarily call that default method. SlimeBlockMomentumTransformer modifies Entity.isSteppingCarefully result in SlimeBlock.stepOn totrue when active, skipping native |y|<.1 horizontal multiplier .4+|y|*.2. SlimeBlockBounceUpTransformer invokes stopBouncing before first getDeltaMovement in bounceUp: active and y>-.08 strict sets y=max(0,y); at y<=-.08 ordinary bounce remains. These are movement inputs; they do not cancel all falls, alter DamageSources, or provide general status/damage immunity.',
      'water_sprint':'WaterSprintTransformer targets LocalPlayer.aiStep isInWater calls and isInFluidType(BiPredicate) calls. Active UNRESTRAINED returns originalWaterResult && !canStandOnFluid(current block fluid); wrapped fluid predicate only transforms WATER_TYPE, preserving other fluid results. With actual Water Walk surface eligibility this allows the relevant native land-sprint checks; submerged/shift/inactive Water Walk still follows original water result. Not unconditional water sprint permission. PathFinderUnrestrainedByLeashTransformer is NOT this equipment mechanic: its separate LEASH_PATHFINDER_OVERRIDE structure marker is explicitly deferred to source closure.',
      'swim':'Builtin Swift Swim supplies current CHEST WATER_MOVEMENT_EFFICIENCY+1 ADD_VALUE, vanilla attribute default0 clamped0..1. In the actual native travel water branch, e=attribute, halved if !onGround; drag starts sprint?.9:getWaterSlowDown(.8), acceleration .02. With e>0: drag+=(.54600006-drag)*e; acceleration+=(getSpeed-.02)*e. Dolphins Grace overrides drag to.96; NeoForge SWIM_SPEED multiplies acceleration. Native fluid/controlled-instance/affected-by-fluid/!canStandOnFluid and collision checks remain. This is native attribute behavior, not a universal fixed speed multiple or Water Breathing. Broken stored-attribute lifecycle is protected R2f8o.',
      'step':'Builtin High Step FEET item attribute STEP_HEIGHT+.5 ADD_VALUE. PlayerTick.Pre with active STEP_UP_ABILITY removes that modifier ID while crouching and, if not crouching and absent, adds the same modifier as PERMANENT. It has no inactive else-cleanup; ordinary equipment changes separately remove old item modifier IDs and add new ones. AttributeInstance distinguishes permanent saved modifiers from transient ones. No additional step-height total is assumed across other modifiers/entities, no teleport or collision bypass. Active gate, real feet equipment, crouch and native movement/collision remain. Save/load and remove/break timing deserve separate fixture controls.',
      'high_jump':'Server EntityTick.Post Living wearer with active LEGS HIGH_JUMP and nonnull component amplifier applies native JUMP(duration2,amp1 default,hidden). Native effect eligibility/merge/expiry remains. Native Jump Boost contributes .1*(amp+1)=.2 to getJumpPower and SAFE_FALL_DISTANCE+1*(amp+1)=+2. Jump power=JUMP_STRENGTH*inputScale*getBlockJumpFactor+boost. Native jumpFromGround only changes velocity and posts LivingJumpEvent when power>1e-5; sets vertical power, adds sprint horizontal.2, marks impulse. This is a vanilla effect with equipment renewal; it is distinct from the separate Double Jump safe-fall modifier. No direct damage or unconditional jump/HP immunity.',
      'slimy_fall':'LivingFallEvent: real Living wearer, FEET coefficient nonnull(default.5), active SLIMY_SOLES, !shift, and (TF formula>0 OR stored forceBounce). TF formula=ceil((eventDistance-SAFE_FALL_DISTANCE)*eventDamageMultiplier*FALL_DAMAGE_MULTIPLIER). Unlike native Living.calculateFallDamage, this helper does not test EntityType FALL_DAMAGE_IMMUNE tag. On admission cancel event; store bounceVelocity=-currentY*sqrt(coefficient), doubleJumpBoostVelocity=same, hasBounced=false. Native CommonHooks.onLivingFall returns null on cancellation; Living.causeFallDamage returnsfalse before parent/HP damage. Thus eligible fall HP damage is canceled via a genuine native event, not reduced by a fabricated source. Failed admission follows native fall source/tag/armor/Resistance/protection/invulnerability and hurt pipeline unchanged. No proof of immunity to non-fall damage.',
      'slimy_bounce':'EntityTick.Post on both sides calls stored bounce consumer without a fresh gear/active check: bounceVelocity!=0 && !hasBounced ->newY=sqrt(currentY^2+bounceVelocity^2), preserveXZ, sethasBounced=true and forceBounce=abs(newY)>.25, sound/particles. LivingJumpEvent clears bounceVelocity and forceBounce, but not doubleJumpBoostVelocity or hasBounced. Double Jump reads the retained boost AFTER native jump callback, combines sqrt(afterJumpY^2+boost^2) and zeroes boost. A legitimate stored bounce can therefore outlive modifier removal until consumed/reset by the actual state callbacks. Coefficient codec is FLOAT without an added positive range guard; legitimate packaged coefficient.5.',
      'slimy_save':'SLIMY_SOLES_BOUNCE_INFO is serialized with SlimySolesAttachment.CODEC fields bounce_velocity,double_jump_boost_velocity,force_bounce,bounce. Actual four-argument constructor writes bounceVelocity,forceBounce,hasBounced only; it ignores the doubleJumpBoostVelocity parameter. Encoding includes boost but decode leaves that field Java-default0. This is proven bytecode state loss on native load, not an uncertain tooltip inference or a proposed fix. Other three encoded fields restore. No copyOnDeath declared; ordinary death attachment copy omits it.',
      'glide':'EntityTick.Post both sides, any Living entity with current LEGS active GRADUAL_GLIDE, nonnull multiplier(default.8333333), descendingY<0 and !fallFlying. Players also require IS_GRADUALLY_GLIDING=true; nonplayers do not. SetY=oldY*mult, preserveXZ, fallDistance=float(newY^2/2/getGravity()). No separate onGround/liquid/passenger/jump-key requirement inside physics helper. Native gravity/collision/fall rules remain; not a blanket no-fall-damage effect, Slow Falling MobEffect or source replacement.',
      'glide_input':'Client RenderFrame.Pre computes flag=(TFConfig.manualTravellersWingsGradualGlideDefault==shift) &&knownMovementY<0&&!onGround, without current gear check; on change stores and sends GradualGlidePacket(bool,playerUUID). Installed client TOML and default config are true, so descending hold-shift is the ordinary input. Bidirectional handler looks up packet UUID in ctx.player.level, requires nonnull Player, sets flag; server forwards to tracking players. It does not compare senderUUID or check gear; actual physics still checks current gear, and server PlayerPre clears true flag when modifier inactive and syncs tracking+self. Client MovementInputUpdate with flag&&shift divides forward/left by.2 without its own gear check. Native input.tick precedes event and item-use .2 slowdown follows it. Packet/state admission is recorded as implemented, with no fabricated traffic or security/runtime testing.',
      'double_state':'PlayerPre sets proposed HAS_DOUBLE_JUMP=false when inactive; else true onGround OR inLiquid OR onClimbable; otherwise leaves it alone. Only when nonnull proposal differs from stored value does it update availability, reset validator0 and remove Double Jump SAFE_FALL_DISTANCE modifier. Client jump-key press uses native key/action/no-GUI check, stores lastpress and avoids creative flight toggle when mayFly &&elapsed<=6; requires current active DOUBLE_JUMP and helper success to send empty PerformDoubleJumpPacket. Server packet calls helper on ctx.player, with failed return routed to movement validator. Helper checks stored HAS_DOUBLE_JUMP and !fallFlying,!onClimbable,!onGround,!isSwimming,!abilities.flying,!inLiquid,!passenger; it does NOT independently recheck current gear. PlayerPre usually clears stale availability on the next tick; ordering remains material.',
      'double_payload':'Admitted helper calls native Player.jumpFromGround() then optional saved Slimy boost combination, resets fallDistance, consumes HAS_DOUBLE_JUMP=false, resets validator0 and adds/updates TRANSIENT SAFE_FALL_DISTANCE+2 under its own ID. Native jump returns void: even if its low jump-power branch produces no vertical impulse, TF continues reset/resource/safe-distance actions and returnstrue. Actual exact TRAVELLERS_WINGS item is checked only for wing-state/particle packet visuals, not the physics admission. Safe-distance removal is conditional on availability transition in PlayerPre, not an unconditional landing hook; do not assume all inactive/equal-false states erase it. Native High Jump effect safe-distance is a distinct additional modifier.',
      'sidestep':'Client MovementInputUpdate LocalPlayer onGround detects prior leftImpulse==0, matching sign with last nonzero, currentTick-lastWalkingTick<4 and newleft!=0; successful tryPerformSidestep sends server boolean left/right. Helper uses current active LEGS SIDESTEP, cooldown nonnull(default40), gameTime-lastSidestepTime>cooldown STRICT, !fallFlying,onGround,!crouching. No separate passenger/creative gate. performSidestep adds horizontal vector magnitude1.6 perpendicular to current yaw with player.push (not velocity replacement), sound and wing state; records time and cooldown-sound flag. Server packet repeats helper for ctx.player; failed helper invokes validator. Cooldown notification uses same strict>cooldown and active current modifier. lastSidestepTime defaults0, so first ordinary use requires gameTime>40; attachment is not serialized, so cooldown does not persist across reconstruction.',
      'validator':'Only failed double-jump/sidestep server packet helpers call validateMovement for ServerPlayer. CurrentServer must be nonnull AND dedicated; integrated server skips. Read stored count and tick delta; when diff>=45&&!fallFlying reset local count=-1; record current lastCheck. If count>=5 disconnect with native flying message; else save count+1. If old/reset count>1 also warn and absMoveTo current pose plus native position packet. No HP/source, invulnerability or cooldown resource change is implied by validator. Serialized count/tick values and helper successful resets differ from visual wing timers.',
      'straight':'Server Living EntityPost reads FEET multiplier(default1.4), active and !=1 determines desired presence of MOVEMENT_SPEED modifier ID. Only when desiredpresence!=actualpresence does it add/update transient(mult-1) ADD_MULTIPLIED_TOTAL orremove. No server forward-input gate; changed numeric component while modifier already present is not updated by that branch. Client MovementInputUpdate LocalPlayer selects multiplier1 if inactive/null/forwardImpulse<=0; otherwise actual value, then addOrUpdateTransient(mult-1) and divides leftImpulse bymult. This is native client/server asymmetry, not uniform unconditional x1.4 speed. Ordinary attribute stacking/clamps, equipment and current inputs remain.',
      'straight_fov':'GetFieldOfViewModifierTransformer targets AbstractClientPlayer.getFieldOfViewModifier: before first FCONST_1 call straightAheadNullify; before every FRETURN call straightAheadRestore, only if first anchor found. Installed target contains anchors. Nullify saves current modifier amount+1 (or1), removes the ID for FOV computation; restore re-adds transient(mult-1) only for LocalPlayer. Nonlocal AbstractClientPlayer has no corresponding restore branch. The native returned FOV/event computes while modifier is removed; this is visual compensation with temporary attribute state, not a second speed buff. TF Goggles zoom is a separate unfinished feature.',
      'agile':'Client MovementInputUpdate LocalPlayer with current LEGS active AGILE_RANGER and nonnull multiplier(default5), usingitem and !passenger, and ((item instanceof ProjectileWeaponItem OR whitelist tag) AND !blacklist tag) multiplies left/forward by5. Installed whitelist adds MOONWORM_QUEEN; no packaged blacklist resource is present, but datapack tags remain extensible. Exact NeoForge244 LocalPlayer.aiStep posts event AFTER input.tick and BEFORE ordinary using-item .2 slowdown; default5 offsets that later factor for eligible use. No server projectile power, ammo, firing callback, source, HP or damage multiplier. Native use-item state, other event handlers and movement gates remain.',
      'persistence':'TFDataAttachments: HAS_DOUBLE_JUMP(false), lastJump/validator/lastCheck/horizontal input state(default0), LAST_TICK_WATER_WALKING(0), TEMPORARY_SAVED_STRAIGHT_AHEAD(1) and IS_GRADUALLY_GLIDING(false) serialize with native codecs; glide also declares native BOOL sync. None declares copyOnDeath. TravellersGearEvents explicit death copy preserves only RED_THREAD_VISION, not movement state. Native attachment death-copy filters copyOnDeath; nondeath copying uses serializer/copy rules. TRAVELLERS_WINGS and TRAVELLERS_WINGS_ANIM have no serializer, so sidestep time/soundflag and visual state do not save. Wing state packets carry ID/state/left/timers for visuals; DoubleJump15 and Sidestep11 tick locks in determineWingState do not create another movement payload. Raw item components persist independently as protected in R2f8o. No runtime save/load test or pack-wide integration claim.'
    }
    E='events/TravellersGearEvents';L=T+'TravellersGearLogic';C='client/event/TravellersClientEvents';D='init/custom/TravellersModifiersManager';H='asmhooks/EntityHooks';B='asmhooks/BlockHooks';P='asmhooks/PlayerHooks';S='components/entity/SlimySolesAttachment';W='components/entity/TravellersWingsAttachment'
    nxt='Complete Travellers belt/hotbar/item-display/zoom/red-thread and Emperor cloth/render/equipment hooks; then remaining utilities/food/passive entities/hazards,10 custom DamageTypes, remaining installed ASM/compatibility/source exclusions, R2f8 and final Twilight promotion. Continue IceAndFire only after Twilight COMPLETE pushed/live verified. No runtime boss/L2/Stage/production/Phase6/7.'
    data=dict(slug='travellers-movement',checkpoint_short='r2f8p',checkpoint='R2f8p-travellers-movement-complete',decision='TWILIGHT_TRAVELLERS_MOVEMENT_SEMANTIC_REVIEW_COMPLETE',starting_sha='3462e60868bb8877855ae2a441379c61a322a90c',previous_checkpoint='R2f8o-travellers-core-complete',previous_draft='partial-drafts/twilightforest-r2f8o-partial.json',facts=facts,packages=[],paths=[],new_damage_types=0,full_classes=FULL,limited_classes={E:['fall/jump/player movement/high-step/entity tick/death-copy registration'],C:['movement handlers and key filter'],H:['water/Unrestrained; leash remains unfinished'],B:['Unrestrained friction/slime only'],P:['Straight Ahead FOV helpers'],'config/TFConfig':['client config load/default'],'config/TFClientConfig':['constructor']},registration_classes=['init/TFItems','init/TFDataComponents','init/TFDataAttachments','init/TFAttributeModifiers','events/RegistrationEvents',D],closure_checklist=['native_slot_and_active_predicates','water_surface_collision_admission','eight_installed_ASM_transformers','unrestrained_friction_stuck_slime_water_sprint','swift_swim_native_formula','high_step_attribute_lifecycle','high_jump_native_effect','slimy_fall_cancel_vs_bounce','slimy_decode_constructor_loss','glide_physics_input_packets','double_jump_availability_vs_payload','sidestep_native_input_and_cooldown','dedicated_server_failed_packet_validation','straight_ahead_client_server_and_FOV','agile_ranger_native_input_order','serialization_death_copy_and_visual_state'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus eleven Travellers movement mechanics and eight installed ASM transformers; belt/display/zoom/cloth and remaining content unfinished. Whole Twilight PARTIAL; zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=30,new_used_profiles=0,reviewed_profiles_after=30,remaining_profiles=10,remaining_disposition='Unfinished other actual callers, not declared unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,controls):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=['activation']+keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=controls));return eid
    water=pkg('travellers_water_walk','Travellers native water-surface collision','CUSTOM_CONTROL',['water'],[H,L,D],{'max_height_exclusive':.4,'native_surface_height':.5},['WATER tag','active feet','!shift','native source/exposed/above collision'],'Custom canStandOnFluid result feeds vanilla collision/travel.','Native equipped Water Walk boots at source-water surface',['flowing/deep/covered water, shift, broken and lava controls'])
    unrestrained=pkg('travellers_unrestrained','Travellers terrain movement overrides','CUSTOM_CONTROL',['unrestrained','water_sprint'],[H,B,L,D],{'block_factors':1,'default_friction':.6,'tiny_bounce_cutoff':-.08},['active feet','specific installed ASM target','actual fluid/terrain state'],'Custom overrides of native movement inputs, not damage immunity.','Native movement over slowing/slime/ice/water surfaces',['custom friction override, depth, shift, stuck and threshold controls'])
    swim=pkg('travellers_swift_swim','Travellers native swim-efficiency attribute','VANILLA_DIRECT',['swim'],[T+'TravellersArmorItem','init/TFAttributeModifiers'],{'water_movement_efficiency_add':1},['real chest attributes','native water travel'],'Direct native attribute semantics.','Native Vest-equipped swim',['ground/air, sprint, Dolphins Grace, SWIM_SPEED and broken controls'])
    step=pkg('travellers_high_step','Travellers crouch-controlled step attribute','VANILLA_LIKE_EXTENDED',['step','persistence'],[E,'init/TFAttributeModifiers'],{'step_height_add':.5},['active feet ability','native player pre tick','crouch'],'Native step-height attribute with custom crouch lifecycle.','Native boots wearer walks an obstacle',['crouch, inactive timing, equipment replacement, save/load'])
    jump=pkg('travellers_high_jump','Travellers renewed native Jump Boost','VANILLA_LIKE_EXTENDED',['high_jump'],[L,E,'init/TFAttributeModifiers'],{'duration':2,'amplifier':1,'jump_boost':.2,'safe_fall_add':2},['server Living tick','active legs','native addEffect'],'Native Jump Boost with custom equipment producer.','Native Wings wearer jumps',['effect merge, broken, low jump strength and sprint'])
    slimy=pkg('travellers_slimy_soles','Travellers fall veto and stored bounce','CUSTOM_CONTROL',['slimy_fall','slimy_bounce','slimy_save','persistence'],[E,L,S],{'coefficient':.5,'force_bounce_threshold':.25},['real fall event','!shift','active feet','positive formula or forceBounce'],'Native fall cancellation plus custom motion/state, distinct from HP damage.','Native damaging fall with Slimy Soles boots',['shift, tag immunity, gear removal, JumpEvent and decode controls'])
    glide=pkg('travellers_gradual_glide','Travellers descent and fall-distance control','CUSTOM_CONTROL',['glide','glide_input','persistence'],[L,E,C,'network/GradualGlidePacket'],{'vertical_multiplier':.8333333,'installed_manual_input':True},['active legs','descending','!fallFlying','Player state or nonplayer'],'Custom vertical motion/fall-distance state through native tick.','Native descending wearer holds shift',['gear, nonplayer, packet identity boundary, gravity and landing controls'])
    double=pkg('travellers_double_jump','Travellers stored second-jump availability','CUSTOM_CONTROL',['double_state','double_payload','validator','persistence'],[E,L,C,'network/PerformDoubleJumpPacket',S],{'safe_fall_add':2,'creative_toggle_window':6},['stored availability','native airborne predicates','native jump helper'],'Custom jump resource and safe-distance lifecycle built on native jump.','Native airborne second jump-key press',['next-tick gear clear, low jump strength, Slimy boost, death/save controls'])
    side=pkg('travellers_sidestep','Travellers native sidestep impulse and cooldown','CUSTOM_CONTROL',['sidestep','validator','persistence'],[L,C,W,'network/PerformSidestepPacket'],{'impulse':1.6,'strict_cooldown':40,'tap_window_exclusive':4},['active current legs','onGround','!crouching','strict cooldown'],'Custom native motion impulse with packet/input resource.','Native left/right double-tap wearer',['yaw, existing velocity, timing40/41, dedicated/integrated and reload'])
    straight=pkg('travellers_straight_ahead','Travellers directional speed and FOV compensation','CUSTOM_CONTROL',['straight','straight_fov','persistence'],[L,C,P,'init/TFAttributeModifiers'],{'multiplier':1.4,'total_add':.4},['current active feet','client forward input','server presence transition'],'Custom direction/state control of native speed attribute.','Native forward/side/back movement in modified boots',['component changed while present, FOV early return, broken and removal'])
    agile=pkg('travellers_agile_ranger','Travellers eligible item-use input recovery','CUSTOM_CONTROL',['agile'],[C,D],{'input_multiplier':5,'native_use_slowdown':.2},['active legs','using eligible item','!passenger','!blacklisted'],'Custom native input multiplier offsets ordinary use slowdown.','Native bow/crossbow/Moonworm Queen use',['tag controls, nonprojectile item, mounted, broken, unchanged projectile payload'])
    data['damage_profiles']=[]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:travellers_movement_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through genuine native equipment/input/physics; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('water_surface','Native source-water surface collision',['water'],[water],[H,L],['ARMOR_PROC','ENVIRONMENT'],['LEVEL0','above-fluid unlike','bottom height','water depth<.4']),
      ('water_negative','Native depth/flow/shift/lava controls',['water','activation'],[water],[H,L,D],['ARMOR_PROC','ENVIRONMENT'],['.4 boundary','samefluid above','flowing','prior result preserved outside water']),
      ('water_travel','Native fluid travel and splash control',['water'],[water],[H,L],['ARMOR_PROC','ENVIRONMENT'],['canStandOnFluid vswaterbranch','splash visualonly','no source']),
      ('terrain','Native block speed and jump factor overrides',['unrestrained'],[unrestrained],[H,L],['ARMOR_PROC','ENVIRONMENT'],['specific FRETURN hooks','factor1','broken negative']),
      ('stuck','Native stuck multiplier before move and post tick',['unrestrained'],[unrestrained],[H,L,E],['ARMOR_PROC','ENVIRONMENT'],['lengthSquared>1e-7','real Living entity','ZERO','noHP immunity']),
      ('friction','Native default friction override',['unrestrained'],[unrestrained],[B],['ARMOR_PROC','ENVIRONMENT'],['defaultIBlockExtension','value.6','custom override not assumed']),
      ('slime','Native slime momentum and tiny-bounce controls',['unrestrained'],[unrestrained],[B],['ARMOR_PROC','ENVIRONMENT'],['stepOn branch','y>-.08','large bounce preserved']),
      ('water_sprint','Native surface-water sprint admission',['water_sprint','water'],[water,unrestrained],[H],['ARMOR_PROC','ENVIRONMENT'],['currentcanStandOnFluid','waterpredicateonly','shift/deep controls']),
      ('swim','Native Vest water travel',['swim'],[swim],[T+'TravellersArmorItem','init/TFAttributeModifiers'],['ARMOR_PROC','ENVIRONMENT'],['efficiency clamp','ground vsair','sprint drag','native acceleration']),
      ('swim_stack','Native swim attribute and effect composition',['swim','activation'],[swim],[T+'TravellersArmorItem',D],['ARMOR_PROC','ENVIRONMENT'],['Dolphins Grace','SWIM_SPEED','broken attributes','WaterWalkbranch']),
      ('step','Native boots obstacle stepping',['step'],[step],[E],['ARMOR_PROC'],['+.5','crouchremove','missingaddpermanent','nativecollision']),
      ('step_lifecycle','Native High Step equipment and save lifecycle',['step','persistence'],[step],[E,'init/TFDataAttachments'],['ARMOR_PROC','OTHER'],['noinactiveelse','nativeitemIDremoval','permanentsave']),
      ('jump_effect','Native Wings Jump Boost renewal',['high_jump'],[jump],[L,E],['ARMOR_PROC'],['effect2/1','jump+.2','safeFall+2','native merge']),
      ('jump_native','Native actual jump power and sprint controls',['high_jump'],[jump],[L],['ARMOR_PROC'],['power>1e-5','sprint horizontal.2','broken stopsrefresh']),
      ('fall_veto','Native eligible fall event cancellation',['slimy_fall'],[slimy],[E],['ARMOR_PROC','ENVIRONMENT'],['activecoefficient','positiveformula','nativeHPcallnotreached']),
      ('fall_negative','Native fall admission failure and tag controls',['slimy_fall'],[slimy],[E],['ARMOR_PROC','ENVIRONMENT'],['shift','noactive','formula0','nativefallimmune tag separate']),
      ('bounce','Native stored bounce on subsequent tick',['slimy_bounce'],[slimy],[L,E,S],['ARMOR_PROC','ENVIRONMENT'],['sqrt','force>.25','no fresh gear check','sound onlyextra']),
      ('bounce_jump','Native JumpEvent and saved bounce boost',['slimy_bounce','double_payload'],[slimy,double],[E,L,S],['ARMOR_PROC'],['event clearsbounce butnotboost','boost afterjump','consumeonce']),
      ('bounce_save','Native Slimy Soles encode/decode',['slimy_save','persistence'],[slimy],[S,'init/TFDataAttachments'],['OTHER'],['fourencodedfields','threeconstructorwrites','decodedboost0','nodeathcopy']),
      ('glide_player','Native descending Player glide',['glide','glide_input'],[glide],[L,C],['ARMOR_PROC'],['holdshift default','vertical*.8333333','fallDistanceformula','nativegravity']),
      ('glide_mob','Native living nonplayer glide',['glide'],[glide],[L],['ARMOR_PROC','MOB_ATTACK'],['reallegs','noPlayerflag','descending','!fallFlying']),
      ('glide_packet','Native glide state dispatch and receive',['glide_input'],[glide],[C,E,'network/GradualGlidePacket'],['ARMOR_PROC','OTHER'],['UUIDlookup','noidentitycomparison','currentgearphysics','inactiveclear']),
      ('glide_input','Native glide crouch input compensation',['glide_input'],[glide],[C],['ARMOR_PROC'],['state&&shift','divide.2','inputtick/event/useitemorder']),
      ('glide_negative','Native glide ascent/flight/removal controls',['glide','glide_input','persistence'],[glide],[L,E],['ARMOR_PROC'],['ascentunchanged','fallflyingexcluded','nonserializedwingsvsserializedflag']),
      ('double_recharge','Native Double Jump availability recharge',['double_state'],[double],[E,D],['ARMOR_PROC'],['ground/liquid/climb','inactivefalse','transitiononlysaferemoval']),
      ('double_key','Native second jump-key and server helper',['double_state','double_payload'],[double],[C,L,'network/PerformDoubleJumpPacket'],['ARMOR_PROC'],['creative<=6','storedstate','nativeairbornepredicates']),
      ('double_payload','Native second jump safe-fall and boost payload',['double_payload','slimy_bounce'],[double,slimy],[L,E,S],['ARMOR_PROC'],['nativevoidjump','resetfall','+2transient','optionalboost']),
      ('double_order','Native Double Jump gear/state and low-power controls',['double_state','double_payload'],[double],[E,L],['ARMOR_PROC'],['helpernoactivecheck','nextPretickclear','lowpowerstillconsumes','visualitemonly']),
      ('double_persistence','Native Double Jump serialized state and death controls',['persistence','double_state'],[double],[E,'init/TFDataAttachments'],['ARMOR_PROC','OTHER'],['statefalse default','nocopyOnDeath','safeattribute distinctfromeffect']),
      ('sidestep_input','Native on-ground left/right double tap',['sidestep'],[side],[C,L],['ARMOR_PROC'],['lastinputzero','samesign','dt<4','helperadmission']),
      ('sidestep_impulse','Native sidestep additive motion',['sidestep'],[side],[L,'network/PerformSidestepPacket'],['ARMOR_PROC'],['perpendicularyaw1.6','existingvelocity','currentgear','notcrouching']),
      ('sidestep_cooldown','Native sidestep cooldown and reconstruction',['sidestep','persistence'],[side],[L,W,'init/TFDataAttachments'],['ARMOR_PROC','OTHER'],['strict40/41','defaultlasttime0','notserialized','notificationsingle']),
      ('movement_validator','Native failed movement-packet validation',['validator'],[side,double],[L,'network/PerformSidestepPacket','network/PerformDoubleJumpPacket'],['OTHER'],['dedicatedonly','diff>=45','countthreshold','noHP/source']),
      ('straight_server','Native server speed presence lifecycle',['straight'],[straight],[L,E],['ARMOR_PROC'],['active +.4total','noforwardgate','presenceonly','numericupdatecontrol']),
      ('straight_client','Native client directional speed controls',['straight'],[straight],[C],['ARMOR_PROC'],['forward>0','leftdivisor','backwardsmult1','nativeattrstack']),
      ('straight_fov','Native Straight Ahead FOV compensation',['straight_fov'],[straight],[P],['ARMOR_PROC','OTHER'],['firstFCONST1','everyFRETURN','temporarilyremove','LocalPlayerrestore']),
      ('agile_weapon','Native ProjectileWeapon item-use movement',['agile'],[agile],[C],['ARMOR_PROC','ACTIVE_ITEM'],['x5before.2','!passenger','actualusingitem','damageunchanged']),
      ('agile_queen','Native whitelisted Moonworm Queen use',['agile'],[agile],[C],['ARMOR_PROC','ACTIVE_ITEM'],['whitelist','blacklistveto','nativeQueenpayloadprotected']),
      ('agile_negative','Native item/tag/gear admission controls',['agile','activation'],[agile],[C,D],['ARMOR_PROC','ACTIVE_ITEM'],['noeligibleitem','broken','mounted','extensibletags']),
      ('wing_visual','Native movement wing-state sync',['persistence','double_payload','sidestep'],[double,side],[L,'network/TravellersWingsStatePacket',W],['OTHER'],['15/11visualtimers','noextraimpulse','actualentityID','nosave'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-evidence/'+BATCH+'-asm.json','reference-routing/'+BATCH+'.json','twilightforest-travellers-movement-caller-scan.json','config-evidence/twilightforest-client.json','reference-evidence/twilight-equipment-asm.json','reference-evidence/twilight-travellers-core-244.json','reference-evidence/twilight-scepter-payloads-244.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','reference-evidence/vv-loader-244.json']
    data['exclusions']=['Nine full declared logic/state/packet classes, selected movement events/hooks, exact config, native attribute/fluid/fall/input comparison and eight registered nested transformers reviewed.','All movement has no new custom DamageType. Eligible fall veto and stored motion are distinct from subsequent native HP damage. No direct HP/SHP write or runtime claim.','Leash pathfinder ASM is structure state, not Travellers Unrestrained; separately unfinished. Belt/display/zoom, Emperor cloth and remaining ASM remain unfinished.','No Curios slot lookup in movement callbacks; generic loader/event hooks present, source-specific external compatibility NONE_PROVEN for these paths, not a pack-wide guarantee.','Protected prior mechanics and source paths retained without redoing accepted work. Twilight remains PARTIAL with zero promoted records.']
    data['fixture_groups']=['Real crafted gear plus source-water/terrain/collision matrix; exact native ASM anchors, no synthetic movement events.','Native effect/attribute stacking, crouch/equipment lifecycle and relevant save/death controls.','Genuine falls and bounce/jump sequence separating event cancellation, motion, state decoding and HP observations.','Actual input and server packet helpers for glide/double-jump/sidestep with current state, cooldown and dedicated/integrated controls.','Native forward/side/back/FOV and projectile-item-use input order with unchanged projectile payload.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-travellers-movement.json',data);assemble('twilightforest-travellers-movement.json')

if __name__=='__main__':build()
