"""Reviewed equipment mechanics with real native callback and transformer paths."""
from catalog_common import *
from collect_twilight_equipment import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed Twilight4.8.3345 outer and nested ASM bytes, raw Minecraft1.21.1 and exact NeoForge21.1.244. Static only. HP requests, ignition, retaliation, source replacement, shatter and equipment stats remain distinct. No runtime/L2/Stage/production/fix. Protected Frosted/Yeti/parry/Knightmetal/Minotaur/giant and scepter contracts are reused, not reopened.',
      'fiery_incoming':'ToolEvents.setup registers fieryToolSetFire on LivingIncomingDamageEvent. If causing entity is Living, its CURRENT main-hand item is exactly FIERY_SWORD or FIERY_PICKAXE, and recipient !fireImmune, invokes igniteForSeconds1. No direct-melee, positive amount, hurt-success, range/LOS, boss/team or explicit side/cancel predicate inside this listener; normal listener dispatch and native earlier hurt admission still apply. Exact244 server Living hurt posts Incoming before ordinary shield/cooldown/armor/HP, so later false/blocked/cooldown-rejected hits can still ignite. Sources with Living causing owner, including arrows and real offhand Cube while holding fiery tool, qualify. Source/amount unchanged; fire-immune negative. Fire Resistance is not fireImmune: it can prevent later ON_FIRE damage while ignition remains. Source whose own early hurt admission is rejected before Incoming cannot reach listener.',
      'fiery_melee':'FierySword/Pick hurtEnemy first call native superclass (true) then ignite15 seconds on server !target.fireImmune. Sword false/client/fireimmune else only particles; Pick particles only client admitted branch. Exact244 Player.attack invokes itemstack.hurtEnemy only after true primary hurt and ServerLevel, resolving multipart parent Living. Subsequent native postHurtEnemy wears Sword1/Pick2 if stack still nonempty and callback true. Sweep secondary targets have hurt calls/Incoming1-second ignition but no per-secondary item hurtEnemy15-second callback. Mob.doHurtTarget uses native damage/enchantment/knockback and never invokes item hurtEnemy/postHurtEnemy: ordinary fiery-equipped Mob gets Incoming1-second route, not Player15-second branch. No item callback on blocked/false primary hurt. No direct HP, custom fire DamageType or forced extra hit from either item method.',
      'native_burning':'Entity.igniteForSeconds floors seconds*20; Living igniteForTicks applies ceil(ticks*Attributes.BURNING_TIME), then Entity only raises existing remainingFireTicks if requested larger, never adds duration or shortens longer fire. Ordinary requested1/15 seconds =>20/300 ticks before Living burning-time multiplier. Native server Entity.baseTick, while burning and !fireImmune, every remainingFireTicks%20==0 and !inLava requests1 minecraft:on_fire, ignores hurt return, decrements fire. Direct/causing null from native onFire factory; ordinary fire tags, Fire Resistance, Protection, cooldown, absorption and extinguishing remain. No guaranteed1/15 HP totals; native fireImmune rapidly removes burning. Fiery items fireResistant property protects item stack/dropped-item against fire-type sources; it grants no wearer Fire Resistance or universal immunity.',
      'fiery_retaliation':'EntityEvents.entityHurts is registered LivingDamageEvent.Post, not Incoming or successful-return callback. Requires nonnull causing entity and event.originalDamage>0. Counts CURRENT nonempty getArmorSlots entries whose Item instanceof FieryArmorItem; ordinary four slots n0..4. fireLevel=5*n; if fireLevel>0 and wearer.random.nextInt25<fireLevel and causingEntity !fireImmune, ignite causing entity for integer fireLevel/2 seconds: n1..4 => probability20/40/60/80%, duration2/5/7/10 seconds before burning-time multiplier. No direct-Living/melee/LOS/distance/boss/team/positive-final-HP gate; projectile owners can burn, including non-Living causing entities. Current slots are read after native armor wear, so a just-broken piece no longer counts. Exact244 Post can occur at final0 after absorption or fully blocked processing; earlier Incoming/cooldown/invulnerability veto cannot reach Post. No extra armor durability cost, custom thorns HP request or elemental source; ordinary native fire ticks follow. Yeti chilling in same callback remains protected existing work.',
      'glass':'Glass tier uses1/enchantability30/attack bonus36; registered Sword adds3 =>MAINHAND attack modifier39 and speed-2.4, ordinary base1 Player fully charged noncrit plain request40 before native modifiers/mitigation (not guaranteed HP). Native Sword callbacks/sweep remain. Glass hurtEnemy sends particles then own hurtAndBreak, always returns true. Server, !Player instabuild, and private hurt true: sound/equipped-break notification, shrink1, Player broken stat. private hurt returns false when INFINITE_GLASS_SWORD component nonnull. Otherwise ServerPlayer alone calls processDurabilityChange(stack,1): <=0 prevents CUSTOM shatter; positive triggers durability criterion0 and glass-break advancement. NonPlayer callback argument would skip enchantment wear processing, but ordinary Mob attacks never invoke this callback. Custom shatter does not consult ordinary UNBREAKABLE/isDamageableItem/item damage hook itself. No target hurt call or damage bonus inside callback.',
      'glass_two_paths':'Exact244 Player true primary hurt -> Glass.hurtEnemy; if custom shatter empties stack, postHurtEnemy skipped. If custom branch is suppressed and stack survives, inherited Sword.postHurtEnemy independently calls native stack.hurtAndBreak1 with normal hooks/enchantment/instabuild/isDamageable rules. Thus a durability-saving roll in first branch does not guarantee survival of second roll; INFINITE_GLASS_SWORD alone suppresses custom shatter but not inherited native wear. Actual creative lore variant from TFCreativeTabs has BOTH INFINITE_GLASS_SWORD and minecraft:unbreakable, protecting both routes; ordinary creative instabuild also avoids wear. UNBREAKABLE alone does not veto custom shatter. Sweep secondaries do not each shatter. Ordinary glass from aurora_room loot has native enchant_with_levels20; not automatically infinite. No survival recipe is asserted. These source-proven branches are preserved without repair/fix/runtime experimentation.',
      'stale_asm':'Outer jarjar metadata binds s.tf-asm4.8.3345 archive SHA1324a81e5cf085d62385f85e4b06e6217bf977977f92c58034af315c5d975690. Its ICoreMod service names twilightforest.asm.TFCoreMod, whose getTransformers includes DamageSourcesTransformer. Transformer targets exactly DamageSources.mobAttack(LivingEntity) and playerAttack(Player), votes YES, inserts before every ARETURN: ALOAD1 then DamageSourceHooks.getCustomDamageSource(original,attacker). Hook tests attacker.getWeaponItem().getItem() instanceof CustomDamageProvider, calls provider.getDamageSource(attacker), else returns original. Full outer interface/caller scan finds CustomDamageSwordItem as sole direct implementer and STALE_BREAD as actual registered instance. This proves installed native registration/insertion intent, not a live transformed-class/runtime experiment. Other nested transformers remain pending scope.',
      'stale_source':'STALE_BREAD is CustomDamageSwordItem(TFDamageTypes.STALE_SANDWICH,Tiers.WOOD,stack1, Sword attributes3/-2.4 with hidden tooltip), not food. Native tier uses59; Player ordinary base1 plusmodifier3 =>fully charged noncrit plain request4. Provider calls attacker.damageSources().source(type,attacker): exact native source overload gives direct=causing=attacker, no projectile owner, position or amount rewrite. Declared twilightforest:stale_sandwich message twilightforest.stale_sandwich, exhaustion0, scaling when_caused_by_living_non_player; installed TF/raw tag graph has no membership. Ordinary armor/shield, Resistance/Protection, cooldown, absorption and native difficulty rules remain, no bypass inferred. Native Player/Mob attacks, Player sweep reusing selected source and any other real factory caller acquire this source only when weapon predicate holds at factory construction. getWeaponItem normally mainhand; Player auto-spin may return captured autoSpinAttackItemStack, so not unconditionally current mainhand. Arrow/thrown/mobAttackNoAggro/explicit source factories are not targeted. Installed TF minecraft:swords membership omits Stale Bread, so no ordinary sword-tag enchantment eligibility is inferred from its Java class; native supported-item rules remain.',
      'stale_alternates':'Protected CubeOfAnnihilation.getDamageSource calls owner.damageSources.playerAttack or mobAttack, so genuine Player Cube use from OFFHAND while main-hand Stale Bread is the current weapon supplies fixed10 native Cube request with stale_sandwich source; callback follows actual live owner/weapon at impact. No Bread melee callback/wear is invoked by Cube, no fabricated source or changed Cube behavior. Null-owner Cube thrown fallback is outside transformer. Native Mob carrying Bread uses mobAttack with own attribute+enchantment amount, not fixed4; native arrows owned by Bread holder keep arrow source. Genuine acquisition includes installed twilightforest:drying recipe bread->stale_bread filter_time6000. Native crafting/drying admission remains; no inference from food name.',
      'shield':'KnightmetalShieldItem extends native ShieldItem, registered durability1024. canPerformAction accepts DEFAULT_SHIELD_ACTIONS or superclass; native SHIELD_BLOCK use/72000/BLOCK semantics and facing/source/pierce/warmup/event admission, native shield disable/knockback/defense remain. Native ShieldItem constructor also registers ArmorItem dispenser-equip behavior, native OFFHAND equip with wearer/canEquip checks; this does not automatically start blocking or grant Mob shield AI. No intrinsic retaliation/spiked HP call in complete class or installed caller scan. Native Player shield wear only if shieldDamage>=3, amount1+floor(shieldDamage), native hooks/creative/enchantments; can occur on fully blocked false hurt. Repair accepts c:ingots/knightmetal OR (!minecraft:planks AND superclass repair), thus ordinary wooden planks excluded. Protected general Twilight parry can act for this shield with same config/time/projectile eligibility; no separate Knightmetal reflect mechanic or custom DamageType.',
      'stats':'Conventional armor uses native ArmorItem slot ADD_VALUE ARMOR plus toughness per piece; all listed materials have knockbackResistance0. Order helmet/chest/legs/boots: Naga only chest7/legs6, toughness.5 each, durability multiplier21; Ironwood2/7/5/2,tough0,mult20; Fiery4/9/7/4,tough1.5,mult25; Steeleaf3/8/6/3,tough0,mult10; Knightmetal3/8/6/3,tough1,mult20; Phantom only helmet3/chest8,tough2.5,mult30; Arctic2/7/5/2,tough2,mult10. Native slot durability factors11/16/15/13. These are attributes, not flat percentages or custom armor-penetration rules. Native Player armor wear positive damage floor(max(1,damage/4)), exact244 ArmorHurtEvent and ArmorItem/canBeHurtBy check; source bypass tags and item fire resistance remain. Armor constructors register real dispenser-equip route with native wearer/slot/permission checks. Yeti stats/proc already protected; Travellers modifier behavior and Phantom kept-on-death callback are separate pending sections, not invented armor-body overrides.',
      'tool_stats':'Ironwood native Sword/Shovel/Pick/Axe/Hoe with tier uses512,bonus2,enchant25; MAINHAND attack modifiers5/3.5/3/8/0, attack-speed modifiers-2.4/-3/-2.8/-3.1/-1. Steeleaf tier uses131,bonus3,enchant9; modifiers6/4.5/4/9/0, speeds-2.4/-3/-2.8/-3/-.5. Fiery tier uses1024,bonus4,enchant10; Sword modifier7/-2.4, Pick5/-2.8. Glass39/-2.4 uses1; Stale3/-2.4 uses59. Add recipient-independent base attributes and native Player charge/crit/enchant/sweep or Mob attack pipeline; never treat attribute as final HP. Tool attacks use real native source, armor/Resistance/cooldown, and Player Sword1/Digger2 post-hit wear; native Mob attacks do not consume those item callbacks. Protected Knightmetal/Minotaur/giant/Ice mechanics are not duplicated.',
      'recipe_components':'Actual native recipe output components differ from plain creative/default item stacks. Ironwood craft: Sword KnockbackI, Axe FortuneI, Pick/Hoe EfficiencyI, Shovel UnbreakingI, helmet AquaAffinityI, chest/legs ProtectionI, boots FeatherFallingI. Steeleaf craft: Sword LootingII, Axe/Shovel EfficiencyII, Pick/Hoe FortuneII, helmet ProjectileProtectionII, chest BlastProtectionII, legs FireProtectionII, boots FeatherFallingII. Naga craft chest FireProtectionIII/legs ProtectionIII. Pinned installed recipes preserve these exact native enchantments; default item registration does not grant them globally. Other captured recipes/loot may supply ordinary native enchantments; no custom statuses inferred. Full ingredient/output paths remain in native data witnesses. Native enchantment compatibility, merging and grindstone rules remain.',
      'arctic':'ArcticArmorItem.canWalkOnPowderedSnow returns stack exactly ARCTIC_BOOTS. Exact244 PowderSnowBlock tests Living FEET stack hook (or walkable entity tag), surface collision additionally requires above/not descending, with native falling-body/fall-distance branches. No blanket phasing/water walk/no-fall property. Armor dye renderer is visual. Separately installed minecraft:freeze_immune_wearables includes each Fiery/Arctic piece: native Living.canFreeze returns false if any armor slot HEAD/CHEST/LEGS/FEET/BODY is tagged, preventing native freeze accumulation/DOT path; not a veto on arbitrary DamageSource FREEZE or existing Frosted effect. Existing Yeti and Travellers vest/boots entries in that same tag are recorded as shared data, their prior/pending mechanics remain distinct.',
      'crown':'MysticCrownItem extends Item implements Equipable HEAD, native swapWithEquipmentSlot use; registration stack1 with HEAD ARMOR+2 using minecraft:armor.head ADD_VALUE, no max-damage/durability, no toughness. Native equip/curse/slot predicates remain. It is not ArmorItem and is not ordinary damageable armor; exact244 ArmorHurt hook defaults non-ArmorItem wear0. No fire/knockback/status immunity. Protected Lich scepter helpers test actual crown and apply their separately reviewed bonuses; no duplicate new scepter payload here. Native armor material body attributes are not used for crown.'
    }
    F='item/FierySwordItem';P='item/FieryPickItem';A='item/FieryArmorItem';G='item/GlassSwordItem';S='item/CustomDamageSwordItem';H='asmhooks/DamageSourceHooks';K='item/KnightmetalShieldItem';C='item/MysticCrownItem';R='item/ArcticArmorItem';E='events/EntityEvents';T='events/ToolEvents';I='init/TFItems'
    nxt='Continue Task C with Charms of Life/Keeping, Phantom retention and Keepsake Casket death/respawn paths; then Travellers gear/components and remaining utility/food, passive entities/hazards10 unfinished custom types, nested ASM and whole-mod compatibility/source closure. Protect each subsection toward R2f8 and final dedup/promotion. IceAndFire only after COMPLETE Twilight pushed/live verified. No runtime boss/L2/Stage/production/fixes/Phase6/7.'
    data=dict(slug='equipment',checkpoint_short='r2f8m',checkpoint='R2f8m-equipment-complete',decision='TWILIGHT_EQUIPMENT_SEMANTIC_REVIEW_COMPLETE',starting_sha='9588519010ff6b717f8921e8d447f3342dc34aa4',previous_checkpoint='R2f8l-bows-fan-complete',previous_draft='partial-drafts/twilightforest-r2f8l-partial.json',facts=facts,packages=[],paths=[],new_damage_types=1,full_classes=FULL,limited_classes={T:['setup','fieryToolSetFire'],E:['setup','entityHurts','getGearCoverage'],'init/TFCreativeTabs':['createGlassSwordAndLoreVer'],'nested ASM':['DamageSourcesTransformer, TFCoreMod, ASMUtil and ICoreMod service only']},registration_classes=[I,'init/TFDataComponents','init/TFArmorMaterials','util/TFToolMaterials'],closure_checklist=['Fiery_Incoming_vs_Player_callback','real_Mob_and_projectile_paths','native_burning','Post_original_vs_final','current_armor_coverage','Glass_two_break_paths','actual_infinite_variant','nested_archive_service_binding','exact_factory_transformer_targets','Stale_direct_cause_amount_tags','real_Cube_alternate','shield_native_no_spikes','native_stats_and_recipe_components','powder_collision_vs_freeze','Crown_plain_Equipable'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus conventional equipment, Fiery ignition/retaliation, Glass shatter, Stale source transformer, Knightmetal shield, Arctic snow/freeze and crown base armor. Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=29,new_used_profiles=1,reviewed_profiles_after=30,remaining_profiles=10,remaining_disposition='Other actual custom caller profiles unfinished, not unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    fire=pkg('fiery_tools_ignition','Fiery tools incoming and Player melee ignition','VANILLA_DIRECT',['fiery_incoming','fiery_melee','native_burning'],[F,P,T],{'incoming_seconds':1,'player_callback_seconds':15,'sword_wear':1,'pick_wear':2},['current causing mainhand at Incoming','native earlier admission','Player true primary callback','not fireImmune'],'Actual native fire with distinct native callback producers.','Native Player Fiery Sword/Pick hit',['Mob hit, arrow/Cube cause, sweep, false hurt, Fire Resistance and extinguishing'])
    retaliate=pkg('fiery_armor_retaliation','Fiery armor probabilistic native ignition retaliation','VANILLA_LIKE_EXTENDED',['fiery_retaliation','native_burning'],[A,E],{'fire_level_per_piece':5,'random_bound':25,'seconds_by_piece':[2,5,7,10]},['Post','original>0','causing entity','current Fiery piece count','not causing fireImmune'],'Custom reactive selection over native ignition.','Native Living Fiery armor receiving attack',['Blocked/absorbed Post, owner range, broken armor and current slots'])
    glass=pkg('glass_sword_shatter','Glass Sword native attack and two break paths','CUSTOM_RESOURCE',['glass','glass_two_paths'],[G,'util/TFToolMaterials',I,'init/TFCreativeTabs'],{'uses':1,'attack_modifier':39,'attack_speed_modifier':-2.4,'custom_shrink':1,'native_wear':1},['true Player primary hurt','server','instabuild','custom component','independent enchantment wear'],'Custom one-stack shatter followed conditionally by native wear.','Native Player ordinary Glass Sword attack',['Enchanted loot, creative lore variant, partial components, sweep/false hit/Mob'])
    stale=pkg('stale_bread_source','Stale Bread native factory source replacement','CUSTOM_DAMAGE',['stale_asm','stale_source','stale_alternates'],[S,'item/CustomDamageProvider',H,I],{'uses':59,'attack_modifier':3,'attack_speed_modifier':-2.4,'plain_player_request':4,'native_cube_request':10},['registered nested transformer','exact two factories','getWeaponItem provider','ordinary native hurt'],'Custom source identity with inherited Player/Mob/Cube amount and admission.','Native Player Stale Bread melee',['Mob, sweep, Cube offhand/mainBread, nonmatching factory/weapon controls'])
    shield=pkg('knightmetal_shield','Knightmetal native shield and repair','VANILLA_DIRECT',['shield'],[K,I],{'durability':1024,'wear_threshold':3},['SHIELD_BLOCK','native source/facing/time','native event/disable','repair material'],'Native shield with alternate durability/repair, shared protected parry.','Native Player Knightmetal Shield block',['Melee/projectile/pierce, wear/disable, parry config and repair'])
    stats=pkg('conventional_equipment_stats','Conventional Twilight tool and armor attributes','VANILLA_DIRECT',['stats','tool_stats','recipe_components'],['util/TFToolMaterials','init/TFArmorMaterials',I,'item/PhantomArmorItem'],{'armor_durability_factors':[11,16,15,13],'all_material_knockback_resistance':0,'ironwood_uses':512,'steeleaf_uses':131,'fiery_uses':1024},['correct equipment slot','actual stack recipe components','native damage/wear','real dispenser wearer'],'Native attribute/armor/enchantment primitives with installed parameter sets.','Native Player equip and melee using actual crafted gear',['Plain default versus enchanted recipes/loot, Mob gear and dispenser'])
    snow=pkg('arctic_snow_and_freeze','Arctic snow collision and Fiery/Arctic freeze eligibility','VANILLA_DIRECT',['arctic'],[R,'init/TFItems'],{'powder_hook_slot':'FEET','freeze_slots':['HEAD','CHEST','LEGS','FEET','BODY']},['actual boots hook','above/not descending','native tagged wearable','ordinary canFreeze path'],'Native powder-snow and freeze eligibility, no universal source immunity.','Native Arctic Boots on powder snow',['Single Fiery/Arctic piece, other slot, descending, explicit freeze-source control'])
    crown=pkg('mystic_crown_armor','Mystic Crown native HEAD armor','VANILLA_DIRECT',['crown'],[C,I],{'armor':2,'durability':None},['HEAD','native Equipable swap','not ArmorItem'],'Native armor attribute on nondamageable Equipable item.','Native Player Mystic Crown equip',['Slot/curse/armor wear and protected scepter interactions'])
    data['damage_profiles']=[dict(type='twilightforest:stale_sandwich',status='USED',amount='Native Player/Mob chosen attack amount; plain fully charged noncrit unmodified Player4. Actual Cube factory alternate10. Transformer does not set amount.',direct_and_causing_entities='Both attacker passed to source factory; Cube uses Living owner as both, not Cube projectile.',callers=[dict(entry='twilightforest/item/CustomDamageSwordItem.class',method='getDamageSource'),dict(entry='twilightforest/asmhooks/DamageSourceHooks.class',method='getCustomDamageSource')],admission='Installed nested transformer targets exactly native mobAttack/playerAttack returns; weapon provider required. Ordinary native hurt tags/eligibility/mitigation apply.',hurt_return_dependency='Factory replacement independent of hurt; downstream native Player/Mob/Cube callbacks preserve their own true/ignored-return rules. No added damage.')]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:equipment_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through genuine native item/source/events; future fixture only, no runtime or source fabrication.',future_controls=controls))
    rows=[
      ('fiery_player','Native Player Fiery Sword/Pick primary hit',['fiery_incoming','fiery_melee','native_burning'],[fire],[F,P,T],['MELEE','ACTIVE_ITEM'],['Incoming1 then true callback15','max not additive','wear1/2']),
      ('fiery_false','Native Fiery Incoming with later false hit',['fiery_incoming'],[fire],[T],['MELEE'],['later shield/cooldown veto','earlier admission veto','current mainhand']),
      ('fiery_mob','Native Mob carrying Fiery tool',['fiery_incoming','fiery_melee'],[fire],[T,F,P],['MOB_ATTACK','MELEE'],['Incoming1','no item callback15','no item wear from Mob.doHurtTarget']),
      ('fiery_owner','Native fiery-holder arrow/Cube owner',['fiery_incoming'],[fire],[T],['PROJECTILE','ACTIVE_ITEM'],['causing versus direct','mainhand at impact','no hurt-success condition']),
      ('fiery_sweep','Native Player Fiery sweep secondaries',['fiery_melee'],[fire],[T,F],['MELEE','AOE'],['true primary gates sweep','secondary Incoming1','no secondary15 callback']),
      ('burn','Native burning duration and damage controls',['native_burning'],[fire,retaliate],[F,P,E],['ENVIRONMENT','OTHER'],['burning_time','Fire Resistance','native ON_FIRE no owner','no guaranteed HP']),
      ('retaliation','Native Fiery wearer Post retaliation',['fiery_retaliation'],[retaliate],[A,E],['ARMOR_PROC'],['n1..4','probability and integer seconds','original>0']),
      ('retaliation_zero','Native zero-HP Post and current armor controls',['fiery_retaliation'],[retaliate],[E],['ARMOR_PROC'],['absorption/block vs early veto','just-broken slot excluded','no extra armor cost']),
      ('retaliation_owner','Native Fiery retaliation against ranged cause',['fiery_retaliation'],[retaliate],[E],['ARMOR_PROC','PROJECTILE'],['no LOS/range/direct-melee gate','nonnull owner','fireImmune negative']),
      ('glass_player','Native ordinary Glass Sword primary attack',['glass','glass_two_paths'],[glass],[G],['MELEE','ACTIVE_ITEM'],['native damage40 baseline','custom shatter after true','false hit/no shatter']),
      ('glass_rolls','Native enchanted Glass Sword wear paths',['glass_two_paths'],[glass],[G,'init/TFCreativeTabs'],['MELEE'],['independent enchantment processing','component-only controls','actual both-component lore variant']),
      ('glass_sweep_mob','Native Glass sweep and equipped Mob controls',['glass','glass_two_paths'],[glass],[G],['MELEE','AOE','MOB_ATTACK'],['one Player callback','Mob no item callbacks','native HP not guarantee']),
      ('stale_player','Native Stale Bread Player melee/sweep',['stale_asm','stale_source'],[stale],[S,H],['MELEE','AOE'],['registered transformer','type/direct/cause','charge/crit/defenses','wear']),
      ('stale_mob','Native Stale Bread equipped Mob attack',['stale_source','stale_alternates'],[stale],[S,H],['MOB_ATTACK','MELEE'],['Mob own attribute','native difficulty scaling','no item callback wear']),
      ('stale_cube','Native Cube offhand and main-hand Stale Bread',['stale_alternates'],[stale],[S,H,'entity/projectile/CubeOfAnnihilation'],['ACTIVE_ITEM','PROJECTILE'],['real factory10','current owner weapon','no fabricated source','no Bread callback']),
      ('stale_negative','Native Stale factory and weapon negative controls',['stale_asm','stale_source'],[stale],[S,H],['PROJECTILE','OTHER'],['arrow/thrown untouched','nonprovider original','getWeaponItem auto-spin exception']),
      ('stale_acquire','Native drying recipe Stale Bread acquisition',['stale_alternates'],[stale],[I,S],['OTHER'],['bread ingredient','filter_time6000','actual item not food']),
      ('shield_block','Native Knightmetal Player shield block',['shield'],[shield],[K],['ACTIVE_ITEM'],['facing/warmup/source/piercing','threshold wear','disable','no intrinsic spikes']),
      ('shield_parry','Native Knightmetal shared parry and repair',['shield'],[shield],[K],['ACTIVE_ITEM','PROJECTILE','OTHER'],['protected same parry contract','knightmetal ingot','planks negative','native dispenser OFFHAND equip without automatic blocking']),
      ('gear_craft','Native crafted conventional tools and armor',['stats','tool_stats','recipe_components'],[stats],[I,'init/TFArmorMaterials','util/TFToolMaterials'],['MELEE','PASSIVE_ITEM'],['native slot attributes','exact output enchants','default stack difference']),
      ('gear_mob_dispenser','Native conventional gear on Mob/dispenser wearer',['stats','tool_stats'],[stats],[I,'init/TFArmorMaterials'],['MOB_ATTACK','ARMOR_PROC','OTHER'],['native Mob attack','no Player item callback','dispenser wearer eligibility']),
      ('arctic_surface','Native Arctic Boots snow surface collision',['arctic'],[snow],[R],['PASSIVE_ITEM','ENVIRONMENT'],['FEET hook','above','descending/fall branches']),
      ('freeze_wearable','Native single Fiery/Arctic freeze-immune wearable',['arctic'],[snow],[R,A],['PASSIVE_ITEM','ENVIRONMENT'],['tagged slot','native canFreeze','not universal FREEZE/Frosted immunity']),
      ('crown_equip','Native Mystic Crown HEAD equip/defense',['crown'],[crown],[C,I],['PASSIVE_ITEM','ACTIVE_ITEM'],['armor2','Equipable swap','no durability','protected scepters separate'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-evidence/'+BATCH+'-asm.json','reference-routing/'+BATCH+'.json','twilightforest-equipment-caller-scan.json','reference-evidence/vv-loader-244.json','reference-evidence/twilight-frosted-244.json','reference-evidence/twilight-minoshroom-knight-244.json','reference-evidence/twilight-giants-tools-244.json','reference-evidence/twilight-utility-projectiles-244.json','vanilla-evidence/royalvariations.json']
    data['exclusions']=['Complete listed item/material/hook bodies plus real event/registration and native inherited paths reviewed; no new runtime test.','Phantom base armor is included, while death-retention producer closes with Charms/Keeping next; Travellers modifier system is pending.','Stale source transformer is bound to actual nested archive and service. Other ASM transforms are not marked complete.','Existing Frosted/Yeti/Knightmetal bonus/Minotaur/giant/scepter/parry packages reused without redoing their accepted semantics.','All other hazards/custom sources and full-mod compatibility/source attribution remain pending. Twilight PARTIAL, zero promoted;30/40 types reviewed,10 unfinished, REVIEW_REQUIRED0.']
    data['fixture_groups']=['Fiery Player/Mob/sweep/projectile Incoming timing and native burn mitigation.','Fiery armor real Post/zero-HP/owner/current-slot retaliation.','Glass true-primary callback, independent wear, actual infinite variant and native Mob/sweep contrasts.','Stale native Player/Mob and Cube factory routes with direct/cause/type/tag/amount controls.','Native Knightmetal block/repair/shared parry; conventional crafted/default stats, powder/freeze eligibility and crown equip.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=1)
    write_json(OUT/'review-inputs/twilightforest-equipment.json',data);assemble('twilightforest-equipment.json')

if __name__=='__main__':build()
