"""Reviewed structural utilities; native source contracts only."""
from catalog_common import *
from collect_twilight_structural_utilities import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed TF4.8.3345/raw Minecraft1.21.1/exact NeoForge21.1.244. Rope, Magic Beans/grower, Uberous Soil growth and remaining Time/Transformation/Sorting cores. Protected MiningCore/OreMagnet unchanged. No new DamageType:31/40 reviewed,9 unfinished. Static only; runtime0, no L2/Stage/production/Phase6/7.',
      'use_admission':'Genuine ServerPlayerGameMode useItemOn retains RightClickBlock cancellation, spectator, item-before-block/block callbacks, useItem admission/cooldown. ItemStack.useOn posts ITEM_AFTER_BLOCK; server CommonHooks.onPlaceItemIntoWorld checks adventure CAN_PLACE_ON, snapshots stack/components and captures nonbucket block changes. Consuming result posts single/multiblock-place event; cancellation restores block snapshots and prior stack/components, not all earlier custom sounds/stats. Admitted path restores new stack/components and notifications. Creative GameMode separately restores original count after useOn. Item-body shrink alone does not prove final creative cost; direct helper calls are not substitute fixtures.',
      'rope_item':'Rope is native RopeItem/BlockItem;3 Root Strand vertical recipe outputs8. Nonrope context uses normal placement. Existingrope getForward tests clickedface connectable neighbor then opposite; else first3 nearest-look directions, reversed for secondary. Y selectsDOWN; matching X/Z inspects neighboring replaceable/Rope and opposite. UP result becomesDOWN. updatePlacementContext checks candidates while horizontal counter<7, advancing only when axis already present; nonrope replaceable or missing-axis rope returns relocated context. Horizontal checks offsets0..6; vertical counter never increments. Server world-bound check remains. No7-block vertical cap or projectile/levitation.',
      'rope_placement':'Existingrope getPlacementState missing clickedface axis returns state with axis true directly, without super.canPlace; it does not repeat native survival/unobstructed check. Initial/newstate super branch does both. Actual native placeBlock flags11 return gates success/consume1, with creative rules. Rope canBeReplaced only by own item. DefaultYtrue,X/Zfalse; placement onlyclicked axis and actual WATER waterlogging. Native outer interaction/events remain.',
      'rope_support':'canConnectTo rejectsDOWN, otherwise LeavesBlock OR RopeBlock with matching axis OR center-face sturdiness at oppositeface. canSurvive needsANY enabled axis with immediate support (X west/east,Yup,Znorth/south); neighbor-sturdiness helper is passed originalpos here. Place/neighbor schedules1tick. checkConnection walks consecutive identical rope, checks each neighbor, no horizontal7 cap. Tick removes unsupportedaxes; ifnone survive destroyBlock(true), actual loot count equals true-axiscount before explosion decay. Otherwise update survivingstate and drop default one-axis rope once perremovedaxis. Waterlogged update scheduleswater; state persists natively.',
      'rope_motion':'Actual minecraft:climbable tag includesrope; NeoForge default isLadder checks it. Living.onClimbable rejects spectators and calls CommonHooks.isLivingOnLadder (native config in-block/fullboundingbox). No Y-axis requirement. Admitted native movement resets fallDistance, clampsXZ +/-float.15, descent>=-float.15; horizontalcollision orjumping whileclimbable givesY.2. Rope.isScaffolding always true, so Player suppress-sliding branch (!isScaffolding) doesnot zero negativeY atrope feet. X/Z thinbar collision only contextabove&&!descending; Y hasno collision. Outline shows activebars, pathfindablefalse. No flight/invulnerability/damage.',
      'beans_activation':'MagicBeans useOn requires clickedY<max(clickedY+100,175), exactUBEROUS_SOIL and aboveair. Server body shrink1, setBlockAndUpdate above BEANSTALK_GROWER, sound and ServerPlayer stat; mutationbool ignored. Native creative outer count restoration still applies. Wrongsoil/occupiedabove PASS. Grower noCollision/noLoot/strength-1 with typedBE ticker bothsides; client particles, server terrain. HugeStalk is ordinary solid RotatedPillar, no automatic ladder byname.',
      'beans_advancement':'Manual award requires holder!=null AND !manager.getAllAdvancements().contains(holder); native get/values use same map, so ordinary presentholder makes branchfalse. Genuine consuming GameMode.useItemOn still triggers ITEM_USED_ON_BLOCK with pre-use stackcopy. Installed beanstalk advancement requires inventorybeans AND magic_beans used on uberous_soil. Not impossible from manualguard alone. Item stat plus admitted CommonHooks stat can both fire; later placement cancellation doesnot erase earlier stat/sound.',
      'beans_clock':'Ticker increments perreal callback; ticker1 chooses nextLeafY=baseY+10+randInt10,yOffset=randInt100,cScale/rScale=.125+randFloat*.25,maxY=max(GROWERbaseY+100,175). Server growth ticker>100 and even, first102; layerY=baseY+layer. Clear and belowmax growsone layer; otherwise replacebaseHugeStalk/removeBE. Growerbase=soilY+1, distinct from preliminary itemheight. Genuine TimeCore extra typedticker calls canadvance schedule; not globaltime.',
      'beans_geometry':'Helix shifted origin uses sin/cos(baseY+yOffset)*cScale and radius4+sin((baseY+yOffset)*rScale)*3. Layer radius5+sin((layerY+yOffset)*rScale)*2.5, thickness2.5 taper remainingY/5 in last<5. Floor/ceil bounds around shifted origin; squared distance tohelixcenter<thickness^2 attemptsstalk, extraY+1 ifcircle<thickness andY+2 ifcircle<thickness/2. Only mainattempt result updatesclear flag. ResetblocksSkipped afterloop; mayplaceleaves then layer++. No PlayerBreakEvent,mobGriefing,entityoccupancy or damage call; worldmutationbools ignored.',
      'beans_blocking':'Stalk replacesair,native replaceable EXCEPTgrower,leaves or exactFLUFFY_CLOUD. Otherblocks retained; notalreadyHugeStalk and checkBlocked incrementsblocksSkipped, returns<15. Perlayer count;15th stopsmainloop,nexteligiblecallback finalizesbase. AboveY150 successfulplacement clearsWISPY/FLUFFY atUP0..6. Leafcenter setHugeStalk unconditionally; onlyair/leaves receive leaves DISTANCE1..4 flags2. Firstleaf base+10..19; later+5..14 adjusted toalternateYparity. No HP/source/hurt-return request; later solid collision native.',
      'beans_persistence':'Save/load ticker,layer,isAreaClearEnough,nextLeafY,yOffset under beardifierGroundDelta,cScale,rScale,maxY,blocksSkipped. No explicit setChanged in tick; serializable isnot guaranteed everycallback flush. Native chunkdirty/save remains. Rumbling ticker<110 presentation only. Grower listed in c:immovable and c:relocation_not_supported blockentity tags; externalconsumer behavior conditional, no universalban claimed.',
      'soil_conversion':'Soil shape15/16; placement under solid nonbonemealable resolvesDIRT. canSustainPlant rejectsnonvertical, admitscropstag, otherwisefallback. Above-neighborY+1 Bonemealable otherthanthis convertssoil: crops->moisture7FARMLAND,mushroom->MYCELIUM,Bush->GRASS,Moss->thatMossdefault,otherwiseDIRT. Native pushEntitiesUp onshapechange computes newminusoldcollision volume and intersectingentity teleportRelativeY fromcollision result. Plain solidabove nativeFarmBlock.turnToDirt. BelowY-1 Bonemealable convertssoilDIRT andtargetsbelow; callbackdoesnot separatelycheckXZ. No damage/heal/status.',
      'soil_bonemeal':'Ordinary qualifyingconversion queues server TickTask atcurrenttick, actualFakePlayerFactory.getMinecraft. Loop15 freshnative BoneMeal stacks, each exact244 applyBonemeal sameposition; no15-item cost toplayer. Each rereadscurrentblock, postsBonemealEvent; canceled returnsisSuccessful, otherwise actualBonemealable eligibility/successroll/performBonemeal. TF ignoresreturn, noearlybreak afterfailure/replacement. Actualplant/loaderhooks remain; externalpayload conditional.',
      'soil_mushgloom':'AboveMushgloom server specialbranch convertssoil/pushesentities, callsnative growMushroom thenreturns, no15-task. Mushgloom.isValidBonemealTarget false rejectsordinary bone meal; legitimate TFsoil directgrow avoids thattest andnormal40percent successroll. Exact244 growMushroom retainsBlockGrowFeature cancellation/replacement, configuredfeaturepresence, removesoriginal andrestoresif feature.placefalse. DefaultTF BIG_MUSHGLOOM stem2..3,cap1or2,foliageradius1; nativeAbstractHugeMushroom soil/buildheight/air-leafclearance, nonsolidrender stem/cap writes. FeatureLogic onlycapfaceproperties. No explosion/status.',
      'soil_spread':'Soil Bonemealable eligibility: horizontalneighbor sameY/above/below isDIRTtag orFARMLAND, notsoil, withnonsolidabove. performBonemeal Collections.shuffle directions (notpassedworldRNG), skipsvertical, checks same/above/below, spreadsfirstone. isBonemealSuccess true. spreadTo setssoil thenmanualabove callback ifnonair, allowing immediateplantconversion/task. Realbone meal caller governs event/cost. Growth/resource/collision state separate fromHP.',
      'core_activation':'SpecialMagicLog ACTIVEfalse,strength2,WOODsound, light15 onlyactive. onPlace schedules20. Server tick requiresACTIVE&&doesCoreFunction, then sound/effect/reschedule20; inactive/disabled noreschedule. useWithoutItem disabledsetsfalse/message, otherwise toggles,activation schedules20. Pinnedcommon Time/Transformation/Sorting ranges16, disabledifrange<=0. Stateblockstate persistence, nofuel/playerowner. ProtectedMiningCore sharesbase; not reopened.',
      'core_sources':'TimeTreeFeature afternative treeadmission tests origin.above state (notcoreposition) isLOGS orreplaceable, sets coreat(-1,+2,0),Yaxis/defaultACTIVEfalse,schedules20. Transformation/Sorting configs TreeCorePlacer firstlog+Y3/Y2, providerdefaultinactive. Decorator logs.get0/setprovidedstate, noactivation. Installed coreloot dropsmatchingregularlog. Genuinegrowntree use andcreative registereditem are distinct; no intactcoredrop or autoactivation assumed. TransformationLeaves animateTick particlesonly, no biomechange.',
      'time_core':'ActiveTime makes24*tickRate=480 independentsampledpositions per20tick scheduledcallback. WorldUtil uniformeachaxis[-range,+range],default16; repeatspossible, not24ticksperblock. TIME_CORE_EXCLUDED skipsentireposition, installedonlyminecraft:nether_portal. Originalstate isRandomlyTicking ->realrandomTick once. Then lookupcurrentBE but obtainticker fromORIGINALstate withactualBEtype; nonnullticker tickonce. Bothcanoccur; randomtickmaychangestate beforeBElookup. Native dispatch/type/body retained. No scheduledblockqueue/entity/globaltime advancement, syntheticdamage orsourcechange. workedflag onlyparticles. Actualgrower/hazardBE canadvance ifeligible; their ownpayloadgates remain.',
      'transformation_core':'ActiveTrans resolvesENCHANTED_FOREST, upto16 horizontalrandomsamples inconfiguredrange(Y0offset). RejectsdistSqr>256 regardlessrange andalreadytargetbiome atsampleY. Firsteligible: nativechunk,quartXZ, foreachsection sy0,4,8,12; y=clamp(QuartPos.fromBlock(chunk.getMinSection()+sy),minQuart,minQuart+QuartPos.fromBlock(level.getHeight())-1), usesy&3. Actualexpression useschunkminSECTION and repeatspersection, notsectionworldY. Ifnontarget andPalettedContainer,setquartbiome. Unclampedfourvalues coverfourlocalY; nonstandardclamp canrepeat. Markunsaved/resendbiomes/particles/break evenifnomutationultimatelyoccurred. Noexpiry/cost/directHP/effect/forceunlock. Biomedependent hazards retain actualrules; MagicMap staticcache notcleared.',
      'sort_selection':'ActiveSort inclusiveblockcube configuredradius16,skipcorepos,requireBE. Chebyshev<=2 collectsall6non-null BLOCK ItemHandlers intoinputlist; outercellsoutputs. Alive SORTABLE_ENTITIES innewAABB(core).inflate2 likewiseinputlists via6ENTITY_AUTOMATION directions. Installedtag chest_minecart,hopper_minecart,llama,trader_llama,donkey,mule; actualnonnullprovider required. Ifanyinput, entityoutputs alive/tagged withinFIXEDinflate16 (notconfig),excludingentities alreadyinput. No explicitowner/tame/team test; Playernotininstalledtag. Nativeprovideraccess rules remain; no Curios bypass.',
      'sort_order':'InputMap keyList<IItemHandler>,OutputMap keyhandler: equalkeys overwritepositions; sidedduplicates withininputlistremain. Foreachinputgroup/slot simulateextract1; ifnonempty sumoutputstacks withsameITEM regardlesscomponents. Onlycount>0, cannotseedemptydestination. Map<count,handler> retainsone pertie withunspecifiedHashMap iteration; descendingcounts. Targetslot requiresisItemValid, remembersfirstempty butpreferslater sameitem+samecomponents belowmaxstacksize ANDslotlimit. NoLOS/distance/resource cost beyondselection.',
      'sort_transfer':'Chosenoutputslot: ACTUALinput.extractItem(slot,1,false) BEFORE output.insertItem(slot,newStack,true). Nonemptyactualextract andEMPTYsimremainder ->actualinsertfalse; actualremainder IGNORED, transferredtrue andbreakslot/handlerloops forinputgroup. AtmostoneREPORTEDsuccess pergrouppercallback, notoneallgroups. Simrejection afterextract hasNOreinsertion; cantryanotheroutput andextractagain. No rollback ifactualinsertdiffers. Sourcecontracts, notruntimeobservedloss or guaranteedatomic transfer; handlers determineactualresults.',
      'sort_cache':'RegisteredSort Blockobject ownsonefinal directionalcache. Keyrecord ONLYBlockPos+Direction, nolevel/dimension/capability. Firstmiss createsNeoForge cache withfinallevel,pos,context; laterhit nolevelcheck. Exact244 getCapability returnscachedvalue orqueriesSTOREDlevel ifloaded; invalidationclearsvalidity, neverrebindslevel. Samecoord/side inanotherlevel canreusefirstlevelcache after currentlevelBE admission. Notserialized,noclear/partition inTFclass. No runtimeoutcome/pack-wideclaim orfix; providerinvalidation native.',
      'compatibility':'Native NeoForge use/snapshot/placement, ladder/scaffolding, Bonemeal/BlockGrowFeature andcapabilities are GENERIC_CONDITIONAL_PRESENT. Actual bundled interop tags (immovable/relocation,treeattachments,compostactivators/randomiumexclusions) are declarations, externalconsumer behavior UNKNOWN untilproved. No directexternal source-specific combat override proven in scopedbodies (NONE_PROVEN), no packcertification. Dynamicplant/BE/capability bodies retaineligibility/sourceidentity. Passives/hazards/ninetypes/otherstructures/ASM/sourceclosure unfinished.'
    }
    R='block/RopeBlock';I='item/RopeItem';B='item/MagicBeansItem';G='block/entity/GrowingBeanstalkBlockEntity';U='block/UberousSoilBlock';T='block/TimeLogCoreBlock';X='block/TransLogCoreBlock';S='block/SortLogCoreBlock';C='block/SpecialMagicLogBlock';K='util/BlockCapabilityDirectionalCache'
    nxt='Review remaining passive entities and environmental hazards (thorns, oreberry, knightmetal, fiery, fire_jet, reactor, slider, ominous_fire, acid_rain), all actual callers and other combat-significant structures/callbacks; finish nested ASM, compatibility and source exclusions. Protect R2f8 then Twilight COMPLETE promotion before IceAndFire. Static only; no runtime/L2/Stage/production/Phase6/7.'
    data=dict(slug='structural-utilities',checkpoint_short='r2f8u',checkpoint='R2f8u-structural-utilities-complete',decision='TWILIGHT_STRUCTURAL_UTILITIES_SEMANTIC_REVIEW_COMPLETE',starting_sha='45e1866125b36a5a4bfa1d0b26190043abd3da66',previous_checkpoint='R2f8t-maps-information-complete',previous_draft='partial-drafts/twilightforest-r2f8t-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=0,full_classes=FULL,limited_classes={'world/components/feature/trees/TimeTreeFeature':['generate/core placement'],'world/registration/TreeConfigurations':['core decorator configuration'],'util/features/FeatureLogic':['mushroom face helper'],'util/WorldUtil':['getAllAround/randomOffset'],'config/TFConfig':['rebakeCommonOptions']},registration_classes=['init/TFItems','init/TFBlocks','init/TFBlockEntities','init/TFConfiguredFeatures','init/TFFeatures','init/TFFeatureModifiers'],closure_checklist=['native_interaction_creative_restoration','rope_extension_support_and_drops','rope_climb_scaffolding_collision','beans_soil_air_native_advancement','grower_delay_geometry_blocking_persistence','soil_native_displacement','real15bonemeal_calls_events','mushgloom_directgrow_nativefeature','core_state_config_schedule_producers','time_random_and_typed_BE_ticks','biome_fixedradius_actual_quart_expression','sort_real_sided_block_entity_capabilities','sort_countties_extract_before_simulate','sort_dimensionless_cache_loader_storage','scoped_compatibility_boundaries'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus Rope, MagicBeans/grower, UberousSoil/Mushgloom native growth and remaining Time/Transformation/Sorting cores; Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=31,new_used_profiles=0,reviewed_profiles_after=31,remaining_profiles=9,remaining_disposition='All nine have source aids/callers located; semantic review unfinished, not unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,controls):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=controls));return eid
    rope=pkg('rope_structural_movement','Rope native placement, support and movement','VANILLA_LIKE_EXTENDED',['use_admission','rope_item','rope_placement','rope_support','rope_motion'],[R,I],{'horizontal_check_budget':7,'support_delay':1,'climb_speed_cap':.15,'native_climb_Y':.2},['realuse','axis','support','nativeclimbability','collisioncontext'],'Custom rope structure over native ladder/scaffolding movement.','Genuine placed/climbed Rope',['intersection','descending','unsupported','waterlogged','creative/survival'])
    beans=pkg('magic_beans_terrain_growth','Magic Beans native growing terrain','CUSTOM_CONTROL',['use_admission','beans_activation','beans_advancement','beans_clock','beans_geometry','beans_blocking','beans_persistence'],[B,G,'block/GrowingBeanstalkBlock'],{'first_growth_tick':102,'growth_modulo':2,'blocked_limit':15,'height_formula':'max(growerY+100,175)','thickness':2.5},['exactsoil','aboveair','serveruse','typedticker','clearance','height'],'Custom scheduled terrain construction; no attack or heal.','Native Beans use on Uberous Soil',['obstruction','TimeCoreticker','save/load','worldheight','placecancel'])
    soil=pkg('uberous_soil_native_growth','Uberous Soil native growth and shape transition','VANILLA_LIKE_EXTENDED',['soil_conversion','soil_bonemeal','soil_mushgloom','soil_spread'],[U,'block/MushgloomBlock','world/components/feature/BigMushgloomFeature','util/features/FeatureLogic'],{'shape_height':15,'bonemeal_calls':15,'mushgloom_stem':[2,3],'mushgloom_cap':[1,2]},['neighborchange','Bonemealable','FakePlayer/event','Mushgloomroute','featureclearance'],'Custom batch/spread over native bone meal/features/collision displacement.','Actual plant placement adjacent to Soil',['above/below','crop/mushroom/bush/moss','cancel','spread','Mushgloom'])
    time=pkg('time_core_native_ticks','Timewood core native callback acceleration','CUSTOM_CONTROL',['core_activation','core_sources','time_core'],[T,C,'util/WorldUtil','world/components/feature/trees/TimeTreeFeature'],{'period':20,'samples':480,'configured_range':16},['ACTIVE','enabledrange','nonexcluded','randomtickflag orvalidBEticker'],'Extra genuine callbacks, not global time or damage multiplier.','Activated real Timewood core',['bothcallbacks','excludedportal','repeatpositions','grower/hazard'])
    trans=pkg('transformation_core_biome','Transformation core native biome replacement','CUSTOM_CONTROL',['core_activation','core_sources','transformation_core'],[X,C,'world/registration/TreeConfigurations','world/components/feature/trees/treeplacers/TreeCorePlacer'],{'period':20,'attempts':16,'configured_range':16,'max_distance_squared':256},['ACTIVE','enabledrange','nonTargetbiome','PalettedContainer'],'Persistent biome mutation, no direct combatstat.','Activated real Transformation core',['fixedradius','quartY','alreadytarget','save/sync','mapcache'])
    sort=pkg('sorting_core_item_transfer','Sortingwood core native inventory transfer','CUSTOM_RESOURCE',['core_activation','core_sources','sort_selection','sort_order','sort_transfer','sort_cache'],[S,C,K,K+'$BlockPosAndDirection','world/registration/TreeConfigurations','world/components/feature/trees/treeplacers/TreeCorePlacer'],{'period':20,'input_radius':2,'block_output_range':16,'entity_output_radius_fixed':16,'extract_request':1},['ACTIVE','actualcapability','taggedaliveentity','matchingitem','extract/inserteligibility'],'Native item-handler transfer/selection, no HP/SHP drain.','Activated real Sorting core with valid handlers',['block/entitysides','ties','simreject','cachelevel','insertrules'])
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:structural_utilities_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through native item/block/ticker/provider; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('rope_new','Native initial Rope placement',['use_admission','rope_placement'],[rope],[I,R],['ACTIVE_ITEM','ENVIRONMENT'],['survival/unobstructed','flags11','creative']),
      ('rope_extend','Native Rope extension/axis addition',['rope_item','rope_placement'],[rope],[I,R],['ACTIVE_ITEM','ENVIRONMENT'],['horizontal7','verticaluncapped','secondary','directaxisbranch']),
      ('rope_support','Native unsupported Rope update/drop',['rope_support'],[rope],[R],['ENVIRONMENT'],['1tick','supports','all vsoneaxis']),
      ('rope_climb','Native Rope ladder/scaffolding movement',['rope_motion'],[rope],[R],['ENVIRONMENT'],['XZ-only','spectator','fallreset','.15/.2','nativeconfig']),
      ('rope_collision','Native Rope platform/descending/water',['rope_motion','rope_support'],[rope],[R],['ENVIRONMENT'],['topXZ','Ynocollision','descending','water']),
      ('beans_use','Native Magic Beans use',['use_admission','beans_activation','beans_advancement'],[beans],[B],['ACTIVE_ITEM','ENVIRONMENT'],['soil/air','creativeouterrestore','placecancel','nativecriterion']),
      ('beans_wait','Native grower wait/first layer',['beans_clock'],[beans],[G,'block/GrowingBeanstalkBlock'],['ENVIRONMENT'],['102','typedBE','clientparticles','baseY']),
      ('beans_growth','Native beanstalk helix/leaves',['beans_geometry','beans_blocking'],[beans],[G],['ENVIRONMENT'],['taper','extraY','leafparity','noHP']),
      ('beans_blocked','Native blocked-layer/cloud behavior',['beans_blocking'],[beans],[G],['ENVIRONMENT'],['15threshold','stalkexcluded','cloudY150','leafcenter']),
      ('beans_save','Native grower save/extra ticker',['beans_persistence','beans_clock','time_core'],[beans,time],[G,T],['ENVIRONMENT'],['allfields','noexplicitdirty','realextraBEtick']),
      ('soil_above','Native Soil upper-plant transition',['soil_conversion','soil_bonemeal'],[soil],[U],['ENVIRONMENT'],['moisture7','planttypes','pushEntitiesUp']),
      ('soil_below','Native Soil lower-plant callback',['soil_conversion','soil_bonemeal'],[soil],[U],['ENVIRONMENT'],['Y-1','dirt','FakePlayer15']),
      ('soil_bone','Native queued Soil bonemeal',['soil_bonemeal'],[soil],[U],['ENVIRONMENT'],['freshstacks','cancel','currentplant','returnignored']),
      ('soil_mush','Native Soil Mushgloom growth',['soil_mushgloom'],[soil],[U,'block/MushgloomBlock','world/components/feature/BigMushgloomFeature'],['ENVIRONMENT'],['ordinarybonemealreject','directgrow','BlockGrowFeature','restorefailure']),
      ('soil_spread','Native bonemeal Soil spread',['soil_spread','soil_conversion'],[soil],[U],['ACTIVE_ITEM','ENVIRONMENT'],['event/cost','shuffle','onecell','newcallback']),
      ('core_toggle','Native core toggle/config/schedule',['core_activation'],[time,trans,sort],[C],['ACTIVE_ITEM','ENVIRONMENT'],['inactive','disabledrange','20tick','persistence']),
      ('time_tree','Native grown Timewood core',['core_sources'],[time],['world/components/feature/trees/TimeTreeFeature'],['ENVIRONMENT'],['origin.abovecheck','offset','inactive','treeadmission']),
      ('trans_sort_tree','Native core tree decorators',['core_sources'],[trans,sort],['world/registration/TreeConfigurations','world/components/feature/trees/treeplacers/TreeCorePlacer'],['ENVIRONMENT'],['firstlog+3/+2','provider','inactive','logdrops']),
      ('time_random','Native Timewood random block ticks',['time_core'],[time],[T],['ENVIRONMENT'],['480samples','cube16','tickflag','portalexclude']),
      ('time_be','Native Timewood typed BE ticks',['time_core'],[time],[T],['ENVIRONMENT'],['originalstate/currentBE','bothcallbacks','hazardgates']),
      ('trans_biome','Native Transformation biome column',['transformation_core'],[trans],[X],['ENVIRONMENT'],['16attempts','dist256','sameYskip','quartloop']),
      ('trans_store','Native transformed-biome persistence',['transformation_core'],[trans],[X],['ENVIRONMENT'],['unsaved','resend','noexpiry','mapcache']),
      ('sort_blocks','Native Sorting block handlers',['sort_selection','sort_order'],[sort],[S,K],['ENVIRONMENT'],['cube','inner2','6sides','BE']),
      ('sort_entities','Native Sorting entity handlers',['sort_selection'],[sort],[S],['ENVIRONMENT'],['alive6types','2/fixed16','noPlayerdefault','capability']),
      ('sort_priority','Native Sorting count/slot priority',['sort_order'],[sort],[S],['ENVIRONMENT'],['itemcount','components','noemptyseed','tiedoverwrite']),
      ('sort_transfer','Native Sorting extraction/insertion',['sort_transfer'],[sort],[S],['ENVIRONMENT'],['extractbeforeoutputsimulate','no rollback','remainderignored','onegroupreported-success']),
      ('sort_cache','Native Sorting cache boundary',['sort_cache'],[sort],[S,K,K+'$BlockPosAndDirection'],['ENVIRONMENT'],['pos+side','storedlevel','otherlevelsamecoord','invalidation']),
      ('core_controls','Native inactive/disabled/eligibility controls',['core_activation','time_core','transformation_core','sort_selection','sort_order'],[time,trans,sort],[C,T,X,S],['ENVIRONMENT'],['nocharge','ineligibleposition','nohandler/output','noHP'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-structural-utilities-caller-scan.json','config-evidence/twilightforest-common.json','reference-evidence/twilight-active-utilities-244.json','reference-evidence/twilight-travellers-movement-244.json']
    data['exclusions']=['Six distinct utilities; protected MiningCore/OreMagnet reused, no duplicate.','Sixteen full TF classes plus limited registrations/callers. TransformationLeaves particles only; generic tree/recipe/loot infrastructure not additional combat packages.','TimeCore delegates real handlers, not universal24x or newsource. Interop tags are declarations, external consumers conditional.','Remaining passives/hazards/ninecustomtypes, other structures/callbacks and ASM/compatibility/source closure unfinished.']
    data['fixture_groups']=['Real Rope placement/axes/extension/support/drop/climb/platform/water with native interaction.','Beans proper soil/air/creative/events/advancement; tick102, blocking15, leaves/clouds, persistence, realTimewood callbacks.','Soil displacement/15 FakePlayer bone meal calls/specialMushgloom growth with nativegates/onecellspread.','Grown/placed inactivecores, config/toggle/schedule, Time random/BE callbacks and actual Transformation quartbiomes.','Sorting real block/entity handlers, ties/slots, extraction-before-simulation/remainder and cross-level cache boundary.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-structural-utilities.json',data);assemble('twilightforest-structural-utilities.json')

if __name__=='__main__':build()
