"""Reviewed structure admission, real hint production, and terrain barriers."""
from catalog_common import *
from collect_twilight_structure_gates import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    P='events/ProgressionEvents';U='world/components/structures/util/';S=U+'ProgressionStructure';H=U+'StructureHints';B='block/StrongholdShieldBlock';T='block/TrophyPedestalBlock';F='block/ForceFieldBlock'
    facts={
      'authority':'Installed TF4.8.3345 with exact Minecraft1.21.1/NeoForge21.1.244, static evidence only. Terrain shields, advancement admission and actual HP damage remain distinct. No new DamageType, direct HP subtraction, runtime fixture execution, production/Stage/L2/Phase6/7 change. All40 custom types already resolved in protected Y; whole Twilight remains PARTIAL pending portal/control blocks, other events/ASM/source/compatibility closure and final promotion.',
      'area_gate':'Registered ProgressionEvents callbacks call isAreaProtected: server level, player not instabuild, not spectator, not FakePlayer, tfEnforcedProgression true, actual located structure start, at least one containing piece whose isPieceProtected is true, actual structure instanceof ProgressionStructure and player missing required advancement. No conquered-state test, DamageType/tag bypass, boss HP or item ownership test. Gamerule is registered defaulttrue; actual world value is not statically assumed. Native PlayerHelper first-entry-only advancement behavior is reused; installed structure lists each have one entry.',
      'landmark_lookup':'LandmarkUtil locateNearestLandmarkStart uses the actual LANDMARK structure tag, legacy nearest-center XZ from supplied chunk coordinates, then center chunk STRUCTURE_STARTS and first matching tagged start. Default readiness check returns empty if that center chunk is not loaded; missing registry/tag/start is empty. It is not an unrestricted nearest bounding-box search. Area admission uses uninflated containing piece bounds; the attack position is victim.blockPosition. Default isPieceProtected is true unless the piece implements ProgressionPiece and returns false.',
      'piece_exceptions':'Installed method census resolves six false overrides: StrongholdAccessChamber, StrongholdUpperAscender, StrongholdUpperLeftTurn, StrongholdUpperRightTurn, StrongholdUpperCorridor and StrongholdUpperTIntersection components. Other actual ProgressionPiece default is true. Access chamber pedestal can therefore be used before the deeper Stronghold advancement; overlapping containing protected pieces can still satisfy anyMatch. Native structure records, pieces and player advancements persist normally; this event gate stores no per-victim invulnerability flag.',
      'block_actions':'BreakEvent server/notcanceled requires block NOT in twilightforest:progression_allow_breaking and area gate, then cancels. EntityMultiPlaceEvent server/Player/notcanceled applies the same break-tag/area tests to replaced snapshots, cancels and resyncs inventory on first protected snapshot. The listener named preventLockedAreaBlockPlacing actually receives every RightClickBlock: server/notcanceled plus area gate cancels and resyncs inventory, without requiring a BlockItem, attempted placement or banned-interaction tag. Installed break allow-tag includes skull_chest, keepsake_casket and optional gravestone:gravestone; banned-interaction tag includes lever, antibuilder, buttons and c:chests. Separate RightClickBlock banned-interaction listener sets UseBlock FALSE for tagged blocks in protected area; earlier full event cancellation is broader and normal event dispatch may skip canceled events. Do not turn the break allow-tag into an all-interaction exemption.',
      'incoming_damage':'LivingIncomingDamageEvent listener requires server Living victim implementing Enemy, source.getEntity() instanceof Player (causing entity, not direct entity), victim not Kobold and area gate at victim block position. It cancels the event, making native LivingEntity.hurt return false before block/armor/damage processing. Real player-owned projectiles can qualify; ownerless sources, mob-caused sources, PVP/non-Enemy victims, Kobolds and exempt players do not satisfy this listener. No source rewrite, reflection, new damage, shield count or direct HP operation. Other native admission/defense/loader listeners remain, including on paths this listener does not cancel.',
      'feedback':'On positive area gate, containing-piece boxes are sent via AreaProtectionPacket to players within64 and real hint production is attempted; this happens even though the player action/damage is subsequently denied. Registered PlayerTick.Post every100 with progression enabled sends locked-structure display using broader AdvancementLockedStructure interface: protected pieces inflated4 for display, unprotected pieces unchanged. Present unlocked start or creative/spectator sends clear; absent start returnsfalse without clear. These packets/render bounds do not expand real protection or create damage. Protected Y biome enforcement at20 ticks is unchanged; portal branch still pending.',
      'hint_sources':'Two genuine callers feed StructureHints: protected action/attack denial at attempted position, and protected Y biome enforcement optional hint_structure via registry lookup. ProgressionStructure holds lastSpawnedHintMonsterTime on the structure registry object, not player, structure start or separate dimension key; initial0 and no serialization. World time below storedtime resets0. Only strict currentTime-last>1200 attempts up to20 times, stops and sets timestamp on first didSpawnHintMonster true; failed attempts do not reset cooldown. First possible attempt from initialstate is worldtime1201, not immediate.',
      'hint_delivery':'Each attempt uses X/Z difference of two nextInt16 (-15..15) and Y difference of two nextInt4 (-3..3) relative to supplied position. Optional configured EntityType.create returns Mob or null; moves to position, then checkSpawnObstruction and sensing.hasLineOfSight(player). Nonempty configured hint item is copied with components into MAINHAND, dropchance1; world.addFreshEntity return is discarded, then method returns true. Thus add-veto can still advance cooldown. No finalizeSpawn call, normal spawn-rule/light test, owner/tame/team assignment or explicit persistenceRequired. Native entity add hooks and native book/equipment drop admission remain. Existing Kobold combat package is reused, not a duplicate new attack.',
      'hint_configuration':'All10 installed hint-configured structure resources specify actual twilightforest:kobold: aurora_palace requires progress_yeti; dark_tower progress_knights; final_castle progress_troll; giant_house/troll_cave progress_merge; hydra_lair progress_labyrinth; knight_stronghold progress_trophy_pedestal; labyrinth/yeti_cave progress_lich; lich_tower progress_naga. Each required list has one entry. HintConfig.checkCastMob literally uses entityType.getBaseClass().isAssignableFrom(Mob.class); exact loader EntityType.getBaseClass returns Entity.class, so this check is not independent subclass proof. Installed actual factories are Kobold. Default generated written-book content has generation3/resolvedtrue/translatable pages; item contents are not damage. ProgressionWrappedStructure delegates generation/settings to wrapped structure and retains progression interfaces, not a new attacker.',
      'stronghold_shield':'StrongholdShieldBlock is a terrain barrier, not the Lich entity shield. Default FACING DOWN, placement nearestLookingDirection with vertical opposite. Properties hardness-1/resistance6000000/no loot/requires correct tool/piston BLOCK; canEntityDestroy false. getDestroyProgress ray traces from player eye/view with BLOCK_INTERACTION_RANGE+1, OUTLINE and FluidNONE. It compares only hit direction to FACING when vertical, otherwise FACING.opposite; no explicit hit-position equality or hit-type check. On matching side returns native player.getDigSpeed(STONE,pos)/1.5/100. Other side uses native parent hardness-1 =>0 normal mining progress. Native mining/equipment/interaction and progression events still apply; creative native destruction path is distinct from ordinary progress. No contact hurt, HP damage, reflect or owner requirement.',
      'shield_producers':'Exact caller evidence records real structure placements, including StrongholdAccessChamber postProcess placing default Trophy Pedestal and a5x5 Stronghold Shield floor; Stronghold wall generation uses actual face states. Pedestal removal is a separate native terrain path. Force-field producers are actual Final Castle structure methods recorded in source-providers evidence; no speculative player damage from visual barrier names.',
      'pedestal_activation':'TrophyPedestal default ACTIVEfalse/WATERLOGGEDfalse; placement detects native water and update schedules water tick. neighborChanged first updates comparator, then server+inactive+above block in TROPHY_PEDESTAL_ACTIVATION_BLOCKS. With progression enabled, any eligible nearby Player permits doPedestalEffect; all ineligible nearby players receive warning. Eligibility is progress_lich OR instabuild. Native getEntitiesOfClass default excludes spectators, within AABB(blockpos).inflate16. With gamerule disabled no nearby eligible player required. Native installed activation tag has8 ground boss trophies (Naga,Lich,Minoshroom,Hydra,Knight,Ur,Alpha,Snow); no default wall/QuestRam trophy member. Ordinary neighbor trigger and tag membership are required, not manual direct helper execution.',
      'pedestal_effect':'doPedestalEffect first writes ACTIVEtrue, then traverses inclusive offsets-5..5 in all3 axes and destroys only exact STRONGHOLD_SHIELD without drops, then plays sound. It does not consume the trophy, damage entities, clear all force fields or emit a player BreakEvent itself. State-write/destroy returns are discarded. No automatic deactivation on trophy removal. Inactive destroyProgress returns-1 and piston BLOCK; active uses parent hardness2/resistance2000 and piston NORMAL. Comparator returns above real TrophyBlock comparatorValue, otherwise0; tag extension alone does not create a comparator value. Block state persists via native chunk data.',
      'pedestal_reward':'After the server inactive+trophy branch, rewardNearbyPlayers executes regardless of whether player eligibility allowed shield removal. All nearby native-query ServerPlayers receive PLACED_TROPHY_ON_PEDESTAL trigger and TROPHY_PEDESTALS_ACTIVATED stat request. With failed activation, repeated neighbor changes can repeat stat/criterion requests. SimpleAdvancementTrigger invokes native listener processing with true custom test; native listener/player predicates still apply. Actual progress_trophy_pedestal resource requires BOTH trophy_pedestal criterion (placed_on_trophy_pedestal) AND kill_lich tick criterion checking progress_lich. An ineligible player can bank the trophy criterion/stat but does NOT thereby complete the advancement or unlock deeper Stronghold. No separate owner/player who placed trophy test.',
      'force_field':'All5 force-field colors use hardness-1/resistance3600000.8/light2/noLoot/noOcclusion/pistonBLOCK, with canEntityDestroyfalse. They do NOT set noCollision: native collision follows getShape, consisting of central cube7/16..9/16, enabled direction arms and qualifying corner planes. No entityInside/hurt/HP/projectile reflect/owner admission. This is physical terrain collision; entity behavior outside its shape is native. Different colors are distinct blocks for direct same-block connection, while any ForceFieldBlock can participate in the corner helper.',
      'force_connections':'Default6 direction bits false and WATERLOGGEDfalse. canConnectTo accepts same exact field block; otherwise counts better connections (adjacent sameblock at placement/nullstate; existing true bits on update) and refuses solid-face connection when count>=3; else requires not native isExceptionForConnection and neighbor face sturdy. Placement forces opposite clicked face true and clicked face true unless secondary use; other directions use canConnectTo(null). Corner helper requires both adjacent direction bits plus sturdy opposite neighbor face or another ForceField whose corresponding bit is true. updateShape schedules water if already waterlogged and sets a direction true if now connectable, but returns unchanged state on failure; it never clears a stale connection bit. Placement does not read fluid, despite waterlogging interface; later native waterlogging and native state save remain. Rotation/mirror permute bits normally.',
      'compatibility':'DIRECT_SOURCE_SPECIFIC: optional gravestone:gravestone tag exemption is a real direct resource mapping, conditional on that registry entry existing; installed Twilight progression listeners match its native progression structures/pieces, tags, player advancement and Kobold exclusion. GENERIC_CONDITIONAL_PRESENT: exact loader RightClick/Break/MultiPlace/IncomingDamage/entity-add hooks, native mining attributes and native criterion predicates. These are real conditional hooks, not evidence that every pack mod cancels, bypasses or augments them. NONE_PROVEN: this inspected barrier/hint logic has no source-specific Tensura/L2 or Curios mapping. UNKNOWN: pack-wide cross-mod outcomes and untested runtime ordering. No runtime compatibility claim from static absence.'
    }
    nxt='Continue native vanishing/reappearing/locked blocks and Castle Doors, then portal/control blocks and remaining events/nested ASM/compatibility/source exclusions. All40 DamageTypes closed; whole Twilight PARTIAL until complete source closure and final dedup/promotion. IceAndFire only after live-verified Twilight COMPLETE. Static only.'
    data=dict(slug='structure-gates',checkpoint_short='r2f8z',checkpoint='R2f8z-structure-gates-complete',decision='TWILIGHT_STRUCTURE_GATES_SEMANTIC_REVIEW_COMPLETE',starting_sha=git('rev-parse','HEAD').strip(),previous_checkpoint='R2f8y-ominous-progression-complete',previous_draft='partial-drafts/twilightforest-r2f8y-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=0,full_classes=FULL,limited_classes={P:['registered protected actions/hostile admission and display; portal next'],'util/landmarks/LandmarkUtil':['loaded landmark lookup, progression gamerule'],'util/PlayerHelper':['protected first-entry advancement helper reused'],'util/entities/EntityUtil':['shield mining ray trace'],'block/AbstractTrophyBlock':['stored comparator value'],'advancements/SimpleAdvancementTrigger':['actual pedestal criterion trigger'],'advancements/SimpleAdvancementTrigger$TriggerInstance':['actual pedestal criterion factory'],'structure_provider_census':['selected genuine producer methods and every isComponentProtected declaration']},registration_classes=['init/TFBlocks','init/TFEntities','init/TFAdvancements'],closure_checklist=['actual_registeredevents','native_causing_player_gate','fakeplayer_exclusion','loaded_landmark_lookup','six_unprotected_piece_overrides','ordinary_break_vs_rightclick','feedback_notlargerprotection','actual_hint_cadence','native_hint_create_no_finalize','ignored_entityadd_return','configured10_kobolds','directional_shield_native_mining','pedestal_eligibility_vs_reward','both_advancement_requirements','native_shield_removal_noHP','forcefield_actual_collision','stale_connection_persistence','compat_attribution'],compatibility_scope=facts['compatibility'],current_scope='Prior Twilight plus structure action/hostile admission, actual hint Kobold production, Stronghold Shield directional mining, Trophy Pedestal removal/advancement and Force Field collision. Twilight PARTIAL; no promotion.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=40,new_used_profiles=0,reviewed_profiles_after=40,remaining_profiles=0,remaining_disposition='None:40 USED; wider event/ASM/source closure remains.'))
    def pkg(k,title,kind,keys,cs,nums,gates,rel,source,controls):
        eid='twilightforest:'+k;data['packages'].append(dict(id=eid,display_name=title,owner=k,primary_classification=kind,facts=keys,classes=cs,parameters=nums,gates=gates,relation=rel,primary_test_source=source,alternate_sources=controls));return eid
    action=pkg('progression_structure_action_admission','Progression structure player action gate','BINARY_MECHANIC',['area_gate','landmark_lookup','piece_exceptions','block_actions','feedback'],[P,U+'ProgressionPiece'],{'display_period':100,'display_inflation':4},['loadedlandmark','protectedpiece','missingadvancement','nonexemptplayer'],'Custom conditional event cancellation over native block actions.','Real locked-structure player mining/right-click',['allowbreaktag','FakePlayer','creative','gamerule','unloadedcenter'])
    incoming=pkg('progression_structure_hostile_damage_admission','Progression structure hostile damage gate','BINARY_MECHANIC',['area_gate','landmark_lookup','piece_exceptions','incoming_damage','feedback'],[P],{},['Enemy','causingPlayer','notKobold','nativeIncomingDamage'],'Custom incoming cancellation; actual source and native hurt pipeline unchanged.','Actual player attack on hostile in locked structure',['playerprojectile','mobattacker','ownerless','Kobold','nonEnemy'])
    hint=pkg('progression_native_hint_mob_production','Progression native hint Kobold production','CUSTOM_RESOURCE',['hint_sources','hint_delivery','hint_configuration'],[S,H,U+'StructureHints$HintConfig'],{'strict_cooldown':1200,'max_attempts':20,'horizontal_extent':15,'vertical_extent':3,'drop_chance':1},['configuredhint','strictcooldown','nativeobstruction','LOS','actualentityadd'],'Custom native Mob/book producer reusing existing Kobold combat.','Native locked action or biome hint attempt',['addveto','noLOS','obstruction','sharedcooldown','bookdrop'])
    shield=pkg('stronghold_shield_directional_mining','Stronghold Shield directional mining gate','BINARY_MECHANIC',['stronghold_shield','shield_producers'],[B],{'native_stone_speed_divisor':150,'extra_reach':1,'hardness':-1,'blast_resistance':6000000},['raydirection','nativeDigSpeed','realminingevents'],'Custom face predicate selects native digging speed; terrain only.','Genuine player mining from each shield face',['horizontal','vertical','creative','eventcancel','pedestal'])
    pedestal=pkg('trophy_pedestal_native_unlock','Trophy Pedestal shield removal and progression credit','CUSTOM_CONTROL',['pedestal_activation','pedestal_effect','pedestal_reward','shield_producers'],[T,'advancements/SimpleAdvancementTrigger'],{'player_aabb_inflation':16,'shield_cube_radius':5,'cube_positions':1331},['serverinactive','validtrophy','gamerule/eligible','separatecriteria'],'Custom terrain removal plus native advancement/stat processing; no HP damage.','Actual trophy neighbor update on unprotected access-chamber pedestal',['ineligible','creative','gameruleoff','Lichcriterion','repeatedneighbor'])
    force=pkg('force_field_native_collision','Force Field conditional terrain geometry','CUSTOM_CONTROL',['force_field','force_connections','shield_producers'],[F],{'colors':5,'central_min':.4375,'central_max':.5625,'solid_connection_limit':3},['realblockstate','connectionbits','nativeshape'],'Custom terrain shape with native collision/waterlogging, no attack.','Actual castle force fields and legitimate block placement',['colors','staleconnections','secondaryuse','water','corners'])
    def path(k,title,keys,ids,cs,labels,controls):data['paths'].append(dict(id='twilightforest:structure_gates_path:'+k,source=title,facts=keys,effect_ids=ids,classes=cs,labels=labels,setup=title+' by actual native event/block/structure delivery; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('break','Native player locked-structure BreakEvent',['area_gate','landmark_lookup','block_actions'],[action],[P],['ENVIRONMENT'],['allowtag','eventcanceled','loadedcenter']),
      ('rightclick','Native protected RightClickBlock cancellation',['block_actions'],[action],[P],['ACTIVE_ITEM','ENVIRONMENT'],['nonBlockItem','emptyhand','inventorysync']),
      ('multiplace','Native multi-place snapshots',['block_actions'],[action],[P],['ACTIVE_ITEM','ENVIRONMENT'],['firstprotected','allowtag','nativeplacementveto']),
      ('banned_interaction','Native banned-block UseBlock gate',['block_actions'],[action],[P],['ENVIRONMENT'],['earliercancellation','bannedtag','UseBlockFALSE']),
      ('piece','Native unprotected Stronghold access and upper pieces',['piece_exceptions','landmark_lookup'],[action,incoming],[P,U+'ProgressionPiece'],['ENVIRONMENT'],['allsix','overlappedprotectedpiece','actualbounds']),
      ('exempt','Native progression player exemptions',['area_gate'],[action,incoming],[P],['ENVIRONMENT'],['FakePlayer','instabuild','spectator','gamerulefalse','advancement']),
      ('melee','Player melee against protected Enemy',['incoming_damage'],[incoming],[P],['MELEE'],['nativehurtfalse','noHP','sourcecausingplayer']),
      ('projectile','Player-owned projectile against protected Enemy',['incoming_damage'],[incoming],[P],['PROJECTILE'],['directprojectile','causingplayer','ownership']),
      ('nonplayer','Ownerless and mob-caused control sources',['incoming_damage'],[incoming],[P],['ENVIRONMENT','MOB_ATTACK'],['notcancelledbythisgate','othernativeadmission']),
      ('victim','Kobold and non-Enemy victim controls',['incoming_damage'],[incoming],[P],['MELEE'],['Kobold','Player','passivevictim']),
      ('feedback','Native structure feedback packets',['feedback'],[action,incoming],[P],['OTHER'],['100tick','inflationdisplayonly','absentstartnoclear']),
      ('hint_action','Native hint attempt from denied action/attack',['area_gate','hint_sources','hint_delivery'],[hint],[P,S,H],['ENVIRONMENT','SUMMONED_ATTACK'],['attemptedposition','strict1200','20attempts']),
      ('hint_biome','Native hint attempt from biome enforcement',['hint_sources','hint_delivery'],[hint],['util/Enforcement',S,H],['ENVIRONMENT','SUMMONED_ATTACK'],['realhintstructure','registrylookup','playerposition']),
      ('hint_spawn','Actual configured Kobold obstruction and LOS',['hint_delivery','hint_configuration'],[hint],[S,H],['SUMMONED_ATTACK'],['10resources','nofinalize','noowner','existingKoboldcombat']),
      ('hint_cooldown','Hint structure-object cooldown and failed add',['hint_sources','hint_delivery'],[hint],[S,H],['ENVIRONMENT'],['rewoundtime','sharedobject','allattemptsfail','addvetoreturnignored']),
      ('hint_book','Native copied hint book equipment/drop',['hint_delivery','hint_configuration'],[hint],[S,H],['OTHER'],['MAINHAND','components','dropchance1','nativedropadmission']),
      ('shield_face','Actual Stronghold Shield mining face',['stronghold_shield'],[shield],[B,'util/entities/EntityUtil'],['ACTIVE_ITEM','ENVIRONMENT'],['verticalFACING','horizontalopposite','raynotpositiontest']),
      ('shield_speed','Native stone digging speed on admitted shield side',['stronghold_shield'],[shield],[B],['ACTIVE_ITEM'],['attribute','equipment','150divisor','progressionevent']),
      ('shield_other','Shield denied face and native destruction controls',['stronghold_shield'],[shield],[B],['ENVIRONMENT'],['hardnessminus1','canEntityDestroyfalse','creativepath']),
      ('pedestal_eligible','Eligible native trophy activation',['pedestal_activation','pedestal_effect'],[pedestal,shield],[T],['ENVIRONMENT'],['progress_lich','anynearbyeligible','shieldcube','nodrops']),
      ('pedestal_ineligible','Ineligible native trophy update',['pedestal_activation','pedestal_reward'],[pedestal],[T],['ENVIRONMENT'],['warn','noactivation','criterionbank','statrepeat']),
      ('pedestal_bypass','Native creative or gamerule-off eligibility',['pedestal_activation'],[pedestal],[T],['ENVIRONMENT'],['instabuild','gameruleoff','noplayersneededoff']),
      ('pedestal_advancement','Native two-criterion pedestal progression',['pedestal_reward'],[pedestal],[T,'advancements/SimpleAdvancementTrigger'],['OTHER'],['trophycriterion','kill_lichcriterion','nodeeperunlockwithoutboth']),
      ('pedestal_state','Native pedestal active/water/comparator state',['pedestal_effect','pedestal_activation'],[pedestal],[T],['ENVIRONMENT'],['piston','destroyProgress','persistentactive','trophyremoved','comparator']),
      ('structure_delivery','Actual Stronghold and Castle structure producers',['shield_producers'],[shield,pedestal,force],['world/components/structures/stronghold/StrongholdAccessChamberComponent'],['ENVIRONMENT'],['actualworldgen','defaultstate','unprotectedaccess']),
      ('force_collision','Five native Force Field collision shapes',['force_field','force_connections'],[force],[F],['ENVIRONMENT'],['centralcube','arms','cornerplanes','noHP']),
      ('force_placement','Force Field placement connection rules',['force_connections'],[force],[F],['ACTIVE_ITEM','ENVIRONMENT'],['samecolor','threeconnectioncap','secondaryuse']),
      ('force_update','Force Field stale connections and native water/state persistence',['force_connections'],[force],[F],['ENVIRONMENT'],['nobitclear','differentcolorcorner','waterplacementfalse','rotation','mirror'])
    ]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-structure-gates-caller-scan.json','twilightforest-structure-gates-source-providers.json','semantic-sections/twilightforest-ominous-progression.json']
    data['exclusions']=['Lich entity shields and actual HP damage are protected separately; Stronghold Shield and Force Field here are terrain.','Biome consumers/first-entry advancement behavior and Kobold attacks reused unchanged; no duplicate mechanic.','Display packets, hint-book prose and comparator values are not damage or larger protection bounds.','Portal creation/transport, vanishing blocks/Castle Doors and remaining callback/ASM/compatibility closure remain ordinary unfinished work, not REVIEW_REQUIRED.']
    data['fixture_groups']=['Native mining/right-click/multi-place and actual player-caused Enemy damage versus exemptions/pieces/Kobold/sourceowner controls.','Real hint attempts through both callers, strict/shared cooldown, obstruction/LOS, add veto and native copied book drop.','Stronghold Shield directional mining with real tools/attributes/events and pedestal removal as distinct terrain mechanism.','Pedestal eligible/ineligible/creative/gamerule controls, criterion credit versus full advancement and persistent active terrain state.','Five Force Field colors with genuine placement/update/water/corner/collision controls.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-structure-gates.json',data);assemble('twilightforest-structure-gates.json')
if __name__=='__main__':build()
