"""Reviewed Travellers storage/view and Emperor cloth semantics."""
from catalog_common import *
from collect_twilight_travellers_utility import FULL,BATCH,T
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed Twilight4.8.3345, its registered nested ASM, raw Minecraft1.21.1 and exact NeoForge21.1.244. Static research only, runtime0; no production/Stage/Phase6/7/L2/boss tests or fixes. Completes Travellers storage/view/cloth and declared Travellers item/event/logic/modifier contracts using protected R2f8o/p activation/recipes/physics. Other utilities, food, passive entities, hazards, ten DamageTypes and remaining ASM/compatibility remain unfinished. No new DamageType or direct HP/SHP payload in these five packages.',
      'belt':'Native Belt properties supply SWAP_HOTBAR_ABILITY, CONTAINER built from nine EMPTY slots, and HAS_BELT; native ItemContainerContents.fromItems trims trailing empty slots and returns EMPTY when all empty, so logical belt capacity9 differs from current serialized getSlots. Genuine Wings+Belt shapeless modifier recipe transfers CONTAINER via protected TransferableComponentModifier and adds SWAP_HOTBAR_MODIFIER marker; copied Wings state persists. Real swap reads player.inventory.getArmor(LEGS.index), requires either swap modifier/ability PRESENT plus CONTAINER, then processes hotbar0..8. Missing stored indices use EMPTY. For each slot, current inventoryStack must canFitInsideContainerItems && !TRAVELLERS_BELT_BLACKLISTED && (active swap OR inventoryStack.isEmpty). Eligible slot stores that current stack and replaces inventory slot with stored stack; ineligible slot keeps stored stack. Rebuild CONTAINER from resulting nine slots; getStackInSlot returns a copy and fromItems copies stacks. Other inventory/offhand slots and selected index are not explicitly swapped. No HP, attack reset, cooldown, item-use action or source creation in helper.',
      'belt_inactive':'hasSwapHotbar tests registry/marker presence, independently from isModifierActive. Broken or spectator-inactive gear can retrieve stored items into EMPTY hotbar slots (subject to empty-stack canFit/tag checks) while nonempty hotbar inputs cannot be deposited/swapped. Stored belt item itself is not rechecked against blacklist/canFit on retrieval; those predicates are on the hotbar input. Client hotbar key consumeClick uses presence+CONTAINER, sends empty SwapHotbarPacket; server handler uses ctx.player and current native helper, then ServerPlayer.broadcastToPlayer(self). No UUID target argument or client inventory prediction. Helper has no rate limit/cooldown. Changed sound uses ItemStack.equals, not isSameItemSameComponents; no gameplay gain inferred from that sound. Actual belt class stack overload canFitInsideContainerItems returns !has(CONTAINER), while noarg returnsfalse; native stack extension calls the stack-aware item hook. Gear with stored container is therefore excluded from native nested-container insertion where that hook is respected. No packaged belt blacklist file exists; tag remains extensible.',
      'display_storage':'ITEM_DISPLAY is a persistent/network component containing six logical positions: MAP,MAP,MAP,COMPASS,CLOCK,MOON_DIAL. Valid MAP means instanceof MapItem; others exact COMPASS/CLOCK/TF MOON_DIAL. Native mutable copy deep-copies stacks into six slots. Genuine Goggles secondary-click handlers require count1 and ITEM_DISPLAY component; on-slot variant also requires slot.allowModification(player). They do not require active/worn/not-broken gear for storage editing. Input must canFitInsideContainerItems; find first matching EMPTY slot, otherwise first matching slot; matching occupied item+components rejects. Split exactly1 into chosen slot. If empty target, set source remainder; if occupied, replace source with displaced item and giveOrDrop input remainder. No transaction rollback if SlotAccess.set returnsfalse; native slot/cursor admission remains. Removal takes first nonempty item accepted by destination slot.mayPlace (or any for cursor); destination uses safeInsert. Sounds are cosmetic. Grindstone return/removal and overflow are protected R2f8o, not another package.',
      'display_state':'Chosen map starts0. Inserting into an empty map slot resets selection only when no other map exists. cycleChosenMapSlot scans forward from chosen+1 for next nonempty MAP position, then sets -1; next cycle from -1 starts0, so the sequence includes a disabled gap rather than immediate wrap. Removing selected map cycles before clearing it. CycleMapSlotPacket acts only ServerPlayer, actual HEAD component with active ITEM_DISPLAY, and contents !isEmpty; if selection changed writes new component, marks inventory changed and plays selected/empty sound. isEmpty means items-list length0, not all entries EMPTY; default six-slot EMPTY returnsfalse, but payload code checks actual stack emptiness. Persistent codec stores only nonempty indexed slots plus chosen_map_slot; fromSlots rebuilds maxIndex+1, or returns shared six-slot EMPTY with chosen0 when no saved slots, so an all-empty chosen-1 resets0 on load. Network codec copies whole items list+index. Native recipes produce valid layouts; codecs do not independently enforce all six-slot/index invariants.',
      'display_map':'TravellersGogglesItem.inventoryTick runs map payload only slotId==36+HEAD.index (39 for native Player Inventory), server side and active current HEAD ITEM_DISPLAY. Nonnull contents, chosen index!=-1, nonempty chosen MapItem: invoke its real virtual inventoryTick(map,level,entity,slot,true), then if ServerPlayer send that MapItem.getUpdatePacket when nonnull. Native MapItem resolves actual saved data, calls tickCarriedBy, updates terrain only when !locked and selected/offhand; the passed true satisfies selected path but does not bypass saved-data/locked/map rules. Other stored items do not get a general inventoryTick loop, consumption, effect application or combat proc. Magic/Maze map subclass bodies remain later map-utility scope; invoking real polymorphic tick is not evidence that their entire mechanics are closed.',
      'display_map_asm':'Installed UpdateMapsInGogglesTransformer targets MapItemSavedData.tickCarriedBy(Player,ItemStack), after EVERY Inventory.contains(Predicate) call. Hook preservestrue; otherwise original method Player argument current HEAD must have active ITEM_DISPLAY, contents, chosen>=0, nonempty chosen map and ItemStack.isSameItemSameComponents(argumentMap,chosenMap). No upper-index bounds check is added by hook. Transformer loads locals2(mapStack) and1(original method player) at BOTH native contains sites. The second native site is a carriedBy entry player inventory check, but false fallback still checks ORIGINAL method player goggles, not that entry player. Thus an eligible original caller can keep other preexisting, not-removed tracked players through that membership branch; native same-dimension/trackingPosition/framed rules still control decoration. This is a source-proven identity boundary, not a fabricated map or runtime verification.',
      'display_hud':'HUD renderer requires Player, no debug overlay, !hideGui, active HEAD modifier and component. It checks each stored type validity, displays only chosen map plus compass/clock/moon. Map reads actual saved map data/id and renders it; does not reveal arbitrary entities or write HP. Compass shows tracked lodestone coordinates/Manhattan distance only with present target in same dimension, otherwise player coordinates. Clock uses natural dimension and fixedTime-or-dayTime with +6000 modulo24000 converted to display time; nonnatural unknown. MoonDial uses native moon phase/natural dimension, nonnatural unknown (April1 text alternate). These are informational utilities, no time/phase change or status buff. Config changes overlay placement/scale/format only. Standalone MoonDial tooltip has same read-only phase behavior.',
      'zoom':'Builtin Goggles component zoom=.3. Client ComputeFovModifierEvent: keyDown AND !player.isScoping, current HEAD active ZOOM_ABILITY and nonnull value ->multiply event current newFov by.3. On state change store IS_USING_GOGGLES_ZOOM_MODIFIER, sound and send GogglesZoomPacket(bool,UUID). Server bidirectional handler resolves UUID in sender level, requires target player exists and target current active ZOOM_ABILITY before changing state/sound/relay; no senderUUID equality check. Client handler sets flag directly. FOV eligibility is recomputed from actual local input/equipment, not solely received flag. No server accuracy/reach/projectile change. Flag serializes/syncs defaultfalse, no copyOnDeath; item armor texture uses flag for lowered-goggles visual even without another active check. Failed server change (including inactive target) does not forcibly clear stored flag in this packet handler.',
      'zoom_mouse':'CalculatePlayerTurnEvent adjustment requires !cinematicCamera, local Player, HEAD zoom component nonnull and zoom key held&&!isScoping. It DOES NOT check isModifierActive, spectator or broken state. SetSensitivity=(.5-1/(6*s))*s/(zoom+.05) with actual float addition for zoom+.05. No guard/clamp in TF or native event setter for s0/zero denominator/nonfinite values. With s0 Java floating division/multiply yields NaN; retain exact unsimplified formula. Native MouseHandler then computes (newSensitivity*.6F+.2F)^3 and ordinary turn scaling. Therefore broken gear can still change mouse sensitivity while FOV zoom is denied. This is native input behavior, no aim-assist/attack multiplier or patch.',
      'red_thread':'Native RedThreadRenderer selects glow when Player holding RED_THREAD item in either hand OR (TRAVELLERS_GOGGLES_RED_THREAD_VISION state && active HEAD modifier). Glow uses depth-test ALWAYS(519) and fullbright15728880 for actual block faces; ordinary view uses cutout/light. Existing native block-entity distance/frustum/loading rules remain: this is marked-thread visibility, not global entity/ore revelation or a server target change. Client key toggle only with active modifier flips local attachment; no custom packet in that handler. Attachment defaulttrue serialized, and the sole explicit Travellers death-copy entry is RED_THREAD_VISION when old holder has data. No native sync declaration for that attachment; do not infer a client-toggle packet persistence guarantee. RedThread block itself is ordinary multiface placement/replacement and block entity, with no combat damage/status tick.',
      'cloth_acquire':'EmperorsClothRecipe requires exactly one cloth ingredient slot and one other nonempty tag-applicable item, no crafting remainder and no existing cloth component; width*height>=2. Assembly copies item and sets persistent/network UNIT EMPERORS_CLOTH. Packaged applicable tag #c:armors plus ELYTRA. Packaged no_template_smithing alternative requires empty template, tag base, cloth addition and none of added component types already present; copies base and applies component. Native recipe/menu consumption remains. These source routes preserve original item attributes/enchantments/durability, not a replacement armor item. Existing cloth removal uses uncanceled RightClickBlock on WATER_CAULDRON level>0, lowers fill1, removes marker, awards CLEAN_ARMOR and cancels SUCCESS; no explicit server-only/creative-refund branch, no cloth item returned.',
      'cloth_visibility':'ArmorVisibilityRenderingTransformer targets LivingEntity.getVisibilityPercent(Entity) before FIRST FSTORE local4, after native getArmorCoverPercentage in INVISIBLE branch. Exact installed target/slot is pinned. ArmorHooks subtracts ArmorUtil shrouded fraction: count nonempty armor slots with component / count ALL iterated armor slots (including empty); native coverage is nonempty/all. Result is unshrouded nonempty/all. Native clamp minimum.1 then multiplier .7*coverage, with earlier discrete factor.8, native matching skull factor.5 and CommonHooks.getEntityVisibilityMultiplier afterward. Four normal player armor slots all shrouded ->invisible visibility .07 (or .056 discrete) before other factors/hooks. If not invisible, this injected branch is not reached: cloth itself does not grant Invisibility. No active/broken/spectator check in cloth count. Native TargetingConditions only applies visibility when testInvisible and range>0; effective range=max(range*visibility,2), then native line-of-sight/attack/allied/selector rules. No universal aggro reset, guaranteed untargetability or damage immunity.',
      'cloth_render':'CancelArmorRenderingTransformer targets exact NeoForge extended HumanoidArmorLayer.renderArmorPiece(...FFFFFF) after first INSTANCEOF, loading local13 ItemStack. Hook turns true ArmorItem predicate false when component present, skipping native humanoid armor/trim/glint draw. First-person TF gloves independently skip their overlay when cloth present. FixCapeUnrenderingTransformer targets CapeLayer.render after first ItemStack.is(Item) ELYTRA check, using local12 stack; component makes checkfalse so ordinary cape may render if other native visibility/skin/model gates pass. No installed TF cloth hook changes ElytraLayer.shouldRender: exact native method still accepts ELYTRA, so cloth on Elytra does NOT prove wing model hidden by the humanoid hook. Render hooks do not remove item attributes/enchantments, native armor/protection, durability or flight; no damage event/source mutation.',
      'persistence_sources':'Storage/cloth/zoom components carry native item persistent/network codecs; normal copies, recipe transfer and death inventory rules remain. Native display remainder helper uses inventory.add then targeted no-pickup-delay dropped remainder if needed; no item duplication is assumed from cosmetic fake pickup branch. All paths use real armor inventory/callbacks, not Curios scans; general external equipment hooks remain conditional. Installed admin /twilightforest travellers_gear add/remove uses permission2, real non-Fake Player main-hand TravellersModifiable, disallows ability modification; add additionally enforces slot cap, absent modifier and matching equipment group. Remove calls native modifier removal without grindstone item-return helper, so stored payload removal differs. Record admin provenance separately; ordinary future fixtures should use genuine crafting/equipment. No command executed. Recipe-view adapters/tooltips/models are discovery/presentation, not independent combat payloads. Source-specific external compatibility NONE_PROVEN here; generic native/loader hooks are present, no pack-wide absence certification.'
    }
    A=T+'TravellersArmorBeltItem';G=T+'TravellersGogglesItem';S='components/item/ItemDisplayContents';M=S+'$Mutable';C='client/event/TravellersClientEvents';E='events/TravellersGearEvents';D='init/custom/TravellersModifiersManager';H='asmhooks/ArmorHooks';U='util/ArmorUtil';R='client/renderer/block/RedThreadRenderer'
    nxt='Review remaining utility/map/food/flask and passive-entity contracts, then environmental hazards and ten unfinished custom DamageTypes; complete remaining installed ASM/compatibility/source exclusions, protect R2f8 and promote full Twilight COMPLETE. IceAndFire begins only after COMPLETE pushed/live verified. No runtime boss/L2/Stage/production/Phase6/7.'
    data=dict(slug='travellers-utility',checkpoint_short='r2f8q',checkpoint='R2f8q-travellers-utility-complete',decision='TWILIGHT_TRAVELLERS_UTILITY_SEMANTIC_REVIEW_COMPLETE',starting_sha='0ed32df8aa5e3dad148f742d25492f90fab4323a',previous_checkpoint='R2f8p-travellers-movement-complete',previous_draft='partial-drafts/twilightforest-r2f8p-partial.json',facts=facts,packages=[],paths=[],new_damage_types=0,full_classes=FULL,limited_classes={'asmhooks/MapHooks':['goggles membership only; landmark locator remains unfinished'],'events/MiscEvents':['setup/washOffCloth'],'util/TFItemStackUtils':['giveOrDrop'],'client/event/ClientGameEvents':['cloth tooltip'],'command/TFCommand':['Travellers command registration']},registration_classes=['init/TFItems','init/TFRecipes','init/TFDataComponents','init/TFDataAttachments','events/RegistrationEvents','client/event/ClientRegistrationEvents','init/custom/ItemDisplays','init/TFKeyBinds','command/TFCommand'],closure_checklist=['actual_belt_transfer_and_nine_slot_swap','inactive_empty_slot_retrieval','container_nesting_native_hooks','display_insert_remove_replace','display_cycle_and_codec_lifecycle','real_virtual_map_tick','map_ASM_original_player_identity','HUD_read_only_payloads','zoom_FOV_packet_admission','mouse_sensitivity_independent_gate','red_thread_depth_state_and_persistence','cloth_crafting_smithing_washing','invisibility_branch_armor_fraction','native_targeting_and_minimum_range','exact_humanoid_cape_render_targets','elytra_render_exclusion','administrative_source_boundaries'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus Travellers belt/display/zoom/red-thread and Emperor cloth. Travellers item/modifier/event/logic/packet scope closed; remaining other utilities/hazards/ASM/source closure unfinished. Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=30,new_used_profiles=0,reviewed_profiles_after=30,remaining_profiles=10,remaining_disposition='Unfinished other actual callers, not declared unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,controls):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=controls));return eid
    belt=pkg('travellers_hotbar_storage','Travellers nine-slot hotbar storage exchange','CUSTOM_RESOURCE',['belt','belt_inactive','persistence_sources'],[A,C,'network/SwapHotbarPacket',E],{'logical_slots':9},['current leg armor','modifier presence','container','input canFit/tag','active ORemptyinput'],'Custom item resource exchange through native inventory.','Genuine Belt or Wings+Belt recipe, equipped hotbar key',['broken/spectator empty retrieval, blacklist, nesting, transfer and grindstone'])
    display=pkg('travellers_item_display','Travellers stored display and actual map ticking','CUSTOM_RESOURCE',['display_storage','display_state','display_map','display_map_asm','display_hud','persistence_sources'],[G,S,M,'asmhooks/MapHooks','network/CycleMapSlotPacket','client/overlay/ItemDisplayOverlay'],{'logical_slots':6,'map_slots':3,'insert_count':1,'native_head_inventory_index':39},['component storage','activeheadforuse','actualmapsaveddata','nativeinput/slot'],'Custom container and native map delivery with read-only HUD.','Genuine Item Display goggles, stored maps and native cycle key',['insert/replace/remove, empty codec, broken, lockedmap, membership identity'])
    zoom=pkg('travellers_goggles_zoom','Travellers zoom and mouse input state','CUSTOM_CONTROL',['zoom','zoom_mouse','persistence_sources'],[C,'network/GogglesZoomPacket',T+'TravellersArmorItem'],{'FOV_multiplier':.3,'sensitivity_offset':.05},['key &&!scoping','active forFOV','componentonly formouse','nativeevent'],'Custom view/input control, not attack accuracy or damage.','Native held zoom key with Goggles',['broken mouse vsFOV, cinematic, s0, packet target and removal'])
    thread=pkg('travellers_red_thread_vision','Travellers marked-thread visibility','BINARY_MECHANIC',['red_thread','persistence_sources'],[R,C,E,'block/RedThreadBlock','block/entity/RedThreadBlockEntity'],{'depth_test':519,'glow_light':15728880,'default_toggle':True},['holdingthread ORactivegoggles&&toggle','nativeblockrendereligibility'],'Binary depth/lighting display of actual marked blocks.','Genuine red-thread block and held thread/modified goggles',['keytoggle, broken, native distance/culling, deathcopy/clientstate'])
    cloth=pkg('emperors_cloth_visibility','Emperor cloth native armor visibility','CUSTOM_CONTROL',['cloth_acquire','cloth_visibility','cloth_render','persistence_sources'],['item/recipe/EmperorsClothRecipe','item/recipe/NoTemplateSmithingRecipe',H,U,'events/MiscEvents',C],{'native_coverage_floor':.1,'invisible_multiplier':.7,'discrete_multiplier':.8,'minimum_targeting_range':2},['actualcomponent','invisible branch fordetection','nativearmor slots','exactrenderhooks'],'Custom clothing component alters native visibility and rendering, preserving defense.','Native craft/smith cloth armor, then genuine Invisibility and target checks',['visible control, partial/full cloth, washed, broken armor, Elytra/cape'])
    data['damage_profiles']=[]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:travellers_utility_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' via genuine installed recipe/equipment/UI/native callback; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('belt_base','Native Belt hotbar exchange',['belt'],[belt],[A,'network/SwapHotbarPacket'],['ARMOR_PROC','ACTIVE_ITEM'],['nine logicalslots','nativecurrentlegs','selected/offhandunchanged','no cooldown']),
      ('belt_transfer','Native Wings plus filled Belt recipe',['belt','persistence_sources'],[belt],[A,T+'modifiers/TransferableComponentModifier'],['OTHER'],['actualpayloadtransfer','nativecopy','slotcapprotected','no duplicatedstore']),
      ('belt_inactive','Native broken/inactive stored retrieval',['belt_inactive'],[belt],[A,C],['ARMOR_PROC'],['presence vsactive','empty input only','stored item not rechecked']),
      ('belt_filters','Native hotbar input/container controls',['belt','belt_inactive'],[belt],[A],['ARMOR_PROC','OTHER'],['blacklist','canFitstackhook','nonempty inactive','trailingemptytrim']),
      ('belt_save','Native Belt save and modifier removal',['belt','persistence_sources'],[belt],[A,E],['OTHER'],['nativecomponentcopy','grindstoneoverflow','noCurioinventory']),
      ('display_insert','Native goggles secondary-click insertion',['display_storage'],[display],[G,M],['OTHER'],['count1','componentpresence','firstmatchingslot','split1']),
      ('display_replace','Native display replacement and remainder',['display_storage','persistence_sources'],[display],[G,M,'util/TFItemStackUtils'],['OTHER'],['samecomponentreject','displacedstack','giveOrDrop','no rollbackifsetfalse']),
      ('display_remove','Native display removal and grindstone return',['display_storage','display_state'],[display],[G,M,E],['OTHER'],['slotmayPlace','safeInsert','chosenmapcycles','ordinaryprotectedreturn']),
      ('display_cycle','Native selected-map cycle packet',['display_state'],[display],[M,'network/CycleMapSlotPacket'],['ARMOR_PROC','OTHER'],['ServerPlayer','currentactivehead','forwardthen-1','nextwrap']),
      ('display_codec','Native Item Display save/load',['display_state'],[display],[S,M],['OTHER'],['sparse slots','all-empty resetchosen0','networkwholelist','listlengthisEmpty']),
      ('display_tick','Native equipped Goggles active map tick',['display_map'],[display],[G],['ARMOR_PROC','PASSIVE_ITEM'],['slot39','serveronly','realMapItemvirtualtick','selectedtrue','lockednativecontrol']),
      ('display_membership','Native map-carrier ASM membership',['display_map_asm'],[display],['asmhooks/MapHooks'],['ARMOR_PROC','PASSIVE_ITEM'],['both containscalls','originalplayerlocal1','actualsamemapcomponents','preexistingotherholdercontrol']),
      ('display_hud','Native HUD map/compass/clock/moon reading',['display_hud'],[display],['client/overlay/ItemDisplayOverlay','init/custom/ItemDisplays','client/overlay/display/MapDisplay','client/overlay/display/CompassDisplay','client/overlay/display/ClockDisplay','client/overlay/display/MoonDialDisplay','item/MoonDialItem'],['PASSIVE_ITEM','ARMOR_PROC'],['noGUI/debug','selectedmaponly','same-dimensionlodestone','natural/fixedtime']),
      ('display_negative','Native display inactive/other stored item controls',['display_map','display_hud'],[display],[G,'client/overlay/ItemDisplayOverlay'],['ARMOR_PROC'],['broken disablesuse notediting','nonchosenmap','otheritemsnotgeneralticked','nogeneralbuff']),
      ('zoom_fov','Native goggles zoom FOV event',['zoom'],[zoom],[C],['ARMOR_PROC'],['.3 currentnewFOV','keynotspyglass','activecurrenthead','noattackeffect']),
      ('zoom_packet','Native goggles zoom state synchronization',['zoom'],[zoom],['network/GogglesZoomPacket',T+'TravellersArmorItem'],['ARMOR_PROC','OTHER'],['UUIDlookup','targetactive','noUUIDequality','flagtextureonly']),
      ('zoom_mouse','Native mouse sensitivity event',['zoom_mouse'],[zoom],[C],['ARMOR_PROC','OTHER'],['exactunsimplifiedformula','noactivecheck','s0NaN','cinematicskip']),
      ('zoom_inactive','Native broken zoom and state controls',['zoom','zoom_mouse'],[zoom],[C,'network/GogglesZoomPacket'],['ARMOR_PROC'],['FOVdeniedmousechanged','removecomponent','nativecalculation','staleserverflag']),
      ('thread_held','Native held red thread glow',['red_thread'],[thread],[R],['ACTIVE_ITEM','ENVIRONMENT'],['eitherhand','ALWAYSdepth','realblockfaces','nativeculling']),
      ('thread_goggles','Native modified goggles thread glow',['red_thread'],[thread],[R,C],['ARMOR_PROC','ENVIRONMENT'],['activemodifier&&toggle','defaulttrue','localtoggleonly']),
      ('thread_state','Native red-thread toggle save/death controls',['red_thread'],[thread],[E,C,'init/TFDataAttachments'],['OTHER'],['soleexplicitdeathcopy','noautonativesync','holdingbypassesgogglestoggle']),
      ('cloth_craft','Native cloth crafting recipe',['cloth_acquire'],[cloth],['item/recipe/EmperorsClothRecipe'],['OTHER'],['tagapplicable','noexistingmarker','noremainder','copyitem']),
      ('cloth_smith','Native no-template cloth smithing',['cloth_acquire'],[cloth],['item/recipe/NoTemplateSmithingRecipe'],['OTHER'],['emptytemplate','base/additionmatch','componentabsent','normalconsumption']),
      ('cloth_wash','Native water-cauldron cloth removal',['cloth_acquire'],[cloth],['events/MiscEvents'],['ACTIVE_ITEM','ENVIRONMENT'],['uncanceledevent','waterlevel>0','fill-1','markerremove','noclothrefund']),
      ('cloth_detection','Native invisible shrouded armor visibility',['cloth_visibility'],[cloth],[H,U],['ARMOR_PROC','MOB_ATTACK'],['invisibleonly','unshrouded/allslots','nativefloor.1','hookafterward']),
      ('cloth_targeting','Native range/line-of-sight and visible controls',['cloth_visibility'],[cloth],[H,U],['ARMOR_PROC','MOB_ATTACK'],['visibleunchanged','range/testInvisible','minrange2','noaggroreset']),
      ('cloth_render','Native humanoid armor and glove rendering',['cloth_render'],[cloth],[H,C],['ARMOR_PROC','OTHER'],['exactlocal13','armortrim/glintskip','glovecomponentgate','defenseunchanged']),
      ('cloth_elytra','Native cloth Elytra and cape controls',['cloth_render'],[cloth],[H],['ARMOR_PROC','OTHER'],['capelocal12','othercapegates','Elytralayerstillrenders','flightunchanged']),
      ('admin_source','Native administrative modifier source boundary',['persistence_sources'],[belt,display],['command/TravellersGearCommand','command/TFCommand'],['OTHER'],['permission2','realplayer mainhand','addslot/groupgates','remove no itemreturn','notruntimefixtureexecuted'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-evidence/'+BATCH+'-asm.json','reference-routing/'+BATCH+'.json','twilightforest-travellers-utility-caller-scan.json','config-evidence/twilightforest-client.json','reference-evidence/twilight-equipment-asm.json','reference-evidence/twilight-travellers-core-244.json','reference-evidence/twilight-travellers-movement-244.json','reference-evidence/twilight-scepter-payloads-244.json','reference-evidence/cult-loader-244.json','reference-evidence/vv-loader-244.json']
    data['exclusions']=['All listed Travellers storage/view classes, both complete Travellers event classes, relevant command source, display renderers and four nested armor/map transformers are pinned. Other preexisting core/movement semantics reused.','HUD/tooltip/MoonDial/wing/goggle texture outputs are informational/cosmetic; no new effects or DamageTypes inferred from names. RedThread affects actual marked-block depth rendering only.','Cloth does not apply Invisibility, erase attributes or force Elytra wings invisible. Native targeting and generic visibility hooks remain.','Map goggles call actual subclass methods; complete Magic/Maze map utilities and landmark-map ASM remain unfinished. Remaining other items/food/passive entities/hazards and ten custom sources are still unfinished.','Administrative add/remove and recipe-view adapters are separate source provenance, not fabricated survival fixtures. No commands or runtime tests performed.']
    data['fixture_groups']=['Genuine Belt/transfer recipe and all nine hotbar inputs, native save/overflow/nesting and broken-state retrieval.','Native display insertion/replacement/removal/cycle plus real selected map tick and both carrier membership call sites.','Local input/equipment FOV/mouse and legitimate packet state with nonfinite/broken/spyglass/cinematic controls.','Real red thread held/equipped visibility, native render limits and actual attachment lifetime.','Native cloth crafting/smithing/wash; genuine Invisibility vsvisible target admission, real armor and Elytra/cape render controls without defense changes.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-travellers-utility.json',data);assemble('twilightforest-travellers-utility.json')

if __name__=='__main__':build()
