"""Explicit installed-code findings for the R2f8a ranged-mob subsection."""
from catalog_common import *
from collect_twilight_ranged_mobs import FULL,BATCH
from twilight_subsection import assemble


def build():
    facts={
      'shared_pipeline':'Protected Minecraft1.21.1/exact NeoForge21.1.244 Living/Player hurt, native effects, ranged-goal, projectile/impact/parry, explosion and BaseIceMob evidence is reused. Source identity/tags/difficulty, armor/shield, Resistance/protection, absorption/cooldown/events and effect eligibility remain native. True hurt is not actual HP loss. Native mob-owned when_caused_by_living_non_player scales Player requests Peaceful0/Easy min(a/2+1,a)/Normal a/Hard1.5a. Status addEffect(effect) calls here provide no explicit attacker; ordinary merge/immunity/cures/events apply. No runtime HP/SHP or L2/Stage claim.',
      'breath_goal':'BreathAttackGoal is shared by FireBeetle and WinterWolf: MOVE/LOOK/JUMP, range5/duration30/chance.1. canUse selects getLastHurtByMob, NOT getTarget; requires range<=5, sensingLOS, alive Living and noncreative/nonspectator before random chance. Saves target eye-position once. start duration30/breathingtrue; continue requires duration>0, host/targetalive, current range/LOS and eligibility. tick decrements, look/face toward SAVED position (100 degree limits); after elapsed>5 calls getHeadLookTarget and attacks one selected winner. Default goal cadence, not30 guaranteed game ticks. Selection ray is30 long from hostY+.25, but candidate box is hostBB moved view*3 and inflated.5, not a swept30-block volume. Live Living/pickable/nonself/noncreative/nonspectator only; own parts removed. Nearest intersection selected before one attack, no block clip; target can be different from retaliation target. Contains-origin sets distance0 sentinel, so subsequent intersection may replace it. Continuation LOS to retaliation target is not a separate ray-winner LOS check. stop duration0/targetnull/breathfalse; state/timers unsaved.',
      'fire_beetle':'FireBeetle HP25/speed.23/attack4, registered1.1x.5 FIREPROOF; arthropod and freeze_hurts_extra_types. Float0/Breath2/Melee3/stroll; retaliation/nearest visible Player. Native breath winner first !target.fireImmune, then scorched2 direct=causing=FireBeetle, true=>ignite10 seconds. Fire Resistance/native fire admission may reject before success; later burning is ownerless on_fire, separate. doHurtTarget while breathing instead requests scorched2, no explicit fireImmune precheck, no ignite and no normal melee helper enchantment/knockback callbacks; otherwise superclass ordinary mob_attack effectiveattack4. Normal AI breath occupies melee flags; callback branch still records the native method, not a guarantee both goals execute together. scorched fire/ignites_armor_stands, no armor/shield bypass/projectile/explosion tag; normal mitigation. Breath particles/gameevents/sounds are not projectiles or extra hits.',
      'wolf_baseline':'HostileWolf is Monster, not tameable Wolf. HP20/speed.3/attack2; Float, native LeapAtTarget(.4), ordinary melee, wander/look; retaliation ignores HostileWolf damage for that goal, nearest Player, wolf-prey Animal, baby-on-land Turtle and AbstractSkeleton targets. Leap wrapper only toggles aggressive animation on start/stop; native leap requires no controlling passenger, target distanceSquared4..16, onGround/random reducedTickDelay5; sets motion toward target with existing momentum, no independent damage. Variant is saved appearance, not combat resource. Mist/Winter override HP30/attack6, dimensions1.4x1.9, notfireproof. All ordinary source admission/death remain; no added HP phase/regeneration/defense override. Winter replaces goal/target list with Float/Breath/Melee/stroll and retaliation/Player, so no inherited leap/prey selector in its actual registerGoals.',
      'winter_breath':'WinterWolf shares the reviewed retaliation breath goal but doBreathAttack requests minecraft:mob_attack2 direct=causing=WinterWolf, ignores hurt bool, no ignite/freeze/Frosted/Slowness/projectile. Native melee remains effectiveattack6. Freeze immune entity tag is recipient defense, not outgoing elemental damage. Winter canSpawnHere expression is (nonPeaceful && exactSnowyForestBiome) OR Monster.isDarkEnoughToSpawn; no parentheses importing the nonPeaceful predicate into the second branch and no base checkMobSpawnRules in that method. Native spawn engine and later Monster Peaceful despawn still apply. Breathing flag unsaved; visual snow is not damage evidence.',
      'mist_blindness':'MistWolf only modifies successful superclass melee: inspect integer getMaxLocalRawBrightness at WOLF position castfloat, requires<.1 (therefore level0), Living victim, and wolf current block !isSolid. Then native Blindness amplifier0: Easy0/noadd, Hard15*20, default7*20 (Normal and Peaceful branch; Player Peaceful hurt usually rejected first). Effect application is success-dependent, may be refused/merged normally; ordinary melee damage6 native mitigation remains. No darkness effect, invisibility, magical outgoing source or damage immunity. HostileWolf leap/target behavior inherited.',
      'nature_bolt':'SkeletonDruid main-hand Hoe creates native NatureBolt ownerDruid, speed.6/inaccuracy6, aim targetEyeY-2.7-shooterY plus horizontalDistance*.2; gravity.003. TFThrowable/ITFProjectile, .25 square. onHitEntity calls super, then Living only, owner==null OR victim!=owner && victim!=owner.vehicle, then leaf_brain2 direct=bolt/causing=currentowner. Only true hurt and difficulty!=Peaceful applies Poison amp0 Easy/Normal60 ticks, Hard140. No poison if failed hurt or owner/vehicle gate; native recipient immunity/effect events remain. Source is magic/projectile, bypasses ordinary armor/transitively shield/wolf armor, witch-resistant; normal Resistance/protection/projectile protection/absorption/cooldown. onHit superclass then server particle3/discard regardless hurt; block case separate. No explicit custom entity-hit server check, but native hurt rejects client. Inherited projectile owner serialization retained, no custom payload state lost on load.',
      'nature_terrain':'NatureBolt onHitBlock first superclass block callback. If canEntityGrief(projectile), server BonemealableBlock valid target calls performBonemeal directly (no isBonemealSuccess probability or bonemeal item/event consumption). Else if solid && canReplaceBlock: no blockentity, solidRender, DRUID_PROJECTILE_REPLACEABLE tag and EntityUtil.canDestroyBlock then persistent BIRCH_LEAVES setBlockAndUpdate. Else branch has no explicit server guard; native delivery/world authority remains. Owner immunity on entities does not stop terrain callback. Standard onHit server discard follows. Tag content/resources pinned; no arbitrary block replacement or duplicated Frosted/ice terrain.',
      'poison_comparison':'Raw PoisonMobEffect amp0 checks every25 duration ticks and, only currentHP>1, requests ownerless minecraft:magic1. Installed NeoForge21.1.244 replaces holder with neoforge:poison when registered (fallback minecraft:magic), still ownerless1/nativehurt/no direct subtraction. This is subsequent poison source, not leaf_brain and not projectile. Ordinary native effect application checks immunity tags/events and merges/cures; toxin does not inherit bolt owner, duration refresh does not guarantee additional immediate damage, and rejected damage still ages. Slowness in TomeBolt is native MOVEMENT_SLOWDOWN amp1 (movement modifier-.15*(amp+1)=-.30), no custom frozen buildup.',
      'druid_state':'SkeletonDruid extends AbstractSkeleton and uses its attributes (HP20, movement.25, base attack2) and ordinary sunburn/equipment protection, skeleton tags/targeting/armor/enchantment setup. registerGoals calls super then priority4 RangedAttackGoal speed1.25/60/range5. Server reassess removes this ranged goal; Hoe mainhand adds it but does NOT remove preexisting inherited melee/bow goals (unlike calling super branch). NonHoe calls inherited reassess (BowItem accepts native mod bows under exact NeoForge); native equal-priority MOVE/LOOK arbitration decides retained goal competition. performRangedAttack Hoe=>NatureBolt, STICK=>no projectile, other item=>inherited arrow. Inherited arrow factory/customArrow and equipment/enchantments remain. Adult default goldenhoe, baby stick. setBaby syncs flag, server transient speed+.5 ADD_MULTIPLIED_BASE, dimensions half/eye.93; NBT IsBaby restores modifier, no age countdown/grow-up. SwarmSpider native summonJockey called after finalizeSpawn: existing passenger OR randInt200==0, creates babyDruid before finalizeSpawn(JOCKEY), ejects prior passenger if any, startRiding(spider), no separate addFreshEntity here (caller passenger-tree insertion matters). Full SwarmSpider review remains separate. Baby control changes native equipment/AI, not custom status.',
      'tome_bolt':'DeathTome normal ranged goal speed1/100/range5; actual projectile ownerTome, speed.6/inaccuracy6, aim targetEyeY-1.1-projectileY+.2*horizontalDistance; gravity.003. TomeBolt TFThrowable/ITFProjectile .25 square. onHit special early return when ownernonnull, BlockHit same blockPos as owner and that block Lectern: skips superclass and discard; no block-owner tag magic. Otherwise superclass; Living hit randomBoolean chooses lost_words OR schooled, request3 direct=bolt/causing=currentowner. True=>SlownessII amp1 Easy40, Normal120, otherwise160 ticks; no explicit Peaceful exclusion (native Player scaling often prevents true). Both types same magic/projectile/armor+shield+wolf-bypass/witch-resistant tags and scaling, distinct identity/deathtext. Hit misses/nonLiving/false hurt still discard server after superclass. No direct projectile HP, homing, Frosted or enchantment-specific damage added. Owner/speed serialize through parent, no custom state lost.',
      'tome_lectern':'DeathTome HP20/speed.25/flying.6/attack4, root.75x1.5, notfireproof; fall immune tag and empty checkFallDamage, cannot ride. FlyingMoveControl(10,false), flying navigation prefers support below, no door open/float but passdoors. DATA_LECTERN saved on_lectern; persistence required whiletrue. Native producers: LichTowerWingRoom.putTrappableLectern(putMimic) places lectern HAS_BOOK=false, creates persistent positioned tome, setsflagtrue/finalizes STRUCTURE/addWithPassengers. MiscEvents registered RightClickBlock DeathTome SpawnEgg on empty lectern cancels ordinary interaction, server native EntityType.spawn(pos.below,SPAWN_EGG,true,false), ifnonnull consumes egg respectingPlayerabilities and setsflagtrue. On lectern aiStep aligns facing, manually server targetSelector.tick and RETURNS withoutsuper; targetnonnull releasesflag, velocity(0,.25,0), immediate ranged shot. Missing Lectern clearsflag then ordinary AI. Lectern Player target finds nearest within3, !shift, noncreative/nonspectator and view-dot>.75 plus VISUAL/FluidNONE LOS to one ofthree tomeY samples (range<=128, samelevel). Normal off-lectern target is native nearestvisiblePlayer; retaliation also exists. Hurt true with doubled-or-normal request>0 releases/lifts and rolls hurtloot; false does not release. Offlectern descending airborneY*.6 AFTERsuper; no regeneration or boss-style damage gate.',
      'tome_fire':'DeathTome hurt multiplies IS_FIRE input by2 BEFOREsuper/native incoming event/mitigation, including on_fire/lava/etc taggedfire; no damage source replacement and no special cold weakness. True and modifiedrequest>0 triggers lectern release and native hurtloot even if actual HP loss0; absent guard does not mean unconditional loot per attemptedhit. Fire Resistance/native invulnerability can reject. Loot is excluded as separate combat mechanic. Saved native HP plus on_lectern, no custom recovery resource.',
      'slime_blob':'SlimeBeetle HP25/speed.23/attack4 root.9x.5 arthropod; Float0, AvoidPlayer2 range3 speeds1.25/2, native Ranged3 speed1/30/range10, wander/look, retaliation/nearestvisiblePlayer. No melee goal despite attackattribute4. Shoots SlimeProjectile ownerBeetle speed.6/inaccuracy6, eyeY-1.1-projectileY+.2*horizontalDistance. Projectile TFThrowable/ITFProjectile .25 square, gravity.006; server Living hit requests ordinary minecraft:thrown4 direct=projectile/causingowner, return ignored, no Slowness/slime status. onHit super then die server(sound/discard/particle), including block or failed damage. hurt calls super but ignores it, then die and returns true regardlessamount/source, even if superclass false; this is projectile disposal not reflection/HP. Native isPickable remainsfalse, so do not invent normal Player melee targeting. No custom save override; parent owner/motion retained. Thrown tag/armor/directional shield/Resistance/protection/projectile protection/absorption/cooldown remain.',
      'ice_snowball':'StableIceCore extends protected BaseIceMob: defaultHP20/speed.23/attack3, .8x1.8; freeze/fallimmune, snowwalkable, notfireproof; inherited descendingY*.6/no riding/warm-biome ownerless on_fire1 per20 ticks. Float0/Ranged1 speed1.25/20/range10, roam/look, retaliation/nearestvisiblePlayer. Shoots IceSnowball ownercore at own eye, targetEyeY-1.4-snowballY+.2*horizontalDistance, speed1.6/inaccuracy6; gravity.006. Projectile TFThrowable/ITFProjectile .25 square. Server Living hit snowball_fight2 direct=projectile/causingowner, ignoresbool; no vanilla Snowball Blaze3 branch, no Frosted or freezing gauge. Source magic/projectile, NO armor/shield/wolfarmor bypass and NO IS_FREEZING even though DamageEffects.FREEZING selects hurt audiovisual. onHit super then server discard/particle; hurt ignores super result then die/true. Not normally pickable; inherited serialization retainsowner/motion. IceCrystal/BaseIceMob evidence reused rather than duplicated.',
      'unstable_death':'UnstableIceCore is separate BaseIceMob melee producer (Float0/Melee1 speed1/roam/look, retaliation/Player); defaultHP20/speed.23/attack3, same dimensions/freeze/fallimmunity/descent/warm-biome on_fire as Stable. It is NOT Stable subclass and never calls IceSnowball. tickDeath increments; only deathTime==60 server captures canEntityGrief then Level.explode(this,position,radius1,interactionMOB), nofire, and independently ifcapturedtrue transformBlocks. Afterwards deathTime=19, super.tickDeath removesat20, then assigns60. Native explosion events/LOS/exposure/armor/Resistance/blast protection/cooldown/knockback remain; source direct=causing=Livingcore, factorytype minecraft:player_explosion despite owner notPlayer, scalingALWAYS. Separate transform still executes after an explosion canceled internally because caller ignores explode return. No directHP/subtraction/heal/ice status. Native DeathTime serialization preserves delayeddeathtiming; core declares no custom save methods.',
      'unstable_terrain':'At delayed death with captured canEntityGrief true, loops dx/dy/dz=-4..4 inclusive729 candidates; each has independent radius4+(randFloat-randFloat)*2, strictEuclideandistance<radius. transformBlock requires block explosionResistance<8 and state destroySpeed>=0. First: nonair/fullblock collision shape && (!solid || LEAVES || exactICE || TF AURORA_BLOCK) =>nearest dye STAINED_GLASS. Else nonair/redstoneConductor=>nearest-dyeTERRACOTTA. Nearest dye minimizes sum absoluteRGBdiff between block MAP color and dye TEXTURE color; first minimum wins. ColorUtil native maps to correspondingblocks. No BE/container/EntityUtil destroyhook predicate, no drop, setBlockAndUpdate; leaves/glass transform separate from actualexplosion destruction. No success/hurt/exposure dependency. Exact scope/predicates preserved, no fix.',
      'projectile_common':'All four new payloads inherit ITFProjectile via TFThrowable. Native timed shield parry on server ProjectileImpactEvent: !external parry mod loaded, Living blocking within configured40 ticks, marker qualifies despite parryNonTwilightAttacks=false; AIM_DEFLECT transfers owner to blocker and cancels impact. It does not require successful normal shield hurt or front-direction check in this callback. Later source uses current owner, changes native difficulty/owner filters; no fabricated reflection source. Native impact hook/deflection may prevent onHit; ignored hurt result is downstream only. TFThrowable itself has no lifetime/discard override; no automatic custom timeout invented. These four are not in TF native REDIRECTABLE_PROJECTILE contribution; Aether deflectable tag exists for Nature/Slime/Ice, absent Tome, but consumer not asserted without installed Aether authority. Data tags are not implementation. Inherited normal projectile save/owner collision/leftOwner behavior reused; no payload class has custom NBT override.'}
    M='entity/monster/';P='entity/projectile/';G='entity/ai/goal/BreathAttackGoal'
    data=dict(slug='ranged-mobs',checkpoint_short='r2f8a',checkpoint='R2f8a-ranged-mobs-complete',decision='TWILIGHT_RANGED_MOBS_SEMANTIC_REVIEW_COMPLETE',starting_sha='cb929fb7833eb27ddc3c16126f281cc62247421a',previous_checkpoint='R2f7-alpha-yeti-snow-queen-complete',previous_draft='partial-drafts/twilightforest-r2f7-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=5,full_classes=FULL,limited_classes={'entity/monster/SwarmSpider':['finalizeSpawn','summonJockey'],'events/MiscEvents':['setup','addTomesToLecterns'],'world/components/structures/lichtowerrevamp/LichTowerWingRoom':['putTrappableLectern'],'util/ColorUtil':['getColor','<clinit>','selected color lambdas']},registration_classes=['init/TFEntities','events/RegistrationEvents','events/MiscEvents'],closure_checklist=['native_producers','retaliation_breath_goal','ray_geometry','fire_vs_winter_identity','druid_weapon_and_baby','lectern_ambush_and_release','all_four_projectile_callbacks','poison_loader_difference','status_and_hurt_dependencies','ice_core_melee_vs_projectile','delayed_explosion_vs_terrain','native_defenses','persistence','caller_scan','source_tags','classification_exclusions'],compatibility_scope='Static installed Twilight4.8.3345 / raw Minecraft1.21.1 / exact NeoForge21.1.244. Existing four conditional compat scans reused; no runtime boss/L2 tests or production/Stage changes.',current_scope='Frosted, all eight named boss reviews and remaining ranged-mob subsection complete; other Twilight content pending, PARTIAL/zero promotion.',exact_next_task='Continue Task C: remaining melee/control mobs and minibosses, then weapons/scepters/staves/armor/charms/projectiles, hazards/resources, remaining18 custom DamageType profiles, compatibility/source/delivery/exclusion closure. Reuse protected ranged mobs, all bosses and Frosted. Protect each logical subsection toward R2f8; final Twilight promotion only after full closure. No runtime boss/L2, Stage/production, fixes/balancing, Phase6 or Phase7; Ice and Fire blocked until final Twilight checkpoint.',damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=17,new_used_profiles=5,reviewed_profiles_after=22,remaining_profiles=18,remaining_disposition='Unfinished other native callers, not unused. Original40 declarations retained.'))
    def package(key,title,classification,keys,classes,parameters,gates,relation,source,alternates):
        eid='twilightforest:'+key
        data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=classification,facts=keys,classes=classes,parameters=parameters,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alternates))
        return eid
    bc=package('retaliation_breath_control','Retaliation breath targeting and timing','CUSTOM_CONTROL',['breath_goal'],[G,M+'FireBeetle',M+'WinterWolf'],{'range_admission':5,'duration_calls':30,'chance':.1,'warmup_calls':5,'ray':30,'box_move':3,'box_inflate':.5},['lastHurtByMob','currentrangeLOS','savedaim','winnerpostselection'],'Custom AI/geometry, no independent source.','Native FireBeetle or WinterWolf after a legitimate hit',['Both producers share goal; nonretaliating currenttarget negativecontrol.'])
    fb=package('fire_beetle_scorched','Fire Beetle scorching and ignition','CUSTOM_DAMAGE',['fire_beetle','shared_pipeline'],[M+'FireBeetle',G],{'breath':2,'burn_seconds':10,'ordinary_attack':4},['breath fireImmune precheck','igniteonlytrue','breathingmelee noignite'],'Custom fire source plus ordinary burn, distinct melee callback.','Native FireBeetle retaliation breath',['Ordinary melee and breathing doHurtTarget branch distinct.'])
    wb=package('winter_wolf_breath','Winter Wolf physical breath','VANILLA_LIKE_EXTENDED',['winter_breath','wolf_baseline'],[M+'WinterWolf',M+'HostileWolf',M+'HostileWolf$LeapGoal',G],{'breath':2,'melee':6},['sharedretaliationgoal','hurtboolignored'],'Ordinary mob_attack through custom ray; no coldstatus.','Native WinterWolf retaliation breath',['Native WinterWolf ordinary melee; freezeimmune recipient control.'])
    nb=package('nature_bolt_package','Nature Bolt damage, poison and terrain','CUSTOM_DAMAGE',['nature_bolt','nature_terrain','poison_comparison','projectile_common'],[P+'NatureBolt',M+'SkeletonDruid',P+'TFThrowable','events/EntityEvents','util/entities/EntityUtil'],{'request':2,'poison_easy_normal':60,'poison_hard':140,'poison_amp':0,'speed':.6,'gravity':.003},['Living/ownerandvehicle','truehurt&&!Peaceful','grief/bonemealorreplacement'],'Custom projectile source plus native Poison and worldcontrol.','Native hoe-equipped SkeletonDruid NatureBolt',['Native reflected projectile/currentowner; bonemeal and replaceable-block impacts.'])
    ds=package('druid_weapon_baby','Druid equipment goals and permanent baby state','CUSTOM_CONTROL',['druid_state'],[M+'SkeletonDruid',M+'SwarmSpider'],{'ranged_interval':60,'range':5,'baby_speed_base_mult':.5,'baby_scale':.5},['mainhandHoe/Stick/other','nativegoalcompetition','IsBabyNBT'],'Custom producer/equipment state using native skeleton melee/arrows/attributes.','Native adult Druid and SwarmSpider baby-jockey producer',['Native pickedup/equipped bow or hoe; save/load state.'])
    tb=package('tome_bolt_package','Tome Bolt alternating source and Slowness','CUSTOM_DAMAGE',['tome_bolt','poison_comparison','projectile_common'],[P+'TomeBolt',P+'TFThrowable',M+'DeathTome'],{'request':3,'slow_amp':1,'duration_easy':40,'duration_normal':120,'duration_other':160,'interval':100},['Living/truehurt','randomsourceidentity','ownlecternblockearlyreturn'],'Custom source identity plus native SlownessII.','Native DeathTome ranged bolt',['Lectern wake immediate shot, reflected bolt, savedowner.'])
    ta=package('death_tome_ambush','Lectern ambush and release control','CUSTOM_CONTROL',['tome_lectern'],[M+'DeathTome',M+'DeathTome$1',M+'DeathTome$2','events/MiscEvents','world/components/structures/lichtowerrevamp/LichTowerWingRoom'],{'player_range':3,'view_dot_threshold':.75,'release_y':.25,'descent_factor':.6},['lectern/gaze/noncrouch','manualtargettick','truepositivehurtrelease'],'Custom ambush state with native targeting/spawn/physics.','Native generated Lich-tower lectern mimic',['DeathTome spawn egg on emptylectern; removedlectern/hurtwake.'])
    tf=package('death_tome_fire_weakness','Death Tome fire vulnerability','VANILLA_LIKE_EXTENDED',['tome_fire'],[M+'DeathTome'],{'fire_multiplier':2},['IS_FIRE before super','nativeadmission','truepositiveforrelease'],'Native fire source with custom amount multiplier.','Native fire hit on DeathTome',['Native later on_fire/lava; absorption/FireResistance controls.'])
    sb=package('slime_beetle_blob','Slime Beetle throwable damage and disposal','VANILLA_LIKE_EXTENDED',['slime_blob','projectile_common'],[M+'SlimeBeetle',P+'SlimeProjectile',P+'TFThrowable'],{'request':4,'interval':30,'speed':.6,'gravity':.006},['serverLiving','hurtboolignored','onHit or projectilehurt disposal'],'Native thrown source4 with custom producer/lifecycle, no slime status.','Native SlimeBeetle shot',['Native block impact/parry/projectilehurt and save/load.'])
    ice=package('ice_core_snowball','Stable Ice Core snowball package','CUSTOM_DAMAGE',['ice_snowball','projectile_common'],[M+'StableIceCore',M+'BaseIceMob',P+'IceSnowball',P+'TFThrowable'],{'request':2,'interval':20,'speed':1.6,'gravity':.006},['serverLiving','hurtboolignored','nativeBaseIceMob'],'Custom magic/projectile2; no Frosted or actualfreezing.','Native StableIceCore shot',['Reflected/currentowner, blockimpact, projectilehurt and reload.'])
    ud=package('unstable_core_death_explosion','Unstable Ice Core delayed explosion','VANILLA_LIKE_EXTENDED',['unstable_death'],[M+'UnstableIceCore',M+'BaseIceMob'],{'death_tick':60,'radius':1,'melee':3},['deadtime60','server','nativeMOBexplosion'],'Ordinary native explosion driven by custom delayeddeath.','Native UnstableIceCore death',['Native melee/warmbiomemelt death; saved DeathTime, grief/canceledexplosion.'])
    ux=package('unstable_core_terrain','Unstable Ice Core terrain transmutation','CUSTOM_CONTROL',['unstable_terrain','unstable_death'],[M+'UnstableIceCore','util/ColorUtil'],{'cube_half':4,'candidate_positions':729,'resistance_exclusive':8,'random_radius':[2,6]},['capturedgrief','perpositionradius','hardness/shapematerial','independentofblastreturn'],'Custom block state replacement, no damage source.','Native UnstableIceCore delayeddeath in suitableterrain',['Canceledblast versus griefveto, leaves/ice/solidconductor, blockentitypredicateabsence.'])
    mb=package('mist_wolf_blindness','Mist Wolf darkness-gated Blindness','VANILLA_LIKE_EXTENDED',['mist_blindness','wolf_baseline'],[M+'MistWolf',M+'HostileWolf',M+'HostileWolf$LeapGoal'],{'melee':6,'brightness_exclusive':.1,'normal_ticks':140,'hard_ticks':300,'amp':0},['supermeleetrue','brightness0atwolf','wolfblocknonsolid','Easyoff'],'Native Blindness supplied by custom successful-melee/lightcondition.','Native MistWolf successful hit in darkness',['Easy/lit/solidblock/falsehurt negativecontrols; native leap/melee.'])
    def path(key,title,keys,ids,classes,labels,controls):
        data['paths'].append(dict(id='twilightforest:ranged_mobs_path:'+key,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' using native entities/equipment/AI and ordinary callbacks, no fabricated damage or HP edits.',future_controls=controls))
    for key,title,keys,ids,classes,labels,controls in [
      ('fire_breath','Native FireBeetle retaliation breath',['breath_goal','fire_beetle'],[bc,fb],[G,M+'FireBeetle'],['MOB_ATTACK','AOE'],['lastattacker vs currenttarget','warmup','fireimmune and truehurtignite']),
      ('fire_melee','Native FireBeetle ordinary and breathing melee callbacks',['fire_beetle'],[fb],[M+'FireBeetle'],['MOB_ATTACK','MELEE'],['4mobattack vs2scorched','no10secondignite frommelee']),
      ('winter_breath','Native WinterWolf retaliation breath',['breath_goal','winter_breath'],[bc,wb],[G,M+'WinterWolf'],['MOB_ATTACK','AOE'],['mob_attack2','no Frosted','freezeimmune not outgoingdamage']),
      ('breath_obstruction','Native breath target movement and winner obstruction',['breath_goal'],[bc,fb,wb],[G],['MOB_ATTACK','AOE'],['snapshotaim','movedbox','retaliationLOS vs hitwinner','insideorigin sentinel']),
      ('winter_melee','Native WinterWolf ordinary melee',['winter_breath','wolf_baseline'],[wb],[M+'WinterWolf',M+'HostileWolf'],['MOB_ATTACK','MELEE'],['effectiveattack6','no inherited leapgoal','ordinarymitigation']),
      ('nature_hit','Native Druid hoe bolt on Living victim',['nature_bolt','poison_comparison'],[nb,ds],[M+'SkeletonDruid',P+'NatureBolt'],['MOB_ATTACK','PROJECTILE'],['ownervehicleexclusion','2thenPoisononlytrue','NeoForgepoisonidentity']),
      ('nature_block','Native NatureBolt bonemeal or replacement impact',['nature_terrain'],[nb],[P+'NatureBolt'],['PROJECTILE','ENVIRONMENT'],['griefveto','bonemealvalidtarget','replaceabletag/helper']),
      ('nature_parry','Native timed shield parry of NatureBolt',['projectile_common','nature_bolt'],[nb],[P+'NatureBolt','events/EntityEvents'],['PROJECTILE','ACTIVE_ITEM'],['ownertransfer','impactcanceled','newownervehicleimmune']),
      ('druid_equipment','Native Druid equipment reassessment',['druid_state'],[ds,nb],[M+'SkeletonDruid'],['MOB_ATTACK','MELEE','PROJECTILE'],['Hoe/Stick/Bow','retainedinheritedgoals','nativebowcustomArrow']),
      ('druid_baby','Native SwarmSpider baby Druid jockey',['druid_state'],[ds],[M+'SwarmSpider',M+'SkeletonDruid'],['SUMMONED_ATTACK','MOB_ATTACK'],['passengerOR1in200','babybeforefinalize','stick','nativepassengerinsertion']),
      ('druid_reload','Native Druid IsBaby/equipment save-load',['druid_state'],[ds],[M+'SkeletonDruid'],['OTHER'],['speedmodifierreapplied','no growingup','weapon-goalreassess']),
      ('tome_hit','Native off-lectern TomeBolt attack',['tome_bolt'],[tb],[M+'DeathTome',P+'TomeBolt'],['MOB_ATTACK','PROJECTILE'],['randomidentity','3thenSlowIItrue','durationdifficulty']),
      ('tome_owner_lectern','Native TomeBolt crossing owner lectern block',['tome_bolt'],[tb],[P+'TomeBolt'],['PROJECTILE'],['sameownerblockPos','Lecternrequired','skiponHit/discard']),
      ('tome_parry','Native timed shield parry of TomeBolt',['projectile_common','tome_bolt'],[tb],[P+'TomeBolt','events/EntityEvents'],['PROJECTILE','ACTIVE_ITEM'],['inheritedITFmarker','currentownerchangeslecternexception','sourcepreserved']),
      ('tome_structure','Native generated lectern mimic gaze activation',['tome_lectern'],[ta,tb],[M+'DeathTome',M+'DeathTome$1','world/components/structures/lichtowerrevamp/LichTowerWingRoom'],['MOB_ATTACK','PROJECTILE'],['range3','noncrouch/gazeVISUALLOS','immediateshot']),
      ('tome_egg','Native spawn egg on empty lectern',['tome_lectern'],[ta],['events/MiscEvents',M+'DeathTome'],['ACTIVE_ITEM','OTHER'],['HAS_BOOKfalse','nativeSPAWN_EGG','consumesifspawnnonnull']),
      ('tome_release','Native lectern removal or accepted hurt release',['tome_lectern','tome_fire'],[ta,tf],[M+'DeathTome'],['OTHER'],['positiveacceptedrequest','Y.25','HPvslootrelease']),
      ('tome_fire','Native fire/ongoingburn on DeathTome',['tome_fire'],[tf],[M+'DeathTome'],['ENVIRONMENT','OTHER'],['2x beforepipeline','FireResistance','HPabsorption']),
      ('tome_reload','Native lectern tome save/load',['tome_lectern'],[ta],[M+'DeathTome'],['OTHER'],['on_lectern persists','persistence-required','removedlecternwake']),
      ('slime_hit','Native SlimeBeetle shot and Living impact',['slime_blob'],[sb],[M+'SlimeBeetle',P+'SlimeProjectile'],['MOB_ATTACK','PROJECTILE'],['avoidPlayergoal','thrown4','no Slowness']),
      ('slime_lifecycle','Native SlimeBlob block/hurt/parry/reload',['slime_blob','projectile_common'],[sb],[P+'SlimeProjectile','events/EntityEvents'],['PROJECTILE','ACTIVE_ITEM'],['false superhurt ignored','not normallypickable','ownerpersists']),
      ('ice_hit','Native StableIceCore snowball impact',['ice_snowball'],[ice],[M+'StableIceCore',P+'IceSnowball'],['MOB_ATTACK','PROJECTILE'],['2custommagicprojectile','no Blazebranch/Frosted','armorretained']),
      ('ice_lifecycle','Native IceSnowball block/hurt/parry/reload',['ice_snowball','projectile_common'],[ice],[P+'IceSnowball','events/EntityEvents'],['PROJECTILE','ACTIVE_ITEM'],['discardindependenthurt','ownertransfer','ownerpersisted']),
      ('core_environment','Native stable/unstable core descent, melting and melee',['ice_snowball','unstable_death'],[ice,ud],[M+'StableIceCore',M+'UnstableIceCore',M+'BaseIceMob'],['MOB_ATTACK','ENVIRONMENT'],['BaseIceMob reused','freeze/fallimmune','unstable no projectile']),
      ('core_death','Native delayed UnstableIceCore explosion',['unstable_death'],[ud,ux],[M+'UnstableIceCore'],['MOB_ATTACK','EXPLOSION'],['death60','player_explosionfactory','nativeexposure/scaling','savedDeathTime']),
      ('core_transform','Native UnstableIceCore independent terrain replacement',['unstable_terrain','unstable_death'],[ux],[M+'UnstableIceCore','util/ColorUtil'],['ENVIRONMENT'],['729randomtests','griefvsblastcancel','glassbeforeterracotta']),
      ('mist_hit','Native MistWolf melee in darkness',['mist_blindness','wolf_baseline'],[mb],[M+'MistWolf',M+'HostileWolf',M+'HostileWolf$LeapGoal'],['MOB_ATTACK','MELEE'],['actualbrightness0','wolfnotvictimlocation','Blindness140/300']),
      ('mist_negative','Native MistWolf lit/Easy/blocked or failed melee',['mist_blindness'],[mb],[M+'MistWolf'],['MOB_ATTACK','MELEE'],['no addwhenEasy','nonsolidwolfblock','false hurt/noeffect'])]:
        path(key,title,keys,ids,classes,labels,controls)
    for name,cl,methods,amount,source,mitigation in [
      ('scorched',M+'FireBeetle',['doBreathAttack','doHurtTarget'],'2; breath true ignites10 seconds, breathing melee doesnot','direct=causing=FireBeetle','Fire; ordinary armor/shield/Resistance/fire protection/absorption/cooldown; FireResistance applies.'),
      ('leaf_brain',P+'NatureBolt',['onHitEntity'],'2; true then Poison60/140 exceptPeaceful','direct=NatureBolt, causing=currentowner nullable','Magic/projectile; bypass armor/transitive shield/wolfarmor, witch resistance; ordinaryResistance/protection/absorption/cooldown.'),
      ('lost_words',P+'TomeBolt',['onHitEntity'],'3 randomBoolean branch, true then SlownessII40/120/160','direct=TomeBolt, causing=currentowner nullable','Same magic/projectile/armor+shield+wolf-bypass/witchresistance as SCHOOLED; ordinary remainingmitigation.'),
      ('schooled',P+'TomeBolt',['onHitEntity'],'3 complementary randomBoolean branch, same effect','direct=TomeBolt, causing=currentowner nullable','Identitydistinct, same gates/tags/mitigation as LOST_WORDS.'),
      ('snowball_fight',P+'IceSnowball',['onHitEntity'],'2 serverLiving, hurtreturnignored','direct=IceSnowball, causing=currentowner nullable','Magic/projectile, ordinaryarmor/shield/Resistance/protection/absorption/cooldown, not IS_FREEZING; no Frosted.')]:
        data['damage_profiles'].append(dict(type='twilightforest:'+name,status='USED',callers=[dict(entry='twilightforest/'+cl+'.class',method=m) for m in methods],amount=amount,direct_and_causing_entities=source,mitigation=mitigation,difficulty=facts['shared_pipeline']))
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','vanilla-evidence/royalvariations.json','vanilla-evidence/variants-prerequisites.json','vanilla-evidence/cult-completion.json','vanilla-evidence/vv-completion.json','reference-evidence/vv-loader-244.json','reference-evidence/royal-loader-244.json','vanilla-evidence/twilight-frosted.json','reference-evidence/twilight-frosted-244.json','vanilla-evidence/twilight-lich.json','reference-evidence/twilight-lich-244.json','vanilla-evidence/twilight-hydra-urghast.json','reference-evidence/twilight-hydra-urghast-244.json','vanilla-evidence/twilight-yeti-queen.json','reference-evidence/twilight-yeti-queen-244.json','config-evidence/twilightforest-common.json','twilightforest-ranged-mobs-caller-scan.json']
    data['exclusions']=['All18 declared native classes fully pinned/read, plus limited producer/registration/color witnesses; names are not evidence.','HostileWolf ordinary melee/leap/variant, ordinary mob attributes/sounds/particles/loot are assessed but not each new package.','BaseIceMob descent/melting/defense reused from protected IceCrystal review; no duplicate Frosted or IceBomb package.','Full SwarmSpider behavior and SnowGuardian equipment are left to remaining mobs/items; only proven babyDruid producer included here.','Custom source census advances only five actual callers; remaining18 are unfinished, not unused.','No inference that all cold-looking attacks freeze, all slime-looking attacks slow, or all magic-tagged attacks bypassarmor.','No runtime tests, balancing, fixes, production or Stage changes.']
    data['fixture_groups']=['Legitimate retaliation-first FireBeetle/WinterWolf goal, snapshot/winner/LOS controls, native fire vs ordinarymob source.','Adult/baby/equipped Druid with native hoe/Stick/Bow, NatureBolt Living/vehicle/terrain/parry/reload and subsequent installedpoison.','Tome natural/structure/spawn-egg lectern producers, gaze/crouch/hurtwake, fireweakness, two sources/Slowness and parry/reload.','SlimeBeetle/Core native shots, exact hurt/discard/owner handling, no inventedslow/Frosted.','UnstableCore death60/nativeblast vs independenttransform, source/tags/exposure/grief/events/persistence.','MistWolf brightness0/nonsolid/Easy/normal/Hard and native successful-melee controls.']
    from collections import Counter
    data['expected_counts']=dict(mechanic_packages=13,delivery_cases=28,classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=5)
    write_json(OUT/'review-inputs/twilightforest-ranged-mobs.json',data)
    assemble('twilightforest-ranged-mobs.json')


if __name__=='__main__':build()
