"""R2f4 Naga semantics. No runtime execution, fixes or final Twilight promotion."""
from copy import deepcopy
from collections import Counter
from twilight_evidence import *
from assemble_batch import refresh

START='d9dffb33a867aae9152a2ed3bc68f50b0b02f59d'
CP='R2f4-naga-complete'
NEXT='Begin Minoshroom + Knight Phantom semantic review from existing installed Twilight source aids. Naga, Lich and Frosted are complete subsections; do not repeat them. Then Hydra + Ur-Ghast, followed by Alpha Yeti + Snow Queen. No Ice and Fire, runtime boss/L2 tests, Stage/production, balancing or Phase6/Phase7 work.'

def build():
    facts={
      'ordinary_melee': 'SimplifiedAttackGoal canUse requires Living target and native melee-range intersection; checkAndPerformAttack also requires LOS and attackTick<=0. Native unmounted reach is head AABB inflated XZ by sqrt(2.04F)-0.6, not a segment-count radius. Goal flags are empty and requiresUpdateEveryTick=true, so it coexists with movement. Start/stop resets counter0; successful admission sets adjustedTickDelay(20)=20 before calling doHurtTarget and ignores its return. With uninterrupted goal execution,20 decrement calls precede the next attack call (21 tick-call spacing); re-entry can attack immediately. Outside blocking special branches and while !isDazed, super Mob.doHurtTarget requests minecraft:mob_attack using effective ATTACK_DAMAGE (registered base5) modified by native weapon enchantments. Success enables native enchantment post-attack/knockback and then Naga adds victim velocity(-sin(yaw)*2,0.4,cos(yaw)*2). False suppresses that extra push. The HP hit is ORDINARY_MELEE; only the extra delivery/control is a special package. True hurt can occur with no actual HP loss.',
      'charge_block': 'Before normal melee, target must be Living and isBlocking. Exact244 isBlocking requires active nonempty use item, SHIELD_BLOCK ability and use elapsed>=5; no facing/source-angle test is added by Naga. With movement state CHARGE, victim server velocity receives (1.5*vx,0.5,1.5*vz), Naga receives(-1.25*vx,0.5,-1.25*vz), using original Naga motion. ServerPlayer gets durability request5 on current use item, then registered play-to-client MovePlayerPacket whose handler adds(3*vx,vy+0.75,3*vz) to client motion. Do not add those server/client vectors into one guaranteed resulting velocity. Naga then requests ownerless minecraft:generic2 on itself, ignores its return, plays block sound, enters doDaze and returns false without ordinary victim melee. Thus false does not mean no self damage or no movement. Self recoil can be rejected by its existing hurt cooldown yet daze still starts. Native durability/Unbreaking/creative rules remain;5 is requested durability, not guaranteed loss.',
      'stunless_block': 'Same initial Living/isBlocking gate, but movement state STUNLESS_CHARGE. ServerPlayer: durability request10, then addCooldown(current use-item item,200), stopUsingItem and broadcast shield-break animation. These are not contingent on damage success. The item is read again after durability handling; if it broke, do not assume the cooldown necessarily names the original shield. Other Living blockers do not receive this Player-only disable branch. Requests minecraft:mob_attack4 directly (not Mob.doHurtTarget, no ATTACK_DAMAGE/weapon-damage modification and no normal post-attack callback), ignores hurt return, changes pattern to CIRCLE and returns false. Player stopped using can take the ordinary mitigated hit; nonPlayer blocker retains native facing shield admission. No special armor/Resistance bypass is created.',
      'parts_link': 'Naga constructs12 NagaSegment objects; each TFPart extends NeoForge PartEntity<Entity>, retaining a final parent reference and the parent EntityType/world. They are Entity, not LivingEntity, and have no HP/armor/effect pool. Parent getParts always returns all12; exact244 tracking inserts/removes all into the part map, and world entity queries append intersecting parts. Client recreate assigns parentId+i+1; TF part data synchronizes positions/dimensions/data. Native interaction lookup uses getEntityOrPart; ordinary reach/world-border/attack hooks still apply. TFPart.isPickable always true; inherited Entity.canBeHitByProjectile is isAlive && isPickable. NagaSegment.is(entity) accepts itself or parent, but the inspected world query uses identity and does not deduplicate by parent.',
      'parts_forward': 'NagaSegment.hurt forwards the SAME DamageSource and amount*2F/3F to parent.hurt when !isInvisible; returns parent result. It neither calls own super.hurt nor subtracts local HP. Multiplication/division occur before parent invulnerability, incoming event, armor, Resistance/protection, absorption and shared hurt cooldown. This is a fixed segment-hit reduction, not a head damage cap or projectile immunity. Two-thirds applies to bypass-tagged sources too; parent source-specific rejection remains. Source direct/causing entities are unchanged and checked against home bounds at the head.',
      'parts_contact': 'Each parent tick calls tick on every part BEFORE repositioning it. NagaSegment tick, when !isInvisible, queries its current AABB. Only entity.isPushable candidates call collideWithEntity. It first invokes recipient.push(part), independently of hurt; for a Living recipient other than ANY Naga, when parent !isDazed and !isDeadOrDying, it then requests minecraft:mob_attack2, or6 if recipient instanceof Animal. Source direct/causing=parent Naga, not the part. Result ignored; no LOS, target, team/owner test, bespoke cooldown or weapon/enchantment post-attack call. Multiple overlapping segments can attempt in one parent tick; recipient native invulnerability normally rejects equal later requests. Native collision push checks same vehicle/noPhysics/sleep and position, and does not use the damage-return gate. Nonpushable entities receive neither this push nor contact hurt. Dazed/dead parent stops contact damage, but not the preceding push.',
      'parts_activity': 'activate sets size2x2 and own invisible flagfalse; deactivate sets size0x0 and own flagtrue. However TFPart.isInvisible returns PARENT.isInvisible, and NagaSegment does not override it. Consequently local deactivation does not make the hurt/contact !isInvisible predicate false while parent visible. All12 remain returned/moved; zero-sized boxes still can intersect a containing AABB and projectile selection inflates hitboxes, so loss is not a proven absolute untargetability/contact-disable guarantee. Parent Invisibility suppresses all segment forwarding/contact regardless their local active flags. This is a resolved installed-code discrepancy, not REVIEW_REQUIRED or a fix. Native generic Entity isAlive only tests removal; dead parent alone does not mark parts removed until parent cleanup.',
      'parts_geometry': 'Every parent tick: update segment count, super.tick, then for each of12 tick/contact followed by position. Leader=head for first, previous part thereafter; normalized existing separation plus head/leader facing straightenForce=0.05+0.5/(i+1), or0 if head dead. Final adjacent offset length2; in-wall part adds vertical correction before normalization. This changes real contact geometry, not just renderer animation. Native part push(D,D,D) does not forward movement to head and next positioning can overwrite displacement. Head isPushable=false prevents ordinary collision shoving, not hurt knockback/manual pushes. Incoming LivingEntity knockback retains registered KR0.25; explicit Naga velocity writes do not read that attribute.',
      'multi_hits': 'Generic Entity queries/AoEs can include head plus multiple parts and make separate forwarded requests; LivingEntity-only AoEs exclude the parts. No Naga-wide attack-ID deduplication exists. Native piercing-arrow ignored IDs are per hit entity, so head/parts are separate candidates, bounded by piercing and collision/return handling. Forwarded requests share head invulnerableTime/lastHurt: equal/lower during>10 is rejected unless BYPASSES_COOLDOWN, larger admitted request contributes only excess over prior amount. A later head hit can therefore add the difference after a reduced segment hit; do not multiply full damage by13. A successful ordinary nonpiercing arrow discards. Parts are not Living, so native arrow potion/post-hurt/knockback callbacks that require Living target do not automatically run on parent. Native Player attack routes successful item.hurtEnemy to the part parent, but enchantment post-attack still receives the originally hit entity; a legitimate sweeping Living-only query may additionally hit head if geometry/eligibility permits.',
      'defense': 'Naga.isInvulnerableTo ordering: nonnull causing entity outside home -> true; nonnull direct entity outside home -> true; IS_EXPLOSION -> true; else super. Home uses floored block positions relative to valid same-dimension restriction point, inclusive |dx|<=46, |dy|<=7, |dz|<=46; invalid/missing home returns true for within-home. No own-position test is added to this damage predicate. Ownerless/directless environment bypasses only the entity-position checks. Thus an inside projectile from an outside owner still fails. These early home/explosion rejections precede super and have no BYPASSES_INVULNERABILITY exemption. Registered EntityType fireImmune=true rejects IS_FIRE through native Entity invulnerability; installed fall_damage_immune tag similarly rejects IS_FALL. Normal native invulnerability event can affect that later superclass decision. Naga also overrides isInLava false, not universal immunity to all unnamed damage. No Naga projectile/magic whitelist, flat cap, daze-vulnerability multiplier, shield resource or HP-phase admission threshold exists.',
      'native_damage': 'Admitted head damage uses exact244 LivingEntity pipeline: invulnerability/client/dead/fire-resistance checks; incoming event; shield/freeze/helmet changes; invulnerableTime>10 rejection or excess; normal armor/toughness, Resistance and protection, absorption, pre/post events/death. No Naga cooldown reset or special short iframe. Naga.hurt only acts after true super return: resets ticksSinceDamaged=0, and if isDazed adds (int)original method argument to damageDuringCurrentStun. This integer accumulator is not actual HP loss; body reduction has already happened, but armor/absorption/cooldown excess have not changed this argument. Server AI forces CIRCLE when accumulator>15 and resets it then only; it is not reset by entering/leaving each daze, so subthreshold totals can carry between dazes. ForceCircle changes state/counter, and daze flag clears when CIRCLE tick executes.',
      'health_segments': 'Registered base HP120, speed0.5, attack5, follow80, KR0.25, stepheight2. Constructor stores final healthPerSegment=getMaxHealth()/10 =12 for native attributes BEFORE finalizeSpawn. Non-Easy finalization adds difficulty_health_boost +130 Hard else+80 and fills health once: native Easy120/Normal200/Hard250. Denominator remains12; it is not recomputed from finalized maxHP or later changes/load. Each tick N=clamp(int(HP/12+(HP>0?2:0)),0,12). All difficulties therefore keep12 segments until HP<120; normal/hard do not use proportional ten-percent segment losses. Alive lowHP retains2, HP0 yields0. On count change, server replaces transient segment_speed_boost ADD_VALUE with float(12/N*0.02), so effective base speed normally0.52 at12 through0.62 at2 before other modifiers. N=0 calculation is unguarded floating-point Infinity, not division exception; native ranged-attribute sanitization/clamping remains. It is not proof of an infinite-speed living attack. No direct HP-based attack-damage multiplier.',
      'segment_lifecycle': 'When N drops old->new, parts indices[new,old) receive deathCounter=(old-i)*12 and remain active-sized until their countdown reaches0. Thus lost parts can continue their actual contact during staged loss. Completion makes particles/sound, resets parent.deathTime=0 and deactivates size0. Growth calls activateBodySegments for ALL indices<new, repositioning them near head; it does not clear existing part deathCounter, so a previously scheduled countdown can later deactivate a reactivated part. No independent severed-part life/damage pool. Parent removal server-side kills all12. Naga server removal waits deathTime>=124 (BaseTFBoss), with segment countdown completion resetting that counter; corpse duration is therefore not always exactly124 after lethal HP loss. HP0 still activates native dead hurt rejection; presentation/deferred removal is not extra HP or mandatory per-segment killing.',
      'regeneration': 'customServerAiStep increments ticksSinceDamaged; when>600 AND divisible by20 it calls native heal(1). First uninterrupted eligible call is620, then640 etc, not600. Counter resets only on true Naga.hurt; a rejected source does not postpone regen. Heal uses native alive/health/event/clamp behavior, not setHealth bypass. Segment count can grow on following tick and reduce speed modifier. Counter, stun accumulator, current count, movement state/counters and part death counters are not custom NBT-saved by Naga/parts; ordinary parent health/attributes/home remain native-saved and constructor-derived denominator remains12 on ordinary reload. There is no permanent severing state.',
      'movement': 'MovementPattern requires target and both self/target in home. Default/stop state CIRCLE counter15, clockwisefalse; stop does not itself clear DATA_DAZE/CHARGE/STUNLESS. Goal MOVE/LOOK, default requiresUpdateEveryTick=false; native Mob schedules it on full selector ticks, generally alternating ticks. State counter advances only when navigation done, using postdecrement (counter--<=0 transitions); while path active it waits or stops a stuck path. These counters are NOT fixed wall-clock attack seconds. Circle clears daze/charge (which clears stunless), uses radius12/14 alternating, radius16 when counter2 and rotation0.1 instead of1 when counter1. CandidateY=min(head.minY,targetY). Intimidate stops/looks, sets forward input.1 and counter +=15+randInt10. One calculation picks stunless with randomFloat*.75 < clamp(.75-HP/maxHP+difficultyId*.05,0,.5), giving probability threshold/.75 capped2/3. It is a choice probability, not a50% cap or hard HP phase.',
      'rush_daze': 'Intimidate transition flips clockwise; if target.minY>head.maxY selects CRUMBLE else charge. Crumble counter20+randInt20, then charge. Charge/STUNLESS counter2 sends navigation to target-relative radius5/rotationPI at speed multiplier1.5, sets DATA_CHARGE; no independent rush DamageSource/damage bonus. CIRCLE uses speed1.0. Custom move control DAZE sets strafe xxa0; CHARGE or INTIMIDATE multiplies strafe by.8; other states INCLUDING STUNLESS_CHARGE use cos(tickCount*.3)*.6; native MoveControl may further set movement. These are real movement inputs, not decorative body animation. doDaze sets state/nav-stop/counter60+randInt40 but DATA_DAZE only sets during DAZE tick; DATA_CHARGE then clears. doCircle counter +=10+randInt10, forceCircle resets10+randInt10; neither immediately clears synced flags. DAZE blocks normal head melee/body damage when bool set, but collision push/externally applied velocity remains; no MobEffect or universal immobilization is created.',
      'terrain': 'customServerAiStep, gated by EventHooks.canEntityGrief and loaded box: x/z head BB±.75; y floor(minY+(shouldDestroyAll?1.01:.5)) to floor(maxY+1). Leaves are destroyed with no drops; other blocks only if charging OR head outside home and EntityUtil.canDestroyBlock succeeds. NagaSmashGoal canUse horizontalCollision+grief; server start uses same XZ with y min+1.01 to maxY (no+1); leaves OR charging/outside-home helper rule. Leaves short-circuit the helper hardness/container/per-block test, though the outer grief and loaded-region gates remain. Helper requires hardness>=0 and<50, nonair, no Container block entity, block.canEntityDestroy and uncanceled LivingDestroyBlockEvent. Default loader block permission for Naga allows, but custom blocks can override. Grief event defaults to mobGriefing and is externally alterable. These destroy real obstacles/support and pressure combat navigation; they are not extra direct damage.',
      'crumble_home': 'CRUMBLE tick calls crumbleBelowTarget(2) and(3). Grief+target needed, int(target.minY)>int(head.minY). For each range r, dx/dz=int(target coord)+rand(r)-rand(r), dy=targetY-rand(r)+rand(r-1); ifdy<=floor substitutes targetY. Helper permission as above, destroys with drops; no bespoke direct damage or LOS requirement. Any later fall damage is native environment, not Naga damage. Combat targeting clears when target distanceSquared>6400 or either outside home; native player target selector also checks home, retaliation remains native. Every20ticks with valid home and headY<homeY-5, teleport to integer homeXYZ and stop navigation. This is positional recovery, no teleport damage/invulnerability/refill. Path shortcut advances nodes while horizontal distance<4*headWidth (normally8), not a body-contact damage radius.',
    }
    E=[];P=[]
    def add(key,title,classification,keys,classes,components):
        eid='twilightforest:naga_'+key
        e=dict(id=eid,mod_key='twilightforest',display_name=title,inspection_status='DRAFT',subsection_status='REVIEWED',primary_classification=classification,classification_provisional=False,actual_behavior=[facts[k] for k in keys],components=[dict(primitive=p,formula=f,numerical_parameters=n,binary_parameters=b,vanilla_relation=v) for p,f,n,b,v in components],implementation=native_refs(*classes),primary_test_source='Native Naga boss-spawner encounter; source/setups in delivery cases',delivery_paths=[],registry_ids=[],pending=['Twilight whole-mod semantic closure and final promotion; Naga subsection is reviewed.'],unresolved_ambiguities=None)
        E.append(e);return eid
    melee=add('head_contact','Naga ordinary melee with added push','VANILLA_LIKE_EXTENDED',['ordinary_melee'],['entity/boss/Naga','entity/ai/goal/SimplifiedAttackGoal'],[('ORDINARY_MELEE','effective attack attribute + native weapon enchantment; ordinary mob_attack',{'base_attack':5,'set_cooldown':20},['melee hitbox','LOS','!dazed','native hurt'],'VANILLA_DIRECT; ordinary damage alone not a separate special package'),('ADDITIONAL_PUSH','success -> (-sin(yaw)*2,.4,cos(yaw)*2)',{'horizontal':2,'vertical':.4},['super.doHurtTarget true'],'Custom additive velocity, no KR lookup')])
    block=add('charge_block','Naga charge block recoil/daze','CUSTOM_CONTROL',['charge_block'],['entity/boss/Naga','entity/ai/goal/NagaMovementPattern','network/MovePlayerPacket'],[('BLOCK_RECOIL','state CHARGE + blocking -> two-way push; generic2 self; daze; false',{'self_request':2,'durability_request':5,'victim_xz':1.5,'self_xz':-1.25,'server_y':.5,'client_xz':3,'client_y_added':.75},['Living isBlocking','state CHARGE','Player-only durability/packet'],'Custom branch around native block/damage APIs')])
    stunless=add('stunless_block','Naga stunless charge shield disruption','VANILLA_LIKE_EXTENDED',['stunless_block'],['entity/boss/Naga','entity/ai/goal/NagaMovementPattern'],[('SHIELD_DISRUPTION','durability10; item cooldown200; stop use; mob_attack4; circle; false',{'durability_request':10,'cooldown':200,'damage_request':4},['Living isBlocking','state STUNLESS_CHARGE','ServerPlayer-only disable'],'Native cooldown/damage primitives in custom return-independent branch')])
    body=add('multipart_body','Naga linked body routing/contact','VANILLA_LIKE_EXTENDED',['parts_link','parts_forward','parts_contact','parts_activity','parts_geometry','multi_hits','segment_lifecycle'],['entity/boss/Naga','entity/boss/NagaSegment','entity/TFPart','network/UpdateTFMultipartPacket','util/multiparts/MultipartEntityUtil'],[('SHARED_DAMAGE_ROUTING','same source *2/3 -> parent hurt',{'factor':2/3,'allocated_parts':12},['!parent.isInvisible','parent admission'],'Native hurt once per forwarded request, shared cooldown'),('BODY_CONTACT','push first; mob_attack2 or Animal6; ignore return',{'normal':2,'animal':6,'active_width':2,'active_height':2,'inactive_size':0,'spacing':2},['recipient pushable','Living non-Naga','parent !dazed/alive for damage'],'Ordinary mob_attack in custom collision producer')])
    defense=add('admission','Naga source/home damage admission','BINARY_MECHANIC',['defense','native_damage'],['entity/boss/Naga','entity/boss/BaseTFBoss','init/TFEntities'],[('ADMISSION','owner/direct within home; !explosion; native fire/fall immunity and hurt processing',{'home_xz':46,'home_y':7,'knockback_resistance':.25},['valid home or unrestricted','source tags','native invulnerability hooks'],'Custom home/explosion gates; native fire/fall and mitigation')])
    health=add('health_body_resource','Naga HP/body/speed and regeneration','CUSTOM_RESOURCE',['health_segments','segment_lifecycle','regeneration','native_damage'],['entity/boss/Naga','entity/boss/NagaSegment','block/entity/spawner/BossSpawnerBlockEntity'],[('HP_TO_BODY_SPEED','N=clamp(int(HP/12+(HP>0?2:0)),0,12); speed+.24/N',{'base_hp':120,'normal_bonus':80,'hard_bonus':130,'health_per_segment':12,'base_speed':.5,'alive_min_segments':2,'stagger':12},['constructor denominator precedes finalization','native attribute clamp'],'Custom coupled state'),('REGENERATION','timer>600 and%20==0 ->heal1',{'delay_exclusive':600,'first_tick':620,'interval':20,'heal':1},['native server AI','successful hurt resets'],'Native heal API; custom timer'),('DAZE_DAMAGE_COUNTER','true hurt adds int(argument); >15 forces circle',{'threshold_exclusive':15},['isDazed','true parent hurt','not actual HP lost'],'Custom cumulative interrupt; no damage cap')])
    movement=add('combat_movement','Naga combat movement state machine','CUSTOM_CONTROL',['movement','rush_daze','crumble_home'],['entity/ai/goal/NagaMovementPattern','entity/ai/control/NagaMoveControl','entity/boss/Naga'],[('MOVEMENT_STATE','CIRCLE/INTIMIDATE/CRUMBLE/CHARGE/STUNLESS/DAZE; navigation-dependent counters',{'circle_speed':1,'charge_speed':1.5,'charge_counter':2,'daze_min':60,'daze_rand_bound':40,'stunless_probability_cap':2/3},['target','home','navigation done for state advance','native goal scheduling'],'Native navigation with custom combat gates and real inputs')])
    terrain=add('terrain_pressure','Naga combat terrain destruction/recovery','CUSTOM_CONTROL',['terrain','crumble_home'],['entity/boss/Naga','entity/ai/goal/NagaSmashGoal','entity/ai/goal/NagaMovementPattern','util/entities/EntityUtil'],[('OBSTACLE_DESTRUCTION','adjacent leaves or charging/outside-home helper-approved blocks',{'xz_padding':.75,'hardness_min':0,'hardness_exclusive_max':50},['canEntityGrief','loaded region','leaf/helper branch'],'Native destroyBlock changes combat navigation'),('SUPPORT_AND_HOME','crumble ranges2+3; home rescue belowY-5 every20',{'crumble_ranges':[2,3],'home_y_offset':-5,'home_check_interval':20},['high target','grief/helper','valid home for rescue'],'No custom damage request; native later environmental damage only')])
    def path(key,labels,title,detail,ids,classes,controls):
        pid='twilightforest:naga_path:'+key
        P.append(dict(id=pid,mod_key='twilightforest',status='DRAFT',subsection_status='REVIEWED',labels=labels,source=title,native_delivery=detail,setup=detail,effect_ids=ids,implementation=native_refs(*classes),future_controls=controls))
        for e in E:
            if e['id'] in ids:e['delivery_paths'].append(pid)
    path('head_melee',['BOSS_ATTACK','MELEE'],'Ordinary head melee',facts['ordinary_melee'],[melee,movement],['entity/boss/Naga','entity/ai/goal/SimplifiedAttackGoal'],['true/false hurt','absorption versus HP','LOS/range','native21-call cadence','dazed flag'])
    path('charge_player_block',['BOSS_ATTACK','MELEE','ACTIVE_ITEM'],'Native Player block during CHARGE',facts['charge_block'],[block,movement],['entity/boss/Naga','network/MovePlayerPacket'],['blocking warmup5','facing away still early branch','durability break/Unbreaking','self hurt cooldown','server/client motion separately'])
    path('charge_other_block',['BOSS_ATTACK','MELEE'],'Other Living blocking during CHARGE','Native Living isBlocking branch; same pushes/self generic2/daze, no ServerPlayer durability/packet.',[block],['entity/boss/Naga'],['genuine native blocking actor required','no invented shield eligibility'])
    path('stunless_player_block',['BOSS_ATTACK','MELEE','ACTIVE_ITEM'],'Native Player block during STUNLESS_CHARGE',facts['stunless_block'],[stunless,movement],['entity/boss/Naga','entity/ai/goal/NagaMovementPattern'],['current use item after durability','false return versus victim HP','cooldown200','native mitigation'])
    path('stunless_other_block',['BOSS_ATTACK','MELEE'],'Other Living blocker during stunless charge','Fixed mob_attack4, no Player-only stop/cooldown/durability; native shield facing may still reject; doCircle/false independent.',[stunless],['entity/boss/Naga'],['native blockable source angle','hurt false still circle'])
    path('body_nonanimal',['BOSS_ATTACK','MELEE'],'Native segment contact with non-Animal Living',facts['parts_contact'],[body],['entity/boss/NagaSegment','entity/boss/Naga'],['pushable predicate','daze/dead: push versus damage','overlapping segments','no LOS/team gate','amount2'])
    path('body_animal',['BOSS_ATTACK','MELEE'],'Native segment contact with Animal','Same collision path with instanceof Animal triples2 to6. Direct/causing parent Naga; no weapon enchantment dispatch.',[body],['entity/boss/NagaSegment'],['Animal versus other Living','Player difficulty scaling applies only to Player victims'])
    path('head_incoming',['MELEE','PROJECTILE','ENVIRONMENT'],'Native incoming hit to head',facts['defense']+' '+facts['native_damage'],[defense,health],['entity/boss/Naga'],['inside projectile/outside owner','ownerless environmental','explosion/fire/fall tags','normal arrow','native bypass tags','shared cooldown/absorption'])
    path('part_incoming',['MELEE','PROJECTILE'],'Native incoming hit to body part',facts['parts_forward']+' '+facts['multi_hits'],[body,defense],['entity/boss/NagaSegment','entity/TFPart','entity/boss/Naga'],['same source identity','2/3 before mitigation','part versus head','nonpiercing/piercing/tipped arrows','Player item callback parent'])
    path('multipart_overlap',['AOE','PROJECTILE'],'One native delivery intersecting multiple parts',facts['multi_hits'],[body,defense],['entity/TFPart','entity/boss/NagaSegment','entity/boss/Naga'],['entity-query versus Living-only AoE','multiple attempts not multiplied HP','BYPASSES_COOLDOWN only from legitimate native source'])
    path('segment_loss_growth',['BOSS_ATTACK','OTHER'],'Native HP loss and subsequent regeneration',facts['health_segments']+' '+facts['segment_lifecycle'],[health,body],['entity/boss/Naga','entity/boss/NagaSegment'],['Easy/Normal/Hard denominator12','120 boundary','pending deactivation versus regrowth','zero-size point geometry','parent Invisibility'])
    path('regen_daze_counter',['BOSS_ATTACK','OTHER'],'Native accepted/rejected hurt and idle regeneration',facts['regeneration']+' '+facts['native_damage'],[health,movement],['entity/boss/Naga','entity/ai/goal/NagaMovementPattern'],['619/620','false hurt no reset','int argument versus HP','cumulative dazes','15 versus16'])
    path('movement_cycle',['BOSS_ATTACK','OTHER'],'Native movement state/HP choice',facts['movement']+' '+facts['rush_daze'],[movement],['entity/ai/goal/NagaMovementPattern','entity/ai/control/NagaMoveControl'],['navigation wait/stuck','actual selector cadence','stunless probability<=2/3','flags update separately','speed multiplier1.5 not damage multiplier'])
    path('adjacent_terrain',['BOSS_ATTACK','ENVIRONMENT'],'Head adjacent terrain clearing',facts['terrain'],[terrain],['entity/boss/Naga','util/entities/EntityUtil'],['mobGriefing/event veto','leaves bypass helper','Container/hardness50','charge/outside-home predicate','loaded box'])
    path('collision_smash',['BOSS_ATTACK','ENVIRONMENT'],'Horizontal collision NagaSmashGoal','Native horizontalCollision + grief permits goal start; server loaded scan minY+1.01 to maxY, leaves OR shouldDestroyAll/helper. It is not an unrestricted block smash or direct damage.',[terrain],['entity/ai/goal/NagaSmashGoal','util/entities/EntityUtil'],['collision but not charging','leaves versus protected blocks','scan height difference'])
    path('high_target_crumble',['BOSS_ATTACK','ENVIRONMENT'],'High target CRUMBLE',facts['crumble_home'],[terrain,movement],['entity/ai/goal/NagaMovementPattern','entity/boss/Naga','util/entities/EntityUtil'],['target above head.maxY transition','two sampled blocks per active goal call','truncated negative coords','native falling after support loss'])
    path('home_recovery',['BOSS_ATTACK','OTHER'],'Native boss-spawner home and recovery','Boss spawner range50, nonPeaceful, native finalization then valid same-dimension GlobalPos restriction. Target/home checks and native rescue teleport apply; native spawn-egg without home is an unrestricted comparison, not equivalent defended encounter.',[defense,movement,terrain],['block/entity/spawner/NagaSpawnerBlockEntity','block/entity/spawner/BossSpawnerBlockEntity','entity/boss/Naga'],['source and target boundaries separately','same dimension','homeY-5','no damage/iframes from rescue'])
    path('death_cleanup',['BOSS_ATTACK','OTHER'],'Native lethal HP and staged part cleanup',facts['segment_lifecycle'],[body,health],['entity/boss/Naga','entity/boss/NagaSegment','entity/boss/BaseTFBoss'],['HP0 native rejection','deathTime reset by part countdown','no independent segment HP','all12 killed on removal'])
    tags={r['entry'].split('/tags/damage_type/')[1][:-5]:r['data']['values'] for r in read_json(OUT/'vanilla-evidence/royalvariations.json')['resources'] if '/tags/damage_type/' in r['entry']}
    def values(tag,seen=()):
        out=set()
        for item in tags[tag]:
            item=item['id'] if isinstance(item,dict) else item
            if item.startswith('#minecraft:'):
                sub=item.split(':',1)[1]
                if sub not in seen:out.update(values(sub,seen+(tag,)))
            else:out.add(item)
        return out
    data=read_json(OUT/'vanilla-evidence/twilight-naga-data.json')['resources']
    profiles=[]
    for name,amount,callers,entities in [('mob_attack','head effective attribute5 default; blocking stunless4; body2/Animal6',[('entity/boss/Naga','doHurtTarget'),('entity/boss/NagaSegment','collideWithEntity')],'direct=Naga; causing=Naga (also body contact)'),('generic','self recoil2',[('entity/boss/Naga','doHurtTarget')],'direct=null; causing=null')]:
        rid='minecraft:'+name;membership=sorted('minecraft:'+k for k in tags if rid in values(k))
        profiles.append(dict(type=rid,status='USED_NATIVE_VANILLA',callers=[dict(entry='twilightforest/'+c+'.class',method=m) for c,m in callers],amount=amount,direct_and_causing_entities=entities,tags=membership,declaration=next(r for r in data if r['entry'].endswith('/'+name+'.json')),
          mitigation='Ordinary native armor for mob_attack; generic bypasses armor and native damage knockback. Both retain Resistance/protection/absorption/cooldown, no invulnerability bypass. Generic is ownerless and has no source-position shield direction. Source flags do not disable the separate explicit Naga motion writes.',
          identity='Neither type is projectile, fire, explosion or magic in the scoped raw/TF declarations. mob_attack is ordinary physical melee identity, not an invented physical tag. No custom Naga DamageType.',
          difficulty='mob_attack caused by Naga scales Player requests: Peaceful0, Easy min(amount/2+1,amount), Normal amount, Hard1.5*amount. Animal/nonPlayer victims do not get Player scaling. generic self recoil ownerless/Naga recipient does not scale.'))
    comparison=['vanilla-evidence/twilight-naga.json','vanilla-evidence/twilight-naga-data.json','reference-evidence/twilight-naga-244.json','reference-evidence/twilight-frosted-244.json','reference-evidence/cult-loader-244.json','reference-evidence/royal-loader-244.json','vanilla-evidence/royalvariations.json','vanilla-evidence/twilight-lich.json','reference-evidence/twilight-lich-244.json']
    section=dict(schema='tno.external_effects.semantic_section.v1',baseline=BASELINE,mod_key='twilightforest',checkpoint=CP,starting_sha=START,status='REVIEWED_SUBSET_NOT_MOD_COMPLETE',subsection_decision='NAGA_SEMANTIC_REVIEW_COMPLETE',semantic_coverage_complete=False,promoted_to_catalog=False,effects=E,paths=P,damage_profiles=profiles,semantic_closure=facts,
      closure_checklist={k:True for k in ['attacks','defenses','body_segments','health_phases','source_delivery','exclusions','damage_types','classification_audit']},
      comparison_evidence=[dict(evidence_file=f,sha256=sha256(OUT/f)) for f in comparison],source_registration_evidence=native_refs('init/TFEntities','events/RegistrationEvents','block/entity/spawner/NagaSpawnerBlockEntity','block/entity/spawner/BossSpawnerBlockEntity','asmhooks/MultipartHooks','util/multiparts/MultipartEntityUtil'),
      exclusions=['Ordinary Mob.doHurtTarget HP damage alone is ORDINARY_MELEE, not a new CUSTOM_DAMAGE package. Included package is its extra success-dependent push.','Hiss/rattle/block sounds, crit/angry/poof particles, red overlay, bossbar10notches, tail renderer rotations and124tick presentation trail are not extra damage/status. Real segment positioning and death-counter resets are retained.','Ambient RandomStroll radius30/Y7 and purely visual interpolation are not separate effects. Combat circle/charge/strafe changes are real movement inputs and retained.','Loot chest/advancement/worldgen/progression acquisition is excluded. Terrain destruction is included only as obstacle/support pressure and home recovery; no invented damage source.','Installed Twilight contributes alexscaves:resists_acid entity tag for Naga. This declaration alone is not proven immunity; external Alexs Caves consumer attribution belongs to its later mod review, which was not started.'],
      compatibility_scope='Native Twilight + Minecraft + exact NeoForge21.1.244, reusing four pinned candidate scans from Frosted. No direct Naga-specific patch proven there. Generic damage/status hooks remain conditional on real dispatched events, source owner/recipient and head-versus-part callback differences; no pack-wide guarantee or fixes. Installed multiplayerFightAdjuster=NONE snapshot is reused, so native multiplayer HP bonus is disabled in that pinned configuration.',
      future_source_requirements=dict(primary='One native Naga producer family; actual boss-spawner encounter establishes home/finalization. Native spawn-egg without home is a distinct control.',controls=['Difficulty variants Easy/Normal/Hard; HP-derived body thresholds and delayed loss/regrowth','Player block warmup/facing and CHARGE versus STUNLESS; durability break/Unbreaking','NonPlayer genuine blocking control; ordinary Living/Animal/nonpushable body recipients','Inside/outside direct and causing entities; native projectile, fire, fall and explosion sources','Head/part single hit, piercing and overlapping native AoE; armor/Resistance/absorption/cooldown','Stun accumulator/regen620 and corpse countdown; native data reload','MobGriefing/event/block eligibility, elevated target and valid/absent home'],runtime_runs_executed=0,minimum_global_runs=None),
      counts=dict(mechanic_packages=len(E),delivery_cases=len(P),classification_totals=dict(Counter(e['primary_classification'] for e in E)),review_required=0,custom_damage_types=0),exact_next_task=NEXT,**boundary_flags())
    write_json(OUT/'semantic-sections/twilightforest-naga.json',section)
    prior=read_json(OUT/'partial-drafts/twilightforest-r2f3-partial.json');draft=deepcopy(prior);draft.update(checkpoint=CP,starting_sha=START,effects=prior['effects']+E,paths=prior['paths']+P)
    write_json(OUT/'partial-drafts/twilightforest-r2f4-partial.json',draft)
    review=read_json(OUT/'mod-reviews/twilightforest.json');review.update(checkpoint=CP,scope='Frosted, Lich and Naga complete reviewed subsections; whole Twilight PARTIAL with zero final promotions.',draft_file='partial-drafts/twilightforest-r2f4-partial.json',notes_file='semantic-sections/twilightforest-naga.json',draft_mechanic_count=len(draft['effects']),draft_path_count=len(draft['paths']),exact_next_task=NEXT);write_json(OUT/'mod-reviews/twilightforest.json',review);refresh(CP)
    for f in ['effect-catalog.json','effect-sources.json','delivery-path-matrix.json','vanilla-comparison.json','behavior-primitives.json']:
        d=read_json(OUT/f);d.update(checkpoint=CP,unfinished_review=dict(mod_key='twilightforest',status='PARTIAL',draft_file=review['draft_file'],promoted_records=0));write_json(OUT/f,d)
    decision=read_json(OUT/'research-decision.json');decision.update(checkpoint=CP,naga_decision='NAGA_SEMANTIC_REVIEW_COMPLETE',next_task=NEXT,save_mode=True,save_reason='Research stopped at70% five-hour usage to reserve validation, commit and push capacity; Minoshroom and Knight Phantom not started.',recovery_naga=dict(local_start=START,live_remote_start=START,working_tree_start='CLEAN',divergence='0/0',newer_work=False,restarted_research=False));decision['checkpoints']['R2f3-lich-complete']=START;decision['checkpoints'][CP]='Self: exact SHA reported after push/live verification.';write_json(OUT/'research-decision.json',decision)
    lines=['# R2f4 — NAGA_SEMANTIC_REVIEW_COMPLETE','','Installed Twilight Forest4.8.3345 / Minecraft1.21.1 / NeoForge21.1.244. Static native review only. Frosted and Lich remain immutable; whole Twilight PARTIAL.','',f"{len(E)} reviewed package drafts, {len(P)} delivery cases; REVIEW_REQUIRED0; no custom Naga DamageType. Combined Twilight drafts: {len(draft['effects'])} packages / {len(draft['paths'])} cases; zero final promotions.",'','## Combat semantics','']
    for k,v in facts.items():lines.extend(['### '+k.replace('_',' ').capitalize(),'',v,''])
    lines.extend(['## Package classification','','| Package | Primary classification |','|---|---|'])
    for e in E:lines.append('| '+e['display_name']+' | '+e['primary_classification']+' |')
    lines.extend(['','## Source/delivery cases','','| Case | Source |','|---|---|'])
    for p in P:lines.append('| '+p['id'].split(':')[-1]+' | '+p['source']+' |')
    lines.extend(['','Each saved case includes native predicates, parameters and future controls in [machine-readable section](semantic-sections/twilightforest-naga.json). No runtime fixtures were executed. Native mob_attack requests are ordinary armor/Resistance/protection/absorption/cooldown damage; generic2 recoil is ownerless, armor-bypassing and no-knockback. Explicit push callbacks remain separate.','', '## Exclusions and evidence',''])
    lines += ['- '+x for x in section['exclusions']]
    lines.extend(['',section['compatibility_scope'],'','[Native evidence](native-evidence/twilight-naga.json), [raw comparison](vanilla-evidence/twilight-naga.json), [exact loader](reference-evidence/twilight-naga-244.json), [integrity validation](twilightforest-naga-integrity.json), [full checkpoint validation](r2f4-naga-validation.json).','', 'Exact next task: '+NEXT,''])
    (OUT/'twilightforest-naga-review.md').write_text('\n'.join(lines),encoding='utf-8')
    print(json.dumps(section['counts']))

if __name__=='__main__':build()
