"""Native portal resource, lightning, transport and configured spawn semantics."""
from catalog_common import *
from collect_twilight_portals import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    P='block/TFPortalBlock';T='world/TFTeleporter';C='world/TeleporterCache';E='events/ProgressionEvents';A='events/CapabilityEvents';N='world/NoReturnTeleporter';V='components/entity/TFPortalAttachment'
    facts={
      'authority':'Exact TF4.8.3345, raw Minecraft1.21.1 PortalProcessor and actual NeoForge21.1.244 references. Static only; no executed portal/boss fixture, no L2/Stage/production/Phase6/7 change. Native terrain creation, transport and genuine lightning are distinct mechanics. All40 custom Twilight DamageTypes remain USED; this subset introduces a vanilla lightning source path, not a41st custom type.',
      'configuration':'Pinned installed common config: newPlayersSpawnInTF=false, portalForNewPlayer=false; originDimension=minecraft:overworld, allowPortalsInOtherDimensions=false, portalCreationPermission=0, disablePortalCreation=false, checkPortalPlacement=true, destructivePortalLightning=true, shouldReturnPortalBeUsable=true, portalUnlockedByAdvancement empty, maxPortalSize64. Alternative configured branches are reviewed native paths, not claimed active defaults. Actual world gamerules remain unknown. Registered playersTfPortalDefaultDelay60 and playersTfPortalCreativeDelay1 are defaults. TFConfig rebake clears cached advancement lock, but TFPortalBlock cachedOriginDimension is initialized once and not cleared by that method.',
      'creation_producer':'Registered PlayerTick.Post ServerPlayer+ServerLevel: !disablePortalCreation, tickCount modulus(checkPortalPlacement?20:100)==0 and profile permission>=configuredpermission. Radius is configuredpermission>=3?4:32 around player AABB. Dimension must equal configuredorigin, exact standard Twilight destination, or allowOther=true. FIRST queried ItemEntity with PORTAL_ACTIVATOR stack, canFormPortal at its block position, and Objects.equals(item.getOwner(),player) is selected. Actual ItemEntity.getOwner resolves cached/UUID thrower, not pickup target stored as Owner. Native player toss with traceItem=true supplies thrower; item-toss/add hooks remain. No arbitrary nearby ownerless catalyst or pickup-ownership substitution.',
      'advancement_lock':'Creation and portal contact each require optional valid configured advancement for noncreative/nonspectator ServerPlayer. Lazy TFConfig lookup validates resource against actual player advancement registry; invalid/missing configured entry logs and clears config string, leaving null; a missing holder at later gate also does not reject. Static playersNotified set suppresses repeated missing-advancement toast, no serialization/removal in portal class. This is separate from tfEnforcedProgression and deeper structure gates. Config snapshot has empty lock.',
      'pool_validation':'canFormPortal accepts actual PORTAL_POOL block tag (installed minecraft:water) OR this portal block with DISALLOW_RETURNtrue. Starting block requires below sturdyUP. Recursive horizontal flood fill requires exact SAME BlockState identity as initial poolBlock and below sturdyUP; edge requires PORTAL_EDGE (farmland/dirt_path/#minecraft:dirt) with above PORTAL_DECO. Portal decoration tag includes installed plants and native flower/leaf/sapling/crop tags, not an inferred flower-only rule. Pool visited map prevents repeats; entry increments size, maxconfigured64, minimum4. Sturdy checks pass current pool position rather than below position to isFaceSturdy. Initial state equality disallows mixed water states despite same block type. Portal activator tag is #c:gems/diamond, not hardcoded one item.',
      'creation_commit':'Only when !checkPortalPlacement does tryToCreatePortal call isSafeAround on CURRENT level and catalyst entity with progressiongamerule; failure sends optionalplayer unsafe message and returnsfalse. NonPlayer catalyst is biome-safe under Restriction helper, though TF structure/worldborder gates still apply. Defaulttrue skips this precheck. On valid pool: shrink catalyst1, causeLightning, then replace each maptrue pool position with default usable portal usingflag2; ignore add/write results and returntrue. Successful helper return triggers MADE_TF_PORTAL criterion. No item-cost refund on creative or write failure in this dropped-item path, no break event or explosion terrain operation. Lightning is requested BEFORE pool writes.',
      'lightning_dispatch':'causeLightning makes real native LightningBolt at block center X/Z, blockY; calls setVisualOnly(destructive), addFreshEntity (return ignored). When destructive=true and ServerLevel, independently queries Entity within AABB(blockpos).inflate3, default native query excludes spectators, then if !EventHooks.onEntityStruckByLightning invokes victim.thunderHit(level,bolt). No line of sight, team, owner or hurt-success gate. This manual query can include the newly added bolt and dropped catalyst; actual subtype callbacks decide effects. A canceled bolt add does not suppress these manual calls. No cause/owner is assigned to bolt.',
      'lightning_modes':'With installed destructive=true: bolt is visualOnly, so automatic entity strikes and spawnFire are suppressed, but the explicit nearby thunderHit calls still run. With destructive=false: no manual query, bolt is NOT visualOnly and normal native lifetime ticks can strike alive entities in bolt-relative X/Z+-3,Y-3..Y+9; initialNormal/Hard spawnFire4 and laterflash spawnFire0 require native doFireTick. Every strike retains loader veto. VisualOnly still powers rods, clears copper and emits LIGHTNING_STRIKE at life2, as protected UrGhast review proved. No claim that false option eliminates damage/fire. Native LightningBolt is noSave; life/flashes/add admission remain native.',
      'lightning_damage':'Native Entity.thunderHit first increments remainingFireTicks by1; if resultingtimer==0 requests ignite8seconds, then hurt(damageSources.lightningBolt(),bolt.getDamage()) with return discarded. Default exact NeoForge bolt damage5 (custom hooks could alter bolt state). Native minecraft:lightning_bolt cached source has direct=null,causing=null,position=null, exhaustion.1; scaling when_caused_by_living_non_player does not scale an ownerless source. Tags: minecraft:is_lightning,no_knockback,panic_causes,panic_environmental_causes; exact loader neoforge:is_environment. Not IS_FIRE,magic,physical,projectile,explosion or armor/shield bypass. Normal armor, Resistance/protection, absorption, cooldown/invulnerability and incoming hooks remain; native directional shield lacks source position. Fire Resistance is not immunity to this lightning request, though later fire remains fire. Fire timer update is independent of hurt result. ArmorStand/ItemEntity and thunderHit overrides retain native subtype behavior; conversions/powered state are not fabricated generic damage. No direct HP subtraction.',
      'portal_block':'Portal default DISALLOW_RETURNfalse (property is_one_way). Outline13/16high. getCollisionShape override returns empty whenusable,13/16high whenoneway, even though registered noCollission; native BlockState collision dispatch/cache calls override. Registered hardness-1,light11,noLoot/noOcclusion,pistonBLOCK. Fluid state is flowingwater amount1; canPlaceLiquid/placeLiquid false. neighborChanged requires belowsturdyUP and eachhorizontal neighbor PORTAL_EDGE or exactsameBlockState; failure replaces block with WATER flag3. Continued survival does not require decoration above. One-way state can be reactivated through native catalyst pool validation; do not directly flip flags in a fixture.',
      'contact_processor':'entityInside acts ONLY when state==defaultBlockState. After optional player advancement gate, entity.canUsePortal(false) then setAsInsidePortal and set overlay attachment inPortal=true. Native base eligibility is alive&&!passenger; Living additionally !sleeping. Vehicle may enter and native transfer handles passengers. Existing portal cooldown resets full cooldown on contact instead of opening processor. Otherwise same Portal identity updates position/insidebit or creates PortalProcessor. Server handlePortal first decrements cooldown, then processes; only qualifying insidebit && canChange increments time. Exact processor compares portalTime++>=delay, so from0 default60 means61 qualifying process calls, configuredcreative1 means2, nonplayer0 means1. Outside callback decays time by4 clamp0; expires<=0. These are processing counts, not measured elapsed runtime ticks.',
      'native_transition':'Portal delay for Player uses abilities.invulnerable to choose gamerule, not isCreative; nonPlayer0. On readiness Entity sets native cooldown BEFORE asking destination; missing destination or travel veto can therefore still leave cooldown. Native Player cooldown10; baseEntity firstpassengerServerPlayer uses that delay, otherwise300. TF destination: if currentdimension is standardTF go cachedorigin, otherwise standardTF; missingserverlevelnull. Coordinate scale uses actual dimension ratio and destination worldborder clamp. Installed TF coordinate_scale.125 gives Overworld->TF8x and reverse1/8 before further routing. Native enabled-level/canChangeDimensions/onTravelToDimension gates remain; TF terrain creation can precede final travel veto.',
      'transport_state':'TF constructs DimensionTransition with Vec3.ZERO and current yaw/pitch plus PLACE_PORTAL_TICKET. Native Entity.changeDimension honors travel veto, handles passenger transfer and native recreate/restore/remove/add, applies requested zero speed; actual base move uses restored entity pitch. Exact ServerPlayer override teleports/syncs current player, effects and attachments and does not apply transition.speed via setDeltaMovement in this method. Do not claim every player velocity is reset. No TF HP/SHP heal/subtraction. PortalCooldown is native saved NBT; PortalProcessor is not normal NBT but restoreFrom copies it during entity transfer. Native type-specific travel eligibility and lifecycle remain.',
      'cache_existing':'TeleporterCache is shared Overworld SavedData twilightforest_teleporter_cache, keyed destination dimension then source entity blockX/Z column, not player/UUID. Values targetpos,lasttime; save/load full maps; add/remove markdirty, access timestamp update alone does not. No age expiry in class. Existing cache accepts any TF portal block includingoneway, rejects missingblock and removes entry; invalidcached path returnsnull for creation rather than fresh search in that method. Cachemiss searches accessible loaded chunks within initial X/Z+-200 and nativeworldborder, allY from min(worldmax-1,highestsection+15)down, closest3D candidate with shrinkingradiusceil(sqrt(distance²)); uses lowestvertical portal. On newmatch sourcepool recursive validator return ignored, maps true cells into cache and adds PORTAL ticket3. Return side chooses random horizontal boundary with fullUPcollision face and emptycollisionabove, elseportal itself, then safePosInColumn.',
      'safe_routing':'Safety only restricts standardTF: outsideborder OR progressionenabled and player biome restriction missing advancement OR any LANDMARK structure reference in chunk. NonTF returnssafe; nonPlayer has no biome restriction. isSafeAround tests center and4cardinal offsets16. Unsafe destinations scan DiagonalSpiral arguments(radius128,spacing16,chunk-coordinate center)->LegacyNearestCenter, then XZQuadrant arguments128,16. Iterator implementations differ: Diagonal divides radius byspacing; XZ stores128 unscaled and emits offsets multiplied16 (up to2048). On a safe inner candidate, code returns biomeCenter rather than testedposInBiome. Ifnone, falls backoriginalpos. safePosInColumn returnsposition when entity-size AABB noCollision; otherwise setsY to heightmap at roundedX/Z without second collision check. No guaranteed hazard-free exit is inferred.',
      'portal_search':'If no existing portal, createPosition reroutes then makePortal; loadSurroundingArea requests5x5chunks using floor(pos.x)>>4 and floor(pos.y)>>4 for Z (literalY). Searches X/Z+-16 with allY, weighted distance uses targetY*factor (Overworld2,else.5). Tries existingportal, idealspot, okay, fallbackinair, then heightmap at originalentityX/Z timesnativehorizontalScale. Ideal4x4x6 excludes FEATURES_CANNOT_REPLACE, requiresDIRTbase/replacableupper; okay allows solid/liquidbase; fallback allows anybase except protectedtag and still replaceableupper. Finalrandomfallback lacks those tests. Native helper search does not repeat border check per candidate. These exact branches are reviewed behavior, not fixes.',
      'portal_construction':'makePortalAt writes12grassperimeter; inner4below becomeDIRT only if DIRT/REPLACEABLE/AIR; writes2x2portal whose DISALLOW_RETURN=locked||!shouldReturnPortalBeUsable. Removes4x4x5above withoutdrops, places12 random GENERATED_PORTAL_DECO (17installedchoices; fallbackSHORT_GRASS), ignores writes/removals. No BreakEvent/directHP/itemcost in generated-destination helper. Reverse cache links added for4newportalcolumns only if source portal found. createTransition finally uses heightmapcenter transition if other transition remainsnull. Separate native worldgen/block callbacks may run; no invented explosion/damage source.',
      'configured_spawn':'Registered login data-fixes legacy PlayerPersisted twilightforest_banished flag then, if BANISHED attachment absent, calls newSpawn; respawn without respawnPosition calls it too. If newPlayersSpawnInTF and TFlevel exists: computes heightmap at currentplayerblock; portalForNewPlayerSpawn true calls createTransition(forcedEntrytrue), else NoReturnTeleporter. changeDimension return is ignored, THEN sets forced TFrespawn at originalnewDefaultSpawn (not final reroutedposition) and BANISHED Unit. Travel veto therefore does not gate these writes. Existing portal selection can bypass new one-way construction even with forcedEntrytrue. BANISHED attachment serialized/copyOnDeath. Installed newPlayersSpawnInTF=false, so this alternative is inactive in snapshot.',
      'no_return_spawn':'NoReturnTeleporter reuses safe routing and same load helper; finds existingportal thenideal thenokay, returns safe center of spot.above; ifnone uses originalentity X/Z*horizontalScale and Y*yFactor+2 then safePosInColumn. Creates no portal and no new cache link; returns standard native transition. Configured source is actual CapabilityEvents, not arbitrary direct teleport call.',
      'overlay_exclusion':'TF_PORTAL_COOLDOWN attachment name is not transport authority: builder has no serialize/sync/copyOnDeath. PlayerTick.Post ticks it. inPortal increments overlaytimer cap60, checks current/belowportal only when !isInWall; otherwise outside timer>0 subtracts2 (odd value canreach-1). ClientLocalPlayer insideportal closes nonpause/nonDeath GUI, closes container ifnecessary, clearsinsidebit. This is presentation/input behavior, not the native PortalProcessor timer or damage. Static playersNotified/toast and particles are likewise not HP mechanics.',
      'compatibility':'DIRECT_SOURCE_SPECIFIC: native portal tags/resources, actual TF advancement/config/structure gates and registered first-spawn attachment callbacks. GENERIC_CONDITIONAL_PRESENT: native ItemToss/entity-add/lightning-strike/dimension-travel hooks, native subtype lightning callbacks, collision and criteria. Common #c:gems/diamond is a tag extension point, not proof every mod diamond is loaded. NONE_PROVEN: this inspected portal logic has no direct Tensura/L2/Curios source mapping. UNKNOWN: pack-wide hook outcomes, actualworldgamerules and runtime transport/collision; no static compatibility certification.'
    }
    nxt='Continue remaining native Builder/Antibuilder and cloud/snow/control blocks, remaining event callbacks/nested ASM, compatibility attribution and global source exclusions. Then R2f8 whole remaining-content closure and final Twilight dedup/promotion. All40 types already USED; IceAndFire only after Twilight COMPLETE pushed/live-verified. Static only.'
    data=dict(slug='portals',checkpoint_short='r2f8ab',checkpoint='R2f8ab-portals-complete',decision='TWILIGHT_PORTALS_SEMANTIC_REVIEW_COMPLETE',starting_sha=git('rev-parse','HEAD').strip(),previous_checkpoint='R2f8aa-vanishing-doors-complete',previous_draft='partial-drafts/twilightforest-r2f8aa-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=0,full_classes=FULL,limited_classes={E:['registered actual dropped-item portal creation; prior structure/biome review reused'],A:['portal overlay tick, login/respawn/configured spawn and legacy migration; prior shield/yeti/fan reviewed separately'],'config/TFConfig':['portal static config/cache rebake'],'config/TFCommonConfig':['portal config definitions'],'util/Restriction':['actual player-only biome admission'],'init/TFDimension':['actual destination and dimension keys']},registration_classes=['init/TFBlocks','init/TFDataAttachments','init/TFGameRules','init/TFAdvancements'],closure_checklist=['actual_catalyst_thrower','native_toss_and_add_hooks','advancement_config_scope','pool_exact_state_and_bounds','creation_cost_lightning_write_order','true_manual_false_automatic_lightning','native_lightning_source_tags_defenses','oneway_collision_override','processor_distinctfromoverlay','native_postincrement_delay','cooldown_before_destination','travel_veto_and_subtypes','native_cache_persistence','destination_safety_actual_limits','exact_search_iterators','native_portal_terrain_construction','configured_spawn_return_ignored','banished_persistence','noReturn_actualproducer','compat_attribution'],compatibility_scope=facts['compatibility'],current_scope='Prior Twilight plus native portal creation/resource, real lightning delivery, native portal transport, destination terrain/search/cache and configured initial/respawn entry. Whole Twilight PARTIAL zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=40,new_used_profiles=0,reviewed_profiles_after=40,remaining_profiles=0,remaining_disposition='None:40 custom USED. Vanilla lightning delivery is separate, not another custom declaration. Wider control/event/ASM/source closure remains.'))
    def pkg(k,title,kind,keys,cs,nums,gates,rel,source,controls):
        eid='twilightforest:'+k;data['packages'].append(dict(id=eid,display_name=title,owner=k,primary_classification=kind,facts=keys,classes=cs,parameters=nums,gates=gates,relation=rel,primary_test_source=source,alternate_sources=controls));return eid
    create=pkg('twilight_portal_native_creation','Twilight Portal native pool/catalyst creation','CUSTOM_RESOURCE',['configuration','creation_producer','advancement_lock','pool_validation','creation_commit'],[P,E],{'default_period':20,'alternative_period':100,'normal_range':32,'operator_config_range':4,'minimum_pool':4,'default_maximum_pool':64,'catalyst_cost':1},['configuredpermission/dimension','actualthrower','taggedcatalyst','exactstatepool','border/support','optionaladvancement'],'Custom resource/terrain creation from native dropped-item producer.','Genuine player-tossed diamond-tag catalyst into valid pool',['ownerless','pickupowner','mixedstates','minmaxsize','config','advancement','writeveto'])
    lightning=pkg('twilight_portal_native_lightning','Portal native lightning delivery modes','VANILLA_LIKE_EXTENDED',['configuration','creation_commit','lightning_dispatch','lightning_modes','lightning_damage'],[P],{'default_damage_request':5,'manual_aabb_inflation':3,'native_ignite_seconds':8},['actualcreatedportal','configvisualflag','nativelightningveto','subtypethunderHit','nativehurt'],'Native lightning/thunderHit with custom manual area delivery and config mode; no new source type.','Actual successful portal creation with installed lightning configuration',['configfalse','boltaddveto','strikeveto','armor','Resistance','firetimer','subtypes'])
    transport=pkg('twilight_portal_native_transport','Twilight Portal native contact and transport','CUSTOM_CONTROL',['portal_block','advancement_lock','contact_processor','native_transition','transport_state','overlay_exclusion'],[P,V],{'outline_height':.8125,'default_delay':60,'creative_delay':1,'ordinary_qualifying_calls':61,'creative_qualifying_calls':2,'outside_decay':4,'player_cooldown':10},['exactdefaultstate','nativecanUsePortal','optionaladvancement','processor','enabledlevel','travelhook'],'Custom dimension destination delivered through native PortalProcessor and transport.','Genuine living/player/entity entry into usable native portal',['oneway','passenger','sleep','cooldown','nativeveto','nonplayer','configdelay'])
    dest=pkg('twilight_portal_destination_terrain','Twilight Portal destination routing and terrain','CUSTOM_CONTROL',['cache_existing','safe_routing','portal_search','portal_construction','native_transition'],[T,C],{'initial_existing_search_radius':200,'new_spot_radius':16,'safety_cardinal_offset':16,'generated_inner_blocks':4,'generated_clear_volume':80,'TF_coordinate_scale':.125},['actualtransition','cache/loadedchunks','nativebiome/structurechecks','searchfallback','nativecollision'],'Custom routing/terrain over native saved data/chunks/collision.','Actual portal transit to cached or newly generated destination',['invalidcache','unsafe','restrictedchunk','fallback','onewayreturn','reload'])
    spawn=pkg('twilight_configured_spawn_transport','Configured Twilight initial/respawn transport','CUSTOM_CONTROL',['configuration','configured_spawn','no_return_spawn','transport_state'],[A,N,T],{},['actualregisteredlogin/respawn','configurednewplayers','TFlevelexists','nativechangeDimension'],'Conditional native player transport with saved respawn/attachment side effects.','Actual new player login with native config branch enabled in future fixture',['noflag','legacyflag','respawnposition','portal/noportal','travelveto','returncache'])
    def path(k,title,keys,ids,cs,labels,controls):data['paths'].append(dict(id='twilightforest:portals_path:'+k,source=title,facts=keys,effect_ids=ids,classes=cs,labels=labels,setup=title+' through genuine native item/block/event/portal delivery; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('owned_catalyst','Native player-tossed portal catalyst',['creation_producer','pool_validation'],[create],[E,P],['ACTIVE_ITEM','ENVIRONMENT'],['actualthrower','diamondtag','ItemToss','firstqualifying']),
      ('owner_controls','Ownerless/different thrower/pickup target controls',['creation_producer'],[create],[E],['ENVIRONMENT'],['getOwnerNOTpickupOwner','droppedentityreload','merge']),
      ('permission','Native config permission/dimension/cadence gates',['configuration','creation_producer'],[create],[E],['ENVIRONMENT'],['permission0or3','20or100','4or32','allowOther']),
      ('advancement','Native optional advancement lock',['advancement_lock'],[create,transport],[E,P],['ENVIRONMENT'],['validmissing','invalidconfig','creative','spectator','toastonce']),
      ('pool','Native connected pool flood fill',['pool_validation'],[create],[P],['ENVIRONMENT'],['exactstates','belowsturdy','edge/deco','min4','max64']),
      ('pool_precheck','Native disabled-checkPortalPlacement precheck',['creation_commit','safe_routing'],[create],[P,T],['ENVIRONMENT'],['currentdimension','catalystnonPlayer','structuregate','failuremessage']),
      ('creation_cost','Native catalyst cost and write ordering',['creation_commit'],[create,lightning],[P,E],['ENVIRONMENT'],['shrink1','lightningbeforewrites','ignoredreturns','actualcriterion']),
      ('lightning_true','Installed true-config manual lightning strikes',['lightning_dispatch','lightning_modes'],[lightning],[P],['AOE','ENVIRONMENT'],['visualOnlybolt','manualinflate3','NO_SPECTATORS','noLOS']),
      ('lightning_false','Alternative false-config automatic native lightning',['lightning_modes'],[lightning],[P],['AOE','ENVIRONMENT'],['realnativebolt','automaticbounds','lifeflashes','doFireTick']),
      ('lightning_addveto','Native lightning add veto versus manual strike',['lightning_dispatch'],[lightning],[P],['AOE','ENVIRONMENT'],['addreturnignored','truebranchmanualstillruns','strikeeventveto']),
      ('lightning_hp','Native lightning request and real mitigation',['lightning_damage'],[lightning],[P],['ENVIRONMENT'],['ownerless5','armor','Resistance','protection','absorption','cooldown','shieldgeometry']),
      ('lightning_fire','Native thunderHit fire timer independent from hurt',['lightning_damage'],[lightning],[P],['ENVIRONMENT'],['incrementfirst','igniteonlytimerzero','FireResistance','hurtfalse']),
      ('lightning_subtype','Native thunderHit recipient overrides',['lightning_damage'],[lightning],[P],['ENVIRONMENT'],['ItemEntity','ArmorStand','charged/conversionnative','noinventedoverride']),
      ('lightning_world','Native visual lightning rod/copper world callbacks',['lightning_modes'],[lightning],[P],['ENVIRONMENT'],['life2','rodredstone','copper','gameevent','noSave']),
      ('usable_contact','Native usable portal entry',['portal_block','contact_processor'],[transport],[P],['ENVIRONMENT'],['defaultstateidentity','nativecanUsePortal','nooverlaytimerbypass']),
      ('oneway','Native one-way barrier and catalyst reactivation',['portal_block','pool_validation'],[transport,create],[P],['ENVIRONMENT'],['collision13/16','contactreject','nativepoolreactivation']),
      ('survival','Native portal support/border failure',['portal_block'],[transport],[P],['ENVIRONMENT'],['sameBlockState','noflowercontinuationgate','waterreplacement']),
      ('processor','Native postincrement portal transition delay',['contact_processor','native_transition'],[transport],[P],['ENVIRONMENT'],['61/2/1eligiblecalls','outside4decay','worldgamerules']),
      ('eligibility','Native portal rider/sleep/dead eligibility',['contact_processor'],[transport],[P],['ENVIRONMENT'],['passengerreject','vehiclepassengers','Livingnotsleeping','dead']),
      ('cooldown','Native cooldown before destination/travel',['native_transition','contact_processor'],[transport],[P],['ENVIRONMENT'],['10Player','300base','contactrefresh','null/vetocooldown']),
      ('transition','Native entity/player actual dimension transfer',['native_transition','transport_state'],[transport],[P,T],['ENVIRONMENT'],['enabledlevel','travelveto','copy/persistence','Playervelocitydistinct']),
      ('scale','Native destination scale and origin cache',['configuration','native_transition'],[transport,dest],[P],['ENVIRONMENT'],['TF8x','return1/8','worldborderclamp','cachedoriginrebake']),
      ('cached','Actual shared saved portal cache',['cache_existing'],[dest],[T,C],['ENVIRONMENT'],['dimension/sourcecolumn','anyportalstate','invalidremoval','reload','nostaleexpiry']),
      ('existing','Native accessible existing portal search and exit',['cache_existing'],[dest],[T],['ENVIRONMENT'],['loadedchunks','3Ddistance','dynamicradius','randomvalidborder']),
      ('reroute','Native progression/structure destination reroute',['safe_routing'],[dest],[T],['ENVIRONMENT'],['Playeronlybiome','alllandmarkreferences','centerplus16','iterators','returnedcenter']),
      ('collision','Native exit collision and heightmap fallback',['safe_routing'],[dest],[T],['ENVIRONMENT'],['entityAABB','roundedcolumn','nosecondcheck','noguaranteedsafety']),
      ('search_new','Native new-portal search fallbacks',['portal_search'],[dest],[T],['ENVIRONMENT'],['YusedaschunkZ','ideal','okay','airfallback','finalheightmap']),
      ('construct','Native destination portal terrain writes',['portal_construction'],[dest],[T],['ENVIRONMENT'],['12grass','4portal','80clear','17deco','noBreakEvent']),
      ('return_policy','Native unusable return portal policy',['portal_construction'],[dest,transport],[T,P],['ENVIRONMENT'],['forcedEntry','returnusablefalse','reactivation','existingportalexception']),
      ('login','Native configured first login transport',['configured_spawn','configuration'],[spawn],[A,T,N],['OTHER'],['snapshotdisabled','BANISHEDabsent','TFlevel','genuineevent']),
      ('respawn','Native configured missing-respawn-position entry',['configured_spawn'],[spawn],[A],['OTHER'],['hasrespawnposition','nativeevent','forcedrespawn']),
      ('spawn_return','Configured portal-enabled spawn path',['configured_spawn','portal_construction'],[spawn,dest],[A,T],['ENVIRONMENT'],['forcedEntrytrue','cachedexisting','newoneway']),
      ('spawn_noportal','Configured NoReturn native transport',['no_return_spawn','configured_spawn'],[spawn],[A,N],['OTHER'],['noportalwrites','existing/ideal/okay','fallbackscaledposition']),
      ('spawn_veto','Native travel veto versus respawn/BANISHED writes',['configured_spawn','transport_state'],[spawn],[A],['OTHER'],['ignoredchangeDimensionreturn','unadjustedrespawnpoint','noHP']),
      ('spawn_save','Native BANISHED persistence and legacy migration',['configured_spawn'],[spawn],[A],['OTHER'],['Unitserialize','copyOnDeath','PlayerPersistedmigration']),
      ('overlay','Native portal presentation attachment control',['overlay_exclusion','contact_processor'],[transport],[V,A],['OTHER'],['nottransporttimer','noattachmentserialization','GUIClose','oddnegative'])
    ]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-portals-caller-scan.json','twilightforest-portals-config-snapshot.json','semantic-sections/twilightforest-structure-gates.json','semantic-sections/twilightforest-hydra-urghast.json']
    data['exclusions']=['Portal overlay attachment is separate from actual native PortalProcessor transport; no extra damage or native delay inferred.','Protected Ur visual lightning rod/copper semantics reused; new mechanic is real portal manual/automatic lightning delivery.','40custom DamageTypes unchanged; vanilla lightning_bolt has native source/recipient admission.','Configured new-player spawn is disabled in installed snapshot but real conditional source reviewed.','Remaining Builder/Antibuilder/cloud/control/events/ASM/source closure is unfinished ordinary work, not REVIEW_REQUIRED.']
    data['fixture_groups']=['Actual player-owned dropped catalyst in valid/invalid native pools with config/advancement/cost/permission controls.','Real portal lightning true/false modes with add/strike veto, source identity, mitigation and native subtype/fire/world callbacks.','Native PortalProcessor contact/eligibility/delay/cooldown/travel and actual entity/player lifecycle controls.','Genuine cached/generated destinations with dimensions/border/progression/structure/collision/fallback/saved-data controls.','Actual configured login/respawn events with portal/noportal, travel-veto, savedrespawn/BANISHED and legacy controls; snapshotdisabled acknowledged.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-portals.json',data);assemble('twilightforest-portals.json')
if __name__=='__main__':build()
