"""Fortification and Lifedrain native contracts; preserve prior scepter work."""
from catalog_common import *
from collect_twilight_scepter_payloads import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed TF4.8.3345, raw Minecraft1.21.1 and exact NeoForge21.1.244. Static source review only. Damage request, final HP, execution/removal, motion, shield count and durability are separate. Protected Lich boss shield, Twilight bolt and R2f8i recharge contracts are reused unchanged. No runtime/L2/Stage/production or balancing fix.',
      'fortification_use':'Native Fortification Scepter use fails damage==max && !instabuild. On server sets temporary shields to5 (not adds; permanent count preserved), then noncreative-material cost1 through protected nonbreaking helper. Capacity9. Sound and SUCCESS; if !Player.isCreative adds native item cooldown1200. isCreative and instabuild are distinct predicates. Ordinary ServerPlayerGameMode.useItem rejects spectator/cooldown before ItemStack.use. No Crown use-cost discount, direction check or HP operation.',
      'shield_counts':'Attachment defaults temporary0/permanent0/timer240. setShields clamps selected count0..115; temporary set always resets timer. addShields clamps integer addition0..115; temporary timer resets only if old temporary<=0. Addition is int before cast to long, so extreme administrative amount can overflow. Other count preserved. Ordinary mutators allow115 each/230 total; two-int codec constructor only clamps negative to0, no upper115 clamp. Sum uses int. breakShield prefers temporary, decrement+timer240; otherwise permanent decremented. No HP write. Non-expired ServerPlayer break awards statistic. Sound/setData occur even zero if method directly called, but native event/timer callers guard positive counts.',
      'shield_producers':'All installed-TF instruction census: FortificationWand.use sets5 temporary; ShieldCommand set/add are the other actual producers. Permission2 native /twilightforest shield <single entity> set|add <int amount> [temp boolean], aliases tf/tffeature, default temp=true. Only LivingEntity receives mutation; command returns1 even other target. Permanent shields therefore have a legitimate administrative path, not a proven survival producer. Attachment event and timer break existing resources. Lich boss shield count is unrelated.',
      'shield_admission':'CapabilityEvents setup installs ordinary LivingIncomingDamageEvent listener. On server and source NOT BYPASSES_ARMOR, obtains attachment; if total>0, if invulnerableTime<=0 breaks one (temporary first), particles, sets invulnerableTime20; then always cancels incoming event, including the last-shield hit and positive invulnerableTime hits that spend no shield. No amount threshold, facing, held shield, armor, attacker, direct entity, source position or player predicate. BYPASSES_SHIELD alone does not bypass this attachment; BYPASSES_ARMOR does. Particle source/owner lookups affect visuals only. Native incoming event precedes ordinary shield blocking, cooldown and final mitigation, so charge consumption does not require an otherwise-successful HP hit. Earlier native immunity/client/dead/fire-resistance rejection and Player admission/difficulty still precede it. Listener registration does not establish order against every other mod; existing cancellation/event behavior remains native. Cancellation yields false hurt and no final HP damage in this native path.',
      'shield_timer':'EntityTick.Post: server Living with existing attachment -> tick. Temporary>0 and nonPlayer OR !Player.abilities.invulnerable. At timer<=0 breaks one expired shield/reset240; else decrements unless HEAD MysticCrown AND tickCount%3==0. Normal fresh240 lasts240 decrements plus next eligible callback to break; Crown skips one in three decrements, phase-dependent duration, not a universal fixed wall-clock interval. Damage break also resets timer. Permanent never expires. Invulnerable Player pauses temporary ticking; world unload has no offline countdown.',
      'shield_persistence':'Registered serialized/synced codec stores only temporary_shields/permanent_shields, not timer. Exact244 Entity save/load uses neoforge:attachments; constructor resets timer240 on decode. AttachmentType default copy serializes/decodes, so eligible copies also reset timer. No copyOnDeath configured: Player death Clone excludes it even keepInventory; non-death Clone copies it. Native living conversion uses copyEntityAttachments(...,true), therefore excludes this attachment. This is count persistence, not preserved remaining duration. Native sync transports both counts; no owner/master shared-resource link.',
      'drain_use':'Lifedrain capacity99/shared resource protected. use fails fully damaged&&!instabuild, else starts native hand use. onUseTick stops on damage==max even creative. Use duration72000, BOW animation; native updateUsingItem runs EventHooks.onItemUseTick then positive-remaining callback, then decrements count. Attempt when remaining count%5==0. canContinueUsing same item ignores component changes; actual hand stack continuity/native use events remain. No bespoke cooldown, physical hit, projectile spawn, ammo, enchantment requirement or damage-helper call. Native recipient cooldown remains, so every5 attempt is not every5 HP loss.',
      'drain_selection':'getPlayerLookTarget uses eye/view segment20 and casterBB expanded view*20 inflated1, native level.getEntities excluding caster. Candidates only isPickable, inflated getPickRadius AABB segment clip. No block ray/LOS, distance attribute, friendship or boss prefilter. Chooses nearest positive intercept with hitDist=0 sentinel; origin-inside candidate sets0, which a later candidate can replace (list order/inside-zero quirk). Final selected entity must Living and not ArmorStand; a selected nonliving/ArmorStand prevents this attempt, no rescan. Living native isPickable excludes removed; dead checks for particles do not add a global pre-hurt alive gate. No claim of universally nearest selection when origin is inside boxes.',
      'drain_source':'Only actual LIFEDRAIN instruction caller is LifedrainScepterItem.onUseTick. Initial native target.hurt(request1) with direct=causing=caster LivingEntity, position from direct entity. Type exhaustion0/scaling when_caused_by_living_non_player. Tags exactly bypasses_armor, bypasses_shield, bypasses_wolf_armor, is_projectile, neoforge:is_magic. It is tagged projectile without a projectile entity. Native Resistance/protection (including applicable projectile protection), absorption, invulnerability, cooldown, PvP/source/event admission remain; no bypass resistance/enchantments/cooldown/invulnerability. Player caster avoids nonPlayer difficulty scaling. Fortification skipped by armor bypass. No fabricated source or guaranteed1 HP loss.',
      'drain_branch':'Outer secondary branch requires initial hurt true and server; true does not guarantee positive HP loss (absorption/events). Tests target CURRENT HP<=1 && !c:bosses AFTER initial request. Low nonboss takes execution branch; otherwise native Slowness20/amp2 (SlownessIII, -.45 base movement attribute) and if remaining count%10==0 caster.heal1, then Player FoodData.eat(1,.1). Food native add clamps food0..20, saturation0..food, giving up to1 food/.2 saturation. Heal and food independent of effect admission/heal return and hunger/fullHP need. No effect causer passed. c:bosses prevents execution only, not damage/slow/restore/motion. Low nonboss branch does not give slow/heal/food. Cadence plus native recipient cooldown can suppress later healing; no constant regeneration claim.',
      'drain_execution':'Within true initial hurt/server/lowHP/nonboss: if target lacks LIFEDRAIN_DROPS_NO_FLESH and caster Player, evaluates native bonus loot at target eye with target/source and caster Player attribution, spawns items and shatter particles. Native data bonus is uniform0..2 rotten flesh; no extra damage/explosion from visual big shatter. Target Mob spawnAnim; optional reflected native death sound. Then only if target !isDeadOrDying: Player gets a second same-type request Float.MAX_VALUE, ignored return, ordinary admission/totem can prevent death. NonPlayer instead native die(source) followed unconditionally by discard(); no second hurt/HP subtraction. die runs native Death hook, but ignored/canceled death does not prevent following discard. This removal can occur while HP remains positive and bypasses a second mitigation/totem check; it is existing native code, not an authorized compatibility implementation. If first request already killed, bonus/sound still run but extra die/discard skipped. NO_FLESH suppresses only bonus/shatter, not execution. Native bonus loot is independent of ordinary death loot rules/hook result; this method does not check doMobLoot before bonus.',
      'drain_motion':'After and independent of initial hurt-success branch: server && target.currentHP<=caster.currentHP -> target.setDeltaMovement(0,.15,0). Replaces XYZ, not additive push, with no knockback-resistance/effect-immunity/LOS/team/hurt-return gate. Comparison follows possible caster healing/execution. Failed/immune hurt can still satisfy motion condition. Calls on already removed/dead object do not prove subsequent world movement. No Levitation effect, launch attachment, source rewrite or fall immunity.',
      'drain_resource':'Only initial hurt true/server reaches Player non-instabuild durability request1, after whichever secondary branch. HEAD MysticCrown skips request when randomFloat<=.05; no Crown means always request1. Shared Unbreaking/Unbreakable/item hooks may change applied cost; native resource helper is protected R2f8i. No cost from false hurt, no healing required, no double cost for second execution request. Direct scepter damage is unaffected by Crown chance.',
      'living_source_hooks':'Because direct entity is caster Living, protected TF ToolEvents use its current MAINHAND independently of used hand or projectile tag. Legitimate offhand Lifedrain while mainhand Knightmetal sword/pick qualifies for protected armored-target bonus; mainhand Knightmetal axe with target armor0 sets original incoming damage+2. Normal mainhand scepter does not qualify. MinotaurAxe bonus also requires current isSprinting; retain that conditional without asserting sustained native sprint while using. Native use/recipient gates and event ordering remain. This source identity does not pass through Mob/Player melee enchantment helpers; no invented Sharpness/Strength addition.',
      'twilight_crown':'Twilight Scepter use: exhausted&&!instabuild FAIL, otherwise server addFreshEntity(new TwilightWandBolt(level,player)), add return ignored before possible charge. Non-instabuild request1 unless HEAD Crown and randomFloat<=.05. No item cooldown. Capacity99 and recharge protected R2f8i; bolt damage/reflection/source paths protected R2f3, not duplicated. Crown never worn down here. Zombie Crown baby producer remains protected; Fortification Crown affects timer rather than use cost. Crown armor material/other gear effects remain separate.'
    }
    F='item/FortificationWandItem';A='components/entity/FortificationShieldAttachment';E='events/CapabilityEvents';D='item/LifedrainScepterItem';T='item/TwilightWandItem';I='init/TFItems';C='command/ShieldCommand'
    nxt='Continue Task C with remaining player projectile/utility weapons (Moonworm Queen, Cube of Annihilation, Ender/Seeker/Triple bows, Peacock Fan), then armor/charms/food, remaining utility/passive entities and hazards/custom sources, exact nested ASM/compatibility coverage. Twelve custom types remain unfinished. Protect every subsection toward R2f8, then deduplicate/promote whole Twilight. IceAndFire only after Twilight COMPLETE is pushed/live verified. No runtime boss/L2/Stage/production/fixes/Phase6/7.'
    data=dict(slug='scepter-payloads',checkpoint_short='r2f8j',checkpoint='R2f8j-scepter-payloads-complete',decision='TWILIGHT_SCEPTER_PAYLOADS_SEMANTIC_REVIEW_COMPLETE',starting_sha='5f56f39696e7c17c4eccd8314f3953ef14578aeb',previous_checkpoint='R2f8i-summon-resources-complete',previous_draft='partial-drafts/twilightforest-r2f8i-partial.json',facts=facts,packages=[],paths=[],new_damage_types=1,full_classes=FULL,limited_classes={E:['setup','updateShields','absorbShieldHits'],'init/TFDataAttachments':['Fortification registration'],'events/ToolEvents':['protected mainhand predicates'],'util/entities/EntityUtil':['getDeathSound']},registration_classes=[I,'init/TFDataAttachments','init/TFDamageTypes','command/TFCommand'],closure_checklist=['native_shield_producers','separate_counts_and_mutators','incoming_admission_order','timer_Crown_expiry','codec_copy_death','native_use_schedule','entity_ray_and_block_occlusion','actual_lifedrain_source','hurt_true_vs_HP','low_HP_boss_tag','Player_second_hurt_vs_nonPlayer_discard','bonus_loot','slow_heal_food','independent_motion','direct_Living_mainhand_hooks','cost_Crown_protected_recharge','protected_bolt_reused'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus full Fortification attachment/producers/admission/persistence, Lifedrain unique payloads and Crown scepter cost interaction. Twilight PARTIAL/zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=27,new_used_profiles=1,reviewed_profiles_after=28,remaining_profiles=12,remaining_disposition='Actual caller profiles unfinished, not unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    shield=pkg('fortification_resource','Temporary and permanent Fortification shields','CUSTOM_RESOURCE',['fortification_use','shield_counts','shield_producers','shield_timer','shield_persistence'],[F,A,C,'init/TFDataAttachments',E],{'scepter_shields':5,'mutator_max_each':115,'timer':240,'cooldown':1200},['real scepter/admin producers','separate counts','temporary first','native codec/copy'],'Custom attachment count and lifetime, not absorption HP.','Native Fortification Scepter use',['Native admin permanent/set/add, Crown and save/clone controls'])
    block=pkg('fortification_admission','Fortification incoming damage cancellation','BINARY_MECHANIC',['shield_admission','shield_counts'],[E,A],{'invulnerable_time':20},['server','not bypasses_armor','total>0','count spend only invulnerableTime<=0'],'Binary native event veto before HP mitigation.','Native hit against real Fortification bearer',['Armor-bypass, shield-bypass-only, final shield and already-invulnerable controls'])
    drain=pkg('lifedrain_request','Lifedrain native selection and custom damage','CUSTOM_DAMAGE',['drain_use','drain_selection','drain_source','living_source_hooks'],[D,'init/TFDamageTypes','events/ToolEvents'],{'range':20,'request':1,'modulus':5,'use_duration':72000},['native hand use','pickable ray selection','Living not ArmorStand','native hurt'],'Custom source with entity-only ray and ordinary native HP admission.','Native held Lifedrain Scepter',['Block obstruction, nonliving blocker, cooldown/defense and real offhand controls'])
    execute=pkg('lifedrain_execution','Lifedrain low-health execution and bonus loot','BINARY_MECHANIC',['drain_branch','drain_execution','drain_source'],[D,'util/entities/EntityUtil'],{'post_hit_hp_max':1,'player_request':'Float.MAX_VALUE','bonus_flesh_min':0,'bonus_flesh_max':2},['initial hurt true/server','not c:bosses','post-hit HP<=1','Player vs nonPlayer','still alive for extra execute'],'Native low-HP execution distinct from initial HP damage.','Native Lifedrain against low-health nonboss',['Boss/no-flesh, first-hit death, Player totem and canceled death controls'])
    restore=pkg('lifedrain_restore','Lifedrain admitted slow and caster restoration','VANILLA_COMPOSITE',['drain_branch','drain_use'],[D],{'slow_ticks':20,'slow_amplifier':2,'heal':1,'food':1,'saturation':.2,'heal_modulus':10},['initial hurt true/server','not low nonboss execution','count%10 for heal/food'],'Native Slowness, heal and food composition with independent outcomes.','Native admitted Lifedrain regular branch',['Boss/absorption/failed effect, full HP/hunger and cooldown phase'])
    motion=pkg('lifedrain_motion','Lifedrain independent vertical motion replacement','CUSTOM_CONTROL',['drain_motion','drain_selection'],[D],{'velocity_x':0,'velocity_y':.15,'velocity_z':0},['server','selected Living not ArmorStand','targetHP<=casterHP','independent hurt result'],'Raw velocity replacement, no Levitation or knockback-resistance path.','Native Lifedrain selection with health predicate',['Failed hurt, higher targetHP and post-heal comparison'])
    crown=pkg('scepter_crown_charge','Crown scepter charge-saving branch','CUSTOM_RESOURCE',['drain_resource','twilight_crown','authority'],[D,T,I],{'skip_chance_inclusive':.05,'ordinary_request':1},['HEAD Crown','non-instabuild','Lifedrain hurt true','Twilight spawn attempt'],'Conditional cost request using protected nonbreaking durability.','Native Crown Twilight/Lifedrain Scepter use',['Without Crown, creative, failed hurt, denied projectile add and Unbreaking'])
    data['packages'][-1]['reuses_protected_effect_ids']=['twilightforest:scepter_charge_resource','twilightforest:scepter_renewal','twilightforest:scepter_crafting_repair','twilightforest:twilight_scepter_bolt']
    data['packages'][2]['reuses_protected_effect_ids']=['twilightforest:knight_phantom_haunt','twilightforest:minoshroom_axing']
    data['damage_profiles']=[dict(type='twilightforest:lifedrain',status='USED',callers=[dict(entry='twilightforest/item/LifedrainScepterItem.class',method='onUseTick')],amount='Initial1 each eligible remaining-count%5 attempt; true/low nonboss/alive Player branch requests Float.MAX_VALUE separately. NonPlayer die/discard is not a second HP request.',direct_and_causing_entities='Both caster LivingEntity; no projectile entity, despite IS_PROJECTILE tag.',mitigation=facts['drain_source'],success_gates='Initial hurt true/server gates slow/heal/food/execute/cost; motion independently uses current HP comparison.',secondary_payload=facts['drain_execution'])]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:scepter_payloads_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' via genuine native mechanics; future fixture, no runtime/fabricated source.',future_controls=controls))
    rows=[
      ('shield_use','Native Fortification Scepter use',['fortification_use','shield_counts'],[shield],[F,A],['ACTIVE_ITEM'],['set5 not add','permanent preserved','cost1/cooldown1200']),
      ('shield_use_negative','Native Fortification use controls',['fortification_use'],[shield],[F],['ACTIVE_ITEM'],['exhausted','creative vs instabuild','native cooldown']),
      ('shield_command','Native administrative shield set/add',['shield_producers','shield_counts'],[shield],[C,A],['OTHER'],['permission2','single Living','temporary default/permanent','clamp/overflow']),
      ('shield_hit','Native Fortification incoming hit',['shield_admission'],[block,shield],[E,A],['MELEE','PROJECTILE','ENVIRONMENT'],['total>0','not armor bypass','cancel/false','no HP requirement']),
      ('shield_cooldown','Native repeated/final Fortification hit',['shield_admission','shield_counts'],[block,shield],[E,A],['MELEE','PROJECTILE'],['invulnerableTime positive free cancel','20 on spend','last shield cancels current hit']),
      ('shield_bypass','Native shield admission negatives',['shield_admission','drain_source'],[block,drain],[E,D],['ACTIVE_ITEM','OTHER'],['armor bypass skips','shield bypass alone does not','earlier native immunity']),
      ('shield_timer','Native temporary shield expiry',['shield_timer'],[shield],[A,E],['PASSIVE_AURA'],['240 decrements then break','temporary first','permanent stable']),
      ('shield_crown','Native Crown and invulnerable shield ticking',['shield_timer'],[shield],[A,E],['ARMOR_PROC','PASSIVE_AURA'],['HEAD skips modulus3 decrement','invulnerable Player pause','damage reset']),
      ('shield_save','Native shield save/copy/death',['shield_persistence'],[shield],[A,'init/TFDataAttachments'],['OTHER'],['count serialization','timer reset','death/conversion excluded','nondeath clone']),
      ('drain_use','Native Lifedrain held use',['drain_use'],[drain],[D],['ACTIVE_ITEM'],['72000 remaining','%5','exhausted creative stops','native use hooks']),
      ('drain_ray','Native Lifedrain entity selection',['drain_selection'],[drain],[D],['ACTIVE_ITEM'],['range20','pickable','no block LOS','inside-zero/list order']),
      ('drain_blocker','Native Lifedrain invalid selected entity',['drain_selection'],[drain],[D],['ACTIVE_ITEM'],['ArmorStand/nonliving blocks attempt','no rescan','removed pickability']),
      ('drain_hurt','Native Lifedrain custom request',['drain_source','drain_use'],[drain],[D,'init/TFDamageTypes'],['ACTIVE_ITEM'],['direct/causing caster','projectile tag','1 request','cooldown retained']),
      ('drain_defense','Native Lifedrain recipient defense controls',['drain_source','drain_branch'],[drain,restore],[D],['ACTIVE_ITEM'],['armor/shield bypass','Resistance/protection/absorption','hurt true not HP']),
      ('drain_offhand','Native offhand drain and mainhand weapons',['living_source_hooks'],[drain],[D,'events/ToolEvents'],['ACTIVE_ITEM'],['Knightmetal mainhand predicates','Minotaur sprint conditional','no melee-helper enchantment']),
      ('drain_execute_mob','Native nonboss low-HP nonPlayer execution',['drain_execution','drain_branch'],[execute],[D],['ACTIVE_ITEM'],['post-hit<=1','true first hit','die then unconditional discard','death hook']),
      ('drain_execute_player','Native low-HP Player execution attempt',['drain_execution','drain_source'],[execute,drain],[D],['ACTIVE_ITEM'],['second Float.MAX_VALUE','ignored hurt return','native totem/admission']),
      ('drain_execute_boss','Native boss and already-dead execution controls',['drain_branch','drain_execution'],[execute,restore],[D],['ACTIVE_ITEM'],['c:bosses prevents execute only','first hit death','no second discard']),
      ('drain_bonus','Native low-HP bonus loot',['drain_execution'],[execute],[D,'util/entities/EntityUtil'],['ACTIVE_ITEM'],['Player caster','NO_FLESH','0..2 flesh','independent ordinary loot','particles not explosion']),
      ('drain_restore','Native regular Lifedrain slow/heal/food',['drain_branch'],[restore],[D],['ACTIVE_ITEM'],['Slowness20/2','count%10 heal1 food1/.2','independent returns']),
      ('drain_restore_negative','Native Lifedrain restoration controls',['drain_branch','drain_use'],[restore],[D],['ACTIVE_ITEM'],['low nonboss no restore','false hurt','full HP/hunger','cooldown phase']),
      ('drain_motion','Native health-gated Lifedrain motion',['drain_motion'],[motion],[D],['ACTIVE_ITEM'],['setsXYZ0/.15/0','independent hurt','no KR','post-heal HP']),
      ('drain_motion_negative','Native Lifedrain motion boundaries',['drain_motion','drain_selection'],[motion],[D],['ACTIVE_ITEM'],['higher targetHP','client','dead/removed object not world-motion proof']),
      ('drain_cost','Native Lifedrain durability and Crown',['drain_resource'],[crown],[D],['ACTIVE_ITEM','ARMOR_PROC'],['true initial hit only','one charge request','HEAD roll<=.05','protected hooks']),
      ('twilight_cost','Native Twilight Scepter Crown cost',['twilight_crown'],[crown],[T],['ACTIVE_ITEM','PROJECTILE','ARMOR_PROC'],['real bolt producer','add return ignored','no cooldown','protected bolt semantics']),
      ('scepter_resources','Native shared scepter repair/recharge controls',['drain_resource','twilight_crown','fortification_use'],[crown,shield],[D,T,F],['ACTIVE_ITEM','PASSIVE_ITEM','OTHER'],['reuse R2f8i','no Crown wear','separate capacities/cost/repair'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-scepter-payloads-caller-scan.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','reference-evidence/twilight-frosted-244.json','reference-evidence/cult-final-244.json','vanilla-evidence/twilight-summon-resources.json','reference-evidence/twilight-summon-resources-244.json']
    data['exclusions']=['Five complete native class surfaces and selected native event/registration/source consumers; all-TF relevant caller scan.','Lich boss shields remain distinct; Twilight bolt, Zombie Crown baby and shared recharge protected, not duplicated.','Crown armor/other items/charms/hazards/nested ASM and whole-mod compatibility closure still pending.','Native die/discard and independent motion documented as installed; no repair/compatibility implementation.','LIFEDRAIN USED:28/40 custom types reviewed,12 unfinished. Twilight PARTIAL, zero promoted, REVIEW_REQUIRED0.']
    data['fixture_groups']=['Native Fortification use/cooldown/admin counts, last-shield/repeated-hit/bypass and timer/save/clone controls.','Real Lifedrain ray/pickability/occlusion/use scheduling with intact source/defense/cooldown.','Distinct low-HP Player hurt versus nonPlayer die/discard, boss/no-flesh/bonus-loot and initial-death controls.','Separate admitted slow/heal/food, independent health-gated motion and real offhand source-identity hooks.','Crown cost requests with protected charge/recharge/projectile controls.']
    data['expected_counts']=dict(mechanic_packages=7,delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=1)
    write_json(OUT/'review-inputs/twilightforest-scepter-payloads.json',data);assemble('twilightforest-scepter-payloads.json')

if __name__=='__main__':build()
