"""Save a bounded source foundation without promoting unreviewed combat packages."""
from catalog_common import *
from collect_eternalstarlight_foundation import START,CP
from assemble_batch import refresh

STEM='eternalstarlight-r2h1-source-foundation'
NEXT='R2h2: Eternal Starlight status/control and damage-admission semantics, starting Crystal Infection plus LivingEntityMixin and ESCommonHandler damage/effect hooks, then Starfire/Flammable/Brittle/Numbness/Dream Catcher/Sticky/Teary/Oblivion. Trace real native producers and one Stage amount boundary per scalable component; no runtime/L2/Stage/production work.'
FACTS={
 'authority':'Installed eternalstarlight-0.8.1+1.21.1+neoforge.jar, SHA acb8fa7a69c4f7d4f1dfa3fba1dbdc96976478ea80b2f9025e43f0c4ee1ceb19, contains1384 classes. Exact bytecode/resource witnesses and existing source aids are reused. Inventory key eternalstarlight differs from actual namespace eternal_starlight. This foundation does not claim completed effect or boss semantics.',
 'factory':'ESDamageTypes.getDamageSource(level,key) delegates getEntityDamageSource with null; entity overload forwards attacker twice; indirect overload constructs ordinary DamageSource(holder,directArgument,causingArgument). Exact native DamageSource constructor/getters are retained in twilight-equipment-244 reference evidence. Source-only has both entities null; entity source has both identical; indirect source preserves separate supplied arguments. No special subclass, rewritten owner, fallback DamageType, target hurt or HP subtraction is performed by these factory methods. registryOrThrow then getHolderOrThrow requires a valid native registry holder.',
 'damage_declarations':'Eighteen native ResourceKeys match eighteen installed damage_type JSON definitions. All declare exhaustion0.1 and difficulty scaling when_caused_by_living_non_player; this is native difficulty policy, not TNO Stage. Only laser and energized_flame request burning damage feedback. Feedback does not add IS_FIRE or ignition; no custom declaration gains IS_FIRE/IS_FREEZING/IS_LIGHTNING in the scoped native tag closure. Individual payload amounts and eligibility remain family review work.',
 'tags':'Scoped raw Minecraft1.21.1 + NeoForge21.1.244 + ES closure: ether/crystal_infection/soul_absorb bypass armor, enchantments and shield; numbness and sonar also bypass shield. Only seeds/shattered_blade/wilt have IS_PROJECTILE. Only numbness belongs to ES bypasses_crescent_pendant. No ES custom declaration gains bypasses_cooldown or bypasses_invulnerability here. Per-type no-impact/no-knockback/panic/armor-stand membership is explicit in the machine table. Other mods/datapacks and runtime load order can alter membership; no whole-pack tag claim.',
 'registered_statuses':'Nine holders: crystal_infection, dream_catcher, sticky, flammable, brittle, numbness, teary, starfire, oblivion. Dream Catcher/Sticky/Numbness/Oblivion are BENEFICIAL; the other five HARMFUL. Registry constructors for Flammable/Brittle/Numbness/Teary are plain MobEffect, so their actual combat consumers must be reviewed in shared hooks rather than assuming absence of behavior. The five custom subclasses likewise need their actual methods and native producers reviewed; registry categories alone do not prove admission or compatibility.',
 'registration':'ESNeoEntrypoint constructor calls EternalStarlight.init, which loads ESMobEffects. RegistrationProvider.get delegates the service-loaded ESPlatform; installed META-INF/services selects ESNeoPlatform. Its provider creates/retains a DeferredRegister in REGISTERS, and the entrypoint registers those instances with the supplied mod event bus. Native bootstrap/datagen definitions and on-disk resources are distinguished from actual holder lookup; no fabricated registry setup is allowed.',
 'event_bridge':'CommonEvents is declared EventBusSubscriber(modid=eternal_starlight), with SubscribeEvent on the pinned eleven combat callbacks. IncomingDamage: if not canceled, call onAllowLivingHurt and cancel on false; afterward call onModifyLivingHurtDamage/setAmount and onModifyPostAttackInvulnerabilityTicks/container setter even if this method just canceled. This describes in-method ordering, not a claim that the event bus dispatches pre-canceled events to a default subscriber. LivingDamageEvent.Pre separately calls onModifyLivingActualHurtDamage/setNewDamage; Post separately invokes onPostLivingHurt. These are different stages, not permission for multiple TNO multipliers.',
 'other_bridges':'LivingHealEvent replaces its amount with ESCommonHandler.onLivingHeal result. LivingDeathEvent consults onAllowLivingDeath only while uncanceled, then calls onLivingDeath only if still uncanceled. LivingChangeTargetEvent sets the new target if the helper returns a different object. EntityTickEvent.Post delegates onEntityTick; CriticalHit calls its helper only when event.isCriticalHit; ShieldBlock calls its helper on getOriginalBlock, and ProjectileImpact delegates hit handling. Actual helper predicates, amount modifications, resource effects and mixin application remain the next semantic review.',
 'census':'All1384 installed classes parsed:29 direct damage-factory caller methods,31 damage-key-reference methods,38 status-field-reference methods. These include implementation/support/registry/client/datagen contexts; counts are not confirmed native delivery counts or completed mechanic packages. The census pins method/entry hashes and exact matched instructions so the next review starts at real producers/consumers.',
 'compatibility':'Explicit-name constant-pool and text-resource scans are negative in both reviewed directions: ES for Tensura/L2Hostility/L2Complements/L2Library names, and installed Tensura plus the four inventoried compat candidates for ES namespace/package names. Scope is exactly six archives, not the entire installed pack. Generic skill, damage/effect admission, event ordering, registry/tag-driven behavior and unnamed integrations remain possible and untested. No absence-of-conflict conclusion.',
 'stage_boundary':'Source construction/registration/tag declarations have NO_STAGE_VALUE. When a reviewed payload requests a numeric hurt/heal amount, choose one amount boundary after native formula selection and retain eligibility/source identity; do not multiply factory creation, native difficulty scaling, status duration/amplifier and multiple event phases together. No payload scaling point or permanent implementation is approved by this foundation.',
 'exclusions':'Rendering/particles, registry-remap acquisition details, creative tabs, crafting, worldgen and ordinary utility are excluded quickly. No deep noncombat sections. Installed source aids are navigation only; existence of a class, method or census hit is not semantic completion.'
}

def save():
    references=['native-evidence/eternalstarlight-foundation.json','eternalstarlight-source-census.json','eternalstarlight-damage-tags.json','eternalstarlight-direct-compat-census.json','annotation-evidence/eternalstarlight-foundation-javap.json','annotation-evidence/eternalstarlight-foundation-javap.txt','reference-evidence/twilight-equipment-244.json']
    d=dict(schema='tno.external_effects.es_foundation.v1',baseline=BASELINE,mod_key='eternalstarlight',checkpoint=CP,starting_sha=START,status='SOURCE_FOUNDATION_COMPLETE_FAMILY_SEMANTICS_PENDING',facts=FACTS,reference_files=[dict(file=f,sha256=sha256(OUT/f)) for f in references],registered_statuses=9,declared_custom_damage_types=18,reviewed_payload_packages=0,promoted_mechanics=0,promoted_paths=0,whole_mod_complete=False,exact_next_task=NEXT,runtime_tests=0,**boundary_flags())
    write_json(OUT/(STEM+'.json'),d)
    review=dict(schema='tno.external_effects.mod_review.v1',baseline=BASELINE,mod_key='eternalstarlight',checkpoint=CP,status='PARTIAL',scope='R2h1 native source/registry/tag and combat-event bridge foundation complete; actual combat family semantics pending.',semantic_discovery_complete=False,special_damage_discovery_complete=False,source_mapping_complete=False,delivery_mapping_complete=False,effects=[],paths=[],unresolved_native_ambiguities=None,remaining_native_ambiguities=None,notes_file=STEM+'.json',exact_next_task=NEXT)
    write_json(OUT/'mod-reviews/eternalstarlight.json',review);refresh(CP)
    for file in ['effect-catalog.json','effect-sources.json','delivery-path-matrix.json','vanilla-comparison.json','behavior-primitives.json']:
        v=read_json(OUT/file);v.update(checkpoint=CP,unfinished_review=dict(mod_key='eternalstarlight',status='PARTIAL',promoted_records=0,notes_file=STEM+'.json'));write_json(OUT/file,v)
    d=read_json(OUT/'research-decision.json');d.update(checkpoint=CP,next_task=NEXT,latest_eternalstarlight_decision='SOURCE_FOUNDATION_COMPLETE_FAMILY_SEMANTICS_PENDING',save_mode=False,save_reason=None);d['checkpoints']['R2g10b-iceandfire-complete']=START;d['checkpoints'][CP]='Self: exact SHA from commit/live verification.';write_json(OUT/'research-decision.json',d)
    lines=['# R2h1 — Eternal Starlight source foundation','', 'Ice & Fire remains COMPLETE at '+START+'. This new mod is PARTIAL with no promoted packages or runtime claims.','']
    for k,v in FACTS.items():lines+=['## '+k.replace('_',' ').capitalize(),'',v,'']
    lines+=['[Machine evidence](eternalstarlight-r2h1-source-foundation.json); [native callers](eternalstarlight-source-census.json); [all eighteen source profiles](eternalstarlight-damage-tags.json).','','Exact next task: '+NEXT,'']
    (OUT/(STEM+'-review.md')).write_text('\n'.join(lines),encoding='utf-8')
    main=ROOT/'docs/external-effects-catalog-research.md';text=main.read_text(encoding='utf-8');heading='## R2h1 — Eternal Starlight source foundation'
    if heading not in text:text+='\n'+heading+'\n\nInstalled 0.8.1 source foundation: 18 custom DamageTypes, 9 MobEffects, 29 factory callers and the actual NeoForge combat bridge pinned. Family semantics remain unfinished; Ice & Fire COMPLETE preserved. [Evidence and next task](benchmarks/external-effects-catalog/'+STEM+'-review.md).\n'
    main.write_text(text,encoding='utf-8')
    print('Saved R2h1 source foundation; accepted records unchanged.')

if __name__=='__main__':save()
