from copy import deepcopy
from catalog_common import *
from bossesrise_combat_common import save_section
CP='R2i8a-bossesrise-gauntlets-complete'
STEM='bossesrise-r2i8a-gauntlets'
START='8740fe66591a4b7c5692608026aa81062e5fc33d'
NEXT='R2i8b: Undying Tentacle real item modes/Ghost Tentacle and Kraken Trident native special delivery; then Dragon armor procs/remaining weapons, watched-method closure and Bosses Rise final dedup/promotion. Apply the R2i8a additive Sandworm producer correction during promotion; protected prior evidence remains immutable.'
CORRECTIONS=[dict(checkpoint='R2i6-bossesrise-sandworm-complete',file='bossesrise-r2i6-sandworm.json',fact='spit_and_hazard',superseded_text='Gauntlet uses a genuine static shoot helper',replacement='SandwormGauntletItem.releaseUsingWithPoisonBarrage directly constructs PoisonSpitPrEntity, sets owner/base6/knockback5 and calls its inherited instance shoot(DDDFF). No external invokestatic call to the convenience shooting helpers exists in this installed JAR.',reason='Equipment tracing distinguishes opcode/invocation descriptor; text matching the class-qualified shoot name alone does not establish a static helper caller.',evidence='bossesrise-gauntlets-helper-census.json')]
FACTS={
'ice_native_use':'IceGauntletItem extends ShieldItem, not plain Item. use starts animation then delegates ShieldItem.use, which starts actual item use and returns consume; inherited block animation/use duration72000 supplies charge/jump/holding admission. PlayerAnimationHandler only schedules cosmetic animation and does not substitute for startUsingItem. Native shield eligibility/directional block/source shield bypass and cooldown remain intact. Item durability1200; native mainhand modifiers attackDamage+4, attackSpeed-3, attackKnockback+2.5 are ordinary melee inputs, not extra HP callbacks or additional Stage points. Successful native melee weapon callback hurtEnemy calls super, writes target frozen400 regardless of the returned item boolean, then returns it. It does not invoke hurt, canFreeze or addEffect. Player.attack/ItemStack dispatch still controls whether the callback occurs. Frozen counter/Roll/native freeze immunity and later passive tick use protected R2i5b, not fabricated instant freezing damage.',
'ice_wave':'ServerPlayer release while secondary-use active and item cooldown absent computes held ticks i=72000-timeLeft; negative returns. Begins end animation, clips eye/view along blockInteractionRange*1.1 with COLLIDER/Fluid.NONE; MISS returns before cost. Pitch is clamped+/-85 only for wave direction after ray. Calls native iceWave range=min(i/32+.5,1.5)*12 (6..18), count=min(i,32), damage10,speed1, origin hit location. Cooldown80 and durability1 follow even if count0 or all candidate terrain rays reject. Protected helper places normal/cluster candidates, owner player, delays16+j, native stored damage10. No eye-to-each-spike LOS override or guaranteed count; normal versus cluster admitted HP/control/reload semantics remain R2i5b. Scale at later native spike/cluster hurt, never setDamage and hurt both.',
'ice_leap':'LivingJumpEvent only ServerPlayer actively using exact gauntlet and no gauntlet cooldown; requires attachment !active and no stored shard UUID. Sets active, costs10durability, stops use, starts jump animation, cooldown400, Spatial push(view+Y2). LivingFallEvent ServerPlayer calls onFall; true cancels fall. PlayerFlyableFallEvent calls it without cancellation. onFall needs ONLY active flag, not continued equipment/use/cooldown; clears flag, starts landing animation, native iceBurst range8/count40/damage3, cluster random1/10 OR index<4, cooldown200. It also independently scans playerBB.inflate2 for any Entity except self, owner-matched OwnableEntity, dead/spectator, normal spike or cluster. Requests ownerless freeze10 then writes frozen200 regardless of hurt result; no Living/canFreeze/team/LOS guard. Passive freeze eligibility remains separate. Falling after item swap or native saved active state is a genuine fixture. Landing HP10 and delayed spikes are separate native payloads; no duplicate Stage scaling.',
'ice_shards':'Native cluster interact with gauntlet and free random slot0..3 starts real use, stores UUID, replaces break resource with slot index, sets held and owner player. useOn searches cluster centers near clicked position in full-side3 box and delegates first successful interaction; client only predicts success. Post PlayerTick attachment clears UUIDs whose loaded entity is not Cluster. With at least one valid shard and continued exact gauntlet use, it can collect additional unheld clusters from full-side3x2x3 box one block ahead of eye until4 slots. It does not consume durability or apply a cooldown there. When no longer using that gauntlet, every>=2 game ticks releases the first valid stored cluster: new native IceSpikeProjectile owner player at eye, speed4, inaccuracy=slotIndex*5, baseDamage4, knockback8; then discards cluster, clears UUID and updates lastShot even if addFreshEntity failed. Projectiles preserve R2i5b swept indirect_magic ceil(speed*base) and genuine playerTouch FREEZE8 as different routes. No extra HP added by attachment. Held clusters can release held-state separately when player stops use; native tick ordering/removal matters. Attachment active/shard UUIDs/last_shot persist; missing entities clear naturally.',
'sandworm_modes':'SandwormGauntlet extends Item, durability1000, use duration72000/BOW. Crouching on top face in onItemUseFirst sets operation mode earthquake; ordinary use defaults missing mode to poison_barrage, applies its modifiers, starts using and consumes interaction. Earthquake adds MOVEMENT_SPEED and JUMP_STRENGTH negative-infinity ADD_VALUE modifiers keyed freeze, ANY equipment group. Poison mode adds MOVEMENT_SPEED +.5 ADD_MULTIPLIED_BASE under a key named slow: code is a positive base-speed modifier, do not infer a slow from its label. release or dropping clears operation mode and removes these two modifier IDs. Native attribute clamping/use lifecycle must be retained; they are control/resources with no Stage multiplier.',
'sandworm_quake':'Server onUseTick in earthquake mode: at useTick30 and every20 thereafter, first costs10 durability via native hurtAndBreak, then chooses up to4 random Living targets other than user in full-side28x8x28 box with strict3<distance<14. No explicit ally/LOS/creative/spectator predicate at candidate selection. Remaining positions use random horizontal radius[3,14). Four native spawnSandColumn attempts pass delay0 and owner user; protected terrain COLLIDER ray may reject each. Column actual victim admission still checks alive, virtual invulnerable, owner and alliance, with push before ally HP rejection. Normal owned payload indirect_magic5 direct column/causing user; unresolved owner magic5 remains native. Cost/count/delay are not Stage values; only final native column HP once.',
'sandworm_barrage':'On release in poison mode compute count=clamp(Java integer (useTick+4)/10,0,4), requiring>=1; earliest count1 at6 held ticks, then2/3/4 at16/26/36. Force=clamp(.5+(useTick-7)/5,.5,1), speed=force*1.5 (.75..1.5), inaccuracy8+count*5. Server directly constructs count PoisonSpitPr at eye with firing ItemStack, sets owner user, silent, baseDamage6 and knockback5, then calls inherited instance shoot along view. It does NOT call the static convenience helpers. No native barrage durability deduction or item cooldown in this method; item-use stat increments for Player. AbstractArrow native speed/base/enchantment HP, return-gated projectile knockback and independent impact PoisonArea use R2i6. Area has no owner transfer, so later native poison tick still has no attacker. Keep each stage point downstream; do not scale count or base6 in addition to HP.',
'correction_and_reuse':'R2i6 boss payload/admission evidence remains valid. Its sentence that the Gauntlet uses a static shoot helper is superseded by this checkpoint: native constructor plus invokevirtual shooting is the real player path; invokestatic census has only convenience helpers calling each other inside PoisonSpitPrEntity. This is an additive, evidence-backed correction, not a rewrite of protected history. Existing nine hazard packages are extended with player delivery paths under the SAME IDs and same scaling points for final deduplication. Gauntlet input/control and landing pulse add three new packages. Native source tags, Resistance/Nullification/effect applicability and Roll semantics are reused unchanged. Cross-mod runtime results remain untested; origin/merge attribution for passive freeze and poison still requires design before Stage implementation.',
'excluded':'IceGauntletMessage handles client sound/particles only, not HP, frozen counters or server input. Player animations, item tooltip/render transforms, mining swing suppression, UUID animation keys and repair acquisition are excluded after identifying genuine use/attack delivery. No runtime/Stage/production changes. Dragon armor, Undying Tentacle and Trident remain next equipment subsections.'
}

def save():
    defs=[('ice_melee','MELEE','Native successful weapon callback -> frozen400, no extra hurt'),('ice_shield_use','ACTIVE_ITEM','Inherited ShieldItem use starts real blocking/charging'),('ice_wave_spike','AOE','Secondary-use release -> terrain-selected normal spikes damage10'),('ice_wave_cluster','AOE','Same native release -> cluster branch damage10'),('ice_jump','ACTIVE_ITEM','Using/no cooldown/no shards -> active leap and400tick cooldown'),('ice_land','AOE','Active fall -> freeze10/frozen200 independent of delayed burst'),('ice_burst_spike','AOE','Native landing burst normal spike stored damage3'),('ice_burst_cluster','AOE','Landing burst first4 cluster candidates plus1/10 others, damage3'),('ice_capture','ACTIVE_ITEM','Genuine cluster interact/useOn and held secondary collection'),('ice_throw','PROJECTILE','Stored cluster release -> player-owned swept magic spike'),('ice_touch','PROJECTILE','Player-owned spike real Player touch -> explicitFREEZE8'),('ice_passive_freeze','OTHER','Native counters -> eligible passive freeze tick'),('sand_mode','ACTIVE_ITEM','Native mode/use/release/drop and attribute resources'),('sand_quake','AOE','Thirtytick charge/every20 -> four owned column attempts'),('sand_column','AOE','Column native owned/unresolved source and hurt-return payload'),('sand_barrage','PROJECTILE','Real release count1..4 constructor/base6/KB5/instance shoot'),('sand_area','AOE','Player spit entity/block impact -> independent ownerless poison area'),('sand_poison_tick','OTHER','Native poison effect after player hazard -> ownerless HP tick')]
    paths=[dict(id='br:gauntlets:'+n,labels=[label],native_path=desc,runtime_status='NOT_RUN',runtime_variants=['Genuine item use/charge/cost/owner path','Reuse protected hazard admission and separate HP/control results']) for n,label,desc in defs];ids={n:p['id'] for (n,*_),p in zip(defs,paths)}
    prior={}
    for file in ['bossesrise-r2i5b-yeti-offense.json','bossesrise-r2i6-sandworm.json']:
        prior.update({m['id']:m for m in read_json(OUT/file)['mechanic_packages']})
    reuse=[('ice_spike_damage',['ice_wave_spike','ice_burst_spike']),('ice_cluster_damage',['ice_wave_cluster','ice_burst_cluster']),('ice_spike_projectile',['ice_throw']),('ice_spike_touch',['ice_touch']),('yeti_passive_freeze',['ice_passive_freeze']),('sandworm_column',['sand_quake','sand_column']),('sandworm_spit',['sand_barrage']),('sandworm_poison_delivery',['sand_area']),('sandworm_poison_tick',['sand_poison_tick'])]
    pk=[]
    for i,keys in reuse:
        m=deepcopy(prior['br:'+i]);m['delivery_paths']=[ids[k] for k in keys];m['extends_existing_package']=True;pk.append(m)
    new=[('ice_gauntlet_control','Ice Gauntlet native use, freezing counter, leap and shard resources','CUSTOM_CONTROL',['ice_melee','ice_shield_use','ice_jump','ice_capture'],None),('ice_gauntlet_landing','Ice Gauntlet native landing freezing pulse','VANILLA_LIKE_EXTENDED',['ice_land'],'GauntletAttachment.onFall native ownerless freeze10 hurt argument only; not frozen counter or delayed spike damage.'),('sandworm_gauntlet_control','Sandworm Gauntlet native modes, cost and movement modifiers','CUSTOM_RESOURCE',['sand_mode'],None)]
    for i,name,cl,keys,point in new:pk.append(dict(id='br:'+i,name=name,primary_classification=cl,tno_categories=['COMPOSITE','ADMISSION_GATED','NUMERIC_SCALABLE' if point else 'NO_STAGE_VALUE'],stage_scaling_needed=bool(point),single_scaling_point=point,stage_reason='Native landing HP pulse once.' if point else 'Native use/admission/control/resource or counter delivery; no additional outgoing HP multiplier here.',delivery_paths=[ids[k] for k in keys]))
    d=dict(schema='tno.external_effects.bossesrise_gauntlets.v1',checkpoint=CP,previous_checkpoint='R2i7b-bossesrise-kraken-offense-complete',starting_sha=START,status='ICE_AND_SANDWORM_GAUNTLET_DELIVERY_COMPLETE',scope='Ice and Sandworm Gauntlet native item prerequisites, costs, owner/control and hazard delivery; protected payloads reused.',summary='Gauntlets extend nine existing native hazard packages; inherited shield use, active landing, shard ownership and real Sandworm constructor delivery are pinned. Prior static-helper wording corrected additively.',facts=FACTS,semantic_corrections=CORRECTIONS,mechanic_packages=pk,delivery_paths=paths,unexecuted_future_fixtures=['native_ShieldItem_use_source_bypass_blocking_and_release','hurttrue_player_itemcallback_frozen400_vs_canFreeze_Roll','wave_secondary_release0_32_rayMISS_cost_candidateMISS','native_jump_active_item_swap_savedactive_landing_fall_veto','landing_anyEntity_owner_exclusion_noCanFreeze_hurtfalse_frozen200','normal_vs_cluster_landing_first4_candidate_terrain_branches','capture_four_slots_loadedUUID_cleanup_auto_collect','native_shard_release_every2tick_owner_base4_KB8_touch_vs_sweep','sand_mode_crouch_top_vs_default_and_release_drop_modifiercleanup','sand_positive_speed_modifier_not_label_inference','sandquake_use30_every20_cost10_fourterrain_attempts','sandbarrage_charge6_16_26_36_force_no_native_cost_orcooldown','gauntlet_column_owner_ally_push_and_unresolved_reload','gauntlet_spit_hurtfalse_ownerlessarea_nativepoison_origin'],review_required=['Future passive freeze/poison Stage requires proven origin and merge policy; no attribution bypass or production change.'],remaining_subsection_native_ambiguities=[],exact_next_task=NEXT,references=['native-evidence/bossesrise-gauntlets.json','bossesrise-gauntlets-helper-census.json','reference-evidence/bossesrise-gauntlets-244.json','vanilla-evidence/bossesrise-gauntlets.json','reference-routing/bossesrise-gauntlets.json','bossesrise-r2i5b-yeti-offense.json','bossesrise-r2i6-sandworm.json','native-evidence/bossesrise-yeti-offense.json','native-evidence/bossesrise-sandworm.json','bossesrise-r2i2a-roll-admission.json'])
    save_section(d,STEM,'R2i8a — Bosses Rise Ice and Sandworm Gauntlet delivery')
if __name__=='__main__':save()
