"""Reviewed consumption resources, native effect payloads and failed-challenge source."""
from catalog_common import *
from collect_twilight_food_flasks import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed Twilight4.8.3345 and raw Minecraft1.21.1/exact NeoForge21.1.244 authority, with incremental bytecode/resource witnesses. Static research only, runtime0. Prior protected gear/boss/source work preserved. This closes food/flask/Essence Berry consumption and Experiment115 block resource; utility/map/passive/hazard and remaining ASM/source closure still unfinished. FAILED_CHALLENGE is USED;31/40 profiles now reviewed,9 unfinished. No Stage/L2/production/Phase6/7 changes.',
      'food_admission':'Native Item.use reads actual stack food properties and Player.canEat(canAlwaysEat); native canEat is abilities.invulnerable OR canAlwaysEat OR foodData.needsFood. Use duration normally32ticks, StackableEffectItem fast16ticks. Native use completion and loader item-use events remain; no instant consumption fabricated. Item.finishUsingItem delegates LivingEntity.eat when food exists. Player.eat adds FoodData and stats/criterion before superclass effects/stack consumption. Native FoodData adds nutrition clamped0..20, saturation gain nutrition*modifier*2 clamped0..newfood. Ordinary possible effects apply server-side when randomFloat<probability; vanilla addEffect admission/merge applies. Native consume preserves stack for infinite-material Player. usingConvertsTo gives bowl copy when consumed stack empty or server inventory/drop otherwise, only without infinite materials. Registration fireResistant protects item entity/stack, not consumer.',
      'food_values':'All nutrition/saturation-modifier parameter sets: raw_venison2/.3; cooked_venison6/.6; hydra_chop18/2; raw_meef2/.2; cooked_meef7/.6; meef_stroganoff14/1.2; maze_wafer4/.6; experiment_1154/.3; berry_medley and moss_soup5/.6; shika_senbei4/1; monster_jerky4/.275; beef/pork/venison/meef_jerky6/1.18; chicken_jerky4/1.075; mutton/salmon_jerky4/1.35; rabbit_jerky4/.925; cod_jerky4/.875; tropical_fish/fugu_jerky2/.6; gelatinous_slime_drop1/.2; gelatinous_maze_slime_drop2/.3. Stackable berries1/.4. Torchberries leave Builder defaults nutrition0/modifier0. Only Torchberries and Meef Stroganoff explicitly alwaysEdible here. Medley, soup and Stroganoff stack1 and return BOWL. No raw-meat, monster-jerky or fugu-jerky poison inferred from name: registration has none.',
      'hunger_health':'Food addition is a nutrition/saturation resource, not immediate HP healing. Native FoodData.tick naturalRegeneration gamerule: food>=20, saturation>0 and Player.isHurt ->each10ticks heal min(saturation,6)/6 and add that numerator as exhaustion; otherwise food>=18 and hurt ->each80ticks heal1/exhaustion6. Actual native heal hook, HP eligibility and subsequent food exhaustion remain. Hunger/starvation is inherited native behavior, not a new Twilight damage source. Food data persists through native Player save/death rules; no Twilight custom food attachment.',
      'torchberries':'Actual food effect GLOWING duration100ticks amplifier0 probability.75. Always edible with0nutrition/0saturation; native outline effect on eater, not emitted light, target damage or custom detection immunity. Ordinary effect eligibility, duration merge, expiry and native rendering remain.',
      'hydra_chop':'Food applies native REGENERATION100ticks amplifier0 probability1. HydraChopItem separately triggers CONSUME_HYDRA_CHOP criterion before parent consumption only ServerPlayer and foodLevel<=0; this is advancement admission, not a second heal or stronger regeneration. Native Regeneration requests heal1 on remaining-duration multiples of50>>amplifier while HP<max, through native heal hook. Full-food ordinary non-invulnerable player cannot begin this non-alwaysEdible food use. Item fire resistance is not consumer immunity.',
      'stroganoff':'Native food applies FIRE_RESISTANCE3600ticks/amp0 and DAMAGE_BOOST(Strength)2400ticks/amp0 independently with probability1 each. AlwaysEdible14nutrition/1.2modifier, bowl remainder. Strength is native attack-damage ADD_VALUE+3 per level, not direct HP. Fire Resistance native hurt gate checks source IS_FIRE; it is not Entity.fireImmune nor protection from arbitrary untagged source. Native effect eligibility/merge and attribute cleanup remain.',
      'slime_food':'Gelatinous Slime Drop applies MOVEMENT_SPEED600ticks/amp0 probability1; Maze variant applies DAMAGE_RESISTANCE600ticks/amp0 probability1. Speed native movement attribute +.2 ADD_MULTIPLIED_TOTAL per level. Resistance native damage reduction is20% per level where native source bypass predicates permit, not absolute immunity. These are food effects on consumer; protected Slime/Maze Slime contact attacks remain separate.',
      'berry_stack':'StackableEffectItem.finishUsingItem server applies each configured custom roll BEFORE super food consumption. Each independent test chance>=random.nextFloat; accepted effect requests MobEffectInstance(effect,currentDurationOr0+extraTicks,configuredAmplifier). All installed berry configured amplifiers0; this extends requested duration, never increments amplifier. Native addEffect return ignored; eligibility, stronger/hidden/infinite effect merge still determine actual result. For active infinite duration=-1 the finite request becomes extraTicks-1; no automatic infinite extension/replacement claim. No cap in TF helper; Java int addition and native instance validation/merge remain. Noarg constructor decompiler appears recursive, but pinned bytecode constructs zero-length StackableEffectInstance array then invokes varargs constructor. Raspberry/Blueberry/Blackberry/Maloberry therefore have no custom status payload.',
      'berry_payloads':'Blightberry independent REGENERATION+160ticks p1, POISON+100ticks p.75, WITHER+100ticks p.15. Duskberry NIGHT_VISION+300ticks p1, BLINDNESS+60ticks p.75. Skyberry JUMP+160ticks p1, MOVEMENT_SLOWDOWN+60ticks p.75. Stingberry DAMAGE_BOOST+200ticks p1, DIG_SLOWDOWN+200ticks p.75. Every payload amp0. Negative rolls do not veto other effects or nutrition. Native levelI Jump adds.1 jump power and+1 safe-fall distance, Slowness movement-.15 total, Strength attack+3, MiningFatigue attackSpeed-.1 total and ordinary Player mining multiplier.3 at amp0. NightVision/Blindness affect native visibility/control rather than HP. Protected native status implementations reused; no TF custom effect registered by these items.',
      'berry_damage':'Native Poison tick requires HP>1, requests1 every25>>amp on duration modulo; exact244 uses holder neoforge:poison, fallback minecraft:magic if holder absent, new ownerless DamageSource. Raw vanilla comparison uses magic. Native Wither requests1 every40>>amp via ownerless minecraft:wither, no HP>1 floor. Tick method returns true independently of hurt success. Regeneration native heal1 every50>>amp only belowmax. These indirect later native status HP requests remain separate from food consumption/roll success; armor/source tags, Resistance/Protection/invulnerability/absorption/loader hooks remain native. No guaranteed final HP amount, no SHP write or new TF DamageType.',
      'flask_fill':'Brittle default POTION_FLASK_CONTENTS EMPTY=(PotionContents.EMPTY,0doses,0breakage,true); Greater default EMPTY_UNBREAKABLE same but false, stack1/fireResistant. Brittle stack-aware max is1 only when inner potion base Holder is present, otherwise native default max64. Both secondary-click override directions require donor POTION_CONTENTS nonnull, existing baseholder empty OR full PotionContents.equals(donor), and doses<3-breakage. No PotionItem class/regular-drinkable-only gate: genuine splash/lingering potions and tipped arrows with actual component also qualify. No additional slot.allowModification/mayPickup check in TF handlers; real menu dispatch posts CommonHooks.onItemStackedOn first, then feature-enabled item handlers before ordinary fallback slot pickup/insert checks. Other native menu/player/event admission remains. Not permission to bypass it.',
      'flask_resource':'If !instabuild filling shrinks donor1 and gives glass bottle via inventory.add or drop. changeAndConsumeFlask splits one flask when stackcount>1, mutates copy, inventory-add/drop; otherwise mutate original. tryAddDose replaces contents with supplied PotionContents and adds1dose, retaining breakage/breakable. Capacity lives in UI caller, not record. An existing custom-only payload without baseholder can therefore be replaced by next donor and does not trigger maxstack1; no ordinary producer of arbitrary custom data is invented. Drink use requires inner PotionContents identity !=static EMPTY and doses>0, starts native32tick DRINK; finish itself does not recheck positive doses. Non-instabuild completion removeDose subtracts1, clears contents if newdose<1, increments breakage only if breakable. Breakable breaks/shrinks1 at breakage>=3, otherwise cracks; Greater unbreakable retains breakage0 and refills max3, no break/crack. Hurt/addEffect return never gates these costs. Creative processes effects but no donor/dose cost; survival and creative actual eligibility still native.',
      'flask_native_payload':'finish requires nonempty-by-identity potion and LivingEntity instanceof Player; server iterates actual getAllEffects, base potion effects then custom list. First tests custom FAILED_CHALLENGE predicate below; otherwise instant MobEffect invokes applyInstantenousEffect(player,player,player,amplifier,1), noninstant calls player.addEffect(copy). For normal noninverted eater, HARMamp0 requests native indirectMagic direct=causing=self amount6; Healingamp0/1 native heals4/8. Inverted heal/harm reverses those native branches, subject to earlier custom branch. Ordinary native PotionItem passes same instant arguments but has no TF custom branch. PotionContents defines payload, so same filling path carries actual installed modded potion effects without assuming all recipient eligibility. Parent here is Item, not PotionItem: default flask has no FOOD; no second potion application, native PotionItem bottle replacement or its DRINK gameevent from this parent call. Native item-use framework hooks still apply.',
      'failed_challenge':'Exact predicate: (effect.is(HARM) != entity.isInvertedHealAndHarm()) && amplifier>0, evaluated BEFORE effect.isInstantenous. Ordinary noninverted Player: amplified HARM only ->hurt(damageSources.source(TFDamageTypes.FAILED_CHALLENGE),(float)(6<<amp)); native Strong Harming amp1 requests12. Inverted Player: EVERY non-HARM amplified effect meets predicate, including noninstant strong Speed/Poison; HARM falls through normal inverted-healing branch. Code does not restrict that side to HEAL/instantaneous. A legitimate inverted Player producer is not proven by this TF method; future inverted fixture must obtain real native eligibility, never manufacture it. Java shift/int overflow semantics retained for nonordinary amplifiers. No direct setHealth/SHP operation.',
      'failed_source':'One-argument native DamageSources.source(key) ->DamageSource(holder) has direct=null, causing=null and explicit sourcePosition=null. FAILED_CHALLENGE declaration exhaustion0, message twilightforest.failedChallenge, scaling when_caused_by_living_non_player. Installed TF+raw native tag closure has no membership: no armor/effect/Resistance/Enchantment/invulnerability/cooldown bypass, no IS_FIRE/IS_PROJECTILE/IS_EXPLOSION or magic/physical/environment tag identity. Potion origin is delivery context only. Ordinary native armor/toughness, Protection, Resistance, absorption, player invulnerability and cooldown remain. Null causing entity does not satisfy living-non-player difficulty scaling. Despite no BYPASSES_SHIELD tag, native directional shield cannot block this null-position source (getSourcePosition null); generic loader block hooks remain conditional. hurt return ignored: following effects/tracking/stat/dose/breakage continue even if request rejected/mitigated. Only advancement trigger below checks player alive, not effect loop/resource code.',
      'flask_tracking':'Server noncreative nonspectator Player with basepotion Holder records FLASK_DOSES attachment after effects. Same Holder increments doses; different resets count1 and start gameTime, then stores Holder. Alive player triggers DrinkFromFlask with floor(float(gameTime-start)/20) seconds and exact native dose/time/HolderMatcher criterion. EntityEvents resetFlaskLogic on an earned advancement containing DrinkFromFlask trigger resets count0/Holdernull, retaining time field. Attachment defaults null/0/0 and serializes those values, no copyOnDeath; no combat buff or separate HP. TFAdvancementGenerator.flaskWithHarming creates a four-dose unbreakable Brittle icon; this data-generation display is not a survival capacity/default recipe. Persistent/network PotionFlaskComponent codec stores potion/doses/breakage/breakable without independent numeric bounds.',
      'experiment_item':'Experiment115Item food4/.3 and ordinary food completion, plus ServerPlayer slice statistic. useOn same Experiment115 block returnsPASS to its block handler; on another block with Player&&!secondary tries native placement, falling back to native food use when placement did not consume action and FOOD exists. Secondary use returnsPASS. Genuine default placed block has BITES_TAKEN7 (one portion), REGENERATEfalse. Component EXPERIMENT_115_VARIANTS selects presentation/advancement icons, no combat effect producer in caller scan.',
      'experiment_block':'Block native no-item use requires Player.canEat(false), immediately adds FoodData4/.3 without item-use32tick delay, awards stats/criterion and increases bites by1 or removes block when oldbites7. This is food resource, not direct heal. Nonsecondary item use with Experiment115 requires bites>0, decreasesbites1 and consumes item1; full0 returnsFAIL. Redstone on full0 nonregenerating block consumes1 and sets REGENERATEtrue. Secondary item use only on nonregenerating block removes one portion and gives native item unlesscreative; last portion removesblock. Native ItemStack.consume respects infinite materials; eating block still removesportion for invulnerable Player. Server randomTick if regenerate&&bites!=0 decreasesbites1, no additional TF chance gate; no ticks after removed. Thus eating finalportion destroys even regenerating block, not inexhaustible instant healing. Belowblock must isSolid; loss of lower support makes AIR; noLootTable and native randomTicks registered. Comparator=8-bites+(regen?7:0), redstone=regen?15-2*bites:0, no direct damage/effect pulse.',
      'essence':'EssenceBerryItem is not FOOD. Either-hand use consumes1 via native consume, server creates actual ExperienceOrb atplayer(x,y+1,z) value6+random.nextInt14=6..19, addFreshEntity; returns sidedSuccess. Infinite-material stack preserved; orb still created by actual use. No direct grantExperiencePoints/heal or personal ownership restriction. Native orb motion/merging/pickup/despawn/ordinary entity admission remain. Exact244 orb playerTouch ServerPlayer with takeXpDelay0 posts cancelable PickupXp; if allowed setsdelay2, then repairPlayerItems before positive residual XP. Native random eligible damaged REPAIR_WITH_XP item and actual getXpRepairRatio/enchantment durability conversion determine repair, recursive leftover accounting; not a fixed TF repair/heal. Another player can pick up actual orb. Oreberry bush harvest/hazard reviewed later, not inferred closed by item consumption.',
      'compatibility':'Native TF source paths use actual inventory/menu/food/effect/XP hooks and no Curios-specific consumer. Generic conditional loader hooks for item stacking/use, effect applicability/merge, heal/damage/block and XP pickup/repair are present. Direct external source-specific compatibility NONE_PROVEN in reviewed food/flask implementation; this is scoped static attribution, not pack-wide compatibility certification. Existing accepted source/effect hooks remain untouched. All fixtures listed are future genuine native deliveries; no runtime test, source injection, direct HP/SHP write or fixes performed.'
    }
    I='init/TFItems';F='item/BrittleFlaskItem';G='item/GreaterFlaskItem';C='components/item/PotionFlaskComponent';S='item/StackableEffectItem';E='block/Experiment115Block';T='components/entity/PotionFlaskTrackingAttachment';X='item/EssenceBerryItem'
    nxt='Review remaining utility/map items (Pocket Watch, transformation and terrain tools, native map/landmark ASM), then passive entities, environmental hazards and nine unfinished custom DamageTypes. Close remaining installed ASM/compatibility/source exclusions, protect R2f8 and promote full Twilight COMPLETE before IceAndFire. No runtime/L2/Stage/production/Phase6/7.'
    data=dict(slug='food-flasks',checkpoint_short='r2f8r',checkpoint='R2f8r-food-flasks-complete',decision='TWILIGHT_FOOD_FLASKS_SEMANTIC_REVIEW_COMPLETE',starting_sha='723f5d70964592ece674c7ab3d93e71e8f3fe69b',previous_checkpoint='R2f8q-travellers-utility-complete',previous_draft='partial-drafts/twilightforest-r2f8q-partial.json',facts=facts,packages=[],paths=[],new_damage_types=1,full_classes=FULL,limited_classes={'events/EntityEvents':['setup/resetFlaskLogic'],'data/TFAdvancementGenerator':['flaskWithHarming icon only']},registration_classes=[I,'init/TFBlocks','init/TFDataComponents','init/TFDataAttachments','init/TFAdvancements'],closure_checklist=['all_registered_food_parameter_sets','native_consumption_and_food_resource','food_effect_payloads','custom_duration_extension_vs_native_merge','native_poison_loader_source','flask_donor_component_admission','menu_hook_order','doses_breakage_creative_persistence','native_instant_effect_chain','failed_challenge_exact_predicate','ownerless_null_position_damage','native_tags_mitigation_hurt_return','advancement_icon_vs_survival_source','experiment_item_block_regeneration','real_experience_orb_pickup_and_repair'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus food/flask consumption, FAILED_CHALLENGE, Experiment115 block resource and Essence Berry native XP. Twilight PARTIAL, zero promoted;31/40 custom types,9 unfinished.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=30,new_used_profiles=1,reviewed_profiles_after=31,remaining_profiles=9,remaining_disposition='Other actual callers unfinished, not unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,controls):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=controls));return eid
    nutrition=pkg('food_nutrition','Twilight native food nutrition and saturation','VANILLA_DIRECT',['food_admission','food_values','hunger_health'],[I,S,'item/HydraChopItem','item/Experiment115Item'],{'normal_use_ticks':32,'fast_use_ticks':16,'saturation_formula':'nutrition*modifier*2'},['native food use','canEat','actualstackfood','nativehealing'], 'Native food resource with installed parameters.','Genuine native food consumption',['full/hungry/invulnerable','bowl return','naturalRegeneration gamerule'])
    torch=pkg('torchberry_glowing','Torchberry native Glowing','VANILLA_DIRECT',['food_admission','torchberries'],[I],{'ticks':100,'amplifier':0,'chance':.75},['consume','native random/effect eligibility'],'Native Glowing effect.','Native Torchberries consumption',['failed roll','full food','effect merge'])
    hydra=pkg('hydra_chop_regeneration','Hydra Chop native Regeneration','VANILLA_DIRECT',['food_admission','hydra_chop'],[I,'item/HydraChopItem'],{'ticks':100,'amplifier':0,'chance':1},['consume','native heal eligibility'],'Native Regeneration plus noncombat criterion.','Native Hydra Chop consumption',['empty-food criterion','full-food denial','effect immunity/merge'])
    stro=pkg('stroganoff_native_effects','Meef Stroganoff native Fire Resistance and Strength','VANILLA_COMPOSITE',['food_admission','stroganoff'],[I],{'fire_resistance_ticks':3600,'strength_ticks':2400,'amplifier':0},['consume','native effect gates','real source IS_FIRE'],'Two native status payloads.','Native Stroganoff consumption',['fire-tag contrast','bowl remainder','native melee vs final HP'])
    speed=pkg('slime_food_speed','Gelatinous Slime Drop native Speed','VANILLA_DIRECT',['food_admission','slime_food'],[I],{'ticks':600,'amplifier':0,'movement_total_modifier':.2},['consume','native effect eligibility'],'Native Speed.','Native Slime Drop consumption',['stack/effect merge','hungry control'])
    resist=pkg('maze_slime_food_resistance','Gelatinous Maze Slime Drop native Resistance','VANILLA_DIRECT',['food_admission','slime_food'],[I],{'ticks':600,'amplifier':0,'ordinary_reduction':.2},['consume','native effect and source bypass gates'],'Native Resistance.','Native Maze Slime Drop consumption',['ordinary vs bypass sources','effect duration merge'])
    berries=pkg('berry_duration_extension','Twilight probabilistic berry duration extension','VANILLA_LIKE_EXTENDED',['food_admission','berry_stack','berry_payloads','berry_damage'],[I,S,S+'$StackableEffectInstance'],{'amplifier':0,'duration_rule':'current+extra','roll_rule':'chance>=randomFloat'},['server completion','independentrolls','native eligibility/merge'],'Custom duration arithmetic over native effects.','Native Blight/Dusk/Sky/Stingberry consumption',['existing stronger/infinite','independent negatives','actual native later DOT'])
    flask=pkg('potion_flask_resource','Brittle/Greater flask dose and breakage resource','CUSTOM_RESOURCE',['flask_fill','flask_resource','flask_tracking'],[F,G,C,T,'events/EntityEvents'],{'fresh_capacity':3,'brittle_breakage_limit':3,'use_ticks':32},['secondary actual component donor','native menu','same contents or emptybase','doses/capacity'],'Custom persistent native-item reservoir.','Genuine filled Brittle/Greater flask',['donor variants','stack split','native32tick drink','creative','save/load'])
    potion=pkg('flask_native_effect_delivery','Flask native potion effect delivery','VANILLA_COMPOSITE',['flask_native_payload','flask_resource','flask_tracking'],[F,C],{'instant_effect_strength':1,'normal_harm_I_request':6,'normal_heal_I':4,'normal_heal_II':8},['Player','server','nonemptyidentity','custom branch exclusion','native eligibility'],'Actual native instant/status callbacks.','Native flask dose with genuine potion component',['HarmI/HealingI/II','noninstant','custom list order','returnfalse still consumes'])
    challenge=pkg('flask_failed_challenge','Flask failed-challenge ownerless damage','CUSTOM_DAMAGE',['failed_challenge','failed_source','flask_resource'],[F],{'ordinary_Harming_II_request':12,'formula':'float(6 << amplifier)'},['Player','server','(isHarm != inverted) && amp>0'],'Custom DamageType request with native mitigation.','Native Strong Harming flask dose',['HarmI control','armor/Resistance','null shield position','cooldown/creative','legitimate inverted eligibility only'])
    experiment=pkg('experiment_115_food_resource','Experiment115 portion storage and regeneration','CUSTOM_RESOURCE',['experiment_item','experiment_block','food_admission','hunger_health'],['item/Experiment115Item',E,I,'init/TFBlocks'],{'initial_bites':7,'max_portions':8,'food_per_portion':4,'saturation_modifier':.3},['native placement/use','canEat','full block forredstone','server randomticks','solid support'],'Custom renewable block resource delivering native food.','Native Experiment115 item/block interactions',['refill','redstone','lastportion removal','secondary extraction','support loss'])
    xp=pkg('essence_berry_experience','Essence Berry native experience orb','VANILLA_DIRECT',['essence','compatibility'],[X,I],{'minimum_xp':6,'maximum_xp':19,'spawn_y_offset':1},['native use','server orb','native pickup/repair'],'Native XP entity delivery.','Native Essence Berry either-hand use',['another collector','PickupXp cancellation','Mending before XP','infinite materials'])
    data['damage_profiles']=[dict(type='twilightforest:failed_challenge',status='USED',amount='(float)(6 << amplifier), ordinary Strong Harming amp1 requests12; never asserted final HP.',direct_and_causing_entities='Both null, explicit sourcePosition null: native one-argument source(key). No owner/projectile.',callers=[dict(entry='twilightforest/item/BrittleFlaskItem.class',method='finishUsingItem')],admission='Player/server, nonempty potion identity, (isHARM != invertedHealAndHarm) && amp>0 before instant predicate. Armor/Resistance/Protection/invulnerability/cooldown native. No native tags. Directional shield lacks nonnull source position.',hurt_return_dependency='Ignored; later effects/tracking/stat/dose/breakage proceed. No direct health subtraction or secondary attack callback.')]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:food_flasks_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through genuine installed item/block/menu consumption; future fixture, runtime0.',future_controls=controls))
    rows=[
      ('ordinary_food','Native plain foods and jerky nutrition',['food_admission','food_values','hunger_health'],[nutrition],[I],['ACTIVE_ITEM'],['all listed nutrition/modifier sets','no inferred poison','hunger regen distinct']),
      ('bowl_food','Native soup/medley food and bowl return',['food_admission','food_values'],[nutrition],[I],['ACTIVE_ITEM'],['stack1','native remainder','infinite materials']),
      ('plain_berries','Native four plain fast berries',['food_admission','berry_stack'],[nutrition],[I,S],['ACTIVE_ITEM'],['empty varargs bytecode','16ticks','no added status']),
      ('torch','Native Torchberries consumption',['food_admission','torchberries'],[nutrition,torch],[I],['ACTIVE_ITEM'],['fullfood allowed','p.75','0nutrition']),
      ('hydra','Native Hydra Chop consumption',['food_admission','hydra_chop'],[nutrition,hydra],[I,'item/HydraChopItem'],['ACTIVE_ITEM'],['hungry','criteriononly at<=0','heal ticks not instant']),
      ('stroganoff','Native Meef Stroganoff consumption',['food_admission','stroganoff'],[nutrition,stro],[I],['ACTIVE_ITEM'],['two effects','bowl','fire tag vs item fireResistant']),
      ('slime','Native Slime Drop food effect',['food_admission','slime_food'],[nutrition,speed],[I],['ACTIVE_ITEM'],['600ticks','native speed attr']),
      ('maze_slime','Native Maze Slime Drop food effect',['food_admission','slime_food'],[nutrition,resist],[I],['ACTIVE_ITEM'],['600ticks','native source bypass eligibility']),
      ('blight','Native Blightberry independent regeneration/poison/wither',['berry_stack','berry_payloads','berry_damage'],[nutrition,berries],[I,S],['ACTIVE_ITEM'],['160/100/100 ticks','1/.75/.15','later native DOT sources']),
      ('dusk','Native Duskberry vision and blindness',['berry_stack','berry_payloads'],[nutrition,berries],[I,S],['ACTIVE_ITEM'],['300/60 ticks','1/.75','native vision effects']),
      ('sky','Native Skyberry jump and slow',['berry_stack','berry_payloads'],[nutrition,berries],[I,S],['ACTIVE_ITEM'],['160/60 ticks','1/.75','jump/safeFall vs speed']),
      ('sting','Native Stingberry strength and fatigue',['berry_stack','berry_payloads'],[nutrition,berries],[I,S],['ACTIVE_ITEM'],['200/200 ticks','1/.75','attack damage/speed and mining']),
      ('berry_merge','Native berry existing-effect merge controls',['berry_stack','berry_damage'],[berries],[S],['ACTIVE_ITEM'],['stronger/hidden/infinite','duration arithmetic','addEffect rejection','no amp stacking']),
      ('flask_slot','Native flask in slot filled from cursor',['flask_fill','flask_resource'],[flask],[F,C],['OTHER'],['secondary','samecontents','cap','bottle/overflow','menuevent']),
      ('flask_cursor','Native carried flask filled from slot',['flask_fill','flask_resource'],[flask],[F,C],['OTHER'],['secondary','actual component','noTFallowModification','native dispatcher']),
      ('flask_donor','Native splash/lingering/tipped-arrow flask donors',['flask_fill','flask_resource'],[flask],[F,C],['OTHER'],['notPotionItemrestricted','donor1','bottle','genuine native components']),
      ('brittle','Native Brittle flask use/breakage',['flask_resource','flask_tracking'],[flask],[F,C,T],['ACTIVE_ITEM'],['32tick','capacity3-breakage','thirdconsume breaks','save/load']),
      ('greater','Native Greater flask use/refill',['flask_resource'],[flask],[G,F,C],['ACTIVE_ITEM'],['unbreakable','three dose capacity','stack1','no break/crack']),
      ('flask_stack','Native stacked flask copy/overflow',['flask_fill','flask_resource'],[flask],[F,C],['OTHER','ACTIVE_ITEM'],['count>1 split','mutateone','inventoryadd/drop','customonly holder boundary']),
      ('flask_creative','Native creative and empty flask controls',['flask_resource','flask_native_payload'],[flask,potion],[F,C],['ACTIVE_ITEM'],['no resource cost','effects eligibility','empty identity','zero dosesuse denied']),
      ('flask_noninstant','Native noninstant flask potion effects',['flask_native_payload','flask_resource'],[potion,flask],[F,C],['ACTIVE_ITEM'],['real potion payload','copy instance','native merge','no second parent effect']),
      ('flask_instant','Native flask Healing and HarmingI callbacks',['flask_native_payload'],[potion],[F],['ACTIVE_ITEM'],['self direct/cause','6magic vs4/8heal','actual inversion','native heal/damage gates']),
      ('flask_challenge','Native Strong Harming FAILED_CHALLENGE',['failed_challenge','failed_source','flask_resource'],[challenge,flask],[F],['ACTIVE_ITEM'],['request12','ownerless','ordinary mitigation','shield nullposition','returnignored']),
      ('flask_inverted','Native inverted-player flask predicate boundary',['failed_challenge','flask_native_payload'],[challenge,potion],[F],['ACTIVE_ITEM'],['legitimate inversionrequired','all nonHARMamp>0','not instantrestricted','no fabricated eligibility']),
      ('flask_sequence','Native flask multiple-effect and hurt rejection sequence',['flask_native_payload','failed_source','flask_resource'],[potion,challenge,flask],[F,C],['ACTIVE_ITEM'],['base thencustom','cooldown','subsequent effects/cost','actual component producers only']),
      ('flask_tracking','Native flask tracking/criterion/save controls',['flask_tracking'],[flask],[T,'events/EntityEvents','advancements/DrinkFromFlaskTrigger','data/TFAdvancementGenerator'],['OTHER'],['sameHolder','aliveonly criterion','reset onearnedadvancement','four-doseicon not survival']),
      ('experiment_eat','Native Experiment115 handheld food',['experiment_item','food_admission'],[nutrition,experiment],['item/Experiment115Item'],['ACTIVE_ITEM'],['ordinary food duration','stat only','presentationvariant']),
      ('experiment_place','Native Experiment115 placement/fallback',['experiment_item'],[experiment],['item/Experiment115Item',E],['ACTIVE_ITEM','ENVIRONMENT'],['sameblockPASS','nonsecondary','native placement fails ->fooduse','oneportiondefault']),
      ('experiment_portion','Native Experiment115 direct block eating',['experiment_block','hunger_health'],[nutrition,experiment],[E],['ACTIVE_ITEM','ENVIRONMENT'],['canEat','immediate FoodData not heal','finalportionremoves evenregen']),
      ('experiment_refill','Native Experiment115 portion refill/extraction',['experiment_block'],[experiment],[E],['ACTIVE_ITEM','ENVIRONMENT'],['fullfails refill','secondaryonlynonregen','creative extractionnoitem','nativeconsume']),
      ('experiment_regen','Native full Experiment115 redstone and random tick',['experiment_block'],[experiment],[E,'init/TFBlocks'],['ENVIRONMENT','ACTIVE_ITEM'],['full0 redstone','server randomtick','solid support','signalnotdamage']),
      ('essence_use','Native Essence Berry orb creation',['essence'],[xp],[X],['ACTIVE_ITEM'],['eitherhand','6..19','y+1','nativeconsume/infinite']),
      ('essence_pickup','Native Essence Berry actual orb pickup and repair',['essence','compatibility'],[xp],[X],['OTHER'],['PickupXp cancel','takeXpDelay','anotherplayer','native Mending before residualXP'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-food-flasks-caller-scan.json','reference-evidence/twilight-equipment-244.json','reference-evidence/twilight-travellers-core-244.json','reference-evidence/vv-loader-244.json','reference-evidence/cult-loader-244.json']
    data['exclusions']=['All food/flask/Experiment115/Essence Berry item contracts listed are reviewed, including actual native superclass/effect/damage/XP comparisons. Full registration food parameter sets pinned; recipes/loot witnesses retain source acquisition.','No invented food poisoning from names; ore berries iron/gold/copper are plain material items. Stale Bread is protected custom sword source, not food.','Brittle four-dose advancement icon and custom-only/inverted predicate boundaries are not invented survival fixture producers. Native data/menu/eligibility retained.','Tooltip/model/variant/criterion outputs do not add combat payloads; bush hazards/harvest and other utility/passive/ASM closure remain later scope.','No runtime boss/L2/Stage/production tests or changes. Twilight remains PARTIAL with31/40 custom source profiles;9 ordinary unfinished sources are not REVIEW_REQUIRED.']
    data['fixture_groups']=['All native food nutrition/saturation/full-food/remainder controls and actual native regeneration/effects.','Genuine four special berries, independent rolls, existing status merge and true native later damage/heal sources.','Both real flask click directions, component donors, split/overflow, doses/breakage/creative and save/load.','Native HarmingI/II and Healing flask positive controls with exact direct/cause/source tags, shield null-position, rejected hurt and separate resource costs.','Actual Experiment115 placement/food/block portion/refill/redstone/randomtick/support lifecycle.','Genuine Essence Berry orb creation and ordinary pickup/XP repair, no direct XP/HP simulation.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=1)
    write_json(OUT/'review-inputs/twilightforest-food-flasks.json',data);assemble('twilightforest-food-flasks.json')

if __name__=='__main__':build()
