"""Last two custom sources and real Ominous/progression resource paths."""
from catalog_common import *
from collect_twilight_ominous_progression import FULL,BATCH,FIELDS
from twilight_subsection import assemble
from collections import Counter

def build():
    F='block/OminousFireBlock';I='item/ExanimateEssenceItem';E='events/EntityEvents';W='util/entities/OminousFireDamageSource';R='item/recipe/EssenceRepairRecipe';P='events/ProgressionEvents';N='init/custom/Enforcements';B='util/Enforcement'
    facts={
      'authority':'Installed TF4.8.3345 and exact Minecraft1.21.1/NeoForge21.1.244. Ominous Fire and Acid Rain are USED; all40 custom DamageType profiles now reviewed. This does not close whole Twilight: remaining structures/events/ASM/compatibility/source exclusions and final assembly still unfinished. Static only; runtime0; production/Stage/L2/Phase6/7 untouched.',
      'identity':'Both use TFDamageTypes.getDamageSource: direct=null,causing=null,explicit/source position=null. Ominous exhaustion.1 and Acid Rain0, declarations when_caused_by_living_non_player but no causing entity so no difficulty scaling. Ominous tags BYPASSES_ARMOR,BYPASSES_SHIELD,NO_KNOCKBACK,PANIC_CAUSES,PANIC_ENVIRONMENTAL_CAUSES,WITHER_IMMUNE_TO,neoforge:is_magic; NOT IS_FIRE/IS_EXPLOSION/IS_PROJECTILE or environment/physical. Acid Rain tags BYPASSES_ARMOR,BYPASSES_SHIELD,BYPASSES_WOLF_ARMOR,NO_KNOCKBACK,WITCH_RESISTANT_TO,neoforge:is_environment/is_magic; NOT fire/projectile/explosion. Feedback effects=burning on Ominous is not ignition.',
      'native_admission':'Both retain recipient invulnerability/client/dead, normal hurt cooldown, incoming/damage events, Resistance max(1-.2*(amp+1),0), applicable protection and absorption. Armor/shield are bypassed by actual tags, not by the source name; neither bypasses effects, Resistance, enchantments, cooldown or invulnerability. NO_KNOCKBACK suppresses ordinary fresh-hit hurt movement. Fire Resistance and fireImmune provide no type-based immunity because neither source is IS_FIRE. Native directional shield geometry is irrelevant to bypass tag, though loader shield hooks remain. Ominous lacks IGNITES_ARMOR_STANDS/CAN_BREAK_ARMOR_STAND; native stand override rejects. ItemEntity uses native item-health handling; ordinary fire-resistant item tagging is not an Ominous immunity. Wither own WITHER_IMMUNE_TO rejection and Witch WITCH_RESISTANT_TO reduction remain native; acid caller is Player-only, so do not fabricate Witch/Wolf exposure.',
      'ominous_contact':'OminousFireBlock extends BaseFireBlock but overrides entityInside WITHOUT parent call. It skips any EntityType tagged minecraft:undead; all other Entity recipients request ownerless ominous_fire1. Hurt return discarded. No fireImmune, living-only, movement, age, crouch or explicit side predicate in body; native recipient performs admission. No native in_fire request, fire-timer increment,8second ignition or Frosted fire-downrank from this custom type. Fire-immune non-undead targets are not exempt here. Undead tag is independent of inverted heal/harm.',
      'ominous_block':'Survival requires below face sturdyUP and current fluid empty. updateShape returns default Ominous Fire ifvalid elseAIR. canBurn always true only supplies inherited base-fire behavior; there is no FireBlock spreading/random-age tick in this class hierarchy. Registered no collision/replaceable/light15; actual loot table has no drops. Native BaseFireBlock.onPlace remains: on actual block change, Ominous block is in minecraft:fire block tag (independent of DamageType tags); Overworld/Nether empty portal shape and onTrySpawnPortal hook can replace with ordinary Nether portal, else native survival/removal. No guaranteed permanent fire or invented dimension bypass. Native player destroy/extinguish handling remains; clone pick gives Exanimate Essence.',
      'essence_delivery':'ExanimateEssence.useOn first checks clicked real CandleBlock in17-entry vanilla CANDLE_MAP and LIT: replaces with matching Ominous Candle, preserving count1..4. Otherwise uses clickedPos.relative(face), requires canBeReplaced and OminousFire.canSurvive then writes Ominous Fire. Sound/BLOCK_PLACE and true flag follow branch; shrink1 whenflag, regardless setBlock return and without local creative exemption; sidedSuccess. Actual native ServerPlayerGameMode creative path restores original count after item use. Normal use/placement/event admission remains; no private helper or free damage delivery. Existing loot/recipe resources supply actual essence; protected Renewal use remains unchanged.',
      'candle_exclusion':'Ominous Candle extends BaseEntityBlock, not OminousFireBlock/AbstractCandleBlock. No hurt, fire timer, conversion, entityInside override or ticking combat payload. CANDLES geometry/light and visual BE height fields are cosmetic/native terrain state. Empty-hand mayBuild interaction replaces with corresponding unlit ordinary candle at same count and calls extinguish; matching candle BlockItem can add until4, consumes1 via native infinite-material handling, sends actual placement criterion/stat/event. BE only stores transient visual heights, no custom persistent attack/owner. Candelabra separate OMINOUS lighting use accepts scepter or essence only from NORMAL, with no essence consumption in that branch; no Ominous Fire block or custom damage is emitted by that inspected callback. Wider Candelabra/source exclusions remain global closure.',
      'death_conversion':'Registered EntityEvents LivingDeathEvent callback requires not canceled and exact source key OMINOUS_FIRE. A mere burning timer or class named OminousFireDamageSource is insufficient. Native totem/death prevention before die means no conversion event. For non-ServerPlayer, actual OMINOUS_FIRE entity-type data map must exist and level must beServerLevel; installed mappings Horse->ZombieHorse, Piglin->ZombifiedPiglin, Villager->ZombieVillager. Calls protected EntityUtil.convertEntity and ignores return; no event cancellation or alternate new type guessed from undead names.',
      'conversion_consequences':'Protected generic conversion creates target, honors canLivingConvert for Living target, uses Mob.convertTo for Mob pairs (copy/clear equipment, native entity add, discardold), otherwise real addition/discard. Then overlays old NBT onto new NBT, restoresnewUUID, sets Living health to resultingmax, drops/clears equipment, preserves passenger rides and conversion callback. It is replacement/full-health initialization, not native heal or direct attack. On ordinary LivingEntity.die, death event precedes !isRemoved&&!dead: successful discard of old Mob suppresses its later normal death-loot branch. Failed/vetoed conversion leaves ordinary death to continue. Generic helper behavior reused unchanged; no duplicate Powder package.',
      'player_zombie':'ServerPlayer death branch takes precedence over data-map membership: creates actual EntityType.ZOMBIE, attaches deceased GameProfile, custom player name, copiesposition, requests canPickUpLoottrue and babyfalse, THEN EventHooks.finalizeMobSpawn(CONVERSION,null), THEN addFreshEntity. No inventory/XP/player-health transfer, resurrection, allegiance or owner assignment. Native Zombie.finalizeSpawn can overwrite loot pickup withrandom<.55*specialDifficulty and can setbabytrue from native groupdata; thus adult/loottrue setters are NOT final guarantees. Native equipment/enchantment/door/jockey/difficulty attributes can apply; no spawn-obstruction check in TF caller, native finalization/add hooks remain. No null guard after Zombie.create in caller; no invented fallback. Player death event is not canceled and normal player death/keep-inventory processing continues. Profile attachment serializes SIMPLE_GAME_PROFILE; customname/native Zombie state save normally, no custom lifespan.',
      'zombie_reentry':'Registered LivingIncomingDamageEvent callback: source not already OminousFireDamageSource, causingentity instanceof Zombie, zombie.hasData(ZOMBIFIED_PLAYER). Captures event.getAmount, cancels original, then recipient.hurt(new OminousFireDamageSource(original),amount), ignores nested return. Wrapper retains original typeHolder, but constructor passes original.getEntity as native DIRECT and original.getDirectEntity as native CAUSING; explicitposition=original.getSourcePosition. For genuine melee both entities are the same Zombie, so attribution is unchanged. A conditional indirect source would swap them; no native ranged-zombie source is invented. Guard prevents this callback recursively wrapping its own nested source. Normal nested native eligibility/defenses/events remain; it is not type ominous_fire unless original already was.',
      'reentry_effects':'Original IncomingDamage cancellation makes ordinary LivingEntity.hurt returnfalse while nested hurt can independently succeed. Genuine Zombie melee therefore skips caller success-only Mob extra knockback/EnchantmentHelper.doPostAttackEffects/setLastHurtMob/playAttackSound and Zombie burning-attacker ignition; native recipient hurt feedback from nested hit can still occur. Player.hurt applies source scaling before Living incoming event, so nested virtual Player.hurt applies it again. With ordinary default mob_attack, no modifying external hooks and standard defenses pending: Hard maps inputx to2.25x across two1.5 passes; Easy applies min(x/2+1,x) twice; Normal unchanged; Peaceful returnszero before event. Not double damage requests that both admit: outer canceled, one nested processing path. Other subscribed incoming hooks may observe both dispatches according to native event order; no pack-wide count guarantee.',
      'death_message':'Wrapper getLocalizedDeathMessage checks living.getKillCredit instanceof Zombie carrying profile. If victim isPlayer and its profileNAME equals stored profileNAME, selects self message; otherwise includes profile name. Not UUID ownership/hostility logic. Fallback delegates ordinary source death message. Genuine Zombie attack keeps mob_attack damage tags/mitigation and does not by itself trigger Ominous death conversion.',
      'enforcement_delivery':'Actual registered PlayerTick.Post callback requires ServerPlayer/ServerLevel; every20player ticks, tfEnforcedProgression gameruletrue, !creative&&!spectator invokes Enforcement.enforceBiomeProgression. No TF dimension, rain, sky visibility, shelter, height, biome-weather or line-of-sight gate in this chain. Level biome at player.blockPosition -> same-ID Restriction registry lookup; missing biomekey/registry/restriction ->none. Requires player lacks required advancement. Calls registered enforcement consumer then optional StructureHints.tryHintForStructure regardless whether consumer applied payload that tick. Hint-monster mechanics and structure protection are separate subsequent closure work. Gamerule defaulttrue; actual world value remains runtime state, not inferred installedtrue.',
      'advancement_gate':'Restriction stores rawfloat multiplier, optionalhint/toast and nonempty advancement list. PlayerHelper.playerHasRequiredAdvancements consumes ONLY FIRST iterable entry: emptylisttrue; server first advancement mustexist and isDone, missing=false; client first progressanalog. It does not AND all entries. Installed nine restriction lists each have one so no default contradiction, but reload/custom multi-entry behavior must be preserved. This exact helper was already pinned during Frosted review; no reopening of Frosted mechanics.',
      'acid_payload':'Acid Rain consumer checks player.tickCount%5==0 and tickRateManager.runsNormally, then hurt(ownerlessacid_rain,restriction.multiplier); only ifhurtreturnsTRUE plays burn sound atplayer. Actual every20 outer caller means opportunities every20 ticks, not5; no native weather requirement. Installed Highlands .5 requires progress_merge, Thornlands1 requires progress_troll, FinalPlateau1.5 requires progress_troll. No secondary potion, fire timer, armor corrosion, equipment damage or native poison. Normal cooldown/absorption/Resistance/protection can change HP and return; a sound is not guaranteed positive HP loss.',
      'other_consumers':'Same real outer biome path: Darkness every60ticks+normaltickrate adds vanillaDARKNESS duration200, amplifier(int)multiplier(default0), ambientfalse,particlestrue; native darkness blend22/no damaging server effect. Hunger every60 adds vanillaHUNGER duration100 withamp=currentamp+(int)multiplier else(int)multiplier(default1), native add/merge/cure; stacks while current persists. Native Hunger server effect adds .005*(amp+1) exhaustion per callback through native player food processing, not direct HP. Fire every60+normaltickrate invokes igniteForSeconds((float)(int)multiplier), default8 forFireSwamp, requiring progress_labyrinth. Native floor(seconds*20), then Living ceil(ticks*BURNING_TIME attribute), then Entity monotonic timer extension retained; subsequent on_fire source separate. Frost every60 adds protected Frosted100 amp0 SnowyForest or1 Glacier; reuse accepted package/path, no repeat review. Darkness sitesDarkForest progress_lich andDarkForestCenter progress_knights; Swamp Hunger progress_lich.',
      'essence_repair':'Distinct genuine CRAFTING EssenceRepairRecipe requires one nonempty damaged SCEPTERS-tag stack plus one nonempty exact ExanimateEssence stack and no other occupiedslots; two essence slots or two scepters reject, stackcounts are not slotcounts. Output copies original scepter including components/count and setsDamage0. assemble alone does not revalidate essence, but actual recipe lookup/matches is admission. Dimensions area>=2. Native ResultSlot consumes one per occupiedslot and ordinary recipe remainders; no creative exemption invented. No enchantment restriction or requirement for fully exhausted charges. This fully repairs custom scepter charge resource without casting; distinct from protected nine-point manual recipes and automatic Renewal.',
      'compatibility':'GENERIC_CONDITIONAL_PRESENT for loader hurt/incoming/death/conversion/finalize/add/placement/effect/recipe hooks. Source-specific TF wrapper and TF advancement/restriction consumers are native TF mechanics. Recipe-viewer Ominous displays describe mappings, not actual conversion callers. Other external combat overrides scoped NONE_PROVEN; additional mod interactions UNKNOWN, no pack-wide compatibility certification. Protected Frosted, Powder conversion and scepter Renewal preserved. Remaining structures,portal/hints,events,ASM and source exclusions still ordinary unfinished review.'
    }
    nxt='All40 custom DamageTypes are reviewed. Continue remaining Twilight structure defenses/hint producers and portal/control blocks, then remaining events/nested ASM/compatibility/source exclusions. Protect R2f8 complete and final Twilight dedup/promotion; IceAndFire only after live-verified Twilight COMPLETE. Static only.'
    data=dict(slug='ominous-progression',checkpoint_short='r2f8y',checkpoint='R2f8y-ominous-progression-complete',decision='TWILIGHT_OMINOUS_PROGRESSION_SEMANTIC_REVIEW_COMPLETE',starting_sha=git('rev-parse','HEAD').strip(),previous_checkpoint='R2f8x-mechanical-hazards-complete',previous_draft='partial-drafts/twilightforest-r2f8x-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=2,full_classes=FULL,limited_classes={E:['registered Ominous death/reentry and protected Frosted comparison'],P:['registered player-tick biome producer; portal/structure protection still pending'],'util/PlayerHelper':['actual first-entry advancement helper'],'util/landmarks/LandmarkUtil':['actual gamerule predicate'],'util/entities/EntityUtil':['protected native conversion reuse'],'block/CandelabraBlock':['Ominous light branch is not a hazard producer'],'world/components/structures/util/StructureHints':['dispatch only; hint spawning next']},registration_classes=['init/TFBlocks','init/TFItems','init/TFBlockEntities','init/TFRecipes','init/TFDataAttachments','init/TFDataMaps','init/TFGameRules','events/RegistrationEvents'],closure_checklist=['lasttwoactualcallers','native_damage_tags_anddefenses','ominous_no_basefire_contact','legitimate_essenceproducer','native_portal_parent_notspread','death_event_exactkey_map','conversion_removed_old_beforeloot','player_profile_spawn_finalizeordering','reentry_sourceidentity_swap','outerfalse_nestedadmission','player_difficulty_two_passes','native_attacker_success_only_callbacks','biome20outer5inner','firstadvancementonly','actualrestrictedbiomes','independentvanilla_consumers','essence_recipe_resource','candle_exclusion_persistence'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus Ominous contact/death/profile source reentry, all biome enforcement consumers and Exanimate Essence crafting repair. All40 custom types reviewed; remaining global source/structure/event/ASM work unfinished, Twilight PARTIAL zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=38,new_used_profiles=2,reviewed_profiles_after=40,remaining_profiles=0,remaining_disposition='None:40 actual caller profiles USED. Whole-mod source/ASM/compatibility closure and final promotion still pending.'))
    def pkg(key,title,kind,keys,cs,params,gates,relation,source,controls):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=cs,parameters=params,gates=gates,relation=relation,primary_test_source=source,alternate_sources=controls));return eid
    hit=pkg('ominous_fire_native_contact','Ominous Fire native non-fire contact damage','CUSTOM_DAMAGE',['identity','native_admission','ominous_contact','ominous_block','essence_delivery','candle_exclusion'],[F,I],{'request':1},['genuinecontact','notundeadtag','nativehurt'],'Custom magic type, no native fire ignition.','Actual Essence-created Ominous Fire',['FireResistance','fireimmune','undead','ArmorStand','ItemEntity','nativeportal'])
    convert=pkg('ominous_death_entity_conversion','Ominous death native mapped entity replacement','CUSTOM_CONTROL',['death_conversion','conversion_consequences'],[E,'util/entities/EntityUtil'],{'installed_mappings':3},['uncanceledLivingDeath','exacttypekey','realmap','ServerLevel','nativeconversionveto'],'Native entity replacement via protected generic helper, independent from damage admission.','Native lethal Ominous contact on actual mapped mob',['Horse','Piglin','Villager','totem','veto','removedoldloot','equipment'])
    zombie=pkg('ominous_player_zombie_production','Ominous player death profile-bearing Zombie','CUSTOM_RESOURCE',['death_conversion','player_zombie'],[E],{'create_attempts':1,'native_baby_odds':.05},['ServerPlayer','uncanceledexacttypeDeath','nativefinalize/add'],'Native Zombie creation and profile state, not player resurrection.','Genuine player death from Ominous Fire',['normaldeath','keepInventory','profileNBT','finalization','baby','lootpickup'])
    wrap=pkg('zombified_player_source_reentry','Zombified-player incoming source wrapper and native re-entry','CUSTOM_DAMAGE',['zombie_reentry','reentry_effects','death_message'],[E,W],{'hard_two_pass_multiplier':2.25},['sourcecausingZombie','hasprofile','notalreadywrapped','nativeevent/hurt'],'Custom event cancellation/retry preserving DamageType and real recipient pipeline.','Actual profile-bearing Zombie melee',['nestedhurtreject','outerfalse','nativepostattack','difficulty','sourceidentity','deathmessage'])
    acid=pkg('acid_rain_native_biome_damage','Acid Rain native biome damage','CUSTOM_DAMAGE',['identity','native_admission','enforcement_delivery','advancement_gate','acid_payload'],[P,B,N,'util/Restriction'],{'outer_period':20,'inner_period':5,'highlands':.5,'thornlands':1,'final_plateau':1.5},['ServerPlayer','gamerule','notcreative/spectator','missingadvancement','normaltickrate'],'Custom magic/environment source from real biome progression callback.','Actual locked Highlands player-tick delivery',['Thornlands','FinalPlateau','indoors','clearweather','hurtreturn_sound','gamerule'])
    dark=pkg('biome_darkness_native_status','Locked Dark Forest native Darkness','VANILLA_DIRECT',['enforcement_delivery','advancement_gate','other_consumers'],[P,B,N],{'period':60,'duration':200,'amplifier':0,'blend':22},['actualrestriction','normaltickrate','nativeaddEffect'],'Direct vanilla Darkness with real native merge/removal.','Player missing Lich advancement in Dark Forest',['DarkForestCenter','knightsadvancement','nativecure','creative'])
    hunger=pkg('biome_hunger_native_stacking','Locked Swamp native Hunger stacking','VANILLA_LIKE_EXTENDED',['enforcement_delivery','advancement_gate','other_consumers'],[P,B,N],{'period':60,'duration':100,'amplifier_increment':1,'exhaustion_coefficient':.005},['actualSwamprestriction','normaltickrate','currentHunger','nativeaddEffect'],'Custom stacking producer over native Hunger/food processing.','Player missing Lich advancement in Swamp',['existingamplifier','cure','leavebiome','nativeexhaustion'])
    ignite=pkg('biome_native_fire_enforcement','Locked Fire Swamp native ignition','VANILLA_DIRECT',['enforcement_delivery','advancement_gate','other_consumers'],[P,B,N],{'period':60,'configured_seconds':8},['actualFireSwamprestriction','normaltickrate','nativeignite'],'Native ignition/timer and later on_fire damage; no custom source.','Player missing Labyrinth advancement in Fire Swamp',['FireResistance','fireprotection','longertimer','water','leavebiome'])
    repair=pkg('scepter_essence_crafting_full_repair','Exanimate Essence native full scepter crafting repair','CUSTOM_RESOURCE',['essence_repair'],[R],{'damage_after':0,'ingredient_slots':2},['actualrecipe','damagedSCEPTERS','oneessenceslot','noextras'],'Full custom charge-resource repair via native crafting, preserving components.','Actual crafting grid with damaged scepter and essence',['partialcharges','allfourscepters','components','extraessenceslot','stackcount'])
    for n,c,m,amount,gate,follow in [('ominous_fire',F,'entityInside','1 per overlap callback',facts['ominous_contact'],facts['death_conversion']+' '+facts['conversion_consequences']+' '+facts['player_zombie']),('acid_rain',N,'lambda$static$8','restriction.multiplier: .5/1/1.5 installed',facts['enforcement_delivery']+' '+facts['acid_payload'],facts['acid_payload'])]:
        data['damage_profiles'].append(dict(type='twilightforest:'+n,status='USED',amount=amount+'; request not finalHP.',direct_and_causing_entities=facts['identity'],callers=[dict(entry='twilightforest/'+c+'.class',method=m)],admission=gate+' '+facts['native_admission'],hurt_return_dependency='Ominous caller discards return; exact-source uncanceled death gates conversion. Acid sound alone requires truehurt. '+follow,secondary_callbacks=follow,source_identity=facts['identity']))
    def path(k,title,keys,ids,cs,labels,controls):data['paths'].append(dict(id='twilightforest:ominous_progression_path:'+k,source=title,facts=keys,effect_ids=ids,classes=cs,labels=labels,setup=title+' through genuine native item/block/entity/event path; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('essence_place','Native Essence-created Ominous Fire',['essence_delivery','ominous_block'],[hit],[I,F],['ACTIVE_ITEM','ENVIRONMENT'],['clickedface','replaceable','sturdy','fluidempty','cost']),
      ('essence_creative','Native creative Essence interaction',['essence_delivery'],[hit],[I],['ACTIVE_ITEM'],['localshrink','outercountrestore','placementveto']),
      ('ominous_overlap','Native Ominous overlap custom source',['ominous_contact','native_admission'],[hit],[F],['ENVIRONMENT'],['request1','cooldown','armor/shieldbypass','Resistance']),
      ('ominous_undead','Native Ominous undead-tag exclusion',['ominous_contact'],[hit],[F],['ENVIRONMENT'],['actualtag','invertedhealharmdifferent','nohurt']),
      ('ominous_fireimmune','Ominous non-fire recipient admission',['identity','native_admission'],[hit],[F],['ENVIRONMENT'],['Blaze','FireResistance','noFrosteddownrank','noignite']),
      ('ominous_subtypes','Ominous item/stand native overrides',['native_admission'],[hit],[F],['ENVIRONMENT'],['itemhealth','fireResistantitem','ArmorStandreject']),
      ('ominous_survival','Ominous block survival and native portal parent',['ominous_block'],[hit],[F],['ENVIRONMENT'],['support','fluid','Netherportalframe','nativeportalhook','noFireBlockspread']),
      ('ominous_horse','Native lethal Ominous Horse conversion',['death_conversion','conversion_consequences'],[convert,hit],[E,F,'util/entities/EntityUtil'],['ENVIRONMENT'],['ZombieHorse','realmap','fullhealthnew','oldremoved']),
      ('ominous_piglin','Native lethal Ominous Piglin conversion',['death_conversion','conversion_consequences'],[convert,hit],[E,F,'util/entities/EntityUtil'],['ENVIRONMENT'],['ZombifiedPiglin','equipmentdrop','noordinaryoldloot']),
      ('ominous_villager','Native lethal Ominous Villager conversion',['death_conversion','conversion_consequences'],[convert,hit],[E,F,'util/entities/EntityUtil'],['ENVIRONMENT'],['ZombieVillager','genericNBT','nativeconvertveto']),
      ('ominous_survivalcontrol','Ominous totem/nonlethal/death-veto controls',['death_conversion'],[convert,zombie],[E],['ENVIRONMENT'],['totempreventsDeath','nonlethal','exactkey','eventcanceled']),
      ('ominous_unmapped','Ominous unmapped non-player death',['death_conversion'],[convert],[E],['ENVIRONMENT'],['nodata','noinventedundead','normaldeath']),
      ('ominous_player','Ominous actual player-death Zombie producer',['player_zombie'],[zombie],[E],['ENVIRONMENT','SUMMONED_ATTACK'],['actualdeath','namedprofile','position','noinventorytransfer']),
      ('ominous_finalize','Native Zombie finalization after TF setters',['player_zombie'],[zombie],[E],['SUMMONED_ATTACK'],['lootrandomoverwrite','baby5percent','equipment','jockey','addhook']),
      ('ominous_profile','Native Zombie profile persistence and later melee',['player_zombie','zombie_reentry'],[zombie,wrap],[E,W],['MOB_ATTACK'],['save/load','attachmentpresence','nativeZombieAI','noallegiance']),
      ('zombie_melee','Profile-bearing Zombie genuine native melee',['zombie_reentry','reentry_effects'],[wrap],[E,W],['MELEE','MOB_ATTACK'],['mob_attacktype','sameentityfields','nestedpipeline','outerfalse']),
      ('zombie_defenses','Wrapped melee native defense and return controls',['zombie_reentry','reentry_effects'],[wrap],[E,W],['MELEE'],['shield','armor','Resistance','cooldown','nestedfalse']),
      ('zombie_difficulty','Wrapped melee actual Player scaling re-entry',['reentry_effects'],[wrap],[E,W],['MELEE'],['EasyTwice','Hard2.25','Normal','Peacefulnoevent']),
      ('zombie_postattack','Wrapped melee outer attacker callbacks',['reentry_effects'],[wrap],[E,W],['MELEE'],['noMobpostenchant','noextraattackerknockback','noburningZombieignite','nativevictimfeedback']),
      ('zombie_deathmessage','Native wrapped-source death message',['death_message'],[wrap],[W],['MELEE'],['killcredit','profileNAME','self','fallback','notOminouskey']),
      ('acid_highlands','Native Highlands Acid Rain',['acid_payload','enforcement_delivery'],[acid],[P,B,N],['ENVIRONMENT'],['.5','progress_merge','20outerticks','noactualrain']),
      ('acid_thornlands','Native Thornlands Acid Rain',['acid_payload','enforcement_delivery'],[acid],[P,B,N],['ENVIRONMENT'],['1','progress_troll','indoors','noheightgate']),
      ('acid_plateau','Native Final Plateau Acid Rain',['acid_payload','enforcement_delivery'],[acid],[P,B,N],['ENVIRONMENT'],['1.5','progress_troll','clearweather','noLOS']),
      ('acid_gate','Native biome progression gamerule/admission',['enforcement_delivery','advancement_gate'],[acid,dark,hunger,ignite],[P,B,'util/Restriction','util/PlayerHelper'],['ENVIRONMENT'],['gameruleoff','creative','spectator','advancementmissing','firstentryonly']),
      ('acid_return','Acid Rain native mitigation and sound return',['native_admission','acid_payload'],[acid],[N],['ENVIRONMENT'],['Resistance','Protection','absorption','truehurt_sound','zeroHP']),
      ('dark_forest','Native Dark Forest Darkness',['other_consumers','enforcement_delivery'],[dark],[P,B,N],['ENVIRONMENT'],['progress_lich','200ticks','amp0','60period']),
      ('dark_center','Native Dark Forest Center Darkness',['other_consumers'],[dark],[P,B,N],['ENVIRONMENT'],['progress_knights','nativeeffectmerge','visionnotAIcontrol']),
      ('swamp_hunger','Native Swamp Hunger accumulation',['other_consumers'],[hunger],[P,B,N],['ENVIRONMENT'],['currentampplus1','100ticks','60period','nativefood']),
      ('hunger_exit','Native Hunger cure/expiry and biome exit',['other_consumers','enforcement_delivery'],[hunger],[P,B,N],['ENVIRONMENT'],['leavebiome','effectnotremovedbygate','nativecure','exhaustion']),
      ('swamp_fire','Native locked Fire Swamp ignition',['other_consumers'],[ignite],[P,B,N],['ENVIRONMENT'],['progress_labyrinth','8seconds','nativeontimer','on_fire']),
      ('fire_controls','Biome ignition native duration and recipient controls',['other_consumers'],[ignite],[P,B,N],['ENVIRONMENT'],['FireResistance','nativefireprotection','water','longertimer','tickfreeze']),
      ('essence_craft','Native Essence full scepter crafting repair',['essence_repair'],[repair],[R],['ACTIVE_ITEM'],['actualmatches','damagedtag','outputdamage0','components']),
      ('essence_craft_slots','Native Essence recipe slot/stack controls',['essence_repair'],[repair],[R],['ACTIVE_ITEM'],['twooccupiedslots','countvsitemslot','extrareject','nativeonTake'])
    ]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-ominous-progression-caller-scan.json','semantic-sections/twilightforest-active-utilities.json','semantic-sections/twilightforest-summon-resources.json']
    data['exclusions']=['Ominous Candle visual names do not emit the Ominous Fire damage source; Candelabra OMINOUS lighting callback is also not a damage/conversion producer.','Protected Frosted biome payload and Powder generic conversion reused; no duplicate Frosted or Powder mechanic.','Essence automatic Renewal was already protected; only distinct Essence CRAFTING recipe is new.','Source-wrapper death message is not a new DamageType or proof of Ominous conversion on mob_attack deaths.','All40 custom types reviewed, but remaining portal/hints/structure defenses, events, ASM and global compatibility/source closure prevent Twilight COMPLETE until finished.']
    data['fixture_groups']=['Genuine Essence/block overlap with source/type/undead/native defenses, no-fire side effects and base-fire portal controls.','Actual lethal Ominous mapped Mob conversion versus veto/totem/nonlethal and removed-old death-loot behavior.','Real player death/profile Zombie finalization/persistence and subsequent native melee re-entry, difficulty, defenses and outer success-only callbacks.','Actual PlayerTick biome enforcement with gamerule/advancement/tickrate/20tick cadence and allnine installed restrictions; no synthetic weather source.','Distinct native Essence crafting full repair versus existing Renewal/manual recharge.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=2)
    write_json(OUT/'review-inputs/twilightforest-ominous-progression.json',data);assemble('twilightforest-ominous-progression.json')
if __name__=='__main__':build()
