"""Reviewed utility activation, transformation and native alternate delivery."""
from catalog_common import *
from collect_twilight_active_utilities import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    resources=read_json(WORK/'twilightforest/resources.json')
    conversions=resources['data/twilightforest/data_maps/entity_type/transformation_powder.json']['data']['values']
    crumbles=resources['data/twilightforest/data_maps/block/crumble_horn.json']['data']['values']
    facts={
      'authority':'Installed Twilight4.8.3345/raw Minecraft1.21.1/exact NeoForge21.1.244 static authority. Completes five active utilities and actual dispenser/mining-core alternatives, including complete ToolEvents class across protected prior subsets. No new custom DamageType;31/40 reviewed,9 unfinished. No runtime/L2/Stage/production/Phase6/7 changes. Maps, structural utilities, passive entities, hazards and remaining ASM/compatibility/source closure remain unfinished.',
      'watch_inventory':'PocketWatchItem registration stack1, no damage/armor attribute. inventoryTick server and LivingEntity: slot0..8 OR40 requests native MOVEMENT_SPEED5ticks/amp0 and JUMP5/0, ambientfalse/particlesfalse/iconfalse. Independently, living.isHolding(this) requests DIG_SPEED(Haste)5/0 with same flags, regardless of this callback stack slot/held boolean. Exact244 Player.Inventory.tick passes global indices: hotbar0..8, ordinary storage9..35, armor36..39, offhand40; raw vanilla compartment indices differ. Actual hotbar/offhand refreshes Speed/Jump; any genuine ticked watch plus a held watch can refresh Haste. No callback for arbitrary stored display/belt/Curio contents is invented. Other Living native inventories require a real caller; method accepting Living is not automatic Mob inventory ticking. Native status eligibility/merge remains. After removal, the last applied short effect expires normally; no custom persistent attachment or infinite status.',
      'watch_native':'Speed native movement attribute+.2 ADD_MULTIPLIED_TOTAL at levelI, Jump native jump-power+.1 and safe-fall-distance+1, Haste native attack-speed+.1 total and ordinary mining multiplier1.2 at amp0. No direct HP, reach, invulnerability, Timewood tick acceleration or global time change. Existing stronger effects follow native merge, not amplifier stacking. Native noncombat tooltip is not another mechanism.',
      'watch_fatigue':'ToolEvents.setup registers MobEffectEvent.Applicable. preventFatigueWithPocketWatch requires event.getApplicationResult true, exact DIG_SLOWDOWN(MiningFatigue), recipient currently isHolding PocketWatch in either hand; sets DO_NOT_APPLY. Exact244 CommonHooks.canMobEffectBeApplied posts the event before addEffect/forceAddEffect merge; Applicable.getApplicationResult is APPLY OR(DEFAULT && entity.canBeAffected(instance)). A prior denial stays denied; TF does not require status source/owner, server/player type, duration, amplifier or pocket inventory position beyond held identity. It prevents eligible new applications/refreshes, does not remove an already active MiningFatigue instance, cleanse other negative effects or bypass external later listeners. Native effect loading from NBT is a different path.',
      'powder_admission':'Player interactLivingEntity checks target.isAlive, then actual held-hand powder and shrink=!player.isCreative. Helper rejects target instanceof OwnableEntity only when getOwner()!=null: resolved owner presence, not a generic tame/ownerUUID test. Then native entity-type holder must have TRANSFORMATION_POWDER datamap. No boss/allied/HP-threshold/LOS/attack-damage check inside helper; actual Player interaction reach/event admission remains. Air use produces only client CRIT particles in look-distance2 radius1 box, returnsSUCCESS without searching/transformation or cost. All32 installed directed mappings (16 pairs) are saved explicitly in package parameters and native resource witness; data maps may be extended by real datapacks.',
      'powder_pairs':'Installed two-way pairs: Minotaur/ZombifiedPiglin, Deer/Cow, Boar/Pig, BighornSheep/Sheep, DwarfRabbit/Rabbit, TinyBird/Parrot, Raven/Bat, HostileWolf/Wolf, Penguin/Chicken, HedgeSpider/Spider, SwarmSpider/CaveSpider, Wraith/Vex, SkeletonDruid/Witch, CarminiteGhastguard/Ghast, TowerwoodBorer/Silverfish, MazeSlime/Slime. No installed boss/Player transformation entry. Mapping absence is not an invented blanket boss immunity. Runtime-loaded map overrides are conditional, not assumed present.',
      'conversion_order':'EntityUtil.convertEntity requires ServerLevel, creates requested entity and rejectsnull. If destination Living, EventHooks.canLivingConvert posts cancelable Pre; rejection returnsfalse before old replacement/cost. Saves old passengers. Old Mob+new Mob branch invokes native oldMob.convertTo(newType,true): creates another destination, copies position/baby/noAI/name/persistence/invulnerability, transfers equipment via copyAndClear, adds entity, transfers current vehicle and discards old. No finalizeMobSpawn in this branch. Other branch copiesposition, if destinationMob calls finalizeMobSpawn(CONVERSION), then addFreshEntity and discards old. In that else branch the nested oldMob+newMob equipment copy condition is unreachable after the earlier branch. TF and native Mob helper ignore addFreshEntity boolean; no guarantee against external spawn cancellation. Native convertTo can returnnull and TF does not recheck it before later stages; no failure recovery invented.',
      'conversion_state':'After replacement, inside try: remember NEW UUID; new.load(old.saveWithoutId(new.saveWithoutId(new CompoundTag()))); restore remembered NEW UUID; if Living setHealth(getMaxHealth()). Source writes into destination NBT, rather than copying only selected safe fields. Native saveWithoutId writes even removed entities; native Living read loads saved attributes/effects/absorption/health/hurt/death/brain state. AttributeMap.load uses saved values for attributes present in destination, so resulting maxHealth can reflect old persisted attributes rather than destination species default. setHealth is a direct native state reset after load, not heal(amount), damage, source or healing-event callback; no damage-resistance/shield/HP-return gate. It does not remove copied status effects. TF catches Exception only around UUID/NBT/health section, logs warning and continues later stages; not a transactional rollback.',
      'conversion_equipment':'Crucial ordinary Mob hand/armor sequence: native convertTo transfers each nonempty stack with copyAndClear, emptying old slots; subsequent old Mob.save writes ArmorItems/HandItems lists containing empty compounds over destination NBT; new Mob.read replaces destination hand/armor slots with those emptied lists. Thus ordinary transferred hand/armor can disappear before final TF drop loop. Do not claim guaranteed equipment preservation or drops. BODY key is conditional: empty old body does not overwrite preexisting destination body key, so it can remain in seeded destination NBT. Subtype save/load overrides and actual slot layout remain native. TF then drops a SADDLE if old was saddled and new is not Saddleable, calls destination Mob.spawnAnim twice, and copyAndClear/spawnAtLocation for equipment that actually survives the reload. Saved old passengers are force-rebound to new entity; native startRiding admission still returns its own result, ignored. Living conversion Post follows, then sound and true return. Powder shrinks1 only on returnedtrue and shrinkStack flag. No loot/death attack source attributed to the Player.',
      'powder_dispenser':'Registered TransformationDispenseBehavior selects every LivingEntity intersecting the one-block AABB immediately in front of dispenser with NO_SPECTATORS predicate, server only. Calls same transformEntityIfPossible(target,stack,true) for every returned entity. No explicit isAlive recheck here, no break after one success and no remaining stack count/empty check in the loop: one activation can transform multiple eligible recipients and calls shrink1 per success even after original stack count reacheszero. Native helper still rejects ownership/missingmap/conversionPre; dispenser itself does not directly damage. Its instance fired flag becomestrue on any success and is never reset in execute/playSound, affecting later sound only. Default item-ejection fallback is not called; unchanged stack returned on no success.',
      'horn_activation':'Crumble Horn durability1024, native use starts72000tick TOOT_HORN. onUseTick requires remaining count>10 && count%5==0 && ServerLevel; count is REMAINING use time, not elapsed warmup. Exact244 native item-use tick hook may alter remaining count before callback. Therefore an eligible72000 first callback can act immediately and last10remainingticks are excluded. canContinueUsing tests same Item identity, reequip onlyslot/item change. Center=floor(eye+look*3), construct AABB.encapsulatingFullBlocks(center-2,center+1). WorldUtil.getAllInBB casts integer bounds and betweenClosed includes upper bound; resulting integer positions center-2..center+2 in each axis (125 positions), not only4cubed. No TF ray/LOS filter. Each successful crumble awards block stat toServerPlayer and hurtAndBreak1 on used hand, then break loop when damage>=max. Native wear/creative/enchantments remain; no direct Living HP request.',
      'horn_payload':'Per nonair block require CRUMBLE_HORN datamap, exact installed63 mappings captured. Player user first posts BreakEvent and canceled returnsfalse, before random. AIR-result branch chance randomFloat<chance: Player additionally block.canHarvestBlock then removeBlock(false), block.playerDestroy with ItemStack.EMPTY and post-removal getBlockEntity, event2001/stat; nonplayer Living additionally EventHooks.canEntityGrief then destroyBlock(true). NonAIR branch chance succeeds ->setBlock(result.withPropertiesOf(old),3),event2001/stat; no nonplayer grief check there. Returntrue does not test boolean success of remove/set/destroy calls. Ordinary native terrain/loot/support consequences remain, not fabricated damage. Installed AIR mappings are .05; nonAIR .2 including crack/downgrade stone/copper/Twilight masonry. Full source table retained, not inferred by names.',
      'horn_secondary':'The real Player BreakEvent can also reach protected ToolEvents.damageNonMazebreakerToolsMore: MAZEBREAKER_ACCELERATED state plus current MAINHAND damageable non-Mazebreaker item requests native wear16 before final break success. This may affect a held Horn or a different mainhand item while Horn is used offhand, and occurs before this Horn probability test. Earlier cancellation can suppress ordinary event dispatch; later rejection does not refund prior wear. Reuses protected maze_tool_durability, not another mechanic. Other protected native BreakEvent listeners keep their own conditions.',
      'horn_dispenser':'Registered CrumbleDispenseBehavior acts only front block, requires stack.maxDamage != stack.damage+1 and a datamap entry. It ignores chanceToCrumble: AIR->destroyBlock(true), otherwise setBlock preserving matching properties/event2001. No TF Player BreakEvent, harvest or grief gate in this class. Requests native durability1 with ServerLevel/nullplayer, firedtrue; playSound resets firedfalse after successful sound. It does not use handheld box/countdown or guaranteeworld mutation success. Keep this legitimate alternate separate from handheld probability and admission.',
      'magnet_activation':'Ore Magnet durability64, use starts72000tick BOW. release server && elapsed>10. Tries yaw/pitch offsets in order(0,0),(10,0),(10,10),(0,10),(-10,10),(-10,0),(-10,-10),(0,-10),(10,-10), stopping as soon as moved>0. Each ray uses eye to offset-look*32 convertedto BlockPos and integer VoxelBresenhamIterator, not collision raycast. If moved>0 native hurtAndBreak(moved) usedhand andsound. No cooldown, attack/hurt/source or XP call. isEnchantablefalse; book method compares Enchantments.UNBREAKING ResourceKey to each entry from book.getEnchantments().entrySet via Objects.equals, not entry key. Nonempty ordinary ENCHANTMENTS entries therefore reject even Unbreaking; empty ordinary list passes native superclass true. Native getEnchantments reads ENCHANTMENTS, not STORED_ENCHANTMENTS, so this is not a proven blanket ban on normal enchanted books. Other native anvil/enchantment admission remains.',
      'magnet_lookup':'ToolEvents TagsUpdated refresh clears item/tree maps. For c-namespace tags whose path contains ores_in_ground/, derives suffix via substring15, finds matching c:ore_bearing_ground/suffix; iterates each ground thenore, puts last encountered ground as replacement unless ore.defaultState is respective ORE_MAGNET_IGNORE or MINING_CORE_EXCLUDED. Iteration order can select among multiple grounds; no hardcoded per-ore guarantee. If allowed and absent, AncientDebris->Netherrack fallback. Installed exclusion tags include minecraft:coal_ores; safe replacement tag aggregates native dirt/gravel/sand/nylium/base stone/end stone/ore replaceable and TF root-ground tags. Real loaded tag/data changes are generic conditional integration, not direct proof every external ore works.',
      'magnet_move':'Ray scans inclusively and chooses first safe-replace-tag block as base, then first later nonAIR ore in selected map with no block entity. It does not stop at solid obstacles. findVein recursively visits six-axis neighbors, exact BlockState identity and cap24. Only initial selected ore explicitly checked for block entity; neighbors follow exactstate/cap. For each HashSet vein position, destination=source+(base-found); admit destination safe-replace ORcanBeReplaced ORair. Set source to mapped replacement.defaultState (STONE fallback), set destination to first selected ore BlockState, bothflags2, increment count regardless of setBlock returns. No TF break/place/harvest/grief/LOS event checks here; generic world hooks remain. HashSet order/overlapping targets and later native block updates retain their real behavior, not guaranteed atomic vein move or drops. No custom state persistence; actual changed blocks persist, maps rebuild on tag update.',
      'mining_core':'MineLogCore uses same helper with sourceIsMineCoretrue and tree map, no held item/durability. SpecialMagicLog defaultACTIVEfalse, onPlace schedules20ticks; native no-item interaction togglesACTIVE if doesCoreFunction, scheduleswhenenabled; disabledconfig forcesinactive. Server scheduled tick only if ACTIVE&&enabled performs effect and reschedules20ticks; otherwise no reschedule. Mine core chooses random offset peraxis nextInt(2*range+1)-range; exact installed common miningCoreRange16, disabled when configuredrange<=0. Thus random endpoints eachaxis[-16,16], not 32block Player look ray. Core-specific extra is particles/sound to nearbyplayers(distanceSq<4096), noentitydamage. Light15 whenACTIVE, nativeblocks/persistedACTIVE. Other Time/Transformation/Sorting cores remain separate unfinished structure utilities.',
      'lamp_terrain':'Lamp of Cinders durability1024/fireResistant, table/book enchantingfalse. useOn attempts burnBlock at clicked position immediately with no durability/side gate in TF: only exact BROWN_THORNS or GREEN_THORNS ->BURNT_THORNS.withPropertiesOf(old), true despite unchecked setBlockAndUpdate result, criterion/sound/particles. Airuse begins72000tick BOW; release requires elapsed>12 AND damage+1<getMaxDamage, then doBurnEffect. No hurtAndBreak/shrink/addCooldown anywhere in complete Lamp class: release checks a durability reserve but does not spend it. Server burn loop center=floor(eye+look*2), offsets-4..4 eachaxis729positions. Native thorn hazard details remain later; this utility converts blocks rather than source injection.',
      'lamp_ignite':'Independently of server-only terrainloop, doBurnEffect if user instanceof Player iterates native getEntitiesOfClass(LivingEntity,new AABB(center.below2).inflate4), default NO_SPECTATORS. Excludes every Player and ignites each other Living for5seconds. No TF LOS, distance sphere, team/owner, alive, fireImmune or successful thorn-change predicate. Branch occurs outside explicit server-only guard, though actual authoritative fire ticks are server native. Nonplayer genuine use can burnterrain but has no ignition branch. Native igniteForSeconds floors5*20=100ticks; Living multiplies by BURNING_TIME thenceil and Entity onlyraises currentremainingticks, not additive stacking. Fire immunity/native water/powdersnow extinguish and FireResistance/damage eligibility remain. Native later ON_FIRE ownerless damage1 on20tick modulo, separate from initial ignition, ordinary source tags/mitigation and hurtreturn; no initial HP hit, enchantment postattack, direct/cause attacker or custom Lamp DamageType.',
      'compatibility':'PocketWatch effect-applicability hook and native utility logic belong to TF. NeoForge conversion Pre/Post, item-use/interaction, effect applicability, BreakEvent/harvest/grief, entity spawning/serialization and ordinary fire mitigation are GENERIC_CONDITIONAL_PRESENT. Dynamic c ore tags/data maps are shared integration points. Recipe-view compat discovery is presentation, not additional damage delivery. No direct external source-specific combat override is proven in these bodies (NONE_PROVEN scoped here), and no pack-wide compatibility certification. No Curios-specific watch consumer in source scan; actual vanilla inventory and either-hand tests retained. Ominous-fire conversion is a proven separate caller, its death/source predicate and payload remain unfinished hazard scope.'
    }
    W='item/PocketWatchItem';P='item/TransformPowderItem';U='util/entities/EntityUtil';H='item/CrumbleHornItem';M='item/OreMagnetItem';L='item/LampOfCindersItem';E='events/ToolEvents';D='dispenser/TransformationDispenseBehavior';C='dispenser/CrumbleDispenseBehavior';I='init/TFItems'
    nxt='Review native Magic/Maze maps, Ore Meter and landmark ASM; remaining structural utility items/blocks (Rope, Magic Beans, magic cores and relevant callbacks), passive entities, hazards and nine custom DamageTypes. Complete remaining ASM/compatibility/source exclusions, R2f8 and final Twilight COMPLETE promotion before IceAndFire. No runtime/L2/Stage/production/Phase6/7.'
    data=dict(slug='active-utilities',checkpoint_short='r2f8s',checkpoint='R2f8s-active-utilities-complete',decision='TWILIGHT_ACTIVE_UTILITIES_SEMANTIC_REVIEW_COMPLETE',starting_sha='a5aed2439d588673357293c434d83570377bf21f',previous_checkpoint='R2f8r-food-flasks-complete',previous_draft='partial-drafts/twilightforest-r2f8r-partial.json',facts=facts,packages=[],paths=[],new_damage_types=0,full_classes=FULL,limited_classes={U:['convertEntity; OminousFire source admission remains hazard scope'],'util/WorldUtil':['getAllInBB/randomOffset'],'config/TFConfig':['rebakeCommonOptions'],'dispenser/TFDispenserBehaviors':['native registrations']},registration_classes=[I,'init/TFBlocks','init/TFDataMaps','events/RegistrationEvents','dispenser/TFDispenserBehaviors'],closure_checklist=['watch_real_inventory_indices_and_short_effects','watch_application_veto_vs_existing_effect','powder_all32_installed_mappings','native_conversion_Pre_replacement_NBT_health_Post','equipment_copy_clear_save_load_order','ownership_alive_and_actual_interaction','powder_dispenser_multi_recipient_cost','horn_remaining_time_and_inclusive_box','horn_probability_break_harvest_grief','horn_dispenser_distinct_admission','magnet_ray_cache_tags_vein_mutation','actual_mining_core_config_and_schedule','lamp_durability_gate_without_cost','lamp_terrain_vs_separate_ignition','native_fire_source_and_mitigation'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus PocketWatch, TransformationPowder, CrumbleHorn, OreMagnet/MiningCore and LampOfCinders; actual dispenser/native callbacks reviewed. Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=31,new_used_profiles=0,reviewed_profiles_after=31,remaining_profiles=9,remaining_disposition='Other actual callers unfinished, not unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,controls):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=controls));return eid
    watch=pkg('pocket_watch_native_effects','Pocket Watch native inventory effects','VANILLA_COMPOSITE',['watch_inventory','watch_native'],[W,I],{'ticks':5,'amplifier':0,'speed_jump_slots':'0..8 or40'},['server callback','Living','actualindex','holdingforHaste','nativeeffecteligibility'],'Native short effect refresh with item admission.','Native Player hotbar/offhand PocketWatch',['storage/held','stronger effects','actual244 globalindices','removal expiry'])
    fatigue=pkg('pocket_watch_fatigue_veto','Pocket Watch Mining Fatigue application veto','BINARY_MECHANIC',['watch_fatigue'],[E,W],{'effect':'minecraft:mining_fatigue'},['current application allowed','exacteffect','currentlyheldwatch'],'Binary eligibility veto, no status cleanse.','Native incoming MiningFatigue while holdingwatch',['alreadyactive','prior denial','hand switch','ordinary effect source'])
    powder=pkg('powder_entity_conversion','Transformation Powder native entity replacement','CUSTOM_CONTROL',['powder_admission','powder_pairs','conversion_order','conversion_state','conversion_equipment','powder_dispenser'],[P,U,D,'util/datamaps/EntityTransformation'],{'directed_mappings':conversions,'powder_per_returned_success':1},['real mapping','resolved owner absent','ServerLevel','conversionPre','native interaction/dispenser'],'Custom entity replacement and state reset; no attack source.','Native Powder interaction with mapped Living',['dispenser multi recipients','ownership','NBT/gear/health','conversion cancellation'])
    horn=pkg('crumble_horn_terrain','Crumble Horn native terrain transformation','CUSTOM_CONTROL',['horn_activation','horn_payload','horn_secondary','horn_dispenser'],[H,C,'util/WorldUtil','util/datamaps/CrumbledBlock'],{'durability':1024,'remaining_modulo':5,'positions_per_box':125,'mappings':crumbles},['real map','Player BreakEvent','nativeprobability/harvest','distinct dispenser'],'Custom terrain alteration through actual block methods.','Native held Horn use and dispenser',['AIR/nonAIR','Player/nonplayer gates','nativewear','remainingtime'])
    data['packages'][-1]['reuses_protected_effect_ids']=['twilightforest:maze_tool_durability']
    magnet=pkg('ore_magnet_terrain','Ore Magnet and mining-core block relocation','CUSTOM_CONTROL',['magnet_activation','magnet_lookup','magnet_move','mining_core'],[M,E,'util/iterators/VoxelBresenhamIterator','block/MineLogCoreBlock','block/SpecialMagicLogBlock','util/WorldUtil'],{'durability':64,'player_range':32,'vein_cap':24,'core_range':16,'core_period':20},['actualtag cache','firstbase thenore','initial noBE','destreplaceable','nativeworld mutations'],'Custom terrain relocation with real dynamic ore integration.','Native OreMagnet release and enabled MiningCore',['ray order','coal exclusion','24limit','state identity','nativecore vsitem'])
    lampterrain=pkg('lamp_thorn_conversion','Lamp of Cinders thorn conversion','CUSTOM_CONTROL',['lamp_terrain'],[L,I],{'durability':1024,'minimum_elapsed_strictly_greater_than':12,'area_positions':729,'durability_cost':0},['exactthorn','nativeclickeduse ORreleasepredicate'],'Native block-type conversion, no initial damage.','Native Lamp clicked thorn or charged release',['clicked vsarea gate','durability edge','nonthorn','property preservation'])
    lampfire=pkg('lamp_native_ignition','Lamp of Cinders native nonplayer ignition','VANILLA_LIKE_EXTENDED',['lamp_terrain','lamp_ignite'],[L],{'seconds':5,'base_ticks':100,'query_inflation':4},['releasepredicate','Playeruser','nativeLivingquery','recipient notPlayer'],'Custom area selection over native ignition and later ON_FIRE.','Native Player charged Lamp release',['no thorn needed','Player excluded','team/LOS','fireimmune/resistance','burningtime'])
    data['damage_profiles']=[]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:active_utilities_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through actual native item/inventory/dispenser/block callback; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('watch_hotbar','Native Pocket Watch in hotbar',['watch_inventory','watch_native'],[watch],[W],['PASSIVE_ITEM'],['0..8','heldboolignored','5tick refresh','nativeeligibility']),
      ('watch_offhand','Native Pocket Watch in offhand',['watch_inventory','watch_native'],[watch],[W],['PASSIVE_ITEM'],['actual244 index40','Speed/Jump/Haste','noCurio substitute']),
      ('watch_held','Native held-watch Haste and spare inventory watch',['watch_inventory','watch_native'],[watch],[W],['PASSIVE_ITEM','ACTIVE_ITEM'],['eitherhandidentity','Hasteindependentofcallbackslot','storageonlynoSpeedJump']),
      ('watch_veto','Native held-watch Mining Fatigue application',['watch_fatigue'],[fatigue],[E],['PASSIVE_ITEM'],['Applicableallowed','exactfatigue','DO_NOT_APPLY','prior/latereventcontrols']),
      ('watch_existing','Native already active fatigue and watch removal',['watch_fatigue','watch_inventory'],[fatigue,watch],[W,E],['PASSIVE_ITEM'],['no cleanse','5tickexpiry','NBTload distinct']),
      ('powder_player','Native Player mapped-entity Powder interaction',['powder_admission','powder_pairs','conversion_order'],[powder],[P,U],['ACTIVE_ITEM'],['all32 native mappings','alive','resolvedowner','Precancel','creativecost']),
      ('powder_air','Native Powder air-use negative control',['powder_admission'],[powder],[P],['ACTIVE_ITEM'],['particlesonly','noentitysearch','no cost']),
      ('powder_dispenser','Native Powder dispenser all-front-recipient loop',['powder_dispenser','conversion_order'],[powder],[D,P,U],['OTHER'],['oneblockAABB','NO_SPECTATORS','noone-targetbreak','no stack-emptyrecheck']),
      ('powder_save','Native conversion NBT/UUID/health lifecycle',['conversion_state','conversion_order'],[powder],[U],['OTHER'],['newUUIDrestored','oldattributes/effects','max afterload','nothealcallback','exceptionscope']),
      ('powder_gear','Native conversion hand/armor/BODY and saddle handling',['conversion_equipment'],[powder],[U],['OTHER'],['copyAndClear ->oldsave ->newload','ordinaryhandarmorloss','conditionalBODY','survivingdrops']),
      ('powder_riding','Native conversion vehicle/passenger and event paths',['conversion_order','conversion_equipment'],[powder],[U],['OTHER'],['nativeMobbranch','nonMobbranch','force rebind','ignoredreturns','Post']),
      ('horn_tick','Native handheld Horn remaining-time ticks',['horn_activation'],[horn],[H,'util/WorldUtil'],['ACTIVE_ITEM','AOE'],['remaining>10mod5','firstcallback','inclusive125','nativeuseevent']),
      ('horn_replace','Native Horn probabilistic nonAIR conversion',['horn_payload'],[horn],[H],['ACTIVE_ITEM','ENVIRONMENT'],['.2 mappings','PlayerBreakEvent','sharedproperties','nonplayer no griefgate']),
      ('horn_destroy_player','Native Horn AIR result for Player',['horn_payload'],[horn],[H],['ACTIVE_ITEM','ENVIRONMENT'],['.05','BreakEvent','canHarvest','remove then playerDestroy emptytool']),
      ('horn_destroy_other','Native Horn AIR result for other genuine Living user',['horn_payload'],[horn],[H],['ACTIVE_ITEM','ENVIRONMENT'],['actual callerrequired','.05','canEntityGrief','notautomaticMobAI']),
      ('horn_wear','Native Horn success/wear and rejection controls',['horn_activation','horn_payload','horn_secondary'],[horn],[H],['ACTIVE_ITEM'],['returntrue perblock','wear1','protected mainhand maze wear16 before roll','worldbooleanignored','cancel/no map/roll']),
      ('horn_dispenser','Native Horn dispenser front-block conversion',['horn_dispenser'],[horn],[C],['OTHER','ENVIRONMENT'],['no probability','maxDamage !=damage+1','noPlayerBreak/harvest','nativewear1']),
      ('magnet_release','Native OreMagnet held release and nine rays',['magnet_activation'],[magnet],[M],['ACTIVE_ITEM'],['elapsed>10','firstsuccessstops','range32','wear movedcount']),
      ('magnet_tags','Native OreMagnet actual tag-cache refresh',['magnet_lookup'],[magnet],[M,E],['OTHER'],['c tags','separateexclusions','grounditeration','AncientDebris fallback']),
      ('magnet_vein','Native OreMagnet vein admission and relocation',['magnet_move'],[magnet],[M,'util/iterators/VoxelBresenhamIterator'],['ACTIVE_ITEM','ENVIRONMENT'],['exactstate','24cap','initialnoBE','destpredicate','flags2/notatomic']),
      ('magnet_enchant','Native OreMagnet enchant admission controls',['magnet_activation'],[magnet],[M],['OTHER'],['tablefalse','entry vsResourceKey','ordinary vsstored enchants','nativeanvilrules']),
      ('magnet_core','Native active mining-core alternate delivery',['mining_core','magnet_lookup','magnet_move'],[magnet],['block/MineLogCoreBlock','block/SpecialMagicLogBlock',M,'util/WorldUtil'],['ENVIRONMENT'],['range16config','20scheduledticks','treecache','nohelditemwear','activepersistence']),
      ('lamp_click','Native Lamp immediate clicked-thorn conversion',['lamp_terrain'],[lampterrain],[L],['ACTIVE_ITEM','ENVIRONMENT'],['exactbrown/green','no durabilitygate','no entityignitiononthispath']),
      ('lamp_release','Native Lamp charged release terrain cube',['lamp_terrain'],[lampterrain],[L],['ACTIVE_ITEM','AOE','ENVIRONMENT'],['elapsed>12','damage+1<max','729blocks','no durabilityspend']),
      ('lamp_fire','Native Player Lamp nonplayer ignition area',['lamp_ignite','lamp_terrain'],[lampfire],[L],['ACTIVE_ITEM','AOE'],['5seconds','offsetAABB','no thornsuccessneeded','noLOS/teamfilter']),
      ('lamp_native_fire','Native Lamp later fire and mitigation',['lamp_ignite'],[lampfire],[L],['ENVIRONMENT'],['BURNING_TIME','maxremainingnotadditive','ownerlessON_FIRE','water/fireimmune/Resistance']),
      ('lamp_controls','Native Lamp Player exclusion/nonplayer-user and durability controls',['lamp_ignite','lamp_terrain'],[lampfire,lampterrain],[L],['ACTIVE_ITEM'],['allPlayers excluded','nonPlayeruserterrainonly','1022vs1023','clickedindependent'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-active-utilities-caller-scan.json','config-evidence/twilightforest-common.json','reference-evidence/twilight-equipment-244.json','reference-evidence/twilight-travellers-utility-244.json','reference-evidence/twilight-food-flasks-244.json','reference-evidence/vv-loader-244.json']
    data['exclusions']=['Complete five utility item classes, two dispenser behaviors, native data-map records, ore ray/core classes and ToolEvents are reviewed; old ToolEvents mechanics reused without redo.','Actual32 powder mappings and63 crumble entries pinned. No arbitrary target conversion, synthetic native source or fallback damage introduced.','Recipe-view integrations are informational; ordinary native hooks and dynamic tags/maps remain conditional, not blanket pack compatibility.','OminousFire conversion caller and thorn hazard admission remain unfinished separate hazards; reviewing shared helper does not close those sources.','Other maps/structural utilities/passive entities/hazards/nine custom types/ASM/source closure remain unfinished; no production, Stage, L2 or runtime work.']
    data['fixture_groups']=['Actual global-slot PocketWatch effects plus new-vs-existing MiningFatigue application.','Player/dispenser powder real mapping/ownership/conversion events, UUID/NBT/health/equipment/vehicle/passenger lifecycle.','Handheld vsdispenser Horn remainingtime/box/probability/harvest/grief/wear contrasts.','Actual OreMagnet tag caches, nine rays and24state-identical vein cap, enabled MiningCore alternate.','Clicked/charged Lamp thorn transformation separately from native nonplayer ignition and later fire damage.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-active-utilities.json',data);assemble('twilightforest-active-utilities.json')

if __name__=='__main__':build()
