from catalog_common import *
from bossesrise_combat_common import save_section
CP='R2i7a-bossesrise-kraken-defense-complete'
STEM='bossesrise-r2i7a-kraken-defense'
START='7bc191b33d5454b1c07f54510ec727e8538a3bcf'
NEXT='R2i7b: Kraken tentacle attack/crate/runaway goals, native smash geometry and custom source, cannon interaction/aim/fire and projectile impact/explosion, pirate summons. Parent/tentacle defense and phase resources are protected in R2i7a. Then equipment and whole-mod closure; no runtime work.'
FACTS={
'incoming_order':'Kraken.hurt first tests CannonballEntity.hasCausedDamage: exact custom CANNONBALL_HIT OR exact vanilla EXPLOSION with directEntity instanceof CannonballEntity. Matches multiply incoming amount5; only ELSE does IS_PROJECTILE multiply.25. Thus native custom cannon impact receives5, not1.25; recognized cannon explosion also receives5. Arbitrary player_explosion or projectile owner match does not satisfy the exact second predicate. Original source is forwarded to inherited hurt unchanged. Tentacle parent ordinary hurt rejects client and routes to part8; part overload applies cannon5, with NO generic projectile.25 reduction, then inherited hurt on this tentacle. Parts do not forward HP to the Kraken boss. Native defense multipliers are not Stage scaling points.',
'hidden_admission':'Kraken DATA_IS_HIDDEN update writes blocksBuilding=!hidden, calls setInvulnerable(hidden), and refreshes dimensions; hidden dimensions0x0. This sets Entity backing invulnerable state, unlike a virtual getter-only override. Native Entity.isInvulnerableTo consequently rejects ordinary hidden damage subject to BYPASSES_INVULNERABILITY, creative-source exception and Neo invulnerability hook. Kraken.hurt has no additional phase/hidden early rejection; the source pipeline matters. No evidence supports treating hidden as an unconditional bypass-proof shield. Kraken is unpushable, no movement writes via setDeltaMovement, no entity pushing, piston IGNORE, isInWall false. Tentacles similarly suppress these movements and have no special invulnerability override in this class. Native incoming armor/Resistance/enchantment/event rules still apply.',
'knockdown':'After super.hurt true, and only when !isKnockedDown (KNOCKDOWN active OR either dying animation counts as knocked down), accumulates max(previousHP-currentHP,0). At100 AND !phase3 resets resource0 and pushes KNOCKDOWN. Resource is actual net HP loss, not requested amount; no timeout/reset except threshold. While knocked down it neither accumulates nor triggers. KNOCKDOWN lasts through timer304, stuns loaded tentacles onStart, and moves body using clamped interpolation: offset0->1 over0..76, stays until228, returns by304. It does not itself change incoming HP multiplier or armor. Position/exposed body is a distinct future fixture. Resource and state stack/timer persist.',
'phase_initialization':'Base and config default Kraken HP500/armor20/attack10. finalizeSpawn applies config and fills HP. Native ship spawner directly creates the Kraken, sets ship transform and phase-1, adds it without calling finalizeMobSpawn; therefore do not assume custom configuration was applied on this producer solely because finalizeSpawn exists. Default shared phase0 initializes tentacles directly; ship route has intro. Boss phase setter clears initialized flag; server tick initializes once per phase. Phase0 hides body, shows bar, clears respawn queue, spawns8 tentacles (6 melee,2 cannon candidates). Progress bar sums loaded tentacle HP fractions/8, not boss HP. After respawn handling, loaded list empty AND all sampled arena chunks loaded transitions to phase1; lingering UUID list only logs, does not block. Phase2 shows/moves body, clears queue and spawns10 tentacles (6 melee,2 cannon candidates,2 crate); progress uses boss HP. Phase1/intro run cinematic entities, not HP percentage transitions. No phase HP refill exists.',
'cinematic_control':'Intro and phase-transition cinematic entities have server game-time durations490/290. Native parent state starts hidden/bar hidden and waits until entity absent or animationFinished; while waiting, nearby Players in shared full-side64 AABB receive native Resistance100ticks amplifier255 every state tick. Native Applicable and Roll can veto even this beneficial protection. State end chooses phase0/2. Cinematic surrogate hurt alwaysfalse, empty travel/push/knockback/checkFallDamage/customServerAiStep and no outgoing combat callback; do not confuse surrogate immunity with body immunity. Surrogate saves deadline/owner but marks reloaded and discards next tick. Parent saves live surrogate UUID and later resolves it; genuine reload/missing surrogate needs runtime fixture, not invented replacement source. Weather is forced rain/thunder for60ticks every gameTime%40 while boss alive and cleared for24000 on native die; preserve as environmental context for later lightning/fire/equipment fixtures, with no direct Stage payload.',
'tentacle_resources':'Defined tentacles spawn server entities with owner UUID, ID/type/rotation, HP=max Kraken BASE maxHealth/12, armor/attack copied from base attributes, full tentacle HP. They are separate Monsters with parts. Cannon candidate creates a tentacle, chooses nearest Cannon within its BB.inflate32 that has no tentacle first passenger, and must successfully ride it; failure discards it and falls back to melee. Successful spawned UUIDs are tracked. Tentacle removal unconditionally calls owner.onTentacleDestroyed after resolving owner, with no RemovalReason or death-source filter. That callback removes UUID, increments deadTentacles server-side, summons pirates at cumulative count4 or6 OR removed type CANNON, and queues respawn for a matching current-phase definition. Thus discard/unload paths must be tested separately from HP defeat; never simplify callback to on-kill only. Phase0 delays by definition4800/6000/7200/8400; phase2 melee2400, cannon/crate2000. Queue sorted comparator uses respawnAtGameTime ONLY: equal timestamps compare equal even for different IDs. Per-ID duplicate check precedes add, but same-time distinct-ID add can still collapse. Retry spawn at/after deadline; remove timer if no current definition or spawn succeeds.',
'tentacle_lifetime':'Tentacle native owner lookup refreshes server-side in baseTick and remove; Owner NBT capitalization matches on write/read. Type, ID and rotation persist; player targets/goals are not promoted from arbitrary NBT. On die, inherited die runs first; if dead, plays native type-specific death and leaves vehicle. tickDeath removes at>=115 server ticks, so phase resource/removal callbacks occur after the corpse delay. killQuietly is a native scripted direct setHealth0 then die(genericKill) when not dead; it does not route through hurt/IncomingDamage and has no Stage value. Parent death sequence uses it; no compat code is authorized to emulate it. Kraken removal only discards owned loaded tentacles for DISCARDED/KILLED, while tentacle removal itself is unfiltered. Loaded resolution and owner absence materially change resource outcomes.',
'death_sequence':'Shared AbstractStateBoss actual-damage hook may restore lethal HP to.1 after downstream Post unless source bypasses invulnerability. First shouldCancelDeath setsphase3/true. Later returns isInDyingState, which is false during KNOCKDOWN before a dying animation; another native lethal request during that gap may take ordinary death. Server phase3 waits if KNOCKDOWN outside76<=timer<228, switches immediately to dying_from_knockdown inside that range, or selects dying_from_idle when not in dying state and still alive. Either dying state lasts through180; native callback kills all loaded tentacles at80, or a random alive tentacle with probability1/6 on other ticks. State removal happens before onEnd, so final shared simulatePlayerKill sees no dying state and can finish via native PLAYER_ATTACK999. Result is ignored and normal mitigation/admission still matters. No new damage source or direct HP action is proposed; native scripted lifecycle is not scalable.',
'spawn_and_scope':'Ship spawner first summons fixed pirate points near an alive player, tracks UUIDs, then creates Kraken after its tracked list empties. Pirate death hook removes matching UUID near the spawner; full pirate combat stays R2i7b. Parent also emits runaway tentacles for eligible water-bound players near ship with per-player200tick cooldown; exact grab/throw/control remains R2i7b, so not claimed complete here. Saved parent records include ship transform, owned UUIDs, dead counter, respawn timers, initialized flag, hidden state, knockdown resource and cinematic UUID plus shared HP/state. No cosmetics/loot/ship-construction archaeology. This checkpoint closes incoming defense, phase and resource semantics only; whole Kraken and Bosses Rise remain PARTIAL.'
}

def save():
    defs=[('cannon_admission','OTHER','Body cannon5 before projectile.25; exact native source identity'),('hidden','OTHER','Hidden backing invulnerability, zero dimensions and native exceptions'),('part','OTHER','Tentacle part8/default or native part -> own HP, cannon5 only'),('knockdown','OTHER','100 actual HP loss ->304tick native position/stun resource'),('intro','OTHER','Ship producer phase-1 versus generic phase0 and configuration path'),('phase1','OTHER','Eight tentacles, loaded-arena empty transition and290tick phase cinematic'),('phase2','OTHER','Ten tentacles plus exposed independent boss HP'),('cinematic','AOE','490/290 native surrogate deadlines and Resistance255 player protection'),('tentacle_spawn','SUMMONED_ATTACK','Base-attribute copies, cannon ride requirement and melee fallback'),('tentacle_remove','OTHER','115tick corpse or other removal -> unfiltered owner resource callback'),('respawn','SUMMONED_ATTACK','Current-definition timers, duplicate timestamps and native retries'),('death','OTHER','Phase3 lethal restoration gap and180tick dying states'),('scripted_cleanup','OTHER','Native tentacle killQuietly and final simulated player kill'),('reload','OTHER','Saved phase/hidden/resource/owner/state restoration')]
    paths=[dict(id='br:kraken_defense:'+n,labels=[label],native_path=desc,runtime_status='NOT_RUN',runtime_variants=['Native source/producer, state and owner resolution','HP result versus resource/callback ordering']) for n,label,desc in defs];ids={n:p['id'] for (n,*_),p in zip(defs,paths)}
    groups=[('kraken_admission','Kraken body and tentacle native admission','BINARY_MECHANIC',['cannon_admission','hidden','part']),('kraken_knockdown','Kraken actual HP knockdown resource','CUSTOM_RESOURCE',['knockdown']),('kraken_phase','Kraken native tentacle phases and cinematic protection','VANILLA_LIKE_EXTENDED',['intro','phase1','phase2','cinematic']),('kraken_tentacle_resources','Kraken tentacle ownership, removal and respawn','CUSTOM_RESOURCE',['tentacle_spawn','tentacle_remove','respawn','reload']),('kraken_death','Kraken native death and scripted cleanup','CUSTOM_CONTROL',['death','scripted_cleanup'])]
    pk=[dict(id='br:'+i,name=name,primary_classification=cl,tno_categories=['COMPOSITE','ADMISSION_GATED','NO_STAGE_VALUE'],stage_scaling_needed=False,single_scaling_point=None,stage_reason='Native incoming modifier, resource/phase/admission, beneficial control or scripted cleanup; no separately scalable outgoing HP payload.',delivery_paths=[ids[k] for k in keys]) for i,name,cl,keys in groups]
    d=dict(schema='tno.external_effects.bossesrise_kraken_defense.v1',checkpoint=CP,previous_checkpoint='R2i6-bossesrise-sandworm-complete',starting_sha=START,status='KRAKEN_DEFENSE_PHASE_RESOURCE_SEMANTICS_COMPLETE',scope='Kraken body/tentacle incoming damage, native phases, knockdown, death and spawn resources; outgoing attack goals and cannon next.',summary='Kraken hidden state sets real invulnerability; cannon5 takes priority over projectile.25. Knockdown tracks actual HP loss, and tentacle removal callbacks are not limited to death.',facts=FACTS,mechanic_packages=pk,delivery_paths=paths,unexecuted_future_fixtures=['cannon_custom_hit_vs_exact_explosion_direct_entity_and_projectile_priority','tentacle_part_damage_not_parent_and_no_generic_projectile_reduction','hidden_actual_invulnerability_native_bypass_creative_and_hook','netHP100_knockdown_no_accumulation_304_position_timing','ship_spawn_config_vs_finalize_and_phase_init_reload','phase0_all_loaded_tentacles_empty_arena_chunks_vs_UUID_list','cinematic_native_Resistance_Applicable_Roll_veto_deadline_reload','cannon_tentacle_ride_failure_discard_callback_and_melee_fallback','tentacle_death115_vs_discard_unload_owner_resolution','respawn_same_timestamp_differentID_sortedset_collision','phase3_knockdown_gap_second_lethal_vs_active_dying_restore','native_cleanup_bypasses_hurt_then_terminal_request_rejection','state_owner_resource_reload'],review_required=[],remaining_subsection_native_ambiguities=[],exact_next_task=NEXT,references=['native-evidence/bossesrise-kraken-defense.json','native-evidence/bossesrise-shared.json','native-evidence/bossesrise-sandworm.json','reference-evidence/bossesrise-sandworm-244.json','bossesrise-r2i2a-roll-admission.json','bossesrise-damage-tags.json'])
    save_section(d,STEM,'R2i7a — Bosses Rise Kraken defense and phase resources')
if __name__=='__main__':save()
