"""R2g4: combat integration decisions; no Stage or production implementation."""
from catalog_common import *
from assemble_batch import refresh
START='71e033d0cb6f2e82ff10accae511fbad953c00ac'
CP='R2g4-gorgon-complete'
NEXT='R2g5: Dragons combat review: shared native attack/admission, fire/lightning breath and charge payloads, melee specials, age attributes and defenses. Reuse R2g1 factories and R2g2b Frozen/charge routing unchanged; no runtime/L2/Stage/production work.'
FACTS={
 'gaze_entry':'Gorgon.aiStep follows super, decrements positive playerStatueCooldown, and works on the current target. Gorgon/prey Blindness and deathTime gate forced Mob look control; the stare goal can also force Mob look. Mutual IafEntityUtil.isEntityLookingAt(...,0.4), !isBlindfolded(target), neither participant Blindness, no rejecting BlacklistedFromStatues, deathTime==0, SCARE animation tick>10, server side and cooldown==0 admit conversion. SCARE starts on eligible mutual gaze; no proof of 10 uninterrupted gaze ticks is implied. Cooldown is assigned40 and target cleared after conversion; it is not serialized by this class. No direct target-current-HP or creative check occurs at this final gaze block: native acquisition, LOS and subsequent player hurt still matter.',
 'gaze_geometry':'isEntityLookingAt multiplies degree by 1+0.1*looker.distanceTo(seen); normalized view dot normalized eye-direction must exceed 1-degree/eyeDistance. It then requires looker.hasLineOfSight(seen) and seen not StoneStatue. Exact LivingEntity LOS requires same level, eye distance<=128 and COLLIDER/Fluid.NONE ray MISS. Both directions are checked. Stare goal15block squared-distance/20seen ticks control navigation/strafe, not an additional final petrification range. Gorgon.isTargetBlocked returns COLLIDER/Fluid.NONE ray !=MISS; its sole installed caller is DragonUtils.getBlockInTargetsViewGorgon, which has no installed direct caller. Do not substitute this unused positioning helper for actual gaze LOS.',
 'gaze_order':'aiStep builds and attempts to add statue BEFORE victim disposal. addFreshEntity return is ignored. Player hurt uses causeGorgonDamage(this), float2147483648 (rounded integer-max float), discards hurt result; direct=causing=Gorgon. Thus rejected player damage can coexist with a statue. Non-player remove(KILLED) does not call hurt/die, emit this DamageSource, or directly subtract HP/SHP. Native entity removal callbacks still occur; no generic damage/death-hook guarantee is invented.',
 'head_entry':'GorgonHead.use starts use, sets ACTIVE and returns SUCCESS; use duration72000, empty onUseTick. releaseUsing has no minimum charge-time test. A32block eye/view segment queries expanded entity bounds; no block ray or LOS check. Candidates Living, pickable, !deadOrDying, !Blindness, !IMMUNE_TO_GORGON_STONE, no rejecting BlacklistedFromStatues, and Player or DragonUtils.isAlive. That helper additionally excludes model-dead dragons/IDeadMob/StoneStatue; it is not itself the generic HP check. Unlike gaze, Head does not invoke isBlindfolded, so native blindfold equipment, BLINDED and the compat helper are not automatically Head gates.',
 'head_order':'Nearest inflated-AABB segment selection preserves shared-root-vehicle rules. If an AABB contains the ray origin, code sets best distance0 WITHOUT selecting that entity; do not copy Siren Flute behavior. Player hurt is first, using causeGorgonDamage(pointedEntity): direct=causing=VICTIM, not wielder or item. Only hurt==true admits statue creation; true is not proof of death or HP loss. Non-player server remove(KILLED) precedes statue construction; success flag remains true. Server spawn return is ignored. A selected Living target consumes one Head for noncreative Player user even when player hurt rejects; no selected target consumes none. ACTIVE removed at end. Player hurt/item consumption has no whole-method server guard; only non-player removal and statue spawn are explicitly server gated.',
 'native_admission':'R2g1 GORGON resource: only scoped bypasses_armor/bypasses_shield, no bypass_invulnerability/cooldown/resistance/effects/enchantments. Exact ServerPlayer hurt checks invulnerability, spawn protection and causing-Player canHarmPlayer, then Player ability invulnerability, death, difficulty scaling and Living incoming/shield/cooldown/reduction/death/totem hooks. Head self-attribution therefore enters player-PVP/team checks against the victim itself; PVP disabled rejects. Gaze has Gorgon attribution. Neither gigantic requested amount nor hurt=true certifies death, SHP loss or Nullification bypass. Non-player conversion never reaches this damage admission at all.',
 'immunity':'Native isBlindfolded: nonnull target with HEAD blindfold item OR Blindness OR BLINDED entity tag. Installed BLINDED lists deathworm,dragon_skull,mob_skull. IMMUNE_TO_GORGON_STONE declares optional #c:bosses/#neoforge:bosses plus warden; final merged tags are runtime data, not this static list. Native gaze itself does not read IMMUNE tag, but installed tensura_iaf HEAD cancellable isBlindfolded injection returns true for that tag or SkillUtils.isSkillToggled(ABNORMAL_CONDITION_NULLIFICATION). Protected helper requires instance toggled and mastery>=0; it does not perform ResistSkill.canInteractSkill here. Head checks IMMUNE tag directly but does not call this helper. Cockatrice,DeathWorm,DragonEgg,DragonSkull,Ghost,MobSkull,StoneStatue return false from canBeTurnedToStone; Cyclops returns !isBlinded. No assumption that every boss is immune without tag membership.',
 'compatibility':'Existing required compat mixins classify exact GORGON as abnormal and not physical. Ordinary player hurt still traverses actual Tensura/NeoForge/L2 pipelines; final interactions require runtime tests. Non-player remove can avoid damage-based defenses because that is the installed native route; research does not add or authorize a bypass. IafHandler rejects nonnull MobEffect additions to StoneStatue via Manas LivingEffectAdded. That is not a veto of statue creation/removal. Native Head versus gaze differences must survive future integration.',
 'fallback_melee':'setTarget invokes parent then chooses server melee/stare goals using own/target Blindness, rejecting blacklist OR isBlindfolded(target), provided deathTime==0 for melee. doHurtTarget has narrower poison predicate: own Blindness OR CURRENT target Blindness OR rejecting CURRENT target blacklist, and deathTime==0. Mere blindfold/tag/compat immunity switches AI but does not alone grant poison. If predicate passes, animation HIT starts and actual Living entityIn gets Poison100ticks amplifier2 before parent Monster/Mob.doHurtTarget; addEffect result ignored, poison not gated by melee hurt. Parent uses current ATTACK_DAMAGE(base3), native mob_attack, enchantment modification then hurt; accepted-hit knockback/postattack retains native result gate. Poison ticks use installed NeoForge poison holder (native magic fallback), source without entity,1requested HP when HP>1, interval25>>2=6; independent normal effect admission/removal/cures and damage hooks remain.',
 'statue_state':'buildStatueEntity creates a separate stone_statue LivingEntity; non-Player saveWithoutId snapshot attempted (exception caught), Player trapped NBT empty; stores registry type,width,height,age scale. It does not preserve a live prisoner or implement timed release. Defaults pig,emptyNBT,.5width/.5height,scale1,cracks0. Saves CrackAmount int but reloads getByte; saves/reloads dimensions,scale,type,tag. No native resurrection path in reviewed statue consumers. Item restore creates another statue, not trapped creature; resets cracks0. ServerEvents player attack repairs statue to maxHP before tool logic, increments cracks for MAINHAND PICKAXES and removes at>9, interrupting attack; other player attack interrupts default. Silk-touch storage/replacement is a short persistence disposition, not a new combat family.',
 'statue_defense':'StoneStatue.hurt first checks source IS_PROJECTILE && amount>0; if so it optionally awards server XP from newly constructed trapped type, removes KILLED and returns true BEFORE parent hurt. No owner/causer requirement, HP subtraction, hurt-hook or invulnerability check in this branch. Non-projectile/zero amount delegates LivingEntity.hurt. isInvulnerable() returns true, but exact Entity.isInvulnerableTo reads its FIELD rather than calling that override; do not claim universal statue damage immunity. baseTick/push are empty, kill removes, and canBeTurnedToStone=false. Ordinary non-projectile damage/loaded Invulnerable field and external overrides require separate runtime observation.',
 'excluded':'Rendering/statue pose/sounds, Head acquisition/crafting/lore and ordinary storage cosmetics excluded. Statue NBT/item restoration retained only to distinguish persistence from resurrection and admission state. Gorgon prolonged cosmetic death, utility data/components and unconnected positioning helpers receive no separate deep review. Troll sunlight uses the shared statue constructor but its trigger belongs to the later Troll family.'
}

def mechanic(id,name,classification,kinds,scaling,point,combat,admission,paths):
    return dict(id='iaf:'+id,name=name,primary_classification=classification,tno_categories=kinds,stage_scaling_needed=scaling,single_scaling_point=point,combat_behavior=combat,admission=admission,delivery_paths=paths)

PATHS=[
 ('gaze_player','BOSS_ATTACK','Gorgon.aiStep mutual gaze -> statue spawn -> GORGON Player hurt; result ignored'),
 ('gaze_nonplayer','BOSS_ATTACK','Gorgon.aiStep mutual gaze -> statue spawn -> remove(KILLED); no hurt'),
 ('head_player','ACTIVE_ITEM','GorgonHead.releaseUsing entity ray -> victim-attributed GORGON hurt -> statue iff true'),
 ('head_nonplayer','ACTIVE_ITEM','GorgonHead.releaseUsing entity ray -> server remove -> statue'),
 ('melee_poison','MELEE','native melee goal -> Gorgon.doHurtTarget conditional Poison -> parent native mob_attack'),
 ('melee_blindfold','MELEE','blindfold/tag/compat fallback melee without poison predicate -> parent mob_attack'),
 ('statue_projectile','PROJECTILE','StoneStatue.hurt positive IS_PROJECTILE -> remove before parent hurt'),
 ('statue_other_damage','OTHER','StoneStatue.hurt nonprojectile -> normal LivingEntity.hurt'),
 ('statue_pickaxe','MELEE','PlayerEvent.ATTACK_ENTITY -> ServerEvents.onPlayerAttack heal + cracks, remove at10'),
 ('statue_other_player_attack','MELEE','same native callback heals then interruptDefault'),
 ('statue_reload','OTHER','saved statue/StoneStatueItem restore -> statue only, no victim resurrection')]

def save():
    ids={s:'iaf:gorgon:'+s for s,_,_ in PATHS}
    packages=[
      mechanic('gorgon_petrification','Gorgon petrification','BINARY_MECHANIC',['BINARY','CUSTOM_ROUTED','ADMISSION_GATED'],False,None,'Binary victim conversion/disposal with materially different player and non-player branches. The huge float is an execution proxy, not a scalable attack budget.','Mutual gaze/LOS/blindfold/blacklist vs Head ray/tag; player hurt/totem/PVP/source identity and statue ordering.',[ids[s] for s in ['gaze_player','gaze_nonplayer','head_player','head_nonplayer']]),
      mechanic('gorgon_melee','Gorgon fallback melee','VANILLA_LIKE_EXTENDED',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],True,'The amount delivered by native Mob.doHurtTarget to victim.hurt(mob_attack,amount), once in the normal damage pipeline. Do not also multiply ATTACK_DAMAGE or Gorgon animation.','Base3 attribute-based ordinary hit; native knockback/enchantment postattack admission.','Native melee goal and ordinary hurt hooks.',[ids['melee_poison'],ids['melee_blindfold']]),
      mechanic('gorgon_poison','Gorgon conditional Poison','VANILLA_COMPOSITE',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],True,'Existing vanilla/NeoForge Poison damage route at PoisonMobEffect.applyEffectTick -> hurt(amount), once per admitted pulse; no Iaf-specific second multiplier and no duration/amplifier scaling. Preserve HP>1 predicate; scaled nonlethal behavior requires future runtime/policy review before implementation.','100ticks PoisonIII requested before melee damage; native interval6 and1requested pulse.','Own/current-target blindness or rejecting blacklist, then native effect and tick-damage admission; no melee-success dependency.',[ids['melee_poison']]),
      mechanic('stone_statue_admission','Stone statue persistence and destruction','BINARY_MECHANIC',['BINARY','CUSTOM_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],False,None,'Persistent separate statue; positive projectile deletes; player pickaxe cracks threshold10; other damage delegates.','IS_PROJECTILE positive gate, native parent hurt/Invulnerable field, PlayerEvent intercept and Manas statue effect veto; never infer all damage immune.',[ids[s] for s in ['statue_projectile','statue_other_damage','statue_pickaxe','statue_other_player_attack','statue_reload']])]
    files=['native-evidence/iceandfire-gorgon.json','iceandfire-gorgon-census.json','reference-evidence/iceandfire-gorgon-244.json','native-evidence/iceandfire-foundation.json','annotation-evidence/iceandfire-compat-javap.json','reference-evidence/vv-loader-244.json','reference-evidence/iceandfire-frozen-tensura.json','iceandfire-damage-tag-census.json']
    fixtures=['gaze_player_damage_accept_reject_totem_statue_count','gaze_nonplayer_no_hurt_event','gaze_interrupted_animation_mutual_LOS_range','blindfold_Blindness_BLINDED_IMMUNE_and_toggle_mastery','head_player_self_attribution_PVP_team_spawn_protection','head_player_hurt_true_without_death_and_hurt_false_consumption','head_nonplayer_removal_statue_snapshot','head_wall_origin_containment_vehicle_charge_time','poison_before_rejected_melee_vs_blindfold_only','poison_NeoForge_source_null_attribution_tick_admission','statue_projectile_ownerless_amount_zero_vs_positive','statue_other_damage_invulnerable_field_override','statue_pickaxe_10_and_nonpickaxe_intercept','statue_reload_cracks_byte_and_item_no_resurrection','statue_effect_veto_and_external_L2_Tensura_hooks']
    d=dict(schema='tno.external_effects.iaf_gorgon.v1',baseline=BASELINE,checkpoint=CP,starting_sha=START,status='GORGON_SEMANTIC_REVIEW_COMPLETE',facts=FACTS,mechanic_packages=packages,delivery_paths=[dict(id=ids[s],labels=[label],native_path=path) for s,label,path in PATHS],unexecuted_future_fixtures=fixtures,reference_files=[dict(file=f,sha256=sha256(OUT/f)) for f in files],remaining_subsection_native_ambiguities=[],review_required=[],whole_iceandfire_complete=False,promoted_mechanics=0,promoted_paths=0,exact_next_task=NEXT,runtime_tests=0,**boundary_flags())
    write_json(OUT/'iceandfire-r2g4-gorgon.json',d)
    r=read_json(OUT/'mod-reviews/iceandfire.json');r.update(checkpoint=CP,scope='Frozen, Siren and Gorgon complete as static subsections; remaining combat families pending.',notes_file='iceandfire-r2g4-gorgon.json',exact_next_task=NEXT);write_json(OUT/'mod-reviews/iceandfire.json',r);refresh(CP)
    for f in ['effect-catalog.json','effect-sources.json','delivery-path-matrix.json','vanilla-comparison.json','behavior-primitives.json']:
        o=read_json(OUT/f);o.update(checkpoint=CP,unfinished_review=dict(mod_key='iceandfire',status='PARTIAL',promoted_records=0,notes_file='iceandfire-r2g4-gorgon.json'));write_json(OUT/f,o)
    o=read_json(OUT/'research-decision.json');o.update(checkpoint=CP,next_task=NEXT,latest_iceandfire_subsection_decision=d['status'],save_mode=False,save_reason=None);o['checkpoints']['R2g3b-siren-flute-attacks-complete']=START;o['checkpoints'][CP]='Self: exact SHA from commit/live verification.';o['recovery_r2g4']=dict(local_start=START,live_remote_start=START,working_tree_start='CLEAN',divergence='0/0',newer_work=False);write_json(OUT/'research-decision.json',o)
    lines=['# R2g4 — Gorgon combat semantics','','Static subsection COMPLETE; Ice & Fire PARTIAL. Four mechanic packages and eleven materially distinct paths; no runtime or implementation.','']
    for k,v in FACTS.items():lines+=['## '+k.replace('_',' ').capitalize(),'',v,'']
    lines+=['## TNO decisions','','Binary petrification, huge execution proxy, statue deletion/cracks and immunity gates receive no numeric Stage multiplier. Ordinary melee and Poison use their existing native damage routes exactly once; Poison remains an independently admitted effect. Exact per-package integration points and future fixtures are in [the machine-readable review](iceandfire-r2g4-gorgon.json). No scaling is implemented or production behavior changed.','','## Validation','','Reproduce installed native/reference witnesses and whole-JAR predicate/caller census; assert conversion ordering and hurt-return dependencies, source argument distinction and actual invulnerability field dispatch; preserve prior accepted records/evidence; five tooling tests and diff checks. This is bounded subsection validation, not a new whole-catalog completion claim.','','Exact next task: '+NEXT,'']
    (OUT/'iceandfire-r2g4-review.md').write_text('\n'.join(lines),encoding='utf-8')
    main=ROOT/'docs/external-effects-catalog-research.md';text=main.read_text(encoding='utf-8')
    if '## R2g4 — Gorgon' not in text:text+='\n## R2g4 — Gorgon\n\nGaze spawns the statue before player hurt; Head uses victim-attributed hurt and requires true before player statue creation. Non-player branches remove directly. Petrification is binary and receives no Stage multiplier; fallback melee/Poison retain native numeric routes. [Combat semantics, immunity, exact integration points and future fixtures](benchmarks/external-effects-catalog/iceandfire-r2g4-review.md). Dragons next; Ice & Fire PARTIAL.\n'
    main.write_text(text,encoding='utf-8')

if __name__=='__main__':save()
