from catalog_common import *
from cataclysm_combat_common import save_section

START='4c8e24d9a493617cd9cf158e210877e15ef437ec'
CP='R2k2a-cataclysm-shared-admission-complete'
STEM='cataclysm-r2k2a-shared-admission'
NEXT='R2k2b: Cataclysm status/control and global event admission. Begin STUN and both LivingEntityMixin addEffect overloads, Unbreakable Skull cooldown, attack/use/jump/target hooks; then the other eleven registered effects and real native producers. Concrete boss overrides/attacks and equipment remain pending. Continue automatically while quota is healthy; static only.'
FACTS={
 'authority_and_scope':'Six installed Cataclysm class witnesses and patched Minecraft1.21.1/NeoForge21.1.244 pin the shared contracts below. The inheritance index records thirteen classes, including two bases and eleven concrete subclasses. Concrete hurt/cap/phase/immunity overrides remain family work; these contracts apply only when that actual call chain reaches the shared implementation. No boss runtime tests or generic compatibility guarantee.',
 'hurt_order':'Both LLibrary_Boss_Monster.hurt and IABoss_monster.hurt first call virtual isInvulnerableTo(source), rejecting when true. Next, BYPASSES_INVULNERABILITY directly returns super.hurt(source,original amount), skipping the shared cap/range/bucket and self-regen timer bookkeeping. Otherwise clamp amount to min(DamageCap(),incoming), apply causing-entity distance admission/falloff, save the prior bucket, update the bucket unless cataclysm:bypasses_hurt_time, then call super.hurt with the SAME source and selected amount. Successful hurt resets self_regen only for cataclysm:block_self_regen; failed hurt rolls back the bucket. Standard native cooldown, armor, shield, Resistance and event processing remain downstream. A true hurt return is not proof of final HP loss.',
 'range':'Animation_Monsters.calculateRange reads source.getEntity(), the causing entity, and its CURRENT distanceSquared from the boss. Null causing entity returns -1 and skips this distance gate; direct projectile distance, launch position, source position and LOS are not tested here. Let L=RangeLimit(): distance>=1.5L rejects, distance>L multiplies amount by (1.5L-distance)/(0.5L) and rejects a nonpositive result. Exact L admits without attenuation; exact1.5L rejects. Anonymous environmental damage and projectiles with/without causing owners are distinct native fixtures. Do not invent an owner to change this admission.',
 'bucket':'Bucket capacity is DamageCap(), NOT DpsCap(). After per-hit cap/falloff, projected=bucket+amount. If projected exceeds capacity: positive remaining room becomes the selected amount and bucket becomes capacity; with no room the code STILL attempts 0.1F damage, leaving bucket unchanged. Otherwise it adds the requested amount to the bucket. It tracks pre-mitigation requests, not measured HP loss. On failed super.hurt it restores the saved bucket. Each server tick with AI enabled drains positive bucket by DpsCap()/20 and clamps negative to0. NoAI prevents decay. cataclysm:bypasses_hurt_time skips only this bucket logic, retaining per-hit cap/range and ordinary native hurt cooldown unless another native tag bypasses that cooldown. No extra Stage multiplier belongs on caps, bucket capacity/drain, distance or the0.1 fallback: preserve this target admission after scaling a real outgoing payload at its producer.',
 'defaults_and_tags':'Base DamageCap and DpsCap are Float.MAX_VALUE, RangeLimit Double.MAX_VALUE, NatureRegen0 and HealCooldown200; concrete overrides remain pending and must not be replaced with these defaults. Pinned MC/NeoForge/Cataclysm tag closure: bypasses_hurt_time={abyssal_burn,maledictio_sagitta,shredder,generic_kill,out_of_world,wither,neoforge:poison}; block_self_regen={generic_kill,mob_attack,out_of_world,player_attack}, with unqualified names in their natural Cataclysm or Minecraft namespace as enumerated in evidence. Ordinary arrow/thrown/explosion sources do not reset this shared timer under these shipped tags. Even tag membership does not reset on the early BYPASSES_INVULNERABILITY return. Other pack/datapack tag contributions remain unmeasured.',
 'native_regen':'super.tick runs first. Positive self_regen decrements on both sides, even NoAI. On the server with AI enabled, self_regen<=0 AND NatureRegen()>0 AND target==null AND tickCount%20==0 call heal(NatureRegen()). No extra alive check here; native LivingEntity.heal and NeoForge healing hooks remain authoritative. Future Stage point: ONCE on the positive NatureRegen() amount entering this shared heal call; preserve cadence, target/no-AI/timer gates and native heal admission/max-HP clamp. Never also multiply config or global healing callbacks. Attack-triggered timer reset requires actual hurt=true plus the shipped tag; effect applications do not reset it by this layer.',
 'effect_whitelist':'Both bases require effect.getEffect().getDelegate().is(cataclysm:effective_for_bosses) AND super.canBeAffected(effect). This is a real Holder tag check. The shipped replace=false whitelist has31 values:27 vanilla plus monstrous,abyssal_burn,blazing_brand,ghost_sickness. Poison,STUN,Levitation,SlowFalling and the other eight Cataclysm effects are not included by this resource. Patched addEffect posts NeoForge Applicable: DEFAULT calls the virtual filter, APPLY can admit without that filter, DO_NOT_APPLY rejects. Cataclysm mixin HEAD admission and concrete boss overrides may add gates; these are not resolved by whitelist membership. Preserve native external effect admission, including Tensura/L2 listeners. No scalable value exists in the whitelist.',
 'home_control':'HOME_COOLDOWN is captured at instance construction as CMCommonConfig.ETC.ReturnHome*20 (installed common-file value20 seconds ->400 ticks, not proof of runtime-loaded config). finalizeSpawn initializes homeTicks; the shared base does not establish the actual home position. On server AI ticks, positive homeTicks decrements, any non-null target resets it, and <=0 invokes ReturnToHome when HOME_COOLDOWN>0. With saved home and ServerLevel: cross-dimension home with an existing server level uses native changeDimension and resets timer; otherwise a position not closer than16 to the block center uses moveTo(x+.5,y,z+.5) and resets timer. If destination level lookup fails it can fall through to that same-coordinate move in the current dimension. No additional LOS/collision/ground gate or direct heal is present in this helper. Portal prohibition does not cancel the explicit native dimension call shown. Native hooks downstream remain intact. Home GlobalPos persists; legacy Home doubles load in OVERWORLD. homeTicks,self_regen and bucket are not serialized here; loading begins with their zero defaults unless concrete code changes them. Test restored home/target state separately from fresh finalizeSpawn.',
 'life_retry':'IABoss alone defines synced LIFE default0 and persists LifeRemain. PlayerCounter counts alive, noncreative, nonspectator Players in box.inflate64 with strict distanceSquared<4096, then sets LIFE. awardKillScore for a killed ServerPlayer decrements LIFE when >0, otherwise calls Retry BEFORE super.awardKillScore. Transition1->0 does not itself call Retry; the next credited ServerPlayer kill while0 does. Base Retry is empty. Actual callers and concrete Retry behavior remain boss-family review. This is native retry bookkeeping, not HP/SHP and not a Stage-scalable payload.',
 'death_and_collision':'Animation_Monsters.die first allows CommonHooks.onLivingDeath cancellation, then processes only not removed/not already dead. It resolves native kill credit, awards score, marks dead and records combat; server death side effects (including AfterDefeatBoss) additionally require causing entity null OR causingEntity.killedEntity(server,this) true. Server death broadcast follows regardless of that callback result. onDeathUpdate calls onDeathAIUpdate before incrementing deathTime and server removal at the chosen duration. IA defaults20; LLibrary uses death animation duration-20 or20, with concrete combat death callbacks deferred. Ordinary IA collision pushes contain no damage/effect, use horizontal native motion and canBePushedByEntity; IABoss returns true. Both bases prohibit riding/portals and ordinary far/peaceful despawn. These lifecycle/ordinary collision facts add no Stage value; special attack knockback remains at its concrete producer.',
 'configuration_and_boundaries':'setConfigattribute applies native transient ADD_VALUE modifiers baseHP*hpConfig-baseHP and baseAttack*damageConfig-baseAttack, then initializes health to max. This is construction/configuration, not an independent heal delivery; concrete constructor use remains pending. Keep native configured attack damage as the input to any future one-time payload scaling. Rendering/animation-only/loot/progression utility is excluded; actual death combat callbacks remain in scope. Research changes no production, source identities, HP/SHP, Stage or eligibility.'
}

def save():
    defs=[
      ('llibrary_hurt','OTHER','Concrete boss -> LLibrary_Boss_Monster.hurt -> native parent hurt',['per-hit cap and bucket room/full0.1','true/false rollback and actual HP','concrete pre/post gates']),
      ('ia_hurt','OTHER','Concrete boss -> IABoss_monster.hurt -> native parent hurt',['per-hit cap and bucket room/full0.1','true/false rollback and actual HP','concrete pre/post gates']),
      ('range_owner','OTHER','Source causing entity -> calculateRange -> falloff/rejection',['current causing owner vs nearby direct projectile','L and1.5L boundaries','null causing source']),
      ('tag_bypasses','OTHER','Native source tags -> early bypass OR bucket-only bypass',['bypasses_invulnerability initial isInvulnerableTo','cataclysm hurt-time vs vanilla cooldown bypass','source tags/direct/causing unchanged']),
      ('bucket_tick','OTHER','AI-enabled server tick -> DpsCap()/20 bucket decay',['NoAI freeze then resume','requested amount vs mitigated HP','full bucket minimum0.1 still native hurt']),
      ('regen_timer','OTHER','Successful tagged native hit -> HealCooldown -> tick countdown',['melee/player tagged true/false','arrow/thrown/explosion shipped untagged','early bypass skips reset']),
      ('llibrary_heal','PASSIVE_AURA','LLibrary_Boss_Monster.tick -> positive NatureRegen -> heal',['target/noAI/timer/20tick boundaries','native heal hooks and max HP']),
      ('ia_heal','PASSIVE_AURA','IABoss_monster.tick -> positive NatureRegen -> heal',['target/noAI/timer/20tick boundaries','native heal hooks and max HP']),
      ('llibrary_effect','OTHER','Native addEffect -> mixin/Applicable -> LLibrary whitelist -> super',['whitelisted/unlisted effect','DEFAULT/APPLY/DO_NOT_APPLY','concrete whitelist override']),
      ('ia_effect','OTHER','Native addEffect -> mixin/Applicable -> IA whitelist -> super',['whitelisted/unlisted effect','DEFAULT/APPLY/DO_NOT_APPLY','concrete whitelist override']),
      ('home_same_level','OTHER','Native targetless home timer -> ReturnToHome -> moveTo',['each base/noAI/non-null target','home null/near/exact16/far','no direct heal']),
      ('home_dimension','OTHER','Native saved home -> server lookup -> changeDimension or coordinate fallback',['destination exists/missing','native dimension hooks','source state persisted on transfer']),
      ('home_reload','OTHER','Native NBT HomePos/legacy Home load -> zero-default timers -> tick',['finalizeSpawn vs load','legacy Overworld home','bucket and regen timer reset at shared layer']),
      ('ia_life','OTHER','Concrete caller -> PlayerCounter -> LIFE -> credited ServerPlayer kill -> Retry',['native caller still family-dependent','strict64 boundary/noncreative/alive','1->0 vs next kill at0','LifeRemain reload']),
      ('llibrary_death','OTHER','Native death hook -> die -> animation duration -> onDeathAIUpdate/removal',['death cancellation','causing killedEntity result','concrete death action deferred']),
      ('ia_death','OTHER','Native death hook -> die -> deathtimer -> onDeathAIUpdate/removal',['death cancellation','causing killedEntity result','concrete death action deferred'])]
    paths=[dict(id='cataclysm:shared:'+n,labels=[label],native_path=p,runtime_status='NOT_RUN',runtime_variants=v) for n,label,p,v in defs];ids={n:p['id'] for (n,*_),p in zip(defs,paths)}
    def m(id,name,cl,point,keys):return dict(id='cataclysm:'+id,name=name,primary_classification=cl,tno_categories=['COMPOSITE','ADMISSION_GATED']+(['NUMERIC_SCALABLE'] if point else ['NO_STAGE_VALUE']),stage_scaling_needed=point is not None,single_scaling_point=point,stage_reason='Native target admission, bookkeeping or lifecycle; no separate payload for Stage.',delivery_paths=[ids[k] for k in keys])
    pk=[m('shared_hurt','Shared boss cap, causing-distance and request bucket','BINARY_MECHANIC',None,['llibrary_hurt','ia_hurt','range_owner','tag_bypasses','bucket_tick']),m('shared_regen_timer','Successful tagged-hit native regen cooldown','CUSTOM_RESOURCE',None,['regen_timer']),m('shared_heal','Targetless native boss regeneration','VANILLA_LIKE_EXTENDED','Once on positive NatureRegen() heal argument in the shared tick call; retain native cadence, gates and heal hooks.',['llibrary_heal','ia_heal']),m('shared_effect_admission','Shared boss whitelist and native effect admission','BINARY_MECHANIC',None,['llibrary_effect','ia_effect']),m('shared_home','Native boss home timer and teleport','CUSTOM_CONTROL',None,['home_same_level','home_dimension','home_reload']),m('shared_life','Native IA player-count and retry resource','CUSTOM_RESOURCE',None,['ia_life']),m('shared_death','Native boss death admission and delayed removal','BINARY_MECHANIC',None,['llibrary_death','ia_death'])]
    d=dict(schema='tno.external_effects.cataclysm_shared.v1',checkpoint=CP,previous_checkpoint='R2k1-cataclysm-source-foundation',starting_sha=START,status='SHARED_ADMISSION_AND_RESOURCE_CONTRACTS_COMPLETE',scope='Shared Cataclysm native boss hurt/effect admission, damage bucket, self-heal, home/life and death contracts; concrete overrides remain pending.',summary='Separated target admission from scalable heal: causing-owner range, rollback bucket with0.1 minimum request, real Holder whitelist and successful-tagged-hit regen timer. Seven packages and sixteen future paths; no production edits.',facts=FACTS,mechanic_packages=pk,delivery_paths=paths,review_required=[dict(id='cataclysm-shared-integration',reason='Runtime fixtures must observe native source/return/HP/effect distinctions and external event/tag contributions. No runtime compatibility certification or repair.')],remaining_subsection_native_ambiguities=[],exact_next_task=NEXT,references=['native-evidence/cataclysm-shared.json','reference-evidence/cataclysm-shared-244.json','reference-evidence/bomd-shared-244.json','cataclysm-boss-inheritance.json','cataclysm-shared-tags.json','native-evidence/cataclysm-foundation.json','cataclysm-installed-common-config.json'])
    save_section(d,STEM,'R2k2a — Cataclysm shared boss admission')

if __name__=='__main__':save()
