"""Moonworm/Cube semantics with actual native delivery and separate resources."""
from catalog_common import *
from collect_twilight_utility_projectiles import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed TF4.8.3345, raw Minecraft1.21.1 and exact NeoForge21.1.244. Native item/dispenser/impact/terrain callbacks only. HP requests, actual HP, equipment, block replacement, motion and durability stay separate. Static research, no runtime/L2/Stage/production/fix. Protected nonbreaking durability, parry, source helpers and weapon-event predicates reused.',
      'queen_use':'Moonworm Queen registered capacity256/setNoRepair; rejects ordinary enchanting and book enchanting. use fails fully damaged even creative; else starts72000-tick BOW use. Native release computes72000-useRemaining, requires server/useTime>12 (strictly13+)/damage+1<max, then addFreshEntity(MoonwormShot) must return true. Real Living shooter constructor uses speed1.5/inaccuracy1 and native shootFromRotation adds shooter motion. Only successful add plays squish and, Player&&!instabuild, protected nonbreaking cost2. No stat/cooldown/second source, no consumption on false add. One remaining charge cannot fire, including creative; direct placement can use it.',
      'queen_dispenser':'RegistrationEvents init schedules TFDispenserBehaviors.init; its actual first anonymous behavior creates ownerless MoonwormShot at native dispenser position. DamageableStackDispenseBehavior requires maxDamage>=damage+getDamageAmount; Moonworm threshold2, but common execute requests wear1 with entity=null, independent of addFreshEntity return. shoot direction(X,Y+.1,Z), speed1.1/inaccuracy18. Item retained; genuine dispenser has no Player creative/Crown owner. Native helper still processes durability hooks/Unbreaking. Protected Twilight Scepter behavior shares helper with threshold1/inaccuracy6; its projectile package remains protected. No direct Player launcher equivalent inferred for dispenser source attribution.',
      'moonworm_collision':'MoonwormShot registered .25x.25, nonfireproof; TFThrowable/ITFProjectile with native ThrowableProjectile collision, gravity float.03, air drag.99/water.8. Native Projectile.canHitEntity retains canBeHitByProjectile (normally alive and pickable) and shared-vehicle-until-left-owner gates; exact244 ProjectileImpactEvent can cancel before hitTargetOrDeflectSelf. Projectile native target deflection is separate. TF protected shield-parry route accepts ITFProjectile independent of parryNonTwilightAttacks, when no shield-parry mod and blocking within configured interval; deflect changes owner to blocker, event cancellation prevents current impact. Item not an arrow; ownerless dispenser/reflected ownership remain real native paths. isPickable=true/pickRadius1 but no hurt override: ordinary direct attack uses inherited Entity hurt, not LichBolt-style manual reflection. No custom age/expiry/NBT override; native owner/motion save remains.',
      'moonworm_head':'onHitEntity after no-op super: if Player && !hasItemInSlot(HEAD), sets HEAD=new Moonworm block item and returns. No hurt/source/HP/Resistance/armor check, team/consent/creative gate, or random draw inside this branch; native collision/event gates still apply. Existing helmet prevents branch. No overwrite of occupied slot; callback adds no armor/status modifier. Outer onHit still broadcasts particles/discards server-side after super dispatch, so successful equip consumes projectile. Administrative/creative spectator collision eligibility is inherited, not bypassed.',
      'moonworm_damage':'Other entity impact calls hurt(twilightforest:moonworm, random.nextInt(3)==0 ?1:0), ignoring return. Direct=MoonwormShot, causing=current owner (nullable); exactly one type caller. Tags only minecraft:no_knockback and neoforge:is_physical, not IS_PROJECTILE despite projectile entity. Exhaustion0, native living-nonPlayer scaling. Ordinary armor, facing shield/source position, Resistance/general Protection, absorption, cooldown and event admission remain; no TF throw-marker or poison/freeze. NO_KNOCKBACK suppresses native hurt knockback; zero request is still an attempted native hurt and need not return false or have no native attribution/cooldown effects. Never claim one HP per impact. No attack attribute/melee enchantment helper. Loot/sound/discard below do not depend on true hurt.',
      'moonworm_drop':'Non-head entity impact always on server evaluates MOONWORM_FAILED_TO_PLACE_DROPS with THIS_ENTITY=shot, ORIGIN=shot position and ownerless minecraft:fall solely as loot context (no fall hurt). Installed table returns1 Moonworm item. Creates temporary ItemEntity then calls its spawnAtLocation(item), which creates/adds the actual dropped item; no second explicit add of temporary entity. Bug sound/ENTITY_DIE event. Failed block placement uses same loot; no doMobLoot check in this callback. Native entity veto/failed hurt does not suppress these actions; canceled projectile impact does.',
      'moonworm_blocks':'onHitBlock first calls native block.onProjectileHit, then adjacent hit-face position: replaceable && not #minecraft:fire && Critter.canSurvive(face) && not lava -> setBlockAndUpdate(default Moonworm facing hit direction), result ignored, projectile-land event/sound; otherwise failure loot/squish. Support requires center support on opposite neighbor OR LeavesBlock. Projectile placement has no Player mayUseItemAt, adventure requirement, mobGriefing or BreakEvent in its TF body. It uses default waterlogged=false even when replacing water; direct Queen placement separately derives block state from context. Outer onHit after super performs server event3/discard regardless placement/damage return. No persistent damaging projectile after impact.',
      'queen_place':'Native useOn requires Player, damage<max, mayUseItemAt(adjusted target,face,stack), default Moonworm unobstructed. Calls tryPlace; returns SUCCESS even if tryPlace fails after these outer tests, but no wear on failure. tryPlace requires context.canPlace, nonnull placement state, canSurvive/unobstructed then setBlock(flags11) true. Applies BLOCK_STATE components/custom block entity tag, setPlacedBy/ServerPlayer criterion, sounds; server non-instabuild protected cost1. No shrink/break. Native block state chooses clicked face then viable looking alternatives and initial waterlogging. Moonworm registered light14/noCollision/instant break; block entity tick is only client rotation. Critter contact may squish bug block for Projectile not DONT_KILL_BUGS or FallingBlockEntity; MoonwormShot explicitly excluded. Squish replaces with water/air, installed Moonworm squish loot1 lime dye/stat/particles, not entity HP damage. No effect merely from wearing this block in this code.',
      'queen_repair':'Special native MoonwormQueenRepairRecipe installed. matches exactly one damaged Queen plus >=1 occupied Torchberry slots, no other nonempty items; no over-repair quantity cap. assemble creates DEFAULT Queen, sets damage oldDamage-64*berrySlotCount (native clamp0..max), so custom name/enchantment/components are not copied. Native crafting consumes one per used slot; stack counts do not multiply repair. Dimension>=2. Ordinary full Queen/duplicate/foreign item fails. This custom recipe works despite setNoRepair and does not use scepter Renewal. Resource primitive protected nonbreaking helper reused.',
      'cube_producer':'Cube item registered stack1/fire-resistant, no durability/cost/cooldown. Data census finds only WIP tag among installed data JSON literal cube_of_annihilation mentions, no recipe/loot producer; actual native Player.use is a valid registered-item administrative/creative fixture, without claiming survival acquisition. All-TF instruction census has only CubeOfAnnihilationItem.use as explicit runtime thrown constructor. THROWN_PROJECTILE persistent/synced UUID per stack: existing token -> PASS; otherwise server creates Cube(owner Player, same stack reference), add result ignored, stores UUID; starts72000 BLOCK use. Server inventory tick removes token if current ServerLevel UUID lookup is not loaded Cube; not a global cap/ownership check. Denied add/unloaded/other-dimension projectile may clear token. Cube entity registered1x1/fireproof, no portal use.',
      'cube_flight':'Cube extends ordinary ThrowableProjectile, NOT ITFProjectile; gravity0. Constructor shoot speed1.5/inaccuracy1; each server tick after native super collision/movement: unresolved owner -> remove(KILLED),return. Otherwise destination owner eye, or owner eye+look*16 while !hasHitObstacle and owner Player isUsingItem (ANY item, not necessarily original Cube). NonPlayer owner/obstacle/notUsing -> returning. Returning distance<2 removes, but no return afterward: velocity/block loop still executes on object that tick. Velocity set toward destination; speed> .5 normalized to.5. <=.5 calls Vec3.multiply(.5) but ignores immutable result, so no extra halving. End-of-tick terrain scan always. Native first launch movement can be1.5 before steering cap. No teleport or HP annihilation.',
      'cube_damage':'onHitEntity only Living -> native hurt10; true only adds60 to Cube.tickCount, false no increment. No hit discard, per-target list or explicit lifetime/maximum-tick check anywhere in full Cube body; +60 does not prove shortened lifetime. getDamageSource casts owner to Living: Player -> minecraft:player_attack direct=causing owner; other Living -> minecraft:mob_attack direct=causing owner; null -> minecraft:thrown direct=Cube/causing null. Null fallback may execute during super collision before later owner-null removal, not a normal stable ownerless deployment. NonLiving owner would fail cast; no legitimate producer here. Ordinary native armor/shield/Resistance/Protection/absorption/cooldown/events and applicable Player difficulty remain. Primary owner sources NOT projectile tagged, so projectile protection/source-position logic follows actual type/owner, not Cube geometry. No attack attributes/Strength/Sharpness helper automatically added to fixed10. Source ownership can still activate protected mainhand Knightmetal/Minotaur predicates under their actual conditions.',
      'cube_shield':'Cube item canDisableShield always true. Exact244 Living.canDisableShield delegates current MAINHAND item; Player shield block against non-IS_PROJECTILE source/direct Living calls native block response and can disable for100 ticks even if HP hurt false. A genuine launched Cube held MAINHAND therefore supplies a shield-disable path because source direct=owner; offhand Cube with other mainhand follows that other item instead. Ordinary Player melee holding Cube also invokes native source/weapon logic. BLOCK animation alone does NOT make Cube bearer block: exact244 Living.isBlocking requires SHIELD_BLOCK ability, inherited IItemExtension.canPerformAction=false, and Cube has no override. No fictitious defensive shield resource/damage absorption.',
      'cube_terrain':'onHitBlock if hit position nonempty calls affectBlocksInAABB(BB inflated float.2); also every server tick ends with same scan. WorldUtil.getAllInBB casts each bound to int (truncate toward zero, not floor) then inclusive BlockPos range. Each nonair block: only ServerPlayer owner; native BreakEvent must not canceled, then (#annihilation_inclusions OR explosionResistance<8 AND destroySpeed>=0) AND (not block-placing-restricted gameMode OR original stack.canBreakBlockInAdventureMode). Included tags can admit normally hard/unbreakable blocks; exact tag pinned, including deadrock/castle/force fields/thorns/nether portal. Allowed -> removeBlock(false), ignored return, sound/particles/BLOCK_DESTROY, no loot/hardness wear/XP. Veto or cancellation sets persistent-in-memory obstacle flag; continues rest of current box, and terrain remains active during return. NonServerPlayer owner skips blocks without setting obstacle. No extra mobGriefing/PlayerGameMode destroy/harvest path. No numeric damage from block removal.',
      'cube_reflection_save':'Exact244 inherited impact event/target deflection still precede Cube custom onHit. Cube custom onHit dispatches only entity/block and does not call Projectile.onHit, so its own dispatch lacks that generic redirectable-projectile target handling/PROJECTILE_LAND event. TF shield parry needs parryNonTwilightAttacks=true for this non-ITFProjectile (or separate external mod behavior, not claimed here); native accepted parry changes owner to blocker, while stored original stack reference/token is not relinked. Steering/damage/terrain then follow new owner. Native owner/motion and CubeOfAnnihilationStack save; hasHitObstacle/tickCount not explicitly saved by Cube, obstacle resets false on construction. remove stops resolved Living owner only if current use item is Cube, even another Cube stack. Bare registry/admin entity constructor leaves stack null; missing saved stack can fail save/restricted terrain path, so no claim of a fully configured summon equivalent. Real item producer supplies stack.'
    }
    Q='item/MoonwormQueenItem';M='entity/projectile/MoonwormShot';R='item/recipe/MoonwormQueenRepairRecipe';C='entity/projectile/CubeOfAnnihilation';I='item/CubeOfAnnihilationItem';D='dispenser/DamageableStackDispenseBehavior';B='block/CritterBlock'
    nxt='Continue Task C with Ender/Seeker/Triple bows and Peacock Fan native control/source paths, then remaining armor/charms/food, utility/passive entities, hazards and11 unfinished custom DamageTypes; close exact nested ASM/compatibility coverage. Protect each subsection toward R2f8 and final whole-Twilight dedup/promotion. IceAndFire only after COMPLETE Twilight pushed/live verified. No runtime boss/L2/Stage/production/fixes/Phase6/7.'
    data=dict(slug='utility-projectiles',checkpoint_short='r2f8k',checkpoint='R2f8k-utility-projectiles-complete',decision='TWILIGHT_UTILITY_PROJECTILES_SEMANTIC_REVIEW_COMPLETE',starting_sha='e5c8d8929aca86db5c3d0f9a7925cd662714fab1',previous_checkpoint='R2f8j-scepter-payloads-complete',previous_draft='partial-drafts/twilightforest-r2f8j-partial.json',facts=facts,packages=[],paths=[],new_damage_types=1,full_classes=FULL,limited_classes={'dispenser/TFDispenserBehaviors':['init'],'events/EntityEvents':['protected onParryProjectile'],'util/WorldUtil':['getAllInBB'],'init/TFItems':['actual item constructors'],'init/TFBlocks':['Moonworm constructor'],'init/TFDataComponents':['THROWN_PROJECTILE codec']},registration_classes=['init/TFItems','init/TFEntities','init/TFBlocks','init/TFDataComponents','init/TFRecipes','events/RegistrationEvents','dispenser/TFDispenserBehaviors'],closure_checklist=['genuine_Queen_release','real_dispenser_owner_cost','bare_head_vs_hurt','zero_one_native_source','independent_loot','block_placement_gates','repair_default_output','native_parry_owner','Cube_registered_producer','per_stack_token','flight_return_ignored_vector','fixed10_owner_source','shield_disable_not_block','terrain_event_tag_adventure','save_and_null_stack_scope'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus complete Moonworm Queen/shot/repair/block and Cube item/entity/native source/control/terrain contracts; Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=28,new_used_profiles=1,reviewed_profiles_after=29,remaining_profiles=11,remaining_disposition='Other actual caller profiles unfinished, not unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    hit=pkg('moonworm_hit','Moonworm zero-or-one native impact','CUSTOM_DAMAGE',['queen_use','queen_dispenser','moonworm_collision','moonworm_damage','moonworm_drop'],[Q,M,D,'dispenser/TFDispenserBehaviors$1','init/TFDamageTypes'],{'chance_one':'1/3','otherwise':0,'gravity':.03},['native impact','not bare-head Player','return ignored','independent loot'],'Custom physical/no-knockback source, not generic projectile tag.','Native Queen shot against occupied-head Living',['Ownerless dispenser, native parry, armor/shield/cooldown, zero request'])
    head=pkg('moonworm_head_equip','Moonworm bare-head forced equipment','BINARY_MECHANIC',['moonworm_head','moonworm_collision'],[M],{'equipped_count':1},['Player','HEAD empty','impact admitted','no hurt'],'Native equipment mutation instead of damage.','Native Queen shot on bare-headed Player',['Occupied slot, canceled impact, dispenser/reflection ownership'])
    place=pkg('moonworm_placement','Moonworm placement and native bug lifecycle','VANILLA_LIKE_EXTENDED',['moonworm_blocks','queen_place','moonworm_drop'],[M,Q,B,'block/MoonwormBlock','block/entity/MoonwormBlockEntity'],{'light':14,'placement_cost':1,'failed_drop':1},['support/replaceability','different direct-use gates','native block state','no collision/HP payload'],'Block placement/light and loot primitives through projectile-specific admission.','Native Queen useOn and shot on block face',['Water/fire/lava/leaves, obstructed/failed placement, bug squish exception'])
    resource=pkg('moonworm_charge_repair','Moonworm charge and Torchberry repair','CUSTOM_RESOURCE',['queen_use','queen_dispenser','queen_place','queen_repair'],[Q,R,D,'dispenser/TFDispenserBehaviors$1'],{'capacity':256,'release_cost':2,'placement_cost':1,'dispenser_threshold':2,'dispenser_cost':1,'repair_per_slot':64},['release>12','native add result','nonbreaking helper','native recipe/default output'],'Persistent charge durability with distinct producer cost/repair routes.','Native Queen fire/place/dispenser and manual repair',['One remaining charge, creative, add rejection, overrepair/components'])
    flight=pkg('annihilation_cube_control','Cube tracking, steering and return','CUSTOM_CONTROL',['cube_producer','cube_flight','cube_reflection_save'],[I,C,'init/TFDataComponents'],{'look_distance':16,'steering_speed_cap':.5,'return_distance_strict':2,'duration':72000},['per-stack UUID','owner/any item use','obstacle','native movement/save'],'Custom owned-projectile steering and resource tracking.','Native registered Cube item use',['Unloaded UUID, denied add, release/obstacle, parry owner and reload'])
    damage=pkg('annihilation_cube_hit','Cube fixed native melee-source hit and shield disable','VANILLA_LIKE_EXTENDED',['cube_damage','cube_shield','cube_producer'],[C,I,'events/ToolEvents'],{'request':10,'tick_increment':60,'shield_disable':100},['Living collision','owner source branch','true increments counter only','current MAINHAND shield predicate'],'Native melee/nullable thrown damage through a distinct projectile carrier.','Native launched Cube against Living',['Owner-source direction/armor/protection, shield block, offhand and repeated-hit cooldown'])
    terrain=pkg('annihilation_cube_terrain','Cube admitted terrain removal','BINARY_MECHANIC',['cube_terrain','cube_flight','cube_reflection_save'],[C,'util/WorldUtil'],{'inflate':.2,'resistance_strict':8},['ServerPlayer owner','BreakEvent','inclusion OR resistance/hardness','adventure predicate','no drops'],'Binary native block removal with explicit event/tag/adventure gates.','Native Cube moving through eligible blocks',['Included hard blocks, event veto, negative coordinates, returning scan and reflected owner'])
    data['packages'][3]['reuses_protected_effect_ids']=['twilightforest:scepter_charge_resource']
    data['packages'][5]['reuses_protected_effect_ids']=['twilightforest:knight_phantom_haunt','twilightforest:minoshroom_axing']
    data['damage_profiles']=[dict(type='twilightforest:moonworm',status='USED',callers=[dict(entry='twilightforest/entity/projectile/MoonwormShot.class',method='onHitEntity')],amount='nextInt(3)==0 requests1, otherwise0; no hurt for bare-headed Player branch.',direct_and_causing_entities='Direct MoonwormShot; causing current nullable owner (shooter or native parry blocker).',mitigation=facts['moonworm_damage'],success_gates='Impact/event/deflection and head branch; hurt return ignored.',secondary_payload='Independent native loot/sound and server discard; bare-head path equips instead.')]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:utility_projectiles_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' using real native mechanics; future fixture only, no runtime/fabricated source.',future_controls=controls))
    rows=[
      ('queen_release','Native Queen charged release',['queen_use'],[hit,resource],[Q,M],['ACTIVE_ITEM','PROJECTILE'],['strict13+','two charges','add true','creative']),
      ('queen_release_negative','Native Queen release negatives',['queen_use'],[resource],[Q],['ACTIVE_ITEM'],['<=12','one remaining','exhausted creative','add false']),
      ('queen_dispenser','Native Moonworm dispenser',['queen_dispenser'],[hit,resource],[D,'dispenser/TFDispenserBehaviors$1'],['PROJECTILE','OTHER'],['owner null','threshold2/cost1','speed1.1/inaccuracy18','add ignored']),
      ('moonworm_head','Native bare-head impact',['moonworm_head','moonworm_collision'],[head],[M],['PROJECTILE'],['Player HEAD empty','equip not damage','discard']),
      ('moonworm_head_negative','Native occupied-head and impact controls',['moonworm_head','moonworm_damage'],[head,hit],[M],['PROJECTILE'],['occupied slot no overwrite','native event cancellation','collision gates']),
      ('moonworm_hurt','Native non-head Moonworm hit',['moonworm_damage','moonworm_drop'],[hit],[M],['PROJECTILE'],['random1/0','NO_KNOCKBACK not IS_PROJECTILE','return ignored']),
      ('moonworm_hurt_negative','Native Moonworm damage defenses',['moonworm_damage','moonworm_drop'],[hit],[M],['PROJECTILE'],['armor/Resistance/shield/cooldown','zero request','loot independent']),
      ('moonworm_parry','Native Moonworm shield parry',['moonworm_collision'],[hit,head],[M,'events/EntityEvents'],['PROJECTILE'],['ITFProjectile','configured timing','new owner','current impact canceled']),
      ('moonworm_place','Native Moonworm projectile placement',['moonworm_blocks'],[place],[M,B],['PROJECTILE'],['support/leaves','replaceable','not fire/lava','default waterlogging']),
      ('moonworm_failed','Native Moonworm failed placement drop',['moonworm_blocks','moonworm_drop'],[place],[M],['PROJECTILE'],['one Moonworm loot','fall context not damage','discard']),
      ('queen_place','Native direct Queen placement',['queen_place'],[place,resource],[Q,B],['ACTIVE_ITEM'],['mayUse/unobstructed/support','true setBlock cost1','one remaining charge']),
      ('queen_place_negative','Native direct placement result controls',['queen_place'],[place,resource],[Q],['ACTIVE_ITEM'],['outer SUCCESS may contain tryPlace FAIL','no wear on failure','creative']),
      ('moonworm_bug','Native placed Moonworm lifecycle',['queen_place'],[place],[B,'block/MoonwormBlock','block/entity/MoonwormBlockEntity'],['ENVIRONMENT','PROJECTILE'],['light14/noCollision','support/water','shot DONT_KILL_BUGS','squish loot not HP']),
      ('queen_repair','Native Torchberry repair',['queen_repair'],[resource],[R],['OTHER'],['64 per occupied slot','one damaged Queen','default output/clamp']),
      ('queen_repair_negative','Native repair/component controls',['queen_repair'],[resource],[R],['OTHER'],['full/duplicate/foreign fails','overrepair allowed','components not copied']),
      ('cube_use','Native registered Cube item use',['cube_producer'],[flight],[I,C],['ACTIVE_ITEM','PROJECTILE'],['real item fixture','no proven survival recipe/loot','UUID/add return','no durability']),
      ('cube_tracking','Native Cube UUID cleanup',['cube_producer'],[flight],[I],['PASSIVE_ITEM','OTHER'],['per stack/current level loaded lookup','unloaded/denied add','not global cap']),
      ('cube_flight','Native Cube outbound/return steering',['cube_flight'],[flight],[C],['PROJECTILE'],['any item use','look16/cap.5','ignored slowdown','return<2']),
      ('cube_hit','Native Cube Living impact',['cube_damage'],[damage],[C],['PROJECTILE'],['fixed10','player/mob direct owner','true +60 only','no hit discard']),
      ('cube_defense','Native Cube mitigation and repeat controls',['cube_damage'],[damage],[C],['PROJECTILE'],['owner direction','ordinary cooldown/armor','not projectile tag','no lifetime claim']),
      ('cube_shield','Native Cube source shield disable',['cube_shield','cube_damage'],[damage],[C,I],['PROJECTILE','MELEE'],['current MAINHAND Cube','native Player block','100 disable even false hurt','BLOCK is not SHIELD_BLOCK']),
      ('cube_offhand','Native Cube other-hand/source predicates',['cube_shield','cube_damage'],[damage],[C,I,'events/ToolEvents'],['PROJECTILE','ACTIVE_ITEM'],['other mainhand controls disable','protected Knightmetal/Minotaur predicates']),
      ('cube_terrain','Native Cube block removal',['cube_terrain'],[terrain],[C,'util/WorldUtil'],['PROJECTILE','ENVIRONMENT'],['event/tag/resistance/adventure','remove no drops','inclusive truncated box']),
      ('cube_obstacle','Native Cube terrain veto and return',['cube_terrain','cube_flight'],[terrain,flight],[C],['PROJECTILE','ENVIRONMENT'],['cancel/obstacle','scan continues','return still removes','nonServerPlayer skips']),
      ('cube_parry','Native configured Cube parry',['cube_reflection_save'],[flight,damage,terrain],[C,'events/EntityEvents'],['PROJECTILE'],['requires nonTF config','new owner','stored stack not relinked']),
      ('cube_save','Native Cube reload/removal boundaries',['cube_reflection_save','cube_damage'],[flight,damage],[C,I],['OTHER','PROJECTILE'],['native owner/stack','obstacle resets','null-owner transient fallback','bare admin stack-null caveat'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-utility-projectiles-caller-scan.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','reference-evidence/twilight-frosted-244.json','reference-evidence/twilight-lich-244.json','reference-evidence/twilight-minoshroom-knight-244.json','reference-evidence/twilight-scepter-payloads-244.json']
    data['exclusions']=['Ten complete native class surfaces and genuine item/dispenser/data callers. Moonworm block client animation and Critter jar/decorative handling have no additional HP/status payload.','Cube registered WIP item has native behavior but no installed data recipe/loot acquisition proven; do not invent survival producer.','Protected Twilight bolt/parry/charge and mainhand bonus packages remain unchanged; optional recipe-viewer/accessory/other gear attribution scoped to whole-mod closure.','No fixes to ignored return/vector, default repair components, null stack or source identity; static research only.','MOONWORM USED:29/40 types reviewed,11 unfinished; Twilight PARTIAL/zero promoted/REVIEW_REQUIRED0.']
    data['fixture_groups']=['Real Queen charged/direct/dispenser use with distinct cost/add-return/creative controls.','Bare-head equip versus random zero/one source, native defenses, impact/parry and independent loot.','Projectile versus direct block placement, native support/fluid/bug collision and Torchberry repair.','Registered Cube item UUID/outbound/return/source/shield and terrain event/tag/adventure controls.','Native reflected owner/reload/nullable-source distinctions without fabricated summon configuration.']
    data['expected_counts']=dict(mechanic_packages=7,delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=1)
    write_json(OUT/'review-inputs/twilightforest-utility-projectiles.json',data);assemble('twilightforest-utility-projectiles.json')

if __name__=='__main__':build()
