"""Reviewed spider, swarm, crab and borer contracts; no new custom damage type."""
from catalog_common import *
from collect_twilight_arthropods import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'pipeline':'Installed Twilight4.8.3345 with raw Minecraft1.21.1 and exact NeoForge21.1.244. These melee paths use native minecraft:mob_attack, direct=causing actual attacking mob, effective ATTACK_DAMAGE plus ordinary native enchantment processing; no custom DamageSource or armor/shield/Resistance/protection/cooldown bypass. Native causingLiving difficulty scaling applies to Player victims. Native hurt true is admission, not a measured HP loss. Hunger is a vanilla MobEffect/resource operation, not another damage event; any later starvation is separate ownerless minecraft:starve, not attributed to the mosquito. Static source evidence only; no runtime, L2, SHP, Stage or production claim.',
      'spider_inheritance':'All four TF Spider descendants retain native Float, Armadillo avoidance (range6, speeds1/1.2, only not-scared Armadillo), leap .4, retaliation and IronGolem targeting. Spider uses WallClimberNavigation and sets a climbing flag from horizontalCollision; exact cobweb makeStuckInBlock skips the ordinary slowdown. Exact Poison is rejected before superclass canBeAffected, including in the installed244 authority (Spider class has no244 replacement). No outgoing poison payload is added. Ordinary native effects, equipment, mitigation and health persistence remain. TF adds Hedge/King/Swarm/Broodling, HelmetCrab and Borer to minecraft:arthropod, affecting tag-based native Bane of Arthropods rather than granting Poison immunity to non-Spider classes. MosquitoSwarm is not in this scoped TF arthropod contribution. No new shield, boss phase or death attack in these bodies.',
      'spider_finalize':'Spider.finalizeSpawn calls super then rolls nextInt(100)==0 for a vanilla Skeleton, directly finalizes it with the caller spawn reason and starts it riding the spider. Passenger creation has no explicit addFreshEntity here; ordinary native passenger-tree insertion is required. With null group data create SpiderEffectsGroupData; on Hard, randomFloat < .1*localDifficulty.specialMultiplier selects one infinite amplifier0 effect: nextInt(5) 0/1 Speed,2 Strength,3 Regeneration,4 Invisibility. Existing group data can share the selected effect. Ordinary native MobEffect attribute/heal/visibility behavior and save/load apply, not a custom resource or fixed unmodified melee amount. TF subclass finalize runs after this native setup; source fixtures must retain genuine finalization and passenger state.',
      'hedge':'HedgeSpider uses native Spider HP16/speed.3/baseattack2. Its registerGoals removes all MeleeAttackGoal instances and installs ordinary MeleeAttackGoal(priority4,speed1,longMemorytrue); replaces only priority2 NearestAttackableTargetGoal with ordinary visible Player targeting. Thus removes SpiderAttackGoal vehicle-start veto and brightness-based random continuation stop, and removes Player darkness targeting gate. Inherited IronGolem targeting still needs brightness<.5; retaliation/Armadillo avoidance/native target eligibility remain. onClimbable remains inherited. Spawn placement uses HedgeSpider.canSpawn: nonPeaceful and either current chunk landmark HEDGE_MAZE or ordinary dark-enough test; this method itself lacks SwarmSpider extra checkMobSpawnRules. Native spawn engine/placement/event checks remain; no assertion of universal aggression or unconditional spawning.',
      'king':'KingSpider HP30/speed.35/attack6, registered1.6x1.6, inherits Spider goals unchanged but onClimbable always false. Native SpiderAttackGoal.canUse requires super.canUse AND !isVehicle; therefore a freshly finalized ridden King cannot start its normal melee goal. Vehicle check is not repeated in canContinueToUse, so it is a start gate, not universal damage immunity or an override of doHurtTarget. Unridden admitted melee uses native mob_attack effective6. Player/IronGolem target acquisition requires brightness<.5; active SpiderAttackGoal can stop at brightness>=.5 with nextInt(100)==0. King finalize calls super, then creates adult SkeletonDruid, directly finalizes JOCKEY, walks first-passenger chain and starts the Druid riding the last rider. It does not eject passengers: the native1% Skeleton case can form King -> Skeleton -> Druid. Each entity retains separate HP/source/AI; no shared master or health pool. Druid equipment/NatureBolt payload is reused from protected ranged section. Attachment height .85*King height is geometry only.',
      'swarm':'SwarmSpider HP3/speed.3/attack1, clustermax6; TowerBroodling inherits Swarm with HP7/attack4, speed.3. Both share Hedge-style ordinary melee and brightness-independent visible Player acquisition, climbing/web/Poison inheritance. Swarm.doHurtTarget first rolls nextInt(4)==0, otherwise returns false without invoking superclass damage. Native AI attempt cooldown can still reset on the failed attempt; probability is per callback, not final HP success. Tower inherits this exact gate. getReinforcementType returns their own EntityTypes, but an all-TF-class instruction scan proves zero call sites for that method: no native reinforcement producer is established by the method name or spawn cluster6. Swarm native spawn placement uses nonPeaceful && (HedgeMaze landmark OR dark) && checkMobSpawnRules; registered TowerBroodling placement instead explicitly uses Monster.checkMonsterSpawnRules. They are not equivalent static-spawn paths.',
      'swarm_jockey':'Protected R2f8a Swarm finalize/jockey contract is reused: superclass Spider setup first, then existing first passenger OR nextInt(200)==0 causes baby SkeletonDruid creation, setBaby(true), EventHooks.finalizeMobSpawn(JOCKEY), eject prior passengers if any, and startRiding spider. This can replace the superclass Skeleton, not stack on it. TowerBroodling overrides summonJockey with an empty method, suppressing this TF baby replacement only; Spider.finalizeSpawn still runs and can create its native Skeleton. Ordinary melee replacement has no Spider vehicle-start veto for either species. This extends producer coverage without duplicating protected Druid permanent-baby or NatureBolt packages.',
      'mosquito':'MosquitoSwarm Monster HP12/speed.23/attack3/stepheight2.1, registered.7x1.9. Ground navigation with Float0/Melee3 speed1 longMemoryfalse/stroll6, retaliation and visible Player targeting; no flying navigation inferred from appearance. doHurtTarget first calls super; only true and LivingEntity applies vanilla Hunger amplifier0: Easy140ticks, Hard600, default300 (including code default Peaceful, whose ordinary Player hurt admission normally prevents it). addEffect has no explicit attacker and retains native eligibility, merging, removals and ticking. False hurt adds no Hunger. Non-Player Living can receive Hunger but its native tick only changes Player exhaustion. displayFireAnimation false is cosmetic, not fire immunity; registration is not fireproof. TF entity tags grant fall_damage_immune and powder_snow_walkable_mobs. canRide false and clustermax1. No poison, custom source, healing or summon.',
      'hunger':'Native HungerMobEffect applies every effect tick: Player.causeFoodExhaustion(.005*(amplifier+1)); Player requires !abilities.invulnerable and server. FoodData caps exhaustion at40; tick consumes4 only when exhaustion>4, then removes up to1 saturation, else1 food when difficulty is not Peaceful. Thus nominal new amp0 exhaustion is .7/1.5/3 across uninterrupted140/300/600ticks before other food operations; no fixed immediate food/HP subtraction. Ordinary natural regeneration can heal and consume exhaustion (food20 with saturation: every10ticks heal min(saturation,6)/6; food>=18: every80ticks heal1, exhaust6). With food<=0 the native counter at80ticks requests ownerless starve1 if HP>10 OR Hard OR (HP>1 AND Normal), ignores hurt return then resets counter. Native source mitigation/event admission still applies; no mosquito owner propagated and no guaranteed death or HP loss. Effects/resource counters retain ordinary native persistence.',
      'crab_exclusion':'HelmetCrab fully reviewed: Monster HP13/speed.28/attack3/armor6, registered.8x1.1/eye.45. Float0, custom AlwaysWatchTargetGoal1, ordinary LeapAtTargetGoal2(.28), Melee3 and stroll/look; retaliation and visible Player targeting. AlwaysWatch has no conflict flags, requires every tick, canUse target!=null and inherited continuation repeats canUse; lookControl.setLookAt(target,100,100), no damage/target eligibility override. Leap/control and armor6 are ordinary vanilla primitives; no shell HP, directional shield, reflect, armor break or special payload. Synced BLUE=false, finalize nextInt(10000)==0, saved blue; rendering/helmet angle only, no combat modifier. Therefore ordinary melee/armor/leap/watch and blue variant are documented exclusions rather than inflated unique effect packages. Borer/Crab do not inherit Spider Poison immunity.',
      'borer_body':'TowerwoodBorer Monster HP15/speed.27/attack5/follow8, registered.4x.3. Ordinary melee4/Float1/ClimbOnTopPowderSnow1, visible Player acquisition and HurtByTargetGoal.setAlertOthers; shared retaliation is ordinary native AI, separate from releasing infested blocks. Movement emission EVENTS and isSteppingCarefully false; not silent/no-sensor immunity. TF adds powder_snow_walkable_mobs, arthropod and immune_to_infested; native LivingEntity rejects INFESTED MobEffect for the last tag, not Poison generally. No custom damage source or death attack, ownership link, saved reinforcement counter, boss state or spawn HP copied from another borer.',
      'borer_notify':'TowerwoodBorer.hurt ordering: isInvulnerableTo(source) false-return first; then if (source.getEntity()!=null OR source.is(ALWAYS_TRIGGERS_SILVERFISH)) && summonBorers!=null, notifyHurt(); finally super.hurt(source,amount). Causing entity, not merely direct entity, admits the first predicate. No positive-amount or final-hurt-success requirement before scheduling; later shield/cooldown/event rejection can leave the timer armed. Raw tag contains minecraft:magic; exact244 adds #neoforge:is_poison containing neoforge:poison plus optional #forge:is_poison. This source-tag route admits ownerless magic/poison; arbitrary ownerless physical damage is not equivalent. Runtime third-party datapack contributions are outside the scoped native tag proof. notify sets20 only at0, does not refresh an active positive counter. Goal has no flags and no requiresUpdateEveryTick override:20 goal tick callbacks, not a promise of20 world ticks; ordinary Mob goal cadence applies.',
      'borer_release':'SummonBorersGoal tick decrements counter; at<=0 scans offsets in order y=0,1,-1,...5,-5 outer, x=0,1,-1,...10,-10 middle, z similarly inner (21*11*21=4851 candidate positions). For each exact INFESTED_TOWERWOOD, canEntityGrief true calls world.destroyBlock(pos,true), ignores return, emits BLOCK_DESTROY; false replaces with ordinary TOWERWOOD flags3, no drop callback or released borer. After each matching block, nextBoolean true exits the entire scan regardless mutation success; otherwise continues. No LOS, hurt success, owner, Player or HP test in scan. Successful drop-bearing destruction can reach InfestedTowerwoodBlock.spawnAfterBreak and produce a fresh borer under its separate gates. No direct spawn call in the goal, no guaranteed count, and repeated hurt while timerpositive does not reset it.',
      'borer_hide':'HideInTowerwoodGoal extends RandomStroll speed1/interval10, MOVE flag. canUse requires no target and finished navigation; nextInt(10)==0 && canEntityGrief then chooses one of six Directions, examines floor(x,y+.5,z)+direction for exact TOWERWOOD. A match sets doMerge true; otherwise clears it and uses normal stroll. start recomputes neighbor, requires still exact TOWERWOOD and nextInt(5)==0, then setBlock INFESTED_TOWERWOOD flags3, spawnAnim, discard self. SetBlock return is ignored; failed placement can still discard the entity. doMerge prevents continuation. Chance is conditional on native AI evaluation, chosen direction, griefing and terrain, not an unconditional1/50 world-tick rate. Block stores no entity HP/effects/UUID; a later released borer is newly created, not healing or restoring this one. No native hurt/death/source for hide-discard.',
      'infested_block':'InfestedTowerwoodBlock extends ordinary Block, overriding spawnAfterBreak only. Calls super, then server && doBlockDrops && !EnchantmentHelper.hasTag(tool,PREVENTS_INFESTED_SPAWNS) creates fresh TowerwoodBorer at(x+.5,y,z+.5), addFreshEntity, spawnAnim. No finalizeMobSpawn, owner/master, stored HP, spawn chance, Player-only or internal mobGriefing predicate; boolean sourceIsPlayer is unused. Native prevents_infested_spawns contains Silk Touch, no additional244 contribution. Player harvest/dropResources and Borer destroyBlock(true) reach exact244 CommonHooks.handleBlockDrops: post BlockDropsEvent, only notCanceled spawns event drops then state.spawnAfterBreak(...,tool,false); its false boolean does not prevent the TF release. Replacement/setBlock and destroyBlock(false) do not reach this callback; ordinary creative destruction also skips harvest drops. Late drop-event cancellation suppresses release; tool or doBlockDrops gate suppresses it independently.',
      'infested_explosion':'Legitimate native destructive explosion follows exact244 BlockBehaviour.onExplosionHit: nonair && interaction!=TRIGGER_BLOCK, then canDropFromExplosion && ServerLevel -> spawnAfterBreak(EMPTY,indirectSource instanceof Player) before getDrops/onBlockExploded. InfestedTowerwood ignores that Player boolean; with doBlockDrops true, empty tool cannot carry Silk Touch, so admitted explosion block processing can release a fresh borer independently of entity-damage hurt returns or explosion loot decay. Native explosion block selection/events/griefing/drop-from-explosion conditions remain. This is a separate callback path from CommonHooks.handleBlockDrops and its BlockDropsEvent gate; no assumption that cancellation of unrelated entity HP damage prevents block spawn. No guaranteed release from a non-destructive/TRIGGER_BLOCK/unselected/protected block.'
    }
    M='entity/monster/';B='block/InfestedTowerwoodBlock';G='entity/ai/goal/AlwaysWatchTargetGoal'
    data=dict(slug='arthropods',checkpoint_short='r2f8e',checkpoint='R2f8e-arthropods-complete',decision='TWILIGHT_ARTHROPODS_SEMANTIC_REVIEW_COMPLETE',starting_sha='f87c0a08b85f49b88c4262d4852066bea8199fe9',previous_checkpoint='R2f8d-giants-tools-complete',previous_draft='partial-drafts/twilightforest-r2f8d-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=0,full_classes=FULL,limited_classes={'init/TFEntities':['reviewed entity registrations'],'events/RegistrationEvents':['reviewed attributes and spawn placements']},registration_classes=['init/TFEntities','events/RegistrationEvents'],closure_checklist=['native_spider_inheritance','jockey_finalization','king_vehicle_melee_gate','swarm_random_gate','no_reinforcement_caller','mosquito_hunger','native_food_vs_starvation','crab_exclusion','tagged_immunities','borer_pre_hurt_schedule','goal_cadence_and_scan','griefing_release_vs_replace','hide_discard','infested_native_drop_and_explosion','silk_and_drop_event_gates'],compatibility_scope=facts['pipeline'],current_scope='Protected bosses/Frosted/ranged/mounted/chain/giants-tools plus remaining spiders, MosquitoSwarm, HelmetCrab and TowerwoodBorer/infested towerwood complete. Twilight PARTIAL/zero promoted.',exact_next_task='Continue Task C with remaining melee/control mobs: Boggard, Redcap/Sapper, Kobold/Troll, CarminiteGolem, Adherent/HarbingerCube, MazeSlime, SnowGuardian, RisingZombie/LoyalZombie and unfinished Wraith/Minotaur bodies; then remaining items/scepters/armor/charms/projectiles/hazards/resources and15 custom caller profiles. Reuse protected arthropods and earlier subsections. Protect each logical subsection toward R2f8 and final Twilight promotion; IceAndFire only after COMPLETE Twilight is pushed. No runtime boss/L2/Stage/production/fixes/Phase6/7.',damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=25,new_used_profiles=0,reviewed_profiles_after=25,remaining_profiles=15,remaining_disposition='Other native caller profiles unfinished, not unused.'))
    def pkg(key,title,classification,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=classification,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    hedge=pkg('spider_aggression','Hedge and swarm spider native AI/defense inheritance','VANILLA_LIKE_EXTENDED',['spider_inheritance','spider_finalize','hedge','pipeline'],[M+'HedgeSpider',M+'SwarmSpider',M+'KingSpider',M+'TowerBroodling'],{'hedge_hp':16,'hedge_attack':2,'leap':.4,'native_skeleton_roll':100,'hard_effect_base_probability':.1},['native target rules','ordinary melee replacement','Poison veto','cobweb exception','finalized group state'],'Modified composition of native Spider/Monster AI, immunity and native spawn effects.','Native HedgeSpider acquisition/melee in bright and dark conditions',['Swarm descendants sharing replacement goals; native finalized effects/riders; web/Poison/Armadillo controls'])
    king=pkg('king_spider_jockey','King Spider rider composition and melee start gate','CUSTOM_CONTROL',['king','spider_finalize','pipeline'],[M+'KingSpider',M+'SkeletonDruid'],{'hp':30,'attack':6,'speed':.35,'passenger_height_fraction':.85},['native finalize','passenger tree insertion','notVehicle for melee start','native target brightness'],'Custom Druid passenger composition with inherited native Spider goal admission.','Native finalized KingSpider carrying adult Druid',['Native Skeleton/Druid rider stack; dismounted King melee; active-goal vs new-goal vehicle control'])
    data['packages'][-1]['reuses_protected_effect_ids']=['twilightforest:nature_bolt_package','twilightforest:druid_weapon_baby']
    swarm=pkg('swarm_melee_gate','Swarm and Tower Broodling probabilistic melee admission','VANILLA_LIKE_EXTENDED',['swarm','swarm_jockey','spider_inheritance','pipeline'],[M+'SwarmSpider',M+'TowerBroodling'],{'swarm_hp':3,'swarm_attack':1,'broodling_hp':7,'broodling_attack':4,'attack_roll_denominator':4,'cluster_cap':6},['random before native hurt','native goal cooldown','different spawn placements'],'Native melee with an extra callback probability gate; no proven reinforcement caller.','Native SwarmSpider and TowerBroodling ordinary melee attempts',['Baby Druid replacement reuses R2f8a; Tower native Skeleton exception; failed-roll controls'])
    data['packages'][-1]['reuses_protected_effect_ids']=['twilightforest:nature_bolt_package','twilightforest:druid_weapon_baby']
    hunger=pkg('mosquito_hunger','Mosquito melee and native Hunger resource effect','VANILLA_COMPOSITE',['mosquito','hunger','pipeline'],[M+'MosquitoSwarm',M+'MosquitoSwarm$1'],{'attack':3,'hp':12,'step_height':2.1,'easy_ticks':140,'normal_ticks':300,'hard_ticks':600,'amplifier':0,'exhaustion_per_tick':.005},['super hurt true','Living recipient','native effect eligibility','Player/server exhaustion'],'Native physical melee followed by native Hunger; starvation is separately sourced native food logic.','Native MosquitoSwarm admitted Player hit',['NonPlayer Hunger no food resource; native failed hurt; effect merge/cure; difficulty and food state'])
    summon=pkg('borer_reinforcement','Borer pre-admission reinforcement timer and block scan','CUSTOM_CONTROL',['borer_body','borer_notify','borer_release','pipeline'],[M+'TowerwoodBorer',M+'TowerwoodBorer$SummonBorersGoal',B],{'hp':15,'attack':5,'follow_range':8,'timer_goal_ticks':20,'scan_candidates':4851,'half_extent_xz':10,'half_extent_y':5},['early invulnerability','causer or damage tag','timer zero','grief hook','exact infested block','random early stop'],'Custom reinforcement scheduling via native block drops, independent of final incoming hurt success.','Native Borer harmed beside infested towerwood',['Ownerless magic/poison tag; late rejected hit; grief false replacement; drop-event and Silk controls'])
    hide=pkg('borer_hide','Borer conditional towerwood infestation and discard','CUSTOM_CONTROL',['borer_body','borer_hide'],[M+'TowerwoodBorer',M+'TowerwoodBorer$HideInTowerwoodGoal',B],{'search_roll':10,'merge_roll':5,'direction_choices':6},['no target','navigation done','grief admission','exact towerwood recheck','native goal start'],'Custom terrain/entity conversion; no HP write, damage source or stored mob state.','Native idle Borer beside ordinary towerwood',['Targeted/moving/grief-denied/wrong-neighbor/failed placement; later fresh block release'])
    inf=pkg('infested_towerwood_release','Infested towerwood native drop and explosion release','CUSTOM_CONTROL',['infested_block','infested_explosion','borer_body'],[B,M+'TowerwoodBorer'],{'fresh_borer_hp':15,'release_per_callback':1},['server','doBlockDrops','no prevents_infested_spawns tool','reachable native drop/explosion callback'],'Custom mob release on native block callbacks; independent of damage HP admission.','Native survival harvest of infested towerwood',['Borer reinforcement destruction; admitted native destructive explosion; Silk/drop-event/no-drop/creative controls'])
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:arthropods_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through ordinary native entities and callbacks; future fixture only, no fabricated source or direct HP writes.',future_controls=controls))
    rows=[
      ('hedge','Native HedgeSpider melee/acquisition',['hedge','pipeline'],[hedge],[M+'HedgeSpider'],['MOB_ATTACK','MELEE'],['bright/dark','attack2','native eligibility']),
      ('spider_defense','Native spider web/Poison/Armadillo controls',['spider_inheritance'],[hedge],[M+'HedgeSpider',M+'SwarmSpider',M+'KingSpider',M+'TowerBroodling'],['MOB_ATTACK','OTHER'],['Poison vs other effects','cobweb vs other stuck blocks','King no climb']),
      ('spider_finalize','Native spider group effects and Skeleton finalization',['spider_finalize'],[hedge],[M+'HedgeSpider',M+'KingSpider',M+'SwarmSpider',M+'TowerBroodling'],['MOB_ATTACK','OTHER'],['Hard/local difficulty','shared group data','infinite vanilla effect','passenger insertion']),
      ('king_rider','Native King adult Druid producer',['king','spider_finalize'],[king],[M+'KingSpider',M+'SkeletonDruid'],['MOB_ATTACK','PROJECTILE'],['protected NatureBolt','adult equipment','no melee goal start while ridden']),
      ('king_stack','Native King Skeleton/Druid passenger stack',['king'],[king],[M+'KingSpider'],['MOB_ATTACK','OTHER'],['first-passenger chain','no eject','separate health/source']),
      ('king_unridden','Native dismounted King melee',['king','pipeline'],[king],[M+'KingSpider'],['MOB_ATTACK','MELEE'],['attack6','brightness','goal start vs continuation']),
      ('swarm_melee','Native SwarmSpider probabilistic melee',['swarm','pipeline'],[swarm],[M+'SwarmSpider'],['MOB_ATTACK','MELEE'],['roll0/1/2/3','attack1','AI cooldown vs HP']),
      ('tower_melee','Native TowerBroodling probabilistic melee',['swarm','pipeline'],[swarm],[M+'TowerBroodling',M+'SwarmSpider'],['MOB_ATTACK','MELEE'],['same roll','attack4','no reinforcement call']),
      ('swarm_jockey','Native Swarm baby Druid replacement',['swarm_jockey'],[swarm],[M+'SwarmSpider',M+'SkeletonDruid'],['MOB_ATTACK','PROJECTILE'],['reuse protected baby/NatureBolt','existing passenger replacement']),
      ('tower_jockey','Native Tower vanilla Skeleton without TF replacement',['swarm_jockey','spider_finalize'],[swarm],[M+'TowerBroodling',M+'SwarmSpider'],['MOB_ATTACK','PROJECTILE'],['empty summonJockey','superclass1% Skeleton retained']),
      ('spider_spawn','Native registered spider spawn admissions',['hedge','swarm','spider_finalize'],[hedge,swarm],[M+'HedgeSpider',M+'SwarmSpider',M+'TowerBroodling','events/RegistrationEvents'],['MOB_ATTACK','OTHER'],['HedgeMaze exception','Swarm base spawn rules','Tower Monster placement']),
      ('mosquito_hit','Native Mosquito admitted hit and Hunger',['mosquito','pipeline'],[hunger],[M+'MosquitoSwarm'],['MOB_ATTACK','MELEE'],['3 physical then Hunger','140/300/600','no false-hurt payload']),
      ('mosquito_effect','Native Hunger nonPlayer/merge/removal',['mosquito','hunger'],[hunger],[M+'MosquitoSwarm'],['MOB_ATTACK','OTHER'],['amp0','ordinary immunity/merge/cure','nonPlayer no exhaustion']),
      ('mosquito_food','Native Player food and later starvation',['hunger','pipeline'],[hunger],[M+'MosquitoSwarm'],['OTHER'],['.005 exhaustion','saturation/food threshold','separate ownerless starve1','native regen']),
      ('mosquito_defense','Native Mosquito locomotion and defense controls',['mosquito'],[hunger],[M+'MosquitoSwarm'],['MOB_ATTACK','OTHER'],['ground step2.1','fall immunity','powder snow','hidden flame not immunity']),
      ('borer_entity_hit','Native Borer causing-entity hurt schedules release',['borer_notify','borer_release','borer_body'],[summon],[M+'TowerwoodBorer',M+'TowerwoodBorer$SummonBorersGoal'],['MOB_ATTACK','ENVIRONMENT'],['causing not merely direct','early invulnerability','later hurt rejection','no refresh']),
      ('borer_ownerless_tag','Native ownerless magic/poison schedules release',['borer_notify','borer_release'],[summon],[M+'TowerwoodBorer',M+'TowerwoodBorer$SummonBorersGoal'],['OTHER','ENVIRONMENT'],['minecraft:magic','neoforge:poison','arbitrary ownerless physical negative']),
      ('borer_grief_release','Native Borer grief-admitted block scan',['borer_release','infested_block'],[summon,inf],[M+'TowerwoodBorer$SummonBorersGoal',B],['AOE','ENVIRONMENT'],['20 goal callbacks','4851 positions','random exit','drop callback gates']),
      ('borer_grief_replace','Native Borer grief-denied block replacement',['borer_release'],[summon],[M+'TowerwoodBorer$SummonBorersGoal'],['AOE','ENVIRONMENT'],['ordinary towerwood','no fresh mob release','mutation return ignored']),
      ('borer_hide','Native idle Borer towerwood merge',['borer_hide'],[hide],[M+'TowerwoodBorer$HideInTowerwoodGoal'],['MOB_ATTACK','ENVIRONMENT'],['target/navigation','1/10 then1/5','six directions','discard no HP/source']),
      ('borer_hide_return','Native infestation then later fresh Borer release',['borer_hide','infested_block'],[hide,inf],[M+'TowerwoodBorer$HideInTowerwoodGoal',B],['ENVIRONMENT','OTHER'],['no stored old HP/UUID','fresh HP15','no finalize hook']),
      ('infested_harvest','Native Player infested towerwood harvest',['infested_block'],[inf],[B],['ACTIVE_ITEM','ENVIRONMENT'],['doBlockDrops','SilkTouch','BlockDropsEvent cancel','sourceIsPlayer false ignored']),
      ('infested_explosion','Native destructive explosion infested towerwood callback',['infested_explosion'],[inf],[B],['EXPLOSION','ENVIRONMENT'],['canDropFromExplosion','empty tool','not TRIGGER_BLOCK','independent HP hurt result']),
      ('infested_negative','Native no-drop/creative/replacement controls',['infested_block','infested_explosion'],[inf],[B],['ENVIRONMENT','OTHER'],['no callback no release','gamerule','native explosion selection','drop cancellation'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','vanilla-evidence/twilight-arthropod-tags.json','reference-evidence/twilight-arthropod-tags-244.json','twilightforest-arthropods-caller-scan.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','vanilla-evidence/twilight-giants-tools.json','reference-evidence/twilight-giants-tools-244.json','vanilla-evidence/twilight-ranged-mobs.json','reference-evidence/twilight-ranged-mobs-244.json','reference-evidence/twilight-chain-244.json']
    data['exclusions']=['All12 declared native class surfaces pinned; prior Swarm finalize/jockey witnesses reused rather than overwritten. Native registration/attributes/spawn methods reused.','HelmetCrab native armor/melee/leap/watch and blue variant are fully assessed exclusions, not a custom shield or inflated unique effect.','No native getReinforcementType caller exists in the installed TF class instruction census; cluster cap is not a spawn-on-hit mechanic.','Protected Druid baby/NatureBolt packages are linked, not duplicated. Native Skeleton ordinary arrow payload and native Spider random buffs remain vanilla primitives.','No new custom DamageType is introduced by this subsection: reviewed custom census remains25/40,15 unfinished.','All other Twilight areas remain unfinished; zero final promotion and no IceAndFire until whole-Twilight completion.']
    data['fixture_groups']=['Spiders: native brightness/vehicle/Poison/web/Armadillo controls, Hard group effects and distinct King/Swarm/Tower passenger producers.','Swarm/Tower: callback probability vs native AI cooldown/hurt admission, native spawn placement differences and no phantom reinforcement path.','Mosquito: genuine melee followed by Hunger, difficulty/eligibility/merge/removal, Player exhaustion/food/saturation/regen and separately sourced starvation.','Crab: ordinary armor6/melee3/leap/watch and blue cosmetic negative controls only.','Borer: early invulnerability vs late false hurt, causer vs ownerless damage tag, goal-cadence timer, spatial scan/random stop, griefing and drop callbacks.','Infested towerwood: Player harvest, native reinforcement destruction and destructive explosion; Silk/BlockDropsEvent/doBlockDrops/no-drop/creative/replacement controls.']
    data['expected_counts']=dict(mechanic_packages=7,delivery_cases=24,classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-arthropods.json',data);assemble('twilightforest-arthropods.json')

if __name__=='__main__':build()
