"""Native barrier state machines; keeps terrain disappearance separate from HP."""
from catalog_common import *
from collect_twilight_vanishing_doors import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    V='block/VanishingBlock';R='block/ReappearingBlock';L='block/LockedVanishingBlock';C='block/CastleDoorBlock';W='world/components/structures/darktower/DarkTowerWingComponent';M='world/components/structures/darktower/DarkTowerMainComponent'
    facts={
      'authority':'Exact installed Twilight4.8.3345 plus native1.21.1/NeoForge21.1.244. Four complete barrier classes, actual structure/key producers and native interaction ordering. Static only; no runtime, HP/source invention, production/Stage/L2/Phase6/7 change. Whole Twilight remains PARTIAL pending portal/control blocks, remaining events/ASM/compatibility/source closure and final assembly.',
      'vanishing_initial':'VanishingBlock default ACTIVEfalse, no VANISHED property. ReappearingBlock adds VANISHEDfalse; LockedVanishing adds LOCKEDtrue. Genuine useWithoutItem on visible/inactive block: bounded lock search true plays locked sound, false activates; returns sidedSuccess in both branches. Already active/vanished returnsPASS. Server neighborChanged starts visible/inactive powered block only when bounded lock search false. Native RightClickBlock and default-interaction admission remain, including protected Z structure gate. This is block interaction, not a damage-source hit.',
      'lock_search':'areBlocksLocked uses FIFO queue starting at position and a checked set, with at most512 queue POP iterations. On every popped position, exact LOCKED_VANISHING_BLOCK with LOCKEDtrue returns true. Then mark checked; only VanishingBlock instances expand six neighbors not already checked. Enqueued positions need not be vanishing blocks; duplicate queued positions are possible because membership is tested against checked, not queued. Thus512 is not a count of512 unique connected blocks or an unlimited component proof. No block-owner/player-key/advancement predicate inside search.',
      'activation':'Private activate reads actual state, accepts any VanishingBlock subclass visible/inactive, writes ACTIVEtrue, schedules that actual block at2+nextInt5 (2..6 ticks). It does NOT test areBlocksLocked or LOCKED. Visible active server tick: if VANISHED property exists, set ACTIVEfalse/VANISHEDtrue and schedule80; otherwise removeBlock(pos,false) with no drops. Then activate each of six neighbors. Propagation does not repeat initial network-lock check and can activate a LOCKEDtrue block reached after the initial bounded search or after changed state; this is the installed chain, not an authorized bypass implementation. State/write/remove returns ignored. No BreakEvent or canEntityDestroy test in this callback itself.',
      'reappearance':'Reappearing block at vanished/inactive scheduled tick after80: sound, ACTIVEtrue, schedule15. At next vanished/active tick: VANISHEDfalse/ACTIVEfalse, reappear sound. Nominal vanished interval95ticks after original disappearance, apart from native scheduling/chunk delays. Vanished shape is central6/16..10/16 outline but collision empty; visible state uses parent collision. Native active/vanished block states and scheduled ticks persist through normal chunk save; no custom BE/owner/timer NBT. Reappearing visible/inactive can start again. Reappearance does not explicitly hurt, relocate or push overlapping entities; subsequent native collision/inside-block handling remains separate.',
      'vanishing_defenses':'Ordinary Vanishing/Reappearing registered hardness10/resistance35, pistonBLOCK; Reappearing forceSolidOn/light4/requires correct tool, ordinary Vanishing light4 onlyACTIVE. UnbreakableVanishing reuses class/properties with hardness-1/resistance6000000/no loot. Vanishing getExplosionResistance returns6000 whenever !ACTIVE, otherwise parent value. Consequently inactive UnbreakableVanishing also reports6000 through this override, while active parent6000000 applies. Vanishing canEntityDestroy when !ACTIVE returns !areBlocksLocked; active delegates parent. These native entity-destruction/explosion predicates do not prevent the class own removal callback. No entity HP shield, fire/effect or projectile reflection.',
      'locked_defenses':'Locked variant registered hardness-1/resistance2000/pistonBLOCK. LOCKEDtrue explosion resistance6000000 regardlessACTIVE and canEntityDestroyfalse; unlocked delegates Vanishing, giving inactive6000 and active parent2000. Unlock does not alter registered mining hardness-1, so it is not a ordinary-mining unlock. Actual chain removal still follows inherited tick. LOCKED state is native saved block state, no specific key identity or owner stored.',
      'key_interaction':'LockedVanishingBlock.useItemOn requires stack nonempty, exact TOWER_KEY and LOCKEDtrue. Server body shrinks1 first, writes LOCKEDfalse, plays sound; ignores write success and returns sidedSuccess. No local instabuild/infinite-material exemption. Exact native ServerPlayerGameMode invokes blockstate.useItemOn before ItemStack.useOn; consumed block result returns immediately through ITEM_USED_ON_BLOCK criterion. Its creative ItemStack.useOn count restoration is later and does NOT refund this successful block callback. Thus native creative unlock also consumes one key. Wrong/empty key or already unlocked goes parent/default interaction path. Unlock does not call activate itself; normal subsequent interactions/neighbor redstone updates can start the chain. Existing protected structure RightClickBlock veto can prevent entry.',
      'key_source':'TOWER_KEY is ordinary fireResistant/uncommon Item, no custom item damage behavior. Native darktower_key chest loot has a separate unconditional one-roll pool containing one tower_key, in addition to other loot. DarkTowerMain.addChildren, when !placedKeys and generation depth<2, chooses up to4 distinct size9 same-generation-depth wing candidates without replacement, marks keyTowertrue, warns/stops if exhausted, and sets transient placedKeys even if fewer; that field is not serialized by the class. DarkTowerWing serializes keyTower; its native treasure-room method selects DARKTOWER_KEY when true and otherwise DARKTOWER_CACHE. This is a genuine loot producer, not a manually injected key. Existing protected kept_on_death tag handling also includes tower_key; reuse that mechanic without duplication. MuseumCurator artifact resource lists key but does not confer combat behavior.',
      'castle_initial':'All4 CastleDoor colors default ACTIVEfalse/VANISHEDfalse, where property name is vanish (different from VanishingBlock vanished). isBlockLocked is literalfalse in installed code. No native key, advancement or completed-boss requirement in this helper. useWithoutItem calls onActivation: vanished/active returnsFAIL; otherwise changeToActiveBlock and SUCCESS. Dead locked branch would PASS but is unreachable with this helper. neighborChanged calls activation when changed neighbor block is NOT CastleDoorBlock and current redstone powered; no explicit side guard in that body. Native outer interaction/progression gate still applies independently.',
      'castle_cycle':'changeToActiveBlock sets ACTIVEtrue for CastleDoor state and schedules actual block2+nextInt5. Visible/active tick writes VANISHEDtrue/ACTIVEfalse, schedules80, sounds/particles, then checks allsix neighbors. Any CastleDoor subclass/color visible/inactive and helper-unlocked is activated; no same-color restriction. Vanished/inactive tick invokes same2..6tick activation helper; vanished/active tick restores bothfalse. Nominal vanished interval82..86ticks after disappearance, not the ReappearingBlock95. Initial disappearance also waits2..6. Each state-write return ignored. CastleDoor schedule callbacks do not remove the block or consume resources.',
      'castle_geometry':'CastleDoor vanished collision empty and outline.375..625cube; visible parent collision. Occlusion shape is parent only when visible AND active, otherwiseempty, which does not imply empty collision. Registered hardness100/resistance100, requires correct tool, forceSolidOn, pistonBLOCK. Skip-render behavior connects allCastleDoor colors with equal vanished state. Sounds/ANNIHILATE particles are visual, not damage. Native saved states/scheduled ticks persist, no custom owner or HP. No explicit entity damage, effects, ignition, knockback, teleport, hurt-return dependence or entity displacement in these four classes.',
      'source_paths':'Caller evidence ties Vanishing/Reappearing/Locked terrain to actual Dark Tower generation and CastleDoor colors to actual Final Castle generation; registered blocks also admit ordinary native placement where an item exists. UNBREAKABLE_VANISHING_BLOCK is BLOCKS.register with no associated item-registration wrapper; do not invent a normal survival placement item. Actual repeated chain callbacks are delivery paths distinct from manual/redstone entry. Resource/tag/loot data are pinned to installed JAR, not assumed from tooltip.',
      'compatibility':'DIRECT_SOURCE_SPECIFIC: native key/type/state and actual Twilight structure producers; kept_on_death tag reuses protected native item-retention hook. MuseumCurator key listing is direct presentation metadata only. GENERIC_CONDITIONAL_PRESENT: exact loader RightClickBlock/UseBlock/UseItem and native criteria, block updates/collision/scheduling; protected progression gate can cancel actual interaction. NONE_PROVEN: no source-specific Tensura/L2/Curios combat mapping in these state-machine bodies. UNKNOWN: pack-wide callback alterations and actual runtime scheduling; static review does not certify compatibility.'
    }
    nxt='Continue remaining native portal creation/transport and control blocks (Builder/Antibuilder/cloud/snow as applicable), then remaining events/nested ASM/compatibility/source exclusions. All40 custom types closed. Finish R2f8 and final Twilight promotion before IceAndFire. Static only.'
    data=dict(slug='vanishing-doors',checkpoint_short='r2f8aa',checkpoint='R2f8aa-vanishing-doors-complete',decision='TWILIGHT_VANISHING_DOORS_SEMANTIC_REVIEW_COMPLETE',starting_sha=git('rev-parse','HEAD').strip(),previous_checkpoint='R2f8z-structure-gates-complete',previous_draft='partial-drafts/twilightforest-r2f8z-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=0,full_classes=FULL,limited_classes={W:['native barrier/loot producers and keyTower persistence'],M:['native source/key candidate selection and transient placedKeys guard'],'world_provider_census':['actual selected barrier producers; layout not a new damage mechanic']},registration_classes=['init/TFBlocks','init/TFItems','loot/TFLootTables'],closure_checklist=['full_four_classes','512_queue_pops_not_unique','real_manual_redstone_entry','propagation_no_lock_recheck','ordinary_permanent_removal','reappearing95statecycle','explosion_override_vs_properties','locked_native_key_cost','creative_block_callback_before_refund','realkeylootproducer','castle_lock_literalfalse','castle82to86statecycle','crosscolorpropagation','actual_collision_vs_outline','nativepersistence','noHPpayload','compat_attribution'],compatibility_scope=facts['compatibility'],current_scope='Prior Twilight plus Vanishing/Reappearing/Locked barriers, Tower Key genuine loot/use and Castle Door state machines. Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=40,new_used_profiles=0,reviewed_profiles_after=40,remaining_profiles=0,remaining_disposition='None:40 USED; global source/ASM/compatibility closure unfinished.'))
    def pkg(k,title,kind,keys,cs,nums,gates,rel,source,controls):
        eid='twilightforest:'+k;data['packages'].append(dict(id=eid,display_name=title,owner=k,primary_classification=kind,facts=keys,classes=cs,parameters=nums,gates=gates,relation=rel,primary_test_source=source,alternate_sources=controls));return eid
    vanish=pkg('vanishing_native_block_chain','Native Vanishing Block removal chain','CUSTOM_CONTROL',['vanishing_initial','lock_search','activation','vanishing_defenses','source_paths'],[V],{'queue_pop_limit':512,'activation_delay_min':2,'activation_delay_max':6,'inactive_blast_resistance':6000},['genuineinteraction/redstone','visibleinactive','boundedlocksearch','actualscheduledtick'],'Custom terrain removal and propagation over native block callbacks.','Actual Dark Tower vanishing doorway',['redstone','lockedneighbor','boundedsearch','unbreakablevariant','propagation'])
    appear=pkg('reappearing_native_block_cycle','Native Reappearing Block collision cycle','CUSTOM_CONTROL',['vanishing_initial','activation','reappearance','vanishing_defenses'],[V,R],{'vanished_first_delay':80,'vanished_second_delay':15,'nominal_vanished_interval':95},['actualVanishedproperty','scheduledtick','nativecollision'],'Custom saved block-state cycle with ordinary native collision, no HP request.','Actual native Reappearing Block activation',['manual','redstone','chain','reload','occupiedrestoration'])
    key=pkg('tower_key_locked_barrier','Tower Key native locked-barrier gate','BINARY_MECHANIC',['lock_search','activation','locked_defenses','key_interaction','key_source'],[L,V,W,M],{'cost':1,'max_key_wing_choices':4,'locked_blast_resistance':6000000},['nonemptynativekey','LOCKEDtrue','actualblockuse','servercost'],'Custom key/state admission and actual loot resource; native item interaction.','Genuine Dark Tower key-loot unlock',['creativecost','alreadyunlocked','wrongkey','progressionveto','save/load'])
    castle=pkg('castle_door_native_cycle','Castle Door native collision cycle','CUSTOM_CONTROL',['castle_initial','castle_cycle','castle_geometry','source_paths'],[C],{'colors':4,'activation_delay_min':2,'activation_delay_max':6,'wait':80,'nominal_vanished_min':82,'nominal_vanished_max':86},['visibleinactive','realinteraction/redstone/chain','scheduledtick'],'Custom block-state/collision cycle; installed lock helper alwaysfalse.','Genuine Final Castle door activation',['crosscolor','redstone','vanishedinteraction','reload','occupiedrestoration'])
    def path(k,title,keys,ids,cs,labels,controls):data['paths'].append(dict(id='twilightforest:vanishing_doors_path:'+k,source=title,facts=keys,effect_ids=ids,classes=cs,labels=labels,setup=title+' through actual native block/structure/item delivery; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('vanish_manual','Native visible/inactive Vanishing Block use',['vanishing_initial'],[vanish],[V],['ENVIRONMENT'],['sidedSuccess','lockedfeedback','defaultinteraction']),
      ('vanish_redstone','Native powered Vanishing neighbor callback',['vanishing_initial'],[vanish],[V],['ENVIRONMENT'],['serverside','visibleinactive','locksearch']),
      ('lock_search','Actual bounded Vanishing network lock lookup',['lock_search'],[vanish,key],[V],['ENVIRONMENT'],['queue512','duplicatequeue','boundarynonblocks','exactlockedtype']),
      ('vanish_chain','Native six-neighbor propagation after removal',['activation'],[vanish],[V],['ENVIRONMENT'],['2to6delay','nolockrecheck','changedlock','boundedsearchlimit']),
      ('vanish_remove','Actual Vanishing permanent terrain removal',['activation'],[vanish],[V],['ENVIRONMENT'],['nodrops','removefalse','noBreakEvent','noHP']),
      ('vanish_blast','Vanishing inactive/active explosion predicates',['vanishing_defenses'],[vanish],[V],['EXPLOSION','ENVIRONMENT'],['6000inactive','35active','nativeexplosionadmission']),
      ('unbreakable','Actual Unbreakable Vanishing variant',['vanishing_defenses','activation'],[vanish],[V],['ENVIRONMENT'],['hardnessminus1','6000inactive','6000000active','nativechainstillremoves']),
      ('entity_destroy','Native Vanishing entity-destruction predicate',['vanishing_defenses','locked_defenses'],[vanish,key],[V,L],['ENVIRONMENT'],['activeparent','inactivelocksearch','LOCKEDtrue']),
      ('appear_entry','Genuine Reappearing manual/redstone entry',['vanishing_initial','activation'],[appear],[V,R],['ENVIRONMENT'],['actualproperty','initial2to6delay']),
      ('appear_chain','Reappearing chain and95tick vanished state',['activation','reappearance'],[appear],[V,R],['ENVIRONMENT'],['80then15','sixneighbors','reusable']),
      ('appear_collision','Reappearing outline versus collision',['reappearance'],[appear],[V,R],['ENVIRONMENT'],['emptycollision','centraloutline','occupiedrestore','nocustomhurt']),
      ('appear_save','Native Reappearing state and scheduled ticks',['reappearance'],[appear],[V,R],['ENVIRONMENT'],['chunkreload','activevanished','delayedtick']),
      ('key_loot','Actual Dark Tower key-wing chest loot',['key_source'],[key],[W,M],['OTHER'],['size9','depthmatch','withoutreplacement','fewerthan4','onekeypool']),
      ('key_unlock','Native Tower Key block callback',['key_interaction','locked_defenses'],[key],[L],['ACTIVE_ITEM'],['shrinkbeforewrite','unlocksoneblock','doesnotactivate','stillhardnessminus1']),
      ('key_creative','Creative native key use cost',['key_interaction'],[key],[L],['ACTIVE_ITEM'],['blockreturnbeforeItemuse','oneconsumed','nativecriterion']),
      ('key_controls','Wrong key/already unlocked/event-veto controls',['key_interaction'],[key],[L],['ACTIVE_ITEM'],['parentfallback','sneakUseBlock','progressionveto']),
      ('key_state','Saved key-wing and unlocked block state',['key_source','locked_defenses'],[key],[L,W,M],['OTHER','ENVIRONMENT'],['keyTowerNBT','placedKeysnotsaved','keptondeathreuse']),
      ('castle_manual','Native CastleDoor activation with no installed lock',['castle_initial'],[castle],[C],['ENVIRONMENT'],['literalfalse','SUCCESS','activevanishedFAIL']),
      ('castle_redstone','Native CastleDoor powered neighbor entry',['castle_initial'],[castle],[C],['ENVIRONMENT'],['neighborNOTCastleDoor','normaloutercallback']),
      ('castle_chain','Native CastleDoor cross-color propagation',['castle_cycle'],[castle],[C],['ENVIRONMENT'],['allsix','anycolor','2to6delay']),
      ('castle_cycle','Native CastleDoor82to86tick vanished cycle',['castle_cycle'],[castle],[C],['ENVIRONMENT'],['80then2to6','statewritereturn','noitemcost']),
      ('castle_collision','CastleDoor collision/outline/occlusion distinction',['castle_geometry'],[castle],[C],['ENVIRONMENT'],['visiblecollision','vanishedempty','visualnotdamage']),
      ('castle_save','CastleDoor native state/tick persistence',['castle_cycle','castle_geometry'],[castle],[C],['ENVIRONMENT'],['reload','occupiedrestoration','nativecollision']),
      ('worldgen','Actual Dark Tower and Final Castle barrier placement',['source_paths','key_source'],[vanish,appear,key,castle],[W,M],['ENVIRONMENT'],['selectedproducercensus','genuineplacement','noinventedunbreakableitem'])
    ]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','twilightforest-vanishing-doors-caller-scan.json','twilightforest-vanishing-doors-source-providers.json','semantic-sections/twilightforest-structure-gates.json']
    data['exclusions']=['Terrain disappearance is not HP damage, armor bypass or source identity. No new DamageType.','Castle Door is not a subclass of Vanishing Block; no inferred shared lock or95tick timing.','Tower Key kept-on-death retention and protected progression event gate reused; no duplicate mechanic.','Particles/sounds/MuseumCurator listings are presentation only. Remaining portal/control/events/ASM work is unfinished, not REVIEW_REQUIRED.']
    data['fixture_groups']=['Real manual/redstone/chain Vanishing entries with bounded lock search, subclass and resistance controls.','Reappearing95tick cycle with native scheduled ticks/collision/reload controls.','Native key loot and actual block callback including creative cost, wrong key, event veto and state persistence.','Four CastleDoor colors through genuine manual/redstone/chain with82..86tick vanished interval and native collision/save controls.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-vanishing-doors.json',data);assemble('twilightforest-vanishing-doors.json')
if __name__=='__main__':build()
