from catalog_common import *
from iceandfire_combat_common import save_section
START='a5cda1cfdbc1feb0165c3693cc75a504a3653b90'
CP='R2g8c-avian-mounts-complete';STEM='iceandfire-r2g8c-avian-mounts'
NEXT='R2g8d: Dread creature/summon/skull combat. Then remaining equipment (including Dragon Flute delivery), chain/status/resource callbacks and whole-JAR custom DamageType/combat closure; dedup/promote Ice & Fire and continue next target if usage healthy.'
FACTS={
 'bird_hits':'Stymphalian doHurtTarget starts Peck only if NO_ANIMATION,returnstrue. Server aiStep live actualtarget,Pecktick7,distSquared<1.5 requests intATTACK_DAMAGE mob_attack direct=causing=Bird. Native nearest goal uses sight,excludes sameclass/statue,victor,targets eligible Player/Villager/Golem and configAnimals. Peaceful removes Bird; creative/victor target cleared. RangeSquared>3 and<225 starts Shoot outsidePeck/Shoot; whileflying ticks7and14 with collider directpath launches FOUR owned Feather each (8peranimation),speed1.6,inaccuracy14-difficultyId*4. No extra Stage per volley count.',
 'feather_and_bundle':'StymphalianFeather owned constructor uses configfeatherAttackDamage as baseDamage; AbstractArrow handles native velocity/crit/source/impact/PVP/damage. If shooterBird AND victimBird, onHitEntity suppresses parent entirely; Player bundle feather can damage Bird then decrements arrowCount after parent independent of hurt success. Tick>100discards. FeatherBundle use cooldown15,server8ownedfeathers at yaw+45successively/horizontal pitch0,speed1.5,inaccuracy1,consume1noncreative,returnsPASS. Pickup/drop cosmetics do not add damage. Bird and Player sources share arrow direct=projectile/causer=owner, with distinct friendly gate.',
 'bird_flock_control':'Server die with Living causing entity assigns VictorUUID to deadBird and all current flock members. getVictor resolves ONLY level.getPlayerByUUID, so nonPlayer killer UUID does not resolve as active victor. Saved VictorUUID blocks targetsetter/nearest target and aiStep clears matching Player target. Leader assignment propagates target only to idle nonleader members; no damage amount modifier. Flee goal requires resolved victor and first eligible visible nonallied Player in boxinflate(10,3,10) equalvictor; native selection/order and inverted-looking continuation distanceSquared<2 retained, not guaranteed full flee duration. Flock and victor are AI control, no Stage value.',
 'avian_arrows':'StymphalianArrow baseDamage3.5,ordinary AbstractArrow hit,noGravitytrue; when horizontal speed<.1 addsY-.01 aftersuper. AmphithereArrow base2.5,ordinary accepted-Living-hit postcallback excluding Enderman: target hasImpulse, halves horizontal velocity then adds normalized projectile horizontal direction*1.4,Y+.6. No zero-horizontal guard and no Living knockback/resistance callback; rejected hurt does not reach gust. Cosmetic explosion particles are not Explosion damage. Both ArrowItems override createArrow only; protected IafRecipes+ArrowItem.asProjectile prove registered dispenser creates vanilla Arrow, losing these special entity behaviors. Legitimate weapon factory retains native customArrow/enchantment hooks.',
 'amphithere_body':'doHurtTarget while no Bite/Tail/Wing and no controller chooses Bite half,else Tail ifnotflying/randombit orWing; returns true when starts, no direct hurt. tick actualtarget: Bite tick7 distSquared<10 normal knockback.6 BEFORE intATTACK_DAMAGE hurt; Wing ticks6..21 distSquared<25 requests intATTACK_DAMAGE/2 everytick; Tail tick7 distSquared<10 requests intATTACK_DAMAGE. All source mob_attack direct=causing=Amphithere and no newframeLOS. Wing marks target impulse but resistance check uses ATTACKER knockbackResistance and displacement writes ATTACKER motion; Tail likewise moves ATTACKER, no target displacement beyond impulseflag. Swapped dx/dz vector preserved. No hurt-success control gate.',
 'amphithere_rider_defense':'Rider controlbit2 with actual owner/tame Player controller (not currenttarget) uses protected rider-ray2.5 and requests intattack EVERYupdate,sourceAmphithere notPlayer,noanimationframegate. Wild adult empty-hand native mount allows riding; untamed rider random1/15 NO_ANIMATION starts BiteRider; serverpositionRider tick6 whileuntame requests mob_attack1 onpassenger. RidingTime increments with Player passenger whilewild,resetswhenabsent; after>configtameTime tames that Player,clears matching target; savedcounter. hurt BEFOREparent marks isFallen for wild flying airborne IS_PROJECTILE server even if later HP rejected. Tame owner causer sharing vehicle returnsfalse. Fallen sets flightBehaviorNONE,uncontrolled flight addsY-.3 and fallen adds-.2; landing stopsflight,cooldown12000wild/50tame. EmptycheckFallDamage prevents ordinary fall route. Native onHearFlute(tame,airborne) also marksfallen; exact Flute item entry retained for equipment closure.',
 'hippogryph_body':'doHurtTarget starts randomBite/Scratch and returnsfalse when new, true if already either; aiStep tick6,targetdistSquared<8 requests intATTACK_DAMAGE(base5),source mob_attackHippogryph. Scratch independently adds(-.5/sqrt(.5),1,-.5/sqrt(.5)),halveshorizontal,thenonGroundaddsY.3; fixed world-direction motion, not away-from-attacker knockback. Rider controlbit2 actualtameowner Player,protected ray3,choosesanimationifneeded,requests intattack at animationticks10..12; own natural target may also receive tick6path. hurt rejects controller-caused whilevehicle; emptycheckFallDamage suppresses natural fall. Keep owner/passenger target/command/mount admission, no synthetic rider.',
 'mount_healing':'Hippogryph/Hippocampus server aiStep random1/900,deathTime0 heal1. Hippogryph owner interaction FOOD+MEAT+injured heal5,noncreativeconsume; droppedTAME_HIPPOGRYPH AI movable/chance1/20/liveitem/native reach consumes1,feedings++,heal4 even before taming. Afterfeedings>3 and (>7 orrandom1/3),wild and itemownerPlayer =>tame,clearTarget,sit; independenthealreturn. Amphithere handHEAL_AMPITHERE+injured heal5,noncreativeconsume (BREEDtag branch has priority); droppedtaggeditem movable/chance1/20/distanceSquared<1 consumes1 thenheal5,no injured/owner gate. Hippocampus hand HEAL_HIPPOCAMPUS serverheal5 evenfullHP,consume1noncreative; validbreed branchprecedes. All real heal calls use LivingHealEvent/positiveHP/maxclamp; feeding/taming costs do not depend on accepted heal.',
 'hippocampus_support':'No custom attack damage callback found. Everytick%20 actualcontrollingpassenger gets WaterBreathing30ticks amp0,ambient/hiddenparticles; not conditioned on water. Controller firstpassenger Mob directly,or firstPlayer if saddled. Native Player mount interaction still requires owner/saddle/adult/notpassenger. Buff effect admission/cures remain and lingers after dismount; no Stage on duration or immunity. Ordinary ride/swim/storage excluded.',
 'macuahuitl_dagger':'AmphithereMacuahuitl.hurtEnemy after legitimate item hit sets targetimpulse and motion=(halfX+attackerlookX*.6,.8,halfZ+lookZ*.6), thenparent; normal Player.attack item callback gated by accepted original damage, no new HP request. Native mob attacks do not universally call this item callback; use native Player item route,not hypothetical proc. StymphalianDagger override simply delegates SwordItem,ordinary damage/speed only. No special bleed/armor bypass inferred from tooltip. Standard melee Stage once at native attack amount.',
 'integration':'Native mob_attack/arrow,owner requirements,normal damage/effect/heal admission and installed Tensura/L2 processing preserved. Numeric attacks once at final hurt amount; no second projectile baseDamage/attribute/volley multiplier. Real heal once at healrequest. Direct motion,fallen state,victor,taming and WaterBreathing remain native. No SHP subtraction/custom damage sources. Flute,eggs and unrelated Dread/equipment remain explicitly next work.',
 'exclusions':'Flight navigation/path details, colors/armor visuals, flute acquisition, pet commands/home/storage, breeding/egg acquisition and feather drops excluded. Their combat-specific callbacks above are retained. No lore-based special effects or runtime completion claims.'
}
def save():
    names=['bird_peck','bird_feather_volley','player_feather_bundle','bird_victor_flock','stymph_arrow_weapon','stymph_arrow_dispenser','amphi_arrow_weapon','amphi_arrow_dispenser','amphi_bite','amphi_wing','amphi_tail','amphi_rider','amphi_bite_rider','amphi_fallen','hippogryph_bite','hippogryph_scratch','hippogryph_rider','mount_passive_heal','mount_hand_heal','mount_dropped_heal','hippocampus_rider_buff','macuahuitl_melee','dagger_melee']
    paths=[dict(id='iaf:avian-mounts:'+n,labels=['PROJECTILE' if any(s in n for s in ['arrow','feather']) else 'OTHER'],native_path=n+'; exact delivery/admission/source in facts',runtime_variants=['real native eligibility/hurt/effect/heal rejection','rider/target/delivery distinctions']) for n in names];ids={n:p['id'] for n,p in zip(names,paths)}
    def m(id,name,cl,cat,point,why,keys):return dict(id='iaf:'+id,name=name,primary_classification=cl,tno_categories=cat,stage_scaling_needed=point is not None,single_scaling_point=point,stage_reason=why,delivery_paths=[ids[k] for k in keys])
    packages=[m('avian_mount_hits','Avian and mount native HP attacks','VANILLA_LIKE_EXTENDED',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],'Once at native hurt amount in Bird/Hippogryph aiStep or Amphithere tick/positionRider, rider tick, ordinary Player sword attack.','Preserve source and each animation request, no attribute/weapon double scaling.',['bird_peck','amphi_bite','amphi_wing','amphi_tail','amphi_rider','amphi_bite_rider','hippogryph_bite','hippogryph_scratch','hippogryph_rider','macuahuitl_melee','dagger_melee']),m('avian_projectiles','Feather/avian-arrow HP damage','VANILLA_LIKE_EXTENDED',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],'Once at inherited AbstractArrow final hurt amount after native velocity/crit/enchantment formula.','No projectile-baseDamage or volley second multiplier.',['bird_feather_volley','player_feather_bundle','stymph_arrow_weapon','stymph_arrow_dispenser','amphi_arrow_weapon','amphi_arrow_dispenser']),m('avian_control','Native gust/scratch/attack motion','CUSTOM_CONTROL',['COMPOSITE','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Keep actual actor/target motion and native hurt-gated arrow/item versus independent creature control.',['amphi_arrow_weapon','amphi_bite','amphi_wing','amphi_tail','hippogryph_scratch','macuahuitl_melee']),m('avian_ai_defense','Victor, taming, rider protection and forced landing','BINARY_MECHANIC',['COMPOSITE','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Native allegiance/control/immunity state, not numeric Stage amount.',['bird_victor_flock','amphi_fallen','amphi_bite_rider','amphi_rider','hippogryph_rider','mount_dropped_heal']),m('mount_healing','Mount native healing','VANILLA_DIRECT',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],'Once at native heal(1/4/5) request through LivingHealEvent, retain native food/random/HP gates.','No multiplier on feeding/taming count.',['mount_passive_heal','mount_hand_heal','mount_dropped_heal']),m('hippocampus_breathing','Hippocampus rider WaterBreathing','VANILLA_DIRECT',['VANILLA_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Native breathing status, no damage/Stage numeric value.',['hippocampus_rider_buff'])]
    d=dict(schema='tno.external_effects.iaf_avian_mounts.v1',checkpoint=CP,previous_checkpoint='R2g8b-hydra-serpent-complete',starting_sha=START,status='AVIAN_MOUNTS_COMPLETE',scope='Stymphalian/Amphithere, related weapons and combat-special Hippogryph/Hippocampus reviewed; Dread/equipment closure remains.',summary='Avian volleys and source gates, real gust actor/target, rider damage/defenses, native mount healing and WaterBreathing reviewed; utility excluded.',facts=FACTS,mechanic_packages=packages,delivery_paths=paths,unexecuted_future_fixtures=['Bird_Peck_and_two4feather_volley_LOS','Bird_vs_Player_feather_friendly_gate','Bundle8arrow_native_PVP_damage_identity','Victor_Player_vs_nonPlayer_flock_retaliation','Avian_ammo_weapon_vs_dispenser_class','AmphiArrow_accepted_hurt_gust_zero_horizontal','Amphi_bite_knockback_before_hurt','Amphi_wing16requests_attacker_resistance_selfmotion','Amphi_tail_selfmotion_not_target','Amphi_rider_everytick_source_vs_bite_rider1','Amphi_projectile_HP_rejection_still_fallen','Hippogryph_AI6_vs_rider10to12_events','Hippogryph_scratch_fixed_negativeXZ_hurtfalse','Native_controller_friendly_veto','Hand_vs_drop_heal_acceptance_consumption_taming','Hippocampus_Mob_vs_saddledPlayer_breathing_linger','Macuahuitl_Player_posthit_gust_no_extra_damage'],remaining_subsection_native_ambiguities=[],review_required=[],exact_next_task=NEXT,references=['native-evidence/iceandfire-avian-mounts.json','iceandfire-avian-mounts-census.json','reference-evidence/iceandfire-hydra-serpent-244.json','native-evidence/iceandfire-hydra-serpent.json','reference-evidence/iceandfire-dragon-combat-244.json','native-evidence/iceandfire-dragon-combat.json','reference-evidence/iceandfire-ghost-troll-244.json','native-evidence/iceandfire-foundation.json','iceandfire-frozen-config-snapshot.json'])
    save_section(d,STEM,'R2g8c — Avian and mount combat')
if __name__=='__main__':save()
