from catalog_common import *
from iceandfire_combat_common import save_section
START='4d309a53ae19fa1bf98e76b8c3c26d48a5e84584'
CP='R2g8d-dread-complete';STEM='iceandfire-r2g8d-dread'
NEXT='R2g9: remaining special equipment, chain/status/resource and Pixie callbacks; then whole-JAR combat/source closure, dedup/promote Ice & Fire, and continue next target if usage healthy.'
FACTS={
 'body_damage':'Ghoul aiStep requires actual target, distance<4 and current LOS: Slash ticks9 and19 each request float ATTACK_DAMAGE (base5) with mob_attack direct=causing=Ghoul, then knockback.25 independent of hurt success. Beast and Scuttler use the same range/LOS gate with Bite tick6, bases4 and7 respectively, then independent knockback.25. doHurtTarget only starts an animation and returns true, not proof of HP damage. Thrall and Knight inherit ordinary Mob.doHurtTarget (base attribute2 plus actual equipment/enchantments); unstaffed Lich uses the same melee route (base1). Keep native damage admission, armor, Resistance and L2 processing. Scale once at final hurt amount, never both attribute and event. Scream/spawn animations add no special damage or invulnerability.',
 'lich_summon':'Mainhand exact LICH_STAFF selects DreadLichAIStrifeGoal; otherwise ordinary melee. Strife requires target/staff and calls performRangedAttack on every tick with sensing LOS. Its squared15 range controls movement, not a hard delivery range; attackCooldown field is assigned100 but unused in tick. Entity fireCooldown/minionCooldown provide actual100-tick cooldowns, decrement in aiStep, not saved. With minionCount<5 and minionCooldown0, summon takes precedence over skull that invocation: Thrall chance>0.5, Ghoul>0.35, Beast>0.15, otherwise Scuttler. Summon is immediate, not animation-frame gated; uses target, nearby native placement/finalizeSpawn, CommanderUUID=Lich and server addFreshEntity. It increments count and cooldown regardless of addFreshEntity success. Summon count/cooldown/placement are native binary/resource admission, not Stage quantities.',
 'commander_resource':'CommanderUUID and Lich MinionCount persist. Base DreadMob resolves Player UUID first, otherwise loaded LivingEntity in same server dimension. Server aiStep copies a living Lich target when resolved. DreadMob.remove decrements a resolved Lich counter on any first removal reason, not only death, with no clamp. Beast and Scuttler override getCommander to return null: their stored commander never resolves, so no base target-follow or removal decrement. Initial summon setTarget still works. Lich also returns null. Thrall/Ghoul/Knight use base resolution. DreadHorse extends SkeletonHorse separately, resolves Player only and has no DreadMob decrement. Counts can remain stale or change on unloading; no automatic reconciliation is present. Test natural summon/kill/unload/reload without repairing counters.',
 'lich_skull_delivery':'When no summon occurs and fireCooldown0, Lich constructs owned DreadLichSkull(baseDamage6), shoot speed0, addFreshEntity, cooldown100. The owned skull constructor calls AbstractArrow(EntityType,Level), setOwner and setBaseDamage only. This constructor chain leaves Entity at (0,0,0); setOwner does not position it. Lich never sets projectile position. Therefore a legitimate Lich launch must first be tested for spawn location/delivery, not assumed to hit near its caster. Player LichStaff.use on server explicitly sets position to (playerX,playerY+1,playerZ), adds projectile, then shoots speed1/inaccuracy1 along noisy look. An earlier shoot(speed7) is overwritten; staff costs durability1 and cooldown4. No ammo/charge threshold. Preserve the native divergence; no relocation fix or synthetic hit is authorized.',
 'skull_homing':'Skull tick before inherited arrow tick: if horizontal speed<.1 OR collision/inGround, and tickCount>5, remove(DISCARDED), without immediate return. Mob owner with target adds (targetPosition-skullPosition)*.015 to velocity; no local LOS/alive/range gate. Player owner first uses player.getKillCredit (not necessarily attacked target); if absent/dead, searches live Enemy in asymmetric projectile box expanded10, chooses nearest to Player, not nearest projectile, with no LOS/alliance filter at acquisition. Player live target steers each axis 10% toward sign(delta)*.5. NoGravity=true and isInWater=false; inherited collision/PVP/projectile-impact handling still applies. Stage belongs at final native arrow hurt amount, not homing speed or baseDamage.',
 'skull_damage':'onHitEntity suppresses parent only when victim.isAlliedTo(owner); null owner is allowed. Ordinary AbstractArrow creates minecraft:arrow direct=skull, causing=owner (or projectile itself when no owner), amount ceil(clamp(speed*baseDamage)), plus native critical handling if applicable. These launchers do not provide firedFromWeapon/enchantment state. Normal hurt false prevents post-hurt shield wear; successful Living hit reaches doPostHurtEffects (native Enderman early return retained). Non-owner Player actively using a ShieldItem and baseDamage>=3 receives extra durability wear1+floor(baseDamage)=7 at default6, independent of actual HP lost. This does not bypass blocking or force hurt true, and is separate from HP scaling. No custom Dread damage type, freeze, soul scatter, direct SHP drain or direct HP subtraction.',
 'necromancy_unreachable':'DreadMob.onKillEntity(LivingEntity):void is a legacy standalone method. Whole installed Iaf726-class and compat24-class instruction census finds zero calls to it; necromancyEntity is called only from it. Exact installed LivingEntity.die invokes killer.killedEntity(ServerLevel,LivingEntity):boolean, not onKillEntity; Dread classes do not override that callback. Thus native death-to-minion conversion is not a proven reachable delivery in this version. Do not promote it as an active path or manually invoke it in tests. Dormant helper would exclude Dragon, map arthropod->Scuttler, Zombie/IHumanoid->Ghoul, undead/skeleton/Player->Thrall, horse->Horse, otherAnimal->Beast, increment commander count and assign DreadMob commander. This is sufficient to explain the gap; no conversion implementation authorized.',
 'defenses_targets':'Dread alliance treats any IDreadMob as allied, plus inherited teams. NonDread target goal preserves parent targeting, excludes IDreadMob and DragonUtils.isAlive false; hostile predicate excludes creative/peaceful Player and model-dead Dragon. Scuttler explicitly rejects Poison then calls normal canBeAffected. Installed entity tags list all seven Dread creatures as freeze_immune_entity_types (powder-snow mechanic, not Iaf Frozen); all except Scuttler are undead, Scuttler arthropod. Native healing/harming/Regeneration/Poison tag behavior and enchantment eligibility therefore matter; do not equate undead with blanket magic immunity. Registry fireImmune is false for Dread types. No custom broad hurt immunity exists in reviewed classes.',
 'knight_mount':'DreadKnight has native horse-mount goal: when not passenger, samples unoccupied AbstractHorse within inflate(16,7,16) every4 game ticks, chooses first, approaches and at squared distance<4 sets horse tamed then startRiding(non-force). Native mount hook may reject; tamed flag is already written. No owner check, no special mounted damage packet/source or extra horse attack. Retain a mounted normal-melee fixture; ordinary horse movement/storage excluded.',
 'queen_exclusion':'DreadQueenEntity class exists with ordinary melee attributes/equipment and boss bar, but IafEntities contains no Queen entity registration or attribute registration. Whole Iaf/compat census finds no external constructor/launch invocation; other references are instanceof rider checks and rendering. No legitimate native Queen boss delivery established. DreadQueenStaffItem is a plain Item with no active combat callback; Queen/Dread swords are standard equipment, handled by ordinary melee. Do not force-spawn an unregistered class or invent staff summons.',
 'direct_compat':'Pinned tensura_iaf data declares cold_resistance and native spiritual-health/magicule baselines for each Dread creature; all are cold_source and no_charisma entity-tag members. Lich additionally belongs to full_gravity_control, no_fear, no_mind_control and no_possession. These are data declarations, not measured runtime immunity or a new damage source; preserve Tensura consumers and pack/tag composition for later tests. No Dread-specific compat mixin restores legacy kill conversion, skull positioning or Queen registration. Entity-existence and gear progression values are not multiplied by this research.',
 'exclusions':'Dread blocks, portal/spawner acquisition/worldgen, loot, texture variants, scream visuals and staff repair are excluded briefly. Registered creature combat and all reachable native skull/summon paths above remain in future runtime coverage. No runtime, Stage, L2 or production work performed.'
}

def save():
    names=['ghoul_slash','beast_bite','scuttler_bite','thrall_melee','knight_melee','lich_unstaffed_melee','lich_summon','summon_target_follow','minion_removal_reload','lich_skull_launch','player_staff_skull','skull_mob_homing','skull_player_homing','skull_impact','skull_shield_wear','dread_defense_admission','knight_mount']
    paths=[dict(id='iaf:dread:'+n,labels=['PROJECTILE' if 'skull' in n else 'SUMMONED_ATTACK' if 'summon' in n else 'OTHER'],native_path=n+'; exact caller, amount and admission in facts',runtime_variants=['native delivery/owner and normal hurt acceptance','eligibility and stated version-specific delivery limits']) for n in names];ids={n:p['id'] for n,p in zip(names,paths)}
    def m(id,name,cl,cat,point,why,keys):return dict(id='iaf:'+id,name=name,primary_classification=cl,tno_categories=cat,stage_scaling_needed=point is not None,single_scaling_point=point,stage_reason=why,delivery_paths=[ids[k] for k in keys])
    packages=[m('dread_melee','Dread native melee HP damage','VANILLA_LIKE_EXTENDED',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],'Once at final native hurt amount in animated aiStep or inherited Mob.doHurtTarget.','Do not multiply attribute/equipment and hurt event twice.',names[:6]),m('dread_motion','Dread animated attack knockback','VANILLA_DIRECT',['VANILLA_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Fixed native knockback independent of hurt result; retain resistance hook.',names[:3]),m('dread_summon','Lich summon and commander resource','CUSTOM_RESOURCE',['COMPOSITE','CUSTOM_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Preserve count/cooldown and actual commander resolution, no Stage multiplier.',['lich_summon','summon_target_follow','minion_removal_reload']),m('dread_skull','Dread skull HP damage and homing','VANILLA_LIKE_EXTENDED',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],'Once at inherited AbstractArrow final hurt amount after speed/base/crit calculation.','Native Lich launch position gap is an availability prerequisite, not permission to fix it.',['lich_skull_launch','player_staff_skull','skull_mob_homing','skull_player_homing','skull_impact']),m('dread_shield','Dread skull extra shield wear','VANILLA_LIKE_EXTENDED',['VANILLA_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Durability resource uses baseDamage, not HP amount; keep native7 default.',['skull_shield_wear']),m('dread_admission','Dread tags, allegiance, immunity and mounting','BINARY_MECHANIC',['BINARY','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Preserve native and Tensura admission. No Stage on tags, owner, mount or immunity.',['dread_defense_admission','knight_mount'])]
    d=dict(schema='tno.external_effects.iaf_dread.v1',checkpoint=CP,previous_checkpoint='R2g8c-avian-mounts-complete',starting_sha=START,status='DREAD_COMPLETE',scope='Dread combat and native availability reviewed; remaining equipment and whole-mod closure pending.',summary='Dread melee, summons, skull sources and defenses reviewed. Native Lich skull origin, unresolved Beast/Scuttler commanders, unreachable legacy necromancy and unregistered Queen are retained as availability limits.',facts=FACTS,mechanic_packages=packages,delivery_paths=paths,unexecuted_future_fixtures=['Ghoul_two_slashes_hurtfalse_knockback','Beast_Scuttler_bite_LOS_poison_admission','Thrall_Knight_equipped_native_Mob_attack','Lich_staff_vs_unstaffed_melee','Lich_summon_precedence_count5_join_veto','Beast_Scuttler_commander_null_target_and_counter','Minion_unload_reload_removal_counter','Lich_skull_native_origin_vs_Player_staff_position','Skull_Mob_vs_Player_getKillCredit_homing','Skull_alliance_PVP_impact_cancellation','Skull_speed_damage_hurtfalse_vs_shield_wear7','Dread_undead_arthropod_freeze_tags_vs_IafFrozen','Dread_Tensura_cold_source_and_control_tags','Knight_mount_hook_reject_after_tamed','Native_kill_has_no_legacy_necromancy_observation_only'],remaining_subsection_native_ambiguities=[],review_required=[],unavailable_native_paths=['legacy_onKillEntity_conversion','unregistered_DreadQueen_boss'],exact_next_task=NEXT,references=['native-evidence/iceandfire-dread.json','iceandfire-dread-census.json','reference-evidence/iceandfire-dread-244.json','reference-evidence/iceandfire-ghost-troll-244.json','reference-evidence/iceandfire-dragon-combat-244.json','native-evidence/iceandfire-foundation.json','iceandfire-frozen-config-snapshot.json'])
    save_section(d,STEM,'R2g8d — Dread combat and summons')
if __name__=='__main__':save()
