"""Reviewed native map information, Ore Meter, locator and a counted historical erratum."""
from catalog_common import *
from collect_twilight_maps_information import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed TF4.8.3345, raw Minecraft1.21.1 and exact NeoForge21.1.244 bytecode. Maps and OreMeter provide information; no HP/status/damage delivery or boss progression mutation. Prior goggles callbacks are reused. Two more registered nested ASM transformers reviewed, including an explicit correction to R2f8q. Static research only, no runtime/L2/Stage/production/Phase6/7 changes. Twilight remains PARTIAL;31/40 custom types reviewed,9 ordinary unfinished types.',
      'registration':'TFItems registers filled_magic_map as MagicMapItem; filled_maze_map/filled_ore_map as MazeMapItem(false/true), matching empty variants, and ore_meter stack1/uncommon without durability. Native recipes use8 c:paper plus matching focus; magic focus is raven feather+torchberries+glowstone dust; ore_map is EMPTY maze_map plus diamond/gold/iron storage blocks. This does not convert an already filled Maze map or preserve its ID. Actual registered OreMeter is a legitimate future item fixture; no survival crafting recipe is inferred from its name. All matching installed resources pinned.',
      'empty_magic':'EmptyMagicMapItem.use clientPASS; server requires dimension TYPE holder tag twilightforest:allows_magic_map_charting, installed value twilightforest:twilight_forest_type. Rejection displays message/FAIL, no consumption/map. Success consumes1 through native ItemStack.consume (infinite-materials exemption), awards stat/sound, creates filled map at floor playerXZ, scale4/trackingtrue/unlimitedfalse. Replaces exhausted held stack; otherwise inventory add copy then drop if insertion fails. No damage, status or use cooldown.',
      'magic_identity':'MagicMapItem.createMapData allocates native free MapId but stores under magicmap_<id>. Center per axis round((coord-1024)/2048)*2048+1024, independent of supplied scale. getCustomMapData missing-data fallback SERVER ONLY uses shared spawn, scale3/trackingfalse, newID; this fallback does not recheck empty-map dimension-type tag. TFMagicMapData server storage is server.overworld().dataStorage, with dimension saved in each map; client separate static name->map cache. Native colors/banner/frame data retained on save/load; custom showOnItemFrame decorations persisted with IDs/counts, conquered string list persisted. No source attacker/recipient ownership.',
      'magic_update':'Exact244 MapItem.getSavedData(ItemStack,Level) dispatches virtual getCustomMapData for MapItem subclasses. Native server inventoryTick performs Player.tickCarriedBy, then if unlocked and selected OR actual offhand stack identity, virtual update. Magic update additionally same dimension ResourceKey identity +Player+server. Samples128x128 output, hard-coded16 blocks/pixel and32 pixel radius (512blocks), even fallback scale3; four biome samples per pixel grid,512x512 cached biome samples atY0 spaced4blocks. Floor then Java integer division affects negative viewer offsets. Ring fuzz outside radius30, only radius<32 and odd parity in fuzzy ring. Stream neighbor preference, actual MAGIC_MAP_BIOME_COLOR datamap; absent map uses MAGENTA/brightness1. Native status/damage/attributes unaffected.',
      'magic_cache':'Static MagicMapItem.CACHE uses only ChunkPos(startX,startZ) for complete biome sample array; dimension/world/seed are not part of cache key. Installed TF instruction scan proves only this class accesses this private field and no clear/removal call in its class. Reusing coordinate key can reuse earlier level biome holders during this JVM lifetime. This is a source-level information-cache property, not runtime-tested world contamination or pack-wide reflection exclusion.',
      'magic_icons':'Within charted pixels, only a Legacy landmark center, a structure holder in LANDMARK tag, LandmarkStructure instance and present icon produce TF decoration. Icon rotation180; LandmarkUtil.isConquered reads actual matching TFStructureStart flag, does not mark it conquered. TFMagicMapData.addTFDecoration first native addDecoration, then uses existing decoration byte x/y and asset ID to make conquered marker ID, adds/removes string accordingly. List mutation alone does not call setDirty/setDecorationsDirty; pixel/decor updates use native dirty paths. A map icon is not proof of a live spawned boss, boss death, shield break or protection removal.',
      'map_packets':'TFMagic/MazeData.getUpdatePacket wraps only a nonnull native ClientboundMapItemDataPacket; otherwise passes native result through. Registered playToClient handlers additionally require clientbound flow. Missing client data is created center0, current client dimension, packet scale/locked; native patch then applied. Magic clears/replaces conquered list, Maze sets ore/yCenter; native MapRenderer.update follows. These packets carry information to clients and do not mutate server boss state. Conquered renderer draws red X for matching map marker and returnsfalse so normal icon can render; Magic Player icon custom4scale returns true. Frame/banner/native rendering remains native, with actual NeoForge virtual map lookup; protected Goggles real inventory callback can deliver update/packet without holding map in hand.',
      'empty_maze':'EmptyMazeMapItem.use creates scale0/trackingtrue/unlimitedfalse at floor playerXYZ with constructor ore flag BEFORE consuming1; unlike EmptyMagic no explicit side or dimension-charting tag guard. Native use, inventory/drop and consume semantics remain. Maze create allocates new mapID and mazemap_<id>, native128*(1<<scale) center rounding; TFMazeMapData.calculateMapCenter sets yCenter=creationY and, only ServerLevel with Legacy selected LABYRINTH, snapsXZ to nearest legacy center. Otherwise keeps native rounded center. Missing-data server fallback uses sharedspawnXYZ scale0/trackingfalse and item ore flag, no empty-map recreation requirement.',
      'maze_pixels':'Maze update requires same dimension ResourceKey and Player; server gate comes from native TF inventoryTick. Pixel size1<<scale, view radius16pixels (8 with ceiling), native HoldingPlayer.step increment, columns step-mod16 or prior-change continuation, radius/parity fuzz. Ceiling uses deterministic pseudorandom DIRT/STONE colors, not underground block contents. Nonceiling reads original state at chunk-localXZ/yCenter and immediately adds its map color. If original is STONE OR air, probesY-3..Y+3 for STONE AND notair, assigns first such state and brightness0below/2above/1same. It does NOT search for the first nonstone; original color multiset is not replaced by searched state. Ore branch uses resulting state, datamap ORE_MAP_ORE_COLOR weight1000 else nonair c:ores PINK weight1000. Actual9 installed color keys cover8 native ore tags plus ancient_debris; dynamically mapped/tagged ores remain conditional.',
      'maze_y':'TF Maze server inventoryTick calls tickCarriedBy first. floor(playerY-yCenter) outside[-3,3] replaces existing own-name decoration with PLAYER_OFF_MAP retaining coordinates/rotation. This vertical test changes marker only: it does not veto subsequent unlocked selected/offhand pixelupdate. yCenter and ore flag persist with native saved map fields; server storageoverworld/clientstatic cache separate from Magic. Same mapId among copies shares saved data. No target damage, mining, teleport or forced block loading is introduced by this review; real update reads native chunks as coded.',
      'cloning':'Native Magic/Maze custom crafting recipes require exactlyone filled matching map slot plus>=1 empty matching map slots and no other nonempty ingredients; canCraftInDimensions requires>=3x3. Output is filled.copy() with count(empty SLOTS+1), so components/mapID preserved and all copies share underlying saved data. Filled Ore and empty Ore are not accepted by MazeMapCloningRecipe. Native recipe consumption remains; no invented copy of Ore map or special quantity-per-stacked-input.',
      'cartography':'Exact244 archive has no replacement for native CartographyTableMenu/its five anonymous classes; raw bytecode slot0 mayPlace requires Items.FILLED_MAP, additional slot PAPER/MAP/GLASS_PANE, quickMove sameFILLED_MAP identity. Genuine UI therefore rejects TF filled item identities; no baseline cartography scale/lock/copy route is proven. TF empty onCraftedBy overrides do not override native onCraftedPostProcess (MAP_POST_PROCESSING handles scale/lock). Do not infer disabled scaling from wrong method or force TF stacks through rejected native slots. Other mods changing admission are conditional external behavior.',
      'locator_asm':'Registered ResolveNearestNonRandomSpreadMapStructureTransformer targets exact ChunkGenerator.findNearestMapStructure(ServerLevel,HolderSet,BlockPos,int,boolean)Pair. Finds LAST ARETURN and inserts originalPair +locals1,2,3,4,5 into MapHooks.resolveNearestNonRandomSpreadMapStructure. Exact244 target has THREE ARETURN instructions: empty placement map early-null and early random-spread result bypass hook; only final return is intercepted. Hook calls WorldUtil.findNearestMapLandmark(...).orElse(original). A found TF pair replaces original without comparing distances to original vanilla result. No unconditional all-return interception or global nearest guarantee.',
      'locator_search':'WorldUtil restricts target holder placements to actual LandmarkGridPlacement, otherwise Optional.empty. Scans Legacy landmark centers using focus chunk &-16, spacing16chunks and supplied radius as GRID radius; skipCenterfalse, iterator hasNext dX+1<=radius means radius0 scansnothing. Placement.isStructureChunk remains: native placement/frequency/exclusion checks; TF ctorfreq1/salt0/zerooffset/noexclusion plus actual center and optional resource-key gridlock==pickVarietyLandmark. Target must be in that placement set and structure biome list contain level.getBiome(centerY0). With skipKnown, START_PRESENT breaks inner target loop. It does not load/validate a generated structure start for every accepted candidate. Chooses smallest center.distToLowCornerSqr(queryX,0,queryZ) among TF candidates. Native search reads info, no spawning/HP/shield/progression modification.',
      'locator_seed':'Legacy center coordinates derive region math and deterministic coordinate seed, sign-dependent+8/+9. Biome-specific landmark selection uses rounded16chunk cells sampled atY0; variety uses overworld worldgen seed+chunkX*25117+chunkZ*151121, hill weights6/3/1,hedge2,Naga2,Lich2, with reserved regional Naga/Lich positions. Gridlock uses variety selection; Magic map landmark pick first uses biome mapping. These are distinct code paths. Full native helper/iterator/placement bodies pinned; blockNearLandmarkCenter shifts by(4+x)/(4+z) per Java precedence rather than adding offsets after shift, and is not the map locator call used here. No new boss attack mechanic inferred from structure choice.',
      'locator_delivery':'Actual ServerLevel.findNearestMapStructure delegates to generator with requested tag holders. Native ExplorationMapFunction requires actual Items.MAP and nonnull loot ORIGIN, then uses configured destination/radius/skipKnown; found result creates ordinary native map with zoom, tracking/unlimitedtrue, biome preview and target marker. VillagerTrades.TreasureMapForEmeralds requires ServerLevel trader and uses destination tag, radius100, skipKnowntrue; found result creates native scale2 map and ordinary offer with emerald cost plus compass, configured maxUses/xp and .2 priceMultiplier. Missing search result yields unchanged loot stack or null trade. Native LocateCommand calls generator directly for actual requested structure holder(s), requires normal command authority. Their results reach TF hook only through final-return path and actual LandmarkGridPlacement target. No installed TF exploration-map loot resource is assumed; direct native path availability is distinct from a configured TF trade/loot producer.',
      'meter_start':'OreMeter.use requires player.getClass()==ServerPlayer.class, not instanceof (real subclasses/FakePlayer fail). isLoading means ORE_LOADING component presence; if present PASS. Otherwise nonsecondary begins server scan with range=getOrDefault1, duration50+25range and ORE_SCANNING only. No ORE_LOADING until first tick, so another valid use before tick can restart. No consumption, durability or cooldown. Secondary air-use only cycles range via positiveModulo(range+1,3) when native Fluid.ANY ray MISS; hit returnsPASS. Separate useOn secondary+actual clicked ORE_METER_TARGETABLE tag sets ORE_FILTER, no loading/server check inside method, no nullPlayer guard. Actual interaction eligibility remains.',
      'meter_geometry':'OreScannerComponent.scanFromCenter uses chunk=(center>>4), origin((chunk-range)<<4,Y0), span=endcoord(chunk+range,15)-origin WITHOUT+1. Normalranges0/1/2 produce15/47/79 blocks per horizontal axis. tickScan uses CURRENT level minBuildHeight as originY, area=xSpan*zSpan, volume=area*CURRENT getMaxBuildHeight (not max-min). march=ceil(float(volume)/abs(duration)), starts at ticksProgressed*march, scans linearX/Z/Y until volume; copies immutable counter and adds one tick. Standard min=-64,max=320 yieldsY-64..255, excluding256..319. This exact formula is recorded, not repaired or assumed to scan full nominal chunks.',
      'meter_progress':'Server inventoryTick any real ticked slot with ORE_SCANNING: tickScan first; if empty removeSCANNINGonly, else unfinished writesLOADINGprogress+SCANNINGnext; finished writesORE_DATA(getResults(CURRENTfilter),centerChunk,volume,CURRENTrange), removesLOADING/SCANNING. No held requirement or persisted dimension: carrying genuine scanning stack across levels can sample current level at storedXZ and combine counters; no runtime assertion. Existing ORE_DATA remains during new scan but loadingHUD takes precedence. No ore removal, damage source, status or direct resource transfer. Scanning continues only with real inventoryTick caller, not hypothetical every container.',
      'meter_results':'Counter includes all scanned Block identities. With assigned filter getResults returns exactly its translated-descriptionID and count (even0); without filter includes count>0 and block holder c:ores. Results use immutable map, saved scannedChunk,totalScannedBlocks, universalId=(counts.hashCode XOR chunk.toLong)*(scannedRange XOR total). ORE_SCANNING codec persists origin/spans/duration/counts/progression; default-on-parse-error is empty scanner. TF registration specifies persistent codec with no explicit network codec, but native DataComponentType.Builder.build derives fromCodecWithRegistries, so not server-only/transient. DATA/LOADING/RANGE/FILTER have explicit persistence/network codecs. Native stack/save/load/sync applies; no timer outside callback.',
      'meter_clear_display':'EntityEvents.LeftClickEmpty listener, if genuine heldmeter hasDATA ORFILTER, sends WipeOreMeterPacket and locally removesDATA/FILTER. Registered playToServer handler uses ctx.player actual hand and exactORE_METER before removing those two only. Does not cancel SCANNING, LOADING or RANGE; ongoing scan may refillDATA. HUD real heldmeter (main preferred), activeclient GUIvisible/no debug/no screen; LOADINGdots elseDATA. Nonzero universalId initializes cached table; id0 skipped unless an entry already exists. Displays snapshot counts/percentages/scannedchunk, not live world query. Cache key omits dimension/independent configuration and can collide; read-only info behavior, not proven pack issue.',
      'cloth_erratum':'R2f8q incorrectly treated untransformed NeoForge ElytraLayer.shouldRender as final behavior. Installed TFCoreMod registers CancelElytraRenderingTransformer, targets exact shouldRender(ItemStack,LivingEntity)Z, inserts ALOAD1 plus ArmorHooks.cancelArmorRendering(originalBoolean,stack) before EVERY IRETURN (172). Exact244 method has local1ItemStack and native ELYTRA identity predicate. Component present turns true tofalse; false staysfalse. Cloth therefore hides native Elytra wing rendering, separately from humanoid armor hook, while cape may render through protected cape hook. This changes no attributes, protection, durability or native flight. Historical Q files remain immutable; new accumulated draft explicitly corrects one paragraph in four locations and one future-control label, with source references and counted locations.',
      'compatibility':'NeoForge virtual custom-map lookup is actual loader behavior; two registered TF ASM hooks are native TF source changes (DIRECT_SOURCE_SPECIFIC to exact native targets). Native inventory/crafting/packet/data-component methods plus real dynamic biome/block data maps and c tags are GENERIC_CONDITIONAL_PRESENT. No direct external mod combat override proven in these scoped source bodies (NONE_PROVEN), no Curios-native map inventory callback invented. Unscanned external modifications remain UNKNOWN; no pack-wide certification or runtime success claim. Other ASM/hazards/passives/source exclusions remain ordinary unfinished scope.'
    }
    M='item/MagicMapItem';Z='item/MazeMapItem';O='item/OreMeterItem';MD='item/mapdata/TFMagicMapData';ZD='item/mapdata/TFMazeMapData';H='asmhooks/MapHooks';W='util/WorldUtil';S='components/item/OreScannerComponent';D='components/item/OreScannerData'
    nxt='Review structural utility items/blocks (Rope, Magic Beans, remaining magic cores and associated callbacks), passive entities, environmental hazards and nine remaining custom DamageTypes; close remaining nested ASM, compatibility and source exclusions. Then R2f8 and final Twilight COMPLETE promotion; only afterward IceAndFire. Static only; no runtime/L2/Stage/production/Phase6/7.'
    data=dict(slug='maps-information',checkpoint_short='r2f8t',checkpoint='R2f8t-maps-information-complete',decision='TWILIGHT_MAPS_INFORMATION_SEMANTIC_REVIEW_COMPLETE',starting_sha='e63af59ef4558422a3036d617381645c0e4ff160',previous_checkpoint='R2f8s-active-utilities-complete',previous_draft='partial-drafts/twilightforest-r2f8s-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=0,full_classes=FULL,limited_classes={W:['findNearestMapLandmark/getOverworldSeed'],'util/landmarks/LandmarkUtil':['read conquered and nearest structure lookup'],'events/EntityEvents':['setup/wipeOreMeterOnLeftClick'],'client/event/OverlayHandler':['registerOverlays/OreMeter snapshot HUD/cache'],'client/event/ClientRegistrationEvents':['map renderer registrations and OreMeter model predicates']},registration_classes=['init/TFItems','init/TFRecipes','init/TFDataComponents','init/TFMapDecorations','events/RegistrationEvents'],closure_checklist=['actual_map_registry_and_recipes','native_loader_virtual_lookup','dimension_type_and_fallback_distinction','map_sampling_cache_and_markers','maze_y_marker_not_update_veto','copy_shared_id_ore_exclusion','cartography_real_item_gate','server_storage_and_client_packets','registered_locator_last_return_only','exact_landmark_placement_biome_presence_predicates','legitimate_native_locator_callers','meter_exact_player_loading_and_filter_gates','meter_off_by_one_horizontal_and_vertical_formula','meter_persistence_and_derived_network_codec','meter_clear_does_not_cancel_scan','registered_Elytra_hook_correction_historical_preservation'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus Magic/Maze/Ore maps, OreMeter, native landmark locator and explicit R2f8q Elytra-render erratum; Twilight PARTIAL, zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=31,new_used_profiles=0,reviewed_profiles_after=31,remaining_profiles=9,remaining_disposition='Ordinary unfinished hazard callers; not unused or REVIEW_REQUIRED.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,controls):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=controls));return eid
    magic=pkg('magic_map_information','Magic Map native biome and landmark information','CUSTOM_CONTROL',['registration','empty_magic','magic_identity','magic_update','magic_cache','magic_icons','map_packets','cloning','cartography'],[M,MD,'item/EmptyMagicMapItem','network/MagicMapPacket','item/recipe/MagicMapCloningRecipe'],{'empty_scale':4,'fallback_scale':3,'blocks_per_pixel':16,'view_radius_pixels':32,'center_grid':2048},['actualnativeuse','creationdimensionTYPEtag','samelevelupdate','Player','native selected/offhand/goggles','unlocked'],'Custom information over native map item/data/packet infrastructure, no damage.','Native emptyMagicMap use and held map',['wrongdimension','fallback','cache','conqueredread','copy','goggles'])
    maze=pkg('maze_ore_map_information','Maze and Ore Map slice information','CUSTOM_CONTROL',['registration','empty_maze','maze_pixels','maze_y','map_packets','cloning','cartography'],[Z,ZD,'item/EmptyMazeMapItem','network/MazeMapPacket','item/recipe/MazeMapCloningRecipe'],{'scale':0,'radius_pixels':16,'ceiling_radius':8,'Y_search':3,'ore_weight':1000},['nativeemptyvariant','samedimension','Player','unlockedselected/offhand','ore flag/maps/tags'],'Custom fixed-Y map pixels and ore colors; no mining or combat mutation.','Native Maze/Ore map use',['actualYslice','verticalmarker','ceiling','nativeclone exclusions','goggles'])
    locator=pkg('landmark_map_locator','Native landmark locator integration','CUSTOM_CONTROL',['locator_asm','locator_search','locator_seed','locator_delivery'],[H,W,'util/landmarks/LegacyLandmarkPlacements','util/iterators/XZQuadrantIterator','world/components/structures/placements/LandmarkGridPlacement'],{'spacing_chunks':16,'hooked_returns':1,'target_returns':3},['actualfinalreturn','LandmarkGridPlacement','biome/structureselection','radius','skipKnown'],'Extends native structure locator, information only.','Native authorized locateStructure for landmark',['nativeexplorationmap','nativevillagertrade conditionaltarget','earlierreturn','no matchingplacement'])
    meter=pkg('ore_meter_information','Ore Meter native scanned snapshot','CUSTOM_CONTROL',['registration','meter_start','meter_geometry','meter_progress','meter_results','meter_clear_display'],[O,S,D,'network/WipeOreMeterPacket','events/EntityEvents','client/event/OverlayHandler'],{'normal_ranges':[0,1,2],'default_range':1,'horizontal_spans':[15,47,79],'scan_durations':[50,75,100]},['exactServerPlayeruse','loadingcomponent','nativeinventorytick','actuallevelgeometry','filtertag','realheldclear'],'Custom informational scan and stored snapshot; not resource extraction or damage.','Native registered OreMeter use',['range/filter','dimensionchange','save/reload','ongoingclear','HUDsnapshot'])
    for e in data['packages'][:2]:e['reuses_protected_effect_ids']=['twilightforest:travellers_item_display']
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:maps_information_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through genuine native item/callback/command; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('magic_create','Native empty Magic Map admitted/rejected dimension',['registration','empty_magic'],[magic],['item/EmptyMagicMapItem'],['ACTIVE_ITEM'],['dimensionTYPE tag','creativeconsume','inventorydrop','clientPASS']),
      ('magic_update','Native held Magic Map biome charting',['magic_update','magic_cache'],[magic],[M],['ACTIVE_ITEM','PASSIVE_ITEM'],['selected/offhand','dimension','locked','Y0stream preference','cache coordinates']),
      ('magic_fallback','Native missing Magic Map data recovery',['magic_identity','magic_update'],[magic],[M,MD],['OTHER'],['spawnscale3','newID','no creationtag recheck']),
      ('magic_landmarks','Native Magic Map landmark and conquered decoration',['magic_icons'],[magic],[M,MD,'util/landmarks/LandmarkUtil'],['OTHER'],['actualLANDMARK/icon','conquered read','nodeathmutation','dirty behavior']),
      ('magic_store','Native Magic Map save/load and packet delivery',['magic_identity','map_packets'],[magic],[MD,'network/MagicMapPacket','network/MagicMapPacket$1'],['OTHER'],['overworlddatastorage','separateclientcache','nativepacketnonnull','showOnItemFrame']),
      ('magic_clone','Native Magic Map custom crafting copy',['cloning'],[magic],['item/recipe/MagicMapCloningRecipe'],['OTHER'],['exactonefilled','empty slots','3x3','sameID']),
      ('maze_create','Native empty Maze Map creation',['registration','empty_maze'],[maze],['item/EmptyMazeMapItem',Z,ZD],['ACTIVE_ITEM'],['Ycenter','labyrinthsnap','actualside','noMagicdimensiongate']),
      ('ore_create','Native empty Ore Map recipe and activation',['registration','empty_maze'],[maze],['item/EmptyMazeMapItem',Z],['ACTIVE_ITEM'],['emptyMaze ingredient','oretrue','nofilled upgrade']),
      ('maze_update','Native Maze Map fixed-Y pixels',['maze_pixels','maze_y'],[maze],[Z],['ACTIVE_ITEM','PASSIVE_ITEM'],['stone search','originalcolor','columnstep','radius16']),
      ('ore_update','Native Ore Map data-map/tag colors',['maze_pixels'],[maze],[Z],['ACTIVE_ITEM','PASSIVE_ITEM'],['actualoreflag','9colorkeys','1000weight','PINKfallback']),
      ('maze_ceiling','Native ceiling Maze/Ore map control',['maze_pixels'],[maze],[Z],['OTHER'],['radius8','pseudorandomcolors','noorequerybranch']),
      ('maze_height','Native Maze Map distant-Y marker',['maze_y'],[maze],[Z],['OTHER'],['floorDeltaoutside3','markeronly','stillupdatespixels']),
      ('maze_store','Native Maze/Ore map persistence and packet',['empty_maze','maze_y','map_packets'],[maze],[ZD,'network/MazeMapPacket','network/MazeMapPacket$1'],['OTHER'],['yCenter/ore','clientbound','sharedsaveddata']),
      ('maze_fallback','Native missing Maze/Ore data recovery',['empty_maze'],[maze],[Z,ZD],['OTHER'],['sharedspawn','itemoreflag','newmapID']),
      ('maze_clone','Native Maze copy and Ore rejection',['cloning'],[maze],['item/recipe/MazeMapCloningRecipe'],['OTHER'],['sameID','orefilled/emptyreject','3x3']),
      ('map_goggles','Protected native Goggles callback to TF custom maps',['magic_update','map_packets'],[magic,maze],[H],['ARMOR_PROC','OTHER'],['realactivemap','nativevirtualcallback','protectedQno redo']),
      ('map_cartography','Native cartography UI negative controls',['cartography'],[magic,maze],[M,Z],['OTHER'],['exactItems.FILLED_MAP','no forcedslot','onCraftedBy !=postprocess']),
      ('locator_command','Native authorized structure locate command',['locator_asm','locator_search','locator_delivery'],[locator],[H,W],['OTHER'],['nativeauthority','finalreturn','actualtargetholder']),
      ('locator_loot','Native configured ExplorationMapFunction lookup',['locator_delivery','locator_asm'],[locator],[H,W],['OTHER'],['realconfiguredtag','notassumedinstalledTFloot','foundresult']),
      ('locator_trade','Native configured TreasureMapForEmeralds lookup',['locator_delivery','locator_asm'],[locator],[H,W],['OTHER'],['realvillageroffer','targettag','no inventedTFtrade']),
      ('locator_gates','Native locator placement/biome/presence and fallback',['locator_search','locator_seed','locator_asm'],[locator],[W,'util/landmarks/LegacyLandmarkPlacements','world/components/structures/placements/LandmarkGridPlacement'],['OTHER'],['radius0','skipKnownSTART_PRESENT','gridlock','no crossresultdistancecomparison','earlyreturns']),
      ('meter_start','Native exact ServerPlayer OreMeter start',['meter_start'],[meter],[O],['ACTIVE_ITEM'],['subclassrejection','pre-firsttick restart','no cost']),
      ('meter_range','Native OreMeter secondary air range cycle',['meter_start'],[meter],[O],['ACTIVE_ITEM'],['FluidANYMISS','0/1/2','loading gate']),
      ('meter_filter','Native OreMeter secondary block filter',['meter_start','meter_results'],[meter],[O,S],['ACTIVE_ITEM'],['actualtargetabletag','useOn distinct','currentfilteratfinish']),
      ('meter_tick','Native OreMeter asynchronous inventory scan',['meter_geometry','meter_progress'],[meter],[O,S],['PASSIVE_ITEM'],['15/47/79','volume=maxheight*area','realinventorytick','noheldrequirement']),
      ('meter_persistence','Native OreMeter persistence/dimension movement',['meter_progress','meter_results'],[meter],[S,D,'init/TFDataComponents'],['OTHER'],['actualsave/load/network','nodimensionfield','currlevelY','snapshotnotlive']),
      ('meter_clear','Native OreMeter left-click clear and validated packet',['meter_clear_display'],[meter],['events/EntityEvents','network/WipeOreMeterPacket'],['ACTIVE_ITEM'],['ctxplayeractualhand','DATA/FILTERonly','scancontinues']),
      ('meter_display','Native held OreMeter snapshot HUD',['meter_clear_display','meter_results'],[meter],['client/event/OverlayHandler',D],['OTHER'],['mainpreferred','GUIgates','id0/cache','no damage or ore extraction'])]
    for row in rows:path(*row)
    old=read_json(OUT/'review-inputs/twilightforest-travellers-utility.json')['facts']['cloth_render']
    new=old.replace('No installed TF cloth hook changes ElytraLayer.shouldRender: exact native method still accepts ELYTRA, so cloth on Elytra does NOT prove wing model hidden by the humanoid hook.','R2f8t correction: registered CancelElytraRenderingTransformer independently targets exact NeoForge ElytraLayer.shouldRender(ItemStack,LivingEntity)Z; before every IRETURN it passes original predicate and local1 stack to ArmorHooks.cancelArmorRendering. Native ELYTRA true becomesfalse with EMPERORS_CLOTH, so cloth hides wing rendering. Untransformed method alone is not final installed behavior.')
    data['semantic_corrections']=[dict(id='R2f8q-cloth-elytra-render-erratum',old_text=old,new_text=new,expected_locations=['effects/189/actual_behavior/2','effects/189/components/0/formula','paths/610/native_delivery','paths/611/native_delivery'],reason=facts['cloth_erratum'],evidence_files=['reference-evidence/'+BATCH+'-asm.json','reference-evidence/twilight-equipment-asm.json','reference-evidence/twilight-travellers-utility-244.json']),dict(id='R2f8q-cloth-elytra-fixture-erratum',old_text='Elytralayerstillrenders',new_text='registeredElytraHookSuppressesClothedWings',expected_locations=['paths/611/future_controls/2'],reason=facts['cloth_erratum'],evidence_files=['reference-evidence/'+BATCH+'-asm.json'])]
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','reference-evidence/'+BATCH+'-asm.json','twilightforest-maps-information-caller-scan.json','reference-evidence/twilight-equipment-asm.json','reference-evidence/twilight-travellers-utility-244.json']
    data['exclusions']=['Information mechanics are separated from HP damage, shields, statuses and boss progression; no new DamageType.','Full25 TF map/scanner/helper classes reviewed; protected Goggles and cloth mechanics reused, only proven Elytra erratum updates accumulated draft. Historical Q evidence unchanged.','Registered map locator target has three native returns, only final transformed; legitimate configured native loot/trade/command paths are conditional, not fabricated installed TF producers.','Other structural utilities, passive entities, hazards/nine custom types, ASM/compatibility/source closure remain unfinished. No runtime or production change.']
    data['fixture_groups']=['Actual emptyMagicdimensiontype gate, Maze/Ore creationY and orevariant; held/offhand/protectedgoggles native callbacks.','Map cache/dimension, fixedYsearch, highYmarker, ceilingcolors, savedIDcloning and cartography negativecontrols.','Native landmark configuredquery: exactfinalreturn, biome/grid/presence/radius0, originalfallback versus TFreplacement.','OreMeter exactplayer/start/loading/filter, geometry/minmaxY, save/dimensionmovement, clear-duringscan, realHUDsnapshot.','Native Emperor cloth on Elytra: registered shouldRender hook suppression separately from cape/defense/flight; runtime0.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-maps-information.json',data);assemble('twilightforest-maps-information.json')

if __name__=='__main__':build()
