"""R2f5 reviewed boss packages, scoped source disposition and owner documentation."""
from copy import deepcopy
from collections import Counter
from twilight_evidence import *
from assemble_batch import refresh

START = 'c30b8c98fbbd8aefad86088cd027d4156b22924f'
CP = 'R2f5-minoshroom-knight-complete'
DECISION = 'MINOSHROOM_KNIGHT_PHANTOM_SEMANTIC_REVIEW_COMPLETE'
NEXT = 'Begin Hydra + Ur-Ghast semantic review using existing installed Twilight source aids, then Alpha Yeti + Snow Queen. Frosted, Lich, Naga, Minoshroom and Knight Phantom are complete subsections; do not repeat them. No Ice and Fire, runtime boss/L2 testing, Stage/production, fixes, balancing, Phase6 reopening or Phase7 work.'
BATCH = 'twilight-minoshroom-knight'


def build():
    facts = {
      'minoshroom_attributes_equipment': 'Minoshroom inherits BaseTFBoss, not Minotaur behavior; registerAttributes reuses Minotaur attributes: HP120, movement0.25, base ATTACK_DAMAGE2 (native attribute default), KR0.5. FinalizeSpawn invokes native Mob finalization, ordinary random armor population, then equips diamond_minotaur_axe and requests ordinary spawn enchantments. Diamond tier attack bonus3 + axe parameter6 supplies +9 MAINHAND attack; settled unenchanted total11. Equipment updates apply native attributes; the axe attack-speed modifier -3.2 does not set mob AI cadence. Armor is not guaranteed zero: native population probability0.15*specialDifficultyMultiplier and equipment/enchantment rolls remain. Minoshroom weapon enchantment chance0.25*specialMultiplier, armor0.5*specialMultiplier. Axe gold enchantability is22, inherited durability1561 for diamond; no boss attack helper invokes ItemStack.hurtEnemy/postHurtEnemy, so ordinary axe wear is not charged by these mob hits. Native Player use of the same axe retains ordinary wear. Mainhand drop chance0 affects loot only. Installed multiplayerFightAdjuster=NONE is reused; no HP difficulty phase/regen/berserk threshold exists in Minoshroom.',
      'minoshroom_melee': 'Priority3 native MeleeAttackGoal(speed1,false) uses live target, path or melee reach, native LOS and melee AABB. Requires every-tick update; attack counter decremented then tested, resets20 before dispatch, independent of hurt success. It calls Minoshroom.doHurtTarget, which REPLACES ordinary Mob.doHurtTarget with EntityUtil.properlyApplyCustomDamageSource using twilightforest:axing, direct=causing=Minoshroom. Effective attack attribute passes native EnchantmentHelper.modifyDamage before victim.hurt, but the helper supplies ATTACKER itself as the affected Entity argument instead of victim (unlike Mob.doHurtTarget); target-dependent enchantment evaluation therefore uses that wrong entity context. This is separate from the later knockback helper, which receives the victim. True enables enchantment-adjusted ATTACK_KNOCKBACK*0.5, attacker XZ velocity*0.6 when extra knockback>0, and native post-attack enchantments. Helper mistakenly calls setLastHurtMob(attacker itself), not victim; preserve this installed distinction. False suppresses those success callbacks; true need not mean HP loss. It is a vanilla-like extended melee package, not an invented ordinary mob_attack CUSTOM_DAMAGE. Axing is physical-tagged with normal armor/Resistance/protection/absorption/cooldown.',
      'minoshroom_sprint_bonus': 'Registered ToolEvents.addExtraAxeChargingDamage listens to LivingIncomingDamageEvent: uncanceled, server target, DIRECT entity Living and sprinting, nonempty MAINHAND instanceof MinotaurAxeItem => current newDamage +7. No source-type or successful-hurt test. Native Player difficulty scaling happens before this incoming hook, so settled unenchanted charging hit is D(11)+7, not D(18); Normal18, Easy13.5, Hard23.5 before downstream mitigation. A zero Player request (including Peaceful scaling) returns before the incoming event and cannot gain the bonus. Enchantments/other hooks can change the input. The same hook works for native Player sprint attacks (player_attack source) and a Minotaur that actually spawned with gold_minotaur_axe; a plain golden axe fails the item predicate. It is not a charge-only tag, and it does not require CHARGING synced flag. Return-false shield/cooldown rejection can occur after the bonus event.',
      'minoshroom_axe_shield': 'Victim Player native blocking remains its own subsystem. Exact244 Living shield processing follows incoming callbacks; nonprojectile direct Living source invokes Player.blockUsingShield, then attacker.canDisableShield. The default IItemExtension returns instanceof AxeItem, inherited unchanged by MinotaurAxeItem/KnightmetalAxeItem. Native Player.disableShield sets current use-item cooldown100, stops use, broadcasts30. This does not depend on the boss melee helper receiving true. Blocking requires native warmup>=5, source direction and no BYPASSES_SHIELD; shield durability request is native1+floor(blocked shield damage) when>=3, subject to ordinary durability/creative/enchantment handling. Twilight adds no extra Minoshroom shield-disable mechanic. Slam bypasses shield and does not enter that block callback. Knight Phantom shield defense has its own early return described separately.',
      'minoshroom_charge': 'Priority2 ChargeAttackGoal(speed1.5,canBreak=true), MOVE/LOOK, requires target, squared distance25..73 inclusive, onGround, sensing LOS, randomInt10==0. Destination snapshots targetY and horizontal target direction overshot2.1. Start windup15..44 and native setSprinting(true), adding movement multiplier1.3 to base0.25; navigation speed parameter1.5 is separate. Continuation is windup>0 OR navigation not done, not renewed target/range/LOS validity. Each tick looks at snapshot; windup predecrements, starts navigation at0; earlier windup sets synced CHARGING true. Every tick, including windup, checks distanceSquared to captured target minY <=5; first qualifying attempt sets hasAttacked=true BEFORE doHurtTarget, so one attempt per run even if rejected. No multi-target collision sweep, special launch or extra charge DamageType. stop clears target/windup/attempt flag/sprint/CHARGING. No independent long recharge counter; reentry uses range/random/goal scheduling. GroundAttack priority1 can interrupt and stop the charge, removing sprint before its slam.',
      'minoshroom_slam': 'Priority1 GroundAttackGoal MOVE/LOOK. canUse postdecrements cooldown even when no target; eligible cooldown<=0, target distanceSquared2..9 inclusive, onGround, chance1/24 with LOS or1/20 without. Start cooldown200..399 canUse evaluations, attackTick30..59 goal tick calls, synced max charge and ground flag. Goal uses default reduced scheduling, not fixed game-tick seconds. Continues while attackTick>=0 without target-life/range/LOS/ground revalidation. Tick looks at captured target and sets MoveControl.operation WAIT (not a velocity reset or universal immobilization); postdecrement<=0 performs one slam and clears ground flag. Selection is block-position-centered AABB XZ +/-7.5, Y from blockY to blockY+3, intersects Entity candidates filtered Player, then recipient.onGround. No radial falloff, target-only/team/LOS/creative prefilter. Push(0,.23,0) happens BEFORE hurt and ignores success; creative/invulnerable/blocked-by-hook players can receive the push despite no HP damage. twilightforest:slam direct=causing=Minoshroom requests0.5*effective ATTACK_DAMAGE (normally5.5); no EnchantmentHelper.modifyDamage or post-attack callback. BYPASSES_ARMOR transitively BYPASSES_SHIELD; retains Resistance/protection/absorption/cooldown. NO_ANGER and AVOIDS_GUARDIAN_THORNS tags preserved. Normally sprint has stopped; the general axe hook would still require actual sprint if another genuine path retained it. No block destruction by this slam. stop sets attackTick0/target null but does not itself clear ground flag, so interruption can leave a visual flag until another completion; no saved ground attack resource.',
      'minoshroom_terrain': 'Charge after windup, canBreak, server, EventHooks.canEntityGrief (default mobGriefing), loaded box: floor headBB XZ +/-0.75, minY unchanged, maxY+0.15. Each block requires EntityUtil.canDestroyBlock AND no block entity at all, then destroyBlock(pos,true). Helper: hardness>=0 and<50, nonair, not Container BE, block.canEntityDestroy and uncanceled destroy event. All BE exclusion is stricter than helper alone. No leaf shortcut here. Destruction changes combat navigation/support, not a damage request. Slam particles/game event do not destroy terrain. Shared BaseTFBoss accepted lavaHurt4 separately removes exact lava blocks in BB.inflate9 without grief/helper permission; inherited by both bosses. Keep this source/return predicate separate from charge clearing.',
      'minoshroom_defense_lifecycle': 'No Minoshroom hurt/isInvulnerableTo override, no source-specific projectile/explosion immunity, shield phase, damage cap, special iframe or HP gate. Registered type is not fireproof and no fall-immunity tag includes Minoshroom; normal native damage, optional equipment, Resistance and hooks apply. Boss membership prevents natural freeze buildup/helper Frosted admission, not every externally delivered IS_FREEZING damage request. Home radius20 uses valid same-dimension strict block-position distanceSquared<400 for priority5 AttemptToGoHomeGoal(speed1.25); it is navigation, NOT Naga-style source/owner admission or invulnerability. Higher-priority combat may preempt home movement. Targeting: native nearest Player(false mustSee), retaliation; no bespoke in-home target gate. BaseTFBoss refuses mounts/portals and fluid pushing; water slowdown1; Base lavaHurt ignites5 seconds then requests ownerless minecraft:lava4; only true hurt calls killLavaAround. It scans bossBB.inflate9 in unit steps, replaces exact Blocks.LAVA with AIR, without mobGriefing/hardness/container checks. Rejected cooldown/invulnerability prevents cleanup; true with absorption may still clean. This is environmental recovery, not fire immunity. Base death removal at20, normal dead hurt rejection; no resurrection/regen. Peaceful restores spawner at loaded valid home then discards; no far-away despawn. Native boss spawner range9 and nearest PlayerY<spawnerY+4, nonPeaceful, finalize then assign home. Spawn eggs without home are a different setup. Synced charge flags/counters and goal state are not custom NBT-saved; native HP/equipment/home persist.',
      'knight_equipment_attributes': 'Each KnightPhantom HP35, base ATTACK_DAMAGE1. Native finalization equips knightmetal sword, phantom helmet3 armor+toughness2.5 and chestplate8+toughness2.5, requests ordinary enchantments, adds transient inactive armor modifier +4 ADD_MULTIPLIED_TOTAL. Equipment settles through native modifier updates. Knightmetal tier bonus3 means sword+6/axe+9/pick+4 attack: unenchanted settled totals7/10/5 inactive and14/17/12 while charged (+7 ADD_VALUE). Charging flag is true for BOTH ATTACK_PLAYER_START and ATTACK_PLAYER_ATTACK, not directional CHARGE_PLUS/MINUS formations. It removes the inactive armor multiplier: ordinary supplied armor11,toughness5 while charged versus11*5=55 clamped by native armor maximum30 while inactive. This is armor, not80% universal immunity; armor-bypass and standard damage formulas remain. State also changes actual dimensions1.25x2.5 inactive to1.75x4 charged; no actual invisibility damage gate. Mob helper does not consume weapon durability or call item hurtEnemy; Living default armor damage method is empty for this boss. Enchantment/post-effect durability behavior remains native where dispatched. setNumber replaces weapon with a NEW unenchanted stack by number%3:0 sword,1 axe,2 pick, losing old durability/enchantments; native six-spawner assigns number after initial enchantment, so mainhand enchantment is discarded there, armor enchantments remain.',
      'knight_melee_weapon_bonus': 'PhantomWatchAndAttackGoal has no flags, canUse targetnonnull, default goal scheduling. With live target: lookAt(10,500); requires sensing LOS, postdecrement attackTime<=0, distance<2 and vertical BB overlap; resets20 before doHurtTarget, ignores return. Counter decreases only with live visible target (range test follows decrement); successful uninterrupted retry after21 visible goal calls, not fixed20 game ticks. Attacks can occur in any formation if eligible. Knight.doHurtTarget uses the same custom helper as Minoshroom with twilightforest:haunt direct=causing=Knight: attribute/enchantment damage with ATTACKER-as-affected-Entity in modifyDamage, success knockback/post-enchantment, erroneous lastHurtMob=self. HAUNT is magic-tagged, NOT armor-bypassing. Registered ToolEvents.doKnightmetalToolLogic at incoming, uncanceled/server/direct Living/nonempty mainhand: sword OR pick and target armorValue>0 adds int(2*armorCoverPercentage) to CURRENT newDamage if cover>0, else+2. Native cover=nonempty armor slots/total slots; quarter-covered target therefore adds0, half1, full2, while armor attribute without worn pieces adds2. Axe with armorValue==0 SETS newDamage=ORIGINAL damage+2 (can overwrite earlier hook changes), otherwise no bonus. Armor test is recipient before mitigation; no bypass. These hooks also apply to genuine native Player tool attacks; they do not run for ownerless ThrownWep sources. Player difficulty scaling precedes hook. Axe uses ordinary native Player shield disabling as described above; sword/pick do not gain it.',
      'knight_projectile_launch': 'Only PhantomThrowWeaponGoal in ATTACK_PLAYER_ATTACK with target and ticksProgress%4==0. Default goal scheduling and formation counter determine cadence; no unconditional every4 game-tick promise. Axe role creates NEW ThrownWep owned by boss, fresh plain knightmetal_axe, defaultdamage6 and gravity0.001, shoot speed0.75/inaccuracy1. Origin body-facing offset1, Y+height*.82; aims XZ to target and Y uses target minY+halfheight minus bossY+halfheight (not originY). Pick role emits8 fresh projectiles at45-degree increments, horizontal initial directions, radius1/Y+height*.82, speed0.5/inaccuracy1, setDamage3,setVelocity(.015) (the latter is GRAVITY, not launch speed), fresh knightmetal_pickaxe. No held-stack consumption, durability, pickup ammunition, enchantment copying or throw inventory pool. Sword emits none. Native ThrowableProjectile drag0.99 air/.8 water and configured gravity apply.',
      'knight_projectile_source_hit': 'ThrownWep extends TFThrowable/ThrowableProjectile, retains native owner reference for collision but creates TFDamageTypes.getDamageSource with NO entity arguments. Therefore direct=null, causing=null, no explicit source position for BOTH thrown_axe6 and thrown_pickaxe3. Pickaxe identity selected only by synced item exactly knightmetal_pickaxe; every other item defaults AXE. Native canHitEntity checks recipient.canBeHitByProjectile and owner/root-vehicle until leftOwner. Accepted server onHitEntity excludes ANY KnightPhantom and exact current owner; no other team/Living-only gate. It calls hurt and ignores result. No weapon enchantment damage/post-effect, Knightmetal incoming bonus, owner-based Player difficulty scaling or directional native shield block, despite projectile retaining owner. Types are IS_PROJECTILE and physical; armor/Resistance/protection/projectile protection/absorption/cooldown remain. No armor/shield bypass tag; missing source position itself prevents ordinary directional shield block. Missing direct Projectile means normal Living knockback direction uses no projectile reference. onHit calls inherited entity/block callback then server smoke event/discard unconditionally even when hurt false or target is excluded. Other Knights therefore consume a colliding throw without HP damage. No piercing/multi-hit/pickup/return/reuse mechanic.',
      'knight_projectile_reflection_persistence': 'Exact244 Throwable tick offers ProjectileImpactEvent before hitTargetOrDeflectSelf; cancellation prevents onHit and discard. TF native timed parry applies to ITFProjectile, server, external parry mod absent (accepted installed scan), actual blocking, use elapsed<=configured40 and native blocking warmup>=5. AIM_DEFLECT transfers owner to blocker and cancels impact, independently of the later ownerless damage request; reflected projectile still cannot damage ANY KnightPhantom, and later source remains direct/causing null. Source-independent parry can work where ordinary ownerless directional shield block cannot. ThrownWep is pickable, pickRadius1, but not in REDIRECTABLE_PROJECTILE; inherited Entity.hurt false and no own hurt override means ordinary Player melee is not a proven bat-back path. Inherited projectile-on-projectile redirect only targets tagged projectiles; a throw can redirect a genuine tagged Lich Bolt via inherited Projectile.onHit but this does not reopen Lich review. There is no ThrownWep save/load override: inherited Projectile saves owner/leftOwner/hasBeenShot; item/gravity/projectileDamage are NOT saved. Reloaded pick becomes empty-item AXE source, damage6/gravity.001, while owner UUID persists. Synced data is not NBT persistence. No custom lifetime counter; normal impact/removal/environment rules remain.',
      'knight_group_identity': 'Native boss spawner attempts6 Knights in60-degree radius4 ring; generic range9 plus nearestPlayerY>spawnerY-2 and nonPeaceful. Finalize, assign same GlobalPos home, setNumber(i), add entity; spawned increments only on add success, spawner remains until6 successes. spawned is not custom NBT-saved; partial failure/reload is not a transactional unique six-member group. Hard gives OFFHAND knightmetal_shield only to i=5, before initialization/numbering. getNearbyKnights is class query in own BB.inflate64 with LivingEntity.isAlive and includes self; no group UUID, team, owner, shared home requirement, or six-member cap. Multiple encounters within range can mix; membership is local and geometry-dependent. Each has independent HP35, formation/counter/charge position. Lowest current number in observed list leads normal formation selection; ties can each qualify, no unique shared lock. updateMyNumber copies another number0 home, fills smaller/duplicate indices, tracks maximum known count for bossbar only. Death postmortem renumbers survivors only when BaseTFBoss.shouldSpawnLoot (doMobLoot) permits postmortem; later switchToFormation also renumbers. Group bossbar aggregate/totalKnownKnights is presentation, not a shared HP resource, reserve, heal or damage redistribution.',
      'knight_formation_schedule': 'Initial HOVER90. Formation durations in GOAL update counts: LARGE clockwise/anticlockwise180, SMALL90, four axis traversals180, WAITING10, ATTACK_PLAYER_START50, ATTACK_PLAYER_ATTACK50. Default requiresUpdateEveryTick=false so native selector normally ticks these on alternating game ticks; all-time counters are not seconds. Update goal always active, no flags: sets noPhysics from OLD progress%20!=0, increments, transitions if>=duration, then sends wanted destination speed2 if FLAG_CHARGING else1. Lowest-number leader when ordinary formation ends randomly chooses smallCW2/8,smallCCW2/8, each axis1/8, broadcasts to all observed noncharging Knights including self, then if none charging chooses RANDOM nearby Knight for ATTACK_PLAYER_START. It is not rotating turn order. Large-circle enum destinations are implemented but not selected by this native random chooser; no fabricated large-circle producer is claimed. START -> ATTACK; ATTACK with>1 live near ->WAITING; WAITING after10 copies nearbyKnights[1] formation/progress (query order, not a proven leader lookup), else START. Broadcast does not reset an already charging member. Local lists/goal order, simultaneous transitions and reload mean no globally guaranteed exclusive attacker.',
      'knight_final_survivor': 'With nearby list size1 at ATTACK end, code first randomly creates sword/axe/pick, THEN switchToFormation(ATTACK_PLAYER_START) calls updateMyNumber. Since there are no OTHER living Knights, nums.isEmpty => setNumber(0), which immediately replaces chosen weapon with sword. Final native survivor therefore reenters sword role; do NOT claim lasting random weapon cycling. A freshly solitary Knight also leaves totalKnownKnights=Integer.MIN_VALUE in that empty-neighbor branch, causing customServerAiStep to retry updateMyNumber each time and reset sword; this field is not an ammunition/shared-health resource. Losses can change surviving weapon roles through renumbering. No regeneration or HP transfer after deaths.',
      'knight_motion_home': 'NoClipMoveControl adds normalized displacement*0.1*speedModifier when courseChangeCooldown postdecrements<=0; resets by adding randInt5+2 to the decremented counter. No collision-clearance path test, stop-near-target epsilon or zero-distance division guard. Formation movement periodically makes noPhysics false at progress multiples20; otherwise passes blocks. travel applies water drag.8/lava.5/air or ground-friction*.91, without normal gravity; checkFallDamage empty and onClimbable false. Actual incoming fall-tag immunity is separately native entity tag. Home defaults to current block if null, radius30 strict valid-dimension block distanceSquared<900. START goal captures target OLD coordinates to BlockPos if SELF in home, otherwise home; does not require target in home. Sword attack aims at stored lower-corner chargePos; axe/pick hover. No combat teleport. Circle radius2.5/8.5 angle=progress*2 degrees with sign plus60*number; Y=homeY+cos(progress/7+number). Axis lane=number*3-7.5, sweep=-7 for first60 then -7+(progress-60)/120*14 with sign; supplied code uses lane on X for alongX and sweep on Z. Hover uses old XZ, if distance>8.5 destination is home+(home-old)/distance*8.5 (opposite side); loiter=home XZ. These are real control changes, not renderer animation. Shared BaseTFBoss lavaHurt ignites5 seconds, requests ownerless minecraft:lava4, and on true removes exact lava blocks in BB.inflate9 without a grief/helper check; not fire immunity and not a teleport. Native target selector is nearest Player(false mustSee); no retaliation goal or bespoke home admission gate.',
      'knight_defense_guard': 'Knight.hurt first calls native isDamageSourceBlocked and returns false with sound if true, BEFORE superclass invulnerability/incoming/shield damage pipeline. This branch does not damage shield, dispatch LivingShieldBlockEvent or blockedByShield/axe-disable callbacks. Actual guard requires native blocking item+warmup>=5+facing/source position, no shield bypass and no piercing-arrow exemption failure. Native Hard sixth Knight is the proven offhand-shield producer. PhantomWatch goal: live target; if offhand instanceof ShieldItem, formation!=ATTACK_PLAYER_ATTACK and private isGuard =>startUsing OFFHAND, else stop. Counter increments while guardCoolDownTime<=180, reaching181 then flips off; off phase decrements to0 then flips on. Formation can suppress use while counter still runs. Timers are goal calls and pause without live target; no health/enrage gate. Item KnightmetalShield only extends native shield abilities/repair/durability1024, no damaging spikes. Outside early block, Knight.isInvulnerableTo rejects exact IN_WALL or superclass; own rule has no bypass-invulnerability exemption. Normal projectiles/explosions/magic/HP requests otherwise admitted under normal rules; no noncharging invulnerability. noPhysics and visually absent body are not damage immunity. Fall-damage-immune tag and empty fall callback both preserved. Skeletons membership gives native undead potion inversion/Poison-Regeneration immunity and boss freeze buildup exclusion, not universal magic immunity. Not fireproof. Armor state and standard hurt cooldown/Resistance/protection/absorption remain; no cap or fresh iframe override.',
      'knight_knockback_death_reload': 'Knight overrides knockback: ignores supplied strength and native KR/hook method, sets impulse, halves current XYZ motion, adds fixed horizontal -ratio/sqrt(xRatio^2+zRatio^2)*.2 and Y+.2, caps Y at.4. There is NO zero-direction guard, so (0,0) produces undefined/NaN horizontal arithmetic; no runtime consequence fabricated. Ordinary native collision push still depends on noPhysics separately. At HP0 native dead damage rejection remains. Base death tick increments; Knight removal requires deathTime>=88 AND no nearby living Knights. At>=18 size set0; corpse can wait while others live, not share their HP. hasYetToDisappear controls initial rise .015 and rendering; last permitted postmortem resets nearby dead Knights deathTime1 and syncs packet, then IT_IS_OVER=true. No resurrection. MobLoot=false skips that reset/renumber postmortem; eventual88/no-live removal still governs. Peaceful spawner/discard and ordinary BaseTFBoss restrictions remain. NBT saves TotalKnownKnights, MyNumber, Formation, TicksProgress, IsItOver plus native HP/equipment/home. Read calls setNumber (replaces weapon), private switchToFormationByNumber (NO setChargingAtPlayer), then restores ticks; FLAG_CHARGING and transient +/-7/armor modifiers are NOT saved/restored here. Constructor defaults false/HOVER/noPhysics; on reload saved attack formation can initially run with inactive dimensions/no charge boost and absent inactive armor modifier until normal switchToFormation reconciles state. chargePos not saved, home setter initializes it to home; watch/guard counters restart. No universal immediate state reconstruction claim.'
    }
    effects, paths = [], []
    def add(owner, key, title, classification, keys, classes, numerical, binary, vanilla, alternates):
        eid = f'twilightforest:{owner}_{key}'
        effects.append(dict(id=eid,mod_key='twilightforest',owner=owner,display_name=title,inspection_status='DRAFT',subsection_status='REVIEWED',primary_classification=classification,classification_provisional=False,actual_behavior=[facts[k] for k in keys],components=[dict(primitive=key.upper(),formula='; '.join(facts[k] for k in keys),numerical_parameters=numerical,binary_parameters=binary,vanilla_relation=vanilla)],implementation=native_refs(*classes),primary_test_source='Native '+owner+' boss-spawner encounter; use the saved path setup and controls',alternate_sources=alternates,delivery_paths=[],registry_ids=[],pending=['Whole Twilight semantic closure and final promotion only; this boss subsection is reviewed.'],unresolved_ambiguities=None))
        return eid
    mm=add('minoshroom','axing','Axing melee and Minotaur axe sprint modifier','VANILLA_LIKE_EXTENDED',['minoshroom_attributes_equipment','minoshroom_melee','minoshroom_sprint_bonus','minoshroom_axe_shield','minoshroom_defense_lifecycle'],['entity/boss/Minoshroom','entity/monster/Minotaur','util/entities/EntityUtil','events/ToolEvents','item/MinotaurAxeItem','entity/boss/BaseTFBoss'],{'base_attack':2,'diamond_axe_add':9,'sprint_incoming_add':7,'native_player_shield_cooldown':100,'melee_cooldown':20},['native melee admission','direct Living/sprint/item for bonus','true for helper callbacks'],'Mob-like damage/enchantment pipeline with custom source, conditional incoming add and self-attribution discrepancy; ordinary axe block behavior is inherited.',['Native Player sprinting with gold/diamond Minotaur axe: same event bonus, Player source/callbacks differ.','Native Minotaur with actual Minotaur axe equipment: axing helper and sprint hook; plain golden axe fails bonus item gate.'])
    ms=add('minoshroom','slam','Ground slam damage and launch','CUSTOM_DAMAGE',['minoshroom_slam'],['entity/ai/goal/GroundAttackGoal','entity/boss/Minoshroom'],{'acquisition_distance_squared':[2,9],'windup':[30,59],'cooldown':[200,399],'aabb_xz':7.5,'aabb_y':3,'attack_factor':.5,'push_y':.23},['grounded Player recipient','no impact LOS check','push before hurt'],'Native hurt API in custom armor/shield-bypassing area source; independent additive velocity.',['No alternate producer of this GroundAttackGoal is registered in the inspected callers.'])
    mc=add('minoshroom','rush','Charge delivery and sprint state','CUSTOM_CONTROL',['minoshroom_charge'],['entity/ai/goal/ChargeAttackGoal','entity/boss/Minoshroom'],{'distance_squared':[25,73],'windup':[15,44],'speed_parameter':1.5,'sprint_multiplier':1.3,'overshoot':2.1,'contact_squared':5},['target/onGround/LOS/random','one attempted hit per run'],'Native navigation/sprinting in custom snapshot/one-attempt delivery.',['Minotaur ChargeAttackGoal: canBreak=false, rangeSquared16..64 and width-derived hit range; not equivalent boss terrain or geometry.'])
    mt=add('minoshroom','terrain','Charge obstacle destruction','CUSTOM_CONTROL',['minoshroom_terrain'],['entity/ai/goal/ChargeAttackGoal','util/entities/EntityUtil','entity/boss/BaseTFBoss'],{'lava_cleanup_inflate':9,'xz_padding':.75,'max_y_padding':.15,'hardness':[0,50]},['post windup','grief/loaded/helper/no BE'],'Native block destruction changes delivery; no direct damage.',['None for exact boss canBreak=true path.'])
    km=add('knight_phantom','haunt','Haunt melee and Knightmetal weapon predicates','VANILLA_LIKE_EXTENDED',['knight_melee_weapon_bonus'],['entity/boss/KnightPhantom','entity/ai/goal/PhantomWatchAndAttackGoal','util/entities/EntityUtil','events/ToolEvents','entity/monster/Wraith'],{'attack_distance_exclusive':2,'counter_reset':20,'weapon_bonus_max':2},['LOS/live/vertical overlap','direct Living/current weapon/recipient armor'],'Mob-like custom magic-tagged source retains armor; incoming weapon predicates and helper self-attribution extend delivery.',['Native Player knightmetal sword/pick/axe: same event modifier, different source/Player callbacks.','Wraith.doHurtTarget is an alternate HAUNT caller: attribute request followed by super.doHurtTarget mob_attack, not equivalent to Knight helper; full Wraith review remains pending.'])
    kp=add('knight_phantom','thrown_weapon','Thrown axe and pick lifecycle','CUSTOM_DAMAGE',['knight_projectile_launch','knight_projectile_source_hit','knight_projectile_reflection_persistence'],['entity/ai/goal/PhantomThrowWeaponGoal','entity/projectile/ThrownWep','entity/projectile/TFThrowable','init/TFDamageTypes','events/EntityEvents'],{'axe_damage':6,'pick_damage':3,'axe_speed':.75,'pick_speed':.5,'axe_gravity':.001,'pick_gravity':.015,'picks':8,'progress_modulus':4,'pick_radius':1},['attack formation/weapon role','native impact admission','not Knight/not owner','server'],'Native throwable physics; custom damage with deliberately preserved ownerless factory identity and unsaved payload.',['Native TF timed shield parry changes projectile owner but not damage attribution.','Native projectile save/load preserves owner but changes unsaved pick payload into default axe6.'])
    kg=add('knight_phantom','formation','Local formation and attack coordination','CUSTOM_CONTROL',['knight_group_identity','knight_formation_schedule','knight_final_survivor','knight_knockback_death_reload'],['entity/boss/KnightPhantom','entity/boss/KnightPhantom$Formation','entity/ai/goal/PhantomUpdateFormationAndMoveGoal','block/entity/spawner/KnightPhantomSpawnerBlockEntity'],{'native_count':6,'query_inflate':64,'start_duration':50,'attack_duration':50,'waiting_duration':10,'death_small':18,'death_min':88},['local live query includes self','lowest number','random selection only when nobody charging','postmortem depends on doMobLoot'],'Custom per-entity coordinated control, no shared HP/ammo/resource pool.',['Native solitary spawn and final survivor are materially distinct from native six-spawner formation.'])
    ka=add('knight_phantom','charged_attributes','Charging attack/armor/size tradeoff','VANILLA_LIKE_EXTENDED',['knight_equipment_attributes'],['entity/boss/KnightPhantom','init/TFItems','init/TFArmorMaterials','util/TFToolMaterials','item/PhantomArmorItem'],{'hp':35,'base_attack':1,'charged_attack_add':7,'inactive_armor_multiplier':5,'armor_clamp':30,'equipped_armor':11,'toughness':5,'inactive_dimensions':[1.25,2.5],'charged_dimensions':[1.75,4]},['START or ATTACK charging flag','native equipment modifier timing'],'Native attributes/dimensions with custom formation toggle; ordinary armor calculations, no invulnerability.',['Saved/reloaded native Knight needs separate state-restoration control.'])
    kd=add('knight_phantom','guard','Timed guard and damage admission','BINARY_MECHANIC',['knight_defense_guard'],['entity/boss/KnightPhantom','entity/ai/goal/PhantomWatchAndAttackGoal','item/KnightmetalShieldItem','block/entity/spawner/KnightPhantomSpawnerBlockEntity'],{'hard_shield_index':5,'guard_counter_threshold':180,'blocking_warmup':5},['real offhand ShieldItem','live target/private guard','not ATTACK_PLAYER_ATTACK','native directional block'],'Early TF rejection precedes normal shield durability/events; other immunity is exact IN_WALL or inherited.',['Hard native sixth Knight; spawn-egg Knight does not automatically get that shield.'])
    kf=add('knight_phantom','flight','Formation flight and knockback','CUSTOM_CONTROL',['knight_motion_home'],['entity/boss/KnightPhantom','entity/ai/control/NoClipMoveControl','entity/ai/goal/PhantomAttackStartGoal','entity/ai/goal/PhantomUpdateFormationAndMoveGoal','entity/boss/BaseTFBoss','util/entities/EntityUtil'],{'lava_cleanup_inflate':9,'small_radius':2.5,'large_radius':8.5,'home_radius':30,'acceleration':.1,'charged_speed_parameter':2,'physics_modulus':20,'fixed_knockback':.2},['native target/home/state','periodic collision','sword versus throwing role'],'Custom motion/no-gravity/noPhysics scheduling, not phasing damage immunity.',['Native in-home/out-of-home target pursuit and reload home-based charge point.'])
    def path(owner,key,label,title,factkeys,ids,classes,controls):
        pid=f'twilightforest:{owner}_path:{key}'
        paths.append(dict(id=pid,mod_key='twilightforest',owner=owner,status='DRAFT',subsection_status='REVIEWED',labels=label,source=title,native_delivery=' '.join(facts[k] for k in factkeys),setup=title+'; use real native spawning/equipment/admission, never fabricated DamageSource or direct HP writes.',effect_ids=ids,implementation=native_refs(*classes),future_controls=controls))
        for e in effects:
            if e['id'] in ids:e['delivery_paths'].append(pid)
    m='minoshroom';k='knight_phantom'
    path(m,'lava_recovery',['BOSS_ATTACK','ENVIRONMENT'],'Minoshroom native lava contact and accepted cleanup',['minoshroom_defense_lifecycle'],[mt],['entity/boss/BaseTFBoss','util/entities/EntityUtil'],['ownerless minecraft:lava4','true vs rejected hurt','BB.inflate9 exact lava only','no mobGriefing gate'])
    path(k,'lava_recovery',['BOSS_ATTACK','ENVIRONMENT'],'Knight native lava contact and accepted cleanup',['knight_motion_home'],[kf],['entity/boss/BaseTFBoss','util/entities/EntityUtil'],['ownerless minecraft:lava4','true vs rejected hurt','BB.inflate9 exact lava only','no fire immunity'])
    path(m,'melee',['BOSS_ATTACK','MELEE'],'Native equipped Minoshroom ordinary melee',['minoshroom_melee'],[mm],['entity/boss/Minoshroom'],['settled attack11 vs enchanted','normal LOS/reach','true/false vs HP','source identity and self lastHurtMob'])
    path(m,'charge_hit',['BOSS_ATTACK','MELEE'],'Native charge including a windup hit',['minoshroom_charge','minoshroom_sprint_bonus'],[mm,mc],['entity/ai/goal/ChargeAttackGoal','events/ToolEvents'],['range25..73','one rejected attempt still spent','Player difficulty before+7','interruption clears sprint'])
    path(m,'slam',['BOSS_ATTACK','AOE'],'Native GroundAttackGoal against grounded Players',['minoshroom_slam'],[ms],['entity/ai/goal/GroundAttackGoal'],['AABB corners/height vs radius','airborne excluded','Player only','armor and shield bypass; Resistance remains'])
    path(m,'slam_rejected',['BOSS_ATTACK','AOE'],'Slam against native invulnerable or cooldown-rejecting Player',['minoshroom_slam'],[ms],['entity/ai/goal/GroundAttackGoal'],['push .23 before rejected hurt','no successful-hit callback','no direct HP subtraction'])
    path(m,'charge_terrain',['BOSS_ATTACK','ENVIRONMENT'],'Native canBreak charge through permitted terrain',['minoshroom_terrain'],[mc,mt],['entity/ai/goal/ChargeAttackGoal','util/entities/EntityUtil'],['mobGriefing/event veto','all block entities excluded','hardness50 boundary','loaded region'])
    path(m,'minotaur_alternate',['MOB_ATTACK','MELEE'],'Native Minotaur charge with actual gold Minotaur axe',['minoshroom_sprint_bonus'],[mm,mc],['entity/monster/Minotaur','entity/ai/goal/ChargeAttackGoal'],['plain golden axe negative control','range16..64','canBreakfalse','gold-tier equipped attack differs'])
    path(m,'player_axe',['MELEE','ACTIVE_ITEM'],'Native sprinting Player with gold/diamond Minotaur axe',['minoshroom_sprint_bonus','minoshroom_axe_shield'],[mm],['events/ToolEvents','item/MinotaurAxeItem'],['player_attack identity','native Player attack strength and durability','sprint state at incoming hook','shield false can disable100'])
    path(m,'incoming_home',['PROJECTILE','MELEE','ENVIRONMENT'],'Native incoming sources inside/outside Minoshroom home',['minoshroom_defense_lifecycle'],[mm],['entity/boss/Minoshroom','entity/boss/BaseTFBoss','entity/EnforcedHomePoint'],['ordinary arrow/explosion admitted subject to mitigation','home is navigation only','source owner position not special gate'])
    path(m,'equipment',['BOSS_ATTACK','MELEE'],'Finalized Minoshroom equipment and shield callback controls',['minoshroom_attributes_equipment','minoshroom_axe_shield'],[mm],['entity/boss/Minoshroom','item/MinotaurAxeItem'],['native random armor/enchantments','attributes settled','no mob item hurtEnemy wear','native Player100tick shield disable'])
    path(m,'lifecycle',['BOSS_ATTACK','OTHER'],'Native Minoshroom interruption/save-load/defeat',['minoshroom_defense_lifecycle','minoshroom_slam'],[mm,ms,mc],['entity/boss/Minoshroom','entity/ai/goal/GroundAttackGoal','entity/boss/BaseTFBoss','block/entity/spawner/MinoshroomSpawnerBlockEntity'],['no HP-phase/regen','ground flag interruption','goal timers not persisted','native20 death; Peaceful restoration'])
    for weapon in ['sword','axe','pick']:
        path(k,'melee_'+weapon,['BOSS_ATTACK','MELEE'],'Native numbered '+weapon+' Knight melee',['knight_melee_weapon_bonus','knight_equipment_attributes'],[km,ka],['entity/boss/KnightPhantom','events/ToolEvents'],['inactive/charged settled attributes','armorValue and0/.25/.5/1 cover','axiom: axe branch uses original, sword/pick current damage','native LOS/range cadence'])
    path(k,'throw_axe',['BOSS_ATTACK','PROJECTILE'],'Native axe Knight attack formation',['knight_projectile_launch','knight_projectile_source_hit'],[kp,kg],['entity/ai/goal/PhantomThrowWeaponGoal','entity/projectile/ThrownWep'],['6 ownerless source','speed.75/gravity.001','no enchantment/weapon bonus','armor/projectile protection'])
    path(k,'throw_picks',['BOSS_ATTACK','PROJECTILE','AOE'],'Native pick Knight eight-way volley',['knight_projectile_launch','knight_projectile_source_hit'],[kp,kg],['entity/ai/goal/PhantomThrowWeaponGoal','entity/projectile/ThrownWep'],['8 at45 degrees; damage3 each','speed.5/gravity.015','shared recipient hurt cooldown','no guaranteed multiplied HP'])
    path(k,'throw_collision',['PROJECTILE'],'Native thrown weapon hits Knight/owner/other entity or block',['knight_projectile_source_hit'],[kp,kd],['entity/projectile/ThrownWep'],['ANY Knight and exact owner excluded','excluded collision still discard','hurt false still discard','impact cancellation/deflection may prevent callback'])
    path(k,'throw_parry',['PROJECTILE','ACTIVE_ITEM'],'Native timed shield parry of thrown weapon',['knight_projectile_reflection_persistence'],[kp,kd],['entity/projectile/ThrownWep','events/EntityEvents'],['native5..40 use window','owner transfer but damage remains ownerless','reflected throw cannot hurt Knight','ordinary Player melee is not parry'])
    path(k,'throw_reload',['PROJECTILE'],'Native saved/reloaded thrown pick',['knight_projectile_reflection_persistence'],[kp],['entity/projectile/ThrownWep','entity/projectile/TFThrowable'],['owner persisted','unsaved item/damage/gravity default','post-load thrown_axe6 vs pre-load pick3'])
    path(k,'formation_group',['BOSS_ATTACK','OTHER'],'Native six-Knight spawner encounter',['knight_group_identity','knight_formation_schedule'],[kg,ka,kf],['entity/boss/KnightPhantom','entity/ai/goal/PhantomUpdateFormationAndMoveGoal','block/entity/spawner/KnightPhantomSpawnerBlockEntity'],['query includes self','nearby encounters merge','random not rotating turn','query index1 not guaranteed leader','no shared HP'])
    path(k,'singleton',['BOSS_ATTACK','OTHER'],'Native last survivor and solitary native spawn',['knight_final_survivor'],[kg,ka],['entity/boss/KnightPhantom','entity/ai/goal/PhantomUpdateFormationAndMoveGoal'],['random weapon overwritten by setNumber0','solitary totalKnown sentinel','no regeneration'])
    path(k,'flight_home',['BOSS_ATTACK','OTHER'],'Native formation orbit/traverse/target charge',['knight_motion_home','knight_knockback_death_reload'],[kf,kg],['entity/boss/KnightPhantom','entity/ai/control/NoClipMoveControl','entity/ai/goal/PhantomAttackStartGoal'],['self home rather than target home','periodic noPhysicsfalse','no teleport or damage immunity','zero-direction knockback arithmetic'])
    path(k,'hard_guard',['BOSS_ATTACK','ACTIVE_ITEM'],'Native Hard sixth Knight with shield',['knight_defense_guard'],[kd],['entity/ai/goal/PhantomWatchAndAttackGoal','entity/boss/KnightPhantom','block/entity/spawner/KnightPhantomSpawnerBlockEntity'],['blocking warmup/facing/bypass','early false skips incoming/durability/disable callback','guard counters vs actual use','ownerless thrown source vs timed parry'])
    path(k,'incoming',['MELEE','PROJECTILE','ENVIRONMENT'],'Native charged/inactive Knight receiving genuine damage',['knight_defense_guard','knight_equipment_attributes'],[kd,ka],['entity/boss/KnightPhantom'],['armor30 vs11,toughness5','normal projectile/explosion','IN_WALL/fall exemptions separate','undead Healing/Harming','true hurt vs HP'])
    path(k,'state_reload',['BOSS_ATTACK','OTHER'],'Native saved/reloaded Knight formation',['knight_knockback_death_reload'],[kg,ka,kd],['entity/boss/KnightPhantom'],['saved formation/progress vs unsaved flag/transient modifiers','setNumber overwrites weapon','chargePos restored to home','next normal transition reconciliation'])
    path(k,'group_death',['BOSS_ATTACK','OTHER'],'Native Knight deaths and final encounter cleanup',['knight_group_identity','knight_knockback_death_reload'],[kg,ka],['entity/boss/KnightPhantom','entity/boss/BaseTFBoss'],['doMobLoot true/false postmortem','number reassignment/weapon replacement','corpse wait not extra HP','18 size0,88 and no live neighbors'])
    path(k,'player_tools',['MELEE','ACTIVE_ITEM'],'Native Player knightmetal sword/pick/axe attacks',['knight_melee_weapon_bonus'],[km],['events/ToolEvents','item/KnightmetalSwordItem','item/KnightmetalPickItem','item/KnightmetalAxeItem'],['direct Living','target armor/cover cases','source remains player_attack','Player wear/post callbacks; no new source fabricated'])

    # Merge scoped raw/TF tag contributions, including transitive bypasses_shield.
    tags={}
    for r in read_json(OUT/'vanilla-evidence/royalvariations.json')['resources']:
        if '/tags/damage_type/' in r['entry'] and 'data' in r:
            tags[r['entry'].split('/')[1]+':'+r['entry'].split('/tags/damage_type/')[1][:-5]]=list(r['data']['values'])
    resources=read_json(WORK/'twilightforest/resources.json')
    for name,v in resources.items():
        if '/tags/damage_type/' in name:
            tid=name.split('/')[1]+':'+name.split('/tags/damage_type/')[1][:-5]
            tags.setdefault(tid,[]).extend(v['data']['values'])
    def values(tag,seen=()):
        if tag in seen:return set()
        out=set()
        for item in tags.get(tag,[]):
            item=item['id'] if isinstance(item,dict) else item
            out.update(values(item[1:],seen+(tag,)) if item.startswith('#') else [item])
        return out
    profiles=[]
    for name,amount,callers,identity,mitigation in [
      ('axing','EnchantmentHelper.modifyDamage(effective attack); Minoshroom settled11; incoming sprint bonus+7 AFTER native Player difficulty scaling.', [('entity/boss/Minoshroom','doHurtTarget'),('entity/monster/Minotaur','doHurtTarget')],'direct=causing=attacker Living','Normal armor, shield, Resistance, protection, absorption, cooldown; physical, not projectile.'),
      ('slam','effective attack*.5; settled5.5; lift .23 independent before hurt.', [('entity/ai/goal/GroundAttackGoal','tick')],'direct=causing=Minoshroom','Bypasses armor and transitively shield. NO_ANGER, avoids Guardian thorns; still Resistance/protection/absorption/cooldown; not explosion or projectile.'),
      ('haunt','Knight effective attack1 + weapon6/9/4 + charged7, enchantment-modified; incoming Knightmetal bonus separately. Wraith alternate requests its own attribute then separate super mob_attack.', [('entity/boss/KnightPhantom','doHurtTarget'),('entity/monster/Wraith','doHurtTarget')],'direct=causing=attacker Living','Magic-tagged, ordinary armor/shield/Resistance/protection/absorption/cooldown; no implicit magic armor bypass.'),
      ('thrown_axe','6; reloaded unsaved pick also defaults6.', [('entity/projectile/ThrownWep','onHitEntity')],'direct=null; causing=null; no source position, despite retained projectile owner','Projectile/physical; normal armor/projectile protection/Resistance/absorption/cooldown; native directional shield lacks source position; no entity-based Player difficulty scaling.'),
      ('thrown_pickaxe','3 from native eight-pick launch.', [('entity/projectile/ThrownWep','onHitEntity')],'direct=null; causing=null; no source position, despite retained projectile owner','Same ordinary mitigation as thrown_axe; independent attempts share recipient cooldown, not guaranteed8x damage.')]:
        rid='twilightforest:'+name
        profiles.append(dict(type=rid,status='USED',callers=[dict(entry='twilightforest/'+c+'.class',method=m) for c,m in callers],amount=amount,direct_and_causing_entities=identity,tags=sorted(t for t in tags if rid in values(t)),declaration=resources[f'data/twilightforest/damage_type/{name}.json']['data'],mitigation=mitigation,difficulty='Declared WHEN_CAUSED_BY_LIVING_NON_PLAYER. Entity-owned axing/slam/haunt scale Player requests Peaceful0,Easy min(x/2+1,x),Normalx,Hard1.5x before Living incoming hooks; ownerless thrown sources do not qualify. No scaling on nonPlayer recipients.'))
    comparison=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','vanilla-evidence/royalvariations.json','vanilla-evidence/twilight-lich-tags.json','vanilla-evidence/twilight-naga-data.json','vanilla-evidence/twilight-naga.json','reference-evidence/twilight-naga-244.json','reference-evidence/twilight-frosted-244.json','reference-evidence/twilight-lich-244.json','reference-evidence/cult-loader-244.json','reference-evidence/royal-loader-244.json','config-evidence/twilightforest-common.json']
    section=dict(schema='tno.external_effects.semantic_section.v1',baseline=BASELINE,mod_key='twilightforest',checkpoint=CP,starting_sha=START,status='REVIEWED_SUBSET_NOT_MOD_COMPLETE',subsection_decision=DECISION,semantic_coverage_complete=False,promoted_to_catalog=False,effects=effects,paths=paths,damage_profiles=profiles,semantic_closure=facts,
      boss_states={'minoshroom':'SEMANTIC_REVIEW_COMPLETE','knight_phantom':'SEMANTIC_REVIEW_COMPLETE'},closure_checklist={x:True for x in ['attacks','defenses','equipment_callbacks','group_coordination','state_persistence','source_delivery','damage_types','vanilla_classification','exclusions']},
      comparison_evidence=[dict(evidence_file=p,sha256=sha256(OUT/p)) for p in comparison],source_registration_evidence=native_refs('init/TFEntities','init/TFItems','events/RegistrationEvents','events/ToolEvents','block/entity/spawner/MinoshroomSpawnerBlockEntity','block/entity/spawner/KnightPhantomSpawnerBlockEntity'),
      exclusions=['Ordinary melee scheduling, ordinary item attributes/durability and native axe shield disabling are not additional Twilight custom packages; exact extensions are identified in the saved packages.','Ground slam charge interpolation, rush walk animation, Phantom smoke/equipment render visibility, sounds, particles and bossbars are not damage sources or immunity.','Loot/trophies/conquest and chest transfer are excluded as effects. Death-dependent renumbering, corpse lifetime and the doMobLoot guard are retained because they alter combat state.','Ordinary home navigation is not a source immunity gate. Actual charge terrain pressure and spectral formation movement are retained.','No thrown block is created by either reviewed boss or its goals. ThrownBlock uses its own caller/class, not inferred from a registry name. Knightmetal shield has no damage callback; the knightmetal DamageType belongs to separate KnightmetalBlock contact code, not this shield. Those separate mechanics remain outside this subsection.','Wraith alternate HAUNT method is pinned only for source disposition; its complete entity review is pending, not silently marked complete.'],
      damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=4,new_used_profiles=5,reviewed_profiles_after=9,remaining_profiles=31,remaining_disposition='Unfinished caller semantics, not unused; includes unrelated thrown_block and knightmetal mechanics. No DECLARED_BUT_NO_COMBAT_CALLER_PROVEN invented.'),
      compatibility_scope='Installed native Twilight4.8.3345 + raw Minecraft1.21.1 + exact NeoForge21.1.244. Reuse protected four compat scans; no direct Twilight name hits there, generic owner/recipient/event hooks remain conditional. Early Knight guard skips later events, ownerless throws do not acquire owner-based bonuses. No pack-wide guarantee or compatibility fixes.',
      fixture_groups=['Native Minoshroom boss-spawner, equipped/enchantment/armor controls; melee, sprint charge, grounded/airborne slam, legitimate shields and home/terrain predicates.','Native Minotaur equipment variants and Player Minotaur axe alternate event producers.','Native six-Knight spawner (Hard shield included), all three roles and attack states; nearby-group/survivor/death controls.','Native thrown axe/pick collision, mitigation, timed parry and save/load controls; projectile owner versus DamageSource entities separately.','Native Knight state save/load, guard, home flight, exposed/projectile/explosion/undead-potion admission controls; native Player Knightmetal tool alternate hooks.'],
      counts=dict(mechanic_packages=len(effects),delivery_cases=len(paths),classification_totals=dict(Counter(e['primary_classification'] for e in effects)),per_boss={owner:dict(packages=sum(e['owner']==owner for e in effects),paths=sum(p['owner']==owner for p in paths)) for owner in [m,k]},review_required=0,new_custom_types_resolved=5),exact_next_task=NEXT,**boundary_flags())
    write_json(OUT/'semantic-sections/twilightforest-minoshroom-knight.json',section)
    prior=read_json(OUT/'partial-drafts/twilightforest-r2f4-partial.json');draft=deepcopy(prior);draft.update(checkpoint=CP,starting_sha=START,effects=prior['effects']+effects,paths=prior['paths']+paths)
    write_json(OUT/'partial-drafts/twilightforest-r2f5-partial.json',draft)
    review=read_json(OUT/'mod-reviews/twilightforest.json');review.update(checkpoint=CP,scope='Frosted, Lich, Naga, Minoshroom and Knight Phantom complete subsections; whole Twilight PARTIAL with zero final promotion.',draft_file='partial-drafts/twilightforest-r2f5-partial.json',notes_file='semantic-sections/twilightforest-minoshroom-knight.json',draft_mechanic_count=len(draft['effects']),draft_path_count=len(draft['paths']),exact_next_task=NEXT);write_json(OUT/'mod-reviews/twilightforest.json',review);refresh(CP)
    for f in ['effect-catalog.json','effect-sources.json','delivery-path-matrix.json','vanilla-comparison.json','behavior-primitives.json']:
        d=read_json(OUT/f);d.update(checkpoint=CP,unfinished_review=dict(mod_key='twilightforest',status='PARTIAL',draft_file=review['draft_file'],promoted_records=0));write_json(OUT/f,d)
    decision=read_json(OUT/'research-decision.json');decision.update(checkpoint=CP,minoshroom_knight_decision=DECISION,next_task=NEXT,save_mode=True,save_reason='New research stopped at68% five-hour usage to reserve full validation, commit and push capacity; Hydra and Ur-Ghast have not started.',recovery_minoshroom_knight=dict(local_start=START,live_remote_start=START,working_tree_start='CLEAN',divergence='0/0',newer_work=False,restarted_research=False));decision['checkpoints']['R2f4-naga-complete']=START;decision['checkpoints'][CP]='Self: exact SHA supplied after push/live verification.';write_json(OUT/'research-decision.json',decision)
    lines=['# R2f5 - '+DECISION,'','Installed Twilight4.8.3345 / Minecraft1.21.1 / NeoForge21.1.244. Static semantic research; no runtime tests. Prior three sections remain protected.','',f"{len(effects)} new packages / {len(paths)} delivery cases; combined Twilight {len(draft['effects'])}/{len(draft['paths'])}, PARTIAL, zero promoted. REVIEW_REQUIRED0.",'','## Native mechanics','']
    for name,value in facts.items():lines.extend(['### '+name.replace('_',' ').capitalize(),'',value,''])
    lines.extend(['## Packages','','| Package | Owner | Classification |','|---|---|---|'])
    for e in effects:lines.append('| '+e['display_name']+' | '+e['owner']+' | '+e['primary_classification']+' |')
    lines.extend(['','## Damage caller disposition','','| Type | Amount and caller behavior | Source entities |','|---|---|---|'])
    for p in profiles:lines.append('| '+p['type']+' | '+p['amount']+' | '+p['direct_and_causing_entities']+' |')
    lines.extend(['','All five types are USED. Nine of40 custom profiles now reviewed;31 remain unfinished. Sources, transitive tags, prerequisites, classifications, all28 delivery cases and alternate/native fixture controls are saved in [the machine-readable section](semantic-sections/twilightforest-minoshroom-knight.json). Requests and hurt returns are not measured HP loss.','','## Exclusions and future fixtures',''])
    lines+=['- '+x for x in section['exclusions']]+['']+['- '+x for x in section['fixture_groups']]
    lines.extend(['',section['compatibility_scope'],'','[Native witnesses](native-evidence/'+BATCH+'.json), [raw comparison](vanilla-evidence/'+BATCH+'.json), [exact loader](reference-evidence/'+BATCH+'-244.json), [integrity](twilightforest-minoshroom-knight-integrity.json), [full validation](r2f5-minoshroom-knight-validation.json).','','Exact next task: '+NEXT,'','Hydra and Ur-Ghast have not started. Protect this checkpoint, verify live SHA equality, then STOP.',''])
    (OUT/'twilightforest-minoshroom-knight-review.md').write_text('\n'.join(lines),encoding='utf-8')
    print(json.dumps(section['counts'],indent=2))


if __name__=='__main__':build()
