from catalog_common import *
from eternalstarlight_combat_common import save_section
START='12e4e62abb0b8d3ceb44456fa9b91d97f64e9935'
CP='R2h8a-combat-closure-complete';STEM='eternalstarlight-r2h8a-closure'
NEXT='R2h8b: deterministic ES package/path deduplication, whole-source disposition map, promotion to all five views/ledger, full validation and five tooling tests, push/live verify. Then Bosses Rise native combat foundation automatically while healthy.'
FACTS={
 'coverage':'Whole installed artifact inventory1384 classes;274 watched common/server combat/admission methods now have native method witnesses. All29 custom source-factory caller methods,31 damage-key references and38 custom-status reference methods remain protected in R2h1; all18 actual DamageTypes have reviewed caller families. Scans index semantic contracts and explicit exclusions, not proof that any witnessed class is automatically reviewed. Registries, nine effects, combat items/armor, creatures, AI, native projectiles, spells/crests, event bridges, mixins, environment and inherited hazard paths are accounted for. Full source disposition/promotion map is next, no runtime compatibility certification.',
 'dusk':'Server lit Dusk Light/Emitter activated face casts30block COLLIDER ray from face+.51; explicit always-passable tag wins, then always-unpassable tag, else HalfTransparentBlock passes. Beam stops at native hit, can activate receptor for5ticks and destroy tagged blocks. In beam AABB (transverse halfwidth.25), every Entity except ItemEntity gets setRemainingFireTicks(max(old,100)); no hurt, shouldHarm, owner or fireImmune test at writer. Emitter alwaysActivated refreshes5; ordinary/reinforced Light require receptor activation and FACING. Native Entity.baseTick fireImmune reduces timer4 without on_fire hurt; otherwise every20ticks when not lava requests ownerless on_fire1. Fire Resistance/native mitigation still matters. Scale only that final native fire hurt, never timer/range, and do not attribute beam to placer.',
 'alloy':'Server AlloyFurnace tick increments overheat while lit and either no cooling or litTicks%coolingEfficiency==0; unlit subtracts1 plus coolingEfficiency if cooling, clamp0..configured totalOverheatTicks. At threshold destroys furnace then Level.explode(null,null,null,center,configured explosionRadius,true,BLOCK,...). Native source factory yields ownerless explosion, no Player placer ownership, no custom ES type. Real damage/exposure/block admission and explosion events remain native. Radius/fuse/cooling and fire creation unscaled; each final native per-victim explosion hurt is sole Stage point, later placed fire keeps native fire scaling separately. Crafting/recipe/container details excluded.',
 'inherited_hazards':'Three actual vanilla MagmaBlock instances (Abyssal/Thermabyssal/Cryobyssal) inherit stepOn: Living and !isSteppingCarefully -> ownerless hot_floor1. No extra Frost Walker predicate in installed method; native downstream admission remains. TorreyaCampfire constructor damage1 inherits lit Living contact campfire1 independently of its already-reviewed status aura. No ice/cold source inferred from Cryobyssal name. Scale each final native hot_floor/campfire hurt once; reuse existing contact/fall packages on promotion where identical.',
 'native_movement':'LunarisCactusGelBlock extends SlimeBlock: nonsuppressed bounce fall multiplier0, reflectedY*1 Living/.8 other; careful/suppressed bounce delegates ordinary fall, low-|Y|<.1 noncareful step damps horizontal by.4+abs(Y)*.2. Separate from Gel item cleanse. ThermalSpringstone produces native upward bubble column; three Magma blocks downward, native bubble movement/air callback unchanged. AirSac Boots EntityMixin records bottomInWater during tick when isInWater AND bottom-center fluid is WATER; equipped boots getGravity returns0 under that cached condition. Does not confer fall/fire/drowning immunity or damage. Native fixed movement/admission receives no Stage multiplier.',
 'weapon_companions':'LivingEntityMixin.getKnockback adds1 when current weapon #hammers. UnrealiumCrossbow arrow independently halves LivingEntity.hurt knockback strength and AbstractArrow.doKnockback horizontal Vec3 scale. These are separate base-hit and successful-arrow enchantment knockback contributions, not two multipliers on one impulse; arrow vertical push.1 remains. Preserve native knockback resistance and rejected-hit gating. AbstractArrow mixin marks any ES-namespace CrossbowItem firedFromWeapon as shotFromCrossbow, WiltedCrossbow arrow water inertia.99, and ThrowableProjectile mixin treats WiltedPetal/EnergySpark as not in water for tick drag. No new HP source/Stage amount, but actual weapon/owner/water provenance is a future fixture.',
 'native_companion_control':'Stranghoul hirer contract admission requires Player hiring cooldown<=0, accepted hiring-food tag, adult, not already hired and targetnull. Native24000tick hire, persisted owner/count and cooldown; hirer hurt-by/hurt-target goals use changed timestamps and TargetingConditions.DEFAULT, then native Mob.setTarget. isAlliedTo accepts ordinary team OR any Stranghoul OR with hirer: hirer alliance, hirer itself, or OwnableEntity whose ownerUUID matches. Unhired Player prey additionally health ratio<.15; tagged prey excludes #stranghoul_cannot_hunt. Existing Seeds/Spear/Bow/native melee retain actual mob source, not hirer damage attribution. Native taming Moth target reset and previously resolved wantsToAttack stay in R2h4a; no repeated research or forced target bypass.',
 'native_supply_and_fire_delivery':'Galactic Quiver held-ammo fallback runs only when original held-projectile lookup is empty and shooterPlayer; choose first predicate-compatible stored ammo, copy and mark QUIVER_ARROW. Native useAmmo successful result with marker and ammoUse>0 consumes matching stored components; ES tick removes marker from pickup ammo/inventory. This supplies genuine existing projectile factories, no new damage/scaling; storage mechanics excluded. SaltpeterMatchbox is actual FlintAndSteelItem; registered dispenser uses BaseFireBlock placement or lights campfire/candle or native TntBlock.explode. BaseFireBlock mixin selects Abyssal/Amaramber fire by native support predicates (Amaramber later wins if both); genuine native ignition route to reviewed contact hazards. TearBomb TNT replacement remains prior native package, not a duplicate explosion implementation.',
 'short_exclusions':'Ordinary rendering/animation/sounds, crafting/acquisition, loot/progression/book UI, storage, crop/wood/weathering/worldgen and noncombat transport omitted. SoulitSpectator is timed camera/chunk-loading projectile, no hurt payload. EyeOfSeeking is navigation information; EthericEye surface teleport/resetFallDistance is ordinary self utility with no target/combat callback. GravityPickaxe item pickup, natural600tick item repair/Crescent repair, important-item invulnerability, food-item aging, respawn dimension, attachment sync and loot targeting are utility/persistence rather than new HP/status combat mechanics. StarfireBird successful player-caused hurt only changes trust. Passive Yeti/Grimstone/Ent/Ratlin/Rookfish/Lacewing exclusions remain; flight steering and Permafrost death velocity add no offensive payload. Eight registered spell callback stubs remain return-only, no imagined fire/ice attacks.',
 'compat_and_stage':'Scoped R2h1 explicit-name scan found zero direct ES/Tensura/L2 references; generic hooks/mixins remain runtime concerns. Every native source, effect admission, hurttrue dependency, owner and iframe policy is retained. Stage belongs at final admitted native numeric damage/heal boundary, never repeated on derived Numbness debt/Starfire fraction, attributes, count/radius or binary control. Runtime fixtures, resistance/nullification intersections and source-specific mitigation need later approval; no runtime, Stage, production, Phase6/7 changes.'
}

def save():
    defs=[('dusk_emitter','ENVIRONMENT','always-active emitter native fire counter'),('dusk_relay','ENVIRONMENT','receptor-lit normal/reinforced Light native fire counter'),('furnace','EXPLOSION','configured overheat -> ownerless native BLOCK explosion'),('magma','ENVIRONMENT','three native MagmaBlock hot_floor contacts'),('campfire','ENVIRONMENT','lit TorreyaCampfire inherited campfire contact'),('gel','ENVIRONMENT','Gel block native Slime fall/bounce/step'),('bubble','ENVIRONMENT','Springstone upward/Magma downward native bubble column'),('boots','ARMOR_PROC','AirSac Boots cached water-bottom gravity suppression'),('hammer','MELEE','native hammer +1 knockback'),('unrealium_kb','PROJECTILE','Unrealium arrow separate native hit and enchant knockback halves'),('water_physics','PROJECTILE','Wilted arrow/petal and EnergySpark native drag variants'),('hire_melee','MOB_ATTACK','hired/unhired Stranghoul native target melee'),('hire_ranged','MOB_ATTACK','hired/unhired native Seeds/Spear/Bow source'),('quiver','PROJECTILE','genuine stored ammo native factory fallback'),('matchbox','ACTIVE_ITEM','Player/dispenser native fire/TNT ignition')]
    paths=[dict(id='es:closure:'+n,labels=[l],native_path=p,runtime_variants=['native admission/source retained','no fabricated helper events or additional HP']) for n,l,p in defs];ids={n:p['id'] for (n,*_),p in zip(defs,paths)}
    def m(id,name,cl,point,keys):return dict(id='es:'+id,name=name,primary_classification=cl,tno_categories=['COMPOSITE','ADMISSION_GATED']+(['NUMERIC_SCALABLE'] if point else ['NO_STAGE_VALUE']),stage_scaling_needed=point is not None,single_scaling_point=point,stage_reason='Native control/eligibility/physics remains fixed; reused damage paths retain their already-reviewed final amount point.',delivery_paths=[ids[k] for k in keys])
    pk=[m('dusk_fire','Dusk beam native timed fire','VANILLA_LIKE_EXTENDED','Once at final native Entity.baseTick on_fire1 hurt; no beam/timer multiplier.',['dusk_emitter','dusk_relay']),m('alloy_explosion','Alloy Furnace native environmental explosion','VANILLA_DIRECT','Once per final native ownerless explosion hurt after native exposure/radius.',['furnace']),m('inherited_block_hp','Inherited Magma/TorreyaCampfire contact HP','VANILLA_DIRECT','Once at final native hot_floor1/campfire1 hurt.',['magma','campfire']),m('inherited_movement','Native Gel bounce and bubble movement','VANILLA_DIRECT',None,['gel','bubble']),m('airsac_buoyancy','AirSac Boots native gravity override','CUSTOM_CONTROL',None,['boots']),m('weapon_physics','Native weapon knockback and projectile-water companions','VANILLA_LIKE_EXTENDED',None,['hammer','unrealium_kb','water_physics']),m('hirer_admission','Stranghoul native hirer and prey targeting','CUSTOM_CONTROL',None,['hire_melee','hire_ranged']),m('native_supply_delivery','Native Quiver and ignition source prerequisites','VANILLA_COMPOSITE',None,['quiver','matchbox'])]
    d=dict(schema='tno.external_effects.es_closure.v1',checkpoint=CP,previous_checkpoint='R2h7b-creature-combat-complete',starting_sha=START,status='STATIC_COMBAT_CLOSURE_COMPLETE',scope='Final combat-significant source/admission gaps and brief noncombat exclusions; promotion remains next.',summary='Whole1384-class/274-method audit closes Dusk/Furnace/inherited hazards and remaining native source/physics prerequisites;18 custom source families retained.',facts=FACTS,mechanic_packages=pk,delivery_paths=paths,damage_types_newly_reviewed=[],unexecuted_future_fixtures=['Dusk_Emitter_vs_relay_LOS_passable_tags_item_exclusion_native_fire_immunity','Alloy_threshold_cooling_native_ownerless_explosion_fire_event_veto','Magma_crouch_hotfloor_immunity_Torreya_lit_contact_independent_aura','Gel_suppress_bounce_Bubble_drag_air_Boots_cached_gravity','Hammer_KB_Unrealium_two_distinct_impulses_KBR_rejected_hit','Wilted_arrow_inertia_Spark_Petal_water_drag_genuine_native','Stranghoul_hire_owner_team_preys_target_veto_melee_ranged_source_identity','Quiver_vs_held_inventory_native_ammo_factories_and_marker_consumption','Saltpeter_player_dispenser_TNT_Abyssal_Amaramber_native_fire_paths'],review_required=[],remaining_subsection_native_ambiguities=[],whole_combat_semantics_closed=True,exact_next_task=NEXT,references=['native-evidence/eternalstarlight-closure.json','eternalstarlight-combat-closure-census.json','reference-evidence/eternalstarlight-closure-244.json','vanilla-evidence/eternalstarlight-closure.json','reference-routing/eternalstarlight-closure.json','eternalstarlight-source-census.json','eternalstarlight-damage-tags.json','eternalstarlight-direct-compat-census.json','native-evidence/eternalstarlight-creatures.json','native-evidence/eternalstarlight-status-control.json','native-evidence/eternalstarlight-special-weapons.json'])
    save_section(d,STEM,'R2h8a — Eternal Starlight combat closure')
if __name__=='__main__':save()
