"""Reviewed modifier framework and non-movement Travellers gameplay contracts."""
from catalog_common import *
from collect_twilight_travellers_core import FULL,BATCH,T,M,R
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'authority':'Installed Twilight4.8.3345, raw Minecraft1.21.1 and exact NeoForge21.1.244, plus the installed service-registered nested TF ASM archive. Static research only, runtime tests0. This section closes modifier admission/crafting/removal, base equipment and non-movement defensive/resource payloads. Movement, belt/display/zoom and other ASM hooks remain pending. No compatibility implementation, HP/SHP simulation, Stage/production/Phase6/7 changes.',
      'registry':'TravellersModifier.CODEC dispatches through TFRegistries.TRAVELLERS_MODIFIER_TYPE; RegistrationEvents registers the synced datapack TRAVELLERS_MODIFIERS registry and cache invalidation reload listener. Manager caches found and missing keys; reload clears both. Native packaged data/twilightforest/twilight/travellers_modifiers/*.json, not tooltip prose, supplies defaults. Component modifiers test presence of their one component; entry modifiers test marker presence; transferable modifiers require marker plus payload component; builtin modifiers test component presence. Presence is not a checked equality to the packaged default value. Registry lookup absence returns false. No recipe slot-count or item-type check inside low-level addModifier; actual recipes enforce their own admission.',
      'activation':'TravellersModifier.isActive requires hasModifier, !spectator, and either !isTravellersArmorAndBroken(stack) or modifier key in ALWAYS_ACTIVE. The sole ALWAYS_ACTIVE key is AUTO_REPAIR. Broken means IS_TRAVELLERS_GEAR marker AND isDamageableItem AND damage>=maxDamage-1. Native isDamageableItem requires MAX_DAMAGE and DAMAGE and no UNBREAKABLE. Explicit-stack overload uses that supplied stack; no independent equipment-group validation or required gear marker for component activation. Normal callers below retrieve real HEAD/CHEST/LEGS/FEET stacks. Entity-only overload resolves exactly one armor slot from registry group; zero or multiple matching armor slots returns EMPTY, so ARMOR-wide Auto-Repair uses its explicit per-stack loop. Neither selected payloads nor activation manager query Curios inventory. No claim that another installed mod cannot redirect general equipment APIs.',
      'crafting':'Actual shaped/shapeless modifier recipes select the first TravellersModifiable input with getModifierSlots()>0; require countInsertableModifiers<slots, target modifier absent, and <=1 transferable data-provider ingredient; shaped pattern or exact shapeless ingredient count/matching must also pass. Assembly copies armor then tries transfer first and add second, returning EMPTY if neither works. Count includes registered Insertable and !isAbility present modifiers; builtin abilities do not consume a slot. Component addition writes its packaged value; nonbuiltin entry addition writes actual attribute entries plus marker; builtin entry addition writes marker only. Transfer searches Ingredient item arrays having any matching payload; sole provider uses its first stack payload, not a merge; >1 fails, absent provider falls back to default addition. Genuine recipes use actual input singleton ingredients. Gear/component state, damage, name and other copied components persist in outputs; no added DamageSource.',
      'removal':'AnvilUpdate cancels when BOTH input stacks have IS_TRAVELLERS_GEAR, including different gear items. Grindstone OnPlace with a live server: two marked gear inputs cancel; one marked gear with no insertable nonability modifier cancels; otherwise copy input and remove every present registered insertable nonability modifier, then use copied result. Component removal deletes component, nonbuiltin entry removal deletes matching attribute entries+marker, transfer removal deletes marker+payload; builtin abilities remain. OnTake returns contained swap-hotbar or item-display contents only from a unique matching marked input via ItemHandlerHelper.giveItemToPlayer, whose server overflow becomes a real ItemEntity with40-tick pickup delay. This is removal/resource behavior, not damage. Belt/display use payloads are reviewed next. Vest+Gloves merge accepts exactly one of each, vest without HAS_GLOVES, copies only vest and adds HAS_GLOVES; no new modifier slot or glove enchant/component merge. ItemCrafted advancement trigger is bookkeeping, not an additional buff.',
      'equipment':'Four durable pieces Goggles/Vest/Wings/Boots have3 insertable slots each, durability multiplier12 ->132/192/180/156, and actual armor attribute2/4/3/2 with toughness0/knockback resistance0. Material enchantability0. Gloves(CHEST) and Belt(LEGS) are nondurable, slots0, stack limit1. Their plain properties inherit native COMMON_ITEM_COMPONENTS.ATTRIBUTE_MODIFIERS=EMPTY; TF constructor stores that nonnull empty value BEFORE virtual getDefaultAttributeModifiers(), which then returns that same empty value. Thus native Gloves/Belt do NOT acquire the material chest4/legs3 armor merely by extending ArmorItem. The four main pieces explicitly seed their own armor entries; no doubled material armor. ItemAttributeModifiers/loader equipment pipeline applies actual entries. Base Vest also carries Swift Swim water-movement +1 and Boots step-height +.5; their full movement controls are deferred. Wings carries native high-jump component1; Goggles zoom .3, also deferred.',
      'equipment_predicates':'TravellersArmorItem.makesPiglinsNeutral returns true for exact Goggles item OR HAS_WINGS component, without broken/spectator/modifier-active check. Native PiglinAi.isWearingGold checks equipped armor/body stacks through the item hook; this affects that gold-clothing admission, not every aggression/retaliation rule. canWalkOnPowderedSnow is exact TravellersBoots item, again no broken check; native powder-snow collision eligibility remains. These callbacks are independent of disabled active modifiers. isEnchantable/isPrimaryItemFor/supportsEnchantment are false, isBookEnchantable true, isRepairable false. Native anvil still tests inherited ArmorItem.isValidRepairItem(TANNED_LEATHER) for material repair, independently of isRepairable; ordinary damage/cost/level/output checks remain. Two-gear anvil combination is separately canceled. Enchantment-book true alone does not overcome supportsEnchantment false for ordinary survival; native creative compatibility override remains. No HP/SHP or custom damage from equipping.',
      'durability':'Uncanceled ArmorHurtEvent: each marked gear stack whose damage+newArmorWear>=maxDamage gets new wear=maxDamage-currentDamage-1; else if sum>=maxDamage-1 and wearer ServerPlayer, play item-break sound. Native ArmorHurtEvent.setNewDamage does not clamp; TF has no extra max(0) for anomalous states. Native CommonHooks applies integer newDamage through stack.hurtAndBreak after uncanceled event, preserving enchant/durability/creative eligibility. This caps ordinary armor wear at last durability, not arbitrary stack destruction or all durability callers, and does not cancel/reduce incoming HP damage. Later registered setLastDamageArmorTime records current gameTime if ANY EquipmentSlot event newDamage>0, including other armor; zero wear does not refresh. No hurt-return/positive-HP requirement in this tracking handler. It records event wear, not a later guaranteed consumed durability amount.',
      'broken_attributes':'ItemAttributeModifierEvent handling runs only with nonnull ServerLifecycleHooks.currentServer and marked damageable gear. At damage>=max-1, if raw ATTRIBUTE_MODIFIERS component exists, union its entries with any STORED_BROKEN_ATTRIBUTES in LinkedHashSet, persist that union, and clear event modifiers. It does not erase raw component or stop unrelated enchantment attribute pass. At repaired damage<max-1, stored entries replace corresponding event entries, stored component is removed and event.build written back to raw ATTRIBUTE_MODIFIERS. ItemStack.getAttributeModifiers computes through CommonHooks on each retrieval; subsequent equipment refresh uses returned entries. Client-only tooltip environment lacking currentServer need not match server attribute suppression. Stored component is persistent/network-synchronized; no timer/HP/shield resource, no universal suppression of later other-mod listeners or separately installed transient modifiers.',
      'broken_removal':'Stored-broken attributes are a separate component that TravellersEntryModifier.removeModifier never edits. With a genuine broken Aquatic piece whose STORED_BROKEN_ATTRIBUTES already contains its oxygen/mining entries, grindstone removal copies the piece, clears the Aquatic marker/current entries but preserves that stored component. Native grindstone custom output is returned before ordinary vanilla computeResult. Subsequent legitimate Tanned Leather anvil repair can make damage<max-1; the next attribute event restores ALL saved entries without checking whether their marker/modifier was removed. Thus Aquatic attributes can return with no Aquatic marker. Removing all modifiers also removes Auto-Repair, so this sequence does not assume it remains available. This is a proven native component lifecycle, no patch or runtime exploit test; absence of marker does not prove absence of previously stored attributes.',
      'repair':'EntityTick.Post calls Auto-Repair only server-side for LivingEntity. Require gameTime-LAST_DAMAGE_ARMOR_TIME>200 strict; attachment defaults0 and serializes LONG. Iterate real armor slots; each requires probability component and explicit-stack active AUTO_REPAIR, which remains active when broken but not spectator. Independent per-piece roll: if adjustedProbability>random.nextFloat(), setDamageValue(max(oldDamage-1,0)). No XP/item consumption, heal(), HP write or DamageSource. No explicit isDamaged/isDamageable gate in loop. Base p=.001. If !canSeeSky use p; otherwise TF dimension TYPE ->1-(1-p)^1.5; other dimension daytime ->1-(1-p)^3; other nighttime ->p. Uses dimension type, sky visibility and day rather than brightness/weather. One repair point can leave max-1 broken state and restore attributes on subsequent native query. Not guaranteed periodic repair; component codec positive float has no upper probability clamp.',
      'dodge':'ProjectileImpactEvent must carry EntityHitResult whose recipient is LivingEntity. Read its current CHEST stack, active PERFECT_DODGE and nonnull probability; installed default.3. Client cancels immediately; server returns if probability<=random.nextFloat(), otherwise cancels and emits sound/particles. No owner/causing/direct-entity test, no DamageType/tag, damage amount, held shield, invulnerableTime, sight, boss or distance gate. It cancels that native impact event, not LivingHurt, and neither reflects/reassigns/discards projectile nor changes HP. Exact244 AbstractArrow/ThrowableProjectile call EventHooks before native impact callbacks; cancellation suppresses that impact, with remaining projectile motion/lifetime governed by its own caller. Cannot protect from arbitrary hurts or projectile implementations that do not post this event. Failed server roll uses unchanged native source, armor/shield/Resistance/protection/cooldown/eligibility.',
      'magnet':'ProjectileImpactEvent requires owner LivingEntity, BLOCK hit and projectile.tickCount<200, then active owner ARROW_MAGNETISM, AbstractArrow and !client. Player owner: if !hasInfiniteMaterials && pickup==ALLOWED, give getPickupItemStackOrigin() to player and mark inventory changed. Native method returns stored pickup stack (not newly generated generic arrow). Discard if ALLOWED, or CREATIVE_ONLY && player.isCreative; DISALLOWED stays, CREATIVE_ONLY survival stays. Creative ALLOWED discards without granting extra item. Nonplayer living owner discards eligible arrow without inventory return regardless pickup mode. Reads CURRENT owner chest at impact; shooting vest snapshot is not stored. No distance/line-of-sight/projectile DamageType/damage-success test. Full inventory uses native helper remainder drop. It does NOT cancel event; exact244 Arrow.tick has no removal recheck between EventHooks return and hitTargetOrDeflectSelf, so a discard here does not itself suppress already-selected block impact callbacks. No target HP damage or owner reassignment.',
      'allnight':'Active HEAD ALL_NIGHT_GOGGLES sets PlayerSpawnPhantomsEvent.Result.DENY. Native PhantomSpawner asks per non-spectator player and shouldSpawnPhantoms returns false for DENY, retaining existing global spawner/game-rule timing. Does not reset TIME_SINCE_REST, remove existing phantoms, deny all other players, block eggs/summons or grant damage immunity. TravellersGogglesItem.isEnderMask delegates same active modifier; native EnderMan.isLookingAtMe calls CommonHooks.shouldSuppressEnderManAnger before dot-product/sight test. Thus suppresses gaze admission while eligible, not already-established anger/retaliation. No night-vision effect, HP/source write, resource consumption or cooldown in these callbacks. Broken/missing modifier/spectator disable active admission; base Goggles Piglin predicate is independent.',
      'stealth':'Server PlayerTick.Post calls travellersStealth: active CHEST STEALTH and crouching applies native INVISIBILITY(duration2,amplifier0,ambient=false,particles=false,icon=false) each tick. Client RenderFrame.Pre for rendered Players uses same active/crouch predicate and setInvisible(true), not another server effect. If active but not crouching and current Invisibility exists with duration<2, setInvisible(false); longer effects not explicitly cleared, no removeEffect call. Removing/breaking gear stops renewal; native short effect expires through ordinary ticking. Native addEffect eligibility/merge/hooks remain. Ordinary invisibility visibility multiplier includes armor coverage and native visibility events; no guaranteed target reset, stealth immunity, HP reduction or new source. Armor-shrouding ASM is a separate pending mechanic.',
      'haste':'Server EntityTick.Post for LivingEntity reads active CHEST HASTE and nonnull amplifier, then addEffect(DIG_SPEED,duration2,amp,ambient=false,particles=false,icon=false). Packaged amp1 (HasteII), refreshed while eligible; no extra active cost. Native effect merge/applicability/expiry remain. Native Haste adds ATTACK_SPEED .1*(amp+1) ADD_MULTIPLIED_TOTAL (about+.2 here), mining factor1+.2*(amp+1) (1.4 here), and swing duration6-(1+amp) (4 ticks here), subject to ordinary attribute/effect selection and other modifiers. No direct attack-damage bonus, hurt callback, DamageSource or HP/SHP write. Removing gear stops refresh without deleting an independent stronger/longer Haste effect.',
      'aquatic':'Native Aquatic Agility insertion adds HEAD OXYGEN_BONUS+3 ADD_VALUE and PLAYER.SUBMERGED_MINING_SPEED+4 ADD_MULTIPLIED_TOTAL plus marker. These are actual item attributes, not a water-breathing MobEffect or oxygen refill. Native decreaseAirSupply: with oxygen value d>0 retain current air when random.nextDouble()>=1/(d+1), else decrement1; +3 alone yields decrement probability.25, not infinite breath/drowning immunity. Native Player.getDestroySpeed multiplies by submerged-mining attribute in water (default.2 becomes1 before other changes); above-water mining has no corresponding multiplier from this attribute. Native equipment, broken-attribute suppression, removal and ordinary attribute clamps remain; no custom DamageSource or HP write.',
      'eater':'Installed nested ReduceMovementFoodExhaustionTransformer is registered by protected TFCoreMod service. Targets EXACTLY ServerPlayer.checkMovementStatistics(DDD)V and Player.jumpFromGround()V; inserts PlayerHooks.getFoodExhaustion before each matching Player/ServerPlayer.causeFoodExhaustion(float) call. Hook reads current CHEST active EFFICIENT_EATER with nonnull divisor and returns f*(1/divisor), default divisor2. Thus swim/underwater/water movement .01 per block ->.005; sprint .1 per block ->.05; native walk/crouch0 remains0; sprint-jump.2->.1 and ordinary jump.05->.025. Native rounded-centimeter movement, passenger/no-motion branches remain. No change to damage/attack/mining/regeneration exhaustion callers outside those target methods; no food gain/heal/refund. Native causeFoodExhaustion server-only and !abilities.invulnerable still applies; FoodData accumulation/conversion remains. Codec.FLOAT and hook impose no additional positive/nonzero divisor guard; installed value2 is the legitimate default.',
      'persistence_sources':'Gear modifier/attribute/stored-broken components have native persistent/network codecs; ordinary ItemStack save/load/copy carries them. LAST_DAMAGE_ARMOR_TIME is serialized; no custom death-copy routine for it is added by this subsection. Native crafted base items do not automatically carry the sample auto-repair/dodge/stealth combinations used by DefaultModifiedTravellersGearGetter; actual modifier recipes must be performed. No innate Curio passive tick/slot scan is present in the reviewed Travellers callbacks: real equipment slots and vanilla/loader events are the proven delivery. Source-specific compatibility beyond those generic hooks is NONE_PROVEN here; this is not pack-wide compatibility certification. All eleven mechanics have no new custom DamageType; no fallback or synthetic damage was introduced.'
    }
    E='events/TravellersGearEvents';L=T+'TravellersGearLogic';A=T+'TravellersArmorItem';G=T+'TravellersGogglesItem';D='init/custom/TravellersModifiersManager';I='init/TFItems'
    nxt='Complete Travellers movement/control and installed ASM paths (water-walk, unrestrained, slimy soles, high-step/swim/jump, gradual glide, double-jump, sidestep, straight-ahead/agile ranger and packets); then belt/display/zoom and Emperor cloth, remaining utilities/food/passive entities/hazards,10 custom DamageTypes, full ASM/compatibility/source exclusions, R2f8 and final Twilight promotion. IceAndFire only after COMPLETE pushed/live verified; no runtime boss/L2/Stage/production/Phase6/7.'
    data=dict(slug='travellers-core',checkpoint_short='r2f8o',checkpoint='R2f8o-travellers-core-complete',decision='TWILIGHT_TRAVELLERS_CORE_SEMANTIC_REVIEW_COMPLETE',starting_sha='bf7b2fc69d8adab76096b99f49850a3d52206861',previous_checkpoint='R2f8n-charms-complete',previous_draft='partial-drafts/twilightforest-r2f8n-partial.json',facts=facts,packages=[],paths=[],new_damage_types=0,full_classes=FULL,limited_classes={E:['non-movement gear lifecycle/defense/resource handlers and lambdas'],L:['stealth/repair/haste and actual helper/lambdas'],G:['constructor/isEnderMask'],'client/event/TravellersClientEvents':['setup/handleStealth'],'asmhooks/PlayerHooks':['getFoodExhaustion'],'util/TFMathUtil':['probabilityOfAtLeastOneSuccess']},registration_classes=[I,'init/TFRecipes','init/TFDataComponents','init/TFDataAttachments','init/TFAttributeModifiers','init/TFArmorMaterials','events/RegistrationEvents','init/custom/TravellersModifierTypes','TFRegistries','TFRegistries$Keys'],closure_checklist=['registry_data_cache_reload','component_vs_ability_presence','actual_activation_and_armor_groups','recipe_slot_count_transfer_removal','gear_components_and_empty_attribute_proof','native_armor_wear_state','stored_attributes_repair_cycle','auto_repair_probability_and_delay','projectile_dodge_event_order','arrow_owner_pickup_recovery','phantom_and_enderman_admission','stealth_native_effect','haste_native_attributes','aquatic_native_attributes','installed_exhaustion_ASM_targets','persistence_equipment_integration'],compatibility_scope=facts['authority'],current_scope='Prior Twilight plus Travellers modifier framework, native gear/durability, Auto-Repair, Perfect Dodge, Arrow Magnetism, All-Night, Stealth, Haste, Aquatic Agility and Efficient Eater. Movement/storage/render hooks pending; PARTIAL zero promoted.',exact_next_task=nxt,damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=30,new_used_profiles=0,reviewed_profiles_after=30,remaining_profiles=10,remaining_disposition='Unfinished other actual callers, not declared unused.'))
    def pkg(key,title,kind,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=kind,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    framework=pkg('travellers_modifier_resource','Travellers modifier registry, crafting and removal','CUSTOM_RESOURCE',['registry','activation','crafting','removal','broken_removal','persistence_sources'],[D,M+'TravellersModifier',M+'TravellersComponentModifier',M+'TravellersEntryModifier',M+'TransferableComponentModifier',R+'TravellersGearModifierRecipe',E],{'main_piece_slots':3,'accessory_piece_slots':0},['registered key','real recipe','count<slots','not already installed','native component state'],'Custom component/recipe resource admission.','Actual packaged modifier recipe',['Slot limit, reload, builtin, transfer and grindstone controls'])
    gear=pkg('travellers_native_equipment','Travellers native loadout and equipment predicates','VANILLA_COMPOSITE',['equipment','equipment_predicates'],[A,G,I,'init/TFArmorMaterials'],{'armor_head_chest_legs_feet':[2,4,3,2],'durability':[132,192,180,156],'gloves_belt_armor':0},['actual item attribute component','real equipped slot','native item hook','independent broken predicates'],'Native item armor, gold-neutral and powder-snow predicates with actual component differences.','Native equip each Travellers piece',['Gloves/Belt zero armor, broken boots/goggles, anvil material and enchantment controls'])
    wear=pkg('travellers_broken_state','Travellers last-durability and stored-attribute state','CUSTOM_RESOURCE',['activation','durability','broken_attributes','broken_removal'],[A,E],{'broken_threshold':'maxDamage-1'},['marked damageable gear','ArmorHurtEvent','server-present attribute event','component presence'],'Native armor wear capped and attribute state stored/restored independently from HP.','Actual armor-wearing hit then native repair',['Zero wear, other armor, broken threshold, Unbreakable and later event controls'])
    repair=pkg('travellers_auto_repair','Travellers native Auto-Repair probability','CUSTOM_RESOURCE',['activation','repair','persistence_sources'],[L,D,'util/TFMathUtil'],{'base_probability':.001,'delay_strict_ticks':200,'sky_twilight_tries':1.5,'sky_day_tries':3,'durability_per_success':1},['real armor slot','active even broken','server Living tick','strict wait','per-piece roll'],'Native item damage repair, not healing or Mending XP.','Genuine crafted Auto-Repair gear worn after armor damage',['Covered/sky/day/TF-type, broken, spectator, multiple slots and save/load'])
    dodge=pkg('travellers_perfect_dodge','Travellers Perfect Dodge impact veto','BINARY_MECHANIC',['activation','dodge'],[E,D],{'probability':.3},['real ProjectileImpactEvent','Living recipient','active current chest','server roll'],'Impact cancellation before native projectile payload, without reflection or hurt replacement.','Actual arrow or throwable hitting eligible vest wearer',['Failed roll, ownerless, broken/missing modifier and non-event damage'])
    magnet=pkg('travellers_arrow_magnetism','Travellers missed-arrow native recovery','CUSTOM_RESOURCE',['activation','magnet'],[E,D],{'maximum_age_exclusive':200,'overflow_pickup_delay':40},['current living owner','BLOCK','AbstractArrow','server','pickup state'],'Native pickup-item recovery and discard; block callback remains separate.','Actual player arrow block impact while wearing crafted modifier',['Creative/nonplayer, pickup modes, overflow, age and equipment swap'])
    night=pkg('travellers_all_night','Travellers All-Night native admission','BINARY_MECHANIC',['activation','allnight'],[E,G,D],{},['active head','real per-player spawn event or Enderman mask callback'],'Phantom spawn and gaze eligibility, not damage resistance.','Genuine All-Night goggles and native Enderman gaze',['Broken, established anger, other player phantom check and native spawn alternatives'])
    stealth=pkg('travellers_stealth','Travellers crouch invisibility','VANILLA_LIKE_EXTENDED',['activation','stealth'],[E,L,'client/event/TravellersClientEvents'],{'duration_ticks':2,'amplifier':0},['Player','active chest','crouch','native effect eligibility'],'Vanilla Invisibility refreshed by custom equipment/crouch producer.','Native crouching player in crafted Stealth vest',['Stand, remove/break, longer effect and armor visibility controls'])
    haste=pkg('travellers_haste','Travellers passive native Haste','VANILLA_LIKE_EXTENDED',['activation','haste'],[E,L,D],{'duration_ticks':2,'amplifier':1,'attack_speed_total_add':.2,'mining_factor':1.4,'swing_ticks':4},['server Living tick','active chest','nonnull amplifier','native addEffect'],'Vanilla HasteII attribute/effect contract with custom renewal.','Native equipped Haste vest',['Removal/broken, existing stronger effect, real mining and attack cooldown'])
    aquatic=pkg('travellers_aquatic_agility','Travellers oxygen and submerged mining attributes','VANILLA_COMPOSITE',['aquatic','broken_attributes'],[D,M+'TravellersEntryModifier','init/TFAttributeModifiers'],{'oxygen_bonus':3,'submerged_mining_total_add':4,'air_decrement_probability_alone':.25},['real head attribute entries','native air/mining hooks','broken attribute suppression'],'Vanilla oxygen-bonus and submerged-mining attributes.','Native crafted Aquatic goggles underwater',['No infinite breath, above-water mining, removal and competing attribute controls'])
    eater=pkg('travellers_efficient_eater','Travellers movement and jump exhaustion reduction','CUSTOM_RESOURCE',['activation','eater'],['asmhooks/PlayerHooks',D],{'divisor':2,'sprint_per_block':.05,'water_per_block':.005,'jump':.025,'sprint_jump':.1},['current chest','active modifier','exact two transformed methods','native exhaustion eligibility'],'Native food-exhaustion input multiplier on bounded movement callers.','Native movement and jumping with Efficient Eater vest',['Unmodified attack/damage/regeneration callers, creative, missing/broken and divisor data'])
    data['damage_profiles']=[]
    def path(k,title,keys,ids,classes,labels,controls):data['paths'].append(dict(id='twilightforest:travellers_core_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' using installed native crafting/equipment/event callbacks; future fixture only, runtime0.',future_controls=controls))
    rows=[
      ('craft','Packaged shaped/shapeless modifier craft',['registry','crafting'],[framework],[D,R+'TravellersGearModifierRecipe',R+'TravellersGearModifierShapedRecipe',R+'TravellersGearModifierShapelessRecipe'],['OTHER'],['three slots','duplicate rejection','builtin not counted','actual ingredients']),
      ('transfer','Native modifier component transfer',['crafting'],[framework],[M+'TransferableComponentModifier',R+'TravellersGearModifierRecipe'],['OTHER'],['one provider','copy not merge','default fallback','preserve damage']),
      ('grind','Native grindstone removal and payload return',['removal'],[framework],[E,M+'TravellersEntryModifier',M+'TransferableComponentModifier'],['OTHER'],['builtin stays','no modifiers cancel','unique input','native overflow']),
      ('merge','Native vest/gloves merge',['removal'],[framework],[R+'TravellersVestGlovesMergeRecipe'],['OTHER'],['exact pair','vest copy','no extra slot','already merged negative']),
      ('reload','Native registry/component save and reload',['registry','activation','persistence_sources'],[framework],[D,'init/TFDataComponents'],['OTHER'],['present/missing cache clear','serialized components','no Curio slot assumption']),
      ('equip','Native four main pieces equipped',['equipment'],[gear],[A,I],['ARMOR_PROC'],['actual2/4/3/2','durability132/192/180/156','no double attributes']),
      ('plain_accessory','Native Gloves/Belt equipment',['equipment'],[gear],[A,I],['ARMOR_PROC'],['common EMPTY attrs','nonnull constructor cache','armor0','nondurable slots0']),
      ('piglin_snow','Native gold-admission and powder-snow callbacks',['equipment_predicates'],[gear],[A],['ARMOR_PROC','ENVIRONMENT'],['goggles or wings','exact boots','still true broken','native surrounding checks']),
      ('anvil','Native material repair and enchantment admission',['equipment_predicates','removal'],[gear,framework],[A,E,'init/TFArmorMaterials'],['OTHER'],['Tanned Leather material path','two gear canceled','supports false','creative override']),
      ('wear','Native armor-wear threshold hit',['durability','broken_attributes'],[wear],[E,A],['ARMOR_PROC'],['last durability retained','HP independent','integer wear/enchant hooks','no general destruction immunity']),
      ('attributes','Native broken then repaired attribute query',['broken_attributes'],[wear],[E],['ARMOR_PROC'],['store union','clear event','restore/remove stored','server present','enchantment pass separate']),
      ('broken_grind','Native broken Aquatic grindstone then material repair',['removal','broken_removal','broken_attributes'],[framework,wear],[E,M+'TravellersEntryModifier'],['OTHER','ARMOR_PROC'],['stored entries survive marker removal','native custom grindstone output','Tanned Leather repair','attributes return without marker']),
      ('wear_track','Native armor-hit delay tracking',['durability','repair'],[wear,repair],[E,L],['ARMOR_PROC'],['other armor positive wear','zero wear','no positiveHP requirement','serialized timestamp']),
      ('repair','Native Auto-Repair worn tick',['repair'],[repair],[L],['ARMOR_PROC'],['strict>200','roll each slot','one point','no XP/heal']),
      ('repair_sky','Native Auto-Repair sky/dimension probability',['repair'],[repair],[L,'util/TFMathUtil'],['ARMOR_PROC','ENVIRONMENT'],['p vs1-(1-p)^1.5/3','type not dimension ID','day/night/covered']),
      ('repair_broken','Native repair out of broken state',['activation','repair','broken_attributes'],[repair,wear],[L,E,D],['ARMOR_PROC'],['ALWAYS_ACTIVE only repair','spectator false','next attribute query','save/load']),
      ('dodge_arrow','Native arrow impacts eligible vest wearer',['dodge'],[dodge],[E],['PROJECTILE','ARMOR_PROC'],['probability.3','impact before damage','native cancel','source unchanged on fail']),
      ('dodge_throwable','Native throwable or ownerless impact',['dodge'],[dodge],[E],['THROWN_PROJECTILE','ARMOR_PROC'],['no owner/source type gate','must post event','native remaining motion']),
      ('dodge_sides','Native Perfect Dodge client/server and gear states',['activation','dodge'],[dodge],[E,D],['ARMOR_PROC'],['client alwayscancel onceactive','server roll','broken/spectator/missing']),
      ('dodge_negative','Native melee/environment and non-event damage controls',['dodge'],[dodge],[E],['MELEE','ENVIRONMENT'],['no LivingHurt cancellation','no reflected source','no blanket immunity']),
      ('recover','Native survival allowed-arrow block hit',['magnet'],[magnet],[E],['PROJECTILE','ARMOR_PROC'],['actual pickup component stack','current owner','tick<200','no distance gate']),
      ('recover_pickup','Native pickup/creative matrix',['magnet'],[magnet],[E],['PROJECTILE','ARMOR_PROC'],['ALLOWED','CREATIVE_ONLY','DISALLOWED','no creative item grant']),
      ('recover_mob','Native nonplayer living-owner arrow',['magnet'],[magnet],[E],['MOB_ATTACK','PROJECTILE','ARMOR_PROC'],['real equipment','discard without inventory','pickup mode independent']),
      ('recover_full','Native full-inventory recovery',['magnet'],[magnet],[E],['PROJECTILE','ARMOR_PROC'],['helper overflow ItemEntity','40 delay','not direct inventory overwrite']),
      ('recover_timing','Native arrow current-gear/age/block-callback controls',['activation','magnet'],[magnet],[E,D],['PROJECTILE','ARMOR_PROC'],['swap vest before impact','age200negative','entityhitnegative','discard doesnot cancel block callback']),
      ('phantom','Native per-player phantom spawn admission',['allnight'],[night],[E],['ARMOR_PROC'],['DENY','other players unchanged','TIME_SINCE_REST unchanged','no existing phantom removal']),
      ('enderman','Native Enderman gaze at All-Night goggles',['allnight'],[night],[G,D],['ARMOR_PROC','MOB_ATTACK'],['mask before dot/sight','existing anger separate','no damage immunity']),
      ('night_broken','Native inactive All-Night and separate Piglin callback',['activation','allnight','equipment_predicates'],[night,gear],[G,A,E],['ARMOR_PROC'],['broken disables modifier','piglin predicate remains','missing/ordinary goggles']),
      ('stealth','Native crouching Stealth Player tick',['stealth'],[stealth],[E,L],['ARMOR_PROC'],['serverInvisibility2/0','clientrender prediction','native merging']),
      ('stealth_end','Native stand/remove/break Stealth controls',['stealth'],[stealth],[L],['ARMOR_PROC'],['<2 setInvisiblefalse','longer effect preserved','renewal stops']),
      ('stealth_target','Native invisible-player visibility controls',['stealth'],[stealth],[E,L],['ARMOR_PROC','MOB_ATTACK'],['armorcoverage','native visibility event','no guaranteed target reset']),
      ('haste','Native living wearer Haste tick',['haste'],[haste],[E,L],['ARMOR_PROC'],['HasteII','attackSpeed+.2','mining1.4','swing4']),
      ('haste_end','Native Haste removal and stronger effect controls',['activation','haste'],[haste],[L,D],['ARMOR_PROC'],['broken/removed no renewal','native effect eligibility','no direct damage boost']),
      ('oxygen','Native Aquatic goggles underwater air',['aquatic'],[aquatic],[D,M+'TravellersEntryModifier'],['ARMOR_PROC','ENVIRONMENT'],['oxygen+3','decrement.25alone','not waterbreathing/infinite air']),
      ('submerged','Native Aquatic submerged mining and broken state',['aquatic','broken_attributes'],[aquatic,wear],[D,E],['ARMOR_PROC'],['attribute*5','outside water no gain','native clamp','restore after repair']),
      ('exhaust_movement','Native transformed ServerPlayer movement',['eater'],[eater],['asmhooks/PlayerHooks',D],['ARMOR_PROC'],['sprint/water amounts','rounded centimeters','passenger/no movement controls']),
      ('exhaust_jump','Native transformed Player jump',['eater'],[eater],['asmhooks/PlayerHooks'],['ARMOR_PROC'],['.05/.2 input halves','native invulnerable/server eligibility']),
      ('exhaust_other','Native non-movement exhaustion and modifier controls',['eater','activation'],[eater],['asmhooks/PlayerHooks',D],['ARMOR_PROC','OTHER'],['attack/hurt/regen untouched','current chest','broken missing','actual divisor2'])]
    for row in rows:path(*row)
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-evidence/'+BATCH+'-asm.json','reference-routing/'+BATCH+'.json','twilightforest-travellers-core-caller-scan.json','reference-evidence/twilight-equipment-asm.json','reference-evidence/twilight-equipment-244.json','reference-evidence/twilight-bows-fan-244.json','vanilla-evidence/cult-completion.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json']
    data['exclusions']=['Nineteen complete declared framework/base-item/recipe classes, selected non-movement handlers, actual item/component/registry producers and installed exhaustion ASM are pinned.','Move/control/packet contracts, belt/display/zoom and other ASM/Emperor cloth are explicitly unfinished, not REVIEW_REQUIRED or silently covered by framework evidence.','Tooltips/advancement/cosmetic visuals do not add damage; material defense is not assumed for empty-attribute Gloves/Belt.','No new custom DamageType or direct HP/SHP payload. Remaining10 declarations belong to later source review. Whole Twilight PARTIAL, zero promoted; no runtime or compatibility fix.']
    data['fixture_groups']=['Actual modifier crafting, slot cap, component transfer, grindstone and vest/gloves merge; native saves/reload.','Real equipment, broken threshold, armor event wear and repair, current versus stored attributes, sky probability and positive-wear timer.','Native projectile impact dodge/recovery with owner/pickup/age/gear/client-server/overflow and failed-admission controls.','Native per-player phantom/gaze/gold/snow eligibility, crouch Invisibility, Haste and Aquatic attributes.','Real transformed movement/jump exhaustion versus unmodified attack/damage/regen callers; no synthetic events.']
    data['expected_counts']=dict(mechanic_packages=len(data['packages']),delivery_cases=len(rows),classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=0)
    write_json(OUT/'review-inputs/twilightforest-travellers-core.json',data);assemble('twilightforest-travellers-core.json')

if __name__=='__main__':build()
