from catalog_common import *
from eternalstarlight_combat_common import save_section
START='8af2c7777cd3d4fc483ee4f83efd9e4403e8e1e3'
CP='R2h2a-crystal-numbness-complete';STEM='eternalstarlight-r2h2a-crystal-numbness'
NEXT='R2h2b: finish Eternal Starlight Starfire, Flammable/Brittle, Dream Catcher, Sticky, Teary and Oblivion status/control paths; reuse R2h2a effect/debt admission. Then remaining native combat families and all 18 DamageType caller dispositions; no runtime/Stage/production work.'
FACTS={
 'crystal_tick':'CrystalInfectionEffect requests ownerless eternal_starlight:crystal_infection HP damage = amplifier+1 every duration%35==0. Finite effects use remaining duration; infinite effects use recipient tickCount. applyEffectTick returns true regardless of hurt result; rejection does not remove the effect. The separate armor modifier is -1.5*(amplifier+1), ADD_VALUE with one stable armor.crystal_infection ID; native effect update/removal replaces/removes it. This armor penalty affects other armor-routed hits, not the infection source that bypasses armor. No direct HP/SHP subtraction, native magic classification or generic Tensura immunity is implied.',
 'crystal_melee':'Player.attack calls CrystalGreatswordItem.getAttackDamageBonus before critical multiplication and native hurt. Bonus = existing amplifier * (amplifier>=4 ? .25 : .15) * current input attack damage; absent infection gives zero. At amplifier4 the bonus equals the input damage. Only a successful primary target hurt followed by item.hurtEnemy true (SwordItem returns true), server side/nonempty stack, calls postHurtEnemy. After ordinary durability cost: existing amplifier defaults0; if >=4 attempt removeEffect, otherwise addEffect duration60 amplifier=min(existing+1,4). Thus first application is amplifier1, not0; subsequent native merge/expiry rules apply. Removal failure is not repaired and addEffect failure only suppresses ordinary chime. No separate burst hurt exists in this callback; the particles are cosmetic. Sweep targets do not each execute this item callback. Mob-held delivery is not claimed from the Player-only chain.',
 'crystal_crossbow':'CrystalCrossbowItem.createProjectile delegates to native CrossbowItem (arrow or firework), writes persistent ARROW_TYPE=eternal_starlight:crystal, and for AbstractArrow adds .25 base damage; shootProjectile then multiplies resulting velocity by1.35. Native ProjectileImpact event invokes ESCommonHandler on the server before normal impact HP handling, not after a successful hurt. Block impact clears the marker but continues this invocation. Five candidate positions within random offset4 are moved upward at most40 until air, then raycast down128 with COLLIDER/Fluid.NONE. A ground hit spawns one CrystalCluster; owner copied only if projectile owner is Living. Entity impact on Living separately adds infection200 amplifier0 if absent, otherwise min(old+1,4), ignoring addEffect return and without shouldHarm/LOS checks in that status branch. Entity impact does not clear the marker. Arrows/piercing and firework impacts are distinct future fixtures. Event cancellation before ES dispatch can suppress the helper; cancellation later does not undo already spawned clusters/status.',
 'crystal_cluster':'CrystalCluster server tick resolves saved owner UUID in the same ServerLevel; if unresolved it clears that UUID. At spawnedTicks>=20 it discards, without returning; at >5 and nonnull Living owner it still visits Living entities in its AABB inflated.5. shouldHarm(owner,target) must pass, then hurt4 via crystal_infection direct=cluster/causing=owner must return true before infection120 amplifier0 is requested. There is no LOS predicate. The final discard tick can still execute this block. Repeated visits are subject to ordinary native damage cooldown; do not multiply damage by duration or entity count. Ownerless clusters never enter this damage branch. NBT saves owner UUID and spawned_ticks; cluster hurt itself only discards/returns true for BYPASSES_INVULNERABILITY, otherwise false (binary entity removal, no numeric HP).',
 'crystal_stew':'ESBlocks registers Desert/Withered Desert Amethysia with infection4 seconds and Red/Blue Crystalfleur with10 seconds. DesertFlowerBlock delegates to FlowerBlock, whose SuspiciousStewEffects entry converts seconds to ticks; these are native suspicious-stew effect providers, not contact hazards. SuspiciousStewItem.finishUsingItem applies component entries through ordinary addEffect: amplifier0,80 or200 ticks. Acquisition/crafting and flower placement are excluded beyond identifying this real component route; no invented potion, splash or lingering recipe.',
 'shared_effect_admission':'All reviewed status producers use ordinary addEffect, not force-add/map insertion. Exact NeoForge LivingEntity.addEffect calls CommonHooks.canMobEffectBeApplied, then Added event and native update/hidden-effect merging. canBeAffected and external applicability hooks remain authoritative; successful hurt does not guarantee status admission. removeEffect and removeAllEffects pass removal hooks; expiration can be canceled. LivingEntityMixin.eat HEAD attempts to remove each non-beneficial effect for Lunaris Cactus Gel, with each removeEffect result ignored; it does not remove beneficial Numbness. Milk/cure behavior remains the native per-effect cure set and removal event, not an unconditional bypass. These custom statuses have no newly proven direct ES-specific Tensura/L2 hook; R2h1 scoped explicit-name scan is not a certification of generic runtime compatibility.',
 'numbness_admission':'Silver Pungency Fruit native FoodProperties requests Numbness1200 amplifier0 with probability1 (and independent Nausea120 at.8). LivingEntity.eat/addEatEffect performs the server food-effect application through addEffect. LivingDamageEvent.Pre passes current damage to onModifyLivingActualHurtDamage AFTER armor, Resistance and enchantment reductions but BEFORE absorption for both LivingEntity and Player. If Numbness is active: debt += modified*.75, immediate damage = modified*.25. Amplifier has no role. This is deferred damage, not HP healing or a direct subtraction. Debt can be written even when subsequent absorption consumes all immediate damage.',
 'numbness_release':'LivingEntityMixin injects AFTER updateGlowingStatus inside tickEffects. Exact21.1.244 host executes this only inside effectsDirty && !clientSide, not every entity tick. If Numbness absent and stored debt !=0: request ownerless eternal_starlight:numbness damage equal to the entire debt; then clear debt to0 regardless of hurt result. Ordinary expiration/removal marks effectsDirty, but canceled removal/expiry or a still-active hidden effect can prevent payout. An externally loaded nonzero debt with no dirty effect state has no unconditional per-tick drain. Native NUMBNESS_DAMAGE default0 is Codec.FLOAT serialized, not synced and not configured copyOnDeath. Direct archive field-access census finds only registration, Pre accumulation and this release; no ES retry or guaranteed eventual HP loss. Rejection can consume the debt without HP loss. Payout again passes ordinary armor/Resistance/enchantment/absorption and invulnerability, but its tag bypasses shields and Crescent Pendant; it is not an exact conservation of HP.',
 'shared_defenses':'Crescent Pendant must occur in ACCESSORIES components of HEAD/CHEST/LEGS/FEET equipment (set union; duplicates do not stack), not merely inventory or weapon. In Pre, unless source has eternal_starlight:bypasses_crescent_pendant, amount>maxHP*.75 is capped to maxHP*.75 BEFORE Numbness split. Finally BYPASSES_INVULNERABILITY returns max(original Pre amount,modified), AFTER debt is stored: bypass can retain full immediate damage plus future debt. Preserve this native ordering, not an inferred immunity override. IncomingDamage veto: exact Unrealium Helmet plus minecraft:in_wall, or exact Unrealium Chestplate plus minecraft:cramming. These are exact type keys, no global suffocation/crushing tag immunity. Shared source/weapon multipliers in onModifyLivingHurtDamage remain later family review.',
 'damage_identity_and_mitigation':'R2h1 tag closure (rawMC+NeoForge21.1.244+installedES) gives crystal_infection BYPASSES_ARMOR/BYPASSES_ENCHANTMENTS/BYPASSES_SHIELD, whereas numbness only BYPASSES_SHIELD plus BYPASSES_CRESCENT_PENDANT among those. Neither bypasses effects, Resistance, invulnerability or cooldown; neither is IS_MAGIC/IS_PROJECTILE/IS_FIRE/IS_FREEZING from these archives. Both DamageType exhaustion=.1, native scaling=when_caused_by_living_non_player. Infection DOT and Numbness have null direct/null causing; cluster preserves cluster/owner, so Player difficulty scaling may differ. Armor bypass does not imply Resistance bypass: the loader handles Resistance before enchantment bypass. Native death, totem, event cancellation and skill/L2 processing remain untouched and must be observed later.',
 'single_stage_boundary':'Independent numeric requests: scale infection DOT once at its native hurt amount; cluster once at native hurt4; ordinary Greatsword and Crossbow once at the final native primary/sweep/arrow/firework hurt amount after native weapon calculations. Do not additionally scale attack attributes, bonus fractions, base-damage increment, projectile velocity, stack amplifier, tick duration or cluster count. Numbness inherits the already-scaled parent damage; never multiply the debt or payout again. The native payout can apply mitigation a second time; do not compensate by bypassing defenses. Stage lineage handling is an explicit future implementation/test requirement, not a change made here. Fixed armor modifiers, cap percentage, deferral ratio and binary admission keep native values.',
 'scope':'Static semantic subsection only. Registry/decompiler aids checked against installed bytecode, exact loader and raw fallback routing. Other status/shared-handler branches and the remaining16 DamageType dispositions are unfinished; no full ES completion claim. Cosmetic chimes/particles, flower placement and ordinary acquisition omitted. All runtime fixtures remain unexecuted.'
}

def save():
    definitions=[
     ('crystal_tick','OTHER','CrystalInfectionEffect.applyEffectTick -> getDamageSource(CRYSTAL_INFECTION) -> hurt(amplifier+1)','null','null','hurt return ignored; effect persists'),
     ('crystal_greatsword','MELEE','Player.attack -> getAttackDamageBonus -> native hurt -> item.hurtEnemy -> postHurtEnemy','Player','Player','successful primary hurt required; remove/add effect independently admissible'),
     ('crystal_crossbow_arrow','PROJECTILE','CrystalCrossbowItem.createProjectile/shootProjectile -> AbstractArrow.tick -> ProjectileImpact -> ES crystal branch; normal onHitEntity follows','arrow for ordinary HP','shooter for ordinary HP','status/spawn precedes normal hurt; event cancellation ordering matters'),
     ('crystal_crossbow_firework','PROJECTILE','CrystalCrossbowItem.createProjectile -> FireworkRocketEntity.onHit -> ProjectileImpact -> ES crystal branch; ordinary explosion follows','rocket for ordinary HP','owner for ordinary HP','impact status independent of explosion hurt; lifetime explosion alone is not impact delivery'),
     ('crystal_cluster','AOE','server CrystalCluster.tick >5 with owner -> shouldHarm -> hurt4 -> infection120','cluster','Living owner','hurt must return true for infection request'),
     ('crystal_stew','ACTIVE_ITEM','FlowerBlock suspicious effects -> SuspiciousStewItem.finishUsingItem -> addEffect80/200 amp0','none','null effect cause','ordinary effect applicability/merge'),
     ('numbness_food','ACTIVE_ITEM','Silver Pungency Fruit -> FoodProperties -> LivingEntity.addEatEffect -> addEffect1200','none','null effect cause','server native food and effect admission'),
     ('numbness_pre','OTHER','LivingDamageEvent.Pre -> ESCommonHandler.onModifyLivingActualHurtDamage -> debt*.75/immediate*.25','original source','original source','after armor/magic before absorption; debt retained independently of later HP result'),
     ('numbness_release','OTHER','dirty server tickEffects -> after updateGlowingStatus -> absent effect && debt!=0 -> hurt(debt) -> clear','null','null','hurt result ignored; no retry'),
     ('crescent_cap','ARMOR_PROC','armor component union -> LivingDamageEvent.Pre cap>.75maxHP -> Numbness split','original source','original source','bypass_crescent_pendant skips cap; bypass_invulnerability max-original after debt'),
     ('unrealium_admission','ARMOR_PROC','LivingIncomingDamageEvent -> exact equipment/type check -> setCanceled','original source','original source','in_wall Helmet; cramming Chestplate'),
     ('cactus_gel_cure','ACTIVE_ITEM','LivingEntityMixin.eat HEAD -> snapshot nonbeneficial effects -> ordinary removeEffect','none','none','removal cancellation preserved; Numbness beneficial excluded')]
    paths=[dict(id='es:status:'+n,labels=[label],native_path=path,direct_entity=direct,causing_entity=cause,admission=admission,runtime_variants=['native eligibility and cancellation','source identity; HP versus status/debt side effect']) for n,label,path,direct,cause,admission in definitions];ids={n:p['id'] for (n,*_),p in zip(definitions,paths)}
    def m(id,name,cl,cats,point,why,keys):return dict(id='es:'+id,name=name,primary_classification=cl,tno_categories=cats,stage_scaling_needed=point is not None,single_scaling_point=point,stage_reason=why,delivery_paths=[ids[k] for k in keys])
    pk=[m('crystal_infection_dot','Crystal Infection periodic HP','CUSTOM_DAMAGE',['NUMERIC_SCALABLE','CUSTOM_ROUTED','ADMISSION_GATED'],'Once at CrystalInfectionEffect native hurt(amplifier+1).','Keep source, interval and admission.',['crystal_tick','crystal_greatsword','crystal_crossbow_arrow','crystal_crossbow_firework','crystal_cluster','crystal_stew']),m('crystal_infection_status','Crystal Infection armor and native stack state','CUSTOM_STATUS',['COMPOSITE','VANILLA_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Keep native armor/amplifier/duration and ordinary effect admission.',['crystal_tick','crystal_greatsword','crystal_crossbow_arrow','crystal_crossbow_firework','crystal_cluster','crystal_stew','cactus_gel_cure']),m('crystal_cluster_damage','Owned Crystal Cluster impact','CUSTOM_DAMAGE',['NUMERIC_SCALABLE','CUSTOM_ROUTED','ADMISSION_GATED'],'Once at CrystalCluster native hurt4.','Do not also scale count/lifetime or DOT producer.',['crystal_crossbow_arrow','crystal_crossbow_firework','crystal_cluster']),m('crystal_weapon_damage','Crystal weapon native primary damage','VANILLA_LIKE_EXTENDED',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],'Once at each final native melee/sweep/arrow/firework hurt request after native weapon calculations.','No extra multiplier at bonus, baseDamage or velocity.',['crystal_greatsword','crystal_crossbow_arrow','crystal_crossbow_firework']),m('numbness_debt','Numbness deferred damage','CUSTOM_RESOURCE',['COMPOSITE','CUSTOM_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Parent damage is scaled once before deferral; debt/payout inherits it and must not scale again.',['numbness_food','numbness_pre','numbness_release']),m('crescent_cap','Crescent Pendant native damage cap','CUSTOM_RESOURCE',['COMPOSITE','CUSTOM_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Fraction of current maxHP; preserve source bypass and Numbness order.',['crescent_cap']),m('unrealium_admission','Unrealium exact source veto','BINARY_MECHANIC',['BINARY','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Exact item/type cancellation.',['unrealium_admission']),m('cactus_gel_cure','Cactus Gel harmful-status removal','VANILLA_LIKE_EXTENDED',['BINARY','VANILLA_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Ordinary cancellable effect removal; no HP value.',['cactus_gel_cure'])]
    d=dict(schema='tno.external_effects.es_crystal_numbness.v1',checkpoint=CP,previous_checkpoint='R2h1-eternalstarlight-source-foundation',starting_sha=START,status='CRYSTAL_NUMBNESS_ADMISSION_COMPLETE',scope='R2h2a Crystal Infection, Numbness and shared cap/cure/admission complete; other R2h2 statuses pending.',summary='Crystal delivery and hurt-return distinctions, finite/infinite tick behavior, armor penalty, native Numbness debt/payout and Crescent/Unrealium admission reviewed; derived damage requires one Stage application on the parent.',facts=FACTS,mechanic_packages=pk,delivery_paths=paths,damage_types_reviewed=['eternal_starlight:crystal_infection','eternal_starlight:numbness'],unexecuted_future_fixtures=['Crystal_DOT_amp0_1_4_finite_vs_infinite','Crystal_DOT_armor_bypass_Resistance_admission','Crystal_Greatsword_first_amp1_bonus_at4_removal_veto','Crystal_primary_vs_sweep_vs_rejected_hurt','Crystal_crossbow_arrow_piercing_firework_block_entity_impact_veto','Crystal_cluster_owner_null_unloaded_allied_PvP_and_hurtfalse','Crystal_cluster_final_discard_tick_and_cooldown','Crystal_stew80_200_vs_cactus_cure_cancel','Numbness_Pre_after_mitigation_before_absorption','Numbness_expiry_remove_hidden_effect_removal_cancel','Numbness_dirty_vs_clean_loaded_debt','Numbness_hurtfalse_clears_no_retry','Numbness_payout_second_mitigation_parent_Stage_once','Numbness_bypass_invulnerability_full_hit_plus_debt','Crescent_equipped_component_vs_inventory_duplicate_threshold_source_bypass','Unrealium_exact_type_and_exact_slot'],remaining_subsection_native_ambiguities=[],review_required=[],exact_next_task=NEXT,references=['native-evidence/eternalstarlight-crystal-numbness.json','reference-evidence/eternalstarlight-crystal-numbness-244.json','vanilla-evidence/eternalstarlight-crystal-numbness.json','reference-routing/eternalstarlight-crystal-numbness.json','annotation-evidence/eternalstarlight-crystal-numbness-javap.json','annotation-evidence/eternalstarlight-crystal-numbness-javap.txt','eternalstarlight-status-attachment-census.json','eternalstarlight-source-census.json','eternalstarlight-damage-tags.json','native-evidence/eternalstarlight-foundation.json','eternalstarlight-direct-compat-census.json'])
    save_section(d,STEM,'R2h2a — Crystal Infection, Numbness and shared admission')
if __name__=='__main__':save()
