"""R2f8c explicit chain/spike path review; source identity is intentionally preserved."""
from catalog_common import *
from collect_twilight_chain import FULL,BATCH
from twilight_subsection import assemble
from collections import Counter

def build():
    facts={
      'pipeline':'Installed TF4.8.3345/raw Minecraft1.21.1/exact NeoForge21.1.244; shared damage, multipart, item durability/enchantment and projectile/event references reused. SPIKED is physical only in scoped merged tags: no IS_PROJECTILE, explosion, fire, armor/shield/Resistance/enchantment/iframe bypass or no_knockback. A projectile entity does not supply the missing projectile DamageType tag. Native armor, directional blocking whenstillactive, Resistance/general protection, absorption, cooldown and events remain; Projectile Protection is not granted solely by projectile delivery. Source declaration uses when_caused_by_living_non_player; native Player difficulty scaling depends on actual CAUSING LivingnonPlayer. Hurt true is not measured HP loss. No runtime/L2/SHP/Stage claims.',
      'goblin_state':'BlockChainGoblin HP20/speed.28/attack8/armor11, root.9x1.4, one permanent SpikeBlock part. Float0/AvoidPrimedTnt1(range2,far1/near2)/ThrowSpike4/Melee5/strolllook; retaliation/visiblePlayer. No custom hurt/death/regen/HPphase. No custom save methods for angle, recoil, extension, throwingflag or goalcooldown; nativeHP/attributes persist, these control values reset. SpikeBlock .75x.75 via setSize/refreshDimensions, TFPart/PartEntity parent relation, not an independently spawned projectile. It is unpickable/unpushable and hurt alwaysfalse, no forwarding to rootHP; is(entity) aliases self OR parent for identity only. Cannotride; own spawnpacket throws UnsupportedOperationException and saves no customdata. Parent ticks part; after parentdead part falls withY-.04, one initialgroundsound/event, no hurt call onfall. Deadparent disables attackcollision. TF multipart IDs/network handling already reviewed; source identity remains actualpart.',
      'goblin_melee':'Native MeleeAttackGoal enters BlockChainGoblin.doHurtTarget -> EntityUtil.properlyApplyCustomDamageSource(self,victim,SPIKED(this,this.block),null). TFDamageTypes factory firstentitydirect, secondcausing: direct=BlockChainGoblin, causing=SpikeBlock. This ordering is literal and differs from item projectile path; no inferred Livingowner substitution. Amount effectiveATTACK_DAMAGE default8 through sharedhelper, whose modifyDamage affectedentity=attacker and successful lastHurtMob=self quirks are retained. NonLiving SpikeBlock causer means when_caused_by_living_non_player does NOT scale Player difficulty here, and ordinary Livingcauser attribution/retaliation differs. Native sourceposition is directgoblin. Postattack/knockback helper callbacks require hurttrue. No extra spiked status, armor penetration or forced HP write.',
      'goblin_collision':'After super.tick andparttick, positive recoil--, angle+=16 mod360. isSwingingChain = swinging OR(targetnonnull &&recoil==0). Orbit radius.9 while swinging, else.3; Yoffset1.5-radius/4. Whenextension>0 partposition=currentviewXZ*extension plus goblinXYZ, Y=eyeHeight+.25 (viewYnotused); extension>=6 turns throwingfalse before collision. Server alive&&(throwing ORswinging) queries partBBinflate(.2,0,.2); every pushable entity exceptgoblin is pushed bycollider BEFORE damage. Livingcollided then calls SUPER.doHurtTarget, so ordinary minecraft:mob_attack effective8 direct=causingGoblin, NOT the SPIKED override. LivingnonPlayercauser scales Player Peaceful0/Easymin(a/2+1,a)/Normal a/Hard1.5a. True adds independentY+.4, sound/PROJECTILE_LAND, recoil40 and clears throwing; false retains priorpush but no extraY/recoil/stop. Loop can affect multiple candidates even after one success changesflags. No explicit LOS/team filter here, standard superclass damage checks remain. Whilethrowing, collider.isInWall stops throw/sounds/HIT_GROUND without breakingblock. Endoftick extension +=.5 ifthrowing else-=1.5, clamped0..6. No source on orbit movement alone; damage requires collision selection. Returning part may still collide when swingpredicate true; recoil suppresses target-driven swing but explicit swinging bypasses it.',
      'goblin_goal':'ThrowSpikeBlockGoal MOVE/LOOK, targetnonnull/distSquared<=42/cooldown<=0 then requires goblinalive/currentLOS/randomInt56==0. Else branch decrements cooldown; a qualified candidate failingrandom doesnot decrement, and counter can becomenegative. start throwingtrue, cooldown100+rand100,PROJECTILE_SHOOT; continuation extension>0 only. No customtick/aim/stopoverride, no targetalive/creative eligibility in this goal beyond inherited targetselection, no guaranteed cancellation reset when goalinterrupted. Native goalcadence rather than cooldown in seconds. PrimedTNTavoid selects first alive/LOS/notallied/noncreative/nonspectator PrimedTnt in rootBBinflate2,3,2, calls DefaultRandomPos.getPosAway(mob,16,7,mob.position()) using SELF position, rejects result closer to threat, navigates ifpath. Continues untilnavigationdone; defaultgoal cadence. Speed2 within distanceSquared<49 otherwise1. Avoidance higherpriority can interrupt MOVE; not explosionimmunity or defusal.',
      'item_launch':'BLOCK_AND_CHAIN is ChainBlockItem extends Item, durability99, no configured attackattribute or custom melee callback. Rightclick requires stack THROWN_PROJECTILE absent and PLAYER blockPos insideworldborder. Playssound; server constructs native ChainBlock(type,level,player,hand,stack), addFreshEntity returnignored, storesUUID; bothsides startUsingItem andSUCCESS, otherwisePASS. Instant release-independent launch speed1.5/inaccuracy1/pitchoffset0, ownerPlayer, same stack object reference, hand captured, foilcosmetic. No charge scaling, launchdurabilitycost, custom usecooldown or second entity while samecomponentpresent. Use duration72000/animationBLOCK; exact NeoForge isBlocking requires SHIELD_BLOCK ability, which ChainBlockItem/Item doesnotprovide (IItemExtension defaultfalse), so holding this animation is not a native shield in installedloader. Ordinary held-item melee remains default Player attack/enchantment pipeline, not projectile10 or spiked. UUIDcomponent is persistent+network-synced; server inventoryTick removes if samecurrent ServerLevel UUID lookup is missing/notChainBlock, including unloaded/otherdimension. Not a global one-perPlayer cap; separate stacks mayeachlaunch. Block-and-chain-use release doesnot independently triggerreturn. Native inventory/equipment transitions/durability rules unchanged.',
      'item_hit':'ChainBlock extends ThrowableProjectile directly, not TFThrowable/ITFProjectile; .6x.6 gravity.05, cannotuseportal. onHitEntity firstsuper(emptyparentpayload), then SERVER &&victim!=currentowner &&victim.blockPos insideworldborder; not Living-only. SPIKED direct=ChainBlock/causing=currentowner; base10. Withstoredstack and Livingvictim, native modifyDamage(level,stack,VICTIM,source,10); for PartEntity withLivingparent useparent asaffectedentity; otherentities no modifyDamage. Installed Destruction levelL adds-1.5L through native DAMAGE component: levels1/2/3 yield8.5/7/5.5 beforeothermodifiers/mitigation, evenonentityhits. No explicit outgoing doPostAttackEffects call in ChainBlock; native recipient/hurt hooks stillapply. Before damage>0 check ORhurt: Player victim using an item with SHIELD_BLOCK ability gets hurtAndBreak5 onusedstack then disableShield(); no isBlocking5-tickwarmup/frontangle/positiveamount/success prerequisite. Native disableShield cooldown100 for getUseItem().getItem() at that moment thenstopUsing/event30; ifdurabilitybreakemptiesstack first, currentitemmaynow beAIR. Nativecreative/Unbreaking/durabilityhooks remain. This pre-hurt action cannot be undone by laterzero/rejected HP. NonPlayer shieldusers skip this customdisable and maynormallyblock. Damage>0&&hurttrue only=>sound,hitEntitytrue,returningtrue,tickCount+=60,storedstack durabilityrequest1 ifLivingowner. False/zero doesnotsetreturn orcost1; shieldprocessingalreadyhappened. hitEntity flag doesNOT guard future hits: outbound/returning canattempt multipleimpact targets undernativecollision/cooldown. Ownerexcluded, not blanketownerteam exclusion.',
      'item_flight':'shoot overrides store velXYZ immediately aftersuper.shoot; subsequent shootFromRotation shooter-momentum addition occursaftercapture, so stored return/bounce velocity is initialshot component, not currentflightvelocity. Each tick calls super first (nativegravity/drag/collision/impacthook); server nullowner=>discard. Otherwise only whileoutbound: ifxOld!=X ORzOld!=Z, then bothabsXZdelta<.003 incrementstuckTime. ExactstationaryXZ doesnotincrement; counterneverresets onfastermotion. >=100 setsreturning. Distanceowner>16 setsreturning. Returning dist<2: ifstoredstack andLivingowner and OWNER SMASH_BLOCKS count>0 requestmin(count,3) durability, then discard; codecontinues calculatingreturnvelocity thattick. CastownerLiving is safe for legitimatePlayer launch/nativeLiving parry, not a genericanyEntityowner contract. Blend age=min(tickCount*.03,1), directiontoownereyes normalized; velocity stored*(1-age)+direction*2*age, Y also-minusgetGravity. Successfulhit+60 normallyforcesfullreturnblend. Bounce alwayssetsreturning, scales allstoredcomponents*.6 and hitface opposedcomponent anadditional*-.6; only firstoutbound/nohit playscollisionsound. No damage/durabilityfrombounceitself. Nativeimpact cancellation can skip payload; no custom TTL/lifetime guarantee. No directreturn-on-playerrelease/death/stackdrop method. remove calls super then stopsownerusing ANY BlockAndChain item ifcurrentuseisthatitem; doesnotclearUUIDitself (inventoryTick later).',
      'item_save_and_parry':'NBT calls parent preservingOwner/leftOwner/hasBeenShot and native entitymotion; saves BlockAndChainStack serialized plusIsReturning, reads ItemStack.parseOptional into a NEW detached stack, not rebound to inventory. Thus laterdamagecost acts on deserializedprojectilestack; originalinventory durability sharing is only initialconstructorreference. HAND,foil,hitEntity,stuckTime,velXYZ andtickCount notsaved; defaultsMAIN/false/0 onload, evenforoffhandlaunch. Spawnpacket sendsownerID+hand andacceptsonlyLivingowner. Normalnativeproducer alwaysprovidesnonnullstack; ownerless/missingstack manufacturedentities are not legitimate testdelivery (save dereferencesstack andsuccessfulLivingowner hitdoesalso). No marker means TF shield-parry hook is ineligible with pinned parryNonTwilightAttacks=false even though Twilightregistered. No TF REDIRECTABLE_PROJECTILE contribution forChainBlock, so no ordinary melee reflection fromitsnativeentitytag. If configuration explicitly enables general parry andexternalparrymodnotloaded, protected timednativehook mayAIM_DEFLECT/currentownertransfer andcancelimpact; this is conditional setup, not currentpackdefault. IMPACT_PROJECTILES tag is not projectile DamageType tag or reflection authority. No invented reflection source.',
      'destruction_terrain':'Destruction is native enchantment maxlevel3, supportedblock-and-chain/slotsHAND; DAMAGEadd-1.5L and HIT_BLOCK SmashBlocksEffect(maxSmash12,radius1,immune=#block_and_chain_never_breaks), no vulnerableBlocks/smashSound value. ChainBlock onHitBlock firstsuper nativeblockprojectilecallback, then ServerLevel &&storedstack &&nonair. Compute restrictedmode onlyforServerPlayerowner. canBreakBlockAt requiresblockinsideborder, stack.isCorrectToolForDrops, !neverbreakstag and(!restricted ORstack.canBreakBlockInAdventureMode). Item isCorrectToolForDrops additionally requires THROWN_PROJECTILE present, MINEABLE_WITH_BLOCK_AND_CHAIN andservernonnull, nativeDestructionlevel>0, tierWOOD1/STONE2/IRONotherwise; Tool rulesfirstdeniesincorrecttiertag thenmines/dropsallowedtag. Mineable expandsfourvanillapickaxe/axe/shovel/hoe; neverbreaksexpandsmazestone/castle/deadrock/witherimmune plusfourmagiclogcores/giantobsidian. Pinnedrecursive raw+TFtagclosure, notregistry-name inference. IfcanBreakfalse ORPROJECTILEblocksSmashed>=12 =>bounce. Regardlessbounce, EnchantmentHelper.onHitBlock executesatclamped hitlocation shiftedX-.5, currentblockstate, entity=PROJECTILE, ownerLivingnullable, slotnull, breakcallbackkillsprojectile. Hence anunbreakablecentralhit canbounceAND stillsmasheligibleadjacentblocks. No automatic blockbreak in ChainBlock itself.',
      'destruction_effect':'SmashBlocksEffect apply onlyifEnchantedItemInUse.owner ServerPlayer. Read countfrom passedentity (ChainBlock in thisnativepath), max/radius rounded; ifcount>=12 return. Loop3x3 sameY horizontalblockplane aroundBlockPos.containing(callbackposition), stopatcap12 acrosshits. Each nonair, !immuneoptional, canBreakBlockAt, state.canEntityDestroy(level,pos,PLAYER), uncanceledNeoForge BlockEvent.BreakEvent ->level.destroyBlock(pos,false), then ifnoncreative originalstate.block.playerDestroy(level,player,pos,originalstate,level.getBlockEntity(pos),stack), optionalsound, count++. destroyBlock returnnotchecked; blockentity lookup occurs AFTER destruction; preserve native break/drop callbacks rather than assert normal pre-break BEdata. No mobGriefing or EntityUtil hardness/containerpredicate. vulnerableBlocks codecfield exists butapplyneverreads it. Nativeinstalledresourceabsent, not a hidden whitelist. Countwrite to samePROJECTILE attachment serialized viaCODEC blocks_smashed (registeredserialize); no native resetsetter exceptthiseffect. ChainBlockbounce checksPROJECTILEcount; returndurability checksOWNERcount instead. Actual TFcaller scan proves no transfer/copy fromprojectile toowner; projectile-only use byfreshPlayer leavesownercount0 and therefore no terrain durabilitycostonreturn despiteprojectilecount>0. HOWEVER the legitimate vanilla mining-start HIT_BLOCK path passes PLAYER asentity and canpopulateownercount independently whileitemUUIDpresent; see destruction_mining. Returncost thenmin(ownercount,3) on everyreturn withnonnullstack, withoutconsuming/resettingthatcount. Bothbudgets serialize, no perthrow ownerreset. This is source-derived mismatch, not a proposedfix or runtime finding. ChainBlock entity-hitcost1 remains separate. No HP damage/heal/status fromterrainroutine.'}
    facts['destruction_mining']='Legitimate second Destruction terrain producer: native ServerPlayerGameMode.handleBlockBreakAction START_DESTROY_BLOCK invokes EnchantmentHelper.onHitBlock(mainhandstack,ownerPLAYER,entityPLAYER,slotMAINHAND,blockcenter,state). RawMinecraft caller census also finds AbstractArrow/ThrownTrident, but their own weapon payloads do not normally carry this block-and-chain-supported enchantment; no fabricated enchantedarrows admitted. Exact NeoForge mining ordering: uncanceled LeftClickBlock event, canInteractWithBlock(pos,1), Y<maxBuildHeight, START action, level.mayInteract, then creative branch returns throughordinarydestroy BEFORE enchantment; noncreative blockActionRestricted mustfalse; nonair initialstate callsenchantment BEFORE block.attack/getDestroyProgress/actualbreak. event.useBlock FALSE skips block.attack but NOT preceding enchantment. No wait for miningcompletion or hurt, no outgoingDamageSource. Smash effect entity=Player ->PLAYERbudget, independentofprojectilebudget. Item correcttool still requires THROWN_PROJECTILE component, so genuinepositive is launch native Destruction mainhandchain, releaseuse (projectilecontinues) and startmining eligible nearbyblock whileUUIDstillpresent. WithoutUUID no smash; offhandenchantment alone notused; creative start skips thisproducer. Same3x3/cap12/border/tag/tier/adventure/canEntityDestroy/BreakEvent rules apply, centeredactualminedblock (not projectileX-.5). Playercount persists on sameentity save/load, saturates12 with no perthrow reset and can make laterchainreturns costmin(count,3) repeatedly; no transfer fromprojectile. Smashing itself has no durabilitycall; ordinary Item.mineBlock only costsdurability throughTOOLcomponent, absent fromnativeChainBlockItem, so do not invent perblockcost. Returncost and entityhitcost remain separate. Futuretests must control priorPlayerminingbudget aswell as currentprojectilebudget.'
    M='entity/monster/';G='entity/ai/goal/';P='entity/projectile/ChainBlock';I='item/ChainBlockItem';E='enchantment/SmashBlocksEffect';A='components/entity/SmashBlocksEnchantmentAttachment'
    data=dict(slug='chain',checkpoint_short='r2f8c',checkpoint='R2f8c-chain-complete',decision='TWILIGHT_CHAIN_SEMANTIC_REVIEW_COMPLETE',starting_sha='e391928b3448e67dd4d2d551f5bf58f20e62037c',previous_checkpoint='R2f8b-mounted-mobs-complete',previous_draft='partial-drafts/twilightforest-r2f8b-partial.json',facts=facts,packages=[],paths=[],damage_profiles=[],new_damage_types=1,full_classes=FULL,limited_classes={'init/TFItems':['<clinit>','ChainBlockItem lambda'],'init/TFDataComponents':['<clinit>','UUIDUtil lambda'],'init/TFDataAttachments':['<clinit>','SmashBlocks attachment lambda'],'init/TFEnchantmentEffects':['<clinit>','SmashBlocksEffect lambda']},registration_classes=['init/TFEntities','events/RegistrationEvents','init/TFItems','init/TFDataComponents','init/TFDataAttachments','init/TFEnchantmentEffects'],closure_checklist=['all_spiked_callers','goblin_source_reversal','orbit_superclass_source','multipart_no_hp','throw_and_recoil','tnt_avoidance','instant_item_launch','ability_vs_animation','shield_disable_beforehurt','return_not_onehit','stored_velocity','save_stack_identity','parry_config_and_marker','destruction_damage_and_terrain','recursive_tool_tags','block_callback_order','projectile_vs_owner_resource','vanilla_mining_start_delivery','source_tags','exclusions'],compatibility_scope=facts['pipeline'],current_scope='Frosted, eight named bosses, ranged/mounted mobs and both chain/spike source paths complete; other Twilight content remains PARTIAL, zero promoted.',exact_next_task='Continue Task C: GiantMiner/ArmoredGiant with actual equipment damage, remaining melee mobs/minibosses, then remaining weapons/scepters/armor/charms/projectiles/hazards/resources and16 unfinished custom profiles. Do not redo protected chain/ranged/mounted/boss/Frosted reviews. Protect subsections toward R2f8 then whole-Twilight dedup/promotion; IceAndFire only after COMPLETE Twilight is pushed. No runtime boss/L2, Stage/production, balancing/fixes, Phase6/7.',damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=23,new_used_profiles=1,reviewed_profiles_after=24,remaining_profiles=16,remaining_disposition='Other native caller paths unfinished, not unused.'))
    def pkg(key,title,classification,keys,classes,nums,gates,relation,source,alts):
        eid='twilightforest:'+key;data['packages'].append(dict(id=eid,display_name=title,owner=key,primary_classification=classification,facts=keys,classes=classes,parameters=nums,gates=gates,relation=relation,primary_test_source=source,alternate_sources=alts));return eid
    gm=pkg('chain_goblin_spiked_melee','Goblin melee with spike-part attribution','CUSTOM_DAMAGE',['goblin_melee','pipeline'],[M+'BlockChainGoblin','util/entities/EntityUtil','init/TFDamageTypes'],{'default_attack':8},['nativeMeleeGoal','directGoblin','causingSpikeBlock','hurtdependentcallbacks'],'Custom physical source through native helper; literal nonLiving causer differs from ordinary melee.','Native BlockChainGoblin ordinary melee',['Native orbit collision as source-distinct control; nativearmor/shield/absorption/cooldown'])
    gc=pkg('chain_goblin_collision','Goblin orbit/throw collision and control','VANILLA_LIKE_EXTENDED',['goblin_collision','goblin_goal','goblin_state'],[M+'BlockChainGoblin',G+'ThrowSpikeBlockGoal',G+'AvoidAnyEntityGoal',G+'AvoidAnyEntityGoal$1'],{'default_attack':8,'angle_per_tick':16,'orbit_radius':[.3,.9],'max_extension':6,'extend':.5,'retract':1.5,'recoil':40,'success_push_y':.4,'goal_range_squared':42,'random_denominator':56},['serveralive','throwingORswinging','pushable','LivingforHP','superhurttrueforYboost'],'Native mob_attack with custom moving multipart geometry and result-dependent control.','Native goblin swinging part contact',['Native throw/retract, blockedhit/partwall, multi-target query, PrimedTNTavoid'])
    gp=pkg('chain_goblin_part','Goblin spike part damage rejection','BINARY_MECHANIC',['goblin_state'],['entity/SpikeBlock',M+'BlockChainGoblin$MultipartGenericsAreDumb','entity/TFPart'],{'part_dimensions':[.75,.75]},['hurtalwaysfalse','unpickable','noindependentHP'],'Native multipart identity with unconditional part damage rejection and no root forwarding.','Native goblin spike-part collision/selection controls',['Rootdamage, parentdeath/harmlesspartfall, native save/load'])
    cr=pkg('chain_item_flight_resource','Chain Block launch, return and stack resource','CUSTOM_RESOURCE',['item_launch','item_flight','item_save_and_parry'],[I,P,'init/TFDataComponents'],{'durability':99,'speed':1.5,'inaccuracy':1,'gravity':.05,'range':16,'return_distance':2,'use_duration':72000,'stuck_limit':100,'stuck_horizontal_exclusive':.003,'return_speed':2,'return_blend_rate':.03},['stackUUIDabsent','playerinsideborder','nativeowner','returntriggers','reloadstackdetached'],'Native projectile/item primitives plus per-stack UUID, returning state and serialized payload.','Native Player BlockAndChain use fromeitherhand',['Multiple distinctstacks, outsideborder, release, bounce/range/stuck/ownerloss, reload'])
    cd=pkg('chain_item_spiked','Thrown Chain Block spiked damage','CUSTOM_DAMAGE',['item_hit','pipeline'],[P,'init/TFDamageTypes'],{'base':10,'destruction_per_level':-1.5,'success_durability':1,'success_age_add':60},['server','notowner','targetinsideborder','positiveenchantedamount','nativehurt','nohitEntityguard'],'Custom physical damage source and enchantment-modified request, no projectiletag or outgoingpostattack call.','Native Player ChainBlock entity impact',['Outbound/returning, Living/multipart/othereligible, Destruction0..3, falsehurt'])
    cs=pkg('chain_item_shield_disable','Chain Block pre-hurt shield disruption','VANILLA_LIKE_EXTENDED',['item_hit'],[P],{'durability_request':5,'native_cooldown':100},['PlayerusingSHIELD_BLOCKitem','beforepositiveamountcheck','nofront/warmup/successrequirement'],'Native durability and Player.disableShield called by custom impact gate before HP admission.','Native ChainBlock impact on Player using shield',['Under5tickwarmup, rearimpact, latehurtfalse/zero, itembreak, nonPlayerblocker'])
    ds=pkg('chain_destruction_terrain','Destruction terrain smash and per-entity budgets','CUSTOM_RESOURCE',['destruction_terrain','destruction_effect','destruction_mining'],[P,I,E,A],{'max_level':3,'radius':1,'plane_candidates':9,'per_entity_cap':12,'nominal_return_cost_cap':3},['ServerPlayerowner','nativeHIT_BLOCK','tool/tag/border/adventure','canEntityDestroy','uncanceledBreakEvent','projectilecountvsownercount'],'Native enchantment and block breaking hooks with custom terrain-selection/counter; no HP source.','Native Destruction-enchanted ChainBlock block impacts',['Native mainhand mining-start whileUUIDpresent populatesPLAYERbudget; levels1/2/3 tiergate, blockedcenter/eligibleadjacent, countcap/reload, canceledBreakEvent, creative'])
    def path(k,title,keys,ids,classes,labels,controls):
        data['paths'].append(dict(id='twilightforest:chain_path:'+k,source=title,facts=keys,effect_ids=ids,classes=classes,labels=labels,setup=title+' through installed native item/entity/AI callbacks, static review only; no fabricated sources or HP writes.',future_controls=controls))
    rows=[
      ('goblin_melee','Native goblin ordinary melee',['goblin_melee','pipeline'],[gm],[M+'BlockChainGoblin'],['MOB_ATTACK','MELEE'],['directGoblin/causingpart','noPlayerdifficultyScaling','helperquirks']),
      ('goblin_orbit','Native goblin orbit contact',['goblin_collision'],[gc],[M+'BlockChainGoblin','entity/SpikeBlock'],['MOB_ATTACK','MELEE'],['mob_attack8','difficulty','pushbeforehurt','recoil40']),
      ('goblin_throw','Native goblin extended spike and retraction',['goblin_goal','goblin_collision'],[gc],[M+'BlockChainGoblin',G+'ThrowSpikeBlockGoal'],['MOB_ATTACK','OTHER'],['rangeSq42','currentview','.5out/1.5back','noactualprojectile']),
      ('goblin_blocked','Native goblin failed hit, wall and multiplecolliders',['goblin_collision'],[gc],[M+'BlockChainGoblin'],['MOB_ATTACK','OTHER'],['priorpush','noYwithouttrue','wallstopnodestroy','multiquery']),
      ('goblin_tnt','Native goblin PrimedTNT avoidance',['goblin_goal'],[gc],[G+'AvoidAnyEntityGoal',G+'AvoidAnyEntityGoal$1',M+'BlockChainGoblin'],['MOB_ATTACK','OTHER'],['firstthreat','selfpositionawayargument','pathrejection','notimmunity']),
      ('goblin_part','Native spike part and root damage distinction',['goblin_state'],[gp],[M+'BlockChainGoblin','entity/SpikeBlock'],['MELEE','PROJECTILE'],['partfalse','rootordinaryHP','notforwarded']),
      ('goblin_reload_death','Native goblin save/load and parentdeath',['goblin_state'],[gp,gc],[M+'BlockChainGoblin','entity/SpikeBlock'],['OTHER'],['controlvaluesreset','nativeHPsaved','harmlesspartfall']),
      ('chain_main','Native mainhand BlockAndChain launch',['item_launch','item_flight'],[cr],[I,P],['ACTIVE_ITEM','THROWN_PROJECTILE'],['instant1.5','stackUUID','nochargecost','BLOCKnotshield']),
      ('chain_off','Native offhand or separatestack launch',['item_launch','item_save_and_parry'],[cr],[I,P],['ACTIVE_ITEM','THROWN_PROJECTILE'],['handcaptured','distinctstacknotglobalcap','reloadmainhanddefault']),
      ('chain_admission','Native blocked repeat/outsideborder use and inventory cleanup',['item_launch'],[cr],[I],['ACTIVE_ITEM','OTHER'],['sameUUIDPASS','samelevel lookup','unloadedcleanup','release noforcedreturn']),
      ('chain_hit','Native ChainBlock outbound/returning entity impact',['item_hit','pipeline'],[cd,cr],[P],['THROWN_PROJECTILE'],['10customphysical','noIS_PROJECTILE','repeatimpacteligible','truecost1']),
      ('chain_destruction_hit','Native Destruction-modified ChainBlock hit',['item_hit'],[cd],[P,I],['THROWN_PROJECTILE'],['8.5/7/5.5','victimcontext','partparentcontext']),
      ('chain_shield','Native ChainBlock used-shield disruption',['item_hit'],[cs,cd],[P],['THROWN_PROJECTILE','ACTIVE_ITEM'],['preHP5durability','disable100currentitem','warmup/rear/falsehurtcontrols']),
      ('chain_nonplayer','Native ChainBlock nonPlayer blocking and rejecteddamage',['item_hit'],[cd,cs],[P],['THROWN_PROJECTILE'],['noPlayerdisablebranch','positiveamount','ordinaryshield','no cost/returnonfalse']),
      ('chain_return','Native ChainBlock bounce/range/stuck return',['item_flight'],[cr],[P],['THROWN_PROJECTILE','OTHER'],['snapshotvelocity','>16/<2','stationarydoesnotcount','noTTLguarantee']),
      ('chain_reload','Native ChainBlock entity/item save-load',['item_save_and_parry','item_launch'],[cr,cd],[P,I],['THROWN_PROJECTILE','OTHER'],['Owner/savedmotion','detachedstack','hand/velocityreset','originalinventorycost']),
      ('chain_parry','Native impact-hook and parry eligibility control',['item_save_and_parry'],[cr,cd],[P,'events/EntityEvents'],['THROWN_PROJECTILE','ACTIVE_ITEM'],['markerabsent/pinnedfalse','conditionalgeneralparry','noordinaryreflection']),
      ('chain_bounce','Native unenchanted/unbreakable block collision',['destruction_terrain','item_flight'],[cr,ds],[P,I],['THROWN_PROJECTILE','ENVIRONMENT'],['superblockcallback','bounce thenenchantment','noautomaticbreak']),
      ('chain_smash','Native Destruction terrain plane',['destruction_terrain','destruction_effect'],[ds],[P,I,E,A],['THROWN_PROJECTILE','ENVIRONMENT'],['3x3','12total','WOOD/STONE/IRON','immune/tags/adventure/border']),
      ('chain_smash_control','Native denied/creative/capped/reloaded smash',['destruction_effect','destruction_terrain'],[ds,cr],[P,E,A],['THROWN_PROJECTILE','ENVIRONMENT'],['BreakEvent','destroyreturnignored','BElookupafter','projectilevsownerbudget','savedcount'])]
    rows += [
      ('destruction_mining','Native mining-start Destruction while chain is in flight',['destruction_mining','destruction_effect'],[ds,cr],[I,E,A,P],['ACTIVE_ITEM','ENVIRONMENT'],['mainhand/UUIDpresent','START notcompletedbreak','Playerentitycounter','noncreative/unrestricted/events']),
      ('destruction_mining_controls','Native inactive/offhand/creative mining and laterreturn budget',['destruction_mining','item_flight'],[ds,cr],[I,E,A,P],['ACTIVE_ITEM','ENVIRONMENT'],['noUUID negative','creative skipscallback','independentPlayercap12','repeatreturnmin(count,3)','no perthrow reset'])]
    for row in rows:path(*row)
    data['damage_profiles']=[dict(type='twilightforest:spiked',status='USED',callers=[dict(entry='twilightforest/entity/monster/BlockChainGoblin.class',method='doHurtTarget'),dict(entry='twilightforest/entity/projectile/ChainBlock.class',method='onHitEntity')],amount='Goblin effectiveattack8 viahelper; Player ChainBlock10 modified bystoredstack (Destruction subtract1.5L). Part collision instead mob_attack8.',direct_and_causing_entities='Goblin melee: directGoblin/causingSpikeBlock; itemimpact: directChainBlock/causingcurrentowner (nativePlayer).',mitigation=facts['pipeline'],difficulty='Neither normalnative SPIKED caller has LivingnonPlayercauser: part is nonLiving; itemownerPlayer. Goblin orbit mob_attack DOESscale Player difficulty. Conditional owner-transfer canchangeeligibility.')]
    data['comparison_files']=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','reference-routing/'+BATCH+'.json','vanilla-evidence/twilight-chain-tools.json','twilightforest-chain-caller-scan.json','twilightforest-chain-vanilla-caller-scan.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','vanilla-evidence/twilight-minoshroom-knight.json','reference-evidence/twilight-minoshroom-knight-244.json','vanilla-evidence/twilight-naga.json','reference-evidence/twilight-naga-244.json','config-evidence/twilightforest-common.json']
    data['exclusions']=['Eleven native class surfaces fully reviewed/pinned, including synthetic switch/anonymous predicate; incremental registrations and recursive mining/immune/tier tags also pinned.','SPIKED source identity never inferred from projectile appearance; twoactualcallers closed, multipart contact explicitlydifferent.','Ordinary item-held Player melee, genericdurability/enchantment, sounds/particles/loot are assessed but not standalonecustomdamage.','Destruction damage modifier is partofChainBlock damage package; terrain/counter is separate, no duplicated enchanthit package.','No claimed runtimefrequency/HP or compatibilityfix for separate projectile/mining-owner counters, shieldordering, detachedreloadstack or TNTself-awayargument.','Sixteen other customprofiles remain unfinished; no wholemodpromotion or IceAndFire research yet.']
    data['fixture_groups']=['Goblin native melee vs movingpart contacts with source direct/causing/type/difficulty separatelyobserved; geometry, falsehurtpush, successfulY/recoil, multiplecolliders.','Goblin throw goal/control, partvulnerability/rootHP, parentdeath/load, PrimedTNTavoidance.','Player chain instantmain/offhand launch, UUID/resource cleanup, currentowner collision and shield preemption, native mitigation/enchantmentlevels.','Return/range/stuck/bounce, repeatedhits, perhitdurability, release, save/loadhand/stackalias and conditionalparry controls.','Destruction blockborder/tier/tag/adventure/event/cap/creative/drop callbacks and projectilecount vs independent native mining-start ownercount/returndurability; no direct terrainHP source.']
    data['expected_counts']=dict(mechanic_packages=7,delivery_cases=22,classification_totals=dict(Counter(e['primary_classification'] for e in data['packages'])),review_required=0,new_custom_types_resolved=1)
    write_json(OUT/'review-inputs/twilightforest-chain.json',data);assemble('twilightforest-chain.json')

if __name__=='__main__':build()
