"""R2f6 installed-code semantic closure, draft packages and owner review."""
from copy import deepcopy
from collections import Counter
from twilight_evidence import *
from assemble_batch import refresh
from collect_twilight_hydra_urghast import BATCH

START='79b3284081ee71a1a5c5ec0b18af02595535e379'
CP='R2f6-hydra-urghast-complete'
DECISION='HYDRA_UR_GHAST_SEMANTIC_REVIEW_COMPLETE'
NEXT='Alpha Yeti + Snow Queen semantic review from existing installed Twilight source aids. Do not repeat Frosted, Lich, Naga, Minoshroom, Knight Phantom, Hydra or Ur-Ghast. Twilight remains PARTIAL; no runtime boss/L2 tests, Stage/production, balancing, compatibility fixes, Phase6 reopening or Phase7. Protect this checkpoint, then continue Alpha Yeti + Snow Queen while current usage is healthy. Ice and Fire remains blocked until all Twilight semantic work and final promotion are complete and pushed.'


def build():
    facts={
    'hydra_body_parts': 'Hydra is BaseTFBoss, base HP360/movement0.28, registered root dimensions16x12 and fireproof. Installed multiplayerFightAdjuster=NONE remains pinned. Seven containers each hold one 4x4 HydraHead and five 2x2 HydraNecks; body6x6, two legs2x3 and tail6x2 give46 Entity parts. They are TFPart/NeoForge PartEntity, NOT LivingEntity, with no independent HP. First three containers start IDLE, remaining four DEAD. Root is not pickable; actual parts are pickable and forward the same DamageSource to the parent. NeoForge part IDs/world queries/native Player reach and impact hooks are reused. HydraPart.hurt does not itself reject inactive dimensions or markedDead: parent state admission is decisive. Only head hits add that head counter; neck/body/leg/tail hits affect parent HP without adding a head counter. Multiple queried parts or piercing-arrow part IDs can cause multiple attempts, but all forward to ONE parent cooldown/HP pipeline. A rejected arrow hit can still increase a head counter; nonpiercing arrow callback/discard follows the returned bool, not the counter. No seven independent HP pools or guaranteed multiplied HP damage.',
    'hydra_admission': 'Exact part admission order: server IN_WALL first attempts terrain clearing; then reject causing OR direct entity equal to Hydra; reject either equal to any own part; identify the exact head or reject a neck belonging to DYING/DEAD head; compute parent-to-causing-entity distanceSquared (-1 if absent); reject >400, or >600 when DIRECT entity is HydraMortar; reject DYING/DEAD head; forward to BaseTFBoss.hurt. Head interpolated mouth openness strictly>0.5 forwards original amount; every other part/closed head forwards Math.round(amount/8F). Closed-head/body armor is this fixed pre-pipeline reduction, not armor attribute or a bypassable armor tag. Open-head counter adds (int)original amount; closed-head counter adds rounded amount, AFTER hurt regardless of its bool or actual HP. Admission rejects before forwarding add nothing. Native server/alive/fire-resistance/events/shield/cooldown/armor/Resistance/protection/absorption then decide HP. True alone resets ticksSinceDamaged. Parent hurt called directly accepts only BYPASSES_INVULNERABILITY; part forwarding deliberately calls super.hurt and avoids that root gate. Hydra.isInvulnerableTo returns false for exact hydra_mortar, otherwise superclass (fireproof included); this exception does not remove later Living fire-resistance, dead/client/event/cooldown checks and does not bypass the root hurt gate. Own unreflected mortar is rejected by owner identity even with the correct type. Source owner range, not projectile range/home radius, governs distant attacks; ownerless source skips range. BYPASSES_INVULNERABILITY does not override the preceding part self/range/state gates.',
    'hydra_head_resource': 'Each head has integer damageTaken, initially0; addDamage truncates each float request independently, never reads actual HP loss. Server AI schedules DYING only when !isDead and damageTaken>120 (strictly greater, not >=120), ends current action and sets respawnCounter140. It also picks one random current DEAD head whose counter==-1 and schedules140 if any; there is no eighth head. DYING counts as dead for attacks/hurt and active-count, but isActive means state!=DEAD, so DYING is saved as active. DYING lasts70; respawn countdown only decrements while current DEAD. A newly recruited already-DEAD head therefore starts its140 countdown immediately, while the killed head waits through DYING first. At --counter<=0, schedule BORN, reset damageTaken0, end current action and set counter-1. Then BORN20 -> ROAR_START10 -> ROAR_RAWR50 -> IDLE. No parent heal in head regrowth and no fire/cauterize predicate. All seven can ultimately be active. Bite remains restricted to head indexes0..2 and requires active-count>2; all heads can flame/mortar. Loss can reduce concurrency and suppress bites until regrowth; it is not an HP-threshold phase.',
    'hydra_state_machine': 'Container server tick: tick head/necks; update difficulty; activate nondead zero-width parts or deactivate DEAD parts; advance respawn, then ++ticksProgress and transition when>=ticksNeeded, then position/facing/execute/sounds. A transition sets progress0, so attack runs on entry. Explicit pending next state wins automatic successor; endCurrentAction sets progress=ticksNeeded for next tick. Initial active IDLE uses60/60 (transitions next tick); enum IDLE duration10 thereafter. Durations: BITE_BEGINNING40 -> BITE_READY80 -> BITING7 -> BITE_ENDING40 -> ATTACK_COOLDOWN80 -> IDLE; FLAME_BEGINNING40 -> FLAMING100 -> FLAME_ENDING30 -> cooldown; MORTAR_BEGINNING40 -> MORTAR_SHOOTING25 -> MORTAR_ENDING30 -> cooldown; DYING70 -> DEAD20 loop; birth sequence as above. Secondary attacks replace automatic cooldown with IDLE and clear their flag. Mouth is clamped interpolation previous-state to current-state, not a binary attack flag: idle/cooldown/dead/born/ending0, flame/mortar beginning0.75 and active1, bite beginning0.25/ready1/biting0.2, roar-start0.25/roar1. Thus vulnerable >0.5 includes portions of windup/end/roar, not all attack ticks; for example BITING starts open and closes during seven ticks. Death marks head at1 and five necks at10/20/30/40/50, then each marked part deactivates at its deathTime20. Size/state/mouth/current+last and names are synced through existing multipart data; not independent health.',
    'hydra_scheduling': 'Custom server AI has no walking/path pursuit (xxa=zza=0; navigation createPath null/canUpdatePath false). Each AI call has70% nearest-Player acquisition within48, rejects creative, chase100..119; live target and parent LOS required to request primary attacks, clears on expired chase/death/distanceSquared>2304. Idle nonsecondary heads get main target. Primary head0..2: idle plus concurrency admission, bite distance4<d<10/chance1/10/active>2/no other biting (including pending bite); else flame0<d<20/chance1/100; else mortar8<d<32/chance1/160 and target.minY<=parent.maxY. Heads3..6 lack bite branch. Other-head concurrency score adds1 per current isAttacking, plus2 if biting; reject score>=1+activeHeads*(Hard0.5, otherwise0.3). Pending flame/mortar is not counted by isAttacking; pending bite IS checked by isBiting, so this is not an absolute simultaneous-head cap. Secondary selection: nearest Living in unit parent box inflated20, excludes any Hydra, main target, any already-targeted entity, creative/spectator and lacks parent LOS; heads1..6 idle/nondead and closer in XZ to target than parent can flame chance1/10 within20 or mortar1/16 within8..32. Secondary does not reuse primary concurrency, bite or target-above predicates. Native query/scheduling, not guaranteed damage per second.',
    'hydra_bite': 'Every server BITING tick (seven state ticks) queries head BB.inflate(0,1,0), all Living except parent; no target-identity/LOS/team filter. Before hurt, a currently blocking Player: if use item not on cooldown, request112 durability via native hurtAndBreak; then add cooldown200 to current use item, stop use, send additive MovePlayerPacket(-head.cardinalX*0.5,0.15,-head.cardinalZ*0.5). This pre-hurt control is independent of damage acceptance, and does not check shield facing or source shield bypass. Damage request48, twilightforest:hydra_bite, direct=causing=Hydra, not head; entity-type exclusion argument only affects death text. Afterwards regardless bool another Player push packet uses Y0.1 (so blocking branch sends both); nonPlayer code calls knockback(-cardinalX,0.1,-cardinalZ). Preserve this argument-order quirk: first arg is STRENGTH, not X. Default strength is1 only when cardinalX=-1; 0 or-1 otherwise yields no positive native knockback absent hook changes. RatioX0.1/ratioZ=-cardinalZ; ordinary knockback hook/KR then apply. Physical source retains armor/Resistance/protection/absorption/cooldown; preemptive stop-use normally prevents ordinary shield block for that attempt. Repeated attempts share recipient cooldown; seven requests are not seven48 HP hits. No success-only enchantment callback in this attack.',
    'hydra_flame': 'FLAMING runs one server look-target query per tick for100 state ticks, not one hit per rendered flame. Track target coordinates toward entity by normalized step0.04 (Hard0.1); facing max5 degrees yaw. Ray source=(headX,headY+1,headZ), view vector, endpoint30. Block.OUTLINE/Fluid.ANY clip supplies a BlockPos even for MISS; candidate AABB is headBB MOVED by look*(per-axis min(30,abs(head-coordinate-hitBlock-coordinate))) and inflated3, NOT a swept30-long box. Candidate pickable entities exclude head and only necka/b/c; nearest ray/AABB intersection wins, using full30 endpoint without comparing entity intersection against block-hit distance. Self Hydra/any own HydraPart and fire-immune winner are rejected AFTER selection, so they can occlude a later eligible target. This implementation is not a cone, block ignition, multiple-target sweep, or a proven strict block-occluded ray. For eligible target request19 hydra_fire direct=causing=Hydra; only hurt true calls igniteForSeconds(3). Normal armor/shield/Resistance/protection/absorption/shared cooldown and fire immunity/Fire Resistance apply. Fire tag is not projectile or explosion. Later burning is native on_fire, a separate source, not repeated hydra_fire; no terrain ignition here.',
    'hydra_mortar_launch': 'MORTAR_SHOOTING progress0/10/20 creates three HydraMortars per state sequence. Owner=parent Hydra via ThrowableProjectile(owner). Position=head look*3.5 plus headY+1; head velocity is zeroed; shootFromRotation(head,pitch,yaw,-20,0.5,1) supplies upward pitch offset and inaccuracy. If current target nonnull and head COLLIDER/Fluid.NONE LOS fails, set megaBlast true (no target => ordinary). Gravity0.05, native throwable movement/collision/impact hook/deflection; type0.75x0.75 fireproof, pickable radius1.5. onHit override dispatches its own entity/block callback and omits superclass Projectile.onHit redirection of a struck projectile. Entity hit server requires owner nonnull; if target another mortar, requires target.getOwner().is(owner), not different owner (ownerless target dereference has no null guard); reject target.is(owner) or own HydraPart while owner Hydra. Allowed entity hit detonates; disallowed hit has no discard. Ordinary block top hit sets vertical speed0 and onGround=true; other faces detonate then still set onGround. Mega detonates on any block. Ground tick calls immutable velocity.multiply(.9) but discards its result: no extra .9 damping is applied. Server fuse starts80 and postdecrements only onGround, detonating when old<=0 (81 grounded checks). No airborne lifetime fuse.',
    'hydra_mortar_damage': 'detonate FIRST calls native Level.explode(source=mortar,radius ordinary0.1 or mega4,fire=canEntityGrief(level,mortar),interaction=MOB); THEN loops entities in mortarBB.inflate(1) without owner exclusion or LOS. Non-fire-immune entities OR any Hydra/HydraPart receive18 twilightforest:hydra_mortar direct=mortar, causing=current owner (nullable); only true ignites5 seconds. Finally discard regardless accepted HP damage. There is no separate on-collision18 hit before explosion:18 is the post-explosion nearby query, and ignores explosion exposure. Native explosion source is minecraft:player_explosion when direct mortar and Living indirect owner both exist (despite the type name, original Hydra owner qualifies), otherwise minecraft:explosion. Standard radius/exposure damage formula and separate knockback apply. The18 request is fire-tagged, NOT IS_EXPLOSION or IS_PROJECTILE and NOT armor bypass; Explosion Protection applies to preceding explosion, Fire Protection to the custom18, ordinary Protection/Resistance/absorption/cooldown remain. Explosion may consume cooldown before18, so never sum full damage automatically. Mega block resistance min(original,0.8) except COMMON_PROTECTIONS; native explosion block/event/mobGriefing rules still apply. Ordinary radius0.1 can damage very-near entities; it is not an inert cosmetic explosion. A reflected mortal splash can attempt multiple Hydra parts and counters; closed parts round18/8 to2, open heads forward18, owner-distance<=sqrt600 and shared parent cooldown still apply.',
    'hydra_mortar_reflection_save': 'Entity tag REDIRECTABLE_PROJECTILE includes HydraMortar. Native Player.attack after attack-interaction admission invokes AIM_DEFLECT and RETURNS before target.hurt; direction becomes player look normalized (speed1), owner=Player. This normal reflection does NOT clear onGround, extend fuse, use speed1.5 or toggle mega. An incoming projectile using superclass Projectile.onHit can first redirect a tagged mortar to its owner. Separately, a genuine source reaching HydraMortar.hurt calls super.hurt but ignores that return: on server any nonnull causing entity shoots along its look at1.5/inaccuracy0.1, clears onGround, adds20 fuse; only Living causing entity replaces owner; returns true regardless amount. Ownerless/client returns false. Native incoming arrow may therefore run both redirection and hurt callbacks; callers that override onHit may omit the first. Mortar is NOT ITFProjectile; pinned parryNonTwilightAttacks=false means TF timed shield parry does not catch it, despite its Twilight registry name. No custom save methods: inherited projectile saves owner/leftOwner/shot plus Entity position/motion/onGround, but fuse and mega reset80/false on reload. Ordinary Player reflection after reload remains tag-based. Preserve these distinct native paths; do not fabricate a reflected DamageSource.',
    'hydra_terrain_contact': 'Body and tail contact when parent hurtTime==0 push Living (creative Players excluded) by (dx/max(dx²+dz²,.1)*8, .2, dz/max(...)*8) relative to that part center; no hurt or source. Parent excluded; parts are nonLiving. This can occur on both queried body and tail, independently of damage returns. Hydra itself overrides pushability/knockback/doPush; explosion additive motion is a different API and not suppressed by knockback override alone. Server terrain destroys body/tail and !isDead head BBs each AI tick, own BB moved down1 every20 if floor-below solid fraction<.6, and IN_WALL part BB before damage gates. Requires deathTime<=0 and canEntityGrief; EntityUtil helper excludes air, hardness<0 or>=50, Container BE, canEntityDestroy false and canceled destruction event; no added loaded-area gate. WorldUtil.getAllInBB truncates coordinates to int, not floor, then inclusive betweenClosed. Destruction uses drops=false. Fireproof avoids Base lavaHurt ignition/cleanup branch. Home20 supplies encounter location, not ordinary pathing or independent hit-range exemption.',
    'hydra_recovery_save_death': 'ticksSinceDamaged increments in aiStep; custom server AI heal(1) only when counter>1000 and divisible5: first1005, then every5 until forwarded hurt true resets0. Native heal event may alter/cancel; setHealth clamps max; no DamageSource and no head-counter reset from healing. Root bypass damage does not use that reset branch. NBT stores NumHeads BITMASK (not numeric count), HeadNames, native HP/home; only set bits queue IDLE/end action on load, with NO clearing of constructor first-three defaults. Thus dead first-three heads are reactivated on reload even with clear saved bits; DYING saved bits also return idle. Per-head damage, pending action/progress/respawn counter, target, regen counter and secondary flag are unsaved. Noninitial unscheduled DEAD heads remain dead; no accurate mid-regrowth continuation promise. At HP0 native dead rejection remains. Death tick1 cancels all respawn and interrupts nondead heads to IDLE/hurtTime200; ticks20..140 schedule indexes0..6 DYING when nondead; exactly200 remove KILLED, without ordinary Base tickDeath. Peaceful discards head entities then Base restores valid loaded home spawner/discards root. Head death particles, roars, name clearing and bossbar are not new damage.',
    'ur_attributes_defense': 'UrGhast extends BaseTFBoss, NOT Ghast; reuses CarminiteGhastguard attributes only: HP250, follow128, KR1, ordinary default armor0; root14x18 fireproof. No shared HP with minions. isReflectedFireball requires DIRECT instanceof LargeFireball AND causing instanceof Player, no exact DamageType check. Such source skips UrGhast.isInvulnerableTo entirely; otherwise exact IN_WALL, any IS_FIRE, or superclass reject. Native Living dead/client/Fire Resistance/events/cooldown/armor/Resistance/protection still apply. Unlike Ghast minions, no reflected-hit1000 branch: a live reflected custom fireball requests16 (or1.6 in tantrum), subject to mitigation. Ordinary nonfire sources otherwise accepted; no explicit home range gate. Native fireball collision additionally rejects noPhysics targets; a trapped UrGhast may therefore be passed over even when a reflected source would satisfy hurt admission. isOnFirefalse, isPushablefalse and knockback no-op; native separate explosion additive velocity is not that method. Fall tag immunity/empty checkFallDamage; no portal/mount/native Base restrictions. No real combat teleport.',
    'ur_phase_resource': 'damageUntilNextPhase field initializer10 is immediately reset to18 by constructor setInTantrum(false); threshold18 from spawn, not10. Every hurt first divides input by10 if tantrum, snapshots HP, calls super.hurt, then computes actual oldHP-newHP. Server subtracts that actual loss only if hurtTime==hurtDuration, alive after hit and inTrapCounter<=0. Bool is returned but NOT tested for phase accumulation. Shared cooldown higher-damage follow-ups whose hurtTime no longer equals hurtDuration can lose HP without counting; zero-loss/rejected/fully absorbed hits subtract0. No fixed duration or HP percentage. Counter<=0 toggles phase and resets18, discarding overshoot; fatal damage does not toggle. Enter tantrum sets flag/reset, spawns visualOnly lightning near radius18 and calls trap minion producer. Exit toggles flag/reset. setInTantrum(false) called by traps resets18 every trap tick even if already false. NBT saves only inTantrum plus inherited data; load resets progress18, trap timer/cry/timers/path/trap list unsaved. Tantrum reduction precedes the incoming event and native mitigation, so it is not armor and not avoided by armor-bypass tag.',
    'ur_tantrum_tears_weather': 'Custom server AI while tantrum clears target, cries every20..49 ticks (audio only), and each entity tickCount%10==0 performs real damage/control. Query box=UrGhastBB.move(0,-16,0).inflate(0,16,0): same XZ footprint, Y from boss.minY-32 through boss.maxY, NOT a spherical radius or falling-projectile collision. All queried Players with canSeeSkyFromBelowWater at blockPosition request3 ghast_tear, direct=causing=UrGhast. No team/range/LOS-to-boss check; native Player creative/spectator/mitigation still decide. Every CarminiteGhastling in same box receives additive push(0,1,0), with no sky/owner/minion/hurt-success test. Tear source has physical, BYPASSES_ARMOR (transitively shield), DAMAGES_HELMET, NO_KNOCKBACK and AVOIDS_GUARDIAN_THORNS; not projectile/fire/explosion. Any head-slot item invokes native helmet durability processing and scales amount*.75 before cooldown/remaining mitigation (Normal3 ->2.25, not guaranteed HP); Resistance/protection/absorption remain. Boss tear particles have no Entity projectile or hurt callback here. Client tantrum sets TFWeatherRenderer.urGhastAlive; tickRain raises local rain visual by.1 capped1, clears flag, otherwise decays.02; combines max with world rain. No server weather/timer alteration. All summoned lightning has visualOnly=true: no real lightning damage/fire. Particles/rain/audio are separate from server tear checks.',
    'ur_fireball_schedule': 'UrGhastAttackGoal canUse requires target and !tantrum, default Goal scheduling (not requiresUpdateEveryTick); timers count goal tick calls, generally alternate game ticks via Mob.serverAiStep. Start resets attack/prev0; in distanceSquared<4096 and sensing LOS timer pre-history then increment; warn10, fire20 if still !tantrum, reset-40. Out-of-range/LOS decrements only positive timer; stop clears charging. Native nearest-Player mustSee target goal follow128 is separate from firing range64. Each volley spawns3 UrGhastFireball(power1) owner=UrGhast; center aims target midpoint from boss midpoint, spawn look*8.5 plus midpointY+2; two side shots same spawn except no+2 and offsetX/Z plus (randFloat-randFloat)*8. No special damage attribute/enchantment scaling of16. Registered actual entity type is inherited minecraft:fireball, not a Twilight fireball registration.',
    'ur_fireball_impact': 'UrGhastFireball overrides onHit and does NOT call LargeFireball.onHit or Projectile.onHit. Entity-hit server only, except any AbstractHurtingProjectile target: request16 damageSources.fireball(this,owner), then EnchantmentHelper.doPostAttackEffects regardless hurt bool, then explode(source=null,radius power1,fire=canEntityGrief(owner),interaction=NONE) and discard. Excluded projectile target does not explode or discard in that branch. Block-hit calls inherited block projectile callback, then same null-source explosion/discard; its method has no own server guard (normal AbstractHurtingProjectile tick runs both sides); authoritative HP remains server. No extra inherited6 hit or second inherited MOB explosion in live custom path. Impact source minecraft:fireball direct=projectile/causing=owner; null owner uses minecraft:unattributed_fireball factory direct=causing=projectile. Fire/projectile tags, ordinary armor/directional shield/Fire Resistance/Resistance/Fire or Projectile Protection/absorption/cooldown. No direct target ignite call (projectile burning itself is distinct). Ownerless explosion is minecraft:explosion direct=null/causing=null: native difficulty scaling is ALWAYS, not owner-dependent; no source position for ordinary directional shield, and Explosion Protection applies. NONE keeps blocks but fire=true can still set eligible fire in native finalizeExplosion; do not call it no entity damage/no fire. Explosion and16 are distinct attempts sharing cooldown; enchantment callback and explosion are unconditional on first return.',
    'ur_fireball_motion_reflection_reload': 'Native AbstractHurtingProjectile starts movement normalized aim*.1, adds normalized current movement*accelerationPower(.1), then inertia.95 (.8 water) each tick, no mortar gravity. It discards on server when known owner removed or chunk absent; native owner/leftOwner/ray collision/event admission retained, excludes noPhysics targets. UrGhastFireball.shoot method is not used by the native volley producer. Fireball.hurt returns false, so ordinary attack damage does not itself reflect. Minecraft fireball is REDIRECTABLE_PROJECTILE: Player.attack early AIM_DEFLECT transfers owner/direction; incoming native Projectile.onHit can redirect it too. Live custom instance implements ITFProjectile, so pinned TF timed blocking5..40 ticks can AIM_DEFLECT and cancel impact when external shield-parry mod absent. DeflectedByPlayer resets acceleration.1; other generic deflection halves acceleration. Reflection leaves custom16 payload and null-source explosion unchanged. Native Entity save stores minecraft:fireball ID; registry factory recreates LargeFireball on reload, NOT UrGhastFireball (no custom registered type/loader restoration). Owner/leftOwner/shot, native motion, acceleration and ExplosionPower1 persist, but post-load impact becomes vanilla6, inherited projectile redirection/onHit flow, source=fireball MOB explosion, and no ITFProjectile marker for TF parry under parryNonTwilightAttacks=false. Client spawn likewise uses registered vanilla type. This is a static proven factory distinction, not measured runtime damage.',
    'ur_trap_discovery_flight': 'Server scans GHAST_TRAP POIs on firstTick or tickCount%100 at valid home else current position, radius64, any occupancy, requires canSeeSky(trap.above), sorts distance; append unseen. Every60 removes cached positions whose block is not GHAST_TRAP or no sky. FlightGoal MOVE builds/shuffles trap path at canUse; if no traps, four cardinal offsets20 plus center. Start picks next point, Y+=20 when restriction point nonnull, speed parameter1, sets noPhysics=false. On path index wrap, if no trap has>=4 queried CarminiteGhastlings in centered unit box inflated(8,16,8), spawnGhastsAtTraps; count includes nonminions and has no master filter. Traps are not required to be charged/active for spawning/path. Constructor noPhysicstrue; trap also sets true, next flight start can restorefalse. NoClipMoveControl adds normalized displacement*.1*speed each cooldown2..6-style postdecrement interval, no clearance or zero-distance guard. Travel applies water.8/lava.5/air or ground friction*.91 without ordinary fall acceleration, no climb. Tantrum and trap do not install a new speed or halt flight goal; tantrum clears attack target. inTrapCounter set20 and custom AI decrements while clearing target; ordering after native goal tick can matter. Path/counters restart on reload; no teleport.',
    'ur_minion_spawn': 'Entering tantrum and insufficient-ghast flight-path wrap both call spawnGhastsAtTraps: shuffled cached traps, first min(2,size). Each location spawns visualOnly lightning at y+4; loop declares24 tries but increments spawns unconditionally and breaks at6, so exactly6 attempts per selected trap, not24 retries or six guaranteed successes. Position X/Z=trap+(randDouble-randDouble)*4, Y=trap+randDouble*8. Create CarminiteGhastling, makeBossMinion then EventHooks.finalizeMobSpawn(MOB_SUMMONED), call instance checkSpawnRules then addFreshEntity/spawnAnim. Exact inherited Mob.checkSpawnRules returns true; this call does NOT call static CarminiteGhastling.canSpawnHere placement predicate or checkSpawnObstruction. Finalize/add hooks may still prevent actual addition. Static spawn predicate is separately notPeaceful and (MOB_SUMMONED or darkEnough) and checkMobSpawnRules, but not this direct producer gate. No boss reference, UUID owner/master, team, target assignment, shared pool or on-boss-death cleanup is assigned. Native ghastling default HP10/follow16; makeBossMinion sets isMinion=true,wanderFactor.005 (normal4), base maxHP6 then setHealth(max). No scaling from UrGhast HP.',
    'ur_minion_behavior': 'CarminiteGhastling extends CarminiteGhastguard extends native Ghast; its own nearest-Player mustSee selector acquires target, no target inheritance from UrGhast. shouldAttack rejects EXACT Items.PUMPKIN in helmet (not carved pumpkin); within3.5 requires target LOS, otherwise target view-dot >1-.025/distance AND LOS. GhastguardAttackGoal uses same20/-40 default-scheduled counter and64-range LOS; emits ONE ordinary LargeFireball, owner=ghastling, inherited explosionPower default1; after shot chance1/6 clears target. Vanilla projectile requests fireball6 then unconditional post-enchantment; inherited onHit explodes with projectile source/MOB regardless hurt, unlike live boss projectile16/null/NONE. Ghastling is fireproof/fall-immune, normal mitigation otherwise; native Ghast reflected-LargeFireball+Player hurt branch requests1000 then returns true regardless super result (UrGhast does not inherit this branch). Flight uses Ghast collision-checking move control with tiny minion wander, not Ur noClip controller. isMinion saved; loading true calls makeBossMinion AFTER super native HP load, restoring full6 HP and wander. No saved master or despawn bond; native Ghast/monster despawn applies. Minion flag does not restrict trap charge, tantrum lift, boss consumption or local enough-ghasts count.',
    'ur_consume_heal': 'Every server custom AI queries ALL CarminiteGhastlings in bossBB.inflate(1), no owner/minion/team/LOS/liveness predicate added. For each: spawnAnim, discard, then heal(2). It is native LivingEntity.heal (event can cancel/change; HP must>0; setHealth clamps maximum), not direct boss setHealth, no DamageSource and no SHP system. Consumption remains even when heal canceled/full HP. Does not lower/reset damageUntilNextPhase or derive heal from consumed HP/maxHP. Any native CarminiteGhastling in range qualifies, not only this boss spawns. Tantrum upward push can change later delivery to consumption box but is not healing itself.',
    'ur_trap_charge': 'Inactive non-debug ticking trap scans new AABB(blockPos).inflate(10,16,10) for CarminiteGhastlings with deathTime>0, stores unique entity references in dyingGhasts; no minion/master/kill-credit/LOS/sky filter. Same corpse is counted once per trap, can charge multiple traps; list is not pruned on corpse removal. isCharged requires size>=3. Only neighborChanged server, inactive+charged+hasNeighborSignal activates block state and queues event0; charge reaching3 alone does not call activation, so an actual neighbor notification is required. Event0 resets counter and clears list; event1 resets counter only. Active state is block state; counter/list have no custom save/load or sync packet fields, reset on BE reconstruction. Charge visuals client-local can differ from server list; no invented persistent shared soul resource. Active load can restart duration from0 but inactive saved charge is lost.',
    'ur_trap_active': 'Active tick increments counter. Server queries Mob in AABB(pos.above16.center,pos.above16.offset(1,1,1).center).inflate(6,16,6): X/Z pos-5.5..+7.5, Ypos+.5..+33.5. Predicate instanceof native Ghast OR UrGhast (thus ghastling/guard/vanilla ghast); no player/LOS/sky/minion/master test. Every Ur tick first setInTantrum(false) resetting phase18, setInTrap20, noPhysicstrue, setDeltaMovement((x-posX-.5)*-.1,(y-posY-2.5)*-.1,(z-posZ-.5)*-.1). Independent chance1/10 requests ownerless minecraft:generic7 and resets threshold again irrespective bool. Since tantrum already false, no divide10; inTrap>0 excludes hit phase accumulation. Other Ghasts receive same XZ but Ytargetpos+1.5 and chance1/10 generic10. Control is set velocity, independent of hurt/KR, not heal or direct HP subtraction. Generic retains normal armor/Resistance/protection/absorption/cooldown, no source-position directional blocking, no fire/projectile/explosion flag; no Player difficulty here. End active tick atcounter>=120 sets inactive and event1, after that tick effects. Random requests are not guaranteed12 accepted hits; shared cooldown and multiple overlapping traps apply. No ownership retarget, permanent phase lock or automatic minion kill guarantee.',
    'ur_death_persistence': 'Native Base death handling with Ur isDeathAnimationFinished deathTime>=90; dying getDeltaMovement returns(0,-.03,0), no revived HP. die calls Base and adds visualOnly lightning at center; first30 smoke then loot-transfer particles are cosmetic. Ur boss spawner inherits range9 and adds nearest Player Y>spawnerY-4; Hydra spawner range50. Both native spawners set home after normal finalize, and Peaceful Base restoration/discard remains. Unrestricted spawn eggs without home are alternate delivery fixtures, not guaranteed trap availability. Ur health/home and inTantrum persist; residual threshold, trap cache, timer, flight progress and consumed-minion history do not. No DamageType other than ghast_tear is constructed directly by UrGhast; its fireball and trap use vanilla sources.',
    'shared_damage_pipeline': 'All reported numbers are requests, not measured HP. Installed raw1.21.1 and exact NeoForge21.1.244 are compared; source aids alone are not authority. Custom four declarations scale when_caused_by_living_non_player: native Player Peaceful0/Easy min(x/2+1,x)/Normalx/Hard1.5x before Living incoming; nonPlayer has no such Player scaling. Hydra-owned bite48 => Easy25/Normal48/Hard72; flame19=>10.5/19/28.5; mortar18=>10/18/27 until reflected Player owner (no scaling); tear3=>2.5/3/4.5, then native helmet*.75. Ur-owned fireball16 follows same owner-based scaling (9/16/24); reflected Player fireball does not. Native explosions have scaling ALWAYS, including ownerless explosion. Native Living order: invulnerable/client/dead/FireResistance -> incoming hook -> block/freeze/helmet -> shared cooldown -> armor/toughness, Resistance/protection/absorption/damage hooks/HP. True is not identical to HP loss. Explosion radius R requests ((q*q+q)/2*7*(2R)+1), q=(1-distance/(2R))*exposure, within2R and nonzero displacement, no integer floor in installed code. Explosion additive velocity is separately event/EXPLOSION_KNOCKBACK_RESISTANCE governed, independent of hurt result and ordinary knockback override. Explosion start/detonate/impact/enchantment/heal/grief hooks can change delivery. Fire ignition API extends native burn duration; later on_fire damage has its own identity. Bare resource names do not imply armor/shield bypass or real projectile delivery.',
    }
    facts['ur_lightning_world']='Ur phase entry, each selected trap spawn location, and death each create native LightningBolt with visualOnly=true. This suppresses native entity thunderHit and spawnFire, not every server callback: life==2 still powers a LightningRodBlock at strike position, runs copper deoxidation and emits LIGHTNING_STRIKE game event. Native rod outputs15, notifies neighbors and resets after8 scheduled ticks; a correctly wired charged trap can receive a legitimate redstone notification, with no automatic guarantee. Copper first-state conversion and native random cleaning walks are vanilla world changes, not HP damage. Phase entry passes radius18 random seed through ServerLevel.findLightningTargetAround (heightmap/rod/nearby sky-visible Living selection), so final strike need not remain exactly18 away. Spawn producer places bolt at trap x,y+4,z; death at boss position+half-height. Native lightning EntityType is noSave; no persistent bolt/phase resource inferred. These are ordinary native visualOnly-lightning semantics in custom producer locations; include as VANILLA_DIRECT world interaction, not a new damaging storm or source.'
    facts['hydra_mortar_damage']=facts['hydra_mortar_damage'].replace('reflected mortal splash','reflected mortar splash')
    facts['hydra_body_parts']+=' Positioning caveat from complete Hydra methods: aiStep explicitly ticks body and both legs (not tail), repositions body and tail (not legs), and container tick repositions head/necks. No dedicated leg reposition call exists; do not assume all46 parts form correctly placed independent body hitboxes. No runtime positioning result or fix is claimed.'
    facts['ur_death_persistence']=facts['ur_death_persistence'].replace('no real lightning','no lightning damage')
    effects=[];paths=[]
    def add(owner,key,title,classification,keys,classes,nums,gates,relation,alternates):
        eid=f'twilightforest:{owner}_{key}'
        effects.append(dict(id=eid,mod_key='twilightforest',owner=owner,display_name=title,inspection_status='DRAFT',subsection_status='REVIEWED',primary_classification=classification,classification_provisional=False,actual_behavior=[facts[k] for k in keys],components=[dict(primitive=key.upper(),formula='; '.join(facts[k] for k in keys),numerical_parameters=nums,binary_parameters=gates,vanilla_relation=relation)],implementation=native_refs(*classes),primary_test_source='Native '+owner+' boss-spawner encounter; see saved native path and negative controls',alternate_sources=alternates,delivery_paths=[],registry_ids=[],pending=['Whole Twilight semantic closure/final promotion only; this subsection is reviewed.'],unresolved_ambiguities=None))
        return eid
    h='hydra';u='ur_ghast';H='entity/boss/Hydra';C='entity/boss/HydraHeadContainer';M='entity/boss/HydraMortar';U='entity/boss/UrGhast';F='entity/projectile/UrGhastFireball';T='block/entity/GhastTrapBlockEntity';G='entity/monster/CarminiteGhastling'
    hd=add(h,'part_admission','Multipart damage admission','BINARY_MECHANIC',['hydra_body_parts','hydra_admission'],[H,'entity/boss/HydraPart','entity/boss/HydraHead','entity/boss/HydraNeck','entity/TFPart'],{'hp':360,'parts':46,'closed_divisor':8,'mouth_threshold':.5,'range_squared':400,'mortar_range_squared':600},['self/direct/owner/range/dead head before HP','root bypass tag only'],'Native same-source forwarding with custom admission and fixed reduction.',['Native ownerless environmental sources and root bypass source have distinct gates; no fabricated source.'])
    hh=add(h,'head_resource','Head counters and regrowth','CUSTOM_RESOURCE',['hydra_head_resource','hydra_state_machine','hydra_recovery_save_death'],[H,C,C+'$State','entity/boss/HydraPart'],{'initial_heads':3,'maximum_heads':7,'counter_threshold_exclusive':120,'dying':70,'respawn_dead_ticks':140,'birth':20,'roar_start':10,'roar':50},['integer request accumulation independent of HP','pending death and available DEAD head','no cauterization gate'],'Per-head custom counters/state, one boss HP pool.',['Multiple native piercing/area part attempts and reload are separate controls.'])
    hs=add(h,'head_schedule','Head attack scheduling','CUSTOM_CONTROL',['hydra_scheduling','hydra_state_machine'],[H,C,C+'$State','entity/boss/Hydra$1'],{'acquisition_range':48,'factor_normal':.3,'factor_hard':.5,'bite_ticks':7,'flame_ticks':100,'mortar_ticks':25,'cooldown':80},['idle/pending/target/LOS/range/concurrency','secondary predicates differ'],'Custom multi-head AI/counters; not damage itself.',['Secondary native Living targets; zero/one/two available original heads alter bite eligibility.'])
    hb=add(h,'bite','Bite damage and blocking control','CUSTOM_DAMAGE',['hydra_bite'],[C,'network/MovePlayerPacket'],{'request':48,'shield_wear':112,'item_cooldown':200,'blocking_push_y':.15,'post_push_y':.1},['BITING overlap Living','blocking before hurt','post movement ignores hurt bool'],'Custom48 physical area request plus native durability/cooldown and movement calls.',['Native blocking/nonblocking Players and nonPlayer cardinal directions.'])
    hf=add(h,'flame','Flame ray and ignition','CUSTOM_DAMAGE',['hydra_flame'],[C],{'request':19,'burn_seconds':3,'ray_length':30,'candidate_padding':3,'tracking':.04,'hard_tracking':.1},['FLAMING nearest selected entity','self/fireimmune rejected after selection','ignite on hurt true'],'Custom ray geometry/fire source; ordinary burn is separate.',['Eligible nonLiving pickable entities and own-part/fireimmune occluders.'])
    hm=add(h,'mortar','Mortar explosion and fire splash','CUSTOM_DAMAGE',['hydra_mortar_launch','hydra_mortar_damage','hydra_mortar_reflection_save'],[C,M,'events/EntityEvents'],{'request':18,'burn_seconds':5,'blast_radius':.1,'mega_radius':4,'splash_inflate':1,'fuse':80,'gravity':.05,'hurt_reflect_add_fuse':20},['native launch/impact/ground fuse','explode then splash','reflect owner vs source','reload payload reset'],'Native explosion plus distinct custom fire splash and reflection lifecycle.',['Native Player tag reflection, incoming projectile redirection/hurt, grounded reload.'])
    ht=add(h,'terrain_contact','Body pressure and terrain clearing','CUSTOM_CONTROL',['hydra_terrain_contact'],[H,'util/WorldUtil','util/entities/EntityUtil'],{'push_xz_factor':8,'push_y':.2,'minimum_distance_squared':.1,'support_fraction':.6,'support_check_ticks':20},['hurtTime0 body/tail Living','grief/death/helper before terrain removal'],'Independent native push/terrain mutation, no contact damage request.',['IN_WALL part callback and unsteady support are alternate terrain producers.'])
    hr=add(h,'recovery','Delayed HP recovery','CUSTOM_RESOURCE',['hydra_recovery_save_death'],[H,'entity/boss/BaseTFBoss'],{'first_heal_counter':1005,'heal_interval':5,'heal_amount':1,'death_remove_tick':200},['forwarded hurt true resets timer','native heal event and max clamp'],'Custom inactivity clock feeding ordinary heal, separate head counter resource.',['Root bypass hurt and fully absorbed/false forwarded attempts distinguish timer behavior.'])
    uf=add(u,'fireball','Three-fireball volley and lifecycle','VANILLA_LIKE_EXTENDED',['ur_fireball_schedule','ur_fireball_impact','ur_fireball_motion_reflection_reload'],[U,F,'entity/ai/goal/UrGhastAttackGoal','events/EntityEvents'],{'volley':3,'live_impact':16,'reloaded_impact':6,'explosion_radius':1,'fire_counter':20,'reset_counter':-40,'range_squared':4096,'acceleration':.1},['target/non-tantrum/LOS','non-AbstractHurtingProjectile impact','native redirectable/parry admission'],'Native LargeFireball extension changes amount/attribution/impact filters; saved type reverts behavior.',['Reflected live volley, native reload and ghastling ordinary LargeFireball comparison.'])
    up=add(u,'tantrum','Damage-driven tantrum and admission','CUSTOM_RESOURCE',['ur_attributes_defense','ur_phase_resource','ur_death_persistence'],[U,'entity/boss/BaseTFBoss'],{'hp':250,'phase_actual_loss':18,'tantrum_divisor':10,'trap_counter':20,'death_ticks':90},['actual HP loss/hurtTime equality/alive/not trapped','reflected LargeFireball+Player exception'],'Custom phase counter/reduction; normal HP and native mitigation remain.',['Trap-forced exit and saved inTantrum reload reset18.'])
    ut=add(u,'tears','Tantrum tear damage and minion lift','CUSTOM_DAMAGE',['ur_tantrum_tears_weather'],[U,'client/renderer/TFWeatherRenderer'],{'damage':3,'cadence':10,'downward_extent':32,'helmet_factor':.75,'ghastling_push_y':1},['Player under box + sky','ghastling push lacks sky and hurt test'],'Custom server area source; particles/local weather are excluded.',['Covered Player negative control, any native ghastling in box, head-slot item mitigation.'])
    um=add(u,'minions','Native minion summoning and targeting','CUSTOM_CONTROL',['ur_minion_spawn','ur_minion_behavior'],[U,G,'entity/monster/CarminiteGhastguard','entity/ai/goal/GhastguardAttackGoal','entity/ai/goal/GhastguardHomedFlightGoal','entity/ai/goal/GhastguardRandomFlyGoal'],{'max_traps':2,'attempts_per_trap':6,'hp':6,'normal_hp':10,'minion_wander':.005,'normal_wander':4},['cached traps','finalize/add hooks','independent target/gaze','no master identity'],'Custom native summon producer, ordinary Ghast inheritance and fireball attack retained.',['Natural nonminion ghastlings qualify for trap/heal/count; native minion reload restores6.'])
    uh=add(u,'consume_heal','Nearby ghastling consumption and healing','VANILLA_LIKE_EXTENDED',['ur_consume_heal'],[U,G],{'box_inflate':1,'heal_per_entity':2},['any queried ghastling','discard before heal','native heal event/clamp'],'Ordinary heal triggered by custom entity consumption; no source or phase refund.',['Natural or another encounter ghastling, full HP and canceled-heal controls.'])
    ug=add(u,'trap','Ghast trap charge and control','CUSTOM_CONTROL',['ur_trap_charge','ur_trap_active'],['block/GhastTrapBlock',T,U],{'charge_corpses':3,'active_ticks':120,'damage_chance_denominator':10,'ur_request':7,'ghast_request':10,'velocity_factor':-.1},['neighbor notification/charged/signal','Ghast or UrGhast active query','control independent of hurt'],'Custom trap charge/control plus native generic damage; no direct HP subtraction.',['Vanilla Ghast, Ghastguard, natural ghastling and other UrGhast qualify; overlapping/reloaded traps differ.'])
    uv=add(u,'flight','Trap-linked flight and target suppression','CUSTOM_CONTROL',['ur_trap_discovery_flight'],[U,'entity/ai/goal/UrGhastFlightGoal','entity/ai/goal/UrGhastLookGoal','entity/ai/control/NoClipMoveControl','init/TFPOITypes'],{'scan_radius':64,'scan_ticks':100,'prune_ticks':60,'hover_offset':20,'enough_ghastlings':4,'path_fallback_offset':20},['sky-visible cached POI','path wrap insufficient local ghastlings','trap/noPhysics ordering'],'Custom flight/path feeding native motion; no teleport or global immunity.',['Native spawn without home/traps uses fallback path and cannot produce trap-based minions.'])
    ul=add(u,'lightning_world','Visual-only lightning world callbacks','VANILLA_DIRECT',['ur_lightning_world'],[U],{'rod_signal':15,'rod_scheduled_ticks':8,'entry_seed_radius':18,'trap_bolt_y_offset':4},['native bolt strike-position block','visualOnly suppresses damage/fire, not rod/copper','native noSave type'],'Ordinary native lightning rod/copper callbacks; retained because redstone can affect native trap delivery.',['Phase entry, trap spawn and boss death have distinct native placement producers.'])

    def path(owner,key,labels,title,keys,ids,classes,controls):
        pid=f'twilightforest:{owner}_path:{key}'
        paths.append(dict(id=pid,mod_key='twilightforest',owner=owner,status='DRAFT',subsection_status='REVIEWED',labels=labels,source=title,native_delivery=' '.join(facts[k] for k in keys),setup=title+' using actual native entities, equipment, spawning and callbacks; never fabricated sources or direct HP edits.',effect_ids=ids,implementation=native_refs(*classes),future_controls=controls))
        for e in effects:
            if e['id'] in ids:e['delivery_paths'].append(pid)
    for key,title,keys,ids,cl,controls in [
      ('open_head','Native hit on living open head',['hydra_admission'],[hd,hh],[H,C],['mouth>.5','HP and counter separate','amount fractional truncation']),
      ('closed_head','Native hit on closed head',['hydra_admission'],[hd,hh],[H,C],['round(amount/8)','mouth=.5 boundary','armor bypass still divided']),
      ('body_neck','Native body, leg, tail and neck hits',['hydra_body_parts','hydra_admission'],[hd],[H,'entity/boss/HydraPart'],['no head counter','dead neck reject','root gate distinct']),
      ('owner_range','Native nearby/distant owners and returned mortar',['hydra_admission'],[hd,hm],[H,M],['400 vs600 squared','ownerless skips range','self and own-part identity']),
      ('overlap','Native piercing arrow or area hitting several parts',['hydra_body_parts','hydra_admission'],[hd,hh],[H,'entity/TFPart'],['one parent cooldown','rejected HP increments head counter','part-specific native arrow return']),
      ('root','Native root environmental and bypass damage',['hydra_admission'],[hd,hr],[H],['only bypass-invulnerability root gate','fire immunity','root does not reset regen timer']),
      ('head_regrowth','Native head counter crossing and regrowth',['hydra_head_resource','hydra_state_machine'],[hh,hs],[H,C],['120 vs121','DYING then DEAD countdown','one extra available head','no boss heal']),
      ('head_reload','Native Hydra save/load during head loss',['hydra_recovery_save_death'],[hh,hd,hr],[H,C],['bitmask not count','first-three defaults resurrect','unsaved counters/timers']),
      ('primary','Native main-target head selection',['hydra_scheduling'],[hs],[H,C],['three-head bite restriction','pending vs current concurrency','Hard factors']),
      ('secondary','Native alternate Living target selection',['hydra_scheduling'],[hs],[H,C],['head0 excluded','no primary cap/above check','secondary skips cooldown']),
      ('bite_player','Native bite with blocking/nonblocking Player',['hydra_bite'],[hb],[C,'network/MovePlayerPacket'],['112 wear/200 cooldown before hurt','two additive push packets if blocking','false damage still control']),
      ('bite_mob','Native bite on nonPlayer Living',['hydra_bite'],[hb],[C],['cardinal knockback argument order','hook/KR','seven attempts shared cooldown']),
      ('flame','Native flame ray and successful ignition',['hydra_flame'],[hf],[C],['moved candidate box','nearest winner','hurt true ignite3']),
      ('flame_occlusion','Native flame with self/fireimmune or block obstruction',['hydra_flame'],[hf],[C],['postselection reject does not retarget','block hit not hard clipped endpoint','Fire Resistance']),
      ('mortar_air','Native mortar entity and side-face collision',['hydra_mortar_launch','hydra_mortar_damage'],[hm],[C,M],['owner filter','same-owner mortar condition','explosion then18']),
      ('mortar_ground','Native ordinary mortar top landing and fuse',['hydra_mortar_launch'],[hm],[M],['81 grounded checks','multiply result ignored','airborne fuse paused']),
      ('mortar_mega','Native mortar fired when head lacks target LOS',['hydra_mortar_launch','hydra_mortar_damage'],[hm],[C,M],['radius4','resistance cap .8 exclusions','native grief hooks']),
      ('mortar_player_reflect','Native Player melee reflection of mortar',['hydra_mortar_reflection_save','hydra_admission'],[hm,hd],[M,H],['AIM early return','fuse and grounded state unchanged','owner range and shared cooldown']),
      ('mortar_projectile_reflect','Native incoming projectile redirect/hurt on mortar',['hydra_mortar_reflection_save'],[hm],[M],['caller onHit behavior','hurt fuse+20/speed1.5 only if reached','Living vs nonLiving causing']),
      ('mortar_reload','Native grounded/mega mortar save/load',['hydra_mortar_reflection_save'],[hm],[M],['owner/onGround persist','fuse80 mega false','no TF parry with pinned config']),
      ('body_pressure','Native body/tail overlap and terrain pressure',['hydra_terrain_contact'],[ht],[H,'util/WorldUtil','util/entities/EntityUtil'],['no HP source','hurtTime0','negative-coordinate truncation','grief/helper veto']),
      ('heal_death','Native inactivity, forwarded hits and boss death',['hydra_recovery_save_death'],[hr,hh],[H,'entity/boss/BaseTFBoss'],['1005 then every5','heal event/fullHP','200 removal and respawn canceled'])]:
        path(h,key,['BOSS_ATTACK','OTHER'],title,keys,ids,cl,controls)
    for key,title,keys,ids,cl,controls in [
      ('volley','Native three-shot Ur-Ghast volley',['ur_fireball_schedule','ur_fireball_impact'],[uf],[U,F,'entity/ai/goal/UrGhastAttackGoal'],['range64 LOS','goal call counters','16 then ownerless radius1']),
      ('fireball_block','Native custom fireball block/projectile collision',['ur_fireball_impact'],[uf],[F],['AbstractHurtingProjectile target excluded','block callback/NONE fire','no inherited6']),
      ('fireball_reflect','Native Player or timed shield reflection',['ur_fireball_motion_reflection_reload','ur_attributes_defense'],[uf,up],[F,U,'events/EntityEvents'],['transferred owner','LargeFireball+Player predicate','no1000 boss hit','noPhysics collision gate']),
      ('fireball_reload','Native saved live custom fireball reloaded',['ur_fireball_motion_reflection_reload'],[uf],[F],['minecraft:fireball factory','6/MOB/source restored','no ITF marker']),
      ('phase_loss','Native untrapped normal/tantrum damage',['ur_phase_resource','ur_attributes_defense'],[up],[U],['spawn threshold18','actual HP not request','hurtTime equality','overshoot/fatal loss']),
      ('phase_reload','Native tantrum save/load',['ur_phase_resource','ur_death_persistence'],[up],[U],['flag persisted','remaining counter reset18','no timer duration']),
      ('tears_player','Native sky-exposed Player under tantrum box',['ur_tantrum_tears_weather'],[ut],[U],['box not projectile','helmet*.75/wear','armor/shield bypass','no tear knockback']),
      ('tears_cover','Native covered/outside Player and in-box ghastling',['ur_tantrum_tears_weather'],[ut],[U],['sky negative control','ghastling lift no sky','visual rain not server weather']),
      ('minion_entry','Native tantrum trap minion spawn',['ur_minion_spawn'],[um],[U,G],['two traps six attempts each','instance spawn check true','no obstruction or master assignment']),
      ('minion_wrap','Native flight path wrap replenishment',['ur_trap_discovery_flight','ur_minion_spawn'],[um,uv],[U,'entity/ai/goal/UrGhastFlightGoal'],['any trap>=4 suppresses replenishment','nonminions count','zero traps zero spawn']),
      ('minion_attack','Native minion targeting and ordinary fireball',['ur_minion_behavior'],[um,uf],[G,'entity/monster/CarminiteGhastguard','entity/ai/goal/GhastguardAttackGoal'],['independent Player/gaze/LOS','exact pumpkin not carved','vanilla6 then owned MOB explosion']),
      ('minion_reload','Native damaged summoned ghastling save/load',['ur_minion_behavior'],[um],[G],['isMinion persists','makeBossMinion resets health6','no boss death linkage']),
      ('consume','Native minion/nonminion enters boss consumption box',['ur_consume_heal'],[uh,um],[U,G],['discard before heal2','fullHP/canceled heal still consume','no phase refund']),
      ('trap_charge','Native ghastling deaths and redstone neighbor event',['ur_trap_charge'],[ug],['block/GhastTrapBlock',T],['three unique corpse references','multiple traps can count','charge alone no activation']),
      ('trap_boss','Native charged active trap below Ur-Ghast',['ur_trap_active'],[ug,up,uv],[T,U],['force normal before generic7','20 timer/18 reset','velocity independent of hurt']),
      ('trap_ghasts','Native active trap with other Ghast subtypes',['ur_trap_active'],[ug,um],[T],['generic10 chance1/10','Ytarget1.5','no owner/minion filter','not Player damage']),
      ('trap_reload','Native inactive-charged/active trap reload',['ur_trap_charge','ur_trap_active'],[ug],[T,'block/GhastTrapBlock'],['charge list/counter unsaved','active state persists','duration can restart']),
      ('lightning_entry','Native tantrum-entry lightning world callbacks',['ur_lightning_world'],[ul,up],[U],['native strike target search','no damage/fire','rod15 for8 ticks']),
      ('lightning_spawn','Native trap-spawn lightning world callbacks',['ur_lightning_world'],[ul,um],[U],['fixed trapY+4','native strike block','redstone notification only if actually delivered']),
      ('lightning_death','Native boss-death lightning world callbacks',['ur_lightning_world'],[ul],[U],['boss midpoint position','no damage/fire','noSave type']),
      ('flight_death','Native home/no-home flight, trap suppression and death',['ur_trap_discovery_flight','ur_death_persistence'],[uv,up],[U,'entity/ai/goal/UrGhastFlightGoal','entity/ai/control/NoClipMoveControl'],['POI/sky prune','noPhysics timing','no teleport','90 death descent/no real lightning'])]:
        path(u,key,['BOSS_ATTACK','OTHER'],title,keys,ids,cl,controls)
    # Meaningful delivery labels supplement the detailed, distinct native cases.
    for p in paths:
        key=p['id'].split(':')[-1]
        if any(x in key for x in ['mortar','fireball','volley','overlap']):p['labels'].append('PROJECTILE')
        if any(x in key for x in ['bite','head','body_neck']):p['labels'].append('MELEE')
        if any(x in key for x in ['tears','trap','flame','pressure']):p['labels'].append('AOE')
        if any(x in key for x in ['reflect','player']):p['labels'].append('ACTIVE_ITEM')

    tags={};resources=read_json(WORK/'twilightforest/resources.json')
    for r in read_json(OUT/'vanilla-evidence/royalvariations.json')['resources']:
        if '/tags/damage_type/' in r['entry'] and 'data' in r:tags[r['entry'].split('/')[1]+':'+r['entry'].split('/tags/damage_type/')[1][:-5]]=list(r['data']['values'])
    for p,v in resources.items():
        if '/tags/damage_type/' in p:tags.setdefault(p.split('/')[1]+':'+p.split('/tags/damage_type/')[1][:-5],[]).extend(v['data']['values'])
    def values(t,seen=()):
        if t in seen:return set()
        out=set()
        for x in tags.get(t,[]):
            x=x['id'] if isinstance(x,dict) else x
            out.update(values(x[1:],seen+(t,)) if x.startswith('#') else [x])
        return out
    profiles=[]
    for name,cl,method,amount,identity,mitigation in [
      ('hydra_bite',C,'executeAttacks','48 each BITING tick; pre-hurt shield wear/control separate','direct=causing=Hydra','Physical; ordinary armor/Resistance/protection/absorption/cooldown; pre-hurt stop-use normally prevents block, no bypass tag.'),
      ('hydra_fire',C,'executeAttacks','19 per eligible nearest winner; true=>ignite3 seconds','direct=causing=Hydra','Fire; ordinary armor/directional shields/Fire Resistance/Resistance/Fire Protection/absorption/cooldown; no projectile or explosion tag.'),
      ('hydra_mortar',M,'detonate','18 in BB.inflate1 AFTER separate native explosion; true=>ignite5 seconds','direct=HydraMortar; causing=current owner (nullable)','Fire; normal armor/shield/Fire Resistance/Resistance/protection/absorption/cooldown; not explosion or projectile-tagged; Hydra exact exception/self/range/part rules retained.'),
      ('ghast_tear',U,'doTantrumDamageEffects','3 every tickCount%10 in box with sky; helmet factor.75 before cooldown','direct=causing=UrGhast','Bypasses armor and shield, damages helmet, no knockback, physical; Resistance/protection/absorption/cooldown remain; not fire/projectile/explosion.')]:
        rid='twilightforest:'+name
        profiles.append(dict(type=rid,status='USED',callers=[dict(entry='twilightforest/'+cl+'.class',method=method)],amount=amount,direct_and_causing_entities=identity,tags=sorted(t for t in tags if rid in values(t)),declaration=resources['data/twilightforest/damage_type/'+name+'.json']['data'],mitigation=mitigation,difficulty=facts['shared_damage_pipeline']))
    comparison=['vanilla-evidence/'+BATCH+'.json','reference-evidence/'+BATCH+'-244.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','vanilla-evidence/twilight-lich-tags.json','vanilla-evidence/twilight-naga-data.json','vanilla-evidence/twilight-naga.json','reference-evidence/twilight-naga-244.json','reference-evidence/twilight-lich-244.json','reference-evidence/twilight-frosted-244.json','vanilla-evidence/twilight-minoshroom-knight.json','reference-evidence/twilight-minoshroom-knight-244.json','reference-evidence/cult-loader-244.json','config-evidence/twilightforest-common.json','twilightforest-hydra-urghast-caller-scan.json']
    section=dict(schema='tno.external_effects.semantic_section.v1',baseline=BASELINE,mod_key='twilightforest',checkpoint=CP,starting_sha=START,status='REVIEWED_SUBSET_NOT_MOD_COMPLETE',subsection_decision=DECISION,semantic_coverage_complete=False,promoted_to_catalog=False,effects=effects,paths=paths,damage_profiles=profiles,semantic_closure=facts,boss_states={'hydra':'SEMANTIC_REVIEW_COMPLETE','ur_ghast':'SEMANTIC_REVIEW_COMPLETE'},closure_checklist={k:True for k in ['multipart_vs_HP','head_states_regrowth','all_attack_paths','source_entities_tags_mitigation','hurt_return_dependencies','reflection_reload','tantrum_counter','minions_master_absence','trap_charge_control','healing_API','movement_terrain','death_persistence','caller_census','classification','exclusions']},
      comparison_evidence=[dict(evidence_file=p,sha256=sha256(OUT/p)) for p in comparison],source_registration_evidence=native_refs('init/TFEntities','events/RegistrationEvents','init/TFPOITypes','block/entity/spawner/HydraSpawnerBlockEntity','block/entity/spawner/UrGhastSpawnerBlockEntity','block/entity/spawner/BossSpawnerBlockEntity'),
      vanilla_sources=[dict(type='minecraft:fireball',producer='Live Ur custom impact16, minion/reloaded vanilla impact6',identity='direct=projectile, causing=owner',tags=sorted(t for t in tags if 'minecraft:fireball' in values(t))),dict(type='minecraft:unattributed_fireball',producer='Same native factory with owner null',identity='direct=causing=projectile',tags=sorted(t for t in tags if 'minecraft:unattributed_fireball' in values(t))),dict(type='minecraft:explosion',producer='Ur custom null-source explosion; ownerless mortar/native fireball explosion',identity='Ur null/null; projectile direct with null indirect owner otherwise',tags=sorted(t for t in tags if 'minecraft:explosion' in values(t))),dict(type='minecraft:player_explosion',producer='Owned mortar/minion/reloaded fireball native explosion with Living owner',identity='direct=projectile, causing=Living owner; name does not require Player',tags=sorted(t for t in tags if 'minecraft:player_explosion' in values(t))),dict(type='minecraft:generic',producer='Trap random7 Ur or10 other Ghast',identity='direct=null,causing=null',tags=sorted(t for t in tags if 'minecraft:generic' in values(t))),dict(type='minecraft:on_fire',producer='Later native burning after successful custom ignition',identity='ownerless subsequent vanilla source',tags=sorted(t for t in tags if 'minecraft:on_fire' in values(t)))],
      damage_census=dict(total_custom_declarations=40,previous_reviewed_profiles=9,new_used_profiles=4,reviewed_profiles_after=13,remaining_profiles=27,remaining_disposition='Unfinished unrelated caller semantics, not unused. Four requested profiles USED; no unsupported DECLARED_BUT_NO_COMBAT_CALLER_PROVEN.'),
      exclusions=['No package per Hydra head/neck: one forwarding system and one head-counter system; body HP remains single pool.','Hydra sounds/death particles/name clearing/bossbars and Ur local rain/tear particles/loot-transfer are not extra damaging effects. Native visualOnly-lightning rod/copper interactions are explicitly retained separately.','Ordinary minion vanilla fireball and generic trap mitigation are compared explicitly; no invented custom DamageType for them.','Food/loot/trophy/progression rewards and unrelated terrain weather/enforcement are outside these combat boss closures.','Ownerless explosion, custom fire splash, head counter and HP effects remain separate. No runtime HP/SHP result or pack-wide compatibility guarantee is claimed.'],
      fixture_groups=['Native Hydra spawner/parts, open/closed/dead states, owner-distance/source/control overlap, counter/HP and reload.','Native Hydra primary/secondary bites/flame/mortar, shield controls, terrain, reflection and fuse/reload differences.','Native Ur volley live/reflected/reloaded, normal/tantrum actual-loss accounting, under-sky tears and visual-only weather controls.','Native Ur minion production/target/fireball/reload, independent natural ghastling and consumption/heal-event controls.','Naturally charged trap with real ghastling deaths/redstone, boss/ordinary Ghast query, control vs hurt, save/load and overlapping traps.'],
      compatibility_scope='Installed Twilight4.8.3345 + raw Minecraft1.21.1 + exact NeoForge21.1.244. Protected existing four compat scans reused; generic source/owner/recipient hooks stay conditional. No runtime boss/L2 or integration tests, and no production/balance/fix changes.',counts=dict(mechanic_packages=len(effects),delivery_cases=len(paths),classification_totals=dict(Counter(e['primary_classification'] for e in effects)),per_boss={o:dict(packages=sum(e['owner']==o for e in effects),paths=sum(p['owner']==o for p in paths)) for o in [h,u]},review_required=0,new_custom_types_resolved=4),exact_next_task=NEXT,**boundary_flags())
    write_json(OUT/'semantic-sections/twilightforest-hydra-urghast.json',section)
    prior=read_json(OUT/'partial-drafts/twilightforest-r2f5-partial.json');draft=deepcopy(prior);draft.update(checkpoint=CP,starting_sha=START,effects=prior['effects']+effects,paths=prior['paths']+paths)
    write_json(OUT/'partial-drafts/twilightforest-r2f6-partial.json',draft)
    review=read_json(OUT/'mod-reviews/twilightforest.json');review.update(checkpoint=CP,scope='Frosted, Lich, Naga, Minoshroom, Knight Phantom, Hydra and Ur-Ghast complete subsections; whole Twilight PARTIAL with zero promotion.',draft_file='partial-drafts/twilightforest-r2f6-partial.json',notes_file='semantic-sections/twilightforest-hydra-urghast.json',draft_mechanic_count=len(draft['effects']),draft_path_count=len(draft['paths']),exact_next_task=NEXT);write_json(OUT/'mod-reviews/twilightforest.json',review);refresh(CP)
    for f in ['effect-catalog.json','effect-sources.json','delivery-path-matrix.json','vanilla-comparison.json','behavior-primitives.json']:
        d=read_json(OUT/f);d.update(checkpoint=CP,unfinished_review=dict(mod_key='twilightforest',status='PARTIAL',draft_file=review['draft_file'],promoted_records=0));write_json(OUT/f,d)
    decision=read_json(OUT/'research-decision.json');decision.update(checkpoint=CP,hydra_urghast_decision=DECISION,next_task=NEXT,save_mode=False,save_reason='Updated user workflow on 2026-09-22 removes the old five-hour percentage boundary. Current active usage is healthy (0% of weekly window, no secondary window reported). Protect each complete subsection before continuing. Hydra/Ur-Ghast complete; Alpha Yeti/Snow Queen unstarted until R2f6 push/live verification.',recovery_hydra_urghast=dict(local_start=START,live_remote_start=START,working_tree_start='CLEAN',divergence='0/0',newer_work=False,restarted_research=False));decision['checkpoints']['R2f5-minoshroom-knight-complete']=START;decision['checkpoints'][CP]='Self: exact SHA supplied after push/live verification.';write_json(OUT/'research-decision.json',decision)
    lines=['# R2f6 - '+DECISION,'','Installed Twilight4.8.3345 / Minecraft1.21.1 / NeoForge21.1.244. Static installed-code review only; no runtime boss tests. All five earlier subsections preserved.','',f"{len(effects)} new packages / {len(paths)} delivery cases; Twilight combined {len(draft['effects'])}/{len(draft['paths'])}, PARTIAL, zero promoted. REVIEW_REQUIRED0.",'','## Native mechanics','']
    for key,value in facts.items():lines += ['### '+key.replace('_',' ').capitalize(),'',value,'']
    lines += ['## Packages','','| Package | Owner | Classification |','|---|---|---|']
    for e in effects:lines.append('| '+e['display_name']+' | '+e['owner']+' | '+e['primary_classification']+' |')
    lines += ['','## Damage caller disposition','','| Type | Request | Source entities |','|---|---|---|']
    for p in profiles:lines.append('| '+p['type']+' | '+p['amount']+' | '+p['direct_and_causing_entities']+' |')
    lines += ['','All four USED;13/40 custom profiles reviewed,27 unfinished, not unused. All tags, delivery cases and controls are in [the semantic section](semantic-sections/twilightforest-hydra-urghast.json). Requests/hurt returns/counters are not measured HP.','','## Exclusions and future fixtures','']+['- '+s for s in section['exclusions']]+['']+['- '+s for s in section['fixture_groups']]
    lines += ['',section['compatibility_scope'],'','[Native witnesses](native-evidence/'+BATCH+'.json), [raw comparisons](vanilla-evidence/'+BATCH+'.json), [exact loader](reference-evidence/'+BATCH+'-244.json), [caller scan](twilightforest-hydra-urghast-caller-scan.json), [integrity](twilightforest-hydra-urghast-integrity.json), [full validation](r2f6-hydra-urghast-validation.json).','','Exact next task: '+NEXT,'']
    (OUT/'twilightforest-hydra-urghast-review.md').write_text('\n'.join(lines),encoding='utf-8')
    print(json.dumps(section['counts'],indent=2))


if __name__=='__main__':build()
