"""R2g5b shared Dragon combat; preserve native amount, source and admission boundaries."""
from catalog_common import *
from iceandfire_combat_common import save_section
START='bc5f76c9cc1d4c738f286c847822623f00436fce'
CP='R2g5b-dragon-body-combat-complete'
STEM='iceandfire-r2g5b-dragon-combat'
NEXT='R2g6: Cockatrice gaze/debuff/damage and tame/control semantics plus native Cockatrice Scepter; reuse Gorgon looking/blindfold and Siren MiscData scaffolding without repeating them. Then Death Worm/Cyclops and remaining combat families. No runtime/L2/Stage/production.'
FACTS={
 'entry':'Dragon.tick runs shared common update, then for live model on server updateDragonServer (including rider update), then updateDragonAttack. Native subtype aiStep and flying proximity may also start attack animations. DragonAIAttackMeleeGoal requires AdvancedPathNavigate, live target, canMove and not flying/hovering to start; native reachSquared=4*dragonWidth^2+targetWidth, cooldown20. Tick LOS controls navigation update, not the final reach/cooldown attack call. The three installed Fire/Ice/Lightning doHurtTarget overrides select animation/possible mount and return false; they do not call the base direct-damage override. DragonBase.doHurtTarget is a fallback method, not an extra guaranteed hit for these subtypes.',
 'body_attacks':'Shared updateDragonAttack requires playing attack animation,current target,dragon LOS and distance<renderSize*.2574*2+2. Bite requests int(current ATTACK_DAMAGE) at each animation tick16..24; Tail at21..29 adds independent knockback(ageTier*.6); Wing at15/25/35 similarly. All attackTarget booleans discarded here; tail/wing control is not hurt-success gated. Attack randomization does not reset the current animation, so preserve repeated requests and normal i-frames rather than assuming one hit per animation. attackTarget uses mob_attack direct=causing=Dragon if rider null; with current Player rider uses indirect_magic direct=Dragon,causing=rider. No Iaf custom dragon elemental source or weapon/enchantment callback is synthesized.',
 'tackle':'AI updateDragonServer, while flying with target and tackling, checks asymmetric box.expandTowards(2,2,2) intersection, requests ageTier*3 through attackTarget(target,null), randomizes and lands; no additional LOS at this damage call. Rider travel arms tackling when aggressive,pitch>-5,velocity length>1; updateRider tackling scans box.expandTowards(2,2,2), explicit predicate target!=rider && Living, and calls attackTarget(victim,rider,tier*3) each eligible update. No team/LOS predicate is added to that rider victim lambda; default-query exclusions must not be assumed for explicit-predicate overload. Grounded not-flying clears tackle but the current entered block still continues. Ordinary damage/creative/PVP hooks decide acceptance.',
 'rider_bite':'Native control bit aggression from real authorized rider update calls riderLookingAtEntity at range=tier+bounding-box width, starts Bite animation if needed and immediately requests int ATTACK_DAMAGE; no animation-frame or item attack cooldown gate here. Ray helper filters onSameTeam/pickable/Living/!self/!allied/!dead-mob, inflates target AABB by pickRadius+2, has no world LOS clip, and uses AABB.clip.orElse(Vec3.ZERO) for a miss. Origin/shared-root cases remain native. Additional !hasSameOwner gate follows selection. Config canHealFromBiting(snapshotfalse) and hurt==true enable heal(raw requested integerDamage*.1), not observed HP loss. The DreadQueen branch contains a Player-only attack condition that ordinary DreadQueen controller cannot satisfy; no fabricated rider fixture.',
 'shake_prey':'All three subtype SHAKE_PREY branches random1/2, direct collider path, preyWidth<dragonWidth*.5, no controller, ageTier>1, not DragonBase and !isAnimaniaMob (helperfalse) start SHAKEPREY and call prey.startRiding(dragon); return ignored. Native mount admission remains required: already-riding/cycle guards, canMountEntity event, prey canRide (ordinary sneaking/boarding cooldown) and Dragon canAddPassenger (<2 passengers). Otherwise fallback Bite. positionRider handles controller separately, all other passengers via updatePreyInMouth. It forces shake animation, positions prey near mouth until animationTick>55, then requests2*float ATTACK_DAMAGE via mob_attack direct=causing=Dragon. hurt==true and canHealFromBiting enables heal(raw requestedDamage*.5). Nonplayer prey increments hunger1 independent of hurt, then all prey receive stopRiding. Native dismount canMountEntity(false) may veto, so a retained passenger can be processed again; do not assert unconditional release. No direct kill or HP/SHP subtraction.',
 'roar':'Server random1/500 while awake/live or hurt-entry random1/4 with causing entity can call roar before final damage admission. At tier>3, size=(tier-3)*30, query box.expandTowards(size,size,size) is directional, not symmetric radius. Living recipients except same/higher-tier dragons: owner or same-owner pet gets StrengthI, others WeaknessI. Epic random branch duration50*size and checks native HEAD earplugs only for hostile Weakness; normal duration30*size has NO earplug test. No LOS or Siren/SpiritualNull helper. Effect returns ignored; standard effect immunity/cures and attribute effects remain. Animation already playing does not prevent another effect application. No numeric Stage multiplier on radius/duration/amplifier.',
 'attributes':'All three constructors use damage endpoints1 and1+configattackDamage(snapshot18), health endpoints.04*configmaxHealth andconfigmaxHealth(snapshot28..700), speed0.15..0.4 and armor1..20. updateAttributes uses age=min(getAgeInDays,125) for rounded maxHP/attack and interpolated speed, but armor uses getAgeInDays without125cap. Server armor modifier replaces same UUID/id with permanent ADD_VALUE of1+sum equipped DragonArmor type protection; reload/equipment/growth can recalculate. getAgeInDays clamps ticks/24000 to0..tamedConfigMax(snapshot128) or128; native tier boundaries25/50/75/100. Native age is not TNO Stage. Keep these attributes as native baselines and apply damage scaling once downstream, not again at each attribute refresh.',
 'resources':'Hunger setter clamps0..100; server natural aging increments AGE_TICKS unless agingDisabled, refreshes attributes each24000; hunger decrements1 per configured positive hungerTickRate(snapshot3000) while>0. No starvation HP callback appears in these shared logic consumers. Saved age,hunger,model-death and death-stage are restored; body damage/health current native values persist through ordinary entity lifecycle. Spawn initialization and growth are not recurring heal effects; ordinary progression/items beyond these combat changes excluded.',
 'healing':'Ordinary owner feeding uses valid FoodUtils food points F>0 and hunger<100 OR HP<max; writes setHealth(min(maxHP,int(HP+F/10))), increases hungerF and consumes1 if noncreative. Native AI dropped-food goal hungry<100/canMove (prioritizeItems disallows hunger>=60) selects live food item and on mouth/body proximity writes setHealth(min(maxHP,int(HP+F))), hunger+F, consumes1. Exact Uranus FoodUtils requires FOOD component, MEAT or allowed FISHES for meatOnly, yields nutrition*10. Thus dropped food restores10 times hand-fed nominal HP. These writes bypass LivingHealEvent; native setHealth clamp and installed overrides still apply. Meal owner branch age<cap re-enables growth, grows1,hunger+20 and heal(min(currentHP,floor(maxHP/2))); sickly meal when not agingDisabled heals(maxHP),hunger+20,disables aging. Creative meal live-model branch can tame and uses same min(currentHP,halfmax) heal. Actual heal calls pass native LivingHealEvent and require currentHP>0. No direct SHP write is present; downstream mod interactions untested.',
 'defenses':'DragonBase.hurt rejects model-dead unless SAME DamageSource object as damageSources.fellOutOfWorld(), controller-caused damage while ridden, and while dragon itself passenger either msgId contains arrow or causing entity equals its vehicle. Rejects exact IN_WALL/FALLING_BLOCK/CRAMMING types before parent. Positive damage may wake/set hostile Player target; roar may occur before later rejection. checkFallDamage empty prevents that ordinary fall path, not a universal FALL-source hurt veto. Only Fire Dragon EntityType is fireImmune; Ice/Lightning registry flagsfalse. Lightning.isInvulnerableTo compares source message id with vanilla lightningBolt message id, calls heal15 and FireResistanceII20ticks then returns true; it is not a broad custom-lightning/tag immunity. This callback can run on invulnerability queries, not exclusively admitted HP hits. Native effects/health hooks and external overrides remain.',
 'death_and_compat':'tickDeath sets deathTime0,modelDead=true,ejects passengers and only removes once deathStage>=ageDays/5; live server attacks stop for dead model. die calls super then changes its OWN hunger by FoodUtils.getFoodPoints(this), not a proven attacker feeding callback. Existing tensura_iaf IafHandler vetoes skill plunder, energy drain and spiritual hurt on model-dead or deathStage>0 dragons. Keep normal hurt/death and native corpse disposal distinct; no corpse farming or resurrection fix is authorized.',
 'multipart':'Native DragonPart delegates to MultipartPart.hurt(source,amount*partMultiplier) on parent and returns parent hurt; no separate part HP budget. Head and final tail1.5, neck/other tail1, wings.5 from updateScale. Part override isInvulnerableTo lists fall,drown,inwall,fallingblock,lava,IS_FIRE but own hurt does not invoke it before parent delegation. Client Player-caused part hurt also sends native MultipartInteract payload; receiver nonnullPlayer/serverLivingParent/distance<100/dmg>0 calls parent.hurt(mob_attack(player),supplied amount), otherwise interact. Separate ServerEvents Player ATTACK_ENTITY handles parts via player.attack(parent), plus native PlayerHitMultipart packet on client; its receiver repeats player.attack(parent) with distance<100. Runtime must count server accepted events/actual source and check duplicate delivery, not scale at both part and parent. No packets are fabricated in research.',
 'census_disposition':'Dragon primitive caller census: DragonBase/Logic/Lightning/AIfood/Multipart and receiver reviewed here; DragonCharge/manager reused fromR2g2b/R2g5a; DragonEgg hatching hunger and cave/roost spawn HP are initialization/progression-only exclusions; DragonSkull hurt is decorative break-to-item utility; DragonFleshItem consumption is explicitly deferred to special equipment/consumables, not lost. Shared network and registry methods contain unrelated families whose presence is not review completion.',
 'exclusions':'Navigation detail, ordinary travel handling, armor models, corpse loot/acquisition, recipes, taming progression, menu/storage, structure layout and rendering excluded after identifying the actual combat callbacks. Grab position change/mount admission, health writes and source-changing multipart route are retained because they affect compatibility. No runtime boss/L2 tests or production/Stage change.'
}

FACTS['target_admission']='Native rider DRAGON_STRIKE key calls attack->control bit2; isAggressive reads bit2, distinct from breath bit3. Protected packet validates actual owner/passenger before state update. Natural target registration preserves owner retaliation and HurtBy goals; non-tamed goal calls native parent search then permits sleeping Player only within squared16, other targets only awake. Registered Player filter requires noncreative and neutralToPlayer=false; nonplayer hunger random gate plus other type/canHostilesTarget/isAlive/shouldTarget. Species shouldTarget selects other eligible smaller live dragon types while wild, otherwise Player/species target tag (Ice also WaterAnimal) and wild villagers. Generic DragonAITargetGoal has an actual old-target-nonnull/different-class check BEFORE super.canUse; do not assume it independently acquires from a null target. It also rejects command1/2,sleeping, wild roosting, checks size, same-owner/live-dragon and tame-player restrictions, and food-positive/movable/hunger<90/native tame-target exclusions. Keep native acquisition in future positive controls; do not repair this ordering or fabricate a target event.'

def save():
    routes=[('bite','MELEE'),('tail','MELEE'),('wing','AOE'),('ai_tackle','MOB_ATTACK'),('rider_tackle','MOB_ATTACK'),('rider_bite','MELEE'),('shake_prey','MOB_ATTACK'),('normal_roar','PASSIVE_AURA'),('epic_roar','PASSIVE_AURA'),('hand_food','ACTIVE_ITEM'),('dropped_food','OTHER'),('dragon_meal','ACTIVE_ITEM'),('sickly_meal','ACTIVE_ITEM'),('creative_meal','ACTIVE_ITEM'),('lightning_absorb','OTHER'),('body_defense','OTHER'),('multipart_damage','OTHER'),('multipart_player_attack','MELEE'),('age_equipment_refresh','OTHER'),('corpse','OTHER')]
    paths=[dict(id='iaf:dragon:body:'+name,labels=[label],native_path=name+'; exact caller/admission in facts',runtime_variants=['AI vs current legitimate rider/source identity','native hurt/effect/heal rejection where applicable']) for name,label in routes];ids={name:p['id'] for (name,_),p in zip(routes,paths)}
    def m(id,name,classification,kinds,point,reason,keys):return dict(id='iaf:'+id,name=name,primary_classification=classification,tno_categories=kinds,stage_scaling_needed=point is not None,single_scaling_point=point,stage_reason=reason,delivery_paths=[ids[k] for k in keys])
    packages=[
      m('dragon_body_hits','Dragon body/rider damage','VANILLA_LIKE_EXTENDED',['NUMERIC_SCALABLE','VANILLA_ROUTED','ADMISSION_GATED'],'At target.hurt amount emitted by IafDragonLogic.attackTarget once (bite/tail/wing/tackle/rider). For shake, native updatePreyInMouth hurt amount once. Same downstream Stage layer, no attribute/animation/part second multiplication.','Preserve different source identities, repeated requests and normal native admission.',['bite','tail','wing','ai_tackle','rider_tackle','rider_bite','shake_prey']),
      m('dragon_grab_knockback','Dragon grab and body control','CUSTOM_CONTROL',['COMPOSITE','ADMISSION_GATED','NO_STAGE_VALUE'],None,'No extra numeric Stage value for mount/position/dismount or native tail/wing knockback; preserve hooks and independent hurt returns.',['tail','wing','shake_prey']),
      m('dragon_roar','Dragon roar Strength/Weakness','VANILLA_COMPOSITE',['VANILLA_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Leave vanilla effect amplifier/duration/range intact; downstream native attacks already read modified attributes and receive Stage once.',['normal_roar','epic_roar']),
      m('dragon_healing','Dragon combat healing and food restoration','CUSTOM_RESOURCE',['NUMERIC_SCALABLE','COMPOSITE','ADMISSION_GATED'],'Heal requests: the one Dragon heal(amount) invocation through native LivingHealEvent. Direct food: only the HP delta at its native setHealth boundary, before native maxHP clamp; never multiply absolute current/maxHP or a paired damage event. Bite uses raw requested native damage for its heal formula, not observed HP loss.','Separate future healing policy/runtime approval is required; points identify eligible native amount boundaries, not an implemented multiplier.',['rider_bite','shake_prey','hand_food','dropped_food','dragon_meal','sickly_meal','creative_meal','lightning_absorb']),
      m('dragon_native_defense','Dragon native damage/corpse defenses','BINARY_MECHANIC',['BINARY','ADMISSION_GATED','NO_STAGE_VALUE'],None,'Preserve all source/controller/parent/model gates and lightning message-id admission; never scale boolean rejection.',['body_defense','lightning_absorb','corpse']),
      m('dragon_native_attributes','Dragon age/armor/hunger baselines','CUSTOM_RESOURCE',['CUSTOM_ROUTED','NO_STAGE_VALUE'],None,'Native age, health/armor baselines, gear modifier and hunger counters stay native. Numeric attack/heal integration is already assigned elsewhere exactly once.',['age_equipment_refresh','hand_food','dropped_food','dragon_meal','sickly_meal','creative_meal']),
      m('dragon_multipart','Dragon multipart damage routing','VANILLA_LIKE_EXTENDED',['CUSTOM_ROUTED','ADMISSION_GATED','NO_STAGE_VALUE'],None,'No extra part multiplier beyond native partMultiplier. Apply any ordinary Stage amount once to resolved parent damage; native network/player paths require event-count validation.',['multipart_damage','multipart_player_attack'])]
    d=dict(schema='tno.external_effects.iaf_dragon_combat.v1',checkpoint=CP,previous_checkpoint='R2g5a-dragon-elements-complete',starting_sha=START,status='DRAGON_BODY_COMBAT_COMPLETE',scope='Dragon elemental and body combat, roar, native defenses and healing/resource integration reviewed; Frozen/Siren/Gorgon preserved. Other Ice & Fire families remain pending.',summary='Shared Dragon body attacks, rider source changes, independent control, roar variants, healing versus direct HP writes, defenses and multipart routing are reviewed with single scaling points.',facts=FACTS,mechanic_packages=packages,delivery_paths=paths,unexecuted_future_fixtures=['body_animation_tick_windows_and_rejected_hurt_knockback','AI_vs_rider_mob_attack_indirect_magic_identity','rider_tackle_directional_box_and_team_members','rider_ray_wall_miss_ZERO_fallback','shake_mount_veto_tick56_hurt_false_dismount_hunger','raw_damage_based_bite_heal_config_gate','roar_normal_vs_epic_earplugs_directional_box','roar_Strength_owner_pet_and_stronger_dragon','hand_vs_dropped_food_health_delta_and_heal_event','meals_clamp_currentHP_and_growth_disabled','lightning_msgId_query_heal_not_custom_lightning_type','native_hurt_veto_model_dead_controller_passenger','multipart_head_wing_tail_parent_multipliers_and_event_counts','age_reload_equipment_modifier_no_double_Stage','corpse_plunder_energy_spiritual_veto'],remaining_subsection_native_ambiguities=[],review_required=[],exact_next_task=NEXT,references=['native-evidence/iceandfire-dragon-combat.json','reference-evidence/iceandfire-dragon-combat-244.json','vanilla-evidence/iceandfire-dragon-combat.json','reference-routing/iceandfire-dragon-combat.json','iceandfire-dragon-combat-census.json','native-evidence/iceandfire-foundation.json','native-evidence/iceandfire-gorgon.json','native-evidence/iceandfire-frozen-dragons.json','iceandfire-frozen-config-snapshot.json','annotation-evidence/iceandfire-compat-javap.json'])
    save_section(d,STEM,'R2g5b — Dragon body combat and defenses')

if __name__=='__main__':save()
