"""Retired policy-bearing promotion builder; native facts remain in the catalog.

Historical source is available at5002968. Canonical views are generated by
refresh_catalog_views.py; this entry point must never republish Stage policy.
"""


def build():
    raise RuntimeError("Retired promotion builder: use refresh_catalog_views.py and audit_catalog_integrity.py")


if __name__ == '__main__':
    build()
