"""Preserve an INCOMPLETE Cult assembly draft; never publish it as a mod review.

Stopped at the owner's usage boundary. Classifications, comparisons, attribution,
source alternatives and component-level references still require final review.
"""
from catalog_common import *

FILES=['native-evidence/cultofazazel-partial.json','native-evidence/cultofazazel-r2c1.json','native-evidence/cultofazazel-r2c2.json','native-evidence/cult-completion.json']
W={w['id']:(f,w) for f in FILES for w in read_json(OUT/f)['witnesses']}
OLD=read_json(OUT/'partial-notes/cultofazazel-r2c2.json')['findings']
E=[];P=[]
def impl(ids):
    return [dict(evidence_file=W[k][0],witness_id=k,entry=W[k][1]['entry'],methods=[m['name'] for m in W[k][1].get('methods',[])]) for k in ids]
def comp(p,formula,relation='CUSTOM',numbers=None,binary=None):
    return dict(primitive=p,formula=formula,vanilla_relation=relation,numerical_parameters=numbers or {},binary_parameters=binary or [],implementation='See parent record exact class/method witnesses; this component is part of that callback.')
def effect(key,name,kind,summary,behavior,ids,closest,difference,components,numbers=None,state=None,registry=None,damage=None,eligibility=None,removal=None):
    row=dict(id='cultofazazel:'+key,mod_key='cultofazazel',display_name=name,registry_ids=registry or [],primary_classification=kind,
      inspection_status='DRAFT',native_status='STATIC_EVIDENCE_ASSEMBLY_INCOMPLETE',human_summary=summary,actual_behavior=behavior,implementation=impl(ids),
      closest_vanilla_equivalent=closest,vanilla_similarities='The literal vanilla components below retain their native implementation, recipient admission and processing. Similarity does not make custom control/state identical to vanilla.',
      vanilla_differences=difference,components=components,numerical_parameters=numbers or {},scalable_parameters=list((numbers or {}).keys()),
      scalability_note='Available numerical parameters only; no Stage formula or scaling decision is authorized.',
      binary_parameters=list(dict.fromkeys(b for c in components for b in c['binary_parameters'])),custom_state=state or 'No source-specific target state beyond vanilla components.',
      flags=dict(custom_source=False,custom_attributes=False,custom_state=bool(state),direct_hp_write=damage=='direct',custom_stacks=False),
      eligibility=eligibility or 'Native callback conditions described in actual_behavior. AABB queries are boxes, not spherical radii unless an additional distance predicate is stated.',
      stacking='MobEffect payloads use native update: stronger replaces while retaining eligible hidden weaker state; same amplifier extends to longer duration, not additive stacks. Custom counters/state follow the stated assignment/reset rules.',
      removal=removal or 'Native effect expiration/cure or explicit state reset as described. No invented general cure for AI, item or terrain state.',
      damage_path=dict(source_mod_custom_damage_type=False,types=damage if isinstance(damage,list) else [],direct_hp_write=damage=='direct',shp='No native Cult SHP capability or SHP subtraction.',
        admission='hurt requests retain native armor/shield/resistance/enchantment/invulnerability/event processing unless an explicit bypass is stated. Requested amounts are not measured HP loss. Direct setHealth/die and discard are separately identified.'),
      reference_evidence=FILES+['vanilla-evidence/cult-completion.json','reference-evidence/cult-loader-244.json','reference-evidence/vv-loader-244.json','vanilla-evidence/variants-prerequisites.json','vanilla-evidence/vv-completion.json'],
      existing_compat_modification='UNKNOWN',
      compat_note='Attribution is unfinished. See partial-notes/cultofazazel-r2c3-partial.md for inspected conditional RAR hooks. Do not infer NONE from absence of a source-mod name.',
      confidence='PROVISIONAL_ASSEMBLY: pinned static evidence; final per-mechanic audit not completed. No game execution.',
      unresolved_ambiguities=None,pending=['Complete final classifications, exact comparisons, component references and compat attribution before promotion.'],delivery_paths=[],primary_test_source=None,alternate_sources=[])
    E.append(row);return row
def path(key,rows,labels,source,setup,ids):
    pid='cultofazazel:'+key
    P.append(dict(id=pid,mod_key='cultofazazel',status='DRAFT',labels=labels,effect_ids=[r['id'] for r in rows],primary_source=source,setup=setup,implementation=impl(ids)))
    for r in rows:
        r['delivery_paths'].append(pid)
        if r['primary_test_source'] is None:r['primary_test_source']=source
        elif source!=r['primary_test_source'] and source not in r['alternate_sources']:r['alternate_sources'].append(source)
    return pid
def old(i):return OLD[i]['fact']

man=effect('manipulation','Manipulation','CUSTOM_CONTROL','Redirects piglin targets and the affected player’s input, aim and attack clicks.',
 'Affected Player: server effect tick when remaining duration%20==0 retargets Piglin/ZombifiedPiglin in AABB20. Amplifier unused. Client local-player event increments angle0.05, yaw+=sin(angle)*0.8, pitch+=cos(angle*0.5)*0.3; enqueues attack clicks with random20..59-tick spacing. Input searches first lava/fire in x/z±10,y±5, not nearest and without pathfinding; look-relative forward/left impulses steer toward it, or random[-1,1) impulses every15 player ticks when none. Static client timers are not reset on cure.',
 ['coa-manipulation','coa-client-control'], 'Vanilla mob targeting and player movement/attack input; no equivalent vanilla debuff',
 'Custom harmful effect joins server aggro and actual client input writes. It is not Slowness/Weakness or merely an overlay.',
 [comp('AGGRO_REDIRECTION','setTarget(affectedPlayer) every duration%20==0',numbers={'interval':20,'AABB':20},binary=['affected Player','Piglin or ZombifiedPiglin']),comp('INPUT_CONTROL','camera oscillation, attack click queue, direction impulses',numbers={'angle_step':.05,'yaw':.8,'pitch':.3,'click_min':20,'click_max':59,'random_input_interval':15},binary=['local player','effect present'])],
 {'stick_duration':600,'mob_duration':200,'amplifier':0},'MobEffectInstance + client static rotationAngle/clickTimer',['netherman:manipulation'])
path('manipulation_melee',[man],['MELEE'],'netherman:manipulator_stick','Admitted item hurtEnemy callback; server adds600/0 and spends4 durability, then superclass sword callback.',['coa-stick'])
path('manipulation_cast',[man],['MOB_ATTACK','SPELL'],'netherman:manipulator','Live Player target distanceSquared<=225, attack cooldown expired, no flee/cast. Applies200/0 immediately; attack cooldown160 goal ticks, manipulation cooldown1200 entity ticks.',['coa2-manipulator-attack','coa2-manipulator'])
pull=effect('stick_pull','Manipulator Stick pull','CUSTOM_CONTROL','Pulls the first living target along a sampled eye ray.',
 'Non-sneaking use with20 durability available samples0.5..15 by0.5; first alive non-user LivingEntity in sampleAABB0.6 gets Manipulation600/0 and velocity(normalizedTowardPlayer.x*1.4,0.4,normalizedTowardPlayer.z*1.4). No block ray occlusion, hurt call or addEffect-success gate for motion; spends20 durability. No ordinary-use cooldown.',
 ['coa-stick'],'Vanilla fishing/knockback velocity operations','Explicit velocity replacement and custom ray sampling; not a vanilla knockback formula.',
 [comp('FORCED_MOVEMENT','replace horizontal normalized*1.4, Y0.4',numbers={'horizontal':1.4,'Y':.4},binary=['alive non-user','durability available'])],{'range':15,'step':.5,'box':.6,'durability':20})
path('stick_active_pull',[pull,man],['ACTIVE_ITEM'],'netherman:manipulator_stick','Ordinary use with eligible living target.',['coa-stick'])
flee=effect('stick_flee','Held-stick fleeing','CUSTOM_CONTROL','Nearby Villagers and AbstractPiglins receive fleeing navigation requests.',
 'Every fourth server entity tick finds nearest Player within12 holding stick main/offhand. Villager/AbstractPiglin asks DefaultRandomPos.getPosAway(16,7,player position), then navigation.moveTo speed1.3 if a point exists. No hard movement lock or applied fear status.',
 ['coa-stick-events'],'Vanilla fleeing navigation','Custom held-item predicate and event trigger; successful navigation/path not guaranteed.',
 [comp('AI_FLEE','navigation request to away point',numbers={'range':12,'horizontal_search':16,'vertical_search':7,'speed':1.3,'interval':4},binary=['held stick','eligible mob','away point exists'])],{'range':12,'interval':4,'speed':1.3})
path('stick_passive_flee',[flee],['PASSIVE_ITEM'],'netherman:manipulator_stick','Hold either hand near Villager or AbstractPiglin.',['coa-stick-events'])
summon=effect('owned_skeleton_control','Owned Wither Skeleton targeting','CUSTOM_CONTROL','Summons five equipped skeletons with owner-aware target filtering.',
 'Sneak use needs50 durability, attempts five WitherSkeletons, gold sword/armor and zero equipment drop chances, persistent SummonerUUID, spends50 and cooldown40. Every4 entity ticks an owned skeleton without target picks first Player/Monster in AABB16 excluding owner, Azazel and WitherSkeleton. LivingChangeTargetEvent cancels excluded target classes/owner. Native WitherSkeleton melee remains unchanged; mob-produced skeletons have no SummonerUUID.',
 ['coa-stick','coa-stick-events'],'Native WitherSkeleton summon plus owner target predicates','Custom ownership and target filtering; no direct player damage or fabricated wither source.',
 [comp('SUMMON','attempt five native WitherSkeleton creations',numbers={'count':5,'durability':50,'cooldown':40}),comp('TARGET_FILTER','Player/Monster excluding owner/Azazel/WitherSkeleton',numbers={'box':16,'interval':4},binary=['SummonerUUID','target absent'])],{'count':5,'cooldown':40,'durability':50},'Persistent SummonerUUID')
path('stick_owned_summon',[summon],['ACTIVE_ITEM','SUMMONED_ATTACK'],'netherman:manipulator_stick','Sneaking use. All owner-exclusion and non-owner recipient cases share the same filter.',['coa-stick','coa-stick-events'])

chance=effect('chance_totem','Chance Totem rescue','BINARY_MECHANIC','Cancels death, consumes a totem, relocates the player and grants six vanilla effects.',
 'HIGH LivingDeathEvent for ServerPlayer: mainhand, offhand, then first matching Curios slot when Curios is loaded. Non-null totem cancels death, setHealth1, removeAllEffects, shrink1, teleport to recorded respawn dimension/position with overworld/shared-spawn fallback, then Resistance600/4, Invisibility600/0, Blindness600/1, Weakness600/2, Regeneration600/4, Slowness600/0. No random proc. Unlike checkTotemDeathProtection, handler has no bypasses_invulnerability source veto. It still needs an emitted uncanceled death event.',
 ['coa-chance-totem','coa-curios'],'Totem of Undying','Adds relocation, different six-effect bundle and accessory lookup. Native totem happens earlier in hurt before death-event handling; not every lethal attempt reaches this event.',
 [comp('DEATH_CANCELLATION','LivingDeathEvent cancel; HP=1; consume1',numbers={'HP':1,'consumed':1},binary=['ServerPlayer','matching item','uncanceled death event']),comp('RELOCATION','recorded respawn +(.5,1,.5), fallback shared spawn'),comp('VANILLA_EFFECT_BUNDLE','Resistance4,Invisibility0,Blindness1,Weakness2,Regeneration4,Slowness0; each600','VANILLA_DIRECT',{'duration':600})],{'HP':1,'duration':600},None,['netherman:chance_totem'],'direct')
for k,source,label in [('hand','Chance Totem in main/offhand','PASSIVE_ITEM'),('curio','Chance Totem equipped in a native Curios charm/hands/ring slot','ACCESSORY_PROC')]:
 path('chance_'+k,[chance],[label],source,'Native uncanceled ServerPlayer death event; hand priority precedes first Curios result.',['coa-chance-totem','coa-curios'])
mask=effect('mask_rescue_repair','Azazel Trophy charges and regeneration','CUSTOM_RESOURCE','Head-slot mask rescues the wearer three times and repairs damaged stages over time.',
 old(0).split('AzazelEntity.hurt')[0] + 'HIGHEST ServerPlayer death handler: stages0/1 cancel death, replace head stack by stage1/2, store LastRegenTick, setHealth2, clear effects, add Regeneration900/1 FireResistance800/0 Absorption100/1. Last stage cancels, consumes mask, setsHP1 and invokes Chance relocation/bundle. Worn damaged stages repair one stage when worldTime-LastRegenTick>=maskRegenCooldown2400 (range200..72000), carrying CUSTOM_DATA into fresh prior-stage stack. Initial timestamp default0; timer is elapsed world time, not accumulated wearing time. No native totem source veto here.',
 ['coa-mask','coa2-mask-item','coa2-config'],'Totem of Undying + timed item charges','Native totem setsHP1 and uses same first-stage effect durations; mask usesHP2, three item stages, LastRegenTick and final relocation.',
 [comp('DEATH_CANCELLATION','early stages HP2; last HP1',numbers={'early_HP':2,'last_HP':1}),comp('CHARGE_STATE','stage0->1->2->consumed; timed one-stage repair',numbers={'repair_ticks':2400},binary=['head slot','world-time threshold']),comp('VANILLA_EFFECT_BUNDLE','regen900/1,fire_resistance800/0,absorption100/1, or Chance bundle','VANILLA_DIRECT')],{'charges':3,'repair_ticks':2400,'regen_ticks':900,'fire_resistance_ticks':800,'absorption_ticks':100},'Item identity stages + CUSTOM_DATA.LastRegenTick',['netherman:azazel_trophy','netherman:azazel_trophy_stage2','netherman:azazel_trophy_stage3'],'direct')
path('mask_death_repair',[mask],['ARMOR_PROC'],'netherman:azazel_trophy','Wear in HEAD; exercise all three death stages and both reverse repairs. HIGHEST precedes Chance HIGH; ordinary default canceled-event listeners skip after cancellation.',['coa-mask','coa2-mask-item'])
firemask=effect('mask_fire_immunity','Mask fire immunity','BINARY_MECHANIC','Cancels fire, lava and hot-floor incoming damage while wearing any mask stage.',
 'LivingIncomingDamageEvent handler cancels IS_FIRE or literal LAVA/HOT_FLOOR when entity wears any Azazel Trophy stage in HEAD and maskFireImmunity true (default). This is an event cancellation; it does not erase arbitrary fire counters or other damage types.',
 ['coa-mask','coa2-config'],'Fire Resistance / entity fireImmune predicate','Config-gated head-item event veto instead of MobEffect; no duration/amplifier.',
 [comp('DAMAGE_IMMUNITY','cancel matching incoming event',binary=['config true','HEAD mask','fire tag or explicit type'])],state='Equipment and config eligibility',damage=['minecraft:in_fire','minecraft:on_fire','minecraft:lava','minecraft:hot_floor'])
path('mask_fire',[firemask],['ARMOR_PROC'],'Any Azazel Trophy stage in HEAD','Legitimate native fire/lava/hot-floor exposure.',['coa-mask'])

arrow=effect('crimson_arrow_ricochet','Crimson Arrow ricochet','VANILLA_LIKE_EXTENDED','Bow/crossbow arrow reflects off blocks five to ten times.',
 'createArrow returns CrimsonArrowEntity shooter constructor, bounces=random.nextInt(6)+5. Block hit with positive count decrements and sets (v-2(v dot normal)normal)*0.95; resets inGround/inGroundTime, updates rotation. At0 delegates native impact; BouncesLeft saved. No custom entity-hit override. Constructor does not pass weapon stack into AbstractArrow, so weaponItem-dependent inherited post-hit metadata differs. Bow/crossbow use ARROWS-tag ammo through native ArrowItem dispatch. Source mod registers no dispenser behavior; native default dispenses the item. If another mod registers inherited asProjectile, it creates ordinary Arrow, not ricochet.',
 ['coa-arrow','coa2-arrow-item','coa3-NetherExp','coa3-item/crafting/CrimsonArrowRecipe'],'Native AbstractArrow block impact','Replaces sticking by a bounded reflected trajectory; weapon stack omitted; no new damage identity. Entity-type-only constructor has zero bounces.',
 [comp('PROJECTILE_REFLECTION','v_next=(v-2(v dot n)n)*0.95',numbers={'retention':.95,'min_bounces':5,'max_bounces':10},binary=['block hit','remaining>0'])],{'min_bounces':5,'max_bounces':10,'retention':.95},'BouncesLeft NBT',['netherman:crimson_arrow'],['minecraft:arrow'])
for k,source in [('bow','Vanilla Bow + netherman:crimson_arrow'),('crossbow','Vanilla Crossbow + netherman:crimson_arrow')]:
 path('ricochet_'+k,[arrow],['PROJECTILE'],source,'Genuine native shoot path, block reflection then native entity hit. Crafting coating consumes one crimson honey bottle with1..5 vanilla arrow count; native recipe witness retained.',['coa-arrow','coa2-arrow-item'])

shield=effect('azazel_shield','Azazel hit-counter protection','BINARY_MECHANIC','Counts incoming owner hits, heals20 and temporarily rejects damage.',old(0),['coa2-azazel'],'Shield blocking / temporary invulnerability','Pre-super.hurt counter can count attempts that later fail. State2 veto is not an equipped shield or Resistance effect.',[comp('DAMAGE_REJECTION','client/IN_WALL/state7..10/state2 reject before super',binary=['source/state predicate']),comp('HIT_COUNTER','uniform inclusive sorted5..20 hits; at threshold state0 enters state2 for100 countdown and heal20',numbers={'min':5,'max':20,'duration':100,'heal':20})],{'min_hits':5,'max_hits':20,'duration':100,'heal':20},'hitCounter, nextShieldThreshold, ATTACK_STATE, attackTimer',damage=['incoming source preserved'])
path('azazel_shield',[shield],['BOSS_ATTACK','OTHER'],'netherman:azazel','Use genuine LivingEntity-owned damage attempts while boss is idle; preserve triggering-hit versus subsequent-state distinction.',['coa2-azazel'])
terminal=effect('azazel_terminal','Azazel terminal threshold and discard','BINARY_MECHANIC','Raw incoming amount can trigger a protected death cinematic instead of normal damage.',old(0),['coa2-azazel'],'Vanilla death/loot handling','currentHP-rawAmount <= maxHP*0.05 triggers state9 before mitigation; after200 cinematic ticks creates loot/barrel then discard. No direct5% damage and no explosion damage.',[comp('TERMINAL_STATE','raw-amount threshold -> state9 -> discard',numbers={'threshold_fraction':.05,'cinematic_ticks':200},binary=['eligible hurt state','threshold'])],{'threshold_fraction':.05,'cinematic_ticks':200},'ATTACK_STATE/MERCY_TICK',damage='direct')
path('azazel_terminal',[terminal],['OTHER'],'netherman:azazel','Legitimate incoming hurt reaches threshold; distinguish state7..10 immunity and state2 veto.',['coa2-azazel'])
mercy=effect('azazel_mercy','Azazel mercy and forced facing','CUSTOM_CONTROL','Weapon surrender changes the boss state and forces nearby players to face it.',old(1),['coa2-azazel'],'Vanilla target/navigation stop and lookAt','Custom one-time five-attack offer and cinematic state; not a frozenTicks status.',[comp('AI_STATE','offer once after5 selected attacks, timeout>284 ticks; weapon interaction ->7 ->8 ->discard',numbers={'attacks':5,'offer_timeout':284,'state7_ticks':76,'state8_ticks':40},binary=['accepted weapon','creative consumption exception']),comp('FORCED_FACING','state8 lookAt boss eyes in AABB30 each tick',numbers={'box':30})],{'offer_attacks':5,'offer_timeout':284,'facing_box':30,'facing_ticks':40},'HasOfferedMercy,TotalAttacks,ATTACK_STATE,MERCY_TICK')
path('azazel_mercy',[mercy],['ACTIVE_ITEM','BOSS_ATTACK'],'Azazel + iron/diamond/netherite sword or axe','Wait for native mercy offer and interact with accepted weapon. All six items share one exact predicate; consumption skipped in creative.',['coa2-azazel'])
motion=[('wind','Wind',60,5,.8,.2,20),('pull','Pull',60,5,.6,1.5,20),('launch','Launch',80,8,0,2.5,5),('wheel','Wheel',90,4,1.2,0,1)]
for key,name,duration,damage,horizontal,vertical,box in motion:
    e=effect('azazel_'+key,'Azazel '+name,'CUSTOM_CONTROL',name+' attack uses its own timing and velocity-control callback.',old(2),['coa2-azazel'],'Native hurt(mobAttack) plus motion vector API','Vector writes bypass knockback-resistance calculation and are not conditioned on hurt return. All four delivery implementations remain distinct; durations are entity ticks.',[comp('FORCED_MOVEMENT',{'wind':'add away-normalizedXZ*.8,Y+.2 each active tick','pull':'timer>15 add towardXZ*.6; at15 setY1.5','launch':'timer40 setY2.5','wheel':'timer<=50 boss dash1.2; every3 entity ticks set target full dashVec*1.5'}[key],numbers={'horizontal':horizontal,'vertical':vertical,'box':box}),comp('NATIVE_DAMAGE_REQUEST',f'mobAttack configured default{damage}; callback-specific timer','VANILLA_DIRECT',{'damage':damage})],{'duration':duration,'damage':damage,'horizontal':horizontal,'vertical':vertical,'box':box},'ATTACK_STATE/attackTimer',damage=['minecraft:mob_attack'])
    path('azazel_'+key,[e],['BOSS_ATTACK','AOE'],'netherman:azazel',f'Native {name} attack selection; no direct callback injection. Eligibility/damage tick in saved behavior.',['coa2-azazel'])
midasfire=effect('midas_fire_ring','Midas expanding fire ring','VANILLA_COMPOSITE','An expanding ring requests native fire damage and ignites nearby players.',old(3),['coa2-azazel'],'Native in_fire damage and burning','New distance/time geometry; ignition5 seconds independent of hurt success. Not a new fire DamageType.',[comp('FIRE_DAMAGE','abs(distance-(elapsed/120)*30)<=1.5 ->inFire8','VANILLA_DIRECT',{'damage':8,'width':1.5}),comp('BURN','igniteForSeconds5 (extends native fire timer)','VANILLA_DIRECT',{'seconds':5})],{'duration':120,'max_radius':30,'box':35,'damage':8,'ignite_seconds':5},'attackTimer',damage=['minecraft:in_fire','minecraft:on_fire'])
midasgold=effect('midas_inventory','Midas inventory replacement','CUSTOM_RESOURCE','Proximity buildup replaces a random nonempty inventory stack with raw gold.',old(3)+' Raw and exact loader Inventory compartments are36 main/hotbar+4 armor+1 offhand=41. It does not inspect ender chest, crafting cursor, Curios, or contents nested inside item stacks.', ['coa2-azazel'],'Vanilla Inventory.setItem; no vanilla combat equivalent','Replaces full stack and loses old components; counter is proximity tracking, not a MobEffect or native hunger/mana drain.',[comp('PROXIMITY_BUILDUP','within6 adds1 per scanned tick; threshold40 resets; out6 in35 resets; outside35 unvisited',numbers={'radius':6,'threshold':40,'scan_box':35}),comp('INVENTORY_REPLACEMENT','uniform eligible slot0..40 ->RAW_GOLD old count',numbers={'slots':41},binary=['nonempty','not RAW_GOLD'])],{'threshold':40,'radius':6,'slots':41},'midasProximityTracker UUID->count')
path('azazel_midas',[midasfire,midasgold],['BOSS_ATTACK','AOE'],'netherman:azazel','Native close-player Midas selection; separately cover fire-shell and inner inventory counter.',['coa2-azazel'])
prison=effect('azazel_prison','Azazel prison terrain','CUSTOM_CONTROL','Builds temporary walls and extends them when the target climbs.',old(4),['coa2-azazel','coa3-block/GrandDoorPartBlock'],'Vanilla block collision and placement','Custom timed ring replaces terrain and tracks cleanup; no actor teleport/stun. GrandDoorPart inherits real block collision and its removal callback may also remove a nearby registered Grand Door.',[comp('TERRAIN_CONFINEMENT','rounded radial ring with step/height conditions; target rise adds5 layers',numbers={'radius':5,'duration':200,'max_initial_height':6,'added_layers':5},binary=['replaceable blocks','target height']),comp('CLEANUP','recorded matching column/part ->AIR; no old-state restoration',binary=['expiry/death/removal','tracked identity'])],{'radius':5,'duration':200,'max_height':6,'extra_layers':5},'prisonCenter/Target/Blocks, unpersisted')
path('azazel_prison',[prison],['BOSS_ATTACK','ENVIRONMENT'],'netherman:azazel','Native prison attack with Player target; ordinary block placement and cleanup.',['coa2-azazel'])
fangs=effect('native_fangs','Azazel native Evoker Fangs','VANILLA_DIRECT','Summoned native fangs request six indirect-magic damage after their warmup.',old(5)+' Native fangs decrement warmup and deal at-8. Alive, not isInvulnerable, not owner; with owner reject allied target. Azazel owner ->indirectMagic(fangs,Azazel)6; ownerless native fallback is magic6. Successful hurt triggers native enchantment post-attack hook. Native damage cooldowns remain.', ['coa2-azazel'],'Minecraft EvokerFangs','Azazel changes producer geometry/count (20 at timers100/80/60), not fang damage/admission.',[comp('NATIVE_DAMAGE_REQUEST','indirect_magic6 at warmup=-8','VANILLA_DIRECT',{'damage':6,'warmup_start':0,'damage_tick':8},['alive','not invulnerable','not owner/allied'])],{'damage':6,'bursts':3,'per_burst':20},None,damage=['minecraft:indirect_magic'])
path('azazel_fangs',[fangs],['BOSS_ATTACK','SUMMONED_ATTACK','AOE'],'netherman:azazel','Native arrow-attack variant1; owner remains Azazel.',['coa2-azazel'])
laser=effect('laser_hazard','Laser moving hazard','VANILLA_LIKE_EXTENDED','An invulnerable moving Mob requests magic damage and sets a burning timer.',old(10)+' Registered hitbox width3,height18.75. No owner is assigned by Azazel; source is magic, not mob/projectile damage.', ['coa2-laser','coa3-NetherExp'],'Vanilla magic damage, fire timer and entity movement','Custom moving Mob with hurt=false and direct setPos; it is not a beam DamageType or Arrow. Absolute fire60 can shorten an existing timer.',[comp('NATIVE_DAMAGE_REQUEST','magic5 every2 ticks for alive noncreative Player overlapping hitbox','VANILLA_DIRECT',{'damage':5,'interval':2}),comp('BURN','setRemainingFireTicks60','VANILLA_DIRECT',{'ticks':60}),comp('HAZARD_MOTION','speed.15 + perpendicular sin(t*.3)*.15; angle varies every10',numbers={'speed':.15,'life':1200},binary=['hurt always false','not pickable/pushable'])],{'damage':5,'interval':2,'fire_ticks':60,'life':1200,'width':3,'height':18.75},'LIFE_TICKS saved; moveAngle/tickCount condition',damage=['minecraft:magic','minecraft:on_fire'])
path('azazel_lasers',[laser],['BOSS_ATTACK','SUMMONED_ATTACK','AOE'],'netherman:azazel','Native variant2 creates10 lasers on radius7; let moving hazards intersect target.',['coa2-azazel','coa2-laser'])

protection=effect('believer_protection','Believer protection','BINARY_MECHANIC','Pray grants nearby Believers150 ticks of hurt rejection.',old(6),['coa2-believer','coa2-azazel'],'Invulnerability predicate','Boolean hurt veto before superclass, with no source exception; not Resistance.',[comp('DAMAGE_REJECTION','IS_PROTECTED ->false hurt; timer150 decrements each server tick',numbers={'duration':150},binary=['protected flag'])],{'duration':150},'IS_PROTECTED/protectedTimer')
path('believer_pray_protection',[protection],['BOSS_ATTACK','PASSIVE_AURA'],'Azazel + netherman:believer','Native Pray selection needs Believer within40; all in AABB40 receive protection.',['coa2-azazel','coa2-believer'])
sick=effect('believer_sickness','Believer sickness','CUSTOM_CONTROL','Sickness stops voluntary travel; a golden apple cures it.',old(6)+' Doctor tick timer starts as declared and decrements per entity tick; when0 it resets2400 then chooses one healthy Believer in AABB15. Because decrement branch and trigger branch are separate, later attempts are2401 ticks apart. Doctor does not heal sickness: golden apple trade is refused if any sick Believer in AABB10.', ['coa2-believer','coa3-entity/DoctorEntity'],'Native travel(Vec3.ZERO)/navigation stop','Custom IS_SICK with no timed expiry or MobEffect immunity. Sickness does not suppress Believer heal5 logic.',[comp('AI_MOVEMENT_SUPPRESSION','sick/praying stop navigation and travelZERO',binary=['IS_SICK or IS_PRAYING']),comp('CURE','golden apple clears IS_SICK; gunpowder sets it',binary=['correct item','creative consumption exemption'])],{'doctor_box':15,'doctor_reset':2400,'doctor_attempt_interval':2401},'IS_SICK persisted by Believer save; Doctor SicknessTimer saved')
path('believer_sickness_item',[sick],['ACTIVE_ITEM'],'Gunpowder / golden apple + netherman:believer','Native interaction sets/clears sickness.',['coa2-believer'])
path('believer_sickness_doctor',[sick],['PASSIVE_AURA'],'netherman:doctor + healthy Believer','Native timed random selection in AABB15.',['coa3-entity/DoctorEntity'])
heal=effect('believer_healing','Believer boss healing','VANILLA_DIRECT','Each linked Believer requests five HP of boss healing per20 ticks.',old(6),['coa2-believer'],'LivingEntity.heal','Different native producer and amount; no custom healing attribute or sickness suppression. Native heal event can modify/cancel.',[comp('HEAL','live selected Azazel heal5 every20 entity ticks','VANILLA_DIRECT',{'amount':5,'interval':20})],{'amount':5,'interval':20,'initial_box':30,'retained_distance':40},'currentAzazel/IS_PRAYING')
path('believer_heal',[heal],['PASSIVE_AURA'],'netherman:believer near Azazel','Native initial AABB30 selection, retain live current boss at distanceSquared<1600.',['coa2-believer'])
omen=effect('bad_omen','Believer Bad Omen and Azazel aggro','VANILLA_LIKE_EXTENDED','Player-attributed Believer death grants Bad Omen, which can wake Azazel.',old(6)+' Raw1.21.1 BadOmen ticks every tick: nonspectator ServerPlayer in nonpeaceful village with absent/eligible raid receives RaidOmen600 with same amplifier, records position, removes BadOmen. Cult also checks actual BAD_OMEN in bossAABB30 to trigger aggro.', ['coa2-believer','coa2-azazel'],'minecraft:bad_omen','Actual vanilla effect with additional Cult boss-aggro consumer; not a custom damage or fear status.',[comp('VANILLA_STATUS','BAD_OMEN36000/0 ->native RaidOmen pathway','VANILLA_DIRECT',{'duration':36000,'amp':0}),comp('AGGRO_TRIGGER','idle Azazel +Player BAD_OMEN inAABB30',numbers={'box':30},binary=['BAD_OMEN present'])],{'duration':36000,'amp':0,'boss_box':30},None,['minecraft:bad_omen'])
path('believer_death_omen',[omen],['OTHER'],'netherman:believer killed by a Player-owned source','die callback attribution; spawned Statue is separate source context.',['coa2-believer'])

rapid=effect('guardian_rapid_melee','Guardian rapid melee','CUSTOM_DAMAGE','Rapid native melee resets the target’s hurt cooldown before each hit.',old(7)+' Exact normal AI scheduler: Goal.requiresUpdateEveryTick=false; Mob runs full selector on even(tickCount+id), otherwise only every-tick goals. GuardianGoal therefore advances every2 server ticks while running: combo3..5*3=9..15 attempts, interval8 ticks within each set; set length22 ticks. Startup/state changes/goal interruption can shift or pause timings; no fixed DPS claim.', ['coa2-guardian','coa2-guardian-goal'],'Native mob_attack + hurt cooldown','Explicit invulnerableTime=0 is a real native cooldown bypass. It does not bypass armor/shields/Resistance or arbitrary event cancellation.',[comp('COOLDOWN_RESET','target.invulnerableTime=0 before hurt',binary=['target within range']),comp('NATIVE_DAMAGE_REQUEST','mob_attack3 or buffed8',numbers={'base_damage':3,'buffed_damage':8,'base_range':4,'buffed_range':8,'intra_set_ticks':8,'set_ticks':22})],{'damage':3,'buffed_damage':8,'hits_min':9,'hits_max':15,'interval':8},'goal combo/punchCooldown + IS_BUFFED',damage=['minecraft:mob_attack'])
mega=effect('guardian_mega_punch','Guardian mega-punch','VANILLA_LIKE_EXTENDED','Area punch damages eligible living targets and adds upward velocity.',old(8),['coa2-guardian','coa2-guardian-goal'],'Native area mobAttack and golem-like launch','No hurt-cooldown reset; Y+.9 ignores hurt return and target knockback resistance. Native ally-type exclusion list retained.',[comp('NATIVE_DAMAGE_REQUEST','10 or buffed15 in distance10 or20','VANILLA_DIRECT',{'base_damage':10,'buffed_damage':15,'base_radius':10,'buffed_radius':20}),comp('FORCED_MOVEMENT','Y+=.9 independent of hurt result',numbers={'Y':.9})],{'damage':10,'buffed_damage':15,'Y':.9,'normal_goal_cooldown_ticks':320},'goal state/cooldown + IS_BUFFED',damage=['minecraft:mob_attack'])
buff=effect('welcomer_buff','Welcomer Guardian buff','CUSTOM_STATUS','A casting Welcomer switches nearby Guardians to stronger, longer-range attacks.',old(8),['coa2-welcomer','coa2-guardian'],'Strength / reach-like attack parameters','Custom boolean changes hardcoded damage/range; no vanilla Strength amplifier or modifier stacking.',[comp('DAMAGE_AND_RANGE_SWITCH','melee3->8/range4->8; mega10->15/range10->20',numbers={'poll_ticks':10,'box':30},binary=['casting Welcomer nearby','Guardian with target initiates casting'])],{'poll':10,'box':30},'IS_CASTING,IS_BUFFED; recomputed, not additive')
for key,row in [('rapid',rapid),('mega',mega)]:path('guardian_'+key,[row],['MOB_ATTACK'],'netherman:guardian','Native retaliation target; exercise unbuffed and buffed (Welcomer) cases. Spawn egg, Nether Spawner, Manipulator companion and Midas summons share native attacks.',['coa2-guardian','coa2-guardian-goal'])
path('welcomer_aura',[buff],['PASSIVE_AURA'],'Welcomer + targeted Guardian within30','Use Nether Spawner next to polished blackstone brick stairs for Welcomer; its own registration has no listed spawn egg.',['coa2-welcomer','coa2-guardian','coa3-block/entity/NetherSpawnerBlockEntity'])
golem=effect('golem_healing_pull','Gilded Golem healing pull','CUSTOM_RESOURCE','Pulls and consumes items or damages players while healing itself.',old(9),['coa2-golem','coa3-event/GildedGolemSpawnEvent'],'Native heal, magic hurt, item removal and velocity','Item consumption removes entire stack entity; player heal6 is unconditional after request2, not proportional lifesteal.',[comp('FORCED_MOVEMENT','horizontal normalizeToward*.15 added',numbers={'strength':.15,'box':10}),comp('ITEM_CONSUMPTION','first squaredDistance<2.5 discard item and heal4',numbers={'heal':4}),comp('LIFE_DRAIN','if no item eaten, squaredDistance<3.5 every20 request magic2 then heal6',numbers={'damage':2,'heal':6,'interval':20},binary=['player alive','not creative/spectator/creator'])],{'phase_threshold':.25,'pull':.15,'item_heal':4,'damage':2,'player_heal':6,'interval':20},'Creator UUID,IsHealingPhase persisted',damage=['minecraft:magic'])
path('golem_healing_unowned',[golem],['MOB_ATTACK','AOE'],'netherman:gilded_golem','Spawn egg or Nether Spawner raw-gold-block branch has no creator. Lower living golem to<=25% then use items/eligible Player.',['coa2-golem'])
path('golem_healing_creator',[golem],['MOB_ATTACK','AOE'],'Player-built Gilded Golem','Gold-block T + carved pumpkin/jack-o-lantern. Spawn event writes creatorUUID; include creator immunity and noncreator cases.',['coa3-event/GildedGolemSpawnEvent','coa2-golem'])
glaunch=effect('golem_launch','Gilded Golem extra launch','VANILLA_LIKE_EXTENDED','Successful golem melee adds an extra upward push beyond vanilla.',old(9)+' IronGolem parent on successful hurt adds .4*max(0,1-targetKnockbackResistance) upward; Cult then adds another .4 unconditionally on parent success. Total added Y=.4*max(0,1-KR)+.4. Native base attack random amount f/2+nextInt((int)f) is ordinary physical context, not a new special-damage mechanic.', ['coa2-golem'],'IronGolem.doHurtTarget','Extra .4 is independent of knockback resistance; both parts require admitted parent hit.',[comp('EXTRA_LAUNCH','Y += .4*max(0,1-KR)+.4','VANILLA_LIKE_EXTENDED',{'native_base':.4,'extra':.4},['successful parent hit'])],{'extra_Y':.4},damage=['minecraft:mob_attack'])
path('golem_melee',[glaunch],['MELEE','MOB_ATTACK'],'netherman:gilded_golem','Native melee; all creation paths share launch implementation.',['coa2-golem'])

if __name__=='__main__':
    document=dict(schema='tno.external_effects.partial_draft.v1',baseline=BASELINE,
        checkpoint='R2c3-partial',mod_key='cultofazazel',status='PARTIAL',
        semantic_coverage_complete=False,promoted_to_catalog=False,
        note='Unfinished assembly stopped after Gilded Golem. Draft counts are not final semantic counts. Read partial-notes/cultofazazel-r2c3-partial.md before continuation.',
        effects=E,paths=P,**boundary_flags())
    write_json(OUT/'partial-drafts/cultofazazel-r2c3-partial.json',document)
    print(len(E),'draft records;',len(P),'draft paths; no catalog promotion')
