"""Friends & Foes semantic packages. Static installed-code review, no runtime execution."""
from catalog_common import *
from collections import Counter
from assemble_batch import refresh

START='7dcdcc4c03516928aa516fe10a1cd0d1fc1a9a91'
CHECKPOINT='R2e-complete'
W={w['id'].removeprefix('faf:'):w for w in read_json(OUT/'native-evidence/friendsandfoes.json')['witnesses']}
E=[];P=[]
EN='common/entity/';MX='common/mixin/';UT='common/util/';BR=EN+'ai/brain/';TASK=BR+'task/'
ICE=EN+'IceologerEntity';CHUNK=EN+'IceologerIceChunkEntity';ILL=EN+'IllusionerEntity';WI=EN+'WildfireEntity';DEBRIS=EN+'WildfireShieldDebrisEntity'
MA=EN+'MaulerEntity';CO=EN+'CopperGolemEntity';TU=EN+'TuffGolemEntity';GL=EN+'GlareEntity';RA=EN+'RascalEntity';PI=EN+'PlayerIllusionEntity'
TOT=UT+'TotemUtil';PLAYER=MX+'PlayerEntityMixin';REG='common/init/FriendsAndFoesEntityTypes'
REFERENCES=['vanilla-evidence/friendsandfoes.json','reference-evidence/friends-loader-244.json','vanilla-evidence/variants-prerequisites.json','vanilla-evidence/vv-completion.json','reference-evidence/vv-loader-244.json','vanilla-evidence/cult-completion.json','reference-evidence/cult-loader-244.json','vanilla-evidence/royalvariations.json','reference-evidence/royal-loader-244.json','vanilla-evidence/royal-final.json','reference-evidence/cult-final-244.json']

def proof(*keys):
    return [dict(evidence_file='native-evidence/friendsandfoes.json',witness_id=W[k]['id'],entry=W[k]['entry'],methods=sorted({m['name'] for m in W[k].get('methods',[])})) for k in keys]

def c(primitive,formula,numbers=None,binary=None,relation='CUSTOM'):
    return dict(primitive=primitive,formula=formula,numerical_parameters=numbers or {},binary_parameters=binary or [],vanilla_relation=relation)

def add(key,name,kind,actual,closest,difference,components,keys,state='No new target capability; native state described in behavior.',registry=None):
    implementation=proof(*keys)
    for component in components:component['implementation']=implementation
    e=dict(id='friendsandfoes:'+key,mod_key='friendsandfoes',display_name=name,primary_classification=kind,actual_behavior=actual,human_summary=actual,
        registry_ids=registry or [],implementation=implementation,closest_vanilla_equivalent=closest,vanilla_similarities='Exact shared primitives, eligibility and differences are recorded per component and in native_behavior.',vanilla_differences=difference,
        components=components,numerical_parameters={k:v for x in components for k,v in x['numerical_parameters'].items()},binary_parameters=[v for x in components for v in x['binary_parameters']],
        scalable_parameter_candidates=[dict(primitive=x['primitive'],parameters=list(x['numerical_parameters']),meaning='Observation only; no Stage, calibration or eligibility proposal.') for x in components if x['numerical_parameters']],
        custom_state=state,delivery_paths=[],primary_test_source=None,alternate_sources=[],inspection_status='VERIFIED',unresolved_ambiguities=[],reference_files=REFERENCES)
    E.append(e);return e

def p(key,rows,labels,source,setup,keys,fixture):
    row=dict(id='friendsandfoes:'+key,mod_key='friendsandfoes',status='VERIFIED',labels=labels,effect_ids=[e['id'] for e in rows],primary_source=source,setup=setup,implementation=proof(*keys),fixture_family=fixture)
    P.append(row)
    for e in rows:
        e['delivery_paths'].append(row['id'])
        if e['primary_test_source'] is None:e['primary_test_source']=source
        elif e['primary_test_source']!=source and source not in e['alternate_sources']:e['alternate_sources'].append(source)

LIFECYCLE='Literal MobEffect instances retain native admission and merge: stronger replaces/hides weaker; equal amplifier only extends to a longer duration. No additive stacking. Native milk/totem cure membership and cancellable NeoForge removal apply; removeAllEffects is separately called by the two custom totems and is not a selective cure. Speed +.2*(amp+1) and Slowness -.15*(amp+1) ADD_MULTIPLIED_TOTAL. Blindness/Glowing/Invisibility have no damage-amplifier formula; native holder behavior is retained. Normal active effects save duration/amplifier; custom counters are specified separately.'
FREEZE='Frozen ticks is a gauge assignment, not 400 ticks of stun: threshold140, outside powder snow normally decreases2/tick; powder snow uses min(140,n+1). Native frost movement modifier is -.05*min(n,140)/140 ADD_VALUE when supported on a nonair legacy block. Every40 entity ticks while fully frozen and canFreeze requests1 minecraft:freeze; native freeze-hurts-extra tag multiplies incoming freezing damage5, including Wildfire. canFreeze and armor/tag immunity still gate native DOT even where producer writes the gauge without checking them. No additive gauge stacking.'
HURT='Amounts are native hurt requests, not observed HP loss. Exact raw damage-type tags and installed LivingEntity processing remain: invulnerability, fire resistance, shield facing/source position, repeated-hit comparison while invulnerableTime>10, armor, enchantment/Resistance and absorption; loader events can veto/modify. No synthetic damage or HP subtraction. Child actions only depend on hurt return where explicitly stated.'
TRIGGER='Player.hurt HEAD on server: alive/not dead, pre-hit HP<=maxHP/2, source owner nonnull, source not IN_FIRE/ON_FIRE/FALL/FALLING_BLOCK. No positive-amount or successful-hurt gate. Hands first, then native custom-equipment compat; first friendsandfoes:totems item. Clear all effects, animate, consume1 before payload. No heal, hit cancellation or death protection; original incoming hit continues. Third-party tag additions can consume/clear without either recognized payload.'

freeze=add('iceologer_freeze','Iceologer frozen-gauge spell','VANILLA_LIKE_EXTENDED','Native spell casts setTicksFrozen(400) on alive target only if canFreeze. Spell enum BLINDNESS is visual; no Blindness/Slowness holder. Native warmup20 adjusted by Goal cadence, casting state20 and next-start interval220.', 'Powder-snow frozen gauge','Custom targeted assignment and spell scheduling; native frost/DOT semantics remain.',[c('FROZEN_GAUGE','assign400, not add; '+FREEZE,{'assignment':400,'warmup':20,'casting_state':20,'interval':220},['alive target','canFreeze'],'VANILLA_DIRECT')],[ICE,ICE+'$SlowTargetGoal'])
chunk=add('ice_chunk','Iceologer falling ice chunk','VANILLA_COMPOSITE','Native summon creates invulnerable no-gravity ice entity above target at min(targetY+height^2,targetY+6). Fall delay60..100 ticks; moving target is followed at .2 only when target velocity squared>=.0001. Then acceleration -.05Y per tick; vertical collision scans chunk AABB inflated(.2,0,.2), requests12 indirectMagic(chunk,owner), or magic if owner absent. Alive/noninvulnerable recipients only; owner and owner allies excluded. canFreeze recipients get gauge400 independently of hurt return. Target creative/spectator player discards chunk.', 'Evoker-style indirect magic plus native freezing','Custom physical-looking delivery uses native magic, not falling-block damage; freeze does not require HP damage.',[c('MAGIC_HIT','request12 indirect_magic; owner absent magic',{'damage':12,'delay_min':60,'delay_max':100,'follow_speed':.2,'fall_acceleration':.05,'extra_box_xz':.2},['verticalCollision','alive','not invulnerable','not owner/allied'],'VANILLA_DIRECT'),c('FROZEN_GAUGE','assign400; '+FREEZE,{'assignment':400},['canFreeze','independent hurt result'],'VANILLA_DIRECT')],[CHUNK,ICE+'$SummonIceChunkGoal'],state='Owner/target UUID and fall/idle counters saved; idle10..20 is not read by damage/movement. Visual lifetime30 is not a damage timer. Summon interval160/casting state30/warmup20; no target-spawn success guarantee.')
blind=add('illusioner_blindness','Illusioner Blindness spell','VANILLA_LIKE_EXTENDED','Literal Blindness200/0 from the caster; native goal requires live target, not casting, next-start reached, different target ID from last cast and local effective difficulty>2. Warmup20, casting state20, interval180.', 'Vanilla Illusioner Blindness400/0','Same holder and goal admission, duration halved to200; no new Blindness effect.',[c('BLINDNESS','literal holder200/0',{'duration':200,'amplifier':0,'vanilla_duration':400,'interval':180},['different target ID','local difficulty>2'],'VANILLA_DIRECT')],[ILL,ILL+'$IllusionerBlindnessSpellGoal'],state='lastTargetId/goal deadlines are transient; ordinary active effect saved.')
illusions=add('illusioner_decoys','Illusioner reactive real decoys','CUSTOM_CONTROL','Real Illusioner reacts before parent hurt to nonallied owner while cooldown0 (creative player excluded): WasAttacked=true, cooldown600, Invisibility60/0, ring radius9 with9 configured candidate slots. One slot teleports parent; others create real bow-equipped Illusioner entities with lifetime600 and parent pointer. createIllusion calls this.tryToTeleport on the PARENT, then adds clone at its copied earlier position. Spawn/teleport results can reduce count. Not nine guaranteed clones. Repeats when attacked state and cooldown reaches0; target loss after cooldown<lifetime/3 clears state. Decoy rejects ownerless/nonliving-owner hits; nonallied living-owner hit discards it and returnsfalse. Raider/illager-friendly owners rejected on real and clone paths.', 'Vanilla Illusioner invisibility/rendered offsets','Real entities with independent native bow attacks and hurt admission, not cosmetic mirror images. Vanilla mirror gives Invisibility1200/0 on interval340.',[c('DECOY_SUMMON','max slots9; lifetime/cooldown600; real entity bow AI',{'slots':9,'ring_radius':9,'lifetime':600,'cooldown':600},['native config','real vs illusion','teleport admission']),c('INVISIBILITY','literal60/0',{'duration':60,'amplifier':0},relation='VANILLA_DIRECT'),c('DAMAGE_ADMISSION','decoy living nonally owner -> discard,false; nonliving owner -> false',binary=['owner type','allied/raider tags'])],[ILL],state='IsIllusion, WasAttacked, despawn/cooldown timers saved. Parent pointer not saved; missing pointer after reload is not proof of immediate discard. Parent death discards decoy only while pointer available.')
freezetotem=add('freezing_totem','Totem of Freezing low-health reaction','VANILLA_COMPOSITE',TRIGGER+' Freezing payload: AABB9 native forNonCombat query ignores invisibility/LOS, excludes creative Players/self; no ally filter. Assign400 frozen ticks without canFreeze check, add Slowness400/1; user Speed200/1.', 'Native frost + Slowness II + Speed II','Custom pre-hit threshold/consumption and AoE package; it does not save from a fatal hit.',[c('LOW_HEALTH_TRIGGER',TRIGGER,{'health_fraction':.5,'consumption':1},['owner source','four excluded DamageTypes']),c('FREEZE_AND_SLOW','gauge400; Slowness400/1 => -.30 movement total; '+FREEZE,{'gauge':400,'slowness_duration':400,'slowness_amp':1,'box':9},['native forNonCombat recipient query'],'VANILLA_DIRECT'),c('SPEED','user200/1 => +.40 movement total',{'speed_duration':200,'speed_amp':1},relation='VANILLA_DIRECT')],[PLAYER,TOT],registry=['friendsandfoes:totem_of_freezing'])
illusiontotem=add('illusion_totem','Totem of Illusion low-health reaction','CUSTOM_CONTROL',TRIGGER+' Illusion payload constructs up to9 PlayerIllusion candidates on radius9; helper returns nonnull even when teleport/spawn fails. Copies equipment and user pointer/UUID, lifetime600, maxHP1 (setHealth(userMax) clamps to1), no attack goals. Mob query AABB18 selects mobs currently targeting user, sets aggressive and lastHurtByMob/lastHurtMob to independently sampled candidates; does not directly setTarget. These mobs get Blindness400/1. A sampled candidate supplies user teleport destination; candidate discarded regardless teleport success. User gets Invisibility200/0 even if no spawn succeeds.', 'Native invisibility/blindness/teleport and combat memories','Custom decoy and memory-control package; no guarantee of retargeting or nine spawned illusions; no player-illusion attacks.',[c('DECOY_ENTITY','9 candidate slots, radius9, lifetime600, HP1; hurt discards and returnstrue',{'slots':9,'radius':9,'lifetime':600,'max_hp':1},['native collision-safe teleport','no attack goals']),c('MEMORY_REWRITE','current attackers in AABB18; separate random lastHurtByMob/lastHurtMob',{'box':18},['mob currently targets user','candidate exists']),c('BLINDNESS','selected mobs400/1',{'duration':400,'amplifier':1},relation='VANILLA_DIRECT'),c('TELEPORT_AND_INVISIBILITY','16 vertical attempts from y-8; selected candidate discarded; user200/0',{'vertical_attempts':16,'invisibility_duration':200},['randomTeleport succeeds for movement'],'VANILLA_DIRECT')],[PLAYER,TOT,PI,UT+'PlayerIllusionUtil'],state='Illusion lifetime and PlayerUuid saved; player pointer not resolved from UUID after reload. Countdown0 or known dead player discards. No XP/loot.',registry=['friendsandfoes:totem_of_illusion'])
crown=add('wildfire_crown','Wildfire Crown Fire Resistance refresh','VANILLA_LIKE_EXTENDED','Player tick TAIL wearing literal Wildfire Crown in head slot adds Fire Resistance160/0 while not on fire and eyes not in lava. No explicit server-only check. Burning/lava-eye state stops refresh; existing duration counts down. Native armor material is ordinary equipment; no custom damage multiplier.', 'Fire Resistance','Conditional passive refresh of native IS_FIRE protection; not universal damage immunity.',[c('FIRE_RESISTANCE','native160/0 refreshed on eligible tick',{'duration':160,'amplifier':0},['head item','not on fire','eyes not lava'],'VANILLA_DIRECT')],[PLAYER,'common/init/FriendsAndFoesItems','common/init/FriendsAndFoesArmorMaterials'],registry=['friendsandfoes:wildfire_crown','minecraft:fire_resistance'])
curiototem=add('curios_undying','Native Totem of Undying from Curios','VANILLA_LIKE_EXTENDED','Wraps LivingEntity.checkTotemDeathProtection hand lookup. When looked-up hand is not literal vanilla Totem of Undying, custom-equipment integrations can return one. Installed Curios adapter searches only Players and returns actual equipped stack. Native death-protection admission, consumption, HP1 and cure/effect grants remain in caller. Distinct from custom low-health totems.', 'Totem of Undying','Adds native item lookup source; does not change native rescue eligibility.',[c('EQUIPMENT_LOOKUP','Curios findFirstCurio(predicate literal vanilla totem)',binary=['Player','integration loaded','native death-protection admission'],relation='VANILLA_DIRECT')],[MX+'LivingEntityMixin','neoforge/modcompat/CuriosCompat','common/modcompat/ModChecker'])
shield=add('wildfire_shields','Wildfire shield budget and regeneration','CUSTOM_RESOURCE','Four shields; raw incoming amount accumulates before native hurt. At >=max-health attribute*.25 (30 default), break ONE shield, reset counter0, request8 mob_attack against living owner; excess budget discarded. Covered hit becomes0 even when it breaks last shield. Every eligible non-generic hit resets regeneration300; every300 timer ticks regenerate one to cap4. Exact cached generic/genericKill sources bypass this routine; exact cached inFire or owner in wildfire_allies rejects. Shield counter is not saved. Installed enableWildfire=false means constructor/tick discard: these native paths are unavailable in this configuration.', 'Absorption/shield-like defense','Independent hit budget/count; not native Absorption, armor, block facing or a status effect.',[c('SHIELD_RESOURCE','raw sum>=.25*maxHP breaks1; count4; request becomes0',{'max_shields':4,'threshold_fraction':.25,'default_threshold':30},['exact source object exceptions','owner ally tag']),c('COUNTER_HIT','request8 mob_attack against living owner at break',{'damage':8},['living owner'],'VANILLA_DIRECT'),c('REGENERATION','one shield per300 timer ticks',{'ticks':300},['any eligible hit resets timer'])],[WI],state='Shield count, regen ticks, summoned blaze count saved; raw amount counter transient. Regen countdown runs tick-side code without server guard.')
barrage=add('wildfire_barrage','Wildfire debris barrage','VANILLA_LIKE_EXTENDED','Barrage task timeout180 requires attack target and absent barrage cooldown. Four potential volleys of8 debris (fired<=30 allows total32), cooldown field10 decremented on subsequent task ticks; no continuous LOS gate. Triangle spread deviation2.297*(distanceSquared^.25*.5), speed uses Fireball native direction. Optional alternating melee within3. Debris is concrete custom Fireball using EntityType.SMALL_FIREBALL. On non-wildfire-allies contact ignite5 seconds and request5 fireball; failed hurt restores previous fire ticks, success runs native enchantment post effects. Block contact adjacent air may ignite under mobGriefing; no explosion. No deflection (hurtfalse).', 'SmallFireball entity/block damage','Adds ally predicate and barrage scheduler. Uses raw game rule for block fire, unlike installed SmallFireball loader grief event. Registry type remains SMALL_FIREBALL, so reload is not guaranteed to retain custom concrete class.',[c('BARRAGE','4*8 projectiles; CD10 plus decrement/else task step; cooldown150..300 onstop',{'volley_size':8,'max_volley_count':4,'cooldown':10,'task_timeout':180,'stop_cd_min':150,'stop_cd_max':300},['live target','task memory gates']),c('FIREBALL','5 direct fireball plus ignite5s; rollback fire on hurtfalse',{'damage':5,'ignite_seconds':5},['not wildfire ally','hurt result'],'VANILLA_DIRECT'),c('BLOCK_FIRE','native BaseFireBlock at adjacent air',binary=['mob owner requires mobGriefing'],relation='VANILLA_DIRECT')],[DEBRIS,TASK+'wildfire/WildfireBarrageAttackTask',BR+'WildfireBrain'],state='Projectile inherits fireball state under vanilla SMALL_FIREBALL identity; task debris cooldown not reset by start. Wildfire disabled by installed config.')
shock=add('wildfire_shockwave','Wildfire shockwave native melee AoE','VANILLA_LIKE_EXTENDED','Task requires visible attackable player within6 and absent shock cooldown. At task counter20 scans entity AABB6, excludes creative/spectator and wildfire_allies, calls native Mob.doHurtTarget. Request uses ATTACK_DAMAGE8 and ATTACK_KNOCKBACK declared32 but native range clamps it to5; native knockback amount is attribute*.5 before recipient resistance. Animation1.2s supplies24-tick duration; smoke is not explosion/fire. stop cooldown150..300.', 'Native Mob melee and knockback','AoE scheduling/eligibility, not custom damage identity or explosion.',[c('AOE_MELEE','counter20, AABB6, native melee attribute8',{'counter':20,'box':6,'damage_attribute':8,'duration_ticks':24},['target within6','not allies'],'VANILLA_DIRECT'),c('KNOCKBACK','clamp declared32 to5; native melee strength2.5 before recipient resistance',{'declared':32,'clamped':5,'strength':2.5},['successful native melee'],'VANILLA_DIRECT')],[WI,TASK+'wildfire/WildfireShockwaveAttackTask','common/entity/animation/WildfireAnimations'])
summon=add('wildfire_blazes','Wildfire native Blaze summons','VANILLA_LIKE_EXTENDED','Eligible fight task creates max(0,randomInclusive(1,2)-storedCount) native Blazes, until stored count2. Offset X/Z[-2,2],Y+1; native finalizeSpawn(MOB_SUMMONED), target and Wildfire UUID assigned. Count increments without checking add success. Native Blaze melee and small fireballs remain native. Blaze death HEAD callback resolves Wildfire UUID and decrements its count before native death outcome. stop cooldown600..1200, task duration20.', 'Native Blaze attacks','Custom ownership/count replenishment, with native summoned attack implementations.',[c('SUMMON_COUNT','max(0,U[1,2]-count), cap2; CD600..1200',{'cap':2,'cooldown_min':600,'cooldown_max':1200,'duration':20},['attack target','summon memory absent']),c('NATIVE_BLAZE_ATTACK','native melee6; ranged small fireball5 + fire5s',{'melee':6,'fireball':5},relation='VANILLA_DIRECT')],[TASK+'wildfire/WildfireSummonBlazeTask',MX+'BlazeEntityMixin',MX+'BlazeLivingEntityMixin',BR+'WildfireBrain'],state='Blaze WildfireUuid saved; Wildfire count saved. Canceled death/spawn failure can desynchronize count; no corrective production change.')
snow=add('snowball_wildfire','Snowball extra Wildfire request','VANILLA_LIKE_EXTENDED','WrapMethod Snowball.onHitEntity executes original, then requests thrown3 for Wildfire target, otherwise thrown0. Applies to all Snowball callback executions, not only Wildfire. Original Snowball separately requests Blaze3/other0. No extra source or DOT. Native hurt/cooldown gates and Wildfire shield budget remain.', 'Snowball Blaze bonus','Adds Wildfire-specific second native thrown request, and second zero call for other targets.',[c('SNOWBALL_HIT','after original: Wildfire3,other0',{'wildfire':3,'other':0,'vanilla_blaze':3},['concrete Wildfire target'],'VANILLA_DIRECT')],[MX+'SnowballEntityMixin'])
mauler=add('mauler_enchantment_reserve','Mauler enchantment reserve and attributes','CUSTOM_RESOURCE','Nonangry Mauler consumes offered enchanted item/book (creative exempt) when storedXP<1395. Value=sum noncurse enchantment minCost(level), cap1395; cursed-only item can be consumed for0. Every tick size=1+storedXP/1395*1.25; SCALE=size, maxHP=int(20*size), attack=4*size (4..9, despite registration8). MaxHP write does not heal. Native attack override requests mob_attack directly, no parent Mob enchantment/knockback processing. Bottles withdraw floor(XP/7), capped by held count, consume bottles even creative; addItem result unchecked. XP reward=stored reserve.', 'Grindstone noncurse cost and native attributes','Stored resource couples consumption to live size/health cap/damage. Grindstone computes randomized XP payout, not deterministic stored attribute reserve.',[c('RESOURCE','store min(1395,old+sum noncurse minCost(level))',{'cap':1395,'bottle_cost':7},['not angry','offered enchanted item']),c('ATTRIBUTE_BASE','size=1+XP/1395*1.25; maxHP=int(20*size); attack=4*size',{'base_scale':1,'scale_gain':1.25,'base_hp':20,'base_attack':4},['setBaseValue not heal'],'VANILLA_DIRECT'),c('MELEE','request current ATTACK_DAMAGE through mob_attack',binary=['not burrowed'],relation='VANILLA_DIRECT')],[MA],state='StoredExperiencePoints and burrow state saved/synced. Setter sets xpReward; normal death admission applies. Native range for offered items0..1395; external NBT values not assumed clamped.')
burrow=add('mauler_burrow','Mauler burrow self-control state','CUSTOM_CONTROL','When not angry/day/not navigating/cooldown<=0, random>=.999 and ground sand/red_sand/dirt/coarse_dirt/grass_block, start burrow600..1200 goal ticks. Set invulnerable=true; animation progress +.04/server tick, invisible at1. No pushing/doPush or attack while buried. But Mauler.hurt first stops a RUNNING burrow before super.hurt, clearing invulnerability; not reliable hit immunity. Melee goal start also stops it; melee tick waits until progress decays to0. Stop clears invisibility/invulnerability/buried, cooldown3000..6000 entity ticks.', 'Native invulnerable/invisible flags and goal scheduling','Custom state/timer and pre-hurt interruption; no status cure or guaranteed stun/defense.',[c('BURROW_FLAGS','set flags; animation +/- .04; stop clears',{'animation_step':.04,'duration_goal_min':600,'duration_goal_max':1200,'cooldown_min':3000,'cooldown_max':6000,'attempt_chance':.001},['day','not angry','supported ground','hurt interrupts before admission'])],[MA,EN+'ai/goal/mauler/MaulerBurrowDownGoal',EN+'ai/goal/mauler/MaulerMeeleAttackGoal'],state='Buried/progress/cooldown/goal duration saved; goal running flag transient. Goal ticks are not automatically wall/entity ticks; inherited Goal scheduling applies.')
copper=add('copper_oxidation','Copper Golem oxidation and statue state','CUSTOM_CONTROL','Unwaxed/nonimmobilized server tick chance.00002 increments oxidation. MOVEMENT_SPEED base=.2-min(ordinal,2)*.033333335 unless lightning flag then.3. Oxidized sets WasStatue=true; isImmobilized=oxidized OR WasStatue. Statue applies saved pose snapshot and stops movement; control/brain/push overrides use immobilized. Scraping reduces oxidation but does not clear WasStatue, so do not claim restored normal AI. Honeycomb waxes only nonimmobilized; axe removes wax or one stage with1 durability outside creative.', 'Copper block weathering and entity movement','Entity persistent statue/control flag plus movement base, not vanilla Slowness.',[c('OXIDATION_STATE','chance.00002/tick; ordinal0..3; WasStatue latches',{'chance':.00002,'stages':4},['server','unwaxed','not immobilized']),c('MOVEMENT_BASE','.2-min(ordinal,2)*.033333335; lightning .3',{'base':.2,'per_stage':.033333335,'lightning':.3},['setOxidationLevel updates attribute'],'VANILLA_DIRECT')],[CO,BR+'CopperGolemBrain',UT+'MovementUtil'],state='Oxidation/wax/WasStatue/lightning counter and snapshot saved; statue latch not cleared by scraping.')
lightning=add('copper_lightning','Copper Golem lightning restoration','VANILLA_LIKE_EXTENDED','thunderHit calls parent first, then clears fire and sets currentHP=maxHP. Refresh lightning counter1200..2400; if unwaxed set oxidation UNAFFECTED (attribute recalculation sees lightning flag). Flag decrements only while not oxidized; expiry does not itself recompute movement attribute. Default lightning DamageSource has no owner, so owner-instance-LightningBolt hurt veto is not immunity to natural lightning; parent normally requests5 before restoration.', 'Lightning contact and direct health restoration','Custom full restoration/extinguish and oxidation flag. Do not infer general lightning invulnerability or automatic speed restoration at timeout.',[c('RESTORATION','after parent thunderHit clear fire; setHealth(maxHP)',binary=['native thunderHit callback'],relation='VANILLA_DIRECT'),c('LIGHTNING_STATE','timerU[1200,2400]; unwaxed oxidation reset',{'min':1200,'max':2400},['unwaxed for oxidation'])],[CO])
repair=add('golem_repair','Copper/Tuff Golem native repair','VANILLA_LIKE_EXTENDED','Player interaction with damaged Copper Golem + copper ingot or Tuff Golem + tuff requests heal5 and consumes1 outside creative. Native heal cap/events retained; no effect, periodic regen or maxHP increase.', 'Iron Golem iron-ingot repair25','Same native heal/consume primitive with different ingredients and5 rather than25.',[c('HEAL','heal5; consume1 outside creative',{'heal':5,'consumption':1,'vanilla_iron_golem_heal':25},['damaged','ingredient','server'],'VANILLA_DIRECT')],[CO,TU])
golemadmission=add('golem_source_veto','Golem narrow source veto','BINARY_MECHANIC','Copper/Tuff hurt reject only owner instanceof LightningBolt or exact cached sweetBerryBush source. Default lightning source is ownerless, so natural lightning passes this predicate; Copper restores HP later in thunderHit. This is not damage-tag-wide lightning immunity. Other hits use parent admission; Tuff wakes custom sleep pose before parent outcome.', 'Native source eligibility','Narrow object/owner predicate added on two golem classes.',[c('SOURCE_VETO','owner LightningBolt OR source===cached sweetBerryBush ->false',binary=['owner concrete type','source object identity'])],[CO,TU])
glaregen=add('glare_regeneration','Glare native periodic healing','VANILLA_EQUIVALENT','Alive server-side Glare requests heal1 whenever entity tickCount%10==0; tamed or wild. Native heal event/cap applies.', 'Allay periodic heal1/10 ticks','Same periodic native healing primitive, different recipient class.',[c('HEAL','heal1 each10 entity ticks',{'heal':1,'interval':10},['alive','server'],'VANILLA_DIRECT')],[GL])
glarefood=add('glare_food_healing','Glare dropped-berry healing','VANILLA_LIKE_EXTENDED','Glare pickup accepts glow berries when no item-pickup cooldown/held item and native pickup admission. Splits excess count back to world, consumes picked entity and heals2*food nutrition (fallback1 nutrition if missing component), then cooldown20..200 ticks. Native glow berries nutrition2 =>heal4. Direct player heal method has same2*nutrition, but caller also requires !isFood(glowberries) while installed glare_tempt_items includes glowberries: unreachable under pinned tags; not a second legitimate current source.', 'Wolf food healing','Custom dropped-item producer, doubled nutrition and pickup cooldown; direct hand-heal branch contradicts installed tag.',[c('FOOD_HEAL','heal2*nutrition, missing component fallback2 HP',{'nutrition_factor':2,'default_glow_berry_heal':4,'cooldown_min':20,'cooldown_max':200},['native pickup gates','glow berries'],'VANILLA_DIRECT')],[GL,BR+'GlareBrain','data/friendsandfoes/tags/item/glare_tempt_items.json'],state='Item pickup cooldown uses native Brain memory; no new heal status.')
glaretame=add('glare_taming_health','Glare taming health transition','VANILLA_LIKE_EXTENDED','Untamed Glare offered glow berries consumes1 outside creative; server random1/3 tames. applyTamingSideEffects sets maxHP30 and fills to max when tame; untame maxHP10 without explicit currentHP adjustment. Tamed offspring inherit owner and side effects.', 'Wolf taming health attributes','Native tame/owner model with custom10->30 health and berry source.',[c('TAME_HEALTH','1/3 chance; maxHP10->30 and setHealth(maxHP)',{'chance':1/3,'wild_hp':10,'tamed_hp':30},['server','untamed','glow berry'],'VANILLA_DIRECT')],[GL])
glow=add('glare_hostile_reveal','Glare hostile reveal','VANILLA_LIKE_EXTENDED','Owned adult tamed Glare, not leashed/sitting/passenger and not daytime with open sky, reaches a valid remembered dark spot within2. Grumpy task start scans block-position unit AABB inflated24, all Monster subclasses (not all Enemy), no LOS/alliance/radius-sphere filter, adds native Glowing200/0 once on task start. Not a continuous damage aura. Dark-spot locating cooldown400..800 after stop.', 'Glowing','Custom dark-spot discovery and Monster AoE producer; native outline effect only.',[c('GLOWING','literal200/0 once/task start; AABB24',{'duration':200,'amplifier':0,'box':24,'arrival_distance':2},['owner exists','valid dark spot','Monster recipient'],'VANILLA_DIRECT')],[GL,TASK+'glare/GlareBeGrumpyAtDarkSpotTask',TASK+'glare/GlareTravelToDarkSpotTask',TASK+'glare/GlareLocateDarkSpotTask',BR+'GlareBrain'])
rascalhits=add('rascal_hit_counter','Rascal three-hit disappearance','CUSTOM_RESOURCE','Unnamed Rascal receiving Player-owned source increments DamageCount and returnsfalse without parent hurt; at count>=3 discards. No amount/success/physical-only condition, so projectiles with Player owner qualify. Named Rascal and nonplayer-owner sources use ordinary damage.', 'Native hurt rejection/entity discard','Player-owned hit counter replaces HP damage for unnamed Rascal.',[c('HIT_COUNTER','increment per incoming callback; >=3 discard,false',{'threshold':3},['Player source owner','no custom name'])],[RA],state='DamageCount synced but no custom NBT write/read; resets after reload. No timed reset or status cure.')
rascalhide=add('rascal_hide','Rascal hide-and-seek concealment','VANILLA_COMPOSITE','Unnamed Rascal wait task requires eligible live player within5 and interaction memory; increments caught count onstart. Onstop, reward threshold causes discard; otherwise Invisibility200/0 and up to64 randomTeleport attempts with x/z +/-8, y[-4,3] clamped to world, only destination in mineshaft. Successful move farther than10 stops attempts; a closer successful move can still move entity before another attempt. Native collision-safe teleport, no damage.', 'Invisibility and randomTeleport','Custom mineshaft/interaction state and disappearance, no invulnerability from invisibility.',[c('INVISIBILITY','literal200/0',{'duration':200,'amplifier':0},relation='VANILLA_DIRECT'),c('TELEPORT','64 attempts; mineshaft gate; farther than10 ends',{'attempts':64,'spread_xz':8,'success_distance':10},['unnamed','taskstop','not reward threshold'],'VANILLA_DIRECT')],[RA,TASK+'rascal/RascalWaitForPlayerTask',BR+'RascalBrain'],state='Caught/damage counts synced, not custom-saved. isHidden reads Brain AVOID_TARGET Player, not Invisibility. Reward iff caughtCount==3; nod cooldown200. Task counter90 and target pointers transient.')
tuffstate=add('tuff_glue_sleep','Tuff Golem glue/sleep control','CUSTOM_CONTROL','HoneycombItem sets glued flag consuming1 outside creative. Axe clears glue; code damages axe1 only when instabuild=true (literal inverted condition retained). isNotImmobilized gates custom movement on animation0, inactive spawn ticks0, not glued/not custom sleeping pose. Home sleep task timeout6000..12000 and sleep cooldown6000..8000; native hurt wakes custom sleep pose before hurt result. isPushable checks inherited LivingEntity.isSleeping (bed state), not custom sleep pose: custom statue pose alone does not prove push immunity. No special damage or attack goal.', 'Native movement pause/sleep presentation','Custom glue and pose state, not Slowness or bed sleep protection.',[c('GLUE_CONTROL','persistent glued movement gate; honeycomb1; axe1 only creative branch',{'consumption':1},['HoneycombItem','AxeItem']),c('SLEEP_CONTROL','home sleep timeout6000..12000; prehurt wake',{'min':6000,'max':12000},['custom pose vs native bed state'])],[TU,BR+'TuffGolemBrain',TASK+'tuffgolem/TuffGolemSleepTask',UT+'MovementUtil'],state='Glued/pose/home data saved; custom pose distinct from bed sleeping. Carrying changes getSpeed .225->.175; no target slow aura.')
tempt=add('tuff_temptation','Tuff Golem native temptation target extension','VANILLA_LIKE_EXTENDED','TemptGoal fallback after vanilla canUsefalse searches TuffGolem in AABB(16,3,16) through the existing targetingConditions; follows native held-item temptation predicate. Starts/looks/walks toward Tuff instead of Player, stops navigation below distance squared6.25. Scared goal rejects motion squared>.01 or angle changes>5 within squared distance36. Does not set combat target or mind-control hostile mobs without TemptGoal. Continuation caveat: ModifyReturnValue runs after original canContinueToUse; scared native goal dereferences its Player field. A fresh Tuff-only fallback can leave Player null and reach that dereference before the extension. Static failure path, not runtime-certified lure. Fallback also runs after vanilla cooldown refusal; no extra cooldown check.', 'TemptGoal player-held food lure','Extends eligible lure entity to Tuff Golem; native food and scare rules preserved.',[c('AI_LURE','native temptation predicate; box16,3,16; stop distance2.5',{'box_xz':16,'box_y':3,'stop_distance':2.5,'scare_distance':6,'move_squared':.01,'angle':5},['existing TemptGoal','valid held food'],'VANILLA_DIRECT')],[MX+'TemptGoalMixin',TU])
prey=add('mauler_prey_rules','Mauler prey and native avoidance rules','VANILLA_LIKE_EXTENDED','Mauler nearest-target tag includes chicken/rabbit/frog/slime/zombie but rejects non-size1 Slimes and nonbaby Zombies. Native hurt-retaliation/anger400..1000 ticks retained. Chicken goal priority2 and Rabbit priority4 avoid nonburrowed Mauler within10 at speeds1.4/2.2 respectively. Native AvoidEntityGoal navigation, not a Fear effect or forced player control.', 'Native target predicates/AvoidEntityGoal','Adds Mauler-specific recipients and burrow-dependent avoidance.',[c('TARGET_RULES','tag + baby/size filters; avoid10',{'range':10,'chicken_speed':1.4,'rabbit_speed':2.2,'anger_min':400,'anger_max':1000},['nonburrowed for avoidance','entity class/tag'],'VANILLA_DIRECT')],[MA,MX+'ChickenEntityMixin',MX+'RabbitEntityMixin','data/friendsandfoes/tags/entity_type/mauler_prey.json'])
trap=add('zombie_horse_trap','Zombie Horse trap riders','VANILLA_LIKE_EXTENDED','Trapped zombie horse activates for nearest noncreative/nonspectator Player within10. Clears trap, tames/adults original horse, spawns visual-only lightning, mounts a native adult Zombie; creates3 more tamed adult ZombieHorses with riders. New horses and riders invulnerableTime60, persistence; empty rider main/head gets iron sword/chainmail helmet; native MOB_SPAWN_EQUIPMENT provider enchants after clearing those enchants. Native zombie melee remains unchanged. Trap lifetime check uses postincrement >=18000 then discard.', 'Skeleton horse trap','Same trap pattern with four zombie/horse pairs, native range10; Zombie melee/gear replaces Skeleton ranged attacks. Visual trigger lightning does no damage.',[c('TRAP_SUMMON','1 existing+3 horses/riders; timeout18000; cooldown field60',{'pairs':4,'trigger_range':10,'trap_timeout':18000,'invulnerable_time':60},['trap flag','eligible player'],'VANILLA_DIRECT')],[EN+'ai/goal/zombiehorse/ZombieHorseTrapTriggerGoal',MX+'ZombieHorseEntityMixin',MX+'ZombieHorseAnimalEntityMixin',MX+'ZombieHorseAbstractHorseEntityMixin'],state='ZombieTrap/ZombieTrapTime saved; trap flag adds/removes goal. Native attack cooldown is not absolute invulnerability60.')
storm=add('extra_storm_lightning','Additional storm lightning path','VANILLA_LIKE_EXTENDED','After native ServerLevel.tickChunk, enabled zombie horse trap feature adds independent rain/thunder roll1/100000 per chunk invocation and rain-at-target. Horse chance is doMobSpawning AND random<effectiveDifficulty*.01 and no lightning-rod tag beneath. Always adds LightningBolt for successful weather roll: visualOnly when horse spawned, real native lightning otherwise. This is an additional environmental native lightning/fire path; trap-trigger lightning separately visual-only.', 'Vanilla storm lightning','Additional roll and zombie-trap condition, unchanged real LightningBolt source/damage/fire implementation.',[c('LIGHTNING','weather roll1/100000; horse chance .01*effectiveDifficulty; real bolt if no horse',{'weather_chance':.00001,'horse_difficulty_factor':.01,'native_lightning_request':5},['rain/thunder','native lightning eligibility'],'VANILLA_DIRECT')],[MX+'ServerWorldMixin'])
nativeflags=add('native_type_defenses','Native type defenses and vulnerabilities','VANILLA_DIRECT','Installed entity tags: Iceologer freeze immune and powder-snow walkable; Copper/Tuff/Wildfire fall-damage immune; Wildfire freeze-hurts-extra (native incoming freezing multiplier5); Crab arthropod and underwater breathing. Entity builders fireImmune for Wildfire/IceChunk/PlayerIllusion. Glare causeFallDamagefalse/checkFallDamage empty, Copper/Tuff decreaseAirSupply returns unchanged air; these override/enable existing native defenses. Wildfire isSensitiveToWatertrue and fallfalse, downward velocity*.6 while falling; no universal magic immunity.', 'Native entity tags/fire immunity/fall and breath overrides','Direct native primitives on new recipient types; not a registered custom status.',[c('NATIVE_TAG_FLAGS','native tag-driven immunity or vulnerability',{'freeze_multiplier':5},['exact recipient type/tag'],'VANILLA_DIRECT')],[REG,EN+'GlareEntity',CO,TU,WI]+[k for k in W if k.startswith('data/minecraft/tags/entity_type/')])

# Distinct delivery implementations; shared formulas do not erase source cases.
p('iceologer_spell',[freeze],['SPELL','MOB_ATTACK'],'friendsandfoes:iceologer','Live eligible target; let native SlowTargetGoal cast.',[ICE,ICE+'$SlowTargetGoal'],'iceologer')
p('ice_chunk_owned',[chunk],['SUMMONED_ATTACK','AOE'],'Iceologer native ice chunk','Native summon/collision with owner UUID resolving; preserve magic source.',[CHUNK,ICE+'$SummonIceChunkGoal'],'iceologer')
p('ice_chunk_owner_absent',[chunk],['SUMMONED_ATTACK','AOE'],'Native ice chunk whose owner no longer resolves','Legitimate persisted/native chunk lifecycle; no fabricated damage source.',[CHUNK],'iceologer')
p('illusioner_blind',[blind],['SPELL','MOB_ATTACK'],'friendsandfoes:illusioner','Local effective difficulty>2 and new targetID.',[ILL,ILL+'$IllusionerBlindnessSpellGoal'],'illusioner')
p('illusioner_reaction',[illusions],['MOB_ATTACK','OTHER'],'friendsandfoes:illusioner','Native owned incoming hit, cooldown0; inspect real-vs-decoy gates.',[ILL],'illusioner')
p('illusioner_repeat',[illusions],['SUMMONED_ATTACK','OTHER'],'Attacked Illusioner with live target','Let600 cooldown expire; no injected spawn.',[ILL],'illusioner')
p('illusioner_clone_bow',[illusions,blind],['SUMMONED_ATTACK','PROJECTILE'],'Native summoned Illusioner clone','Bow AI and its own blindness goal; decoy hurt/discard and saved lifetime.',[ILL],'illusioner')
for key,e,item in [('freezing',freezetotem,'totem_of_freezing'),('illusion',illusiontotem,'totem_of_illusion')]:
    p(key+'_hand',[e],['PASSIVE_ITEM','AOE'],'friendsandfoes:'+item+' held','Pre-hit HP<=50%, owner source, admitted type; test rejected/zero native hit too.',[PLAYER,TOT],'custom_totems')
    p(key+'_curios',[e],['ACCESSORY_PROC','AOE'],'friendsandfoes:'+item+' in native Curios slot','No earlier held tagged totem; preserve source slot and native predicate.',[PLAYER,TOT,'neoforge/modcompat/CuriosCompat'],'custom_totems')
p('crown_tick',[crown],['ARMOR_PROC'],'friendsandfoes:wildfire_crown','Native head slot; burning and lava-eye refresh admission cases.',[PLAYER],'crown')
p('curios_undying',[curiototem],['ACCESSORY_PROC'],'minecraft:totem_of_undying in Curios','Native death protection caller and bypass admission.',[MX+'LivingEntityMixin','neoforge/modcompat/CuriosCompat'],'undying')
p('wildfire_shield',[shield],['OTHER'],'friendsandfoes:wildfire','Unavailable with installed enableWildfire=false. Future separately authorized native configuration only.',[WI],'wildfire')
p('wildfire_counter',[shield],['MOB_ATTACK','MELEE'],'Wildfire shield break + living source owner','Same native threshold; return request8 and its own hurt gates.',[WI],'wildfire')
p('wildfire_regeneration',[shield],['OTHER'],'Native Wildfire shield countdown','Allow the native300-tick regeneration timer to reach0, separately from incoming-hit budget/counter callbacks. Current config disables Wildfire.',[WI],'wildfire')
p('wildfire_barrage_entity',[barrage],['PROJECTILE','MOB_ATTACK'],'Native Wildfire barrage','Actual custom debris concrete class; native collision versus allied/nonallied target.',[DEBRIS,TASK+'wildfire/WildfireBarrageAttackTask'],'wildfire')
p('wildfire_barrage_block',[barrage],['PROJECTILE','ENVIRONMENT'],'Native Wildfire debris block impact','Adjacent air; raw mobGriefing gate and resulting native fire.',[DEBRIS],'wildfire')
p('wildfire_shock',[shock],['AOE','MELEE','MOB_ATTACK'],'Native Wildfire shockwave','Task tick20, native melee/knockback.',[WI,TASK+'wildfire/WildfireShockwaveAttackTask'],'wildfire')
p('wildfire_blaze_melee',[summon],['SUMMONED_ATTACK','MELEE'],'Wildfire-summoned minecraft:blaze','Native close melee; count/UUID/death callback.',[TASK+'wildfire/WildfireSummonBlazeTask',MX+'BlazeEntityMixin'],'wildfire')
p('wildfire_blaze_fireball',[summon],['SUMMONED_ATTACK','PROJECTILE'],'Wildfire-summoned minecraft:blaze','Native ranged AI/SmallFireball, distinct from custom debris.',[TASK+'wildfire/WildfireSummonBlazeTask'],'wildfire')
p('snowball_callback',[snow],['THROWN_PROJECTILE'],'minecraft:snowball + Wildfire/Blaze/other target cases','Original callback then FAF second request. Wildfire case disabled by current config.',[MX+'SnowballEntityMixin'],'snowball')
p('mauler_feed',[mauler],['ACTIVE_ITEM'],'friendsandfoes:mauler + enchanted item/book','Native interaction: reserve saturation/curse-only/creative cases.',[MA],'mauler')
p('mauler_bottle',[mauler],['ACTIVE_ITEM'],'Mauler + glass bottles','Withdraw7 XP per bottle and recompute attributes.',[MA],'mauler')
p('mauler_attack',[mauler],['MELEE','MOB_ATTACK'],'Native Mauler with legitimately fed reserve','Compare reserve endpoints using native attack; no direct damage injection.',[MA],'mauler')
p('mauler_target_selection',[prey],['OTHER'],'Native Mauler + tagged prey','Native nearest-target and hurt-retaliation goals; preserve small-Slime/baby-Zombie predicates separately from injected chicken/rabbit avoidance.',[MA],'mauler')
p('mauler_burrow',[burrow],['OTHER'],'Native Mauler on allowed daytime ground','Let native burrow start/stop and hurt interruption occur.',[MA,EN+'ai/goal/mauler/MaulerBurrowDownGoal'],'mauler')
p('mauler_avoid_chicken',[prey],['OTHER'],'minecraft:chicken + nonburrowed Mauler','Injected AvoidEntityGoal range10/speed1.4.',[MX+'ChickenEntityMixin'],'mauler')
p('mauler_avoid_rabbit',[prey],['OTHER'],'minecraft:rabbit + nonburrowed Mauler','Injected AvoidEntityGoal range10/speed2.2; prey filters include separate slime/zombie cases.',[MX+'RabbitEntityMixin',MA],'mauler')
p('copper_oxidation',[copper],['OTHER'],'friendsandfoes:copper_golem','Native oxidation + honeycomb/axe interactions; WasStatue latch.',[CO],'golems')
p('copper_thunder',[lightning,golemadmission],['ENVIRONMENT'],'Copper Golem + native lightning','Ownerless native lightning admission then restoration; narrow owned-source veto not conflated.',[CO],'golems')
p('copper_repair',[repair],['ACTIVE_ITEM'],'Copper Golem + copper ingot','Native damaged-entity repair interaction.',[CO],'golems')
p('tuff_repair',[repair],['ACTIVE_ITEM'],'Tuff Golem + tuff','Native damaged-entity repair interaction.',[TU],'golems')
p('golem_source_veto',[golemadmission],['ENVIRONMENT','OTHER'],'Copper/Tuff Golem + sweet berry bush','Native source identity; ordinary lightning remains distinct.',[CO,TU],'golems')
p('tuff_glue_sleep',[tuffstate],['ACTIVE_ITEM','OTHER'],'Tuff Golem + honeycomb/axe, native home sleep','Custom movement gate and prehurt wake; no bed-sleep assumption.',[TU,TASK+'tuffgolem/TuffGolemSleepTask'],'golems')
p('tuff_lure',[tempt],['PASSIVE_ITEM','OTHER'],'Tuff Golem holding valid food + animal TemptGoal','Fallback source and native scare predicates.',[TU,MX+'TemptGoalMixin'],'golems')
p('glare_regeneration',[glaregen],['OTHER'],'friendsandfoes:glare','Alive server-side entity ticks10.',[GL],'glare')
p('glare_pickup',[glarefood],['OTHER'],'Glare + dropped glow berries','Native pickup cooldown/held-item gates; direct hand heal excluded as dormant.',[GL,BR+'GlareBrain'],'glare')
p('glare_taming',[glaretame],['ACTIVE_ITEM'],'Untamed Glare + glow berries','Native1/3 tame chance and full-heal transition; offspring alternate native route.',[GL],'glare')
p('glare_tamed_offspring',[glaretame],['OTHER'],'Tamed native Glare breeding','getBreedOffspring copies owner and calls setTame(true,true), reaching the same health side effects without the player-feeding chance.',[GL],'glare')
p('glare_dark_spot',[glow],['PASSIVE_AURA','AOE'],'Owned Glare + valid dark spot + Monster','Native taskstart only; compare Monster vs Enemy, through-wall/AABB cases.',[GL,TASK+'glare/GlareBeGrumpyAtDarkSpotTask'],'glare')
p('rascal_incoming',[rascalhits],['OTHER'],'Unnamed Rascal + Player-owned native attack','Three incoming callbacks; named/ownerless controls.',[RA],'rascal')
p('rascal_hide',[rascalhide],['OTHER'],'Unnamed Rascal native hide-and-seek','Native taskstop in mineshaft; reward/discard threshold controls.',[RA,TASK+'rascal/RascalWaitForPlayerTask'],'rascal')
p('zombie_trap',[trap],['SUMMONED_ATTACK','MELEE'],'Native thunder-created trapped minecraft:zombie_horse','Proximity trigger and four native rider pairs; no summoned-source fabrication.',[EN+'ai/goal/zombiehorse/ZombieHorseTrapTriggerGoal',MX+'ZombieHorseEntityMixin'],'storm_trap')
p('extra_lightning',[storm],['ENVIRONMENT'],'Native rain/thunder chunk path','Real bolt when horse gate fails; visual bolt when succeeds.',[MX+'ServerWorldMixin'],'storm_trap')
p('type_defenses',[nativeflags],['ENVIRONMENT','OTHER'],'Listed native Friends & Foes recipient types','Native fire/fall/freezing/breath/arthropod admissions; Wildfire config restriction retained.',[REG,GL,RA,WI],'native_defenses')

for e in E:
    e['native_behavior']=dict(effect_lifecycle=LIFECYCLE,damage_admission=HURT,freeze_semantics=FREEZE if any('FROZ' in x['primitive'] or 'FREEZE' in x['primitive'] for x in e['components']) else 'Not a freeze package.')
    e['eligibility']='See actual_behavior and binary_parameters; native source/recipient restrictions are not relaxed.'
    e['availability']='DISABLED_BY_INSTALLED_CONFIG' if e in [shield,barrage,shock,summon] else 'NATIVE_CODE_PRESENT; this is not a runtime success assertion.'

def draft():
    obj=dict(schema='tno.external_effects.partial_draft.v1',baseline=BASELINE,mod_key='friendsandfoes',status='PARTIAL',checkpoint='R2e-draft',starting_sha=START,semantic_coverage_complete=False,promoted_to_catalog=False,effects=E,paths=P,remaining=['Finalize coverage/exclusions, comparison claims and exact source cases; validate then promote.'],**boundary_flags())
    import copy
    obj=copy.deepcopy(obj)
    for e in obj['effects']:e.update(inspection_status='DRAFT',unresolved_ambiguities=None,pending=obj['remaining'])
    for p in obj['paths']:p['status']='DRAFT'
    write_json(OUT/'partial-drafts/friendsandfoes-r2e-draft.json',obj)
    print(len(E),'draft packages',len(P),'paths')

if __name__=='__main__':draft()
