"""Royal semantic packages, with independent native producer/admission cases.

Static research only. Run with --partial until final completeness validation passes.
"""
from catalog_common import *
from collections import Counter
from assemble_batch import refresh

START='94532221ac23681deef5462f7932a8a405f5979e'
W={w['id'].removeprefix('rv:'):w for w in read_json(OUT/'native-evidence/royalvariations.json')['witnesses']}
E=[];P=[]
EV='common/events/RVEvents';FX='common/effects/RVEffects'
AR='common/entities/projectile/RoyalArrow';BZ='common/entities/projectile/RoyalBomb'
SK='common/entities/hostile/RoyalSkeleton';ZO='common/entities/hostile/RoyalZombie';CR='common/entities/hostile/RoyalCreeper';EN='common/entities/neutral/RoyalEnderman'
AN='common/entities/projectile/SpectralAnvil';PE='common/entities/projectile/ThrownRoyalEnderPearl';TG='common/entities/projectile/TangleEntity'

def proof(*keys):
    return [dict(evidence_file='native-evidence/royalvariations.json',witness_id=W[k]['id'],entry=W[k]['entry'],methods=sorted({m['name'] for m in W[k].get('methods',[])})) for k in keys]

def c(name,formula,numbers=None,binary=None,relation='CUSTOM'):
    return dict(primitive=name,formula=formula,numerical_parameters=numbers or {},binary_parameters=binary or [],vanilla_relation=relation)

def add(key,name,kind,actual,closest,difference,components,keys,registry=None,state=None):
    e=dict(id='royalvariations:'+key,mod_key='royalvariations',display_name=name,primary_classification=kind,
        actual_behavior=actual,human_summary=actual,registry_ids=registry or [],implementation=proof(*keys),
        closest_vanilla_equivalent=closest,vanilla_similarities='Uses native entity/effect/attribute/event APIs; exact shared primitives are stated below.',vanilla_differences=difference,
        components=components,numerical_parameters={k:v for x in components for k,v in x['numerical_parameters'].items()},
        binary_parameters=[v for x in components for v in x['binary_parameters']],
        scalable_parameter_candidates=[dict(primitive=x['primitive'],parameters=list(x['numerical_parameters']),meaning='Observation only; no scaling formula or eligibility change proposed.') for x in components if x['numerical_parameters']],
        custom_state=state or 'No additional target capability beyond the native state described in this package.',
        delivery_paths=[],primary_test_source=None,alternate_sources=[],inspection_status='DRAFT',unresolved_ambiguities=None,pending=['Final Royal coverage, comparison and compatibility validation.'])
    E.append(e);return e

def p(key,rows,labels,source,setup,keys):
    row=dict(id='royalvariations:'+key,mod_key='royalvariations',status='DRAFT',labels=labels,effect_ids=[e['id'] for e in rows],primary_source=source,setup=setup,implementation=proof(*keys))
    P.append(row)
    for e in rows:
        e['delivery_paths'].append(row['id'])
        if not e['primary_test_source']:e['primary_test_source']=source
        elif e['primary_test_source']!=source and source not in e['alternate_sources']:e['alternate_sources'].append(source)

LIFECYCLE='Native MobEffectInstance admission/merge applies: stronger replaces and may hide weaker; equal amplifier extends only when longer, not additive-duration stacking. Modifiers use coefficient*(amplifier+1); attributes present on recipient only. Native AttributeInstance applies ADD_VALUE, then ADD_MULTIPLIED_BASE, then each ADD_MULTIPLIED_TOTAL factor, then attribute clamp. Milk/totem cures use installed NeoForge effect-cure membership and cancellable removal events; no Royal cure override. Ordinary saved active-effect state restores durations/amplifiers; Royal synced visual counters are reconstructed from active effects and not an independent debuff. Other mods may veto applicability/removal.'

def attrs(items):
    return [c('ATTRIBUTE_'+a, f'{op} {n}*(amplifier+1) on {a}',{'coefficient':n},['recipient has attribute'], 'VANILLA_LIKE_ATTRIBUTE')|dict(attribute=a,operation=op,coefficient=n) for a,n,op in items]
AV='ADD_VALUE';MT='ADD_MULTIPLIED_TOTAL'
fort=add('knightly_fortitude','Knightly Fortitude','VANILLA_COMPOSITE',
    'Armor +7, armor toughness +4 and knockback resistance +1 per amplifier level. Full Royal Knight material set gives wearer400/0 at incoming damage when current HP<=40% max and no Fortitude; owned living entities in point AABB5.5 receive400/1. Current HP is checked before this hit; no hurt-success requirement. Zombie Knighting also gives400/0.',
    'Armor, toughness and knockback-resistance attributes; Resistance is damage reduction instead.', 'No vanilla potion provides this three-attribute package. Resistance is not armor or knockback resistance.',
    attrs([('ARMOR',7,AV),('ARMOR_TOUGHNESS',4,AV),('KNOCKBACK_RESISTANCE',1,AV)]),[FX,EV,'utils/ItemHelper',ZO+'$KnightingGoal'],['royalvariations:knightly_fortitude'])
bless=add('royal_blessing','Royal Blessing','VANILLA_COMPOSITE','Royal Staff server use applies400/0 to user and600/1 to own pets within user AABB13; durability request1, cooldown300. Attack damage+3.5, attack speed+15%, movement+5%, armor+5 per level.',
    'Strength, Speed and native attack-speed/armor attributes','Strength is +3 ADD_VALUE and Speed +20% per level; this is a custom coefficient mixture, no literal vanilla effect holders.',attrs([('ATTACK_DAMAGE',3.5,AV),('ATTACK_SPEED',.15,MT),('MOVEMENT_SPEED',.05,MT),('ARMOR',5,AV)]),[FX,'common/items/RoyalStaffItem','utils/ItemHelper'],['royalvariations:royal_blessing'])
dazed=add('dazed','Dazed','VANILLA_COMPOSITE','Movement speed and ATTACK_DAMAGE each multiply by 1-0.6*(amplifier+1). At0 each is40% of pre-modifier value; at1 factor is-0.2, so an otherwise positive result reaches native minimum0 after final clamp. No attack-speed attribute modification: the modifier ID ends attack_speed but the actual holder is ATTACK_DAMAGE. Native producers: bomb200/0, Royal Creeper300/0, Time Bomb260/0. No stun/action lock or vanilla Slowness/Weakness holders.',
    'Slowness and Weakness','Slowness coefficient-.15 can match movement at level4, but Weakness subtracts4*(amp+1) ADD_VALUE; percentage attack reduction is not equivalent to flat Weakness.',attrs([('MOVEMENT_SPEED',-.6,MT),('ATTACK_DAMAGE',-.6,MT)]),[FX,'common/effects/RVBaseEffect',EV+'$TimeBombTask$1',BZ+'$1',CR+'$1'],['royalvariations:dazed'])
rush=add('undead_rush','Undead Rush','VANILLA_COMPOSITE','Movement+26% and attack speed+15% per level. ChosenVictimGoal gives undead pursuer60 ticks at victim Chosen Victim amplifier; canUse requires target.tickCount%40==0. Applicability event denies entities outside minecraft:undead; this is not a guaranteed every40-tick refresh while the goal already runs.',
    'Speed and attack-speed attribute','Speed is20% per level, Haste is a different mining/attack-speed package. Rush has native undead-tag eligibility.',attrs([('MOVEMENT_SPEED',.26,MT),('ATTACK_SPEED',.15,MT)]),[FX,EV,'common/entities/ai/ChosenVictimGoal'],['royalvariations:undead_rush'])
chosen=add('chosen_victim','Chosen Victim','CUSTOM_STATUS','Successful Royal Zombie parent melee gives400/0. At entity join server adds priority0 ChosenVictimGoal to minecraft:undead Mob unless it has an owner. Goal searches AABB20 and distance<=16, requires nonallied Player/IronGolem/player-owned entity carrying effect, standard targeting/LOS, and target.tickCount%40==0; assigns target through native goal and grants pursuer Undead Rush60/same amplifier. No attribute change on marked victim. Goal continuation uses native TargetGoal and does not independently require effect to remain.',
    'Native mob target goals','No vanilla named effect that recruits this undead recipient set and grants a pursuer buff.',[c('TARGET_SELECTION','priority0; distance<=16; tickCount%40==0',{'radius':16,'search_box':20,'tick_modulus':40},['undead Mob','no owner at join','eligible marked target']),c('PURSUER_BUFF','Undead Rush60/same amplifier',{'duration':60})],[FX,ZO,EV,'common/entities/ai/ChosenVictimGoal','utils/MobUtil'],['royalvariations:chosen_victim'])
marked=add('marked','Marked (Mark)','VANILLA_LIKE_EXTENDED','RoyalArrow.doPostHurtEffects calls parent, then when marking=true applies300 ticks. Amplifier0 if target OR owner Player, otherwise1. Mob owner admits only Player/IronGolem/player-owned target OR its current target. Upon addEffect returning true, non-Player owner and Player/IronGolem/player-owned recipient cause Enemy, non-NeutralMob, nonallied mobs in victim AABB32 to setTarget(victim), with victim noncreative/nonspectator gate. No LOS predicate in recruitment. Mark sets native glowing and dark-red team outline; server synced markedTick becomes5 while effect exists,0 after removal. No generic damage-vulnerability multiplier.',
    'Glowing plus Slowness-like attributes','Four modifiers plus conditional hostile recruitment; armor reduction is25% per level, not direct damage amplification. Mark attack damage is percentage, unlike Weakness.',attrs([('MOVEMENT_SPEED',-.1,MT),('ATTACK_DAMAGE',-.1,MT),('ATTACK_SPEED',-.1,MT),('ARMOR',-.25,MT)])+[c('GLOW_AND_RECRUIT','isCurrentlyGlowing=true; conditional AABB32 target assignment',{'recruit_box':32,'duration':300},['marking flag','post-hurt callback','successful addEffect for recruitment'])],[FX,AR,EV,'utils/MobUtil','mixin/LivingEntityMixin','mixin/EntityMixin','common/attachments/RVCapHelper'],['royalvariations:marked'])
trapped=add('trapped','Trapped / native net','CUSTOM_CONTROL','Native net scans overlap for target at active ticks2..4 (last eligible candidate can win; riding living vehicle substitutes). While active<lifeSpan, live nonboss-tag target with maxHP<=100 and canBeAffected(TRAPPED) is repositioned to net, velocity zeroed, then TRAPPED2/0 readded. Net lifespan50 from skeleton; generic default80. Trapped blocks jumpFromGround, Entity.push(DDD) and LivingKnockBackEvent; movement/swim factor1-(amp+1), KR+2*(amp+1), native bounds apply. Death removes effect. Cutting net requires direct LivingEntity with sword tag and source message mob/player/goety.summon; discards before parent hurt return. Cure alone can be reapplied while net remains eligible.',
    'Slowness, cobweb and knockback resistance','Exact position pin plus three callback vetoes and boss/maxHP admission is not Slowness or universal motion immunity. Other direct velocity writes remain possible.',attrs([('KNOCKBACK_RESISTANCE',2,AV),('neoforge:swim_speed',-1,MT),('MOVEMENT_SPEED',-1,MT)])+[c('POSITION_PIN','setPos(net); setDeltaMovementZERO; refresh2',{'refresh_duration':2,'max_HP':100,'skeleton_life':50,'default_life':80},['!c:bosses','canBeAffected','live']),c('ACTION_RESTRICTION','cancel ground jump, push(DDD), knockback event',binary=['Trapped active']),c('NET_CUT','sword plus direct living and message mob/player/goety.summon',binary=['matching source message','main-hand swords tag'])],[FX,TG,'common/entities/projectile/NetEntity',SK,EV,'mixin/EntityMixin','mixin/LivingEntityMixin','common/network/client/CSetDeltaMovement','common/network/server/SRepositionPacket'],['royalvariations:trapped','royalvariations:net'], 'Net saves Warmup/ActiveTick/LifeSpan/Target/Owner UUID; active effect saved independently. Position packets complement server authority; no separate permanent freeze state.')
timebomb=add('time_bomb','Time Bomb','CUSTOM_STATUS','Royal Creeper Knighting gives Enemy Mobs around its target TIME_BOMB100/0. First applicable addition while alive and no existing effect queues in-memory UUID/level task; checker runs before tick increment, detonates when counter>=83 and effect still present. At73 sets flash10. Existing effect reapplication does not queue another task. Removal/entity unload/level mismatch ends task; tasks cleared on server start/stop and are not restored from saved effect alone. Detonation excludes carrier (source entity), RoyalCreeper and creative/spectator; fixed explosion9 to entities within6, even at zero block exposure, then push; Dazed260/0 only Player/IronGolem/player-owned. Hurt failure does not gate push or Dazed. Removes TIME_BOMB. +10% movement per level; blast/timer independent of amplifier.',
    'TNT/explosion and Speed','Custom cancellable-by-effect timer, fixed through-cover damage and independent restricted Dazed; no native TNT block destruction or native Explosion detonate event for this loop.',attrs([('MOVEMENT_SPEED',.1,MT)])+[c('TASK_TIMER','check counter>=83 while effect exists',{'fuse':83,'flash_tick':73},['effect remains','entity available in stored level']),c('FIXED_EXPLOSION_DAMAGE','hurt(ownerless minecraft:explosion,9), radius6',{'damage':9,'radius':6},['not carrier/RoyalCreeper','not creative/spectator']),c('EXPOSURE_PUSH','(oldVelocity+unitAway*((1-distance/6)*exposure)*(1-explosionKR))*(max(0,1-KR))',binary=['LivingEntity','hurt return ignored']),c('DEBUFF_FOLLOWUP','Dazed260/0 to MobUtil.notMonsterOrAnimal',{'dazed_duration':260})],[FX,EV,EV+'$TimeBombTask',EV+'$TimeBombTask$1','common/events/TimedEvents',CR+'$KnightingGoal','utils/CustomExplosion','utils/MobUtil'],['royalvariations:time_bomb'], 'Active effect saved; ArrayDeque task state not persisted, no queue reconstruction in LivingEffects. Applicable event side effects occur before final application result.')
gaze=add('pressing_gaze','Pressing Gaze','CUSTOM_STATUS','Royal Enderman gives400/0 to living owner of a non-projectile/non-potion incoming source after super.hurt regardless return; clean-water potion owner gets it before parent hurt. Looking-player goal refreshes400/0 while gaze dot>1-.025/distance and LOS, subject to native head-item anger suppression. First applicable gaze on live target without existing gaze adds actual Darkness80/0 independently of final gaze admission. GazeGoal priority0 added to vanilla EnderMan at join, AABB20/distance16/nonallied, ignores LOS; target continuation is native. RoyalEnderman is not an EnderMan subclass. Gaze also admits nonplayers to native end-splash/anvil target gates. Purple outline color is set, but unlike Mark no isCurrentlyGlowing override is added for Gaze itself.',
    'Darkness and Enderman anger/targeting','Persistent cross-entity target/admission marker; Darkness is a separate native instance and does not define full Gaze behavior.',[c('TARGET_MARKER','400 ticks; native EnderMan target selection range16',{'duration':400,'range':16},['royal source reaction/look','target predicates']),c('DARKNESS_ADMISSION_SIDE_EFFECT','add Darkness80/0 when no existing Gaze',{'darkness_duration':80},['Applicability event','live target']),c('SECONDARY_ELIGIBILITY','Gaze admits nonplayer to splash/anvil',binary=['hasEffect PRESSING_GAZE'])],[FX,EN,EN+'$EndermanLookForPlayerGoal',EV,'common/entities/ai/GazeGoal','mixin/EntityMixin'],['royalvariations:pressing_gaze'])
heavy=add('heaviness_of_the_end','Heaviness of the End','VANILLA_LIKE_EXTENDED','Movement and NeoForge swim speed each -40%*(amp+1) total multiplier. getJumpPower result*.75 independent of amplifier; server LivingFallEvent adds.2 to event damage multiplier, also amplifier independent. Anvil successful indirectMagic8 gives140/0 normally or200/0 for player-owner nonpet branch; player pearl successful indirectMagic7 gives140/0; successful RoyalEnderman teleport burst indirectMagic4 gives80/0.',
    'Slowness and fall/jump attributes','Slowness does not multiply jump power, add fall-event multiplier or independently modify NeoForge swimming.',attrs([('MOVEMENT_SPEED',-.4,MT),('neoforge:swim_speed',-.4,MT)])+[c('JUMP_REDUCTION','getJumpPower*.75',{'factor':.75}),c('FALL_MULTIPLIER','incoming event multiplier+.2',{'added_multiplier':.2})],[FX,'mixin/LivingEntityMixin',EV,AN,PE,EN],['royalvariations:heaviness_of_the_end'])
for e in [fort,bless,dazed,rush,chosen,marked,trapped,timebomb,gaze,heavy]:e['effect_lifecycle']=LIFECYCLE

resist=add('resistance','Native spawn Resistance','VANILLA_DIRECT','Royal Zombie finalizeSpawn adds actual minecraft:resistance40/2 (60% native damage reduction unless bypass-resistance/effects tag). No distinct custom resistance formula.', 'Resistance III','Only producer/duration differ.',[c('NATIVE_RESISTANCE','max(0,damage*(25-5*(amp+1))/25)',{'duration':40,'amplifier':2},relation='VANILLA_DIRECT')],[ZO],['minecraft:resistance'])
dark=add('darkness','Native Gaze Darkness','VANILLA_DIRECT','Gaze first-applicability handler adds actual Darkness80/0. Native Darkness fog blends toward15 with22-tick blend; amplifier does not alter this fog function. Curing/removing Gaze does not itself remove Darkness.', 'Darkness','Literal vanilla holder; separate instance from Gaze.',[c('NATIVE_DARKNESS','Darkness80/0',{'duration':80,'amplifier':0,'fog_distance':15,'blend_ticks':22},relation='VANILLA_DIRECT')],[EV],['minecraft:darkness'])
arrow=add('royal_arrow_delivery','Royal Arrow collision and knockback','VANILLA_LIKE_EXTENDED','Royal Arrow inherits Arrow hit/damage and potion post-hurt behavior. Special knockback seeds EnchantmentHelper.modifyKnockback with2 instead of vanilla0 when weapon exists on server; horizontal normalized velocity*modifiedSeed*.6*max(0,1-KR), Y=.1 when vector nonzero. Collision excludes owner/allies, but owner Mob current target returns to parent before allied rejection. No weapon means seed0. Marking defaults true; ArrowItem.createArrow sets false; RoyalBow.customArrow sets true only for RoyalArrow; dispenser asProjectile retains true. Marking saved as Marking; critically flagged native damage remains, only tick crit particles suppressed.',
    'Arrow and Punch','Additional base knockback seed2 and allied collision rules; Mark enablement is producer-specific. Ordinary baseDamage2.4 is context, not a separately counted effect.',[c('KNOCKBACK_SEED','modifyKnockback(weapon,2) vs native0',{'seed':2,'horizontal_scale':.6,'vertical':.1},['weapon','server','hurt success']),c('COLLISION_ADMISSION','exclude owner/allies except current Mob target',binary=['native collision predicates']),c('MARK_ENABLE','Bow customArrow true; ArrowItem create false; dispenser default true',binary=['RoyalArrow concrete class'])],[AR,'common/items/RoyalBowItem','common/items/RoyalArrowItem','mixin/AbstractArrowMixin'],['royalvariations:royal_arrow','royalvariations:royal_bow'])
bomb=add('royal_bomb','Royal Bomb fuse, blast and Dazed delivery','VANILLA_LIKE_EXTENDED','Item throws at speed.8/inaccuracy1, consumes1 unless creative, cooldown40. Entity collision requests native thrown.5 on LivingEntity; impact spawns RoyalBomb regardless hurt result (entity impact Y+1). Bomb constructor fuse40; type default80. Bomb is invulnerable/unattackable, discards then server explodes radius9 TNT interaction. Native damaging reach18. Separate CustomExplosion radius19 applies Dazed200/0 only, no second hurt/push; exposure computed but does not gate effect, ignoreExplosion still gates. All noncreative/nonspectator LivingEntity recipients, including owner/allies. Bomb is LivingEntity source, so explosion owner is bomb itself, not its getOwner thrower field.',
    'Thrown projectile, TNT, Slowness-like debuff','Native explosion plus separate wider through-cover status shell and invulnerable Mob fuse entity.',[c('THROWN_CONTACT','hurt(thrown,.5) then spawn bomb regardless result',{'contact_damage':.5,'cooldown':40,'speed':.8}),c('BOMB_FUSE','40 ticks thrown spawn; default80; saved short Fuse',{'fuse':40,'default':80},['unconditional damage immunity']),c('NATIVE_BLAST','Level.explode power9/TNT; player_explosion identity with bomb owner',{'power':9,'native_reach':18},relation='VANILLA_DIRECT'),c('DEBUFF_SHELL','Dazed200/0 within19 independent of hurt/exposure',{'radius':19,'duration':200},['ignoreExplosion respected'])],['common/items/RoyalBombItem','common/entities/projectile/RoyalBombProjectile',BZ,BZ+'$1','utils/CustomExplosion'],['royalvariations:royal_bomb','royalvariations:royal_bomb_projectile'])
creeper=add('royal_creeper_detonation','Royal Creeper detonation package','VANILLA_LIKE_EXTENDED','Swell max45; fall adds int(distance*1.5), capped maxSwell-5 after parent fall. Priming applies movement-.4 ADD_MULTIPLIED_TOTAL transient modifier; clears outside priming. Lightning marks powered. Server detonation native MOB explosion power6 or12 powered; separate Dazed300/0 shell12 or24, independent of damage/cover. Discards and creates native AreaEffectCloud of active effects, radius2.5, radiusOnUse-.5, wait10,duration300,radiusPerTick-2.5/300. Custom effect instances are copied without quarter-duration reduction (that reduction applies base potion effects). Native cloud scans every5 and reapplication delay20, no custom Royal damage type.',
    'Creeper, charged Creeper and lingering effect cloud','Larger power/fuse, priming speed modifier and independent Dazed shell. Existing effect propagation uses vanilla cloud.',[c('FUSE_AND_PRIMING','45 swell; movement total-.4 while priming',{'swell_max':45,'move_coefficient':-.4,'fall_swell_factor':1.5}),c('NATIVE_CREEPER_BLAST','power6*(powered?2:1)',{'power':6,'powered_factor':2},relation='VANILLA_DIRECT'),c('DAZED_SHELL','12*(powered?2:1), Dazed300/0',{'radius':12,'duration':300}),c('NATIVE_CLOUD','copy current effects;radius2.5;wait10;duration300',{'radius':2.5,'wait':10,'duration':300,'use_radius':-.5,'reapplication':20},relation='VANILLA_DIRECT')],[CR,CR+'$1',CR+'$RoyalSwellGoal','utils/CustomExplosion'],['royalvariations:royal_creeper'])
anvil=add('spectral_anvil','Spectral Gauntlet / Spectral Anvil','VANILLA_LIKE_EXTENDED','Incoming damage to alive noncreative/nonspectator victim: living source owner Player with equipped Curios spectral_gauntlet, nonally, no cooldown and randomFloat<=.15 spawns anvil at victim+(max heights+1)Y; successful spawn adds cooldown140. Not restricted to melee and no hurt-success gate. Enderman AnvilGoal: target LOS, ownHP<=85%max, knightCool0, cast20 summons at countdown10, stop cooldown180. Anvil hovers15 ticks Player owner or20 otherwise then accelerationY-.25/tick. Direct sweep collision invokes damageTargets; impact while dropping also scans AABB4, so same entity may receive two hurt attempts, native cooldown remains. Eligible nonallied: Player owner/non-own-pet -> duration200; else Player target or Gaze ->140. Successful indirectMagic8 alone adds Heaviness. Does not use falling_anvil damage type.',
    'Indirect magic and falling entity geometry','Custom proc, hovering/sweep/AABB and recipient rules; magic armor bypass differs from vanilla falling-anvil damage. Gauntlet +2 BLOCK interaction range is utility, not entity reach.',[c('ACCESSORY_PROC','random<=.15; cooldown140 on spawn success',{'chance':.15,'cooldown':140},['Curios Player equipment','living incoming source owner Player']),c('FALLING_SPELL','hover15/20 then deltaY-=.25',{'player_hover':15,'other_hover':20,'gravity':.25,'AoE':4}),c('MAGIC_DAMAGE','hurt(indirect_magic,8); success then Heaviness',{'damage':8,'player_duration':200,'other_duration':140},['native hurt result'])],[EV,AN,EN+'$AnvilGoal','utils/CuriosFinder','common/items/GloveItem'],['royalvariations:spectral_gauntlet','royalvariations:spectral_anvil'])
pearl=add('royal_pearl','Royal Ender Pearl combat arrival','VANILLA_LIKE_EXTENDED','Use speed1.5/inaccuracy1/cooldown20, consume1 unless creative. Contact calls thrown0; arrival does not depend on contact hurt. Valid alive/awake owner (crossdimension portal permission) is dismounted; ServerPlayer accepting messages uses cancellable EnderEntity teleport event, changeDimension to event target, resets fall. Afterwards enemies nonallied within projectile AABB4 get indirectMagic7; hurt success gives Heaviness140/0. No LOS filter, self teleport damage or endermite spawn. Nonplayer owner branch teleports/resets fall only; no combat burst. Burst centered on projectile even if event retargets owner.',
    'Vanilla Ender Pearl','Vanilla pearl self fall damage5 and random endermite branch are absent; native Royal magic arrival AoE and different cooldown/event path.',[c('TELEPORT_ADMISSION','valid owner; Player connection and uncancelled EnderEntity event',{'cooldown':20},['owner permission']),c('ARRIVAL_MAGIC','projectile AABB4; Enemy nonally; indirect_magic7 then Heaviness140',{'box':4,'damage':7,'duration':140},['Player owner branch','hurt success'])],[PE,'common/items/RoyalEnderPearlItem','utils/MobUtil'],['royalvariations:royal_ender_pearl'])
endsplash=add('enderman_splash','Royal Enderman teleport splash','VANILLA_LIKE_EXTENDED','Royal Enderman valid-ground nonwater teleport posts EnderEntity event and requires randomTeleport success. At destination AABB4 nonallied Player OR Gaze holder receives indirectMagic4, then Heaviness80/0 only if hurt succeeds. No LOS or spherical range filter. Random/chase/defensive/daylight teleports all share this path.',
    'Enderman teleport and indirect magic','Vanilla Enderman teleport has no damaging arrival splash.',[c('TELEPORT_SPLASH','successful teleport -> AABB4 indirect_magic4 -> Heaviness80/0',{'box':4,'damage':4,'duration':80},['valid ground','not water','event accepted','teleport true','target Player or Gaze'])],[EN,'utils/MobUtil'],['royalvariations:royal_enderman'])
evade=add('skeleton_evasion','Royal Skeleton evasive leap and net spawn','CUSTOM_CONTROL','Before super.hurt: netCool<=0, Living source owner within6, nonallied/noncreative/nonspectator -> turn toward attacker, set velocity using normalized skeleton-(attacker+(0,1.5,0)): x/z*2, Y=max(.2,-normalizedY*.6+.2 when -normalizedY*.6>0); spawn lifespan50 Net at attacker, cooldown220. No successful damage gate. netCool decrements server ticks, not saved by RoyalSkeleton override.',
    'Native velocity and trapped terrain','Reactive escape/entangle combo not a vanilla skeleton effect; net recipient may be immune even though leap/spawn occurs.',[c('SELF_LEAP','horizontal2*normalized away; Y conditional .2 minimum',{'horizontal':2,'vertical_scale':.6,'min_vertical':.2,'range':6,'cooldown':220}),c('NET_SPAWN','spawn native net at attacker lifespan50',{'lifespan':50},['before parent hurt return'])],[SK,TG],['royalvariations:royal_skeleton'])
knight=add('zombie_knighting','Zombie Knighting equipment/target package','CUSTOM_RESOURCE','Royal Zombie with target and knightCool0 scans Zombie AABB10; removes only when BOTH no LOS to royal AND allied to royal target (do not strengthen this predicate). Every-tick cast starts16 and at countdown1 gives empty head Royal Knight Helmet, empty main hand iron sword or axe at random<=.25, Fortitude400/0 and sets target to royal target. Existing gear not replaced. stop cooldown100; equipment persists natively; inherited BlessCool is saved.',
    'Native equipment slots and mob target assignment','Custom ally equipment grant/cast/cooldown package; ordinary item combat stats remain native.',[c('EQUIPMENT_GRANT','empty helmet and mainhand only; axe25%, otherwise sword',{'box':10,'cast':16,'cooldown':100,'axe_chance':.25},['royal has target','empty slot']),c('TARGET_ASSIGNMENT','setTarget(royal target)',binary=['selected Zombie'])],[ZO+'$KnightingGoal','common/entities/hostile/RoyalMonster'],['royalvariations:royal_zombie'])
power=add('skeleton_knighting','Skeleton Knighting Power II','VANILLA_LIKE_EXTENDED','Royal Skeleton target + knightCool0 scans AbstractSkeleton AABB14. Removal predicate is conjunction: no LOS AND enchanted mainhand AND !c:tools/bow AND allied to royal target. Cast6 decremented everytick reaches1: if c:tools/bow and unenchanted, enchant actual minecraft:power2, then all selected skeletons receive target. stop cooldown300. Native Power adds1+level*.5 to arrow damage base: level2 adds2 before velocity/critical damage. Royal Bow is in c:tools/bows resource; exact loader TOOLS_BOW tag ID must be read, not inferred from singular constant.',
    'Power enchantment','Literal native Power II with custom producer/target coordination; not a custom attack multiplier.',[c('POWER_ENCHANTMENT','Power2 on unenchanted native bow-tag item',{'level':2,'base_damage_added':2,'box':14,'cast':6,'cooldown':300},['correct tag','unenchanted']),c('TARGET_ASSIGNMENT','selected skeleton target=royal target',binary=['selected AbstractSkeleton'])],[SK+'$KnightingGoal','common/entities/hostile/RoyalMonster'],['royalvariations:royal_skeleton','minecraft:power'])
summon=add('zombie_escort','Royal Zombie spawn escort','VANILLA_LIKE_EXTENDED','Royal Zombie finalizeSpawn creates two native Zombies at +/-2 X, calls their finalizeSpawn MOB_SUMMONED and adds them. No custom ownership or shared HP; native zombie descendants fight through their own goals. Royal spawn Resistance is a separate literal holder.',
    'Native Zombie entities','Custom two-entity escort spawn, not a buff on the royal.',[c('ENTITY_SUMMON','two native Zombie at X+/-2',{'count':2,'offset':2},['RoyalZombie finalizeSpawn'])],[ZO],['royalvariations:royal_zombie','minecraft:zombie'])
crown=add('crown_conversion','Spiritual Crown conversion pause','VANILLA_LIKE_EXTENDED','Server interact on alive nonflashing Zombie/AbstractSkeleton/Creeper/EnderMan consumes1 crown (no creative exemption), queues conversion task, flash10. While task waits, navigation stopped and strafe0. When flashing clears, Mob.convertTo corresponding Royal type,true; copies supported native equipment/state through convertTo, no custom HP preservation. Task not saved, cleared on server stop. Existing RoyalMonster subclasses do not satisfy those four vanilla class tests.',
    'Mob conversion','Custom item-triggered delayed conversion and navigation pause; not a vanilla mob potion.',[c('DELAYED_CONVERSION','flash10 then convertTo(royalType,true)',{'flash':10,'consumed':1},['alive','not flashing','one of four vanilla classes']),c('NAVIGATION_PAUSE','stop navigation/strafe0 while task waits',binary=['in-memory task'])],['common/items/SpiritualCrownItem','common/items/SpiritualCrownItem$ConversionTask','common/events/TimedEvents'],['royalvariations:spiritual_crown'])
defense=add('enderman_native_defense','Royal Enderman native defense/anger','VANILLA_EQUIVALENT','Copies vanilla Enderman projectile/potion admission: initial invulnerability check; clean water can hurt, other projectile/potion bypass parent damage and try64 teleports, returning true upon successful teleport. Nonprojectile parent hurt followed by90% teleport if source has no living owner. Water sensitive, persistent anger20..39s, target gives movement+.15 ADD_VALUE and clears when target null. Added Gaze and damaging teleports are separately cataloged extensions, not attributed to this shared defense primitive.',
    'Enderman native damage admission, water sensitivity and anger speed','For this isolated native defense primitive no new damage rule; Royal producer class differs. Gaze/splash are separate packages.',[c('ENDERMAN_ADMISSION','projectile branch64 teleport attempts; clean water admitted',{'attempts':64,'ownerless_teleport_chance':.9},['native invulnerability','projectile or ThrownPotion']),c('ANGER_SPEED','movement+.15 ADD_VALUE while target set',{'coefficient':.15,'anger_min_seconds':20,'anger_max_seconds':39},['target exists'])],[EN],['royalvariations:royal_enderman'])
allies=add('royal_target_rules','Royal native alliances and target vetoes','BINARY_MECHANIC','Royal Zombie/Skeleton/Creeper/Enderman treat corresponding vanilla Zombie/AbstractSkeleton/Creeper/EnderMan as allies when both teams absent, or self; otherwise parent rules. Creeper rejects Goat setTarget; RVEvents redirects IronGolem target RoyalCreeper to null. RoyalArrow and bomb/net/splash use their own MobUtil bidirectional alliance predicate described per path. These are source/recipient combat rules, not status cures.',
    'Teams and target eligibility','Royal-specific class alliance and target exclusions.',[c('TARGET_ELIGIBILITY','class/team tests; Goat and IronGolem/RoyalCreeper vetoes',binary=['concrete recipient classes','no teams for native class ally'])],[ZO,SK,CR,EN,EV,'utils/MobUtil'])
infection=add('zombie_villager_infection','Royal Zombie native villager infection','VANILLA_DIRECT','On killed Villager, Normal50% or Hard100%, subject to canLivingConvert, calls convertTo(ZombieVillager,false), finalizeSpawn(CONVERSION) and copies villager data/gossip/offers/XP; onLivingConvert event. Same vanilla Zombie infection mechanics.', 'Zombie Villager infection','Royal Zombie producer class; no distinct infection status or damage type.',[c('NATIVE_INFECTION','Normal50%/Hard100%; conversion veto respected',{'normal_chance':.5,'hard_chance':1},relation='VANILLA_DIRECT')],[ZO],['minecraft:zombie_villager'])

# Distinct legitimate producers and admission cases; effect instances remain packages.
p('armor_self',[fort],['ARMOR_PROC'],'Four royalvariations:royal_knight armor pieces','Incoming damage at currentHP<=40%; wearer400/0, no Fortitude. Material identity and four humanoid armor slots.',[EV,'utils/ItemHelper'])
p('armor_pets',[fort],['ARMOR_PROC','AOE'],'Royal Knight full set + owned LivingEntity','Same proc, pets whose owner==wearer in point AABB5.5 get400/1.',[EV])
p('staff_self',[bless],['ACTIVE_ITEM'],'royalvariations:royal_staff','Native use self400/0; cooldown300 and durability1. No mainhand-only check.', ['common/items/RoyalStaffItem'])
p('staff_pets',[bless],['ACTIVE_ITEM','AOE'],'royalvariations:royal_staff + ownable pets','Own pets in AABB13 get600/1.', ['common/items/RoyalStaffItem'])
p('royal_bow_arrow',[arrow,marked],['PROJECTILE'],'royalvariations:royal_bow + royalvariations:royal_arrow','Real native bow/customArrow and successful Arrow post-hurt; Player owner Mark300/0, no recruitment.',[AR,'common/items/RoyalBowItem','common/items/RoyalArrowItem'])
p('other_bow_arrow',[arrow],['PROJECTILE'],'minecraft:bow or crossbow + royalvariations:royal_arrow','ArrowItem.createArrow marks false; no RoyalBow customArrow. Preserve weapon-dependent knockback.',[AR,'common/items/RoyalArrowItem'])
p('dispenser_arrow',[arrow,marked],['PROJECTILE'],'Dispenser + royalvariations:royal_arrow','ArrowItem.asProjectile leaves default marking true, no weapon, owner absent; amp1 unless recipientPlayer. Nonplayer-owned recruitment branch can run.',[AR,'common/items/RoyalArrowItem'])
p('skeleton_arrow',[arrow,marked],['PROJECTILE','MOB_ATTACK'],'royalvariations:royal_skeleton','Native ranged constructor supplies RoyalBow weapon, marking true; target/MobUtil gate, amp0 onPlayer else1; recruitment preserved.',[SK,AR])
p('zombie_melee',[chosen],['MELEE','MOB_ATTACK'],'royalvariations:royal_zombie','Successful native parent melee -> ChosenVictim400/0.',[ZO])
p('chosen_goal',[chosen,rush],['PASSIVE_AURA','OTHER'],'ChosenVictim carrier + native undead Mob','Priority0 goal added at join only if no owner; find target/amp inheritance; target tick modulo40.',[EV,'common/entities/ai/ChosenVictimGoal'])
p('bomb_throw_contact',[bomb],['THROWN_PROJECTILE'],'royalvariations:royal_bomb','Native thrown impact .5 on living target, fuse entity spawned regardless damage result.', ['common/items/RoyalBombItem','common/entities/projectile/RoyalBombProjectile'])
p('bomb_detonation',[bomb,dazed],['EXPLOSION','AOE'],'royalvariations:royal_bomb','Let native fuse40 expire: native TNT power9 then separate radius19 Dazed200.',[BZ,BZ+'$1','utils/CustomExplosion'])
p('creeper_detonation',[creeper,dazed],['EXPLOSION','MOB_ATTACK'],'royalvariations:royal_creeper','Native swelling reaches45; power6 and Dazed300 within12; powered subtype doubles both radii.',[CR,CR+'$1'])
p('creeper_cloud',[creeper],['AOE'],'Royal Creeper carrying legitimate active effects','Native detonation emits copied-effect cloud; any present holder retains its implementation, not proof of a direct producer for all registry effects.',[CR])
p('creeper_knighting',[timebomb],['MOB_ATTACK','AOE'],'Royal Creeper + enemy Mob near its target','Not swelling, knightCool0, enemy non-RoyalCreeper in target AABB6, nonally to target and LOS royal; cast16 reaches1 applies100/0, stopcool350.',[CR+'$KnightingGoal'])
p('time_bomb_task',[timebomb,dazed],['EXPLOSION','AOE'],'Enemy Mob legitimately marked by Royal Creeper','Effect stays present through in-memory counter83. Ownerless explosion9 radius6 and restricted Dazed260/0; carrier excluded.',[EV+'$TimeBombTask',EV+'$TimeBombTask$1','utils/CustomExplosion','common/events/TimedEvents'])
p('skeleton_counter_net',[evade,trapped],['MOB_ATTACK','OTHER'],'royalvariations:royal_skeleton + nearby living attacker','Incoming source owner within6 triggers before hurt result. Net life50, secondary maxHP/boss/effect gates.',[SK,TG])
p('net_cut',[trapped],['MELEE'],'minecraft sword-tag weapon + native Royal net','Direct LivingEntity and message mob/player/goety.summon discards net before hurt return.', ['common/entities/projectile/NetEntity'])
p('gauntlet_proc',[anvil],['ACCESSORY_PROC'],'royalvariations:spectral_gauntlet in Curios + Player-owned hit','Native incoming event; melee or any source with Player owner can pass. Chance<=.15/cool140.',[EV,'utils/CuriosFinder'])
p('enderman_anvil_cast',[anvil],['MOB_ATTACK','SUMMONED_ATTACK'],'royalvariations:royal_enderman','Target has LOS; HP<=85%, knightCool0, cast reaches10; cooldown180 onstop.',[EN+'$AnvilGoal'])
p('anvil_direct',[anvil,heavy],['PROJECTILE','SUMMONED_ATTACK'],'Native spectral anvil from gauntlet or Royal Enderman','Sweep entity contact calls damageTargets regardless isDropping; indirectMagic8 -> Heaviness200 player-owner or140 normal eligible branch.',[AN])
p('anvil_splash',[anvil,heavy],['AOE','SUMMONED_ATTACK'],'Native dropping spectral anvil','On impact while dropping, AABB4 scan calls same damage method; overlap with direct hit still subject to native cooldown.',[AN])
p('pearl_arrival',[pearl,heavy],['THROWN_PROJECTILE','OTHER'],'royalvariations:royal_ender_pearl','Player-owner successful permitted native teleport; projectile-centered AABB4 Enemy-only magic7 ->140.',[PE,'common/items/RoyalEnderPearlItem'])
p('enderman_arrival',[endsplash,heavy],['OTHER','AOE'],'royalvariations:royal_enderman','Successful random/chase/defensive/daylight teleport, destination AABB4 Player/Gaze magic4 ->80.',[EN])
p('gaze_hurt',[gaze,dark],['OTHER'],'royalvariations:royal_enderman + living nonprojectile attacker','Post-super.hurt marker regardless return, except initial invulnerability rejection.',[EN,EV])
p('gaze_water',[gaze,dark],['THROWN_PROJECTILE'],'minecraft splash water potion + Royal Enderman','Clean water owner marker before super hurt; projectile branch still attempts64 teleports.',[EN,EV])
p('gaze_look',[gaze,dark],['PASSIVE_AURA'],'Royal Enderman + looking Player','Native dot/LOS/head suppression and goal cadence, Gaze400/0; Darkness only absent-Gaze applicability branch.',[EN,EN+'$EndermanLookForPlayerGoal',EV])
p('gaze_target',[gaze],['OTHER'],'Gaze carrier + vanilla Enderman','Joined vanilla EnderMan GazeGoal priority0, ignore LOS,distance16. RoyalEnderman not subclass recipient of join-added goal.',[EV,'common/entities/ai/GazeGoal'])
p('zombie_knighting',[knight,fort],['MOB_ATTACK','AOE'],'Royal Zombie + nearby vanilla Zombies','Cast equipment/target and Fortitude400/0; exact conjunctive filter preserved.',[ZO+'$KnightingGoal'])
p('skeleton_knighting',[power],['MOB_ATTACK','AOE'],'Royal Skeleton + vanilla AbstractSkeleton with unenchanted bow-tag item','Cast native PowerII and targets; exact conjunctive exclusion retained.',[SK+'$KnightingGoal'])
p('zombie_spawn',[summon,resist],['SUMMONED_ATTACK','OTHER'],'royalvariations:royal_zombie natural/spawn-egg finalizeSpawn','Actual finalizeSpawn path, not bare entity construction: Resistance40/2 and2 native Zombies.',[ZO])
for key in ['zombie','skeleton','creeper','enderman']:
    p('crown_'+key,[crown],['ACTIVE_ITEM'],'royalvariations:spiritual_crown + minecraft:'+key,'Native interact/conversion task to corresponding Royal type; preserve concrete conversion class case.', ['common/items/SpiritualCrownItem','common/items/SpiritualCrownItem$ConversionTask'])
p('enderman_defense',[defense],['OTHER'],'royalvariations:royal_enderman','Native incoming projectile/potion/nonprojectile branches and target transition; additional Gaze/splash linked separately.',[EN])
p('native_alliances',[allies],['OTHER'],'Royal four mob classes + corresponding vanilla classes','Concrete pair/team predicates, plus Goat and IronGolem target veto cases.',[ZO,SK,CR,EN,EV])
p('villager_kill',[infection],['MELEE','MOB_ATTACK'],'Royal Zombie + native Villager','Normal/Hard legitimate native kill and conversion eligibility.',[ZO])

def write_partial():
    doc=dict(schema='tno.external_effects.partial_draft.v1',baseline=BASELINE,mod_key='royalvariations',status='PARTIAL',checkpoint='R2d1-partial',starting_sha=START,semantic_coverage_complete=False,promoted_to_catalog=False,effects=E,paths=P,
        named_native_effects=[e['registry_ids'][0] for e in E[:10]],remaining=['Finish targeted comparison/loader/tag witnesses, native source/inheritance coverage and exclusions; match compatible generic hooks; validate/promote final Royal review and matrices.'],**boundary_flags())
    write_json(OUT/'partial-drafts/royalvariations-r2d1-partial.json',doc)
    print('Saved Royal semantic draft',len(E),'packages',len(P),'paths')

if __name__=='__main__':write_partial()
