"""Preserve the bounded Cult of Azazel continuation; deliberately not a completion assembler."""
import tomllib
from catalog_common import *
from native_evidence import collect
from assemble_batch import refresh

CHECKPOINT='R2c2'
PROTECTED='2d1022ddb1c6436c0dd2142ee88c764bc8aed4c1'
assert git('branch','--show-current')=='external-effects-catalog-research'
assert git('rev-parse','HEAD')==PROTECTED, 'Historical saver: do not replay after its checkpoint.'
assert not (OUT/'partial-notes/cultofazazel-r2c2.json').exists(), 'Never overwrite a protected partial checkpoint.'

findings=[]
def note(name, fact, sources, pending=None):
    findings.append(dict(name=name,fact=fact,source_witness_ids=sources,
        status='NATIVE_STATIC_PARTIAL',pending=pending or 'Final vanilla comparison, classification, package decomposition and source/delivery assembly remain pending.'))

note('Azazel shield, admission and terminal state',
    'AzazelEntity.hurt returns false on client, IN_WALL, attack states 7..10, and state 2. Before normal super.hurt it tests currentHealth-rawAmount <= maxHealth*0.05 and starts state-9 death cinematic, returning false. This is an incoming-amount threshold before ordinary mitigation, not measured HP damage or a 5%-HP subtraction. A LivingEntity source owner increments hitCounter before super.hurt success is known; threshold is uniformly sampled inclusively between sorted SHIELD_HITS_MIN/MAX (defaults 5..20). At threshold while state 0, counter resets, a new threshold is sampled, state 2 lasts attackTimer=100 and heal(20) is requested. The triggering hit still delegates to super.hurt. State-9 tick 200 creates loot/barrel and discards the boss without an explosion damage call. HitCounter/MercyTick/PhaseState/TotalAttacks/HasOfferedMercy are saved; attack state/timer, next threshold, prison list and Midas tracker are not saved by the shown overrides.', ['coa2-azazel'])
note('Azazel native attack scheduling and mercy control',
    'Aggro starts from a qualifying hurt path or nearby Player with vanilla BAD_OMEN (AABB inflate 30). Idle aggro with target uses 1/ATTACK_CHANCE per entity tick (default 80); after five chosen attacks it offers mercy once. A close-player AABB using MELEE_ATTACK_RADIUS (default 6) and random 0..99 < MELEE_ATTACK_CHANCE (30) selects Launch/Midas equally; otherwise Wind/Wheel/Arrow/Pull/Prison, plus Pray only with Believer in AABB40, are uniformly selected. Phase thresholds <=50% and <=25% set synchronized phase state; the shown attack formulas do not use phase. Mercy state6 clears target/navigation; timeout >284 entity ticks returns to aggro, or iron/diamond/netherite sword/axe interaction consumes one unless creative and enters state7. State7 tick76 enters state8; state8 forces Player lookAt boss eyes within AABB30 until tick40 then discards. Travel sets boss velocity ZERO in state2 or any state>=6. This is real forced orientation during a cinematic, separate from cosmetic subtitles.', ['coa2-azazel'])
note('Azazel Wind/Pull/Launch/Wheel: four distinct control deliveries',
    'All use native mobAttack(this), with no custom DamageType and no check of hurt return before their velocity effects. Wind state1 timer60: every active call Player AABB20 receives currentVelocity + (0.8*normalizedAway.x,0.2,0.8*normalizedAway.z); at timer30 requests configured damage5. Pull state11 timer60: while timer>15 add horizontal normalizedToward*0.6 to Player AABB20; timer15 sets Y velocity1.5 and requests damage5. Launch state12 timer80: timer40 Player AABB5 requests damage8 and sets Y velocity2.5. Its explosion particles/sound do not construct an Explosion. Wheel state3 timer90: timer<=50 with target sets boss horizontal normalizedToward*1.2; every third entity tick Player AABB1 requests damage4 and receives full dashVector*1.5 (including its normalized Y component). Player lists do not explicitly filter creative/spectator or test line of sight in these methods; native hurt eligibility remains downstream.', ['coa2-azazel'])
note('Midas expanding fire ring and inventory replacement',
    'State13 lasts120 entity-tick countdown, tracker cleared on start. Each perform call sets elapsed=120-timer and radius=elapsed/120*30. Players in AABB35 with abs(3D distance-radius)<=1.5 receive native inFire damage request MIDAS_FIRE_DAMAGE (8) and igniteForSeconds(5), without conditioning ignition on hurt success. At distance<=6 each UUID counter increments; reaching MIDAS_GOLD_TIME (40) replaces one uniformly chosen nonempty inventory container slot whose item is not RAW_GOLD with a fresh RAW_GOLD stack of the old count. Original item/components are not preserved. Scanned container size is delegated to vanilla Inventory and needs its own witness before claiming exact slot coverage. Outside6 but within35 resets counter; leaving the scanned AABB does not run that reset. Counters reset after each threshold even when no eligible slot exists. No creative/spectator exclusion in these loops. At timer110 it separately summons either configured StatueBossunit count3 or Guardian count2 on radius4; Guardians get current/fallback target and startSpawning.', ['coa2-azazel'])
note('Azazel prison terrain control',
    'State14 chooses current Player target or nearest Player40, saves its block position, timer=PRISON_DURATION(200). For elapsed10..50 with elapsed%4==0 (actual first12), step=(elapsed-10)/4 creates replaceable ring blocks satisfying round(sqrt(x*x+z*z))==radius (default5). Column maximum is max(3,PRISON_MAX_HEIGHT(6)-abs(x*31+z*17)%4), deterministic per x/z; step<=maxH. After elapsed50, if targetY+1 exceeds recorded highest wall, each call adds up to five layers of GRAND_DOOR_PART on that ring in replaceable cells. No explicit teleport or velocity lock. At expiry/death-cinematic/removal, tracked locations still containing BLACKSTONE_COLUMN or GRAND_DOOR_PART become AIR. Original replaced states are not restored, and locations/timer are not persisted by Azazel save overrides. Removal/world reload behavior needs no fabricated runtime claim.', ['coa2-azazel'])
note('Arrow attack variants and passive summon producers',
    'State4 lasts120; chooses variant0..2. Variant0 at timer100 creates30 ordinary Arrow entities without an owner, at targetY+10 and x/z offsets[-5,5), velocity(0,-1.5,0); no extra potion effects/custom source. Variant1 at timers100/80/60 creates20 native EvokerFangs each, x/z offsets[-1,1), warmup0 and owner Azazel. Variant2 at timer100 creates10 LaserEntity instances on radius7 around boss. Idle aggro passive summon probability1/PASSIVE_SUMMON_CHANCE (600) creates either2 StatueBossunits or4 Statues, x/z offsets[-5,5). These are separate legitimate production paths to native summon attacks, not automatically distinct effects. Inherited Arrow/Fangs and summon callback comparisons remain pending.', ['coa2-azazel'])
note('Believer protection, sickness, healing and death callback',
    'Azazel Pray starts state5 timer180 and calls setProtected(150) on Believers in AABB40. Believer protected boolean causes unconditional false return from hurt before super; server protectedTimer decrements/clears it. Gunpowder interaction sets custom IS_SICK, golden apple clears it, consumes one unless creative. Sick OR praying stops navigation and delegates travel(Vec3.ZERO), but sickness does not gate heal logic. Every20 entity ticks Believer retains current live Azazel if distanceSquared<1600, otherwise selects first in AABB30. A live selected boss receives heal(5) every20 ticks; no aggro, sickness or protected-state gate. On server die, a Player source owner receives vanilla BAD_OMEN36000 amp0 and a Statue is spawned before super.die. All are distinct from the empty ZoneEffect markers.', ['coa2-believer','coa2-azazel'])
note('Guardian rapid melee explicitly clears hurt cooldown',
    'performMeleeAttack reads target, requires distanceSquared<=16 unbuffed/64 buffed, sets target.invulnerableTime=0 then requests mobAttack damage3/8. This is a proven special hit-cooldown bypass by native code, not a new damage identity or bypass of every eligibility rule. GuardianBehaviorGoal uses combo3..5 repetitions, each punchCooldown11 producing calls after decrements at10,6,2; then transition15. Counts are goal.tick invocations, not yet proven entity/server tick intervals. Goal uses no requiresUpdateEveryTick override, so scheduler comparison is required. Entry into combo remains distanceSquared<=16 even when buffed.', ['coa2-guardian','coa2-guardian-goal'])
note('Guardian mega-punch and Welcomer aura',
    'Mega punch requests mobAttack damage10 unbuffed/15 buffed within AABB10/20 and distanceSquared<=100/400. Excludes self, Welcomer, Manipulator, Believer, Guardian, StatueBossunit, Statue and Azazel; remaining LivingEntities receive velocityY+0.9 independent of hurt return. No invulnerableTime reset in this path. Goal enters special if16<distanceSquared<=100, specCooldown0 and random1/20; state5 timer40 calls punch at30 and sets cooldown160 goal invocations. Every10 server entity ticks Welcomer sets IS_CASTING if any Guardian with target in AABB30; every10 Guardian ticks IS_BUFFED becomes whether any nearby Welcomer isCasting. This is a custom boolean range/damage switch, not Strength attribute effect; it does not stack with multiple Welcomers. Guardian death only plays WEAKNESS sound to others, not a Weakness effect.', ['coa2-guardian','coa2-guardian-goal','coa2-welcomer'])
note('Gilded Golem healing pull package',
    'Below/equal25% max HP while alive enters saved IsHealingPhase until full or no candidate ItemEntity/eligible Player in AABB10. Eligible players exclude creative, spectator, dead and recorded creatorUUID. Pull adds horizontal normalizedToward*0.15 to current velocity and sets hurtMarked. Items have priority: first item within distanceSquared<2.5 is discarded as a whole entity (entire stack), heal(4), then no Player branch that tick. Otherwise each player is pulled; distanceSquared<3.5 every20 entity ticks requests native magic damage2 then heal(6), with no hurt-success condition or measured-damage ratio. Separate successful super IronGolem.doHurtTarget adds velocityY0.4; inherited launch must be compared before claiming total knockback. Creator and IsHealingPhase are saved. Every10 ticks while no target/not healing it can target a living recent attacker of a Believer within AABB15, excluding its creator.', ['coa2-golem'])
note('Laser moving magic/fire hazard and immunity',
    'LaserEntity is a Mob with no attack goal, not AbstractArrow. It is unpickable/unpushable, empty knockback/push callbacks, hurt always false, no normal despawn. Each server tick moves by direct setPos: horizontal angle vector*0.15 + perpendicular vector*sin(tickCount*0.3)*0.15, angle perturbed by[-30,30) degrees every10 ticks. Every2 entity ticks alive noncreative Players intersecting its own AABB receive native magic request5, then absolute setRemainingFireTicks(60) without hurt-return check. LifeTicks starts1200, saved; discard requires life<=0 AND tickCount>1200, so saved life alone is not the removal timer after reload. No fabricated projectile source identity.', ['coa2-laser'])
note('Statue Bossunit random vanilla effects',
    'Server attackTimer starts300, decrements until<=0; Player AABB20 nonempty selects independently for each Player one of MOVEMENT_SLOWDOWN/POISON/UNLUCK/WITHER/DARKNESS uniformly and amp0..2 uniformly, duration400, then resets200. Empty scan resets20. No hurt, line-of-sight or creative filter in producer. AttackTimer saved/loaded. Knockback and push(double,double,double) overrides empty. Source is native StatueBossunit, with Azazel Midas/passive spawn and other source producers to finish. Exact downstream effect formulas/admission/merging pending; the names do not imply custom status implementations.', ['coa2-bossunit','coa2-azazel'])
note('Statue observation lock and one-hit state',
    'Each server tick scans all level Players, excluding spectator/dead, and at eye-to-eye distance<64, normalized view dot target direction>0.1 plus player.hasLineOfSight(statue), sets isFrozen. On transition to frozen it stops navigation and resets hasAttacked=false; while observed velocity is multiplied(0,1,0). On unobserved clears frozen. Nested StatueAttackGoal admission/continuation requires !isFrozen && !hasAttacked; its successful scheduling branch calls doHurtTarget then sets hasAttacked=true regardless of hurt return. Thus one attack attempt per released observation cycle. This is custom AI/motion control, not frozenTicks or an applied freeze status.', ['coa2-statue','coa2-statue-goal'])
note('Manipulator mob cast and summon delivery',
    'ManipulatorAttackGoal requires live target; distanceSquared<=225, attackCooldown0, not flee/cast admits cast. If target Player and manipulationCooldown<=0, applies manipulation200 amp0 immediately, sets castTicks75 and manipulationCooldown1200. Otherwise castTicks35 and spawns1..2 native WitherSkeletons at random x/z-3..3 with golden sword/armor, zero drop chances and current target. Unlike the stick summon it writes no SummonerUUID. AttackCooldown resets160 goal invocations (starts40); entity tick independently decrements cast/flee/manipulation counters. Goal nearest distance8..10 navigation and no line-of-sight predicate within cast method. On super.hurt success, HP<=10 once spawns Guardian companion with copied target; flag has no health>0 check there. Other HP40/20 phase changes are cosmetic in shown code; Player hurt above10 sets flee60. Exact scheduler/vanilla WitherSkeleton delivery remains pending.', ['coa2-manipulator','coa2-manipulator-attack'])
note('Manipulator conversion and Ghastly direct death',
    'Convert goal when not casting selects first Villager in AABB10, else Piglin, else Ghastly. Starts castTicks35; at castTicks==1 while target alive creates fresh corresponding prisoner at victim position with numeric MASTER_ID=Manipulator.getId; original Villager/Piglin discarded even if creation null. Does not call native Mob.convertTo or copy original HP/trades/equipment/effects. Ghastly branch instead setHealth(0) then die(native magic source) directly, bypassing its hurt admission; no arbitrary Player execution branch. Prisoner source/reversal and entity-tick versus goal-tick scheduling need completion; do not claim guaranteed successful conversion timing from the counter alone.', ['coa2-manipulator-convert','coa2-prisoner-villager'])
note('Crimson Honey environmental launch',
    'fallOn requests causeFallDamage(distance,0,FALL) for any Entity, even bounce-suppressed; updateEntityAfterFallOn uses super when suppressing bounce, else if velocityY<0 sets velocity(-8*(x-xo), -2*velocityY, -8*(z-zo)) and hurtMarked. entityInside when not suppressing, entityY<blockY+0.9 and abs(x-xo)>0.05 OR abs(z-zo)>0.05 sets(-4*dx,0.6,-4*dz). This is not ordinary Honey slow slide; closest Slime/Honey exact comparison remains. Registration copies HONEY_BLOCK properties, which may carry inherited speed/jump coefficients despite subclassing HalfTransparentBlock; must inspect actual Properties copy before completeness.', ['coa2-honey'])
note('Void block damage and Darkness',
    'VoidCornerBlock.entityInside on server for LivingEntity requests native magic5 then adds vanilla DARKNESS60 amp0, ambient=false particles=false regardless of hurt return. Collision shape empty. VoidMid and VoidMidCorner call sites show the same statements; their individual bytecode is pinned to establish code-proven grouping later. Registry IDs netherman:void_corner, void_mid, void_mid_corner. Nether-suffixed variants are different classes and have not yet been cleared as equivalent.', ['coa2-void-corner','coa2-void-mid','coa2-void-midcorner'])
note('Zone producer correction and non-combat scope',
    'Totemus scans3x3x3 every20 server ticks: blackstone column priority3 clears Fear/Excitement/Faith on Players in blockAABB10; ancient debris2 gives Faith; gold block1 Excitement; default0 Fear. Missing-effect branch removes other markers then adds durationInteger.MAX_VALUE amp0. This is not automatic removal on leaving radius. Azazel aggro every20 ticks adds Anxiety300 amp0 in AABB100; death/mercy transition removes it. Previously pinned ZoneEffect has no gameplay override and client consumer is audio. Native marker exclusion can be finalized after checking all consumers; do not infer fear/stun from names.', ['coa2-azazel'], 'Totemus and client Zone methods are protected in R2c1. Finish caller/consumer coverage without repeating those methods.')
note('Config authority: decompiler static initializer reordering resolved',
    'AzazelConfig.java reading aid misleadingly displays SPEC=BUILDER.build before parameter declarations and groups pushes/pops separately. Actual installed class javap and bytecode show push of Azazel Boss Configuration at offset15 before maxHealth define at38; actual static initializer ordering is the authority. Pinned config witness contains every define and final build. Read-only installed netherman-common.toml snapshot has all listed defaults in named sections. No configuration was changed, no config bug is asserted, and the snapshot is not proof of a running game loaded value.', ['coa2-config'], 'Use bytecode order for registry/config initialization, never reordered decompiler field layout.')
note('Other scoped inspection retained without premature exclusion',
    'AzazelTrophyItem is a fire-resistant stack1 BlockItem implementing Equipable HEAD; no ArmorItem attribute declaration there. CrimsonArrowItem overrides createArrow only, returning shooter constructor; inherited ArrowItem.asProjectile/dispenser behavior remains unresolved, so do not claim dispenser ricochet. CrimsonHoneyBottle registration food nutrition6 saturationModifier0.1 alwaysEdible has no MobEffect food entry. CrimsonWeb is a timed opening block (not Cobweb subclass): staged shapes0..3, connected BFS schedules opening and closing; final combat-scope exclusion needs finish. Traphive contactTimer increments while alive Player intersects blockAABB inflate0.05 and decays1 when absent; threshold10 starts connected opening wave. PointedBlackstone extends PointedDripstone but overrides support chain/placement; inherited fall damage and falling-projectile admission must be traced before saying it is equivalent. EyeBlock copies Honey properties but has no direct hurt/effect callback in its own class. These are explicit resume items, not final classifications.', ['coa2-mask-item','coa2-arrow-item','coa2-web','coa2-traphive','coa2-pointed','coa2-eye'])

classes={
 'azazel':('entity/AzazelEntity',['hurt','travel','tick','startDefenseStun','startDeathCinematic','startMercyPhase','mobInteract','startWindAttack','startWheelAttack','startPrayAttack','startArrowAttack','startPullAttack','startLaunchAttack','startMidasAttack','startPrisonAttack','performPrisonAttack','clearPrison','getHighestPrisonBlock','performMidasAttack','turnRandomItemToGold','performPullAttack','performLaunchAttack','performWindAttack','performWheelAttack','performArrowAttack','handlePassiveSummons','addAdditionalSaveData','readAdditionalSaveData']),
 'believer':('entity/BelieverEntity',['setProtected','hurt','mobInteract','travel','tick','die']),
 'guardian':('entity/GuardianEntity',['tick','performMeleeAttack','performMegaPunch','startSpawning','die']),
 'guardian-goal':('entity/GuardianBehaviorGoal',['<init>','canUse','canContinueToUse','start','tick','stop']),
 'welcomer':('entity/WelcomerEntity',['tick','startSpawning','isPushable','doPush']),
 'golem':('entity/GildedGolemEntity',['tick','performHealingSuck','pullEntity','doHurtTarget','addAdditionalSaveData','readAdditionalSaveData']),
 'laser':('entity/LaserEntity',['<init>','defineSynchedData','tick','hurt','knockback','isPickable','isPushable','push','doPush','addAdditionalSaveData','readAdditionalSaveData']),
 'bossunit':('entity/StatueBossunitEntity',['<init>','<clinit>','tick','knockback','push','addAdditionalSaveData','readAdditionalSaveData']),
 'statue':('entity/StatueEntity',['tick','isBeingLookedAt']),
 'statue-goal':('entity/StatueEntity$StatueAttackGoal',['canUse','canContinueToUse','checkAndPerformAttack']),
 'manipulator':('entity/ManipulatorEntity',['tick','hurt','triggerPhaseEffects','spawnGuardianCompanion','spawnWitherSkeletons']),
 'manipulator-attack':('entity/ManipulatorAttackGoal',['<init>','canUse','tick']),
 'manipulator-convert':('entity/ManipulatorConvertGoal',['canUse','canContinueToUse','start','tick']),
 'prisoner-villager':('entity/VillagerPrisonerEntity',['tick']),
 'honey':('block/CrimsonHoneyBlock',['fallOn','updateEntityAfterFallOn','bounceUpAndBack','entityInside']),
 'void-corner':('block/VoidCornerBlock',['entityInside','getCollisionShape']),
 'void-mid':('block/VoidMidBlock',['entityInside','getCollisionShape']),
 'void-midcorner':('block/VoidMidCornerBlock',['entityInside','getCollisionShape']),
 'config':('config/AzazelConfig',['<clinit>']),
 'mask-item':('item/AzazelTrophyItem',['<init>','getEquipmentSlot']),
 'arrow-item':('item/CrimsonArrowItem',['createArrow']),
 'web':('block/CrimsonWebBlock',['getShape','useWithoutItem','tick']),
 'traphive':('block/entity/TraphiveBlockEntity',['triggerWave','tick','saveAdditional','loadAdditional']),
 'pointed':('block/PointedBlackstoneBlock',['getStateForPlacement','updateShape','canSurvive','destroyChain']),
 'eye':('block/EyeBlock',['<init>','getShape'])
}
specs=[dict(id='coa2-'+key,mod_key='cultofazazel',entry='com/benji/netherman/'+entry+'.class',methods=methods) for key,(entry,methods) in classes.items()]
resume=[
 'Reuse R2b/R2c1/R2c2 partial Cult observations; Variants & Ventures is COMPLETE and must not restart.',
 'Finish remaining Cult class coverage: PiglinPrisoner reversal/persistence, remaining VillagerPrisoner tail, Ghastly immunity/taming/hive path; Blacksmith/Doctor knockback and trade/potion production; block entities, Nether-suffixed void variants, Traphive/Web/GrandDoor/Entrance collision/activation and source producers. Check tags/resources and registration properties, not just direct hurt call sites.',
 'Pin actual vanilla 1.21.1 and installed NeoForge21.1.244 references for ArrowItem bow/crossbow/dispenser creation, Goal scheduler cadence, Inventory container slots, WitherSkeleton/EvokerFangs callbacks, IronGolem launch, Slime/Honey properties, PointedDripstone/falling damage, all reused vanilla effects, fire/death admission and merging/cures. Reuse already pinned shared vanilla/loader witnesses.',
 'Finalize Cult exact registry IDs, package components/one classification per mechanic, numerical/binary flags, source alternatives and distinct delivery cases. Keep raw native versus compatibility modifications separate (pack attribution still UNKNOWN). Only mark COMPLETE when semantic/damage/source/delivery coverage is complete.',
 'Validate, commit, push and verify the next Cult checkpoint before beginning Royal Variations. Remaining targets and R3/R4 stay unfinished.'
]
document=dict(schema='tno.external_effects.partial_notes.v1',baseline=BASELINE,mod_key='cultofazazel',checkpoint=CHECKPOINT,status='PARTIAL',semantic_coverage_complete=False,
    prior_notes=['partial-notes/cultofazazel.json','partial-notes/cultofazazel-r2c1.json'],findings=findings,evidence_specifications=specs,exact_resume=resume,
    caveats=['This preserves native implementation observations, not a finalized count of mechanics.', 'No boss, game, L2 or compatibility runtime was launched.', 'Timers in Goal.tick methods are counted as goal invocations until exact scheduler verification; Entity.tick counters are separate.', 'Damage requests are not measured HP loss; no SHP claim is inferred.', 'Decompiler aids are not initialization-order authority.'],**boundary_flags())
evidence=collect(document)
config_path=MODS.parent/'config/netherman-common.toml'
config_data=config_path.read_bytes()
config_snapshot=dict(schema='tno.external_effects.config_snapshot.v1',baseline=BASELINE,mod_key='cultofazazel',checkpoint=CHECKPOINT,
    path=str(config_path),sha256=byte_hash(config_data),text=config_data.decode('utf-8-sig'),values=tomllib.loads(config_data.decode('utf-8-sig')),
    note='Read-only file snapshot; class defaults and groups pinned separately in coa2-config. Not proof of a live game configuration load.')
write_json(OUT/'config-evidence/cultofazazel-r2c2.json',config_snapshot)
write_json(OUT/'partial-notes/cultofazazel-r2c2.json',document)
write_json(OUT/'native-evidence/cultofazazel-r2c2.json',evidence)
refresh(CHECKPOINT)
decision=read_json(OUT/'research-decision.json')
decision.update(checkpoint=CHECKPOINT,save_mode=True,save_reason='Approaching the owner approximately-80-percent usage threshold; stop new research and protect valid partial Cult work.',
    next_task='Finish Cult of Azazel from partial-notes/cultofazazel-r2c2.json exact_resume; remaining environment/inheritance/vanilla/source coverage. Do not restart completed Variants & Ventures. Then protect Cult completion before Royal Variations. R2/R3/R4 remain unfinished.')
decision['checkpoints']['R2c1']=PROTECTED
decision['checkpoints'][CHECKPOINT]='Self: validated partial Cult continuation and usage-boundary save checkpoint; not Cult or R2 completion.'
write_json(OUT/'research-decision.json',decision)
print(CHECKPOINT, len(findings),'partial observation groups;',len(evidence['witnesses']),'new class witnesses; no added final effect count')
